### ISSUE TITLE
Fix sonar violations not related to tests

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1005]
This ticket is for assessing and fixing all non-test sonar violations.
Either fix in this ticket or create new tickets for the groups of violations.

See:
https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&resolved=false

Break down into separate issues if it makes sense.

**Comment by Pucek9** [comment]
@Xymmer There is some console.warn occurrences, also wrapped specially by functions. Should we get rid of them all?

**Comment by Pucek9** [comment]
@hackergil We have to update sonar configuration for warns but nobody have access

**Comment by Xymmer** [comment]
to bill to talk to gil and tobias, for decision and/or access

**Comment by hackergil** [comment]
For the console.log warnings, I've disabled the rule for typescript. Let me know if I should bring it back.
For the password warnings, we can
* Disable the rule
* Stop scanning the tests
* Other option you can think of

**Comment by Xymmer** [comment]
should we stop scanning the tests for now?
otherwise we need someone to review all the non-test violations and either fix them or create new issues for fixing.

**Comment by Xymmer** [comment]
this ticket is for assessing all non-test violations.
either fix in this ticket or create new tickets for the groups of violations.

**Comment by RadhepS** [comment]
Interpolation warnings - **No fix needed**
- Sonar is assuming that what we did is not intended but it is wrong.

Test warnings - **No fix needed**
- Test warnings are skipped

Image accessibility warning - **Fixed**
- [Issue #3203](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3203)

I will continue to monitor the results periodically.

**Comment by RadhepS** [comment]
Closing ticket as the current errors have been looked at.

Will continue to take a look at Sonar violations periodically.
