### ISSUE TITLE
Fix minor bug sonar violations

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1007]
See
https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&resolved=false&severities=MINOR&types=BUG

**Comment by Pucek9** [comment]
@hackergil Could you look for settings in Sonar for allowing use Angular's '[alt]' attribute for images instead of 'alt'

**Comment by hackergil** [comment]
@Pucek9 Sonar rules cannot be modified in SonarCloud. Also, we cannot make custom rules.

**Comment by kacperknapik** [comment]
https://community.sonarsource.com/t/alt-property-in-angular/4433
@Pucek9 @hackergil - we should probably push them to finally implement this

**Comment by Pucek9** [comment]
https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&pullRequest=1022&resolved=false

Im not sure is it true, but now sonar doesn't find any problems in touched files
