### ISSUE TITLE
Fix critical code smell sonar violations

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1008]
See
https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&resolved=false&severities=CRITICAL&types=CODE_SMELL

Break this one down into smaller tasks or new tickets if it helps spread the love around :)

**Comment by Pucek9** [comment]
Critical smells are done:
https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&pullRequest=1053&resolved=false

Unfortunately changes provided one new major code smell, but it doesn't applicable this ticket

**Comment by kacperknapik** [comment]
sonar errors must be fixed before merging

**Comment by Pucek9** [comment]
> sonar errors must be fixed before merging

@kacperknapik That PR doesn't touch Major Code Smells, for that will be new ticket if @Xymmer decide
