### ISSUE TITLE
Backend: Add a "none" option for the title codes ( Mr Mrs, Dr, etc )

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1026]
Required by GH-872

To be refined.

I don't know which impex needs to be updated for that.  My first guess would be the electronics store sample data.  Also maybe this change could be in the electronics-spa sub catalog.  Needs investigation.

**Comment by Xymmer** [comment]
closing as we decided not to have 'none' option
