### ISSUE TITLE
Backend: Deploy the commerce suite version that makes the title code optional.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1027]
Required by GH-872

See Comments on GH-872 as to which milestone or version of the commerce suite is required for that.

This will require a 1905 build that contains a certain specific milestone produced by Team Stingrays.

**Comment by Xymmer** [comment]
no longer required soon by GH-872, but we will want to update the server eventually.

**Comment by Xymmer** [comment]
this was done elsewhere
