### ISSUE TITLE
Search input invisible in mobile view

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1030]
Even after clicking 'loupe' icon, the input is not visible on mobile view:

![obraz](https://user-images.githubusercontent.com/4001059/51756015-526a0400-20c0-11e9-980f-b514dff8e3f0.png)

**Comment by kacperknapik** [comment]
I remember I fixed this issue once, but it seems it came back again. 

@LTiger14 can you have a look and check if your recent changes to the CSS selectors may have caused that?

**Comment by bgambocjaviniar** [comment]
PR #1192

**Comment by plabadie** [comment]
Fix confirmed:

<img width="378" alt="screen shot 2019-02-07 at 3 04 19 pm" src="https://user-images.githubusercontent.com/7065346/52439612-fbb1f080-2ae9-11e9-95ed-6aa0c1d2ae91.png">
