### ISSUE TITLE
use method "GET" to get a list of cms components (instead of POST)

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1033]
Before, we use POST method, and put the list of cms component ids in request body. Smartedit team change the API, so in SPA, we also need to change the function.

For details, please check this: https://jira.hybris.com/browse/CMSX-8193

Changed in their M14 release

**Comment by bgambocjaviniar** [comment]
#1230

**Comment by hackergil** [comment]
From @bgambocjaviniar:

NOT ABLE TO MERGE YET ---> Because it will break the develop branch

To be able to get a response, do the following:

* point your environment to https://dev-com-2.accdemo.b2c.ydev.hybris.com:9002

_Note_ our current environment do not have the new GET endpoint to get components by ids. These changes were released in wcms-module-19.05.0-M13

**Comment by Xymmer** [comment]
Now we have to do this for 1.0 launch as there is a problem with footer nav nodes
HOWEVER can we set a flag to use one or the other, so 1811 still works?

**Comment by Xymmer** [comment]
this problem only affects when using smartedit.

but we still need to support both for a while.

talk to tobias about optimum solution.

**Comment by bgambocjaviniar** [comment]
UPDATE: 
- Do a GET (since we want to support the latest and greatest one)
- If GET does not exist, do a POST

First of all, need to check what kind of error it will throw if one of them does not work and handle it to use the latter.

**Comment by bgambocjaviniar** [comment]
PR: GH-2430

**Comment by bgambocjaviniar** [comment]
For the QA:

- Go to dev tools on any page like homepage, click the network, and verify it uses the GET endpoint for components
- To test that the fallback works, you can go to occ-cms-component.adapter, and swap the .get and .post and bring the request['componentIds'] = ids.toString() in the get function to the post function. 
-- > Reason being is that I don't think the call will ever fail for the get endpoint, therefore test the post endpoint by giving an invalid body.

**Comment by RadhepS** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2430#issuecomment-493567361_

**Comment by bgambocjaviniar** [comment]
This will be fix in another ticket
