### ISSUE TITLE
Allow direct edit of quantity in product details and cart page

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#105]
Currently you can't edit the quantity besides using the -/+.

Add this ability:
- Make it configurable
- Display appropriate message when not enough stock
- Disallow entering anything except digits 0-9
- Smooth out entries like 001

**Comment by Xymmer** [comment]
Bill to get ui and text for message when out of stock

**Comment by kacperknapik** [comment]
Functionality works good. The only thing is a problem when a product has 100 pcs in stock, you set the qty to 200 - add-to-cart button is active and number of items added is weird. I will create a new ticket for it.
