### ISSUE TITLE
Refactor address book component

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1052]
- avoid using ngrx actions in logic, introduce additional logic in facade if needed
- avoid subscribing in component logic, try to use async pipe only (using rxjs operators)
- delegate complex business logic in component service (can be done when we move component to the cms lib)

**Comment by znikola** [comment]
Related to: #476

**Comment by Matejk00** [comment]
QA done, no bugs found.
Customer is able to add, edit, set as default and delete addresses.
