### ISSUE TITLE
use generic page layout for category pages

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1054]
Leverage page layout for category pages and refactor and move template styles to style lib.

**Comment by tobi-or-not-tobi** [comment]
**QA steps**
- add content to slots on CategoryPageTemplate, ProductListPageTemplate, SearchResultsListPageTemplate
- create/change cms content in slots, i.e. on the search page.

**Comment by LTiger14** [comment]
Passed QA
