### ISSUE TITLE
use generic page layout for cart page

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1073]

**Comment by tobi-or-not-tobi** [comment]
QA:
- content added to CenterLeftContentSlot in WCMS / SmartEdit should be rendered  on the cart page
- content added to CenterRightContentSlot in WCMS / SmartEdit should be rendered on the cart page
- changes to EmptyCartMiddleContent should be rendered on the cart page

**Comment by LTiger14** [comment]
Passed QA
