### ISSUE TITLE
Refactor product listing facets as a CMS component, mapping to ProductRefinementComponent

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1075]
Using the generic page layout, we can now render CMS components using the backend configuration. The backend provides a ProductLeftRefinements slot with a "ProductRefinementComponent" component. 

FR2 tickets for cmscomponrefactor going into epic/cmscomprefactor-fr2

**Comment by Xymmer** [comment]
#1075 and #1076 are similar and also similar to the one marcin did a while ago
