### ISSUE TITLE
[to-be-merged, awaits #1075] Refactor product listing component as a CMS component, mapping to CMSProductListComponent

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1076]
Using the generic page layout, we can now render CMS components using the backend configuration. The backend provides a ProductListSlot slot with a "CMSProductListComponent" component.

FR2 tickets for cmscomponrefactor going into epic/cmscomprefactor-fr2

**Comment by Xymmer** [comment]
#1075 and #1076 are similar and also similar to the one marcin did a while ago

**Comment by kacperknapik** [comment]
@Matejk00 can you quickly fix this error? 
![image](https://user-images.githubusercontent.com/22354613/54116180-7ecaad00-43ee-11e9-8f4f-981234aab270.png)

`display: flex` brakes this 'special' category
