### ISSUE TITLE
[to-be-merged, awaits #1075] Refactor product-list component, mapping to SearchResultsListComponent

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1078]
Using the generic page layout, we can now render CMS components using the backend configuration. The backend provides a SearchResultsListSlot slot with a "SearchResultsListComponent" component.

Please not that this refactor should be done in parallel with #1075 and #1076. The underlying component should be the same. We could potentially map the same component to multiple CMS types. 

FR2 tickets for cmscomponrefactor going into epic/cmscomprefactor-fr2

**Comment by kacperknapik** [comment]
@Matejk00 facet are not visible 
![image](https://user-images.githubusercontent.com/22354613/54116394-f698d780-43ee-11e9-9560-ee39409ec181.png)

**Comment by Matejk00** [comment]
@kacperknapik bug created #1610
