### ISSUE TITLE
use cms page template title for account pages

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1085]
Content pages have a localisable title which can be controlled by business users. This is not yet leveraged in our pages. Some of the pages will use this title.

**Comment by tobi-or-not-tobi** [comment]
Not valid now, as the header is supposed to be the breadcrumb

**Comment by Xymmer** [comment]
i was able to repro the qa steps but am waiting to see if i can change the text in backoffice
