### ISSUE TITLE
Spike: Define and create tickets for what hardcoded (JSP) cms components need conversion to FlexCmsComponent

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1086]
Pages are build based on the CMS structure: pages, page templates, slots and components. Ideally, all the content is driven by CMS components, so that business users are full in control of the usage of those components as well as we de client application (view)logic is as thin as possible. 

There are currently a large number of hard-coded components. This is caused by 2 reasons:
- we have not mapped cms components to js components (i.e. `ProductReferencesComponent` on the PDP page in the _UpSelling_ slot)
- we have not mapped JspIncludeComponent, since they do not have a specific type. With #1079 we have a solution to move JspIncludeComponent to configurable JS components.

In this ticket we must collect all the hardcoded components and all the missing (jsp)components. Based on this list, we need refinement to decide how to refactor. 

| page | UID (JspInclude) | current  | comment
| --- | --- | --- | --- |
| address-book | AccountAddressBookComponent | cx-address-book | done: #1088 |
| order history | AccountOrderHistoryComponent | cx-order-history | done: #1232 |
| order detail page | AccountOrderDetailsHeadlineComponent, AccountOrderDetailsOverviewComponent, AccountOrderDetailsItemsComponent, AccountOrderDetailsShippingComponent, AccountOrderDetailsTotalsComponent, AccountOrderDetailsActionsComponent |  cx-order-details  | TBD
|ProductListPageTemplate | ProductRefinementComponent || in progress
|ProductListPageTemplate | CMSProductListComponent || to-be-merged
|VariantSelector cms component #1365| ? |
| LoginPageComponent | ReturningCustomerLoginComponent  | cx-login-form | #1455  |
| RegisterPageComponent  | RegisterCustomerComponent | cx-register | #1364  |
| Payment Details | AccountPaymentDetailsComponent | cx-payment-methods | - |
| Cart Page | CheckoutComponent (should it be here?), CartSuggestionComponent, PromotionsComponent, PotentialPromotionsComponent, CartTotalsComponent, CartComponent, EmptyCartParagraphComponent | - | - |
| ... | | |

NOTE: we won't refactor **checkout** compontents/pages, because it will be heavily changed

**Comment by Platonn** [comment]
If possible, we can make them OnPush on the go.
