### ISSUE TITLE
[Thurs morning] Smoke test Jan 30 2019 lib release

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1094]
Use this server: http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/

Keep the browser's console open at any time and monitor for errors.

Perform the following smoke tests:

Brian:
- [x] Register, logout, login with the previously registered user
- [x] Go through checkout flow with the previously registered user:
- [x] Search for a product and open it
- [x] Check all tabs (product details, specs, reviews and shipping)
- [x] Add it to cart
- [x] Search for any other product and add it to cart directly from the search results page (don't open the product, just click on "add to cart")

Louis:
- [x] Change quantity
- [x] Create a new shipping address
- [x] Create a new payment method
- [x] Repeat for an existing user (any user that was registered before the smoke testing)
- [x] Check all other functionality/pages and observe is basic functionality broken, are there any UI elements broken, etc.:

Nik:
- [x] Order history page
- [ ] Change language/currency
- [x] Sort
- [x] When searching, use facets and filters
- [x] Check pagination
- [x] Storefinder

**Comment by znikola** [comment]
Created #1113
