### ISSUE TITLE
Define what cms component parity means

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1103]
Bill is defining what it means to have parity with Accelerator.

For CMS components, it means Spartacus supports what the latest Accelerator supports, for responsive storefronts.

We have this list as a starting point: https://wiki.hybris.com/display/spar/CMS+Component+Data. It's what is in Accelerator.
All our supported components are here: https://github.com/SAP/cloud-commerce-spartacus-storefront/tree/develop/projects/storefrontlib/src/lib/cms-lib

Core components:

Then there are other components other teams added:
CxCmsComponentContainer (Personalization)

**Comment by WeizhengSap** [comment]
Here: https://wiki.hybris.com/display/spar/CMS+Component+Parity+List

**Comment by Xymmer** [comment]
thanks!
