### ISSUE TITLE
In product details, change the link "write a review" to "show reviews" and show reviews, don't show edit

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1111]
In product review, current behavior is that there is a link "write a review" at the top. Clicking it shows Reviews tab to write a review. But most of the time people will want to see reviews.

Change this link to say "Show reviews"
When clicking this link, show the reviews tab, with the existing reviews showing.

**Comment by Pucek9** [comment]
@Xymmer what about this scenario: User clicked "show reviews", then "write a review" (form will be displayed instead of reviews list) and he will change tab. After come back there should be again list (form will be canceled), or same form?
Imo after open form it should be still there

**Comment by Xymmer** [comment]
still be there, agree

**Comment by Xymmer** [comment]
passing but clicking the link doesn't scroll the reviews up.
created #1273
