### ISSUE TITLE
[retest] Should render empty slots if in SmartEdit, but not when not

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1114]
In smartedit, I made 2 components invisible. Before the other 2 component occupy the space, now the space is just empty.

Need to ask Tobias how the slot is rendered.

![screen shot 2019-01-31 at 10 53 56 am](https://user-images.githubusercontent.com/44440575/52067396-80c86300-2548-11e9-84a6-79bda84cfa8b.png)

**Comment by Xymmer** [comment]
Olga says wait she'll check with Riry

**Comment by OlgaHaurylchyk** [comment]
Empty slots are expected to be displayed in SmartEdit, so that the Content Manager can add a component into the slot. On the storefront, however, that should not appear.
thanks

**Comment by Xymmer** [comment]
so... what can be done here?

**Comment by KateChuen** [comment]
I still see the empty space
![emptySlotsStorefront](https://user-images.githubusercontent.com/45409515/57322929-b5f9c980-70d2-11e9-9a8f-64c0197f89ff.png)

**Comment by KateChuen** [comment]
As designed. So closing.
