### ISSUE TITLE
[Closed in #1099] Language change produces a console error

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#1116]
Steps to repro: 

1. http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/category/576?pageSize=10&categoryCode=576&query=:relevance:category:576
2. Change language; notice an error in console (but the language is changed). 
![screen shot 2019-01-31 at 12 28 46](https://user-images.githubusercontent.com/11561723/52072762-cdfe0200-2553-11e9-8116-92eed714d600.png)

**Comment by WeizhengSap** [comment]
This one will be fix in this ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1099
