### ISSUE TITLE
Migrate smoke/language to cypress

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1119]
See GH-1102 for original spike.
Take a look at big happy path for example.
See cypress video in our wiki.

all epic/cypressmigration tickets should be merged into epic branch "epic/cypressmigration-fr1".
if this epic branch doesn't exist, you're probably the first, so create it.

**Comment by Pucek9** [comment]
Wait for revert currency/language panel

**Comment by hackergil** [comment]
We are not using CCv2 (aka Model T) anymore so this should be good to go.
