### ISSUE TITLE
migrate smoke/login to cypress

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1121]
See [GH-1102](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1102) for original spike.
Take a look at big happy path for example.
See cypress video in our wiki.

This test needs a user to log in with.
We don't want to use the standard e2e register/login utility for login test. This test would create its register own user and login separately.

**Comment by bgambocjaviniar** [comment]
PR #1359
