### ISSUE TITLE
migrate smoke/terms-and-conditions to cypress

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1123]
See #1102 for original spike.
Take a look at big happy path for example.
See cypress video in our wiki.

There are 2 t&c pages: from registration(don't need to register to see it), and fro checkout review/submit.
- why isn't checkout t&c tested during checkout happy path?
- why is registration t&c tested during registration?

maybe we can update the other tests and get rid of this one?

**Comment by marlass** [comment]
- [ ] Add T&C test to big happy path in register step
- [ ] Add T&C test to big happy path in last checkout step
