### ISSUE TITLE
In Firefox the cart icon is too small

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1134]
In Firefox:
![screen shot 2019-01-31 at 12 12 25 pm](https://user-images.githubusercontent.com/10605724/52077317-b5471980-255e-11e9-98ed-0c18ec6c6e92.png)

in Chrome:
![screen shot 2019-01-31 at 1 47 32 pm](https://user-images.githubusercontent.com/10605724/52077353-d14abb00-255e-11e9-9660-d4d61464567c.png)

The red box around the cart icon should be the same size in Firefox as in Chrome

**Comment by Xymmer** [comment]
verified in firefox, safari, opera, chrome on mac
need to check windows
