### ISSUE TITLE
Refactor cms pages to use the "load once" strategy

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1135]
Originating from #272 and discussed in Nov 29 refinement.

See #272 for example and checklist from Stan. Direct questions to Stan.

Structure of the state will have to be reorganized, and related cmsService methods refactored

**Comment by dunqan** [comment]
The proposed solution for organizing page state:
```
page: combineReducers({
      pageData: entityReducer<Page>(PAGE_ENTITY, templateReducer),
      index: combineReducers({
        content: entityLoaderReducer<string>(CONTENT_PAGES_ENTITY),
        product: entityLoaderReducer<string>(PRODUCT_PAGES_ENTITY),
        category: entityLoaderReducer<string>(CATEGORY_PAGES_ENTITY)
        catalog: entityLoaderReducer<string>(CATALOG_PAGES_ENTITY)
      })
    } )
```

**Comment by znikola** [comment]
`pageData` will be `entities` object with `Page` objects as entities, and the keys are going to `Page`'s `uid`.

**Comment by znikola** [comment]
PR: #1350
