### ISSUE TITLE
User orders data only load once, even user place new orders.

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1137]
We have this:
```
       if (
          orders.orders &&
          Object.keys(orders.orders).length === 0 &&
          this.user_id
        ) {
          this.userSerivce.loadOrderList(this.user_id, this.PAGE_SIZE);
        }
```
So, when there is order data, the data will not loaded again. "Place an Order" should clean the user orders state, so that this `this.userSerivce.loadOrderList(this.user_id, this.PAGE_SIZE);` can be executed.

And it's much better to consider that: an order status can change over time.

**Comment by Pucek9** [comment]
I decided to hold this ticket until header functionality (currency/language change) will be restored

**Comment by Pucek9** [comment]
QA will be done in ticket #1258
