### ISSUE TITLE
Refresh cart page, then change currency, some weird string display

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1138]
Change currency from $ to YPJ

![screen shot 2019-01-31 at 4 26 00 pm](https://user-images.githubusercontent.com/44440575/52086534-2eea0200-2575-11e9-8190-1a2a28e4b270.png)

**Comment by Zeyber** [comment]
Strange text is coming from backend.

**Comment by Xymmer** [comment]
Let's determine for certain it's a backend issue, if so create a RAY issue
can we add a workaround in spartacus, or maybe not worth it?

**Comment by WeizhengSap** [comment]
duplicate ticket of this: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/502

Backend ticket: https://jira.hybris.com/browse/RAY-347 was created.

**Comment by tobi-or-not-tobi** [comment]
no longer an issue, most likely fixed with #502
