### ISSUE TITLE
Console errors when go to checkout page

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1139]
I see these errors when go to checkout page:

![screen shot 2019-01-31 at 4 30 20 pm](https://user-images.githubusercontent.com/44440575/52086710-a61f9600-2575-11e9-9856-1775ab997188.png)

**Comment by Pucek9** [comment]
Error concerns layout service, there was an unexpected missed data or something. Now it is not reproducible

**Comment by Pucek9** [comment]
Wei told issue was fixed,
