### ISSUE TITLE
Configure JS application with runtime backend baseUrl

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#1148]
The JS application currently is configured with the backend baseUrl, typically https://localhost:9002. Angular-cli provides a mechanism for different configurations per environment, but at the end of the day, the configured baseUrl is baked into the JS code. This means that the application cannot be deployed to various environments (dev, qa, prod); a new build is required for each and every environment. The same is true for the pipeline; the pipeline's backend must be aligned with the baked in configuration. 

When we deploy the JS app on a server, ideally, the server should provide a configuration to the JS app when it's served. Sys admin users can then reconfigure the backend baseUrl, and with the next request, the JS app will interact with the newly given baseUrl.

There are different possible solutions, none of them are standard (not in angular(-cli) nor in JS world).

1. Provide a local config file in the JS app that can be read before the app start to bootstrap
2. Provide a http header in the index.html
3. Provide a script tag in the index.html
4. Provide a meta-tag in the index.html

The challenges around this are:
- we do not want to do a separate network request (which is the case in 1 and 2)
- we want a server agnostic solution
- we want an easy to use solution (2 is complicated for non-webserver devs)
- we want a layered approach (means, we could do multiple solutions, with fallbacks)

Based on this, we like to do the following:

Look for meta-tag with a specific name, indicating the OCC backend base URL

```html
<meta name="occ-backend-base-url" content="https://localhost:9002">
```

If the meta tag is not available (can be empty though), the config will fallback to the hardcoded configuration in the environments (angular-cli feature).

**Comment by Platonn** [comment]
QA done by @dunqan while reviewing
