### ISSUE TITLE
Spartacus preview image not showing in SmartEdit start page

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1168]
![image](https://user-images.githubusercontent.com/4998145/52165771-cc0e7d00-26d2-11e9-82ae-19f98f505518.png)

**Comment by WeizhengSap** [comment]
PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/19/overview

use yenv Spartacus template; and reinitialize the system.
