### ISSUE TITLE
Spike page restrictions and what we get from occ e.g. @hardlogin

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1173]
Currently address controllers in Acceleator implemented has annotation @requireshardlogin
occ is not revelaing this info
e.g. faq can be seen by anyone
but address not, you have to be logged in.
and secureportal is coming

we need mechnanism in cms so that we know which pages can only be seen by specific users.
e.g. customer group maybe

just configuration. add restriction in generic way to a page.
Frank can help us spike here.

----
note: cms restrictions work.
e.g. copy faq but add restriction e.g. vipcustomergroup
see if vip user can see it, others not.
you get 'page not exist' (but we need to handle it).

**Comment by WeizhengSap** [comment]
There is no page restriction evaluated for default page. I will close this ticket because this topic is discussed in here: https://jira.hybris.com/browse/CMSX-8491
