### ISSUE TITLE
Add create account form to the order confirmation

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1178]
After confirming the order, the user lands on the order confirmation page. If the user is a guest, the page should display an account creation from at the top of the regular page as mocked by UX. To create a user, the same API as the regular registration is use (POST /users). The only fields to provide are: `guid` (the guid field from the order) and `password`. After the registration the user is should be logged in.

Mocks: https://98qkkl.axshare.com/#g=1&p=d_order_confirmation_2

**Note** this ticket does not require the fancy password rules verification box from the mocks. This should reuse the password and confirm password from the registration form.

### Acceptance criteria

- New section in the order confirmation to create a full user (only if the user is a guest)
- If the user is not a guest the page should remain the same

**Comment by hackergil** [comment]
Currently there is no OCC endpoint to upgrade the user to a registered user. To be addressed on this ticket

https://jira.hybris.com/browse/RAY-404

/users endpoint can create a new user, but the order won't be linked to it. Proper way to do it is by upgrading the current account to a user account.

**Comment by WeizhengSap** [comment]
Try that "createUser" API. Only pass "guid" and "pasword", leave all other parameters empty.

**Comment by LTiger14** [comment]
Got a response from team Stingrays. There is no other endpoint that supports this feature so we can use the deprecated one. This issue is unblocked.

**Comment by giancorderoortiz** [comment]
Unable to advance to order confirmation. See https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4458

**Comment by giancorderoortiz** [comment]
Styling pending. See https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4449

**Comment by giancorderoortiz** [comment]
Functionality confirmed.  🆗 
Able to do guest checkout with different addresses.
