### ISSUE TITLE
2. Update address step & shipping method

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1180]
During a regular checkout, the shipping address step will try to get the user's saved addresses. This cannot be done in the case a guest user. 

If the user is a guest user, the new address form should not be displayed. There shouldn't be any changes to be done to the shipping method page.

We can use the getUserToken method in auth facade to check if user is logged in.

In addition in `checkout-delivery.service` there is a function called `actionAllowed` that interferes with proceeding with the steps when the user is a guest. Adjust this function to be able to proceed with the following checkout steps.

### Acceptance criteria

-  If a user is a guest the address form is displayed without a backend call to fetch existing ones
-  If a user is not a guest the behavior is the same as before
-  The address verification should work with anonymous as user (requires client token)

**Comment by giancorderoortiz** [comment]
Observation: 
@Xymmer, @hackergil 
Guest user cannot make a mistake then when entering an address. If he's in checkout step 2 - 4, and needs to update shipping address, then he will have to re-type the whole thing again. 
Is this the intended behaviour?

**Comment by giancorderoortiz** [comment]
Other than above comment, acceptance criteria fulfilled in this ticket.

**Comment by giancorderoortiz** [comment]
Guest shipping address: 
![Screen Shot 2019-08-25 at 6 32 45 PM](https://user-images.githubusercontent.com/46171897/63656771-d4113580-c766-11e9-8340-5ae620978906.png)

Guest shipping method: 
![Screen Shot 2019-08-25 at 6 33 12 PM](https://user-images.githubusercontent.com/46171897/63656772-d4113580-c766-11e9-9907-7e5a9fe68a58.png)
