### ISSUE TITLE
3. Update payment method & order summary

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1181]
With a regular checkout, the payment method step will try to get the user's saved payment methods. This cannot be done in the case a guest user. 

If the user is a guest user, the new  payment method form should be displayed without trying to fetch existing payment methods. There shouldn't be any changes to be done to the order summary.

In the order summary page, the submit order request will have to be changed to include the client token in the case of a guest order.

We can use the getUserToken method in auth facade to check if user is logged in.

### Acceptance criteria

-  If a user is a guest, the payment method form is displayed without a backend call to fetch existing ones
- If a user is not a guest the behaviour is the same as before

**Comment by giancorderoortiz** [comment]
I see the path difference. Good.  Method paymentdetails?saved=true not called if doing a guest checkout

**Comment by giancorderoortiz** [comment]
**Regular user:** 

![regular-user](https://user-images.githubusercontent.com/46171897/64696451-70784f00-d46c-11e9-8eeb-dfc30a36d783.png)

Guest Checkout: 

![guest-user](https://user-images.githubusercontent.com/46171897/64696462-79692080-d46c-11e9-8143-21c143883a0a.png)
