### ISSUE TITLE
'Consent Management' Facade Functions

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1184]
See "Facade Tickets" in GH-1580

The Consent management facade function(s) will need to align with the OCC Api.  The Api allows for consents to be added or removed on an individual basis.

While the UI component will display the consent list, only one consent at a time will be saved/updated.

This will keep the facade/effect/reducers/actions at a manageable complexity level.  More importantly, Allowing the facade to update consents in bulk while OCC does not support it would create some difficult to manage the state of the non atomic process. For example, when updating 5 consents, 3 updates could be a success and 2 could be in error.

**Comment by znikola** [comment]
PR: #2362
