### ISSUE TITLE
'Consent Management'  UI 

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1185]
See "UI Tickets" in GH-1580

https://98qkkl.axshare.com/#g=1&p=w_profile_consent_management

The wireframe will be updated to have only a 'Done' button.  See 'Consent Management Specific Transitions' below for the form behaviour.

If not already done, the Consent Management UI will present a list of consents to be updated.  However, To comply with the facade and OCC Api, only one consent at a time will be updated by the form. 

This means that this form will behave differently than the rest:

## Consent Management Specific Transitions

- When consent is ticked/un-ticked: Display a spinner instead of the whole form and it's buttons.
- Success: Stay on the page. Display a success message.
- Error: Stay on the page. Reset the value in the checkbox to what it was before. Let the global error management display the error message.
- Done: Go to the home page.

**Comment by znikola** [comment]
Backend PR: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/45/
