### ISSUE TITLE
'Close Account' UI 

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1188]
See "UI Tickets" in GH-1580

https://98qkkl.axshare.com/#g=1&p=w_close_account_default

A Cancel button is supposed to be added to the wireframe.  Implement it.

A specific behaviour to the Close Account page: when the user clicks 'Close Account'. we want to present him with a modal confirmation.  If the wireframes are not updated, see the legacy acc screenshot below for guidelines:

![screen shot 2019-03-07 at 12 01 21 pm](https://user-images.githubusercontent.com/7065346/53975279-7b73b080-40d2-11e9-880e-0cafa4810316.png)

## Specific Transition
Success: We must also sign out the user.

**Comment by KateChuen** [comment]
Tested through ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1579
There are 2 buttons, "Cancel" and "Close my Account"
