### ISSUE TITLE
Create custom component schematic

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#12]
We can provide an angular schematic to simplify the creation of custom components, routes, page templates, etc. This will help to:
- customise very fast
- customise according to our best practice
- avoid reading documentation

Angular schematics are the technique that can be used for this.

**Comment by tobi-or-not-tobi** [comment]
After having done a few enablement sessions with dev teams, this becomes more important. Mainly because of a lack of experience with Angular and the best practices we can bring to the table.

**Comment by znikola** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5260
