### ISSUE TITLE
Spike forgotten password OCC flow

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1218]
master ticket: #349

can /forgottenpasswordtokens be used to reset password for a user? (check with bill if trouble)
https://help.hybris.com/6.3.0/api/ycommercewebservices/main.html#_forgottenpasswordtokens

Acceptance criteria: the OCC calls to reset password are described here, to be used to implement forgot password flow (#1219 and #1220).

**Comment by plabadie** [comment]
Endpoint to trigger the password email exists and works.
It's `/{baseSiteId}/forgottenpasswordtokens`

Endpoint to reset the password can't be found.  Enquiries were sent, either we will learn of its existence to it will get implemented.

**Comment by plabadie** [comment]
Conclusion: the reset password does not exist and it need to be added in the commerce backend.
