### ISSUE TITLE
Add Reset Password (from Forgot Password flow) cms and page

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1220]
master ticket: #349

- determine/update how the send reset password link is sent through email template that points to spartacus (I assume it's a combination of token + spartacus url inserted into email)
- add cms page for 'reset password' page, if it's not already there
- implement reset password page (button should be just 'reset password' not 'my'
![image](https://user-images.githubusercontent.com/4998145/52377595-605e4400-2a33-11e9-80f1-c9f61b163c6a.png)

Acceptance criteria:
- i go through forgot password flow and get a link
- clicking the link goes to reset password page (i should not be logged)
- the password form behaves like when we enter a password when registering
- button activates when password meets min criteria and they match
- submitting successfully redirects to the login page and displays a success message: "Success! You can now login using your new password."

**Comment by Xymmer** [comment]
note there is an issue with being able to reset the password without knowing the old password, we're investigating. Separate last bullet of acceptance criteria (being able to submit successfully) if required.

**Comment by tobi-or-not-tobi** [comment]
- we do not longer have _page controlling logic_, it's all done in components
- the page that is used to reset the password will be hardcoded for now
- the `UpdatePasswordComponent` is used both for requesting the reset password, as well as for setting it (just because it's the case right now). 
- we already have a content page for Update Password, with the page-label `updatePassword`

![image](https://user-images.githubusercontent.com/4745807/52553600-4d0cf900-2de4-11e9-9edf-b6fb708ab5c3.png)

To further decouple, we should consider additional changes in the future: 
- provide a (backend) configuration for the loginPage, requestResetPasswordPage, resetPasswordPage, 
- make all content of those pages cms driven (i.e. paragraph components, link components)

**Comment by WeizhengSap** [comment]
This ticket is blocked by #1270 and https://jira.hybris.com/browse/RAY-239.
What I have done is:
1. create some email render template for site "electronics-spa".
2. create "reset password" cms page in "electronics-spa", and add one JspIncludeComponent "resetPassword". (This component will be replaced by a FlexCmsComponent when #1270 is done.)
3. remove "reset password" page and layout from SPA.
4. add cmsComponent config "ResetPassword", so this JspIncludeComponent can be found.

**Comment by WeizhengSap** [comment]
This is the email body we get (of course, the token is expired). You should be able to click the link then go to "reset password" page.
<html>
	<head>
	</head>
	<body bgcolor="#ffffff"
	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#ffffff">
		<tr>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td align="center" valign="top">
				<table width="610" border="0" align="center" cellpadding="0" cellspacing="0" bordercolor="#fff">
					<tr>
						<td align="center" valign="top" bgcolor="#FFFFFF">
							<table width="570" cellpadding="0" cellspacing="0" border="0" align="center">
								<tr>
									<td valign="middle">&nbsp;</td>
								</tr>
								<tr>
									<td valign="middle">
										
										<img src="http://localhost:4200/_ui/desktop/theme-/images/header_01.png" alt="" width="229" height="72" border="0" align="right" title="" />
									</td>
								</tr>
								<tr>
									<td height="30" align="right" valign="middle" bgcolor="#000000">
										<font color="#FFFFFF" size="2" face="Arial, Helvetica, sans-serif"><a href="http://localhost:4200/my-account"><font color="#FFFFFF">My Account</font></a> | <a href="http://localhost:4200/store-finder"><font color="#FFFFFF">Store Finder</font></a> &nbsp;&nbsp;</font>
									</td>
								</tr>
								<tr>
									<td align="center" valign="middle"><a href="http://localhost:4200" style="display:block; margin-top:10px;margin-bottom:10px;"><img src="http://localhost:9001/medias/banner-sale-now-on.jpg?context=bWFzdGVyfGltYWdlc3wyOTQwMHxpbWFnZS9qcGVnfGltYWdlcy9oMWQvaDE4Lzg3OTYzMjIzMzI3MDIuanBnfDJiODQ5Y2NiMGY2OTJhZDRkMzBkNzc1OGQyNDBjNGZlZmI2ZmVjZjI2YjVmNDIxZGQxY2Q0OGVhOGNmOWU0ZWE" alt="" border="0"/>
</a></td>
								</tr>
								<tr>
									<td>&nbsp;</td>
								</tr>
								<tr>
									<td align="left" valign="top">
																																					<p><font color="#666666" size="2" face="Arial, Helvetica, sans-serif"><b>Dear  Weizheng Gao</b>,</font></p>
										<p><font color="#666666" size="2" face="Arial, Helvetica, sans-serif">You&rsquo;re almost done.&nbsp;&nbsp;</font><font color="#666666" size="2" face="Arial, Helvetica, sans-serif">To update your password please click here:&nbsp;<a href="http://localhost:4200/login/pw/change?token=RqraQgqKOdh3IbbR4%2ByGM0tFJrFBUlVJ0oNC4b%2BjY%2FVn%2FKPgVHey%2BKOogG3neMBXVyDbyU9imaC%2BmbFBp3xp2MnfUSh8QOG3HiQ8oOG2dmiLnQtHPSYI9wVXZG8kaB1uEIu28BqHWk1v3ukzXyklo%2BmxIQ%3D%3D"><font color="#666666">http://localhost:4200/my-account/update-password</font></a> </font></p>
										<p><font color="#666666" size="2" face="Arial, Helvetica, sans-serif">Please note: For security purposes this email will expire within 30 minutes. Please update your  password within 30 minutes of requesting the password update.</font></p>
										<p><font color="#666666" size="2" face="Arial, Helvetica, sans-serif">If the link has already expired, please request an update to your password again here: <a href="http://localhost:4200/login/pw/request/external"><font color="#666666">Request a password update</font></a></font></p>
										<p><font color="#666666" size="2" face="Arial, Helvetica, sans-serif">If we can help you with any enquiry, please check our <a href="http://localhost:4200/faq"><font color="#666666">FAQ page</font></a>, use our <a href="http://www.hybris.com/en/contact"><font color="#666666">Contact Us</font></a> page, or contact our customer services team directly via phone +44 (0)20 / 7429 4175 or email <a href="mailto:customerservices@hybris.com"><font color="#666666">customerservices@hybris.com</font></a>.</font></p>
										<p><font color="#666666" size="2" face="Arial, Helvetica, sans-serif">Many Thanks</font></p>
										<p><font color="#666666" size="2" face="Arial, Helvetica, sans-serif">Customer Services</font></p>
									</td>
								</tr>
								<tr>
									<td>&nbsp;</td>
								</tr>
								<tr>
									<td align="center" valign="middle">
										<a href="http://localhost:4200" style="display:block; margin-top:10px;margin-bottom:10px;"><img src="http://localhost:9001/medias/banner-free-delivery.jpg?context=bWFzdGVyfGltYWdlc3wyMzc3MHxpbWFnZS9qcGVnfGltYWdlcy9oZTEvaDUwLzg3OTYzMjIyOTk5MzQuanBnfGQ0YmI1N2ZmOWM0NmM2OGUyZjVmNjkxYjQyN2VmYzUyMjFkMmU2OGJjZmZiYzI1YjMxNTI0ZjdlY2YzMjc5MzY" alt="" border="0"/>
</a>
									</td>
								</tr>
								<tr>
									<td height="30" align="right" valign="middle" bgcolor="#000000">
										<font color="#FFFFFF" size="2" face="Arial, Helvetica, sans-serif"><a href="http://localhost:4200"><font color="#FFFFFF">Help</font></a> | <a href="http://www.hybris.com/en/contact"><font color="#FFFFFF">Contact Us</font></a> | <a href="http://localhost:4200"><font color="#FFFFFF">Terms &amp; Conditions</font></a> &nbsp;&nbsp;</font>
									</td>
								</tr>
								<tr>
									<td>&nbsp;</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
		</tr>
	</table>
</body>
</html>

**Comment by WeizhengSap** [comment]
backend PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/22/overview

**Comment by WeizhengSap** [comment]
To code reviewer/tester:

The steps to make it work are:
1. uninstall the spacceleratorsampleaddon, and reinstall it
ant addonuninstall -Daddonnames="spacceleratorsamplesaddon" -DaddonStorefront.yacceleratorstorefront="yacceleratorstorefront"
ant addoninstall -Daddonnames="spacceleratorsamplesaddon" -DaddonStorefront.yacceleratorstorefront="yacceleratorstorefront"
2. replace the mail settings into local.properties (inside hybris/config)
```
mail.smtp.server=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=spa.gladiators@gmail.com
mail.smtp.password=hybris2019!
mail.use.tls=true
```
Or you can use Patrick's http://mockmail.plabadie.com/ to do it. Contact @plabadie for how to set it up.

3. rebuild the system, and start the hybris server

4. initialize the system

5. Go to forgot password page, then enter a valid user password. 

6. You should able to get the email after a few seconds.

7. Click the link inside the email, you should see "set password" page open. Enter new password.

8. We don't have the occ endpoint for "set password". The the new password is not really set. You should see the token and new password in browser's console.log.

9. You should be able to see the success message, and you are redirect to login page. But, you cannot login using your new password.

**Comment by KateChuen** [comment]
1) determine/update how the send reset password link is sent through email template that points to spartacus (I assume it's a combination of token + spartacus url inserted into email)

- [X] The link from the email goes to (which contains the spartacus url and token): http://dev-com-22.accdemo.b2c.ydev.hybris.com:4200/login/pw/change?token=ncfqaOMfYstdvL8hOYSgDjjdeAI29QdMn87DUBouLhmavcZvj7iMNdtdt0RzKLYsq3nqGGLwbjRWnJ88XIyvhL7rwFhHNoKpsScUBTfRKOLFjiztFar7jx9%2F3aUwmViTG3y%2BigiuD4x04dlQkKmu28nWw7YOXW3%2FH18v6%2B8%3D

2. add cms page for 'reset password' page, if it's not already there
implement reset password page (button should be just 'reset password' not 'my'

- [X] Button is reset password.
![ResetPwdButton](https://user-images.githubusercontent.com/45409515/54930365-89f10300-4eed-11e9-9f5d-0f10c2d4d002.png)

3. i go through forgot password flow and get a link

- [X] This is the email received: 
![forgotPwdEmail](https://user-images.githubusercontent.com/45409515/54930225-4a2a1b80-4eed-11e9-91e2-1e83d16c0315.png)

4. clicking the link goes to reset password page (i should not be logged)

- [X] Even if I was previously logged in, clicking on the link goes to reset password page and no user is logged in. 

5. the password form behaves like when we enter a password when registering
button activates when password meets min criteria and they match
submitting successfully redirects to the login page and displays a success message: "Success! You can now login using your new password."

- [ ] The "Reset Password" button is active before the password meets the criteria. However, a validation is done when clicked on it.
![resetPwdButtonActive](https://user-images.githubusercontent.com/45409515/54930828-6084a700-4eee-11e9-8a65-deb97632752d.png)

- [X] Successfully submitting the new password redirects user to the login page and with the correct success message.
![successMsg](https://user-images.githubusercontent.com/45409515/54931124-d721a480-4eee-11e9-8f26-965ef2ef74d2.png)

6. We don't have the occ endpoint for "reset password". The the new password is not really reset. You should see the token and new password in browser's console.log.

- [X] Can see token and new password in console.
![NewPwdLog](https://user-images.githubusercontent.com/45409515/54932239-d984fe00-4ef0-11e9-9cf4-4a05b7393a80.png)


7. You should be able to see the success message, and you are redirect to login page. But, you cannot login using your new password.

- [ ] Now able to login with new password - which I think is a good thing.
![loginWithNewPwd](https://user-images.githubusercontent.com/45409515/54932453-3ed8ef00-4ef1-11e9-8898-31f5621996af.png)

**Comment by plabadie** [comment]
For point #5, For the submit button, we followed the form behaviour requirements described in the Wireframes: https://98qkkl.axshare.com/#g=1&p=main_action_on_form_pages
The ticket description should have been updated.
