### ISSUE TITLE
Check email containing link to show anon order

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1223]
After an order an email will be sent with a link to order confirmation (for guest and regular). This should be tested to see if the email points to the old accelerator or spartacus.

If the email points to the accelerator it should be fixed. If it points to spartacus, there are no changes to be made.

**Comment by Xymmer** [comment]
Displaying the anon order is already taken care of?
Also see order expired #1224

**Comment by hackergil** [comment]
I took a look into this. Emails are pointing to the old accelerator and they have a hardcoded URL.

We'll need to create a new email template and override it via spartacusssampledata

**Comment by hackergil** [comment]
URL in email is [host]/guest/order/[order_id]. This won't work with the current API.
