### ISSUE TITLE
Spike find order with last name & orderId

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1225]
As a guest user, it's possible to get an order using the link from the order confirmation email.

An alternative way of doing so would be using the last name and the order id.

This ticket is to evaluate if it is doable with the API and the steps required to do so.

**Comment by WeizhengSap** [comment]
Can get order data by guid.

**Comment by WeizhengSap** [comment]
To make it work:
1. In authentication configuration, set "client_id" to "trusted_client".
2. There is a bug in cms email component (C3PO-1891). Contact Wei for the content of the OrderConfirmation email component.
