### ISSUE TITLE
Domain-driven SiteContext

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1226]

**Comment by Xymmer** [comment]
for 1.0?

**Comment by james-grant-envoy** [comment]
Hi @Xymmer and @tobi-or-not-tobi,

Are there any plans to add domain mapping? I need a way to map customer friendly local routes to specific commerce base sites.

/en-gb/   maps to   /companyA/en-GB/GB
/en-us/   maps to   /companyA/en-US/USD
/en-fr/   maps to   /companyA/fr/EUR

and vise versa.

**Comment by tobi-or-not-tobi** [comment]
@james-grant-envoy sorry for not getting back to you. We're actually planning on doing configurable multi-site, using the multi-site platform capabilities of the backend. We will continue with this in #1810.
