### ISSUE TITLE
Add "compoDoc" into package.json

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1229]
Check this Gil's commit https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/20b6ebd48b0e99c867adbe7a2c03413a0055d2c1.

Better create docs based on libs. So, we can have "core", "storefrontlib"... docs.

CompoDoc has some bugs, in this ticket, to make it work well:
1. in `cx-api.module.ts`, change `@NgModule()` to `@NgModule({})`
2. exclude "/projects/backend" (until we refactor `async function`) (suggestion is with regex).

part 2 is #1315

**Comment by tobi-or-not-tobi** [comment]
Let's exclude the backend as we're going to refactor it going forward.

**Comment by WeizhengSap** [comment]
There is errors when generating docs
![screen shot 2019-02-19 at 11 27 44 am](https://user-images.githubusercontent.com/44440575/53032517-fd11e000-343c-11e9-9345-5cd9cb0f3468.png)

Please fix it.
