### ISSUE TITLE
Spike: Session management / token expiry and refresh + creating tickets

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#123]
SPA-860, SPA-571, and SPA-572 reported issues with access tokens.
Need to spike our strategy and define what changes are needed. Example:
- what to do when session expires
- what to do if refresh fails

Also create tickets and refine with Bill and Tobias.

**Comment by marlass** [comment]
Created tickets. You can wind those under epic/tokenexpiryandrefresh label.
