### ISSUE TITLE
Storefinder pagination and scrolling fixes

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1236]
Currently when you click use my location, you get a list of stores, a map, and pagination at bottom. 
but:
- the list currently displays 20 stores in a scrolling dive
- the pagination is under the map
- it's a known issue that the mock gets you all stores from the mock and has nothing to do with your location

so let's just fix it up a bit:
- [x] put pagination above list with number of stores
- [x] make map same height as scrolling list at left
- [x] when you click Back to List you should see all stores on map

e.g. of what we're seeing now
![image](https://user-images.githubusercontent.com/4998145/55716662-88333f00-59c5-11e9-9a21-df13adb204bf.png)

**Comment by kacperknapik** [comment]
additionally I found one more thing:
- [ ] when you visit second page, stores numbers start again at 1

**Comment by Zeyber** [comment]
Blocked because this bug involves pagination and we should wait until the ngb-pagination migration #2137 has been merged.
