### ISSUE TITLE
Spike+implement strategy for handling different messaging scenarios

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#124]
This issue is to investigate the different scenarios in which we display a global message and come up with a strategy for reducing irrelevant messages. Perhaps make it configurable as well. For example, you don't want to add 'checkout was succesful' if we're displaying a confirmation page anyway.

One suggestion from Tobias is to hide a message when a page/route changes, and we go from there.

For example, you place an order, the 'order placed successfully' message appears and stays that. Would be good if it was hidden if i changed pages.

However, in that particular example, since we display an order confirmation, i'd want to hide that message always, as its redundant. How do we do that?

Maybe the solution is to implement Tobias' suggestion and then we see what improvements need after, but i think it's ok like that.

Let Tobias know what we're doing.

**Comment by Pucek9** [comment]
My idea is something like message from backend has additional property with conditions of displaying message like:

```ts
export default interface Conditions {
  hideOn?: string;
  ttl?: number;
  timeout?: number;
}
```
e.g. it will remove message after go to specified-route
```ts
conditions: {
  hideOn: '/specified-route';
}
```
on set ttl, message will be removed after x navigations
and timeout - after delay

**Comment by tobi-or-not-tobi** [comment]
We do not have such feature in the backend, and I don't like to add it there as well. I'd rather like the UI to dictate the experience. I'd rather expand the message with `hideOnRouteChange`, `hideAfterTimeout` properties. Alternatively, we could have different message types. 

The existing types, `info`, `warn` and `error` could also contribute to the default behaviour, i.e.:
- info: hide on route, hide after 1s
- warn: hide on route, hide after 60s
- error: hide on route, do not auto hide

**Comment by Xymmer** [comment]
second pr

**Comment by marlass** [comment]
Confirmation messages are hidden after a provided delay. Couldn't invoke multiple messages with the same content. No new regression found (closing works, styling without changes, messages shown on right events)
