### ISSUE TITLE
top header line should be hidden if you hide all the links

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1240]
![image](https://user-images.githubusercontent.com/4998145/52500638-822f0680-2bac-11e9-9aad-c1b6c8321bd9.png)

**Comment by LTiger14** [comment]
This is not an issue, it's only happening because the backend used doesn't have the Language & Currency dropdown or the top right links CMS components yet. This will be fixed with a backend update.

**Comment by Xymmer** [comment]
fixed by #1395
