### ISSUE TITLE
use generic page layout for 404

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1251]

**Comment by tobi-or-not-tobi** [comment]
**QA steps**
- open not found page in WCMS / smartedit
- add a component (i.e. paragraph) in any of the slots
- confirm the content shows up in Spartacus

**Comment by Xymmer** [comment]
works! i added a paragraph component to "Middle Content Slot for Error Page" of 404 page.
