### ISSUE TITLE
Consider creating new content for 404 page

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1254]
With using the generic page layout for rendering the 404 page, we've lost some of the hardcoded UI that was build to meet the design:

![image](https://user-images.githubusercontent.com/4745807/52567618-113a5980-2e0d-11e9-9ce5-8c6022de2287.png)

In order to have the UI design back, we could rebuild that UI with existing CMS components. As longs as we use standard components, Spartacus will render them automatically. 

The first is recommended.

**Comment by bgambocjaviniar** [comment]
PR #1445 
Will edit once it starts working again. Something went wrong.

**Comment by WeizhengSap** [comment]
Where is the backend PR?

**Comment by KateChuen** [comment]
Tested on dev17 on chrome, firefox & safari.
I get the new 404 page now.
