### ISSUE TITLE
Change getOrdersLoaded selector 

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#1258]
There's an inconsistency in `getOrdersLoaded` selector:
```
export const getOrdersLoaded: MemoizedSelector<
  StateWithUser,
  boolean
> = createSelector(
  getOrdersState,
  (state: LoaderState<OrderHistoryList>) => loaderLoadingSelector(state)
);
```

Its name is suggesting usage of `loaded` or `success` flags, but we are returning `loading` flag.

In the html (`projects/storefrontlib/src/lib/my-account/order/order-history/order-history.component.html`) template, this is used for displaying "We have no order records for this account" message.

We should use `success` flag and rename methods/selectors/properties to have consistent names.

**Comment by WeizhengSap** [comment]
In this ticket, I QA the ticket #1137 first. It works fine.

**Comment by WeizhengSap** [comment]
The steps to QA this ticket:
1. register a new user
2. go to my-account/order history page, you should be able to see "We have no order records for this account."

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1271
