### ISSUE TITLE
Make footer configurable and extendible

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1259]
We like the storefront footer to be configurable (configure slots that are part of the footer) and extendible (add/replace the footer). The storefront should iterate over all slots that are related to the footer. The _configurable page layout_ are build for this purpose and allow for reconfiguration by customers. 

We keep wrapping the footer in a footer element, for accessibility reasons. In the unlikely situation where a customer would like to replace the footer element as a whole, the customer can implement a custom variant of the _cx-storefront_. That will be a fairly small customisation.

**Comment by tobi-or-not-tobi** [comment]
**QA steps**:
- reconfigure the footer slots, i.e. 
  -  for a given page, i.e. make it an empty array for the cart page
  - configure another slot to be part of the footer config (either on the global or on a specific page)
- validate that the configuration shows up

The config should be applied in the app.module.

**Comment by Platonn** [comment]
Works as expected. I've tested using this complicated config:
```
layoutSlots: {
  footer: {
    sm: { slots: ['SiteLogo'] },
    lg: { slots: ['NavigationBar'] }
  },
  CartPageTemplate: {
    footer: {
      slots: ['NavigationBar', 'SiteLogo', 'Footer'],
      md: { slots: ['MiniCart'] }
    }
  }
}
```
