### ISSUE TITLE
Move title into initial version of the breadcrumb component

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1266]
The page title is currently configured as a page templalte configuration, but should actually be driven by the breadcrumb component. This will make the configuration more lightweight, and the title (with breadcrumb) is runtime configurable by business users.

**Comment by tobi-or-not-tobi** [comment]
This ticket is blocked by #1267 unless we create an interceptor to provide the right structure.

**Comment by Xymmer** [comment]
@tobi-or-not-tobi : i checked latest github io, I'm seeing Home and then the page title in big. Was this the intention of this ticket? I assume further to do here.

**Comment by tobi-or-not-tobi** [comment]
> @tobi-or-not-tobi : i checked latest github io, I'm seeing Home and then the page title in big. Was  this the intention of this ticket? I assume further to do here.

@Xymmer The title might be slightly too big, but in general it's the breadcrumb design as proposed in the visual design. It's just that the breadcrumb shouldn't be configured on the home page, and must be adapted on a view other places. @WeizhengSap has done the modifications already in #1360.
The reason to not finalise the h1 style, is that I had a conversation with @LTiger14 lately to move font sizes to css variables. We'll create a ticket soon to pick that up.

**Comment by Xymmer** [comment]
ok passing then
