### ISSUE TITLE
Move breadcrumb to separate slot

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1267]
Currently the breadcrumb component is added to most (or all) pages, while the design doesn't show it  everywhere. Moreover the current location of the breadcrumb in the cms structure is not aligned with the design. There are 2 places where the breadcrumb shows up:
1. below the header navigation
2. below the hero image (i.e. on the category search result page, see https://app.zeplin.io/project/5a836f2897c4a02f0105b093/screen/5b7ed26c2ebe9560042e24f5). 

The current position of the breadcrumb comes with 2 problems:
1. the css becomes complicated, as the breadcrumb is combined into the navigation slot, which in the UI is placed inside a container with a max-width.
2. we cannot support the category search layout where the breadcrumb is placed somewhere else. 

I suggest we move the breadcrumb to a separate slot. The slot would not be part of the header page layout config.

**Comment by tobi-or-not-tobi** [comment]
@WeizhengSap would you mind if introduce a temporary interceptor for this, until we fixed it in the backend? The interceptor will suggest the new structure and we can move it with the help of that implementation to the backend. It will no longer block us to move the title/breadcrumb forward.

**Comment by WeizhengSap** [comment]
@tobi-or-not-tobi : go ahead for the temporary interceptor :)

**Comment by tobi-or-not-tobi** [comment]
This seems to be fixed as part of #1360.
