### ISSUE TITLE
Config mapping for "FlexCmsComponent" (from 986)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1270]

**Comment by Platonn** [comment]
Should work similar as JSPIncludeComponent (GH-1079).
More description in GH-986

**Comment by WeizhengSap** [comment]
There is "selector" attribute in "FlexCmsComponent". Use the attribute value, e.g. "cx-login" to find the corresponding angular component and dynamically create it in the slot.

**Comment by Platonn** [comment]
QA Steps:
- the same as in https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1326

**Comment by Xymmer** [comment]
i see flexcmscomponent
![image](https://user-images.githubusercontent.com/4998145/53502233-a67b5600-3a7b-11e9-8aac-d278be489d92.png)
