### ISSUE TITLE
Remove deprecated TSLint extension

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#1289]
VScode's TSLint extension has been deprecated in favour to Microsoft's  https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin

We should switch to it, make sure that all the linting rules are working as before and update `extensions.json` file.

**Comment by Xymmer** [comment]
not sure where exactly but i think we need to update one of the docs in https://github.com/SAP/cloud-commerce-spartacus-storefront/tree/develop/docs/contributing

**Comment by znikola** [comment]
You are probably referring to this part: https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/contributing/dev-tools.md#workspace-extensions.
But it doesn't mention any particular extension, it only says: "You can see the list of recommended extensions in .vscode/extensions.json."
