### ISSUE TITLE
Use browser history doesn't trigger changes in the PLP

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1311]
When you're on the PLP, and use pagination, the browser history doesn't update the listed items.

**Comment by tobi-or-not-tobi** [comment]
A few things are off:
- we seem to redirect after routing with default values (the uggly additional query parameters). I believe we shouldn't do this as they're all default)
- navigating back does affect some things (i.e. the new page title #1428), but the product listing component isn't updated.

Easy to reproduce:
- load homepage
- load a category page
- open a facet
- try to navigate back (no refresh of data)

**Comment by Pucek9** [comment]
back/foward are working correct only after use search-box
change category/page/fiter don't trigger ``[Product] Search Products`` action

**Comment by Pucek9** [comment]
I solved partly this bug, but Krzysztof confirmed it doesn't good solution, temporary I don't have more ideas how to fix it.

**Comment by tobi-or-not-tobi** [comment]
@Pucek9 please elaborate on what the solution was and why it isn't a good solution.

**Comment by Pucek9** [comment]
> please elaborate on what the solution was and why it isn't a good solution.

I created an additional effect, which is watching for route change by browser's previous/forward click. Then it uses one before last 'search' action.
This is not right because it's a workaround and works only for one backward action.

A good way is to observe the query params in component (they are correct) and to call from there the search. For me it doesn't work, always after search follows the second unwanted action with current query params.

**Comment by Xymmer** [comment]
i was supposed to ping tobias but assigned back to Michael to follow up with Tobias or seek help from other devs.

**Comment by Platonn** [comment]
# QA steps
- verify that no query params (i.e. `?query=....`) are present when you open initially search/category/brand page. Query params should appear only when you start playing with sorting/pagination/facets.
- verify native browser back navigation brings you to the previous state of the query/sorting/pagination/facets.

In general play with facets, pagination, sorting and native browser back navigation. Also meanwhile go to:
- different category page (from navigation categories menu)
- search a phrase in the search box
- go to some brand page (if Brands menu is available in your env - dev17 / modelT, not sure which)

**Comment by giancorderoortiz** [comment]
Test successful. 🆗 
Given initial state at x0 and facets, x1, x2, x3 applied in sequence, I can see how using browser's back navigation button, PLP returns to x2, x1, x0 correctly. Nice fix. 
Tested on Firefox as well.
