### ISSUE TITLE
Generate CompoDoc(s) automatically

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1315]
write script to generate the doc and push it into 'docs' or 'wiki' (needs spike)

**Comment by hackergil** [comment]
You can see the checked in docs here
https://github.com/hackergil/cloud-commerce-spartacus-storefront/tree/feature/GH-1229/docs/compodoc
Github does not display them as a web page but as source. We need to host them on a static web server.
- We could use github pages, but we are currently hosting spa there.
