### ISSUE TITLE
Doc for customizing styling for Beauty

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1317]
Goal is to have guidelines for how to configure Spartacus styling, so that someone else (cough Brian cough) can style the Beauty project following the steps.

Next step is to give such file to Walkers (?) so that they can build spartacus using style config file.

In summary, as if a customer was doing it with SCC.

**Comment by gladius-mtl** [comment]
Follow-up ticket GH-1497 created to do a full edit and review 😄
