### ISSUE TITLE
Adding different viewports to e2e testing

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#1321]
Our e2e tests only tests the desktop version of our application, but we do not know if it works perfectly for different viewports. Therefore, it would be best to include 'mobile' versions in order to not miss any bugs or errors.

Nightly builds (or at will), because essentially we're running the tests 6 times.
Update DoD as well.

**Comment by KateChuen** [comment]
Yes, totally agree with that. Add viewports for:
[ ] small desktop 
[ ] wide desktop 
[ ] tablet
[ ] small mobile (for eg, iphone 5)
[ ] big mobile (for eg, iphone 7+)

**Comment by Xymmer** [comment]
For this ticket, the goal is to make sure that we are running all e2e tests at different viewports.

If tests fail: create bug or update e2e test.
Then we do a bug triage based on found issues.

Future: what new e2e tests should be created that are specific to mobile?
Or if a modification to an e2e is big, just create the ticket and we'll refine together.

**Comment by bgambocjaviniar** [comment]
PR #1615
