### ISSUE TITLE
compare OCC API specs - new and old

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1325]
About half year ago we've generated Typescript types from the Swagger 2.0 specification of the OCC API. Now we've received an updated specification and we would like to compare them.

**Comment by Platonn** [comment]
Issues with new API specs:

### Removed important types
- removed `CMSPage` type (which had detailed descendant types like `ContentSlotList`, `ContentSlot`, `ComponentList` and `Component`). In place of detailed `CMSPage` type there came a general `PageAdaptedData` type and defined simply as `object`. We will discuss it with the team responsible for CMS API

### Renamed types
- old `Pagination` type was renamed to `DeprecatedPagination` and new `Pagination` type was introduced

### Missing properties
- `PaymentDetails` type lost it's `cvn` property in new specs

### Deprecated endpoints:
- `/{baseSiteId}/cms/components`, method `POST`
- `/{baseSiteId}/deliverycountries`, method `GET`

### Other issues:
- generic `fields` parameter of the 74 calls has strict enum type in API specs: `enum: [DEFAULT, BASIC, FULL]`. However we know that backend accepts any custom string as `fields` parameter. We will create a RAY ticket to loosen the type of `fields` parameter to `string` in backend.

**Comment by tobi-or-not-tobi** [comment]
For the generic fields parameter issue, we've created an OCC ticket: https://jira.hybris.com/browse/RAY-246
