### ISSUE TITLE
Fix SmartEdit contract for JSPIncludeComponent

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1326]
When JSP component is displayed in SmartEdit (for example `AccountAddressBookComponent`), an error occures due to the broken SmartEdit contract: 
![obraz](https://user-images.githubusercontent.com/4001059/53238679-34c99380-369a-11e9-9105-50628b15c03e.png)

---
By convention, the `uid` of JSP component is used as a component type in the cms mapping logic in Spartacus.

Previously, by mistake, this `uid` it was also used to generate `data-smartedit-component-type` attribuite for smart edit contract. But should be the original component type - "FlexCmsComponent" .

**Comment by Platonn** [comment]
### QA steps
- pretend that the app is lanuched in SmartEdit - by editing one line in `cms.service.ts`:
  ![obraz](https://user-images.githubusercontent.com/4001059/53238325-537b5a80-3699-11e9-899e-66152018a82a.png)
- check that JSP components have proper html smart edit attribute `data-smartedit-component-type="JspIncludeComponent"`, for example:
  - log into our app and navigate to address book
  - in dev tools search for `AccountAddressBookComponent` (which is the `uid` of address book JSP component) and verify its html smart edit attributes:
   ![obraz](https://user-images.githubusercontent.com/4001059/53238187-ed8ed300-3698-11e9-89e5-d217270b3889.png)

### Final QA steps
- ideally it should be tested in smart edit

**Comment by Xymmer** [comment]
we'll test smartedit separately with #1463 as we need to update smartedit environment. The code inspect will suffice to pass.

**Comment by Xymmer** [comment]
works with model t server, which is still serving jsp includes... passsing

**Comment by KateChuen** [comment]
Tested with the new type using smartedit. No such error was displayed when accessing the addressbook page from SE.
![addressBookPage](https://user-images.githubusercontent.com/45409515/57464344-8a99ea80-724a-11e9-8d35-bd47d1e91bf4.png)

Also tested with the old type, by importing the following impex provided by Wei

> $contentCatalog=electronics-spaContentCatalog
$contentCV=catalogVersion(CatalogVersion.catalog(Catalog.id[default=$contentCatalog]),CatalogVersion.version[default=Staged])[default=$contentCatalog:Staged]
REMOVE CMSFlexComponent;$contentCV[unique=true];uid[unique=true]
;;AccountAddressBookComponent
INSERT_UPDATE JspIncludeComponent;$contentCV[unique=true];uid[unique=true];name;page;actions(uid,$contentCV);&componentRef
;;AccountAddressBookComponent;Account Address Book Component;accountAddressBookPage.jsp;;AccountAddressBookComponent
UPDATE ContentSlot;$contentCV[unique=true];uid[unique=true];cmsComponents(uid, $contentCV)
;;BodyContent-address-book;AccountAddressBookComponent

And no such error was displayed when accessing the addressbook page from SE either.
<img width="1432" alt="addressBookOldType" src="https://user-images.githubusercontent.com/45409515/57464334-866dcd00-724a-11e9-8f56-c7e05ad8a230.png">
