### ISSUE TITLE
Move urlEncodingParameters defaults to shell app

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#1343]
And expand default currencies to accomodate more values

**Comment by dunqan** [comment]
QA steps:
1. Check if it is possible to run spartacus with different site than electronics
2. Check if removing siteCoontext configuration from app.module.ts will disable language and currency support in url (intended behavior for our libs)

**Comment by Xymmer** [comment]
tested on apparel-uk and apparel-de, worked
was also able to change defaults in config to de/EUR for apparel-de
and removing sitecontext worked as described.
passing...
however, if i set the defaults to en/usd and then try a url with de/EUR. the site completely hangs. created #1454
