### ISSUE TITLE
Update webApplicationInjector.js

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1349]
Update the webApplicationInjector.js to the latest version to make sure we don't have the security issue present in older versions.

See security bulletin: https://help.hybris.com/1808/hcd/13b899e25fd84a9da7c1e80ec4de5c03.html#loio13b899e25fd84a9da7c1e80ec4de5c03

**Comment by WeizhengSap** [comment]
download the latest version from here: https://stash.hybris.com/projects/CMSX/repos/smartedit/browse/smarteditaddon/acceleratoraddon/web/webroot/_ui/shared/common/js/webApplicationInjector.js

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1366
