### ISSUE TITLE
Handle many items in category nav menu

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1352]
See screenshot
Apparel 'Brands' has a long list of items
We should scroll after a configurable # of items and/or automatically put into columns (brainstorm what's best to do considering we also support a second level already)

![image](https://user-images.githubusercontent.com/4998145/52978829-e74edd00-33a0-11e9-906b-8ad5eb29ab37.png)

**Comment by Zeyber** [comment]
Don't know where to find this "Brands" list. It/was it a filter? Is this depreciated?

**Comment by marlass** [comment]
Change content catalog from `electronics-spa` to `apparel-de`. You should then see different assortment, menus and so on.

**Comment by Zeyber** [comment]
I am getting response "Base site apparel-de doesn't exist". Same with `apparel-uk` and `apparel`.

**Comment by Xymmer** [comment]
i added occ impex to https://dev-com-5.accdemo.b2c.ydev.hybris.com:9002 which has apparel
Accelerator is https://apparel-uk.dev-com-5.accdemo.b2c.ydev.hybris.com:9002/yacceleratorstorefront/

**Comment by Pucek9** [comment]
url for testing http://localhost:4200/apparel-de/de/EUR/

**Comment by KateChuen** [comment]
Tested on dev2.
![apparelDESPa](https://user-images.githubusercontent.com/45409515/59061499-a906fc00-8871-11e9-876a-e2b2a487fc65.png)
