### ISSUE TITLE
Spike: Add breadcrumbs

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#136]
Implement breadcrumb feature.
We have a submission from the community (yay!) - see #823.
Check if we can use their work.
Come up with a plan and run it by Tobias first.
Wei said their is a breadcrumb component, but it's not cms right? Bill isn't clear.

Here's the list and format for breadcrumbs.

### Categories and Product Details
Breadcrumbs for categories should handle whatever number of levels is available. Three levels of category is provided as an example.

Page | Example | Notes
--- | --- | ---
Categories | [cat1]() > [cat2]() > cat3 | last breadcrumb no link as its same as page you're on
Product details | [cat1]() > [cat2]() > [cat3]() | last breadcrumb is a link this time

### My Account
The proposal is to add "My Account" in the breadcrumbs but it's not a link for now. If it makes more sense / is easier to make "My Account" a link, we need a page for it. Create a dummy page then a new ticket for filling it in. Talk to Bill about what it would contain.

Page | Example
--- | --- 
Account Profile | My Account > Account Profile
Address Management | My Account  > Shipping Addresses
Payment Management | My Account > Payment Options
Order History | My Account > Order History
Order ### Details | My Account > [Order History]() > Order ### Details

### Pages that don't need breadcrumbs
For pages that don't require breadcrumbs, it's feasible a customer wants to add them. Bill wants to know if it's possible to put a tag/component in anyway but it's empty and not rendered. If it's too complicated, just leave it out.

Page | Notes
--- | --- 
| Home | not needed |
| Search |  there's already "133 results for camera" title |
| Sign in | not needed |
| Registration | not needed |
| Cart | not needed |
| Checkout | not needed - there's already 'tabs for each step |

**Comment by kacperknapik** [comment]
refinement needed

**Comment by tobi-or-not-tobi** [comment]
@Xymmer business questions:
- What should the breadcrumb represent: 
  - the current **user journey** (i.e. /promotions/vegetables/product/1234) or
  - the **static path** (i.e. /product/1234)
- What if there are multiple paths to the "page" (i.e. /product/1234 vs /promotions/product/1234)

**Comment by tobi-or-not-tobi** [comment]
In order to allow for customisations and extensions of breadcrumbs, we should not add the breadcrumb logic inside the breadcrumb component. Ideally the component only renders breadcrumb parts (label, route). 
Configurable routes should also be taken into account.

**Comment by Xymmer** [comment]
moving to framed as tobias said maybe kris might be free to take this

**Comment by Xymmer** [comment]
closing as breadcrumbs is on its way - see z/breadcrumbs epic
