### ISSUE TITLE
Move breadcrumb to right place in CMS

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1360]
Since #1266 we leverage the breadcrumb in the storefront. By design, the breadcrumb should not be part of the navigation slot (as the navigation lives in a container with a max with). To that reason, we like to move the breadcrumb component to the `BottomHeaderSlot`. Moreover, the breadcrumb – according to visual design – should not be available on each and every page. 

**Tasks**:

1. sample data: Remove breadcrumb from NavigationBar 
2. sample data: Add breadcrumb to BottomHeaderSlot (BottomHeaderSlot must be part of page template(s))
3. sample data: Override (clear) BottomHeaderSlot slot for home page (breadcrumb shouldn't be here)
4. sample data: Override (clear) BottomHeaderSlot slot for category/578. Add breadcrumb component to section1 (after hero banner). 

When changes are done, we should drop the `HardcodedBreadcrumb` interceptor.

**Comment by WeizhengSap** [comment]
PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/20/overview

**Comment by Xymmer** [comment]
how to test? does server need updating since PR was merged just yesterday?

**Comment by bgambocjaviniar** [comment]
The small backend fix will be added in here 
https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/24/overview PR #1445
