### ISSUE TITLE
[blocked] drop hardcoded layout for register page

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1364]

**Comment by tobi-or-not-tobi** [comment]
blocked by #1466

**Comment by tobi-or-not-tobi** [comment]
QA steps: 
- amend content on CMS register page
- see changes in Spartacus register page

**Comment by tobi-or-not-tobi** [comment]
`/register` is now available on dev17

**Comment by tobi-or-not-tobi** [comment]
In order to pass the pipeline, I've manually created the register page and slots on the pipeline backend.

**Comment by Xymmer** [comment]
passing. was able to change the page title and url through backoffice as well as add a logo underneath main slot.
