### ISSUE TITLE
Replace the use of JspIncludeComponent by CMSFlexComponent in reset password.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1367]
Depends on GH-1270 

Replace the use of JspIncludeComponent by FlexCmsComponent in the two pages of the reset password flow.

**Comment by WeizhengSap** [comment]
PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/33/overview

**Comment by KateChuen** [comment]
Tested on dev22. 
Typecode is _CMSFlexComponent_
No Jsp found on the page.
![pageContentResetPwd](https://user-images.githubusercontent.com/45409515/54940528-41dbdb80-4f01-11e9-9b47-41508f63a293.png)
![typeCode](https://user-images.githubusercontent.com/45409515/54940635-81a2c300-4f01-11e9-9ee2-541da40cd088.png)
