### ISSUE TITLE
Carousel's product is invisible when double clicking the arrow

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#1369]
## Steps to Reproduce

- Go to homepage
- Scroll down to one of the carousels (Our Best selling Products or What's New)
- Double click the arrow

## Observed Results

The products on the carousel are not visible

## Expected Results

The products on the carousel should be visible

**Comment by mszczepaniak** [comment]
Fixed in #1049
