### ISSUE TITLE
Storefinder: Search improvements

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#1372]
- [x] 1. Searching anything in store finder always returns the same list with 23 stores. 
_Update: After talk with @Xymmer and @frankgrupe turned out that on our dev OCC servers some pieces of functionality for geo location are disabled. We are not able to get valid results. So for now we should keep that list as it is and use exactly what OCC returns wtih the query. In a future we can test it hard with real values in SCC env._

- [x] 2. Add information on the page about results based on pagination (example: 1-10 from 49 stores found).
- [x] 3. Selected item on a list should have different background.

Example:
![requirements](https://user-images.githubusercontent.com/6958810/54740743-86dbd700-4bbc-11e9-9d1d-10ed815b1bcb.png)

**Comment by mirkosoft** [comment]
checked in postman: no matter what query we use backend response is the same (23 items)

**Comment by KateChuen** [comment]
Should also adjust the "storefinder e2e test" if needed.
