### ISSUE TITLE
evaluate ** approach for any content page

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1375]
We've implemented a ** route for content page, but will evaluate if it's still OK as we're considering an alternative approach to render content pages.

**Comment by tobi-or-not-tobi** [comment]
The implementation was done in #846

**Comment by Platonn** [comment]
Currently the page labels are different than ULRs for some content pages. It would be good to update page labels in the backend:
| from                              | to                      |
| --------------------------------- | ----------------------- |
| termsAndConditions                | terms-and-conditions    |
| contactUs (if page exists in CMS) | contact                 |
| orders                            | my-account/orders       |
| cartPage                          | cart                    |
| orderConfirmationPage             | order-confirmation      |
| address-book                      | my-account/address-book |
| orders                            | my-account/orders       |
| payment-details                   | my-account/address-book |
| multiStepCheckoutSummaryPage      | checkout                |
| storefinderPage                   | store-finder            |

The reset/forgot passowrd feature is under development now so we should not modify page labels now now, but revisit later.

For further investigation (GH-1377):
- what page label should have the Order Details page? It has url with param `'my-account/orders/:orderId` so it cannot simply be the page label value
- how to support nested routes of content pages?

**Comment by dunqan** [comment]
Issue #1640 was created after QA
