### ISSUE TITLE
Get preview token and download the cms page based on the token

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1378]
SmartEdit contract is missing something.
We need to load cms page data only based on token.

smartedit sends request e.g. http://localhost:4200/cx-preview?cmsTicketId=6477319597579360769d25e9-5607-45b3-9931-391163b893a2 to SPA.
Now, SPA has this:
```
home: { paths: ['', 'cx-preview'] },
```
So, SPA loads homepage data, when it is launched from smartedit. 
It works well when we click "Homepage". But, if we go to PAGES, and open one of them, we will meet some problems. 
When open one page from PAGES list, smartedit sends request http://localhost:4200/cx-preview?cmsTicketId=6477319597579360769d25e9-5607-45b3-9931-391163b893a2 to SPA as well. But, the cmsTicketId has pageId in it. This pageId will replace the "pageLabeOrId" we set in SPA.
So, when we open e.g. "faq" page, the request will be https://localhost:9002/rest/v2/electronics-spa/cms/pages?pageType=ContentPage&pageLabelOrId=homepage&cmsTicketId=xxxxxx

The occ api get pageId "faq" from cmsTicketId and then replace "homepage". So, "faq" data will be downloaded, which just what we expect. But, in ngrx store, we have page index, which make homepage points to faq page.

We append cmsTicketId to all cms occ calls, so that mean, for any other pages we only can load "faq" page data, because the cmsTicketId replace the pageLabelOrId passed.

So, we need to get new cmsTicketId which doesn't contain pageId. (This will be done by smartedit https://jira.hybris.com/browse/CMSX-8489)

What we need to do in this ticket is:
1. Give "cx-preview" a PageContext. The pageLabelOrId can be anything, because it is not used to download page. (we use cmsTicketId to download page). We only need PageContext to save and select page state. So, we can give the PageContext.id ="smartedit-preview" and PageContext.type=ContentPage

2. In cms occ, we check PageContext. If the id is "smartedit-preview", we will not send any PageType or PageLabelOrId or code. 
Check the following example, we only pass cmsTicketId to the occ api, then we can get "address-book" page.

![screen shot 2019-02-21 at 11 06 56 am](https://user-images.githubusercontent.com/44440575/53183182-d54f8300-35c8-11e9-9d04-c255852ca502.png)

![screen shot 2019-02-21 at 10 53 49 am](https://user-images.githubusercontent.com/44440575/53183082-b18c3d00-35c8-11e9-9bfd-abb781e88b6a.png)

----------------------------------

Second tickets, Stan is working on: getting routes from cms page
#1375 and #1377 

once this is fixed, we can try again cloning pages (which currently doesn't work).

**Comment by WeizhengSap** [comment]
https://jira.hybris.com/browse/CMSX-8481

**Comment by WeizhengSap** [comment]
To code review or QA, if you don't fully understand this ticket, contact wei.

**Comment by princesoni1989** [comment]
Hi All,
When smart edit opens the Spartacus application, how does it know which page to load?
how does Spartacus know page id so that it can make calls to load that particular page data?

For example, if smart edit opens Spartacus page `termsandcondition`, it makes a hit to get `termsandcondition` page data based on pageLabelOrID. My question is how does pageLabelOrID is passed from smart edit to Spartacus.
