### ISSUE TITLE
Clean electronics-spa

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1379]
Spartacus only needs a subset of pages that are in electronics-spa.
1. remove pages that Spartacus currently is not using.
2. remove reorder nav node

should be a good start.

**Comment by WeizhengSap** [comment]
In smartedit, go to page list. You have to check each page to see whether we have it in SPA. Then remove the one SPA doesn't have, for example:
![screen shot 2019-02-21 at 9 57 23 am](https://user-images.githubusercontent.com/44440575/53178113-3f632a80-35bf-11e9-8015-4a86771d6753.png)

**Comment by WeizhengSap** [comment]
In smartedit, go to navigation nodes. Remove this one:
![screen shot 2019-02-21 at 9 55 37 am](https://user-images.githubusercontent.com/44440575/53178205-66b9f780-35bf-11e9-8543-2bdf9cd6d593.png)

**Comment by znikola** [comment]
PR: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/31/diff
