### ISSUE TITLE
Change FlexComponent `selector` attribute to  `flextype`

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1382]
When we introduced the new FlexComponent, we added an attribute `selector` and added an JS component selector to it. We decided to change this attribute to `flextype`. We will migrate existing JspIncludeComponents to FlexComponent and copy the uid to the flextype attribute.

**Comment by WeizhengSap** [comment]
PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/23/overview
