### ISSUE TITLE
1b. Adding second option to login component

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1387]
In accordance to the mocks for the Guest Checkout, the options in a "forced login" should be different from the regular login. In regular login the second option is "Register" where but in the forced login it's "I don't have an account" (or something similar see mocks).

[ ] Create a second "Register" (I don't have an account) button that is hidden in the default login. This button leads to the guest login page.
[ ] Read the data field in the login request for a "forced" flag. If true hide register button and display I don't have an account button. If no forced flag is present it should be assumed it's false

### Acceptance criteria:
- When redirected from checkout to the login page a user doesn't see the register button but instead sees "I don't have an account"
- Accessing the login page in any other way shows the register button
- The "I don't have an account" leads to the guest login page

**Comment by mirkosoft** [comment]
@mszczepaniak @LTiger14 according to my comment in the #1182 `queryParam` is used instead of route `data`.
