### ISSUE TITLE
Add category title to category listing

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#139]
The category title is the "name" field returned when you get a category.
e.g. black and white film is 598:
`/catalogs/electronicsProductCatalog/Online/categories/598`
and you get
```
{
    "type": "categoryHierarchyWsDTO",
    "id": "598",
    "name": "Black & White Films",
    "url": "/electronics/catalogs/electronicsProductCatalog/Online/categories/598"
}
```

**Comment by Xymmer** [comment]
to clarify, when i click Hand Held Camcorders, i see "x restults for cameras"
![image](https://user-images.githubusercontent.com/4998145/49098713-8a2e0a00-f23d-11e8-95da-1dac7a790711.png)

We'd like it to say "x results for Hand Held Camcorders"
is that info available in the api results?

**Comment by Jim-Yang** [comment]
Being fixed in PR GH-504
