### ISSUE TITLE
[LATER] Add the registration form to guest login page

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1394]
The user login UI was done as part of #1193 but without the registration form and the toggle button.

To do:
[ ] Add the html/css for the registration form and toggle between user login in registration as seen in the UX mocks

### Acceptance criteria
- Able to see the register form in the guest login page and toggle between both forms on the page

**Comment by Xymmer** [comment]
dupe of #1178
