### ISSUE TITLE
Implement PDP breadcrumb

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1398]
With #1266 we've started to create the foundation for the breadcrumb component. We have however only implemented the title and a static home link. This ticket will create the foundation for breadcrumbs as well as the PDP implementation.

Each page should be able to contribute to the stream of crumbs. This can be done similar to the PageTitleResolvers (i.e. BreadcrumbResolver). This allows us to provide different implementations for different pages, but moreover, the implementations are extendible and (new) custom once can be added. 

PDP crumb:
  - home / category a / category b
  - home / search / results 
  - home / cart 
  - home / order history / order 

Whenever we load the PDP without context, we will cannot display detailed crumbs (most customer will however show the first category the product lives in)

**Comment by tobi-or-not-tobi** [comment]
We're currently blocked by a missing field in the `/product` endpoint, see https://jira.hybris.com/browse/RAY-260.

**Comment by tobi-or-not-tobi** [comment]
Release on dev-22 has category titles

**Comment by Xymmer** [comment]
Implemented for pdp, for categories only
If i search i still see categories in breadcrumb
Is that intended? @tobi-or-not-tobi

**Comment by Xymmer** [comment]
passing as it corresponds with agreed-upon scope
