### ISSUE TITLE
Add page title to html title tag

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1399]
The page title which has been implemented for the the breadcrumb will be used for the html title tag. Adding an html page title has several advantages:
- the page can be uniquely addressed in the browser (browser history, bookmarks, tabs, etc)
- the page title will increase ranking the page in search engines
- the page title will identify content in search engines

The page title will be updated dynamically, but can be delivered statically using SSR. 

The page title tag will use by default the the page title used in the breadcrumb, but customer must be able to provide a custom implementation. A future version of the page title could come up with some common additional features:
- configurable prefix (i.e. "**prefix** homepage" vs "**custom prefix** homepage" )
- configurable delimiter  (i.e. "prefix **|** homepage" vs  "prefix – homepage" )

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- navigate through storefront
- verify that the page / tab title in the browser reflects the page
- optionally: install a plugin (i.e. https://www.omiod.com/meta-inspector.php) and validate that the title is present on initial page and when navigating to other pages)

Heavy QA (we can skip for now):
- render on SSR
- validate the page title is in the html title tag

**Comment by Xymmer** [comment]
verified, very cool
