### ISSUE TITLE
shipping tab content is not displayed in product details page

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#1408]

**Comment by Pucek9** [comment]
![image](https://user-images.githubusercontent.com/8040837/53335888-f849a200-38fc-11e9-9a7d-787766561f77.png)

**Comment by Pucek9** [comment]
Should fix test 'should contain tabs with correct text' skipped in #1128

**Comment by Pucek9** [comment]
Problem has occurred after merge https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1391

**Comment by Xymmer** [comment]
passed on dev17 feb27 with latest spartacus
