### ISSUE TITLE
Remaining storefinder e2e tests

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1409]
From #736
E2E test suggestions, but our mock always returns same data. Do what we can here.
- [ ] 1-10 from 49 stores found (no such information on page)
- [ ] First store highlighted (store is not highlighted)
- [ ] Test searching for other location, for eg “New York” and click on the “search button” (search returns always the same list though because it's a mock)

**Comment by Matejk00** [comment]
Important: It should be done when following storefinder bugs will be fixed:

https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1372
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1470
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1469
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1468
