### ISSUE TITLE
[Master] Make checkout CMS driven and extendible

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1410]
The Checkout process is currently hardcoded. Since it is a large component with multiple steps involved, it is very hard to extend. Customers will end up with a lot of copy/paste of the standard checkout for small additions. Moreover, the flow isn't extendible for business users as it's all hardcoded. 

Customers and other industry libraries will have a lot of requirements to add:
- change from multi-step to single step process
- customise existing checkout steps
- add additional steps in between standard checkout steps
- reorder the steps
- add content to different parts of the checkout process for up-sell, cross-sell, promotions, and additional messaging to the end user.

In order to make the checkout process customisable, we have a number of solution directions in mind:
- each checkout step should become a CMS component. This allows for more fine-grained replacements or amendments of the checkkout step
- the checkout process should be driven by content pages, this allows for: 
  - navigation of steps(pages) through browser history. 
  - add additional content to each page (using ordinary slots and components)
  - customise the number of steps, i.e. add a step (= page)
  - have all components on one page (going from multi to single step)
  - leverage standard extensibility concepts, such as customisable routes (contentPage.pageLabel) page layouts, outlets)
  - introduce alternative checkout flows (i.e. for A/B testing of the checkout flow)
  - introduce personalised steps (i.e. a specific step for a gold-user)

The missing piece with the above solution is the ability to connect pages and dictate the order of the steps. The CMS doesn't offer this as capability. Therefor we could introduce a configuration for this in the JS app that allows to connect multiple pages to the checkout process. The order confirmation steps should be part of this as it's another optional step that could be amended as well. 

Another area of interest is the validation logic that is required to go from step to step. Each step in the checkout process contributes to the wider checkout form. Ideally we leverage angular reactive forms with a (customisable) form model and (customisable) validations. 

**Note**: the current backend has a configuration to dictate the checkout flow per cms site. The initial intend was to use this as a feature flag on the site. This is only a string, typically providing _single_ or _multi step_ proces. We do not necessarily follow this feature flag as the above solution is mainly  CMS driven and therefor more flexible.

**Comment by WeizhengSap** [comment]
I like this idea. Just have one thought, can we make each process step as one slot, instead of one page?
so, customers still can add new steps or reorder steps, or put all steps in one page...
I think manipulating slots is easier than manipulating pages
we can easily make one slot (step) invisible. 
So, for our current checkout, we will have 5 slots: nav-bar-slot, step1-slot, step2-slot, step3-slot and step4-slot
we have some functions to process and go to next step. They can be moved to checkout.service

**Comment by tobi-or-not-tobi** [comment]
> I like this idea. Just have one thought, can we make each process step as one slot, instead of one page?
> so, customers still can add new steps or reorder steps, or put all steps in one page...
> I think manipulating slots is easier than manipulating pages
> we can easily make one slot (step) invisible.
> So, for our current checkout, we will have 5 slots: nav-bar-slot, step1-slot, step2-slot, step3-slot and step4-slot
> we have some functions to process and go to next step. They can be moved to checkout.service

As agreed over slack with @WeizhengSap: the layout advantages of separate pages is worth the additional price of configuring the page sequence.

**Comment by Xymmer** [comment]
keep this ticket open until the whole feature is done

**Comment by marlass** [comment]
Extensible checkout feature merged into develop. It will be part of the next release.
For docs monitor this ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2459
