### ISSUE TITLE
Hook up the new reset password OCC endpoint.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1412]
This is a follow-up ticket for GH-1220.

When the new reset password endpoint is available from OCC in the commerce suite back end, we need to hook it up to the the reset password screen.  https://jira.hybris.com/browse/RAY-239

**Comment by plabadie** [comment]
The New OCC endpoint is available.

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1627

**Comment by KateChuen** [comment]
Tested on dev22. Able to reset password and login with new password.

![NewPwdLog](https://user-images.githubusercontent.com/45409515/54940858-f4ac3980-4f01-11e9-84d9-2d5a04278a41.png)

![loginWithNewPwd](https://user-images.githubusercontent.com/45409515/54940702-ab5bea00-4f01-11e9-82da-abe819fb0112.png)
