### ISSUE TITLE
[waiting for docs] Enable SSR on spartacus installation scripts

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#1419]
We need Stan's docs in order to do this ticket.

Kate says we will likely want to have the choice to test with or without SSR.  I don't know if we need an installation parameter or if we can have one installation process and then we can chose to start the app with or without SSR.

**Comment by Xymmer** [comment]
closing as i think we can, but will ask kate to be sure

**Comment by KateChuen** [comment]
Re-opening it since it hasn't been done yet. 
Will add it to installation scripts, and we'll start testing with SSR enabled.
