### ISSUE TITLE
Render bannercomponent as SimpleBannerComponent

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1420]
BannerComponent is used only in legacy desktop, so we can either not support it or simply render it as SimpleResponsiveBannerComponent. We do the same with SimpleBannerComponent.

BGJ: EDIT: Changed SimpleResponsiveBannerComponent to SimpleBannerComponent because the banner and responsive banner is two different things*

**Comment by bgambocjaviniar** [comment]
PR #1522
