### ISSUE TITLE
Image is not displayed in search autocomplete & result page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1422]
## Environment Details
- Spartacus: dev branch
- Browser: chrome

## Steps to Reproduce
Type "Powershot" in the search field.

## Observed Results
A list of search results is displayed, but without image. If you select the second one listed, and goes to its pdp page, there is an image there.
<img width="976" alt="imageautosearch" src="https://user-images.githubusercontent.com/45409515/53366405-80d23d80-3911-11e9-98e1-617c1c2bb3de.png">

Same thing on the search result page:
<img width="1115" alt="searchresultpage" src="https://user-images.githubusercontent.com/45409515/53367208-892b7800-3913-11e9-98e1-e42b65892777.png">

## Expected Results
Should have an image displayed in the search autocomplete and search result page. (Is it because we don't have the data for it yet?)

**Comment by KateChuen** [comment]
Investigate why this is happening (could be a config issue with the media url).

**Comment by bgambocjaviniar** [comment]
This is fixed

**Comment by KateChuen** [comment]
Yes, confirmed, it's not happening on dev17 anymore.
