### ISSUE TITLE
Footer titles missing

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1424]
## Environment Details
* Spartacus: dev branch
* Browser: chrome

## Steps to Reproduce
Scroll to the bottom of the page

## Observed Results
Missing "title" of the 2 columns in the footer. It looks like this now:
<img width="1419" alt="footertitle" src="https://user-images.githubusercontent.com/45409515/53366921-c4797700-3912-11e9-8f5c-823d9af996b5.png">

And used to look like this:
<img width="1431" alt="beforefooter" src="https://user-images.githubusercontent.com/45409515/53366929-c80cfe00-3912-11e9-9e6e-4f9c577f64a7.png">

**Comment by Zeyber** [comment]
Not sure if this is still a bug as I only have access to public api and appears to be an issue with backend not providing titles.

**Comment by tobi-or-not-tobi** [comment]
Sample data issue, low prio, should be handled with #1833

**Comment by Xymmer** [comment]
fixed now, but this is another issue with links not appearing
