### ISSUE TITLE
Banners on search result page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1425]
## Environment Details
* Spartacus: dev branch
* Browser: chrome

## Steps to Reproduce
Search for a word, for eg "canon"

## Observed Results
Are the banners on the top and bottom of the page ok? Is it because it should have more banners in the layout, but no image has been uploaded?
<img width="919" alt="bannersonsearchpage" src="https://user-images.githubusercontent.com/45409515/53367108-4ff30800-3913-11e9-9d74-551bd933219e.png">
<img width="1438" alt="bannersonsearchpage2" src="https://user-images.githubusercontent.com/45409515/53367109-4ff30800-3913-11e9-9d1b-2ad11a35503f.png">

**Comment by Xymmer** [comment]
not an issue in spartacus. the banner should align with the left side of the body content, but the banner itself isn't wide enough. need to update sample data not spartacus i think.

**Comment by hackergil** [comment]
@Xymmer who can help us with updating imagery for this?

**Comment by Xymmer** [comment]
this has been fixed
