### ISSUE TITLE
Create PR for moving new types to cms2 extension

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1426]
Create PR in CMSX and send Bill the JIRA link

**Comment by WeizhengSap** [comment]
I want to confirm that, we want to move the new types to "cms2" instead of "accleratorcms".

**Comment by WeizhengSap** [comment]
cms2 PR is here: https://stash.hybris.com/projects/MDM/repos/wcms/pull-requests/947/overview
spacceleratorsampleaddon PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/27/overview

**Comment by WeizhengSap** [comment]
After cms2 PR merged and released, then spacceleratorsampleaddon PR can be merged.

**Comment by WeizhengSap** [comment]
To make these 2 components used by other stores, I have to create a PR to acceleratorcms.

**Comment by WeizhengSap** [comment]
We have to create a new PR for cms2: https://stash.hybris.com/projects/MDM/repos/wcms/pull-requests/963/overview.
And, we need wait wcms M22, then we can merge the PR in coreaccelerator.
