### ISSUE TITLE
Add page description tag for better CTR and social sharing

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1428]
Each page of the storefront could contain a description to improve the click-through-rate (CTR) on the SERP and for better exposure while sharing through social channels. While this is considered best practice, there are actually some occasions where the search engine is better capable to generate the description based on the context.

The formerly implemented PageTitleResolvers and SeoService seem a good foundation for SEO in general. With this ticket we'll refactor the code to make it available to multiple page tags.

**Comment by tobi-or-not-tobi** [comment]
QA Steps:
- browse to product detail page
- validate the page description tag being set

**Comment by Xymmer** [comment]
confirmed that <meta name=description... > contains content equivalent to the product's summary description. So for example 32GB SDHC Card has description "SD High Capacity" (which granted could be nicer sample data) and this appears
<meta name="description" content="SD High Capacity">

**Comment by Xymmer** [comment]
should we document this characteristic?

**Comment by tobi-or-not-tobi** [comment]
@Xymmer i've already documented this in the `seo.md` file. Mr. @gladius-mtl has already worked on an earlier version of this file. I'll do a few passes with multiple tickets on this files (have done a few already) before I ask him to move this to documentation.
