### ISSUE TITLE
Create register page in the electronic content catalog

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1433]
The register process is a new _page_ in the proposed visual designs. The page must be added to our sample data and the existing `NewCustomerLoginComponent` must be **moved** to this page. 

If not much of a trouble, I wouldn't mind to rename the `NewCustomerLoginComponent` to `RegisterCustomerComponent` or `RegisterUserComponent`.

It is preferred to use the `AccountPageTemplate` for this new page (`LoginPageTemplate` sounds like a better fit, but the AccountPageTemplate slots – 'BodyContent', 'SideContent' – will become our standard slots for most pages going forward for multiple reasons).

**Comment by WeizhengSap** [comment]
PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/25/overview
