### ISSUE TITLE
ComponentEffects canceling requests

### ISSUE THREAD

**Issue by ilicivan911** [SAP/cloud-commerce-spartacus-storefront#1434]
Problem is in the "component.effect.ts". When  multiple components are loaded,  of same type but different UID, all HTTP Requests get cancelled but the last one. This is because in this "ComponentEffects" switchMap is used, when changed to mergeMap everything works fine.

![2019-02-26_14h14_34](https://user-images.githubusercontent.com/48019341/53415194-dae60800-39d0-11e9-9fb2-f6a7c2b82567.png)

**Comment by tobi-or-not-tobi** [comment]
@ilicivan911 have you seen the response at your PR:

> This one will be obsolete after [GH-1196](https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1196) (#1253) will be merged,
> It probably also address the same issue as the above, with different approach (uses `mergeMap` to support loading multiple components in parraler with `groupBy` + `switchMap` to restart ongoing loading of the same component uid)

We're most likely publishing today/tomorrow a new release with this fix being added. Hope that solves your problem.

**Comment by Xymmer** [comment]
closing, assuming it's solved, but ping me if not
