### ISSUE TITLE
Add support for "TabPanelContainer" CMS container

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1436]
One example of Cms Container component is "TabPanelContainer" in product details pages. The 4 contained components are hard-coded in SPA. SPA should support CMS container components. The inner components ids one string separated by space. SPA get the ids and loads these inner components (in batch).

![screen shot 2019-02-26 at 9 04 17 am](https://user-images.githubusercontent.com/44440575/53418823-a52c2980-39a6-11e9-96af-74ed78fc7c59.png)

**Comment by Xymmer** [comment]
depends on CMSX-8493

**Comment by Xymmer** [comment]
Dupe of #1484
