### ISSUE TITLE
Clicking on show reviews on pdp page doesn't go to the reviews section

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1437]
## Environment Details
* Spartacus: dev branch
* Browser: chrome

## Steps to Reproduce
Go to pdp page of a product, for eg: http://localhost:4200/en/USD/product/458542
Click on "Show reviews"
<img width="1230" alt="showreviews" src="https://user-images.githubusercontent.com/45409515/53421412-9a27c800-39ab-11e9-81c0-be458df8000f.png">

## Observed Results
Nothing happens.

## Expected Results
It should navigate to the reviews section of the page

**Comment by KateChuen** [comment]
To be verified after the refactoring is done.

**Comment by mszczepaniak** [comment]
When clicking on the "Show reviews" I get a warning: "Translation key missing 'productDetails.label.reviews' in the chunk 'product"
