### ISSUE TITLE
Inconsistent Cart Total on cart page vs Review checkout page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1446]
## Environment Details
* Spartacus: dev branch
* Browser: chrome

## Steps to Reproduce
Add qty 1 of product1 to cart
Add qty 2 of product2 to cart 0 -> It should show 3 items in mini cart
Go to cart page -> It says cart total (3 items)
Proceed to the "Review" Step of checkout

## Observed Results
1) On cart page, the number of items is the total number of items in cart.
On Review checkout page, the number of items is the total number of _**different**_ items in cart.
2) The cart total on cart page is different to the cart total on Review Checkout page.

<img width="999" alt="carttotalcartpage" src="https://user-images.githubusercontent.com/45409515/53427148-64d4a780-39b6-11e9-979e-222b9de44630.png">
<img width="994" alt="carttotalreviewpage" src="https://user-images.githubusercontent.com/45409515/53427149-64d4a780-39b6-11e9-8164-0e84f9b019c3.png">

**Comment by Xymmer** [comment]
Spike what's wrong and talk to your tech lead and Bill about the solution.

**Comment by Matejk00** [comment]
Tested. Items cart total now is displayed properly on review page.
