### ISSUE TITLE
[test] Error for duplicate user on registration page is too general

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1447]
## Environment Details
* Spartacus: dev branch
* Browser: chrome

## Steps to Reproduce
Register userA.
Sign out.
Try to register with the same email as userA.

## Observed Results
The error displayed on the storefront is not meaningful. The user won't know why the registration has failed.
<img width="1041" alt="duplicateuserregister" src="https://user-images.githubusercontent.com/45409515/53430089-d82ce800-39bb-11e9-9d84-1ba0452ba57b.png">

**Comment by KateChuen** [comment]
Maybe a duplicate.

**Comment by Xymmer** [comment]
I couldn't find our spartacus issue, but ray is also working on this.
https://jira.hybris.com/browse/RAY-245

For now we could add some code that detects that all that was returned is the email, and display a message:
Cannot register this email address.

And then if the message is changed, we just display the message we get.

**Comment by Xymmer** [comment]
RAY issue is done, let's retest

**Comment by Xymmer** [comment]
checked with dev 17 apr25, still same. probably not updated yet

**Comment by KateChuen** [comment]
I updated dev2 yesterday night, and I see a different behavior (which is worse). It allows the user to register over and over again with the same email add.

**Comment by Xymmer** [comment]
let's document this behavior

**Comment by gladius-mtl** [comment]
Created a follow-up doc ticket, GH-2179.
