### ISSUE TITLE
Phone number is not updated after edit

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#1449]
To reproduce:

- navigate to `my-account/address-book`
- add an address (if there isn't any)
- click on `edit` and enter a different phone number than the previous

The phone number should be updated, but it remains the same.

**Comment by bgambocjaviniar** [comment]
This is going to be fix in https://jira.hybris.com/browse/RAY-279 as it is a backend-related issue.
