### ISSUE TITLE
After deleting an address the address card is still shown

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#1450]
To reproduce:

* navigate to `my-account/address-book`
* add an address (if there isn't any)
* click on `delete`

The address card should not be displayed, but it's still shown. 
However, after refreshing the page, the address is not displayed anymore.

**Comment by mirkosoft** [comment]
first finding is: it only happens when user has just one address (no matter is it default or not).

**Comment by mirkosoft** [comment]
moving this back to "to do" as switched to work on orders flow test migration (which is more important).

**Comment by mirkosoft** [comment]
Noticed the same issue when deleting payment methods. It might be more general issue then.

**Comment by mirkosoft** [comment]
I am leaving this issue for now as I am busy with others.

**Comment by kacperknapik** [comment]
PR which will close this issue, fixes the payment-details bug also

**Comment by Matejk00** [comment]
Tested. Now deleting address removes the card also.
