### ISSUE TITLE
footer containers h1 elements for each section title

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1451]
The footer navigation uses a `h1` element for each section. This seems too much of a heading for a section title of a list item of links. 
We should make it a lower level heading, i.e. `h3` or `h4`.

**Comment by Xymmer** [comment]
They are now an h5

**Comment by mikelMHybris** [comment]
The default font-size and style matches the default h5 styling we have in spartacus.
