### ISSUE TITLE
Go to unsupported URL /de/EUR if only /en/USD supported, site hangs

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1454]
when testing #1343, if i changed the language and currency in default-occ-config.ts, the site would hang and had to kill the process using chrome task manager.
e.g. i'd set it to apparel-uk with en and USD

**Comment by dunqan** [comment]
Should be fixed by #1461

**Comment by Xymmer** [comment]
yup fixed
