### ISSUE TITLE
[doesn't block release] Test #1326 in SmartEdit environment when updated

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1463]

**Comment by KateChuen** [comment]
Tested with the new type using smartedit. No such error was displayed when accessing the addressbook page from SE.
![addressBookPage](https://user-images.githubusercontent.com/45409515/57464344-8a99ea80-724a-11e9-8d35-bd47d1e91bf4.png)

Also tested with the old type, by importing the following impex provided by Wei

> $contentCatalog=electronics-spaContentCatalog
$contentCV=catalogVersion(CatalogVersion.catalog(Catalog.id[default=$contentCatalog]),CatalogVersion.version[default=Staged])[default=$contentCatalog:Staged]
REMOVE CMSFlexComponent;$contentCV[unique=true];uid[unique=true]
;;AccountAddressBookComponent
INSERT_UPDATE JspIncludeComponent;$contentCV[unique=true];uid[unique=true];name;page;actions(uid,$contentCV);&componentRef
;;AccountAddressBookComponent;Account Address Book Component;accountAddressBookPage.jsp;;AccountAddressBookComponent
UPDATE ContentSlot;$contentCV[unique=true];uid[unique=true];cmsComponents(uid, $contentCV)
;;BodyContent-address-book;AccountAddressBookComponent

And no such error was displayed when accessing the addressbook page from SE either.
<img width="1432" alt="addressBookOldType" src="https://user-images.githubusercontent.com/45409515/57464334-866dcd00-724a-11e9-8f56-c7e05ad8a230.png">
