### ISSUE TITLE
Add leading slash before ContentPage pages

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1466]
Some of the pages have been referenced by page id or by a pageLabel which doesn't act as a URL. We should change sample data for this:

| Old | New|
|---|---|
| login | /login
| notFound | /notFound
| register | /register

**Comment by hackergil** [comment]
Pull request:
https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/29/overview
