### ISSUE TITLE
[after #3943] Store Finder: No stores found if searching with my location from page 3

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1468]
## Environment Details

- Spartacus:  dev
- Browser: safari

## Steps to Reproduce
- Go to store finder
- Search for "tokyo" -> there are results returned.
- Click on "use my location"
- Go to the 3rd page of the results
- Now search for "tokyo" again, or any other location, for eg "kyoto".

## Observed Results
No stores found is returned.
<img width="1182" alt="nostoresfound" src="https://user-images.githubusercontent.com/45409515/53507147-530e0580-3a85-11e9-8655-18bcc1177914.png">

## Expected Results
Should return the results.

**Comment by Matejk00** [comment]
Should be done after #1372

**Comment by Xymmer** [comment]
#1372 is done

**Comment by Xymmer** [comment]
checking on april 8, now clicking the link after following repro steps, the link does nothing. so the bug here is to restart a fresh search using my location.

**Comment by Matejk00** [comment]
List takes data from the store, we should wait for #3943 to prevent conflicts.

**Comment by Matejk00** [comment]
Fixed in #4238
