### ISSUE TITLE
[After  #1372] StoreFinder: the numbering starts with 1 on every page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1469]
## Environment Details

- Spartacus:  dev
- Browser: chrome

## Steps to Reproduce
- Go to Store Finder
- Search for a location with more than one page result, eg: Tokyo
- Go to page 2

## Observed Results
The numbering of the stores starts all over again with 1. 
<img width="1232" alt="storenumbering" src="https://user-images.githubusercontent.com/45409515/53508218-51454180-3a87-11e9-985c-bb1fb0cad09b.png">

## Expected Results
Was expecting it to be continuous, so it would start with 21 on the second page.

**Comment by Matejk00** [comment]
Sould be done after #1372

**Comment by Xymmer** [comment]
Leave as 1. It's a bit weird but the 21 is for pagination and the 1 is for the map.
