### ISSUE TITLE
StoreFinder: Cannot go to a store details page from the result page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1470]
## Environment Details
* Spartacus:  dev
* Browser: chrome

## Steps to Reproduce
* Go to Store Finder
* Search for a location with more than one page result, eg: Tokyo
* Click on a store from there

## Observed Results
It shows it on the map, which is good. But there's no way to go to the store details page from there. 
<img width="1223" alt="storeselected" src="https://user-images.githubusercontent.com/45409515/53508418-b436d880-3a87-11e9-94d0-49a287e5e24e.png">

## Expected Results
What if I want to get more details about the store, phone number etc? Should have a way to go to the store details page from there.
The only way I found was to go to "All stores" and get it from there, which is a bit more painful for the end-user.
<img width="1229" alt="storeselectedallstores" src="https://user-images.githubusercontent.com/45409515/53508430-ba2cb980-3a87-11e9-869a-5826876e1dc9.png">

**Comment by Matejk00** [comment]
Should be done after #1372

**Comment by Xymmer** [comment]
#1372 is done

**Comment by Xymmer** [comment]
Display the company information underneath the map.

**Comment by kacperknapik** [comment]
I believe this is a lack of feature and not a bug. We should refine this one.

@Matejk00 @Xymmer

**Comment by Matejk00** [comment]
Following solution has been implemented: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1470#issuecomment-480799066

**Comment by giancorderoortiz** [comment]
I don't see a fix for this issue yet. Still can't go to store details page.

**Comment by KateChuen** [comment]
To test later. 
For now, "Store Finder" is hidden.
