### ISSUE TITLE
[investigating] breadcrumb's parentOverlay is empty

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1473]
In smartedit, we see the error of "parentOverlay empty for component: breadcrumbComponent". If you login, then you will also see "parentOverlay empty for component: MyAccountComponent"

![screen shot 2019-02-27 at 1 42 49 pm](https://user-images.githubusercontent.com/44440575/53517142-f10cca80-3a9b-11e9-85cd-8cfc3f99355a.png)

**Comment by Xymmer** [comment]
we're not sure how what's causing the problem
wei talking to riry who is talking to fred
we'll see

**Comment by WeizhengSap** [comment]
The reason of this issue was found. A new ticket was created: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1985

So, I will close this ticket.
