### ISSUE TITLE
06a Extract wordings to translation files

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1487]
It's the master ticket for extracting hardcoded wordings from templates and the code to translation files.

We should create detailed followup tickets when we have suggested strucutre of translation files as a result of spikes.

**Comment by Pucek9** [comment]
Proposal for divide namespaces:

Common components:
* HEADER
* FOOTER
* SUMMARY
* PRODUCT

Features:
* LOGIN (+ GUEST LOGIN)
* UPDATE FORGOTTEN PASSWORD
* REGISTER
* PAYMENT METHODS
* ADDRESSES
* SEARCH/BRAND/CATEGORY
* PRODUCT DETAILS
* CART (without SUMMARY, PRODUCT)
* ORDERS [CONFIRMATION] (without SUMMARY, PRODUCT)
* CHECKOUT [SHIPPING METHOD/REVIEW] (without SUMMARY, ADDRESSES, PAYMENT, PRODUCT)

**Comment by Pucek9** [comment]
Hint for verify - checkout to current env (app.module) and setup:
```
server: {
  baseUrl: 'https://dev-com-17.accdemo.b2c.ydev.hybris.com:9002'
},
site: {
  baseSite: 'electronics-spa'
},
```
This will allow you to change the language, for example to Japanese

**Comment by Pucek9** [comment]
Epic branch for our translations: epic/translation-fr2

In plurals case with we use: https://www.i18next.com/translation-function/plurals
