### ISSUE TITLE
Address verification modal close button is outlined by default

### ISSUE THREAD

**Issue by Matejk00** [SAP/cloud-commerce-spartacus-storefront#149]
Address verification modal close button is outlined by default. Tested on Chrome and FF in both cases outline appears together with popup.

## Expected Results
- Remove outline from close button.

## Steps to Reproduce
1. Login into some customer account.
2. Add some product into the cart.
3. Got to checkout.
4. Click 'Proceed to checkout' button
5. Click 'Add new address' button
6. Fill the form with some data and in 'City' field type only: 'review' word.
7. Click 'Continue', than verification modal should shows up
![screenshot2](https://user-images.githubusercontent.com/6958810/47710933-4cd15f00-dc34-11e8-8b6d-749fc20bbb01.png)
8. Close button is outlined by default.

**Comment by RomeroDiver** [comment]
This is behaviour comes from the ng-bootstrap implementation of modal

**Comment by RomeroDiver** [comment]
https://github.com/ng-bootstrap/ng-bootstrap/issues/2814

**Comment by Matejk00** [comment]
Fixed, now outline does not show up on init state.
