### ISSUE TITLE
BannerComponentService is not exported in the storefrontlib

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1490]
The BannerComponentService isn't exported in the public api. A few other best practices:

Whenever component services are created as part of the refactoring, we need to ensure that:
- the service is exported in the public_api of the library
- we carefully add the right modifiers to the methods:
  - public methods only for the public API of the service
  - protected methods for methods that could be overriden in an extended version
  - private only for methods that are used in the service and aren't supposed to be further extended (in general this should be avoided)
- constructor arguments should be at least protected
- constructor arguments should be limited; in case a lot of services are needed, we should compose an other service.

**Comment by KateChuen** [comment]
We'll make sure to add Tobias' feedback to our best practices doc.

**Comment by WeizhengSap** [comment]
I will close this ticket, because the `BannerComponentService` was removed.
