### ISSUE TITLE
4. e2e test for guest checkout

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1494]
Once FR1 is done for the guest checkout we should test it.

**This test should run as part of the regression tests (nightly).**

The tests should leverage the dynamic config injection:
```
context('Guest Checkout', () => {
  beforeEach(() => {
    cy.cxConfig({ features: { guestCheckout: true }});
  });
  /* ... */
});
```

Steps:
- Start anywhere not logged in
- Add product(s) to cart and go to checkout
- Should be redirected to login -> click continue as guest -> fill form
- Complete checkout and validate the order can be placed

**Comment by giancorderoortiz** [comment]
IMHO, there should also be a test whereas the user makes a random decision whether to continue checkout as guest, or as registered user. 
Login page, immediately after checkout button click, must work with either flows...
