### ISSUE TITLE
Configure JS application with runtime backend baseUrl

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#15]
A number of areas in the storefront is driven by configuration. The commerce backend API (`baseUrl`) is good example. Angular-cli provides a mechanism for different configurations per environment, but at the end of the day, the configured baseUrl is baked into the JS code. This means that the application cannot be deployed to various environments (dev, qa, prod); a new build is required for each and every environment. The same is true for the pipeline; the pipeline's backend must be aligned with the baked in configuration. 

When we deploy the JS app on a server, ideally, the server should provide a configuration to the JS app when it's served. Dev-ops can than reconfigure the backend baseUrl, and with the next request, the JS app will interact with the newly given baseUrl.

There are different possible solutions, none of them are standard (not in angular(-cli) nor in JS world).
- Provide a local config file in the JS app that can be read before the app start to bootstrap
- Provide a http header in the index.html
- Provide a script tag in the index.html
- Provide a meta-tag in the index.html

There a number of things we try to achieve/ avoid:
- we do not want to do a separate network request (which is the case in 1 and 2)
- we want a server agnostic solution
- we want an easy to use solution (2 is complicated for non-webserver devs)
- we want a layered approach (means, we could do multiple solutions, with fallbacks)

Based on this, we envision:

The storefront looks for meta-tag with a specific name, indicating the commerce backend base URL

`<meta name="occ-backend-base-url" content="https://localhost:9002" >` 

If the meta tag is not available (can be empty though), the config will fallback to configuration (what we have today). Customers can decide to configure the baseUrl or use a proxy to reroute the request. 

This architecture should be reused for other configurations, such as other backends.

**Comment by Xymmer** [comment]
not urgent at the moment
smartedit might take advantage of this too
could be done by other teams too

**Comment by tobi-or-not-tobi** [comment]
duplicate, fixed with #15
