### ISSUE TITLE
[Blocked] Can't check out with latest 1905

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1500]
When pointing Spartacus to latest 1905, check out stops after submitting payment info. This doesn't happen with earlier releases (1905 from feb 12) or 1811. Dev17 can be used for repro.

when you look at the api calls and response, it looks like the credit card info is not being sent.

1. Need to troubleshoot and deterine why Spartacus is not sending the info. There were changes to the OCC backend recently but it doesn't make sense that it affects Spartacus. For example: RAY-217 or RAY-234. At the same time we can't figure out why SPartacus would work with an older backend. The only difference might be that the newest backends are using Java11.

2. if the payment provider says some fields are missing and rejects the request, how come we aren't even displaying an error message? maybe a new ticket should be created for this.

Here is part of the response when we send cc data to sop url.

```
<input type="hidden" id="MissingField2" name="MissingField2" value="card_cardType" />
<input type="hidden" id="billTo_email" name="billTo_email" value="billmarcotte@gmail.com" />
<input type="hidden" id="shipTo_lastName" name="shipTo_lastName" value="Marcotte" />
<input type="hidden" id="MissingField3" name="MissingField3" value="card_accountNumber" />
<input type="hidden" id="MissingField0" name="MissingField0" value="card_expirationMonth" />
```

**Comment by Xymmer** [comment]
looks like the problem with checking out is a combination of things
from Pawel:
- they are are releasing another milestone M8 later today with the checkout fix that allows uppercase Mockup
- you don’t have to wait for M8, just change payment provider to lower case
- for postUrls, configure website.electronics.http and website.electronics.https for electronics-spa

**Comment by Xymmer** [comment]
I changed Mockup to mockup in backend and it fixed the issue.
Tobias verified that adding the website.electronics-spa fixed that issue, although I didn't try it.
However there are new issues:

Bill says: I saw this one:
From Krzysztof Gumulak of Stingrays:
When adding a new payment card, we get 
![image](https://user-images.githubusercontent.com/4998145/53636153-342a8300-3bed-11e9-8be4-339ac3ff0e37.png)

Bill says: I didn't see this one:
From Krzysztof Gumulak of Stingrays:
when testing placing order with using in the flow add new payment, then I really stacked  at that step, but when I used option to select saved payment then order can be completed
![image](https://user-images.githubusercontent.com/4998145/53636168-43113580-3bed-11e9-9927-fd734037a321.png)

**Comment by hackergil** [comment]
I tested the above with the proper backend changes on dev17. We are still getting the highlighted error in the card with both a new and an existing card.

**Comment by hackergil** [comment]
This is also happening in our CCv2 instance, which doesn't have 1905.
