### ISSUE TITLE
Refactor order-detail component to be CMS-driven

### ISSUE THREAD

**Issue by kacperknapik** [SAP/cloud-commerce-spartacus-storefront#1504]
Examples of such refactor: order-history (#1244) and address-book (#1090)

Among others, we have to take care of:

* adding component module to `cms-lib.module.ts`
* adding `ConfigModule.withConfig()` in components' module (with corresponding mapping)
* adding `entryComponents` array in components' module
* moving router config objects to `pages.module.ts`
* (optional) removing every hardcoded and unwanted piece of the component
* (probably) some other work, specific to the component

You can find more details about components' UIDs in #1086

**Comment by Pucek9** [comment]
Component is able to be divided for 6 slots. In this ticket I made basic refactor and use first one (AccountOrderDetailsHeadlineComponent)

**Comment by kacperknapik** [comment]
We should talk some more about this page. For now we decided to go with just one slot, since we will need additional work anyway.

Each component `AccountOrderDetailsxxx` will have to have a container/wrapper component, since `summary` component for example cannot be mapped right away (it has some inputs).

Further discussions needed @tobi-or-not-tobi
