### ISSUE TITLE
Create facades for StoreFinderModule and move to core

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#151]
Follow instructions from #6 and see example/spike in #140.
If you have a question, post in team slack with @tobias and @wei.

After this, do #415

**Comment by Xymmer** [comment]
We're giving this one to Walkers right?

**Comment by Xymmer** [comment]
Wei is available as a reviewer

**Comment by Matejk00** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/826
