### ISSUE TITLE
Spike ASM

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1511]

**Comment by giancorderoortiz** [comment]
Proposed functionality should follow a SDLC as specified here: https://wiki.wdf.sap.corp/wiki/display/PSSEC/Secure+Software+Development+Lifecycle+Overview

And must comply with security standards as detailed here:
https://wiki.wdf.sap.corp/wiki/display/PSSEC/SAP+Product+Standard+Security+-+Version+8.0
