### ISSUE TITLE
Add /logout link to logout navigation node

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1515]
The sign out link in the cms content has no link action attached. This must be done in order to have a content driven logout proces. 
The `/logout` link is processed as a virtual route in the the application, see #1514

**Comment by plabadie** [comment]
PR: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/28/diff

**Comment by WeizhengSap** [comment]
I approve the PR. Please test it to make sure there is no import errors.
