### ISSUE TITLE
Create facades for GlobalMessageModule

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#152]
Follow instructions from #6 and see example/spike in #140.
If you have a question, post in team slack with @tobias and @wei.

**Comment by WeizhengSap** [comment]
I commented out multi-step-checkout.component.spec in this ticket. This test will be refactored in ticket #154.

**Comment by Xymmer** [comment]
All facades work will be tested with one ticket, #6.
