### ISSUE TITLE
export NavigationComponentService in public_api

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1521]
The `NavigationComponentService` is not exported in the public_api of the storefront library. This means customer cannot use it.

**Comment by khalistan** [comment]
Those who facing this problem, for time being till its not fixed here is workaround:

import { ɵbj as NavigationComponentService } from '@spartacus/storefront';

**Comment by khalistan** [comment]
Here is workaround:

`import { ɵbm as NavigationComponentService } from '@spartacus/storefront';`

and now in constructor

```
 constructor(s:NavigationComponentService){
    super(s);
  }
```

Please careful in import its not a ebm or 0bm there is special character here its **ɵ**bm

**Comment by khalistan** [comment]
i don't know why they put special char here. It took sometime to figure out that its ebm but ɵbm.
