### ISSUE TITLE
Upgrade to latest angular(-cli) and dependencies

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1524]
- angular 7.2.11
- angular-cli 7.3.7
- rxjs 6.4.0
- ngrx 7.2
- any of the dev dependencies that we can update

**Comment by LTiger14** [comment]
This checklist highlights some steps easy to miss like updating the doc. https://wiki.hybris.com/pages/viewpage.action?spaceKey=spar&title=Spartacus+Angular+Version+Upgrade+Checklist

**Comment by znikola** [comment]
@tobi-or-not-tobi the latest ngrx version is `6.4`, but in this ticket `6.2` is specified. Do we want to upgrade to `6.4` or `6.2`?

**Comment by tobi-or-not-tobi** [comment]
7.4 sounds good 👍

**Comment by hackergil** [comment]
Spartacus installation PR [here](https://stash.hybris.com/projects/C3PO/repos/spartacus-installation/pull-requests/21)

**Comment by znikola** [comment]
For the wiki PR: please update `@angular/pwa` version and all `ngrx` to `7.4.0`
