### ISSUE TITLE
Can't cancel address book if no addresses yet

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#1526]
## Steps to Reproduce
1. as logged in user ensure you don't have any addresses in your address book (delete if needed, refresh the page).
2. go to address book (adding new address form should appear) and click "Back to Address List"
## Observed Results
Nothing happens, no errors in the console.

Should this button be visible at all in case user is adding his FIRST address?

**Comment by KateChuen** [comment]
"Back to Address List" button should not be visible.
