### ISSUE TITLE
Introduce page heading to distinguish page heading from page title

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1528]
The page title for SEO and SERP is not necessary the same as the page heading shown in the UI.

The product title is a good example. For a great SERP, you would have something like: 
"Product Title | Main category | Brand"

This is very different from the page heading which we have as part of the breadcrumb. In order to support flexibility, we introduce another resolver that can be implemented.

**Comment by tobi-or-not-tobi** [comment]
**QA steps**
- validate that we have a different page heading and page title (browser tab) for the PDP

**Comment by KateChuen** [comment]
Tested on dev17 (chrome, safari & firefox).

- [X] validate that we have a different page heading and page title (browser tab) for the PDP
