### ISSUE TITLE
Create facades for CartModule

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#153]
Follow instructions from #6 and see example/spike in #140.
If you have a question, post in team slack with @tobias and @wei.

**Comment by WeizhengSap** [comment]
Please also refactor the cart-page-layout.component and cart-page-layout.component.spec to just use cart facade.

**Comment by znikola** [comment]
> Please also refactor the cart-page-layout.component and cart-page-layout.component.spec to just use cart facade.

Done.

**Comment by Xymmer** [comment]
All facades work will be tested with one ticket, #6.
