### ISSUE TITLE
Add meta robot content to control whether pages got indexed and followed by BOTs.

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1530]
The meta data set can contain an instructions to search engines to index the page and follow the page to find other pages. There are 4 values that can be used:

- `FOLLOW` vs `NOFOLLOW`
- `INDEX` vs `NOINDEX`

We introduce another page resolver to control the logic per page.

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- validate the robots meta tag for checkout page. it should have "NOINDEX, NOFOLLOW"

**Comment by Xymmer** [comment]
verified with dev 17 March 12 4pm
home, search results, storefinder, pdp, cart all have "INDEX, FOLLOW"
checkout has "NOINDEX, NOFOLLOW"

**Comment by Xymmer** [comment]
passing but i will see what shows up for other pages, not sure if cart should be indexed?

**Comment by Xymmer** [comment]
to doc for doc input, how is this configured i.e. which pages get noindex or nofollow?

**Comment by tobi-or-not-tobi** [comment]
Cart could be indexed, some commerce sites do it. If not required, it can be implemented by customers. We do not (yet) have it configurable.
All pages have index/follow, only checkout has a specific implementation for noindex/nofollow. Mainly to demonstrate. 
Customers might also want to do this with robots.txt.

**Comment by tobi-or-not-tobi** [comment]
@Xymmer can we move this to done?
