### ISSUE TITLE
[doesn't block release] migrate regression/order-history to cypress

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1533]
See GH-1102 for original spike.
Take a look at big happy path for example.
See cypress video in our wiki.

all epic/cypressmigration tickets should be merged into epic branch "epic/cypressmigration-fr1".
if this epic branch doesn't exist, you're probably the first, so create it.

**Comment by marlass** [comment]
Looked at tests. Currently there is some issue that makes them fail.
More important is that those tests doesn't really check things we want to test.
