### ISSUE TITLE
Re-render components when they change

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1538]
While Single Page Applications can leverage the advantage of caching the page structure after first load and use it during the session or even in sub sequential visits, content isn't necessarily static and could change based on the user interaction. The storefront should reload content while the user re-visits a page.

In the future we could optimise the (re)loading of CMS content, but this should be mainly a backend related story: An optimised interaction from front-end to backend could be implemented to avoid duplicated calls for content. One idea that comes to mind is to provide a hash (in backend) of the page structure and pass this in sub sequential calls. The backend could evaluate the hash and return a 304 (not modified) in case of equal page structure. This would save the network bandwidth and client-site processing of the data.

**Comment by tobi-or-not-tobi** [comment]
This is already done during login, but this is not a generic solution.

**Comment by dunqan** [comment]
QA steps:
1. Check if header is not reloaded / redrawn while navigating
2. Check renavigating to the same page
  - visiting page that already has page data loaded should be instant
  - there still should be network call for new page data (visible in network tab)
3. Check if navigating to `Sales` page from `Help` page works correctly (there is no content left ftom `Help` page)

**Comment by Xymmer** [comment]
1. it's hard to tell but doesn't look like it
2. works as described (go to a listing, click a product, go back, go back to same product, only a few calls vs many first time)
3. Sales works

**Comment by Xymmer** [comment]
passing

**Comment by Xymmer** [comment]
assign to stan for doc check
