### ISSUE TITLE
Create facades for CheckoutModule

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#154]
Follow instructions from #6 and see example/spike in #140.
If you have a question, post in team slack with @tobias and @wei.

Add back the unit test previously commented out:
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/016ffd4f8cf746ee5b5c0765cc666721ca1130b5/projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/container/multi-step-checkout.component.spec.ts

**Comment by Xymmer** [comment]
All facades work will be tested with one ticket, #6.
