### ISSUE TITLE
cms-lib/address-book component Refactor

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#1545]
`cms-lib/address-book/address-card/address-card.component.scss`

1. Remove SASS variables by transferring its values to the CSS properties.
2. Add CSS variables and set previous values as fallbacks.
3. Simplify CSS selector names
4. Update HTML markup to reflect selector names  (keep cx-prefix)
5. Remove unneeded/redundant classes.

**Comment by mikelMHybris** [comment]
![Screen Shot 2019-03-15 at 10 04 51 AM](https://user-images.githubusercontent.com/30266610/54437319-bf863700-470a-11e9-8cbd-7b0cdbb96ac4.png)
