### ISSUE TITLE
Spike storefront installation on CI and QA

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#155]
We don't ship a shell app anymore. Customers are provided setup instructions to create a brand new angular app and add the libs to it. We should use this scenario to install our storefront on the pipeline to continuously catch code updates that would have a side effect on the end result.

Another requirement: Use the same installation script for QA environments and the CI.

**Comment by Xymmer** [comment]
I imported the 3 jira tickets created by Patrick earlier: #172, #173, #174.

**Comment by Xymmer** [comment]
since we're using schematics in the near future, should solve this issue. closing as won't fix.

**Comment by plabadie** [comment]
After investigation, here is what we could do:

ALIGN QA WITH SETUP INSTRUCTIONS
================================

- Align the QA installation script with the installation steps we promote/document.
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/setupandinstallation.md

- Improve the team awareness that the setup instructions and the QA installation steps are related and need updating in the dod of some tickets.

- Let's perhaps run the updated script in QA for a while before propagating it to the CI.


INSTALLATION STEP VALIDATION ON CI
==================================

- Implement an 'installation check' on the pipeline 
-- that shares the core logic with with the QA installation script.
-- that installs and builds the app and checks for defects, like build errors, dependency warnings (but no runtime validation like e2e yet)
