### ISSUE TITLE
Finish facades for AuthModule

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#156]
Follow instructions from #6 and see example/spike in #140.
If you have a question, post in team slack with @tobi-or-not-tobi  and @wei.

**Comment by tobias** [comment]
@WeizhengSap You have the wrong Tobias.

**Comment by znikola** [comment]
In this ticket, only auth module itself is switched to using the facade. For the other modules, see #276

**Comment by Xymmer** [comment]
All facades work will be tested with one ticket, #6.
