### ISSUE TITLE
Bug | Scroll to product details when the element is not visible the first time load  product page

### ISSUE THREAD

**Issue by rafseggir** [SAP/cloud-commerce-spartacus-storefront#1570]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

## Environment Details

- Spartacus:  Alpha.0
- Browser: Chrome, Firefox
- OS: Windows 10, Android 8.1.0

## Steps to Reproduce
When Spartacus loads the product page moves to the Product Details directly and the user can't see the product, the image. 

## Observed Results

It is because the first time loads product page it goes thought *set initial*, in *product-tabs.component.ts*, and it calls to the click event. In the click event, same file, the view scrolls if the element is not visible, I think the first time loads the product page.

![image](https://user-images.githubusercontent.com/13329747/53895309-0cdf1600-4032-11e9-839f-f8bd821ed4dc.png)

## Expected Results
Show the top page when Spartacus loads the first time product page.

**Comment by Xymmer** [comment]
to repro and fix

**Comment by Zeyber** [comment]
Unable to reproduce this issue

**Comment by KateChuen** [comment]
Not able to reproduce either.
