### ISSUE TITLE
After adding the very new address at the checkout show addresses for one second

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#1572]
## Environment Details

- Spartacus: localhost latest develop
- Browser: chrome
- OS: OSX 10.14.3

## Steps to Reproduce
login, delete your addresses if any, add something to cart, go to checkout, click Continue.

## Observed Results
The view with addresses blinks for ~1s and then shipping method appears, see video ~19th second:
https://www.youtube.com/watch?v=Q3BB-_rI7MU

## Expected Results
Blink shouldn't happen, shipping method should appear immediately.

**Comment by Xymmer** [comment]
checked, still occurs

**Comment by KateChuen** [comment]
Tested on dev10. Works now. We don't see the newly added address anymore.
