### ISSUE TITLE
[FEATURE MASTER] Update Personal Details

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1575]
Master ticket for Account Profile Personal Details.

- [x] Implement Facade GH-1145
- [x] Implement UI GH-1146
- [x] Implement e2e tests GH-1160

FR2: Make sure the customer ID is displayed GH-1467

**Comment by znikola** [comment]
Master branch: https://github.com/SAP/cloud-commerce-spartacus-storefront/tree/feature/account-personal-details

**Comment by plabadie** [comment]
For QA, use Dev17

**Comment by KateChuen** [comment]
- [X] No "Account Profile" page yet, so "Personal Details" is above "Password" in the nav menu.
menuOrder
<img width="1127" alt="menuOrder" src="https://user-images.githubusercontent.com/45409515/55811465-2e12a680-5ab7-11e9-8cae-0a8ecc206ad6.png">

- [X] Personal Details Page displays the current info about the user
<img width="802" alt="upatePersonalDetailsPage" src="https://user-images.githubusercontent.com/45409515/55811516-3d91ef80-5ab7-11e9-9efa-af93458790a0.png">

- [X] If the Required fields are empty, proper message displayed to user.
<img width="1113" alt="UpdatePersonalFieldRequired1" src="https://user-images.githubusercontent.com/45409515/55811600-60bc9f00-5ab7-11e9-9b4f-3f969ecb72de.png">
<img width="1026" alt="UpdatePersonalFieldRequired2" src="https://user-images.githubusercontent.com/45409515/55811601-60bc9f00-5ab7-11e9-99bb-498054b1df51.png">

- [X] Title can be changed to None
<img width="1055" alt="updatePersonalTitleNone" src="https://user-images.githubusercontent.com/45409515/55811727-8e094d00-5ab7-11e9-9173-6c03b4bc6cbf.png">

- [X] FirstName and LastName can have numbers and special chars
<img width="1206" alt="UpdatePersonalDetails" src="https://user-images.githubusercontent.com/45409515/55811738-93ff2e00-5ab7-11e9-8de7-5151109a001d.png">

- [X] User is redirected to homepage upon successfully updating his personal details. When Account Profile Page will be created later, then user will be redirected there.

- [X] New personal details is displayed upon successfully saving.

- [X]  Clicking on "Cancel" redirects the user to "homepage".
