### ISSUE TITLE
[FEATURE MASTER] Update Email

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1577]
Master ticket for Account Profile Update Password .

- [x] Implement Facade GH-1165
- [x] Implement UI GH-1166
- [x] Implement logout when email is updated GH-2009
- [x] Implement e2e tests GH-1167

- Implement Authentication feedback GH-1921 --> Closed for historical logs

**Comment by bgambocjaviniar** [comment]
PR: GH-2050

**Comment by KateChuen** [comment]
- [X] No "Account Profile" page yet, so "Email Address" is between "Password" and "Close Account" in the nav menu.
<img width="924" alt="emailAccountProfile" src="https://user-images.githubusercontent.com/45409515/56598987-95564d80-65c3-11e9-9537-7d7fb06fc0cc.png">

- [X] If the user clicks outside the field without entering a valid email address, there's an error message.
<img width="819" alt="invalidEmail" src="https://user-images.githubusercontent.com/45409515/56599436-8a4fed00-65c4-11e9-99cf-663cd6ade468.png">

- [X] If the emails do not match, there's the error message.
<img width="842" alt="matchEmailProfile" src="https://user-images.githubusercontent.com/45409515/56599262-35ac7200-65c4-11e9-8138-0d8957d93693.png">

- [ ]  Error message not informative to the user if s/he enters a wrong old password. Updated ticket #1958

- [X] User is redirected to the Login screen upon successfully updating his email address, with a successful and meaningful message.
<img width="1059" alt="successfulEmailUpdate1" src="https://user-images.githubusercontent.com/45409515/56602123-c38b5b80-65ca-11e9-8f56-017117ebe933.png">

- [X] Clicking on "Cancel" redirects the user to "homepage".

- [X] Trying to click on "Save" without entering valid info, gives the user an error message.
<img width="964" alt="emptyFieldsEmailProfile" src="https://user-images.githubusercontent.com/45409515/56599142-f8e07b00-65c3-11e9-8087-5daf82b2fcfa.png">

- [X] Upon updating the email address, user can no longer sign in with previous one.

- [X]  Upon updating the email address, user can now sign in with new one.

- [X] Upon signing out, user remains on the Update Email Page. Updated ticket #1957
