### ISSUE TITLE
[FEATURE MASTER] Consent Management

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1578]
Master ticket for Account Profile Update Password .

- [x] Implement Facade GH-1184
- [x] Implement UI GH-1185
- [x] Implement e2e tests GH-1186

**Comment by znikola** [comment]
Master PR: #2530 
Backend PR: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/50/overview

**Comment by znikola** [comment]
To QA:
1. Navigate to consents page.
2. Try to give/withdraw a consent
3. Logout, login again, and try to navigate to the page again. Consents should be given/withdrawn just like before the logout. This step is important, because APIs return a caching header, instructing browser to cache consents. This is bypassed by using `No-Cache` header when calling APIs

**Comment by KateChuen** [comment]
Tested on dev17.
- Consent Management is part of MyAccount menu now
<img width="1003" alt="consentMenu" src="https://user-images.githubusercontent.com/45409515/58176513-6f7aa200-7c70-11e9-86a6-f1015979c3e0.png">

- Able to navigate to consent page
<img width="1004" alt="CMPage" src="https://user-images.githubusercontent.com/45409515/58176253-e7949800-7c6f-11e9-95ec-cd16217c1a87.png">

- Able to give/withdraw a consent
<img width="1009" alt="CMGiven" src="https://user-images.githubusercontent.com/45409515/58176524-77d2dd00-7c70-11e9-889b-de41075462b3.png">
<img width="1004" alt="CMWithdrawn" src="https://user-images.githubusercontent.com/45409515/58176525-77d2dd00-7c70-11e9-9f4f-cff1b1d5e938.png">

- Clicking on Done redirects user to homepage while keeping the user's choice for consent
<img width="1004" alt="CMDone" src="https://user-images.githubusercontent.com/45409515/58176544-802b1800-7c70-11e9-9ba2-49f46c10b376.png">

- Signing out redirects user to homepage & logs out. Next time user logs back in, his options for consent is still as selected.
<img width="1011" alt="CMSignOut" src="https://user-images.githubusercontent.com/45409515/58176297-fd09c200-7c6f-11e9-888b-c3a23f2e9365.png">
<img width="1009" alt="CMNotLost" src="https://user-images.githubusercontent.com/45409515/58176566-8b7e4380-7c70-11e9-8cb7-f69405ed8ff0.png">
