### ISSUE TITLE
[FEATURE MASTER] Close Account

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1579]
Master ticket for Account Profile Update Password .

- [x] Implement Facade GH-1187
- [x] Implement UI GH-1188
- [x] Implement e2e tests GH-1189

**Comment by WeizhengSap** [comment]
Created branch `feature/GH-1579` as the feature branch.

**Comment by KateChuen** [comment]
- [X] "Close Account" is located below "Email Address" in the MyAccount nav menu.

- [X] 2 buttons on "Close Account" page, "Cancel" and "Close my account".

- [X] Clicking on "Cancel" brings the user to homepage without closing the account.

- [X] Clicking on "Close my account" presents the user with a confirmation dialog. 

- [X] Clicking on "Cancel" or the "X" button on the confirmation dialog or clicking outside the popup window brings the user back to the "Close Account" page.

- [X] Clicking on "Close Account" on the confirmation dialog takes the user back to homepage, with a successful message, as an anonymous shopper.
<img width="1430" alt="closeAccountSuccess" src="https://user-images.githubusercontent.com/45409515/56610621-d9eee280-65dd-11e9-941a-2d539b1d10ff.png">

- [X] If user tries to login or register with the account that's closed, s/he gets an error message. 
<img width="1431" alt="loginWClosedAccount" src="https://user-images.githubusercontent.com/45409515/56610680-06a2fa00-65de-11e9-8d04-088c4bcfa861.png">

- [ ] Signing out on "Close my account" page leaves the user on the same "Close my account" page. And if user clicks on "Close my account" from there, s/he even gets the popup window to confirm it. But s/he cannot actually close the account from there. Updated ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1957
