### ISSUE TITLE
Finalize facade for ProductModule

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#159]
Follow instructions from #6 and see example/spike in #140.
If you have a question, post in team slack with @tobias and @wei.

*  The facades are already done for this module. In ProductModule, move facade services (in services folder) to facade folder.
* Update the component unit tests to use mocked facade instead of the store directly.  Guards and converters are out of scope of this ticket because they will likely get refactored when they move to the core lib.
* Unit tests in other modules that use the product store are also not in scope of this ticket.

Pull request: #194

**Comment by plabadie** [comment]
Pull request: #194

**Comment by Xymmer** [comment]
All facades work will be tested with one ticket, #6.
