### ISSUE TITLE
[hold] Search results changing on CCv2 instance [still a bug? let's ask gil]

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#1592]
**Please timebox to half a day**

Search results are variating from one day to the next, which is causing that our e2e tests fail. We need to investigate why this is happening.

In the meantime, solr indexing jobs have been turned off. Please turn them on once we know what's going on.

**Comment by Xymmer** [comment]
removing from sprint, may fade away, let's ask gil

**Comment by Xymmer** [comment]
Gil shut off indexing on our model t
now we're moving to jemkins/internal server
let's revisit once all that is done

**Comment by tobi-or-not-tobi** [comment]
No longer an issue. Either way cannot be fixed in spartacus code base.
