### ISSUE TITLE
07: use active language in 'date' pipe

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1596]
For localization pipes (i.e. `date`) Angular uses `LOCALE_ID` (injection token) which is `en` by default. One can also pass a locale as a parameter to `date` pipe. 
And would like to use dynamic value of active language (`LanguageService.getActive()`).

For tree shaking purposes Angular needs all used locales to be registered via [`registerLocaleData()`](https://angular.io/guide/i18n#i18n-pipes) in compilation time.

So in shell app we should register all used locales.

If we are ok with such a solution, we probably need to create custom pipe (`cxDate` ?) that wraps the native `date` pipe and passes active language as a parameter.

Currently we use native `date` pipe in 5 components. 

Note: activeLanguage can be not only `en`, but also `en-GB`

https://angular.io/guide/i18n#i18n-pipes
https://github.com/angular/angular/tree/master/packages/common/locales

**Comment by Platonn** [comment]
QA steps:
0. Yyou need to have at least one order in the history
1. Go to order history page 
2. Change language and verify that the date is formatted differently for different languages.

Note: Features `Product reviews` and `Store finder` also use localized date/time, but we have missing data in backend for those languages:
- there are no product reviews in languages other than English
- the are no opening/closing hours for stores in languages other than English (see #1879)

**Comment by KateChuen** [comment]
Was not able to test it on a server.
We only have 2 servers to test with:
Dev17: Did not see the format of the order date change there.
Dev19: Login screen is missing login form. 

I was able to test it locally though... But it still needs to be tested on a server.
