### ISSUE TITLE
Add og:image meta tag for social sharing

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1598]
Most social media use the og:image tag from the Open Graph standard that was provided by facebook. This is best practice for Commerce storefronts.

**Comment by tobi-or-not-tobi** [comment]
QA:
- test whether the main product image is added as a og:image metatag

**Comment by Xymmer** [comment]
checked for this on dev17 and github.io, but don't see it. will try tomorrow, maybe servers not updated.

**Comment by Xymmer** [comment]
verified on github.io mar13

**Comment by tobi-or-not-tobi** [comment]
@Xymmer The missing part here might be that this is only implemented on the PDP ;) On other pages we do not have a clear idea which main picture to share, I've created a ticket for this in our CMS backlog (CMSX-8615).
Can you test again?
