### ISSUE TITLE
Wireframes for Add to Home Screen on Confirmation Page

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#160]
Here are wireframes detailing the Add to Home Screen issue.

Of note: There are 2 different streams / flows. 1 for Apple devices and another for Android OS.

The button on the confirmation is shared by both device types, however, a media query should be done on click of the 'Add to Home screen button to determine the next part of the flow.

If the user clicks using an apple device, the icon is added and the user is immediately notified that the operation was successful.

If the user clicks using an Android device, there is an intermediate modal giving the user the option to manually place the icon on their homes screen as is normal per newer android operating systems on multiple browsers.

It is my hope that the intermediate modal will come from the (be owned by) the device and not be in our code, however I am unsure if this is possible. We would simply be bypassing the SDK Add to Home Screen modal and be replacing it with our own. The rest of the flow belongs to the device SDK in both apple and android examples. 

I hope this is possible!

Related to Issue #50

**Comment by Xymmer** [comment]
to be validated
then maybe manuel does a styling example
we get dev to assess
then implement

**Comment by Xymmer** [comment]
Hey Anthony! Some comments on the wires:
- The 4 bullet points, the only one that makes technical sense is "No installation needed", I think it's ok if we only say that for now.
- I don't quite understand the info about the intermediate modal but maybe you and Marcin know better than me :) i would like to really on what's native in android and ios in the end, i think that's what you're saying. let's see what marcin says.

**Comment by marlass** [comment]
I left the point "No installation needed" and added "Fast access to application" because single bullet point looked bad. 

I did not implement this modal, because it really does not bring real benefit (Android users are already familiar w A2HS banners and this modal just require additional click from user).

Hope you will like result after merging #242 .

**Comment by julioarguello** [comment]
Is there any kind of access for partners and customers to axure designs?
