### ISSUE TITLE
DOC: SEO updates for Image Resolver

### ISSUE THREAD

**Issue by gladius-mtl** [SAP/cloud-commerce-spartacus-storefront#1607]
See GH-1605 for changes to review in seo.md -- specifically, the new Image Resolver section.

**Comment by gladius-mtl** [comment]
@tobi-or-not-tobi : Assigning this ticket to you so that you can review PR GH-1626. Thanks!

**Comment by tobi-or-not-tobi** [comment]
@gladius-mtl we already have a section in seo.md, anything else you'd expect on this topic?

**Comment by gladius-mtl** [comment]
@tobi-or-not-tobi Yes, since we're not including pull requests in our sprint boards, I assigned this ticket to you so that you could validate and approve to the PR linked in my previous comment (GH-1626). This PR is for your to verify that my edit and review of your Image Resolver input in `seo.md` is complete, accurate, and ready for publishing 😄

**Comment by tobi-or-not-tobi** [comment]
excuses-et-moi, I missed that ;)
