### ISSUE TITLE
Facets are not displaying properly on search results page

### ISSUE THREAD

**Issue by Matejk00** [SAP/cloud-commerce-spartacus-storefront#1610]
After CMS component refactor work there is a problem with facets on search results page. Instead of displaying it on the left side they are at the bottom right now.

![image](https://user-images.githubusercontent.com/6958810/54117752-c69f0380-43f1-11e9-9b80-42de05b4bb5c.png)

**Comment by Pucek9** [comment]
Ticket solved also problem with grid on custom cms category (digital cameras > slr cameras)

**Comment by kacperknapik** [comment]
@Matejk00 can you check with someone if the bottom banner (yellow one) is in a correct place?
