### ISSUE TITLE
Set previewCategory and previewProduct for electronics-spa

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1616]

**Comment by WeizhengSap** [comment]
PR is here:
https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/32/overview

**Comment by WeizhengSap** [comment]
To QA:

You should be able to see them in backoffice:
![Screen Shot 2019-03-11 at 10 36 07 AM](https://user-images.githubusercontent.com/44440575/54131860-994e5780-43e9-11e9-9502-be3757e819a5.png)

**Comment by bgambocjaviniar** [comment]
I can see it

![Screen Shot 2019-03-11 at 2 10 12 PM](https://user-images.githubusercontent.com/29099466/54146944-72068300-4407-11e9-8274-dd0577f90cf3.png)
