### ISSUE TITLE
Redirect to default preview product (category) page [depends on 1344 and RAY-259] 

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1621]
We set the default preview product/category for site electronics-spa. So, in smartedit, if we select Product or Category page from PAGES list, we should see the default product/category page rather than an empty page.

Now, it is empty:
![Screen Shot 2019-03-11 at 10 31 55 AM](https://user-images.githubusercontent.com/44440575/54135369-0c5acc80-43f0-11e9-90ba-828107494be0.png)

We should see this:
![Screen Shot 2019-03-11 at 11 14 30 AM](https://user-images.githubusercontent.com/44440575/54135401-1a105200-43f0-11e9-9c83-d42d0e741ef2.png)

**Comment by WeizhengSap** [comment]
Depends on this:
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1344

and this:
https://jira.hybris.com/browse/RAY-259

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1815

**Comment by WeizhengSap** [comment]
To code reviewer/QA:

Now, the preview product code (2053367) and the preview category code (575) is hard-coded; e.g. `this.routingService.go({
          route: [{ name: 'product', params: { code: 2053367 } }]
  });`.
These values should be read from baseSite. 

We have this ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1810 which can get the baseSite data from ngrx/store.

**Comment by bgambocjaviniar** [comment]
In smartedit, it correctly redirects you using the hardcoded category / product code in the category / product pages.
