### ISSUE TITLE
Smoke test Mar 13 2019 lib release

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1623]
Run **all** the E2E tests on the **release branch** on [jenkins](https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus/): 
**Note**: Make sure that **ALL** the tests are being run (about 17 tests). 

Because these ones have not been migrated to cypress yet, you have to run them manually: 
Use this server: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/
Keep the browser's console open at any time and monitor for errors.
- [x] Order history page
- [x] Change language/currency

Additionally, do a quick smoke test (equivalent to the big happy path test) on:
- [x] Safari
- [x] Firefox

**Comment by marlass** [comment]
Libs released
