### ISSUE TITLE
Refactor order-detail component to be CMS-driven Part 2

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#1624]
Continue refactor started in #1504 by divide main component for 4 slots:
![image](https://user-images.githubusercontent.com/8040837/54142385-d9ccc600-4427-11e9-84da-deb1c5a5bec3.png)

1 AccountOrderDetailsHeadlineComponent
2 AccountOrderDetailsItemsComponent
3 AccountOrderDetailsTotalsComponent
4 AccountOrderDetailsShippingComponent

**Comment by mirkosoft** [comment]
Server QA review done - everything works fine on desktop and mobile.
