### ISSUE TITLE
[Question] No possibility to add e.g next Brand in filter facet

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#1625]
After open any category, and select Stores/Price we can see, that it has been added to filters list, and checkboxes in facet are set as selected.

For Brand there is different situation - Brand/Mounting/Resolution is added to fiters list, but their facet disappear.
It happens also after choose Stores/Price - some facets are not displayed.

Is it correct behaviour?

**Comment by Xymmer** [comment]
Looks like it's behaving as designed. Comparing to Accelerator, it works the same way. You can select multiple prices but not multiple brands. This is defined in the backend, so Spartacus should be a dumb pipe here.

However I would like to understand how to change it in the backend and prove Spartacus works both ways. Let's find out.
