### ISSUE TITLE
Enable E2E tests for products out of stock

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#163]
We have prepared E2E test for edge cases that require a product to be out of stock. We need to set the product to this state and enable tests.

**Comment by marlass** [comment]
Some document with edge case products should be created. Would be very helpful in future E2E tests development.

**Comment by marlass** [comment]
@gladius-mtl Would be good to place this information in our docs.
```
## Helpful E2E test development information

Products for test cases:

- use product 'Alpha 350' with id `1446509` for placing orders (has almost unlimited stock)
- use tripod with id `29925` for testing product out of stock
```

**Comment by gladius-mtl** [comment]
Created follow-up doc ticket GH-246 to incorporate the suggested input into our documentation.
This issue can now be moved to QA (or next logical state).

**Comment by Matejk00** [comment]
Done. Test provided, all builds pass properly.
