### ISSUE TITLE
Fix issues with presentation of whole-cart applied promotions

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/cloud-commerce-spartacus-storefront#1637]
Fix issues with presentation of whole-cart applied promotions
Locations:
-> Promotions displayed at top of cart
-> Promotion displayed in subtotal summary area
Issues
-> Multiple entry handling i.e.
![image](https://user-images.githubusercontent.com/4272069/54338556-824e7600-4632-11e9-8bae-ae10f042da03.png)

-> Resolution of duplicates
-> Styling update

**Comment by Xymmer** [comment]
was already fixed
