### ISSUE TITLE
[retest & doesn't block release] Spartacus and SmartEdit styling issues

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1650]
See CMSX-8254

**Comment by developpeurweb** [comment]
Hey @Xymmer as discussed during stand-up, can you please advise on the status for this ticket considering the original bug in Jira seems to have been tested on a previous version of SmartEdit as well as a previous version of Spartacus (also about to evolve with the new refactoring). Pls see my comments in the Jira ticket. Thanks.

**Comment by KateChuen** [comment]
Tested the ticket on dev2 updated.
The hidden components styling looks ok now.
![hiddenComponents](https://user-images.githubusercontent.com/45409515/57323989-e8a4c180-70d4-11e9-8c62-92ee42d17a41.png)

The menu items styling looks the same (but looks like it's not an issue according to Miguel?)
![menuItems](https://user-images.githubusercontent.com/45409515/57325573-50104080-70d8-11e9-8db1-f0ef50d9ed84.png)

**Comment by KateChuen** [comment]
Ticket is closed on SE side, so they are ok with how the menu items looks. And Miguel said there was no styling conflicts. So closing here too.
