### ISSUE TITLE
Test a few SmartEdit issues [doesn't block release]

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1651]
These issues probably are fixed. Let's double-check:
CMSX-8304: Pages created or cloned in SmartEdit don't work
CMSX-8517: Preview a version in SPA throwing errors related to product Carousel
CMSX-8520: Loading pages throws lots of renderService errors

**Comment by KateChuen** [comment]
So, tried to test this ticket. Here are my findings:

- CMSX-8304: Pages created or cloned in SmartEdit don't work
- [X]  Create page OK on dev2. (On my local, it loads the homepage after the page creation). So did most of the testing on Dev2.
- [ ] Add component to page (Looks like component was added but it does not get displayed, and no error either.
- [ ] - Clone Page was not successful. Was not able to change the page label to add slash.
![SEpageCloned](https://user-images.githubusercontent.com/45409515/54376772-2861a680-465a-11e9-87e0-fe26a98de0f0.png)


- CMSX-8517: Preview a version in SPA throwing errors related to product Carousel
- [ ] Upon creation of a version of the homepage, a lot of errors, and stuck on "loading"
![SEversion](https://user-images.githubusercontent.com/45409515/54376717-0b2cd800-465a-11e9-8e87-96a3057c3a98.png)


- CMSX-8520: Loading pages throws lots of renderService errors
- [ ] Errors still occurring.
