### ISSUE TITLE
[don't merge to develop for 1.1 | can merge to storefinder] Support deep linking for cms pages with routable cms components

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#1656]
Cms pages with page label defined with star `/page/*` should be used for any deep link, like `/page/edit`, `/page/edit/1` and also for: `/page`

Depends on
https://jira.hybris.com/browse/CMSX-8593
https://jira.hybris.com/browse/CMSX-8594
which are done!

**Comment by Platonn** [comment]
### QA steps:
Verify that sub-pages of storefiner work properly after page refresh (deep link).

**Comment by Zeyber** [comment]
QA: Multiple sub-pages of storefinder still work properly after page refresh
