### ISSUE TITLE
Add leading slash before ContentPage pages vol.2

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#1658]
This is a follow up to #1466 

Some of the pages have been referenced by page id or by a pageLabel which doesn't act as a URL. We should change sample data for this:

| Old | New|
|---|---|
| notFound | /not-found
storefinder | /store-finder

**Comment by Xymmer** [comment]
Kris may have fixed this manually in dev17 but we want this fixed in spacceleratorsampledata.
note that spacceleratorsampledata is being moved to acceleratoraddons - talk to louis.

**Comment by plabadie** [comment]
PR: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/34/diff

For smoke test, initialize the commerce instance and assess in back office the new labels

<img width="1527" alt="Screen Shot 2019-03-22 at 12 29 09 PM" src="https://user-images.githubusercontent.com/7065346/54842350-16aa7f80-4ca8-11e9-91b3-df3d8c349ce8.png">
<img width="1520" alt="Screen Shot 2019-03-22 at 12 28 49 PM" src="https://user-images.githubusercontent.com/7065346/54842351-16aa7f80-4ca8-11e9-8f92-d74b2bdcb6bb.png">

**Comment by bgambocjaviniar** [comment]
The two changes are confirmed in the backoffice, but I think it would be best to change the route and guards that points to notFound to not-found too in the frontend

**Comment by plabadie** [comment]
To sum up:
Backend PR: PR: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/34/diff

Spartacus PR: #1801

**Comment by plabadie** [comment]
Apart from the back office part, to QA, you can make sure that the two pages are accessible from `/store-finder` and `/not-found`
Like 
http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/not-found
http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/store-finder

**Comment by KateChuen** [comment]
Tested on dev22 (updated on April3rd, both backend and frontend).
- Verified in backoffice that the pagelabel for not-found and store-finder now have a forward slash.
![notFoundBackoffice](https://user-images.githubusercontent.com/45409515/55636975-11fac680-5792-11e9-86f2-da24533cc59a.png)
![storeFinderBackoffice](https://user-images.githubusercontent.com/45409515/55636981-13c48a00-5792-11e9-8db6-67fc53707551.png)

- Can access both pages by going to their respective urls.
![notFoundPage](https://user-images.githubusercontent.com/45409515/55636983-17581100-5792-11e9-82b3-e7a30ce26822.png)
![storeFinderPage](https://user-images.githubusercontent.com/45409515/55636993-1c1cc500-5792-11e9-83e9-eda7f10840ab.png)
