### ISSUE TITLE
Implement Add to Home in checkout confirmation page

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#167]
See #160 for wireframes
PWA add to home component implemented already
Let's add it to checkout confirmation page

**Comment by plabadie** [comment]
Hi @marlass, can you please add some smoke test instructions on how to validate the happy path for this feature?  

Also, it looks like a mobile platform centric feature.  Please specify if we can test this on a pc somehow or if it's just better to use a mobile device.

Thanks!

**Comment by marlass** [comment]
### About the device
Mobile devices have the best support for add to home screen, however desktop browsers start to catch up. On Windows 10 in Chrome this feature also works. It will move the tab to new window that is styled according to our branding. Additionally, it will be added to start menu and as a icon on desktop. I tested it mostly on this setup and it works 👌 

### How to test it
- run `yarn build:core:lib`
- run `yarn build`
- run `yarn start:pwa`
- go through the checkout and after placing an order you should be able to see the banner (if it isn't there and you don't have app installed you can manually invoke the browser event for it (Devtools -> Application tab -> Manifest -> Add to homescreen ~ top right corner)
- after confirming "Add to homescreen" modal banner should dissappear (link in mobile menu also) and message about successfull install should pop below header

**Comment by Xymmer** [comment]
thanks Marcin! someone from montreal will review, might not necessarily be Patrick.

**Comment by marlass** [comment]
New PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/346
