### ISSUE TITLE
Component guarding

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1678]
Some pages require authentication. Authentication can be page driven, but it's actually based on components used on the pages; components that require authorised users can moved by users from page to page. 

For the CMS we've suggested to return a 403, but for non-cms use-cases (and for as long as the cms doesn't provide auth per page), we like to use a setting per component type, that instructs the UI to redirect to the login page in case there's no authenticated user. 

The component guard instructions must be evaluated during page load, and in case any guarded component is part of the page, the user must be redirected. 

The login page is currently a hard-coded route. 

The component guard configuration can be part of the component mapping configuration.

**Comment by dunqan** [comment]
QA steps:
1. Configure guards (i.e. AuthGuard) for specified CMS Component
2. Logout
3. Check if opening page, that includes that component, requires logging in (redirects to login page if not logged)

**Comment by KateChuen** [comment]
Because dev17 is used for the pipeline, we only have Dev19 to make those changes without affecting anyone. 
But on Dev19 we cannot currently login because it's missing the login form. So was not able to test this.

**Comment by marlass** [comment]
Tested it locally on some CMS components. Works correctly. Also used this feature in extensible checkout epic and didn't have problems with it.
