### ISSUE TITLE
Error handling in effects

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#168]
There are some cases when we don't react appropriately to an error that can occur in an effect; in some cases we do use `catchError()` in an effect, and we do dispatch a custom *_ERROR_ACTION, but we don't react to that action in any reducer. This can cause the error to be 'swallowed', as no logs would be displayed.

We should create a mechanism that will handle these kind of cases. In the future we can maybe use this mechanism to send the errors to the server for the debugging purposes.

Was: SPA-1050

**Comment by Xymmer** [comment]
nik says not needed
