### ISSUE TITLE
Secure lambda calls to Kyma / SPA-1415

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#169]
To do:
- Talk to Johannes and Pascal and determine what we need to to.
- Create tickets to do it (use epic/kymaauth) or add subtasks in this ticket

Original ticket - SPA-1415:

To perform a authenticated call to Kyma from SPA, the developer needs to be able to pass to kyma an oauth id_token retrieved from commerce platform during the user login. 

This id_token is essential to allow Kyma to verify the lambda caller identity with the commerce platform acting as OpenId IdP (Identity Provider)

Current SPA Login code based on Oauth only retrieve an access token from the commerce platform. It should also ask the commerce platform for a Id token and store this additional token in the user object for later use by other part of SPA code requiring to make calls to Kyma.

For CX Live a workaround was put together: https://wiki.hybris.com/display/~johannes.engelke@hybris.com/Ugly+Workaround+to+fetch+id_token+in+SPA

**Comment by znikola** [comment]
After the latest updates from Pascal, here are the required steps:
1. We need to add a new oauth client:
```
INSERT_UPDATE OpenIDClientDetails;clientId[unique=true] ;resourceIds   ;scope    ;autoApprove  ;authorizedGrantTypes         ;authorities  ;clientSecret   ;registeredRedirectUri      ;externalScopeClaimName ;issuer
                                 ;***********           ;hybris        ;openid   ;openid       ;password,client_credentials  ;ROLE_CLIENT  ;******         ;http://MY_APPLICATION/     ;scope                  ;ec
```
2. SPA will still use the existing oauth client to get `access_token` and `refresh_token` and will continue to use those for authentication.
3. SPA will use the new oauth client to get the openid token:
```
POST /authorizationserver/oauth/token?grant_type=password&client_id=****&client_secret=****&scope=openid
Connection: keep-alive
Cache-Control: max-age=0
Content-Type: application/x-www-form-urlencoded
User-Agent: PostmanRuntime/7.11.0
Accept: */*
Postman-Token: aa78b8c7-800e-4f0d-a207-956b32eed38e
Host: localhost:9002
cookie: JSESSIONID=959880FAAD75883B51EBFC3E58E6EE84
accept-encoding: gzip, deflate
content-length: 29
username=****&password=****
HTTP/1.1 200
status: 200
X-Frame-Options: SAMEORIGIN
Set-Cookie: JSESSIONID=C8F9AE642D764C5BB55FB57FC0FB227F; Path=/authorizationserver; Secure; HttpOnly
Pragma: no-cache
Cache-Control: no-store
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 25 Apr 2019 09:55:49 GMT
{ "access_token" : "310f8025-5290-4032-9578-57a11d72bc26", "token_type" : "bearer", "expires_in" : 41458, "scope" : "openid", "id_token" : "JWT token response here"
```
4. SPA will store `access_token` and `id_token` for kyma, but will NOT use them.

This approach is only a temporary one until we have a better solution that implements Markus' proposition (access tokens being id tokens)

**Comment by znikola** [comment]
b2c_cms PR: https://stash.hybris.com/projects/INFRA/repos/yenv/pull-requests/95/overview

**Comment by znikola** [comment]
QA steps:
When registering or logging in, the open id token should be retrieved. Please check the ngrx state or `localStorage`

**Comment by znikola** [comment]
It will be tested as part of #2777
