### ISSUE TITLE
Add support for CxCmsContainer component

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1694]
If personalization is installed, the "save big" banner and 2 of the "4-in-a-row" banners don't appear. 
![image](https://user-images.githubusercontent.com/4998145/54437576-4a673180-470b-11e9-97b4-dbbaf4375566.png)

This is because these extensions add "CxCmsContainerComponent". Team OCCtopus is flattening this component to not use containers, see OCC-4399. After that's done we can do this one.

Acceptance criteria:
- After the change to the backend, we add support, and it should appear as normal. 
- Our devcom17 server (as of this writing) doesn't include personalization. Essentially if you install b2c_acc_plus with spacceleratorsamplesaddon, its should work.

**Comment by Xymmer** [comment]
@bgambocjaviniar : i thought this was done, is this an old ticket?

**Comment by Xymmer** [comment]
this was fixed by the team that owns personalization

**Comment by p-zientek** [comment]
@Xymmer Hi Bill, so basically in order to have 4 banners shown instead of 2 banners and also to have this big banner appear what are the necessary steps to do to achieve that ?
