### ISSUE TITLE
still needed?--- [master ticket] Improve development commerce backend stability: use green builds only

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1696]
There needs to be a "source of truth" commerce backend configuration for Spartacus development and release validation.

The commerce backend needs to be as deterministic as possible, so we can install the same backend on all developers local env and the dec/test servers as well.

The commerce backend needs to stay clear of module sources  ( exceptions to these might be spacceleratorsamplesaddon and commercewebservicesdata ) and ideally use only stable milestones.

One scenario is to go with:
yenv with no sources + stable milestones pulled from "updatepom_with_csp" with a specific commerce suite build number. 

Another scenario is to use commerce suite builds.

**Comment by KateChuen** [comment]
And should also specify if we need to apply some specific configuration, for eg, configuration for cms etc.

**Comment by plabadie** [comment]
Likely the reason for the updatepom_with_csp not working is that the CSP doesn't use a supermom anymore.

Which means that the updatepom_with_csp may be broken beyond repair.  We may have to come up with a system to pull the stable milestones from a csp build.

**Comment by plabadie** [comment]
For commerce suite builds:

weekly stable builds are here (more stable): https://repository.hybris.com/hybris-release/de/hybris/platform/suite/commerce-suite/

Daily green builds are here: https://repository.hybris.com/hybris-repository/de/hybris/platform/suite/commerce-suite/1905.0-SNAPSHOT/

**Comment by Xymmer** [comment]
we don't use yenv for backends anymore, always using latest releases
