### ISSUE TITLE
Spike Accessibility plan [back Aug12]

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#170]
Miguel and Kacper with Tobias were working on the Accessibility plan.
Let's conclude and get some tickets created in the new year.

Original spike: SPA-1037 (has lots of great detail)
Also see this **Accessibility Post-Summit Inventory** in SPA-1364

**Comment by giancorderoortiz** [comment]
Proposed functionality should follow a SDLC as specified here: https://wiki.wdf.sap.corp/wiki/display/PSSEC/Secure+Software+Development+Lifecycle+Overview

And must comply with security standards as detailed here:
https://wiki.wdf.sap.corp/wiki/display/PSSEC/SAP+Product+Standard+Security+-+Version+8.0
