### ISSUE TITLE
Introduce CMS configuration for fast setup

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1706]
While a fine-grained CMS setup provides a lot of flexibility when customers need more control over the content and features they use, it makes it unnecessarily complex for new customers who like a simple setup from the start. 

With this ticket, we layout the foundation for fallback configuration for CMS data. 

It also intends to layout a pattern with loading and adapter logic, to decouple the backend; alternative data sources can be used for loading data and populating it to the UI models. These patterns will be the standard for other areas such as product, cart, promotion, etc.

**Comment by tobi-or-not-tobi** [comment]
QA Steps:
- remove the 'SiteContext' slot (not just hide components) in the cms, and confirm that the lang and curr selectors are still available in the UI
- remove the 'SiteLinks' slot (not just hide components) in the cms, and confirm that the there's a hardcoded store-finder link in the UI
- remove the `BottomHeaderSlot` slot, and confirm that the breadcrumb component is still rendered (even on pages where it shouldn't, i.e. homepage)
- Remove (or hide) the curr selector, and ensure it's not getting override by the static hardcoded config

**Comment by KateChuen** [comment]
The only way to remove a slot is to go through backoffice -> wcms -> page template.

- [X] remove the 'SiteContext' slot (not just hide components) in the cms, and confirm that the lang and curr selectors are still available in the UI -> Language & Currency still displayed on the UI

- [X] remove the 'SiteLinks' slot (not just hide components) in the cms, and confirm that the there's a hardcoded store-finder link in the UI- > Store Finder link still displayed on the UI

- [X] remove the BottomHeaderSlot slot, and confirm that the breadcrumb component is still rendered (even on pages where it shouldn't, i.e. homepage) -> breadcrumb components still displayed

- [ ] Remove (or hide) the curr selector, and ensure it's not getting override by the static hardcoded config -> currency selector is not displayed on the UI anymore.


But in general, there's an issue where we need to remove the smartedit contract wrapping for the SPA components. Created [ticket](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1818) for this.
