### ISSUE TITLE
Update Angular and dependencies to v7 [waiting for ngrx7]

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#171]
Angular 7 released late October 2018.

Changelog: https://github.com/angular/angular/blob/master/CHANGELOG.md

Release policies and predictions: https://angular.io/guide/releases

**Comment by plabadie** [comment]
The dod of such an update contains these additional points:
- Update the installation doc.  (Angular CLI version, specific commands used, dependency list and versions, ... ) https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/setupandinstallation.md

- Make sure to test and evolve the QA installation script, which might have been aligned with the installation do by then.
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/setupandinstallation.md

**Comment by Xymmer** [comment]
waiting for ngrx 7, revisiting when it's released

**Comment by gladius-mtl** [comment]
Doc updates look good! 😄 
Moving this to QA.
