### ISSUE TITLE
Add setUserToken method on the AuthService facade

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1720]
In order to allow for custom authorisation flows we need to provide a method to set the user token. This would allow to get the token in a different way, and still use Spartacus as-is.

**Comment by znikola** [comment]
We already have a similar method that could possibly be renamed:
```ts
  /**
   * Store the provided token
   */
  authorizeWithToken(token: UserToken): void {
    this.store.dispatch(new LoadUserTokenSuccess(token));
  }
```

However, this method is not used internally.
If clients want to use it, they can pass a token to it and the flow will be as follows:
1. A token is passed to `authorizeWithToken`
2. `authorizeWithToken` will dispatch the `LoadUserTokenSuccess` action
3. the corresponding reducer will update the `UserTokenState` slice of the state
4. a meta reducer from `ngrx-store-localstorage` will make sure to sync the changes between the localStorage/sessionStorage and the user token slice of the state. This is configured in `auth-store.module.ts` to sync `auth.userToken` and `auth.clientToken`

**Comment by Xymmer** [comment]
still need to do this? or close?

**Comment by znikola** [comment]
I think @tobi-or-not-tobi was suggesting that we can maybe rename the method, not sure if that's something we should still do?

**Comment by Xymmer** [comment]
@tobi-or-not-tobi can you comment?

**Comment by tobi-or-not-tobi** [comment]
I think the name is actually fine, you either authorize with credentials (`authorize(userId, password)`) or with a token (`authorize(token)`).
