### ISSUE TITLE
Unification of subtotal and total prices throughout the app

### ISSUE THREAD

**Issue by kacperknapik** [SAP/cloud-commerce-spartacus-storefront#1739]
`subTotal` should be a sum of the products prices,
`totalPrice` (also `totalPriceWithTax`) should be `subTotal` + any additional costs or promotions (shipping cost, cart promotion, .., etc)

Example:
- we have 2 products in cart, both $10 = $20
- we have $9 shipping
- then:
subTotal = $20,
totalPrice = $29

Example 2:
- we have 2 products in cart, both $1000 = $2000
- we have free shipping, and we were given a promotion, -$30
- then:
subTotal = $2000
totalPrice = $1970

Currently both prices are the same.

**Comment by kacperknapik** [comment]
I tried to fix the problem on the frontend side, but it appeared that the data is sent from the backend, so couldn't really do much about it.

**Comment by Xymmer** [comment]
to be done in #3244
