### ISSUE TITLE
Fix warnings when building with libraries

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1741]
Using beautacus, saw these warnings, can they be fixed?

- warning @angular-devkit/build-angular > istanbul@0.4.5: This module is no longer maintained, try this instead:
  npm i nyc
Visit https://istanbul.js.org/integrations for other alternatives.

- warning karma > log4js > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.

and in dependencies:

- warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".

- warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".

- warning " > @spartacus/storefront@0.1.0-alpha.1" has unmet peer dependency "@angular/http@~7.2.0".

- warning " > @spartacus/storefront@0.1.0-alpha.1" has incorrect peer dependency "@spartacus/core@^0.1.0-prealpha".

- warning " > @spartacus/storefront@0.1.0-alpha.1" has incorrect peer dependency "@spartacus/styles@^0.1.0-prealpha".

**Comment by tobi-or-not-tobi** [comment]
This ticket is no longer valid. Some of the warning still happen today (mainly ng-bootstrap related), but cannot be fixed in a major release. Given that we move away from ng-bootstrap, we'll close this issue.
