### ISSUE TITLE
PDP: Text under shipping tab is now empty

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1745]
**Environment Details**
Spartacus: dev branch
Browser: chrome

**Steps to Reproduce**
Go to a PDP, for eg: http://localhost:4200/en/USD/product/266685

**Observed Results**
Data under "Shipping" tab is now empty, causing e2e test to fail. 
previously, it used to have the generic text "Lorem ipsum dolor sit amet....."
<img width="808" alt="emptyShippingTabl" src="https://user-images.githubusercontent.com/45409515/54700498-83d3de80-4b09-11e9-8abb-f81bdd279c5c.png">

**Comment by bgambocjaviniar** [comment]
It should have been fixed in GH-1408

**Comment by bgambocjaviniar** [comment]
added fix in #1321

**Comment by Xymmer** [comment]
verified fixed

**Comment by marlass** [comment]
Shipping tab is once again empty.

**Comment by mirkosoft** [comment]
Tested on the server - text is present in the tab.
