### ISSUE TITLE
SmartEdit: Styling missing on edit Page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1746]
**Environment Details**
Spartacus: https://dev-com-2.accdemo.b2c.ydev.hybris.com:9002/smartedit
Browser: chrome

**Steps to Reproduce**
Go to Smartedit, login as cmsmanager/1234
Go to "pages" of SPA Staged Catalog
Click on the 3 dots menu on the right of any page
Click on 'Edit'
<img width="938" alt="editPageSE" src="https://user-images.githubusercontent.com/45409515/54711225-d3bda000-4b1f-11e9-92cc-ea830ab279d5.png">

**Observed Results**
Missing some styling here.
<img width="1440" alt="editPagesSE" src="https://user-images.githubusercontent.com/45409515/54711233-d9b38100-4b1f-11e9-9835-51d92616d680.png">

**Comment by WeizhengSap** [comment]
Confirmed with Riry. It is on smartedit. So, I will close this ticket.
