### ISSUE TITLE
Fix peer dependencies to avoid hard reference to prealpha

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1774]
When I use Stackblitz to setup a quick demo, i'm getting the following error: 

```
Error in /turbo_modules/@angular/compiler@7.2.10/bundles/compiler.umd.js (2500:21)
Unexpected value 'undefined' imported by the module 'BreadcrumbModule'
```

Path to reproduce:
- open stackblitz
- create angular project
- add library `@spartacus/storefront`
- import `StorefrontModule` in the `app.module`

Boom.

This happens with:

- @spartacus/core0.1.0-prealpha.9
- @spartacus/storefront0.1.0-alpha.1
- @spartacus/styles0.1.0-prealpha.10

**Comment by hackergil** [comment]
If you are using storefront alpha.1, I think your core version might be too old.

**Comment by tobi-or-not-tobi** [comment]
Good point, I didn't checked that! But... this means we need to fix our peer dependencies, as they still refer to the **prealpha**.

```
npm WARN @spartacus/storefront@0.1.0-alpha.1 requires a peer of @spartacus/core@^0.1.0-prealpha but none is installed. You must install peer dependencies yourself.
npm WARN @spartacus/storefront@0.1.0-alpha.1 requires a peer of @spartacus/styles@^0.1.0-prealpha but none is installed. You must install peer dependencies yourself.
```

It actually worries me that this has passed our tests before publishing? Do we really test (automated) app creation based on the packages that will be published? As it fails as soon as you import the StorefrontModule.

FYI @Xymmer @hackergil @marlasak

**Comment by tobi-or-not-tobi** [comment]
I assume we can simply leave out the explicit version so that we refer to the latest version on npmjs.
