### ISSUE TITLE
Move translation resources to separate library

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1775]
Translations are used in the storefrontlib and in the core. But currently they are stored in storefrontlib. We should consider moving them into separate library.

It can be `@spartacus/assets` (then we can add there icons, fonts, etc. in future)

**Comment by Platonn** [comment]
To avoid conflicts, should wait for GH-1809

**Comment by mirkosoft** [comment]
With this let's wait for those two: #2210 #2394

**Comment by Platonn** [comment]
Please verify that it also works for production build of an application.

**Comment by Platonn** [comment]
... and for lazy loaded JSON translations fetched from assets.
