### ISSUE TITLE
Create seed data for cypress tests after server initialization

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#1779]
Our cypress e2e tests for checkout with an existing user needs the following pre-existing data:

User:
First Name: Test
Last Name User
email: test-user-cypress@ydev.hybris.com
Password123.

Address:
      body: {
        defaultAddress: false,
        titleCode: 'mr',
        firstName: 'Test',
        lastName: 'User',
        line1: '999 de Maisonneuve',
        line2: '',
        town: 'Montreal',
        region: { isocode: 'US-AK' },
        country: { isocode: 'US' },
        postalCode: 'H4B3L4',
        phone: ''
      }

Payment details (via a new cart)
body: {
          accountHolderName: 'test user',
          cardNumber: '4111111111111111',
          cardType: { code: 'visa' },
          expiryMonth: '01',
          expiryYear: '2125',
          defaultPayment: true,
          saved: true,
          billingAddress: {
            firstName: 'test',
            lastName: 'user',
            titleCode: 'mr',
            line1: '999 de Maisonneuve',
            line2: '',
            town: 'Montreal',
            postalCode: 'H4B3L4',
            country: { isocode: 'US' }
          }

Seed data has to be created before the test runs. According to cypress best practices, it also has to be destroyed (in case it already exist) before running the test.

**Comment by KateChuen** [comment]
In my original test for "checkout with an existing user", I was
- at the beginning of the test:
--  creating a new shipping add
-- creating a new payment card
- at the end of the test, cleanup:
-- deleting the shipping add
-- deleting the payment card

Unfortunately these were removed after the refactoring for adding the mobile viewport was done. 
So I'm adding these again. As such, I won't need to have them in this new file.

In this new file, I will be only,
- checking if the user already exists. If not,
-- register the test user.

**Comment by KateChuen** [comment]
PR https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1941

**Comment by KateChuen** [comment]
After talking to Gil, we decided to keep the setup & teardown of the test data in the test itself (I prefer it this way, so it's independent from creating the test user, which can be run every time we initialize the environment. Then the test data is tied with the test which is when we need it).
BUT, will use rest calls to delete the data, to make sure it is properly deleted.
