### ISSUE TITLE
DOC: Forgot Password compatibility note

### ISSUE THREAD

**Issue by gladius-mtl** [SAP/cloud-commerce-spartacus-storefront#1781]
This is a request for doc input with regards to the Forgot Password feature and its compatibility with 1811 vs 1905.

The idea to be expressed is something along the lines of "you need 1905 because of a new api that allows spartacus to reset the pasword was missing before".

Input can be added in a comment to this ticket 🙂 

Thank you!

**Comment by plabadie** [comment]
The reset password feature requires and SAP Commerce backend version 1905.  One required API endpoint was created in 1905.  The other required endpoint was updated in 1905 for the feature to work as intended.
