### ISSUE TITLE
Some Cart Order summary Lines empty after user logs in

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1782]
**Environment Details**
http://dev-com-22.accdemo.b2c.ydev.hybris.com:4200
Browser: chrome

**Steps to Reproduce**
Do not login.
Go to SPA
Add a few items to cart
Go to Cart Page -> The cart calculations(discount, tax, total) are there.
<img width="1008" alt="cartAnonymousUser" src="https://user-images.githubusercontent.com/45409515/54843219-3e9ae280-4caa-11e9-9617-7245e0bd0fcc.png">

Click on "Proceed to checkout"
Click on Register
Register a new user or Login as a registered user
Go to Cart Page again

**Observed Results**
Some of the cart calculations are now empty (discount, tax, total)
<img width="1009" alt="cartRegisteredUser" src="https://user-images.githubusercontent.com/45409515/54843201-35aa1100-4caa-11e9-9b29-8b4e765d94e0.png">
<img width="1009" alt="cartLoggedUser" src="https://user-images.githubusercontent.com/45409515/54843295-6db15400-4caa-11e9-9cb6-1bd59fade835.png">

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1822

**Comment by KateChuen** [comment]
Tested on dev22 (with updated backend from April 3rd & frontend). 
- Now the cart summary is populated after cart merge for both a new user & a registered user. 
- The only minor issue (unrelated to this ticket) is that the user gets redirected to the homepage after registration (opened ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1926 for this).
