### ISSUE TITLE
Apparel UK search doesn't work

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1787]
Apparel UK has the "old" (gen-1) variants that are still supported.
If I connect Spartacus to apparel-uk backend, search doesn't work.

When you search in Apparel UK, you get 1 example for a variant set.
So for example, jacket X1 comes in red, blue, green.
When searching, you just see one entry of X1 in red.

Later we have to add variant selection in product page but that's for later.

**Comment by mirkosoft** [comment]
For the lack of variants in the typeahead searchbox the issue is because `variantOptions` is missing in the search request call.
Also results should be modified to reflect variants before rendering the searchbox results content.

**Comment by Xymmer** [comment]
- lack of variants: solvable
- not sure solvable yet, Miro is investigating: search results page layouts/slots

**Comment by mirkosoft** [comment]
When I use `variantOptions` in a call for search results there is no `price.formattedValue` for the product record. So the price is not shown at the searchbox product results.

**Comment by mirkosoft** [comment]
@Bill I think we can close this one.

**Comment by mirkosoft** [comment]
Compared to the current ACC behaviour is the same (on both screens the first "Trace..." helm is a variant):
![image](https://user-images.githubusercontent.com/788092/63175051-82b8c600-c043-11e9-9977-23e555d60492.png)

and I would say this is fine as solr WILL return variants if query is more specific:
![image](https://user-images.githubusercontent.com/788092/63175469-5baec400-c044-11e9-987b-83dc95158f6e.png)

It works the same way for SRP. I think it would be nice to have the SRP page equipped with variant indicators however, similar as it's already on the current acc PLP:
 
![image](https://user-images.githubusercontent.com/788092/63176222-d4fae680-c045-11e9-92d8-427f7d1b8cdd.png)

@Xymmer ticket to close?

**Comment by Xymmer** [comment]
works as designed, we display what we get (combined or not, depends on solr config)
