### ISSUE TITLE
Missing catalogVersion data on components (all components are assigned to `undefined` catalog/version)

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1789]
I can see this error in smartedit.

**Comment by WeizhengSap** [comment]
To QA/code reviewer:

With the fix, you should not see this error "externalComponentDecorator - cannot find catalog version for uuid undefined" in smartedit.

![Screen Shot 2019-03-25 at 8 44 54 AM](https://user-images.githubusercontent.com/44440575/54920711-4e990900-4eda-11e9-9daf-13b4fd5b5b36.png)

**Comment by plabadie** [comment]
There are conflicts to resolve and the CI has errors.  Let's resolve this first.

**Comment by plabadie** [comment]
Smoke tested, the  "externalComponentDecorator - cannot find catalog version for uuid undefined" in smartedit." does not show up:

<img width="1670" alt="Screen Shot 2019-03-26 at 3 25 00 PM" src="https://user-images.githubusercontent.com/7065346/55027435-acf9e080-4fdb-11e9-9263-c2a55d6e5f62.png">
