### ISSUE TITLE
Configurable OCC endpoints for auth module

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1791]
Add configuration for OCC endpoints in auth module.

See #1790

**Comment by giancorderoortiz** [comment]
Tested with: 
endpoints: {  login: 'test/supersecure/auth/request' }
Observed:
1. In Storefront, actual calls to login and/or register are not made at all. 
1.a. There are no error messages displayed to user. 
1.b. Dev-tools -> network remains empty. 
2. In angular CLI, there are no error messages either.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-08-07 at 9 49 30 AM](https://user-images.githubusercontent.com/46171897/62632435-76749080-b900-11e9-8e26-24ae0174d33f.png)

**Comment by LTiger14** [comment]
Created #3972

**Comment by LTiger14** [comment]
Please retest

**Comment by giancorderoortiz** [comment]
Retesting

**Comment by giancorderoortiz** [comment]
Test successful

![Screen Shot 2019-08-11 at 1 29 09 PM](https://user-images.githubusercontent.com/46171897/62837456-a17f1d00-bc3d-11e9-8bb7-c0473bd518bf.png)
