### ISSUE TITLE
Configurable OCC endpoints for cart adapters

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1792]
Add configurable OCC endpoints for cart adapters.

See #1790

**Comment by LTiger14** [comment]
Execute the following steps with the console open. There should be no error and the behaviour should be as intended:
- Register
- Add a product to cart
- Go to cart page (should see one product)
- Logout
- Add a product to cart (different than before)
- Add a second different product to cart
- Go to cart page (should see two products)
- Remove one product
- Add one quantity to the remaining product
- Login with the account you created
- Go to cart page (should see two product with a total of 3 quantities)
- Execute a checkout, at the end cart should be empty

**Comment by giancorderoortiz** [comment]
Modified endpoints for error checking as follows: 
cart: 'users/${userId}/acmeCarts.... '
updateEntries: 'users/${userId}/acmeCarts....'
addEntries: 'users/${userId}/acmeCarts....'

Observed: 
1. infinite loop when navigating to product categories or performing product search. 
1.a. Expected to fail gracefully here. 

2. When attempting to add to cart, I get an endless spinner on added-to-cart overlay.

**Comment by giancorderoortiz** [comment]
![added-to-cart-endless-spinner](https://user-images.githubusercontent.com/46171897/62654062-03354380-b92d-11e9-8d1d-0db11a8589e6.png)
![cart-infinite-loop](https://user-images.githubusercontent.com/46171897/62654063-03354380-b92d-11e9-88c1-592ece3343a6.png)

**Comment by LTiger14** [comment]
Issue for the comments above #4043 . Not related to the changes from this PR but still an issue.

**Comment by giancorderoortiz** [comment]
Retest of #4043 successful. 🆗
