### ISSUE TITLE
Configurable OCC endpoints for user adapters

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1797]
Add configurable OCC endpoints for user adapters.

See #1790.

**Comment by plabadie** [comment]
PR #3879

**Comment by plabadie** [comment]
For tests, make regression tests on the following features:

- Register New user
- Forgot Password ( request email + reset the password ) 
- My Account -> Update Password
- My Account -> Update Email
- My Account -> Update Personal Details
- My Account -> Close Account
- My Account -> Payment Details
- My Account -> Consent management.
- My Account -> Order History (list + detail)
- My Account -> Address Book

**Comment by giancorderoortiz** [comment]
e2e tests successful - no regression seen. 
Manual verification successful as well. 

Using invalid endpoints, such as these, causes the correct error to be displayed in console. 
user: 'acmeuser',
userUpdatePassword: 'acmeUserUpdatePassword',
addresses: 'acmeAddresses'

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-08-07 at 11 10 36 AM](https://user-images.githubusercontent.com/46171897/62634989-d1a88200-b904-11e9-9859-547d0ae9f4d2.png)
![Screen Shot 2019-08-07 at 11 11 48 AM](https://user-images.githubusercontent.com/46171897/62634991-d1a88200-b904-11e9-9240-e0860814af88.png)
![Screen Shot 2019-08-07 at 11 13 29 AM](https://user-images.githubusercontent.com/46171897/62634995-d2411880-b904-11e9-8aae-c6be17db6463.png)
