### ISSUE TITLE
Order status - localization

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1806]
Order data that come from OCC `/orders` endpoint contain `statusDisplay` property, but it's not translated (despite the fact that occ call is made with query parameter `lang=de`).

Should we translate the value in the frontend or somehow we can get the translated value from backend?
If we have to translate in frontend, what are all possible values

# Spartacus Example:
`rest/v2/electronics-spa/users/kp@ydev.hybris.com/orders/00002024?fields=FULL&lang=de&curr=USD`

![obraz](https://user-images.githubusercontent.com/4001059/55000021-dc0b5480-4fd1-11e9-94a0-62d7597a3523.png)
![obraz](https://user-images.githubusercontent.com/4001059/54999931-a6666b80-4fd1-11e9-91bc-71e70cad3c1e.png)

# NOTE: In the accelerator the status is translated:

![obraz](https://user-images.githubusercontent.com/4001059/55060383-a4ec8000-5071-11e9-8ea5-32f4272bf68f.png)

**Comment by Platonn** [comment]
Property `displayStatus` is not translated on the backend.
Here is the list of all possible `displayStatus`es (as keys) and relevant translations (as values):
```
cancelled: 'Cancelled'
cancelling: 'Cancel Pending'
completed: 'Completed'
created: 'Created'
error: 'Pending'
Error: 'Pending'
open: 'Open'
processing: 'In Process'
```

please note duplicate of error/Error

**Comment by Xymmer** [comment]
@mirkosoft : is this already being handled with other tickets? if so pls close

**Comment by mirkosoft** [comment]
@Xymmer I don't think so. Indeed, It is a similar issue (trasnaltions frontend or backend?). I guess this is more like order status vs delivery status but didn't ensure yet.
