### ISSUE TITLE
06b: Use translations in HTML

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1808]
1 move translations from ```storefrontapp/src/assets/i18n/xxx.en.json``` to ```storefrontlib/src/translations/en/xxx.en.ts``` (also convert json to ts) 
2 update ```storefrontlib/src/translations/index.ts```
3 use `cxTranslate` pipe in component's templates

**Comment by Pucek9** [comment]
Let's use this comment to tag yourself (inform others which part you are working on)

Common components:
*common (header/footer)
*orderSummary
*product
*payment
*address

Features:
*authorization (login/guest login/update forgotten password, register)
*addToCart (without product)
*productList (search/brand/category, without addToCart)
*productDetailst (without addToCart)
*cart (without orderSummary, product)
*order (orders/confirmation, without orderSummary, product)
*checkout (checkout, shipping method, without orderSummary, address, payment, product) 
*storeFinder
* address-book (without address)
