### ISSUE TITLE
Dynamic attributes from response are ignored

### ISSUE THREAD

**Issue by RobertOzgaSap** [SAP/cloud-commerce-spartacus-storefront#1813]
All dynamic `properties` of components are ignored by SPA.
Only selected few are added as attributes to DOM in component-wrapper.directive.

This blocks personalization mode in smartedit from working properly because we are adding custom attributes required only by peronalization to work with the page.

In my opinion it would be beneficial if all `properties` would be added dynamically to the page transforming
`properties.group.name` into `data-group-name` attribute.

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1858

**Comment by plabadie** [comment]
<img width="1668" alt="Screen Shot 2019-04-01 at 4 55 34 PM" src="https://user-images.githubusercontent.com/7065346/55359118-1166e500-549f-11e9-91ea-e50367818f45.png">
