### ISSUE TITLE
Replace the hard-coded preview product/category code in smartedit service

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#1816]
Depends on https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1810. After this ticket done, we should be able to read the preview product/category codes from ngrx/store. We need use these codes to replace the hard-coded ones.

**Comment by Xymmer** [comment]
We currently have hard coded product "2053367" and category "575" in smartedit. But, if users don't have this product and category, there is problem. these 2 codes are set in `site`.

so we should fix this for beta.

**Comment by WeizhengSap** [comment]
To QA/code reviewer:

To test it:
1. go to smartedit->PAGES, open "product details" page. You should see the default preview product (code is: 2053367). 
2. go to backoffice->WCMS->website, open site "electroncis-spa", then go to tab "WCMS properties", change the "Default Preview Product" to another product.
3. back to smartedit, open "product details" page, you should see the product you set in step 2.

Same for the category.
1. go to smartedit->PAGES, open "product list" page. You should see the default preview category (code is: 575)
2. go to backoffice, change the "default preview category" to another category.
3. back to smarteidt, open "product list" page again, you should see the new category.

**Comment by KateChuen** [comment]
Tested on dev2.
- Verified that the default product details page is for product 2053367:
![SEoriginalPdp](https://user-images.githubusercontent.com/45409515/58655723-c4f62500-82e8-11e9-8c30-55a910fc8b84.png)

- Verified that I can change the default product for pdp
![SEnewPdpBackoffice](https://user-images.githubusercontent.com/45409515/58655737-cc1d3300-82e8-11e9-9d3f-9cda17db5071.png)

- Verified that the new product 1432722 is displayed on pdp
![SEnewPdp](https://user-images.githubusercontent.com/45409515/58655742-d0e1e700-82e8-11e9-9102-1f72b1f3e730.png)

- Verified that the default product listing page is for category 575:
![SEcurrentCategory](https://user-images.githubusercontent.com/45409515/58655756-d6d7c800-82e8-11e9-8a9f-1a151ad50172.png)

- Verified that I can change the default category for plp
![SEnewCategoryBackoffice](https://user-images.githubusercontent.com/45409515/58655761-da6b4f00-82e8-11e9-9b85-1deab337bbed.png)

- Verified that the new category 587 is displayed on plp
![SEnewCategoryPreview](https://user-images.githubusercontent.com/45409515/58655772-e35c2080-82e8-11e9-8e7b-2a4493592d68.png)
