### ISSUE TITLE
[still an issue?] Remove smartedit contract wrapping of SPA components

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1818]
After [ticket](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1706) was implemented, where we can remove a slot from the template page and the it will still renders.

So basically the issue now is that, we have to remove the smartedit contract wrapping of the SPA components. 
Because otherwise, Smartedit is still trying to look for it. But the components are not cms components that are in the database anymore. 

- To remove a slot, go to backoffice -> WCMS -> Page Template
- You'll  see this error when you open it in smartedit. 
If after removing the wrapping, the issue is still present, then we'll need to open a ticket on smartedit side. 

![slotRemovedSPA](https://user-images.githubusercontent.com/45409515/55023727-d4e54600-4fd3-11e9-97fb-30b2e5206b45.png)

GET https://dev-com-2.accdemo.b2c.ydev.hybris.com:9002/cmswebservices/v1/catalogs/electronics-spaContentCatalog/versions/Staged/pages/homepage/contentslots/SiteContextSlot/typerestrictions 400

**Comment by Xymmer** [comment]
Hey Kate, is this still an issue after all smartedit changes?

**Comment by KateChuen** [comment]
Not an issue anymore. Tested on dev2, and there's no error now.
