### ISSUE TITLE
Order delivery status - localization

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1825]
Order data that come from OCC `/orders` endpoint contain consigments with `deliveryStatus` (and each individual consignment has its own `status`). The value is uppercased (i.e. `SHIPPED`). What are all possible values and are they always uppercased? 
![obraz](https://user-images.githubusercontent.com/4001059/55066273-bb98d400-507d-11e9-858d-f401a4d1e52d.png)

**Comment by Platonn** [comment]
The lowercase values will be exposed in separate keys - scope of backend ticket https://jira.hybris.com/browse/RAY-273

Until then we will use the uppercase values. Then we will change to other keys and lowercase values.

**Comment by Pucek9** [comment]
Please use convention proposed in #1962

**Comment by Platonn** [comment]
Possible values of `consignment.status` / `deliveryStatus`
```
READY_FOR_PICKUP: 'Ready for pickup',
PICKUP_COMPLETE: 'Picked up',
SHIPPED: 'Shipped',
CANCELLED: 'Cancelled'
```

**Comment by mirkosoft** [comment]
Did a server QA - all fine.
