### ISSUE TITLE
Stock level status - localization

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1826]
`cart-item.component.html` in line 107 renders conditionally the `stockLevelStatus` property only when it has value `outOfStock`. 
We should use `stockLevelStatus` to conditaionally show something, but the message should be different, taken from translations.

**Comment by Pucek9** [comment]
Please use convention proposed in #1962

**Comment by mirkosoft** [comment]
@Platonn here I would also get rid off this method:
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/77c7c65dac0eca5ccb7ae34303f29730df9cc8bf/projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts#L31

and use `cxTranslate` in the template.
