### ISSUE TITLE
Firefox: Cannot select product in product search autocomplete

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1831]
## Environment Details

- Spartacus: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/
- Browser: Firefox

## Steps to Reproduce
- Type in something in the search box, for eg, powershot.
- Once the search autocomplete result is displayed, click on one of them.

## Observed Results
It doesn't do anything

## Expected Results
it should select the product and go to its pdp.
<img width="1310" alt="firefoxSelectSearchResult" src="https://user-images.githubusercontent.com/45409515/55086856-7d041900-507f-11e9-9fdc-d0102c0f4c4c.png">

**Comment by Xymmer** [comment]
might get replaced with code as it's ng-bs

**Comment by Xymmer** [comment]
works now, we recently did some refactoring on search box
