### ISSUE TITLE
Footer: Missing some links when we change to other languages

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1833]
## Environment Details

- Spartacus:  http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/

## Steps to Reproduce
- Look at the footer
- Change the language to anything other than EN.

## Observed Results
Looks like some links are missing. Is that because we don't have localization yet?

<img width="1010" alt="ENFooter" src="https://user-images.githubusercontent.com/45409515/55087257-34009480-5080-11e9-8ad2-83e64a00c6a2.png">

<img width="1009" alt="DEFooter" src="https://user-images.githubusercontent.com/45409515/55087278-3c58cf80-5080-11e9-8838-e2a859b0b60b.png">

**Comment by Xymmer** [comment]
these texts come from cms... are we not getting the texts or it's something in spartacus?

**Comment by Xymmer** [comment]
checked dev17, still happening, even in english

**Comment by Xymmer** [comment]
also see #1424

**Comment by tobi-or-not-tobi** [comment]
There are 2 issues:
1. Texts are not translated in the sample data; each cms link component can have a localised name, most links have only been provided in english. It's not a Spartacus issue though since it's content. @Xymmer perhaps we get a ticket done on this in sample data (ideally electronics data, so that we "inherit" this in electronics-spa). 
2. The generic link component doesn't show the title when it's an external link. this is a bug and fixed with this ticket.

**Comment by tobi-or-not-tobi** [comment]
QA:
- All headers and links in the footer should be visible
- switching to another language would not necessary show content
- add text for other language for links, ensure the text does show up when the language is selected

**Comment by KateChuen** [comment]
Tested on dev2.
- All the footer links are displayed now. Even when we change languages.
<img width="1075" alt="footerLInks" src="https://user-images.githubusercontent.com/45409515/58568947-2d6ad680-8203-11e9-86a6-19091a4364e9.png">


- Added text for the links for all the languages and they are displayed when we change languages.
<img width="1075" alt="footerDE" src="https://user-images.githubusercontent.com/45409515/58568930-280d8c00-8203-11e9-82fa-357d17dc9028.png">

<img width="1065" alt="footerEN" src="https://user-images.githubusercontent.com/45409515/58568934-29d74f80-8203-11e9-8d55-282669af1d0f.png">

<img width="1072" alt="footerJA" src="https://user-images.githubusercontent.com/45409515/58568935-2a6fe600-8203-11e9-9b03-561f7e577e9a.png">

<img width="1075" alt="footerZH" src="https://user-images.githubusercontent.com/45409515/58568937-2a6fe600-8203-11e9-9304-96a5aa7255d2.png">
