### ISSUE TITLE
[try to repro] Safari: Cannot register a new user

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1835]
**Environment Details**
Spartacus: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/
Browser: Safari

**Steps to Reproduce**
Try to register a new user.

**Expected Results**
it looks like it fails. but it actually went through, and can login with that user afterwards. 
The calls are not in the correct order.

**Note**: Gil & Patrick don't experience this issue. Only happens to me.

<img width="1345" alt="registerUserSafari1" src="https://user-images.githubusercontent.com/45409515/55092185-7d54e200-5088-11e9-83ea-0acac576931c.png">

<img width="1392" alt="registerUserSafari2" src="https://user-images.githubusercontent.com/45409515/55092186-7d54e200-5088-11e9-9cc2-766550c51894.png">

<img width="1407" alt="registerUserSafari3" src="https://user-images.githubusercontent.com/45409515/55092187-7d54e200-5088-11e9-9893-b18874465b0c.png">

**Comment by KateChuen** [comment]
Still can reproduce it.

**Comment by mirkosoft** [comment]
I can't reproduce it on Safari - just created an account successfully.

**Comment by KateChuen** [comment]
Closing since noone else can reproduce this.
