### ISSUE TITLE
link to build.gradle file in installation doc

### ISSUE THREAD

**Issue by pawelwloch** [SAP/cloud-commerce-spartacus-storefront#1838]
Please submit the appropriate build.gradle in the build instructions in p. iii for _b2c_for_spartacus recipe_. Currently link leads to 404 Not Found page. I mean ["Installing SAP Commerce Cloud" instructions](https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Installing-SAP-Commerce-Cloud)

**Comment by Xymmer** [comment]
link has been fixed
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/archived_installation_docs/back_end_installation/1811/build.gradle
