### ISSUE TITLE
Consider to remove lang suffix from namespace files

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#1847]
While we use folders as lang-containers, lets remove redundant extensions of files. It will allow for easier adding new languages by copy-paste.

**Comment by Xymmer** [comment]
@Pucek9 : is this one still needed, if so is it for 1.0 launch, or after?

**Comment by Pucek9** [comment]
> @Pucek9 : is this one still needed, if so is it for 1.0 launch, or after?
@Xymmer 
That is only light proposal, it can be done later for sure.

**Comment by mirkosoft** [comment]
I am going to do this along with #1775
