### ISSUE TITLE
PR: [RAY-259] Default preview catalog in sample data

### ISSUE THREAD

**Issue by pg-sap** [SAP/cloud-commerce-spartacus-storefront#1851]
Hello,

The attribute `defaultPreviewCatalog` has to be set for the SmartEdit integration.

Please review the following pull request to `spacceleratorsamplesaddon`:

- [spacceleratorsamplesaddon/pull-requests/35](https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/35/overview)

**Comment by WeizhengSap** [comment]
PR was merged.
