### ISSUE TITLE
[Blocked] Update dev servers backend

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1859]
Update server deployment template so that they only pull in latest milestones and then update the servers

**Comment by plabadie** [comment]
Spartacus template updated
https://stash.hybris.com/projects/INFRA/repos/yenv/commits/153559f8207c06e9046dca3a0b28cde2ff12f1dc

**Comment by hackergil** [comment]
We will be moving forward with only RC versions and stop using yenv
