### ISSUE TITLE
Perform a whitesource scan on current codebase

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1860]
and then let's discuss the results, create tickets, maybe add some to the sprint and backlog the rest.

**Comment by hackergil** [comment]
Whitesource scan results here: http://wsui.mo.sap.corp:8080/wsui/#
Documentation: https://wiki.hybris.com/display/spar/SPA+Security

Next steps:
* Create tickets to address security concerns
* Determine how often should we do a whitesource scan (and potentially integrate it to our CI)
