### ISSUE TITLE
Loop calling PageLayoutService.getSlots when using ngb-carousel

### ISSUE THREAD

**Issue by cuongrio** [SAP/cloud-commerce-spartacus-storefront#1862]
Hi all,

I am developer hybris, and I am using spartacus for separate storefront.
But I have an issue when I make slider by ngb-coursel
--------------
Window resize trigger call interval when I create component using <ngb-cousel>

![Capture](https://user-images.githubusercontent.com/5031533/55216845-74067980-5230-11e9-9682-d724a4aeed16.PNG)

## Environment Details

- Spartacus:  lastest
- Browser: Chrome
- OS: Window 10
- Device: Desktop/Wrap

## Steps to Reproduce
1. Add new Slider Component
 html using ngb-carousel

2. PageLayoutService.getSlots calling when slider next or previous

## Expected Result
PageLayoutService.getSlots call only one time when slider run

Thanks you for supporting

**Comment by tobi-or-not-tobi** [comment]
I'm not totally sure about the underlying structure, but in general when you build a component, you should not interact with slots. 

The CMS structure we use has:
- a route (URL) related to a CMS page
- a CMS page holds slots (some indirect through page templates)
- a slot holds components

You should implement this in a component, which is where you can also implement a window resize handler. You can get some inspiration from the Spartacus `ProductCarouselComponent`, or have a look at the `BreakpointService.breakpoint$`.
