### ISSUE TITLE
Configurable Nested Routes and auxiliary router outlets

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#187]
It's a subtask of #3.

After doing this task, all acceptance criteria of tasks mentioned above should hold. However, now we would like to also support configurable nested routes. Algorithms to find best matching url to render a link should be modified, if needed.

Motivation for having nested routes: Me may need nested routes to handle a 'sub-navigation' state of a page (for example the current step of the checkout or the active tab in product-details page).

It would be good to also investigate auxiliary router outlets

**Comment by Platonn** [comment]
Docs
- Routes Configuration # Children routes (nested routes)
    https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/core/src/routing/configurable-routes/docs/routes-configuration.md#children-routes-nested-routes

- Configurable router links # Links to nested routes
    https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/core/src/routing/configurable-routes/docs/configurable-router-links.md#links-to-nested-routes

**Comment by gladius-mtl** [comment]
Created a follow-up ticket to take care of documentation: GH-742.
Moving this ticket now to QA.
