### ISSUE TITLE
[needs backend change] Store finder - no opening/closing hours for languages other than English

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1879]
Reproduce steps:
- Using `devcom17` backend 
- enter url `http://localhost:4200/electronics-spa/de/USD/store-finder/country/JP`
- change language any other than English, i.e. German

Then I get an infinite loop with errors in the console 
```
ERROR TypeError: Cannot read property 'closed' of undefined
    at StoreDataService.push.../core/src/store-finder/facade/store-data.service.ts.StoreDataService.isStoreOpen (store-data.service.ts:86)
```
![obraz](https://user-images.githubusercontent.com/4001059/55326222-829a9e00-5487-11e9-80d6-319a77e7574b.png)

**Comment by Xymmer** [comment]
we shouldn't get infinite loop if there is no such info

**Comment by Matejk00** [comment]
This bug still exists. When you set for example Chinese language and go to 'View all stores' in storefinder, the infinite loop happens:

`Cannot read property 'closed' of undefined`

**Comment by mirkosoft** [comment]
we have to wait for the backend change:
![image](https://user-images.githubusercontent.com/788092/63158728-34db9800-c01a-11e9-95aa-dc5d548a1385.png)

**Comment by Matejk00** [comment]
Infinite loop removed. Opening hours for specific language should be set on backend.
