### ISSUE TITLE
Beauty sample data 1

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1881]
beautystore samples from chris w: https://stash.hybris.com/projects/E2EC/repos/e2econnector/browse/beautystore

maybe we need to make a copy and put it alongside spaccelerator for now

some things we need to do (basically all the spartacus-specific changes we did to electronics that ended up in electronics-spa)
- fix category nav (chris used a legacy component we don't support)
- language/currency + other links at top right including storefinder
- delete re-order

new:
- hide breadcrumb and title on home page

**Comment by Xymmer** [comment]
I couldn't get beauty store working then noticed the project.properties file is missing.
I copied the electronics one, changed it to beauty, and it worked.
Assigning back to Wei and putting into to do to update the repo.

**Comment by WeizhengSap** [comment]
project.properties was added to repo, and remove it from `.gitingore`.
