### ISSUE TITLE
solr search result changed again

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1903]
**Scenario #1:**
Go to "Digital camera -> compact cameras"

Before, we used to have "DSC-WX1" returned as first product displayed.
Now it's DCS-S930.

**Scenario #2:**
Type this "DSC-N1" in the search box and press enter.
Go to next page.
Before, we used to have "DSC-W180" returned as first product on 2nd page. Now it's "DSC-WX1"

Looks like the search results keep changing back and forth. Need to investigate and fix it once and for all. Otherwise, we have to keep fixing the e2e tests.

**Comment by Xymmer** [comment]
backend issue and we're looking into it in a separate task

**Comment by Xymmer** [comment]
this might have been because of async problem that probably is fixed... retest and if still a problem, move to bug bucket

**Comment by KateChuen** [comment]
Looks like it's fixed (for now). Ran the product search tests against dev17, and they passed.
