### ISSUE TITLE
After deleting default payment, the other payment doesn't become default

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1905]
**Environment Details**
Spartacus: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/
Browser: Safari

**Steps to Reproduce**
Have 2 payment card details in MyAccount.
Delete the "default" one.

**Expected Results**
The other payment card should now become the default one. 

- [ ] After this is fixed, please change the 'payment-methods.ts' e2e test to make an assertion on this. 
Line 142:   defaultCard.should('contain', 'DEFAULT');

<img width="977" alt="defaultPayment" src="https://user-images.githubusercontent.com/45409515/55432629-5eab8b00-5561-11e9-839b-cb00e0edb05a.png">

**Comment by Xymmer** [comment]
whatever next first payment is can be default after deleting first payment... whatever backend gives us... but if none are set to default then set first payment
