### ISSUE TITLE
Doc: Improve configuration structure for backends 

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1913]
Docs for GH-1784

**Comment by gladius-mtl** [comment]
Docs reviewed and merged to develop. Closing this ticket now.

**Comment by gladius-mtl** [comment]
Re-opening so that updates can be made to https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Configuring-the-Base-URL

**Comment by gladius-mtl** [comment]
No further updates required. Re-closing 😄

**Comment by gladius-mtl** [comment]
Final review of https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Configuring-the-Base-URL now complete. 

Closing ticket and moving to "Done".
