### ISSUE TITLE
Recipe to upgrade backend servers without yenv

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#1916]
Create a spartacus recipe to upgrade backend servers from commerce suite RCs

**Comment by hackergil** [comment]
- New hybris installer recipe for Spartacus [here](https://stash.hybris.com/projects/DIST/repos/conf-commerce-suite/browse/patches/installer/recipes/spartacus?at=refs%2Fheads%2Fspartacus)
- Script to update spartacus [here](https://stash.hybris.com/projects/C3PO/repos/devconfigs/browse/scripts/deploy_cx_for_spa.sh)

**Comment by plabadie** [comment]
Is there a reason for the local.properties file in the Spartacus recipe?

The properties all seem to be already set in the .gradle file.  Maybe we can do without the local.properties file and have something leaner?
