### ISSUE TITLE
Regression test April 10 2019 lib release

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1955]
- [x] Run all the E2E tests on the nightly branch on jenkins:
Note: Make sure that ALL the tests are being run (about 29 tests).
OR run them from your computer, pointing to dev17 server.

Because these ones have not been migrated to cypress yet, you have to run them manually:
Use this server: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/
Keep the browser's console open at any time and monitor for errors.
- [x] ~Order history page~ - we do have e2e test for that
- [x] Change language/currency

Additionally, do a quick smoke test (equivalent to the big happy path test) on:
- [x] Safari
- [x] Firefox

**Comment by kacperknapik** [comment]
on Firefox I found one problem, during checkout:

![firefox_delivery_mode](https://user-images.githubusercontent.com/22354613/55882685-3d701d80-5ba5-11e9-9787-bb7abb67c256.PNG)

not sure (probably not) if that's firefox-related, but still, something like that appeared

**Comment by marlass** [comment]
Seems like this is an issue with backend object missing. Happened to see this type of error in other browsers. Maybe there is some race condition with backend requests.
