### ISSUE TITLE
User should not stay on Update Password page upon signing out

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1957]
**Environment Details**
Spartacus: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/
Browser: Chrome

**Steps to Reproduce**
Sign in.
Go to "MyAccount" -> "Password"
Sign Out.

**Actual Results**
User remains on the "Update Password" page. 
<img width="1290" alt="updatePwdSignout" src="https://user-images.githubusercontent.com/45409515/55753786-2ac8dd80-5a19-11e9-85ba-decfab6b9e51.png">

**Expected Results**
User should be redirected to homepage maybe? 

**Note**: Same thing happens with 
- Update Personal Details  
- Update Email.
- Close Account
Signing out on "Close my account" page leaves the user on the same "Close my account" page. And if user clicks on "Close my account" from there, s/he even gets the popup window to confirm it. But s/he cannot actually close the account from there. 
<img width="1084" alt="closeAccountSignedOut" src="https://user-images.githubusercontent.com/45409515/56610243-fb9b9a00-65dc-11e9-8317-7a8071c5a747.png">

**Comment by Xymmer** [comment]
there's a linked pr but unsure if it's fixed
to dev first to check, fix, or to qa to retest if we think it's fixed

**Comment by Xymmer** [comment]
tested may 19, is fixed
