### ISSUE TITLE
Translation refactor

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#1962]
Main assumptions:
- key name should be closer to component/micro-feature
- remove structure `action`, `label`, `placeholder`, `validation`. There is not much duplicates so we can use eg. `addressForm.firstName.label` & `addressForm.firstName.placeholder` instead of `addressForm.label.firstName` & `addressForm.placeholder.firstName`

storefrontlib/src/translations/en
core\src\i18n\config\default-i18n-config.ts

**Comment by mirkosoft** [comment]
From now on please do not use nestings like `label` or `placeholder` until the key has more than one usage variant. Example of correct nesting:
```
  addressForm: {
    title: 'Title',
    firstName: {
      label: 'First name',
      placeholder: 'First Name',
    },
    lastName: {
      label: 'Last name',
      placeholder: 'Last Name',
    },
    address1: 'Address 1',
    address2: 'Address 2 (optional)',
    country: 'Country',
    ...
  }
```
