### ISSUE TITLE
Spike: Replacing ng-bootstrap

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#1969]
These files below are still dependent on `ng-bootstrap`.
This list is provided in order to potentially replace `ng-boostrap` functionality with something else, must likely TypeScript custom code, or another library.

1. Header / category-navigation component
2. Search Results - Category Listing / product-list component
3. Search Results - Category Listing  / product-facet-navigation component  
4. Cart Page / add-to-cart component  
5. Cart Page / added-to-cart-dialog component  
6. Cart Page / cart-item component 
7. Checkout Wizard / multi-step-checkout component  
8. Checkout Wizard / payment-form component 
9. Checkout Wizard / address-form component 
10. Checkout Wizard / suggested-addresses-dialog component 
11. Store Finder / store-finder-list-item component  
12. cms-lib/navigation/navigation-ui.component.scss 
13. cms-lib/search-box/search-box.component.scss  
14. ui/components/form-components/star-rating/star-rating.component.scss  
15. ui/components/pagination-and-sorting/pagination/pagination.component.scss

**Comment by Xymmer** [comment]
to do: examine what devs have to do, so we can create individual tickets
