### ISSUE TITLE
Fix regression e2e tests for search

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#1972]
e2e tests for search are consistently failing in our nightly build, most likely because the xhr calls (filter by face, price, sorts) are failing. We need to add cypress waits for the XHR calls on these tests.

Examples on how to fix/refactor at projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-product-type-flow.ts

**Comment by Pucek9** [comment]
@hackergil Are you sure it is a source of failing tests? I have verified some last builds and one test need to have updated selector and text assertion (there was different order of products)

**Comment by Pucek9** [comment]
I don't think so it's good solution (anti-pattern), but since merging in to backend are allowed without successful e2e regression, we decided to read XHR response and compare it with UI for getting more stable

**Comment by hackergil** [comment]
Hey @Pucek9 thanks for fixing some of the tests! A couple more are still failing though. Can you take a look?

https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/
