### ISSUE TITLE
The BottomHeaderSlot is not positioned properly.

### ISSUE THREAD

**Issue by stepan-aleksandrov** [SAP/cloud-commerce-spartacus-storefront#1985]
The BottomHeaderSlot is not positioned properly in a viewport (looks like it's outside of the viewport).

## Environment Details

- Spartacus:  latest develop
- Browser: Chrome 73.0.3683.86
- OS: Mac Os

## Steps to Reproduce
1) Order any product and go to a Shopping Cart page.
2) See: the BreadCrumb component does not have a decorator around. So it's not smarteditable.

## Offer to Fix
The BottomHeaderSlot that contains a BreadCrumb component is wrongly positioned in a viewport. It should have the following classes attached: "cx-page-layout cx-page-slot"

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2109

**Comment by WeizhengSap** [comment]
Open SPA page which has breadcrumb in smartedit (e.g. faq page). You should be able to see the breadcrumb exists in the overlay. (You can check the browser's console, there should no "renderService error" for the breadcrumb component).

**Comment by KateChuen** [comment]
The breadcrumb exists in the overlay. No renderService error in the console. But I do see this error: 
"ERROR TypeError: Cannot read property 'properties' of undefined
at PageSlotComponent.push../node_modules/@spartacus/storefront/fesm5/spartacus-storefront.js.PageSlotComponent.addSmartEditContract (spartacus-storefront.js:3205)"
