### ISSUE TITLE
Support for PersonalizationId

### ISSUE THREAD

**Issue by RobertOzgaSap** [SAP/cloud-commerce-spartacus-storefront#1990]
When personalization is enabled in the backend, rest responses will return header `Occ-Personalization-Id`.
Value of this header should be stored and the same header should be added to all future requests to the OCC api in order to enable personalization.

Header name is configurable in the backend and `Occ-Personalization-Id` is a default value. This means that header name in SPA should be configurable as well with proper default value.

- if possible this id should be stored on client side and reused in next sessions

**Comment by WeizhengSap** [comment]
To enable personalization, we need do this:
1. add the following into localextension.xml
```
        <extension name="personalizationcms" />
        <extension name="personalizationcmsbackoffice" />
        <extension name="personalizationcmsweb" />
        <extension name="personalizationfacades" />
        <extension name="personalizationservices" />
        <extension name="personalizationservicesbackoffice" />
        <extension name="personalizationsmartedit" />
        <extension name="personalizationwebservices" />
        <extension name="previewpersonalizationweb" />
        <extension name="personalizationsampledataaddon"/>
```
2. install personalizationsampledataaddon
```
ant addoninstall -Daddonnames="personalizationsampledataaddon" -DaddonStorefront.yacceleratorstorefront="yacceleratorstorefront"
```
3. initialize system
4. in backoffice->personalization->configuration->personalization configuration->select config for "electroncis", and add site "electronics-spa" into it
![Screen Shot 2019-04-25 at 9 19 10 AM](https://user-images.githubusercontent.com/44440575/56740696-6c5ac780-673f-11e9-915b-a3f3088aa4a1.png)
5. go to tab "commerce web services", and set "Personalization for Commerce Web Services" to true
![Screen Shot 2019-04-25 at 9 19 16 AM](https://user-images.githubusercontent.com/44440575/56740740-8694a580-673f-11e9-8874-3d76273bf759.png)
6. in occ calls, you should be able to see "Occ-Personalization-Id" in header.
![Screen Shot 2019-04-25 at 9 22 22 AM](https://user-images.githubusercontent.com/44440575/56740814-a4faa100-673f-11e9-9d37-f7939c86d1b6.png)

**Comment by Xymmer** [comment]
Doc input provided in https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/issues/50
