### ISSUE TITLE
Update documentation on github wiki as part of the release process

### ISSUE THREAD

**Issue by gladius-mtl** [SAP/cloud-commerce-spartacus-storefront#1997]
All documentation that is ready for release is staged on the develop branch of the wiki repo. On release day, develop is merged to the master branch.

Currently this is a manual process, but the reliability of the doc release process would be greatly improved if "merging the develop branch to master in the wiki" was automated 🙂

**Comment by Xymmer** [comment]
unless we're moving to github pages?

**Comment by gladius-mtl** [comment]
Gil asked me to create this ticket... and I think he may have already implemented it -- right after the last release. Perhaps the work he did just wasn't linked to this ticket, in the end. 
I'll check with him.

**Comment by gladius-mtl** [comment]
Update: still to be implemented 🙂

**Comment by hackergil** [comment]
After talking to @gladius-mtl we agreed that it is better if this is done by him. Closing this one.
