### ISSUE TITLE
Reorganise package structure [in progress already?]

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2]
The code base has grown lately and a bit of clean structure is missing. We like to improve this with 2 changes:
1. split up storefront lib in 2 libraries
2. reorganize UI components

**Split up libraries**
Currently the storefront is implemented in two main libraries: storefront and styles. In order to scale better and separate out the framework bits and UI components, we need to separate those out over 2 libraries. Other storefront dev teams (i.e. telco, fsa) can then start building their own UI component lib with a dependency on the core lib only. 

The tasks foreseen for this epic are:
- move out UI components to new library
- rename storefront library (`core` seems to be the right name)

**Reorganize UI components**
TBD

**Comment by Xymmer** [comment]
was done a while ago
