### ISSUE TITLE
Translation keys missing

### ISSUE THREAD

**Issue by hammerbeat** [SAP/cloud-commerce-spartacus-storefront#2002]
After upgrading from alpha.2 to alpha.3/4 I noticed a couple of missing translation keys in Chrome's DevTools Console:

push../node_modules/@spartacus/core/fesm5/spartacus-core.js.I18nextTranslationService.reportMissingKey @ spartacus-core.js:19704

<cx-storefront></cx-storefront>
'common:common.action.skipToShoppingCart'
'common:common.action.skipToMainContent'
'common:common.action.skipToFooter'
'common:common.action.signInRegister'
'common:common.placeholder.searchHere'
'productDetails:productDetails.label.productDetails'
'productDetails:productDetails.label.specification'
'productDetails:productDetails.label.reviews'
'productReview:productReview.label.overallRating'
'productReview:productReview.action.writeReview'
'productDetails:productDetails.label.shipping'
'productDetails:productDetails.label.id'
'productDetails:productDetails.action.showReviews'
'addToCart:addToCart.action.addToCart'
'productDetails:productDetails.label.quantity'
'productDetails:productDetails.action.share'
'productReview:productReview.action.more'

<cx-login-form></cx-login-form>
'login:login.label.emailAddress'
'login:login.placeholder.emailAddress'
'login:login.label.password'
'login:login.placeholder.password'
'login:login.action.forgotPassword'
'login:login.action.signIn'
'login:login.label.dontHaveAccount'
'login:login.action.register'

## Environment Details

- Spartacus:  "@spartacus/core": "^0.1.0-alpha.3", "@spartacus/styles": "^0.1.0-alpha.3", "@spartacus/storefront": "^0.1.0-alpha.4",
- Browser: Chrome Version 73.0.3683.103 (Offizieller Build) (64-Bit)

- package.json dependencies:
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26",
    "@angular/pwa": "^0.13.8",
    "@angular/service-worker": "^7.2.12",
    "@ng-bootstrap/ng-bootstrap": "^4.1.1",
    "@ng-select/ng-select": "^2.16.4",
    "@ngrx/effects": "~7.4.0",
    "@ngrx/router-store": "~7.4.0",
    "@ngrx/store": "~7.4.0",
    "@spartacus/core": "^0.1.0-alpha.3",
    "@spartacus/styles": "^0.1.0-alpha.3",
    "@spartacus/storefront": "^0.1.0-alpha.4",
    "bootstrap": "^4.3.1",
    "i18next": "^15.0.9",
    "i18next-xhr-backend": "^2.0.1",
    "jquery": "^1.9.1",
    "ngrx-store-localstorage": "^7.0.0",
    "popper.js": "^1.14.7"

**Comment by hammerbeat** [comment]
Solution from https://spartacus-storefront.slack.com/team/UD7GV7UP3 

In your app.module.ts please add:
```import { translations } from '@spartacus/storefront';
...
    StorefrontModule.withConfig({
    ...
     i18n: {
        resources: translations,
      },
    }```

**Comment by lindemann18** [comment]
Thanks so much, I was looking how to fix this!
