### ISSUE TITLE
Add category code to PDP page title resolver

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2003]
To have rich page titles in the Search Engine Result Page, we resolve the page title for the PDP by default to this format:

[product title] | [first category title] | [product manufacturer]

Most of this was already in place, but the backend API did not populated the category title. If the category title is missing in the response data, we fallback to the category code.

**Comment by tobi-or-not-tobi** [comment]
QA Steps:
- open PDP
- confirm that the page title contains the (first) category title (can be shown in the browser tab)

**Comment by KateChuen** [comment]
The category title is now displayed.

<img width="980" alt="categoryTitleCamera" src="https://user-images.githubusercontent.com/45409515/56380470-37e78880-61e0-11e9-8f2b-bc156042357a.png">
<img width="1308" alt="categoryTitleDigital" src="https://user-images.githubusercontent.com/45409515/56380471-38801f00-61e0-11e9-8595-365f9851f7a2.png">
<img width="1386" alt="categoryTitleFlash" src="https://user-images.githubusercontent.com/45409515/56380472-38801f00-61e0-11e9-94b4-24cdd1f82ec1.png">
