### ISSUE TITLE
Part 2/2: Move component styles to storefrontstyles lib

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#2013]
Based on the example set by Tobias on GH-1907 we'll now move the following components as well:

- [x] Search Results - Category Listing  / product-view component
- [x] Store Finder / schedule component
- [x] Store Finder / store-finder-grid component
- [x] Store Finder / store-finder-header component
- [x] Store Finder / store-finder-list-item component
- [x] Store Finder / store-finder-map component
- [x] Store Finder / store-finder-search component
- [x] Store Finder / store-finder-list component
- [x] Store Finder / store-finder-search-result component
- [x] Store Finder / store-finder-store-description component
- [x] Store Finder / store-finder-stores-count component
- [x] pwa/components/add-to-home-screen-banner/add-to-home-screen-banner.component.scss
- [x] ui/layout/header/header.component.scss
- [x] ui/components/form-components/item-counter/item-counter.component.scss
- [x] ui/components/form-components/star-rating/star-rating.component.scss
- [x] ui/components/spinner/spinner.component.scss

**Comment by mikelMHybris** [comment]
the header was already done.
