### ISSUE TITLE
Spike adding Coupons functionality

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2026]
Requirements (generally like Accelerator):

On cart page:
- user can add or remove coupons
- when a coupon is successfully applied, display success message inline, display the coupon details info, and update cart summary
- if a coupon doesn't exist, display inline error
- when displaying the cart page, if a coupon has been applied, display the coupon info

On checkout, confirmation page, any order details pages:
- display coupon info if one is applied
- make sure order summary reflects coupon

Certain coupons can be awarded after checkout.
On order confirmation page, add a section "you've been awarded a coupon" like in Accelerator.

See your UX designer and Anthony Reid about wireframes. I don't think we have to stray too far from how it was done in Accelerator, and wires already exist for those.

**Comment by Jerify02** [comment]
For the last requirement 'On order confirmation page, add a section "you've been awarded a coupon" like in Accelerator':
Currently the api is not ready, missing an attribute 'giveAwayCouponCodes' for 'PromotionResultWsDTO'.

**Comment by KevinSu89** [comment]
@Xymmer we have done some research on this topic and it seems the last requirement cannot be implemented. Please see the details in Jerify's comment.

**Comment by KevinSu89** [comment]
The spike is finished and we will start implementation later
