### ISSUE TITLE
Focus lost in added-to-cart dialog after load

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#209]
Bootstrap modal by default moves focus to the first interactive item in a modal.

In our case that is the close button for loading state. After loading completes we replace modal header and focus is completely lost. Keyboard navigation brokes in that moment.

We can also improve focus state for close icon. Focus styles can also be used in `suggested address` modal.

**Comment by wishfulthinkerme** [comment]
Tested on Chrome / Safari / Firefox on OSX. The focus is set on View Cart after loader is gone. Before that `x(close)` is focued.
