### ISSUE TITLE
[retest when 1033 is done] In smartedit, some pages missing some footer nav nodes

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#2108]
In smartedit -> PAGES, you can go to "product details" page, then you will find there are some nav nodes missing from footer.

![Screen Shot 2019-04-23 at 3 26 02 PM](https://user-images.githubusercontent.com/44440575/56612650-e88bc880-65e2-11e9-8ebf-a518addcd6b1.png)

**Comment by WeizhengSap** [comment]
The reason of this is: "POST" changed to "GET" when loading a list of cms components. We have ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1033 to handle it.

**Comment by KateChuen** [comment]
Tested on dev2. Able to see more links now. But still missing some. Wei said it's not smartedit related and the footer now looks exactly like the one in spa. Plus there's already a ticket for the missing links: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2327
<img width="1221" alt="SEfooter" src="https://user-images.githubusercontent.com/45409515/58117911-b8c5e580-7bcd-11e9-8af6-f806bd3a687a.png">
