### ISSUE TITLE
Remove ngBootstrap from Star Rating component

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#2110]
As we progressively work to reduce the project's dependency on Bootstrap, a starting point is to move away from NgBoostrap. This issue is to replace the use of `ngb-rating` from ngBoostrap with a custom implementation.

**Comment by Xymmer** [comment]
How to test? I see that the stars are coming from fonts or icons now

**Comment by tobi-or-not-tobi** [comment]
QA:
- make sure we do not use `ngb-rating` in the DOM in the PLP and PDP (both top of page and review tab)
- make sure functionality works as desired (although icons are different, but that's configurable anyway)
  - star rating is accurate when we visualise colourful stars
  - star rating can be added

**Comment by Xymmer** [comment]
ngb-rating not used, works

**Comment by Xymmer** [comment]
passing
assign to Tobias for doc check
