### ISSUE TITLE
Remove ngbTooltip from payment-form component

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2131]
The payment-form.component.html uses `ngbTooltip` to create the suggested address dialog. This ticket should:

- Remove the use of `ngbTooltip`
- **Keep** the use of `NgbModal`, it will be removed in a subsequent ticket

Don't forget to adjust the unit tests and e2e tests accordingly.

**Comment by Pucek9** [comment]
cart-item.component also uses this directive
