### ISSUE TITLE
Remove ngBootsrap search-box component

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2136]
Search-box component uses `ngbTypeahead` from Ng-bootstrap to open the dropdown when typing. This ticket should:

- Remove the use of `ngbTypeahead`
- Implement custom logic and styling mimicking `ngbTypeahead`
- Not all the feature from the ng-bootstrap components are needed but the Spartacus behaviour should be the same

Don't forget to adjust the unit test and remove the BootstrapModule import from this component's module.

**Comment by tobi-or-not-tobi** [comment]
Based on discussions with UI team, we're changing searchbox configuration in the backend: 
PR: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/49/overview

**Comment by tobi-or-not-tobi** [comment]
QA:

- bootstrap should no longer be used in the html
- the input should be selected when clicking anywhere in the searchbox
- a 50% black overlay should appear over the page when the search box has any results (products, suggestions or messages)
- clicking on the overlay (in case the result panel is shown) should not open any of the under laying links
- the result panel should be hidden when the input is left 
- the result panel should appear again with the former results when the input is selected again
- the input value should be cleared when the reset button is used
- the result panel should be cleared and hidden when the reset button is clicked
- the result panel should show a message when no results are found
- the input value text part of the suggestions should be in plain font type, while the rest should be bold
- when there are no suggestions returned, but there are products being found, the input value should appear as a suggestion (allowing to click on it)
- clicking on a suggestion should open the PLP with the search results
- clicking on a product should open the PDP
- hitting `enter` when the input is focussed, should open the PLP with the search query
- hitting `escape` when the input is focussed, should blur the input (and hide the result panel with that)
- selecting a suggestion should not replace the input value
- the cms searchbox configuration should be taken into account when using the search box . 
  - show / hide products / suggestions
  - search after x-chars are typed
  - display x-number of products
  - display x-number of suggestions
- (default Spartacus backend config) the searchbox behaviour should start searching after the first character is typed
- (default Spartacus backend config) the searchbox behaviour should display max 5 suggestions
- (default Spartacus backend config) the searchbox behaviour should display max 5 products (in desktop)

Mobile:
- clicking on the search icon should open the input field
- clicking on the search icon the 2nd time should hide the input field
- hitting `escape` when the input is shown, should blur the input (and hide the result panel with that)
- products should not be shown in the result, regardless of backend configuration

**Comment by Xymmer** [comment]
QA:

- bootstrap should no longer be used in the html
:heavy_check_mark: verified
- the input should be selected when clicking anywhere in the searchbox
- a 50% black overlay should appear over the page when the search box has any results (products, suggestions or messages)
- clicking on the overlay (in case the result panel is shown) should not open any of the under laying links
- the result panel should be hidden when the input is left 
- the result panel should appear again with the former results when the input is selected again
- the input value should be cleared when the reset button is used
- the result panel should be cleared and hidden when the reset button is clicked
- the result panel should show a message when no results are found
- the input value text part of the suggestions should be in plain font type, while the rest should be bold
- when there are no suggestions returned, but there are products being found, the input value should appear as a suggestion (allowing to click on it)
- clicking on a suggestion should open the PLP with the search results
- clicking on a product should open the PDP
- hitting `enter` when the input is focussed, should open the PLP with the search query
- hitting `escape` when the input is focussed, should blur the input (and hide the result panel with that)
- selecting a suggestion should not replace the input value
- the cms searchbox configuration should be taken into account when using the search box . 
  - show / hide products / suggestions
  - search after x-chars are typed
  - display x-number of products
  - display x-number of suggestions
- (default Spartacus backend config) the searchbox behaviour should start searching after the first character is typed
- (default Spartacus backend config) the searchbox behaviour should display max 5 suggestions
- (default Spartacus backend config) the searchbox behaviour should display max 5 products (in desktop)

Mobile:
- clicking on the search icon should open the input field
- clicking on the search icon the 2nd time should hide the input field
- hitting `escape` when the input is shown, should blur the input (and hide the result panel with that)
- products should not be shown in the result, regardless of backend configuration

**Comment by Xymmer** [comment]
qa steps are doc input, moving to done
