### ISSUE TITLE
Remove ngBootsrap pagination component

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2137]
Pagination component uses `<ngb-pagination>` from Ng-bootstrap. This ticket should:

- Remove the use of `<ngb-pagination>`
- Implement custom logic and styling mimicking `ngb-pagination`
- Not all the feature from the ng-bootstrap components are needed but the Spartacus behaviour should be the same

Don't forget to adjust the unit test and remove the BootstrapModule import from this component's module.

**Comment by giancorderoortiz** [comment]
Observed pagination invalidates faceting selection.
