### ISSUE TITLE
Order Confirmation Message is barely visible

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2138]
**Environment Details**
Spartacus: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/
Browser: Chrome

**Steps to Reproduce**
Go to SPA
Place an order

**Actual Results**
The Order confirmation message is too pale, can barely see it.

![orderConfirmationPale](https://user-images.githubusercontent.com/45409515/56684817-842e3f00-669e-11e9-8869-60bee9c83e4d.png)

**Comment by developpeurweb** [comment]
Fixed in GH-2265
