### ISSUE TITLE
Complete breadcrumb work

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2139]
Final refactor in light of extensibility... Tobias to provide a bit of info

**Comment by tobi-or-not-tobi** [comment]
closed with #2235

**Comment by Xymmer** [comment]
Breadcrumbs look good. E.g. Home > Digital Compacts > Samsung

**Comment by Xymmer** [comment]
assigning to tobias for doc check
