### ISSUE TITLE
Big happy path e2e tests for configurable routes mechanism

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#214]
It's a subtask of #3.

Application should start with custom routes config and then e2e tests should navigate through whole application.

Navigations to cover:
- `routerLink`s in templates
- invocations of `routingService.go()` in TS code

**Comment by Xymmer** [comment]
we can do this ticket when a big portion of configurable routing is done and documented (#213)

**Comment by Platonn** [comment]
Decided not to re-do the big happy path with custom config. But only make e2e test for specific features:
- route aliases
- additional route params
Here is a ticket for it: #776
