### ISSUE TITLE
[master] Review public methods in core and make private where required 

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2140]
As a rule we'd like to expose as many api's as possible. However if we know an api will be refactored, we'd rather not make them public for now.  The task here is to review access levels across classes.

Review and make changes based on the following criteria:
- what is meant to be public, is public
- what is not used outside of the class, make it private (with exceptions)
- evaluate protected methods, make them private if there's no obvious need to extend the method or if the structure of the class isn't of great quality
- consider what we expose in our public api's in our libraries... maybe not export entire classes in our public api e.g. ngrx (but tobias is going to think about that one) --- but if any other whole classes meet this criteria, discuss with tobias
- feel free to be conservative. we can make methods public based on feedback from the community

List taken from: projects/core/public_api.ts

See tickets: https://github.com/SAP/cloud-commerce-spartacus-storefront/labels/public-api

**Comment by WeizhengSap** [comment]
We have this ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2514. So, when you pick up "api review" ticket, you can leave out occ for now.
