### ISSUE TITLE
Move default routes config from core to lib

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2147]
It makes more sense to have the default routes config in the storefront near the routes definition, not in the core library. So we should move this config to the storefront lib. 

Now `default-storefront-routes-config.ts` is provided in `ConfigurableRoutesModule` of core lib.

This default config and providing it should be placed in `PagesModule` of storefront lib.

**Comment by kacperknapik** [comment]
looks good
