### ISSUE TITLE
Regression test April 25 2019 lib release

### ISSUE THREAD

**Issue by kacperknapik** [SAP/cloud-commerce-spartacus-storefront#2150]
- [x] Run all the E2E tests on the nightly branch on jenkins:
Note: Make sure that ALL the tests are being run (about 29 tests).
OR run them from your computer, pointing to dev17 server.

Additionally, do a quick smoke test (equivalent to the big happy path test) on:
- [x] Safari
- [x] Firefox

**Comment by marlass** [comment]
Some e2e tests fail, because of test are not updated. App worked correctly. This should be fixed in #2088 ticket.

**Comment by mirkosoft** [comment]
Tested happy path on safari - works without any issues. Tested on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Comment by mszczepaniak** [comment]
On firefox, compared to chrome, when we go from step 2 shipping method to step 3 payment in checkout, an error appears in the notification area, but it does not stop me from completing the checkout

![image](https://user-images.githubusercontent.com/4272069/56730106-4b05d580-6757-11e9-9d63-f1c6371b1566.png)

![image](https://user-images.githubusercontent.com/4272069/56730125-59ec8800-6757-11e9-8b87-82eed849a8e0.png)

**Comment by marlass** [comment]
Let's ignore it fr now. We will see after extensible checkout if this is still an issue.
