### ISSUE TITLE
safari: Title not set on profile details

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#2153]
![image](https://user-images.githubusercontent.com/788092/56729220-fe20ff80-6754-11e9-89ed-0a1634b35ef2.png)

## Environment Details

- Browser: safari
- OS: OSX
- Device: Macbook

## Steps to Reproduce
Go to my account -> profile details
## Observed Results
title is not set
## Expected Results
title selected in the dropdown
## Additional Information
may be related to #287

**Comment by Xymmer** [comment]
working now
