### ISSUE TITLE
Carousel styling round 2

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#217]
From Miguel (was SAP-979):

The carousel is styled as closer to the mockups as possible, but this will require another round of tickets after the summit in the following areas:

- [ ] Design: we're using a different font type in the carousel titles that is not in the theme (condensed), if we go with this it will have to be implemented at ybase level.
- [ ] Logic: I notice the carousel is not responsive but adaptive, it has to be reloaded in mobile in order to brake down the slides in single products, as opposed to desktop where we have a single slide containing 4 products. According to mockups there should be 2 per slide, but not sure if that is the best solution since we could always have a slide showing up half full, what do we do there?
- [ ] UI-Dev: Adjustments based on whatever gets done in the aforementioned.

**Comment by tobi-or-not-tobi** [comment]
With #853, we're refactoring and restyling the carousel.  The carousel is now response and is reflecting the intended design, although we do not have animation instructions. It is however extendable. 
The font type is a general issue and will be inherited by the carousel once it's fixed.

**Comment by Xymmer** [comment]
ah thanks
