### ISSUE TITLE
three dots should only appear when component is small - right now three dots are always appearing

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2181]
See  https://jira.hybris.com/browse/CMSX-8522

Some info in #845 and #1985 has partially fixed this issue, it seems

how it's looking now
![image](https://user-images.githubusercontent.com/4998145/56833555-c68d8280-683c-11e9-926b-32d88b0efcf5.png)

how it should look:
regular:
![image](https://user-images.githubusercontent.com/4998145/56832902-271bc000-683b-11e9-8a84-2ecc9a44996a.png)
when small:
![image](https://user-images.githubusercontent.com/4998145/56832926-31d65500-683b-11e9-8478-4d1b8eb5e51c.png)

**Comment by stepan-aleksandrov** [comment]
I was able to fix the problem just adding a **display: flex;** styling to the cx-paragraph. Without this css style the browser does not highlight the tag when I hover over it in development mode. So looks like a SPA issue.
