### ISSUE TITLE
Remove * from form fields that are mandatory

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#219]
1. Seen in address form when checking out, but look elsewhere (checkout payment details, checkout payment separate address, registration, ...)

All fields are usually mandatory (so remove the *) but anything that is optional should have "(optional)" next to its label (which seems to be the case).

2. placeholder text should be D3D6DB.

**Comment by RomeroDiver** [comment]
@Xymmer could you please check one more time  - as fas as I can see there are no asterisks for required fields and (optional) is already there

**Comment by Xymmer** [comment]
oops forgot that this is sample data
moving to ux project
we need to update the texts in spacceleratoraddon

**Comment by mikelMHybris** [comment]
@Xymmer I can't find any asterisk in any forms in develop.
