### ISSUE TITLE
List filter texts should be smaller and closer together

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#220]
Filter texts should be much smaller and closer together, so more fit on the screen at once. 
Make sure the filter are still tappable (or as in the case of the applied filters, the X is tappable and thus the filter is removable).

![image](https://user-images.githubusercontent.com/4998145/48080236-3048a000-e1bb-11e8-8ff9-4b9cce34d5b7.png)

**Comment by plabadie** [comment]
The update on the branch GH-220 doesn't seem to meet the requirement in the description:
"Filter texts should be much smaller and closer together, so more fit on the screen at once."

Was there a change of goal for the ticket? Or am I seeing the result I'm supposed to?

Branch GH-220:
<img width="565" alt="GH-220" src="https://user-images.githubusercontent.com/7065346/55032834-25ff3500-4fe8-11e9-82d4-52a9ed60957d.png">

Branch develop:
<img width="604" alt="develop" src="https://user-images.githubusercontent.com/7065346/55032835-25ff3500-4fe8-11e9-8c44-cdc82496b5b8.png">

**Comment by mikelMHybris** [comment]
Based off of the visuals the spacing should be like this.
<img width="772" alt="Screen Shot 2019-03-27 at 9 11 43 AM" src="https://user-images.githubusercontent.com/30266610/55078570-d6b11700-5070-11e9-99c4-7049620c758b.png">
