### ISSUE TITLE
List of Countries not reloaded when language changed during checkout

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2202]
## Environment Details

- Spartacus: develop branch from April 25th
- Browser: Chrome
- Other environment details: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/checkout

## Steps to Reproduce
- Go to SPA
- Change the language to Chinese.
- Add a product to cart
- Login
- Go to cart
- Click on Checkout
- On the first step of checkout, change the language to English.
- In the shipping details, open the drop down menu of "Country".

## Observed Results
- The list is still in Chinese
![listCountriesZHEN](https://user-images.githubusercontent.com/45409515/56899082-932b3d80-6a60-11e9-9c59-55376efeef91.png)

## Expected Results
The list should be in English.

![listCountriesENZH](https://user-images.githubusercontent.com/45409515/56899374-48f68c00-6a61-11e9-80da-c704cbc9d134.png)

**Comment by giancorderoortiz** [comment]
bug fix not yet seen in ccv2 environment. Country selection still in foreign language after language switch back to English.

**Comment by KateChuen** [comment]
Tested on dev17. List of countries is reloaded now in English now.

**Comment by giancorderoortiz** [comment]
I see fix on dev-com17 now as well 🆗
