### ISSUE TITLE
Replace recently hardcoded URLs with configurable ones

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2204]
Need to find and replace those hardcoded urls - i.e. in `CmsPageGuard`:
```
if (pageContext.id !== '/not-found') {
 this.routingService.go(['/not-found']);
}
```

If, needed, add new routes to `default-routing-config`

blocked by #2058

**Comment by dunqan** [comment]
```
    return this.cms.hasPage({
      id: '/logout',
      type: PageType.CONTENT_PAGE,
    });
```
in `logout.guard,ts`

**Comment by Platonn** [comment]
And also
```
{
        path: 'logout',
        canActivate: [LogoutGuard],
        component: PageLayoutComponent,
      },
```

**Comment by Platonn** [comment]
Logout should be made configurable in ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2348

**Comment by Platonn** [comment]
I close it as it's splitted into 2 other tickets #2506 and #2348
