### ISSUE TITLE
Add to Cart Popup doesn't disappear if user clicks on the product title

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2206]
**Environment Details**
- Spartacus: develop branch from April 25th
- Browser: Chrome
- Other environment details: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Go to SPA
- Click on a category, for eg, Film Cameras
- On the product list page, click on "Add to Cart" for one of the items.
- On the popup screen, click on the product title to go to the PDP.
![addToCartModal](https://user-images.githubusercontent.com/45409515/56899931-a3dcb300-6a62-11e9-96fd-7eb36e0c4466.png)

**Observed Results**
The PDP is displayed, but the popup screen didn't disappear.
![addToCartModal2](https://user-images.githubusercontent.com/45409515/56899905-9b847800-6a62-11e9-8a0c-e6742ef70990.png)

**Expected Results**
The popup screen should not be displayed.

**Comment by RadhepS** [comment]
Task was already completed but not placed in the correct location.

**Comment by RadhepS** [comment]
I also fixed clicking on the image so it closes the modal as well.

**Comment by RadhepS** [comment]
PR: GH-2465
