### ISSUE TITLE
Change some of the labels to title case

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#221]
From SPA-1199 - was in code review with an open PR, so there must be a branch somewhere.

Cart total, shipping method in desktop/mobile, edit link in mobile
Basically always use Title Case unless we absolutely have a good reason for all caps, and even then let's think about differentiating some other way, like bold or bigger.

![image](https://user-images.githubusercontent.com/4998145/48081595-69ceda80-e1be-11e8-8737-fe3be624f21b.png)

Marcin wrote: While working on this task I found that we have some dead code in styles. Might be worth to investigate that.
Also pls check if the design matches our vision.

**Comment by plabadie** [comment]
Smoke test ok.

<img width="378" alt="Screen Shot 2019-03-26 at 4 45 22 PM" src="https://user-images.githubusercontent.com/7065346/55032142-99a04280-4fe6-11e9-85be-5671bab92b90.png">
