### ISSUE TITLE
Configurable icons in product view component

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#2213]
In order to offer more configurations with regards to styling the icons are now configurable see #348. This ticket also brought about the use of `Font Awesome` icons.

This ticket is to :

- Replace the lines (hamburger) and boxes that toggle in the product view button on the PLP
- Use `GRID_MODE` and `LIST_MODE` from `ICON_TYPES` from icon.config.ts
- `mini-cart.components.html` and .ts can be used as an inspiration
- The button should still work in the same way and the icons should still toggle

Don't forget to include `IconModule` in the ProductListModule imports.

**Comment by Xymmer** [comment]
Tested by substituting other icons for grid and list
There is another ticket to swap out grid/list as you should show grid when there’s a list, and viceversa

**Comment by Xymmer** [comment]
Assigning to Louis to see if there’s docs to do
