### ISSUE TITLE
Configurable info icon

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#2214]
In order to offer more configurations with regards to styling the icons are now configurable see #348. This ticket also brought about the use of `Font Awesome` icons.

This ticket is to replace the information icon (i in a circle). These are the steps:

- Replace all the use of this icon with a customizable one
- In `icon.config.ts` add a key `INFO = 'info-circle'`
- `mini-cart.components.html` and .ts can be used as an inspiration

Don't forget to include `IconModule` in the imports of the modules where the component is used.

**Comment by LTiger14** [comment]
QA Steps:

1. Go to the add payment method form
2. You should see an 'i' icon next to the CVV field
3. Stop the application
4. Add this in the Storefrontmodule configs in `app.module.ts` (Import ICON_TYPES from spartacus/storefront)
```
      icon: {
        icons: {
          [ICON_TYPES.INFO]: 'cat',
        },
      },
```
5. Start the app `yarn start`
6. Go back to the add payment method form, you should see a cat icon

**Comment by Xymmer** [comment]
Verified

**Comment by Xymmer** [comment]
Assigning back to Louis for doc check
