### ISSUE TITLE
Toggle button code might be obsolete, Keep or Remove before Beta Release

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#2215]
This code is not being used at the moment, nor before the Beta release. Most likely this button will not be worked on but until the A11Y process is in motion.
The resulting button currently doesn't receive any focus and can't be toggled with the keyboard.
Button will have to be refactored at a later time in this ticket: GH-2216

**Risk:** Even though it's not implement anywhere in HTML or TS files, it exist in the CSS file and contributors may find it and use it even if it's unfinished. 

![image001](https://user-images.githubusercontent.com/15113219/56914769-f3cb7200-6a82-11e9-9d0c-a3116868061f.png)

**Comment by LTiger14** [comment]
In my opinion if it's not in use or going to be used in the foreseeable future I would remove it. Just make sure to keep a backup 😉

**Comment by developpeurweb** [comment]
We'll proceed with removal as @tobi-or-not-tobi mentioned in Slack he's **for removing as well**.
