### ISSUE TITLE
Configurable icons in Product facet navigation component

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#2218]
In order to offer more configurations with regards to styling the icons are now configurable see #348. This ticket also brought about the use of `Font Awesome` icons.

This ticket is to replace the "plus" and "minus" "icons" that toggle when you collapse and expend facets. These are the steps:

- Replace the "plus" and "minus" "icons"
- In `icon.config.ts` add a keys `PLUS = 'plus'` and `MINUS = 'minus'`
- `mini-cart.components.html` and .ts can be used as an inspiration
- The toggle of the icons should remain the same. Use ts for this.
- The component behaviour should not change

Don't forget to include `IconModule` in the imports of `product-list.modules` if it isn't already there.

**Comment by Xymmer** [comment]
verified by checked if fonts are used for these 2 icons, they are, closing
