### ISSUE TITLE
Outlets refactor in PDP [after tabs redo / AddtoCart change]

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2219]
We've already put outlets in pdp but these should be reviewed and update before release, as we're stuck with them until 2.0 at least.

We can do listings later because we're adding not changing anything.

**Comment by Xymmer** [comment]
we need GH-2267 and GH-2264
tabs redo / AddtoCart cms change

**Comment by LTiger14** [comment]
PR #2683

**Comment by LTiger14** [comment]
### QA Steps

1. Stop whatever server you are testing this on with `./spartacus.sh stop`
2. In `app.component.html` add 
```
<ng-template cxOutletRef="PDP.DESCRIPTION">
  <p>Test</p>
</ng-template>
```
3. In app.module.ts add `OutletRefModule` in the imports
```
import {
  [...]
  OutletRefModule
} from '@spartacus/storefront';
[...]
imports: [
 [...],
 OutletRefModule
]
```
4. Restart server with `./spartacus.sh start`
5. Go to any product's PDP page. The description should be only "Test"
6. Stop server, remove the changes and restart it

**Comment by KateChuen** [comment]
Tested on dev2. 
After the changes, the product description is now "Test"
![productDescriptionTest](https://user-images.githubusercontent.com/45409515/58904703-09613680-86d6-11e9-989a-9213dfdc554f.png)

Before the changes:
![productStarsPdp](https://user-images.githubusercontent.com/45409515/58904712-0f571780-86d6-11e9-8b2e-5e6f5286303c.png)
