### ISSUE TITLE
[? Doesn't look the same] Configurable credit card logo icon

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#2222]
In order to offer more configurations with regards to styling the icons are now configurable see #348. This ticket also brought about the use of `Font Awesome` icons.

This ticket is to replace the `visa` and `mastercard` icons that are visible when payment methods already exists (only Visa and MC). These are the steps for the ticket:

- In `icon.config.ts` add a keys `VISA = 'cc-visa'` and `MASTER_CARD = 'cc-mastercard'`
- Modify `payment-method.component.ts` and ``payment-method.component.html` to use the new icons
- Delete `visa.ts` and `masterCard.ts`
- Ask around if we should add icons for the other default payment methods

Don't forget to include `IconModule` in the imports of `PaymentMethodModule`.

**Comment by tobi-or-not-tobi** [comment]
Will be possible after #2472 is implemented

**Comment by mikelMHybris** [comment]
I talked with Bill and Anthony about adding more card icons. Anthony was ok with the default visa and master card, but referred me to Bill who had the final say. 
So we are using the logos that are in fontawesome for the cards that we have. For the cards that are not part of fontawesome we will use the generic card icon.

**Comment by KateChuen** [comment]
Tested on dev17. Now there are different logo icon for the credit cards:

- visa has his own visa logo
![visa](https://user-images.githubusercontent.com/45409515/58348813-aba83100-7e2f-11e9-8b0b-b756c1a28772.png)
- mastercard & mastercard/eurocard has the mastercard logo
![mastercard](https://user-images.githubusercontent.com/45409515/58348827-b2cf3f00-7e2f-11e9-9185-3833f3249c48.png)
![mastercardeurocard](https://user-images.githubusercontent.com/45409515/58348828-b2cf3f00-7e2f-11e9-92ac-c4db7e41ea7c.png)
- diner's club has his own logo
![diners](https://user-images.githubusercontent.com/45409515/58348839-b82c8980-7e2f-11e9-8943-a8b1ad466efb.png)
- other cards (maestro, switch) have the default credit card logo
![maestro](https://user-images.githubusercontent.com/45409515/58348850-bebb0100-7e2f-11e9-833b-ea42b2b342f8.png)
![switch](https://user-images.githubusercontent.com/45409515/58348851-bebb0100-7e2f-11e9-902a-b701822fb8e8.png)
