### ISSUE TITLE
Integrate GitHub dependabot

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#2231]
Site: https://greenkeeper.io/
Bot: https://github.com/apps/greenkeeper

GreenKeeper bot checks for newer versions of dependencies in `package.json` files, create a new branch and runs the pipeline with the updated version; it also automatically creates a PR to update them.
Here it is in action: https://github.com/johnpapa/vscode-peacock/pull/139

**Comment by marlass** [comment]
There is new integrated bot into github (dependabot). Public beta is available. Might be worth checking ;)

**Comment by marlass** [comment]
I like the idea of bot updating dependencies. We would avoid massive dependency updates and keep always up to date. Would love to see it in our repo.

**Comment by znikola** [comment]
Yup, I saw it. We could play with both and see what suits us better :)
