### ISSUE TITLE
Merge banner and responsive banner components

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2232]
While the CMS separates the banner and responsive banner, this feels a bit old-fashion. UI should be responsive by default, and even if this is not the case it should be controlled in CSS, not by changing backend models.

**Comment by tobi-or-not-tobi** [comment]
closed as part of #2234

**Comment by Xymmer** [comment]
@tobi-or-not-tobi : to test, we just make sure all banners are displaying properly?

**Comment by tobi-or-not-tobi** [comment]
QA:
- verify whether the simple banner component and responsive banner components work as expected

**Comment by Xymmer** [comment]
They are working as expected, both using CX-media
Assigning to Tobias for doc check
