### ISSUE TITLE
reuse cx-picture in banner components

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2233]
The `cx-picture` component is used for product images, but the functionality should be reused in banners, to benefit from responsive images.

**Comment by Xymmer** [comment]
How to test? I inspect banners and see cx-banner, then CX-media, but no CX-picture

**Comment by tobi-or-not-tobi** [comment]
FYI cx-picture was renamed to cx-media. 

QA steps:
- validate that all product and banner related images are rendered with the `cx-media` component
- validate that all images work as expected

**Comment by Xymmer** [comment]
verified

**Comment by Xymmer** [comment]
assigning to tobias for doc check
