### ISSUE TITLE
Breadcrumb feature: title is too big

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2235]
## Environment Details

- Spartacus:  all pages of SPArtacus default design
Description:  All page titles site wide are being displayed in 36 point type. They should be displayed in 22 point type.

## Steps to Reproduce
View any desktop page with a breadcrumb

![SNAG-0002](https://user-images.githubusercontent.com/44620139/56981121-0cec2580-6b4c-11e9-97ef-65e2b82ffe1f.png)

**Comment by tobi-or-not-tobi** [comment]
closed with #2235

**Comment by Xymmer** [comment]
I can’t tell if it’s any smaller, but a bigger issue is that the product title repeats. Maybe i don’t have the fix yet? This is listed as closed and i have latest develop

**Comment by tobi-or-not-tobi** [comment]
We're using `rem` rather them 'px', but how you could test it:
- select the H1 in Chrome dev tools
- add a style rule to the H1: `font-size: 36pt` (the original size according to @vekterdude)
- toggle the style, and see that it's smaller now
- additional, change the style rule into: `font-size: 22pt` . And validate that the new rem size is equal to `22pt`. 

Alternatively, create a screen dumb and ask @vekterdude whether the size is OK. 

I've verified on my local, and it's implemented as intended.

**Comment by Xymmer** [comment]
using dev17 tues may 7, seeing this
![image](https://user-images.githubusercontent.com/4998145/57319822-7d0a2680-70cb-11e9-9a5d-703caff30f4d.png)

**Comment by Xymmer** [comment]
doesn't look fixed but will try again tomorrow, maybe server needs updating

**Comment by Xymmer** [comment]
breadcrumb font size fixed
