### ISSUE TITLE
[PR submission] Footer items red for no reason

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2237]
Description:  Many items in the site footer appear in red text. According to the visuals provided the text color should be white.

How to duplicate: View any site footer

![SNAG-0004](https://user-images.githubusercontent.com/44620139/56981662-73be0e80-6b4d-11e9-950d-9672faf770c1.png)

**Comment by Xymmer** [comment]
should be white, looks like we have a pr

**Comment by developpeurweb** [comment]
No longer an issue, got fixed in #2792

**Comment by KateChuen** [comment]
Tested on dev2. They are white now. But they are "hyperlinks" as in underlined. Is that what we want?
![footerWhiteLinks](https://user-images.githubusercontent.com/45409515/58904474-9788ed00-86d5-11e9-92a1-8ea90be63844.png)

**Comment by Xymmer** [comment]
nope no lines unless we point at them

**Comment by KateChuen** [comment]
Tested on dev19. Footer items look ok now. 
<img width="1440" alt="Screen Shot 2019-06-13 at 3 13 26 PM" src="https://user-images.githubusercontent.com/45409515/59460814-ef1e0b80-8ded-11e9-8ad2-d0e0397ef814.png">
