### ISSUE TITLE
Homepage banner is too wide

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2238]
## Environment Details

Description:  The main banner on the top of the homepage is currently taking the full project width. It is supposed to max out at the project content width as per visuals.

## Steps to Reproduce
Visit homepage

This image demonstrates the problem. The banners (most of them) are too wide because of the width of the slots in the homepage. The main menu items at the top of the page are the correct project width:

![image-1](https://user-images.githubusercontent.com/44620139/57159783-cc431500-6db4-11e9-8f3c-027c451d3349.png)

This view represents the preferred and agreed upon width and resolution to this issue:

![Web 1920 – HOME – temp](https://user-images.githubusercontent.com/44620139/57160587-2c3abb00-6db7-11e9-97e2-6c8c412386ab.png)

**Comment by Xymmer** [comment]
we'll make sure this is done by beta but removing high priority

**Comment by tobi-or-not-tobi** [comment]
@vekterdude FYI – we've taken https://app.zeplin.io/project/5a836f2897c4a02f0105b093/screen/5a836fee948d985d0c1ff69e as an input for the setup of the landing page.

**Comment by Xymmer** [comment]
checking with anthony

**Comment by vekterdude** [comment]
> @vekterdude FYI – we've taken https://app.zeplin.io/project/5a836f2897c4a02f0105b093/screen/5a836fee948d985d0c1ff69e as an input for the setup of the landing page.

Yes @tobi-or-not-tobi that's exactly the example we are trying to follow! FYI: Manu is the better informed (of us) on this issue. He know the history better.

**Comment by KateChuen** [comment]
Tested on dev2. Homepage banner's width has been fixed. 

<img width="1437" alt="Screen Shot 2019-06-20 at 2 10 36 PM" src="https://user-images.githubusercontent.com/45409515/59871323-4cbdd500-9365-11e9-86b8-20ade1fb3903.png">
