### ISSUE TITLE
[done with 2135] 2 types of ‘caret’ (dropdown arrow) icon on the homepage

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2239]
Description:  In the desktop view there are 2 types of dropdown arrow viewable: one as a solid triangle and one as a chevron. There should only be chevron style dropdown icons product-wide.

How to duplicate: Visit desktop homepage

![SNAG-0007](https://user-images.githubusercontent.com/44620139/56982297-fbf0e380-6b4e-11e9-9971-bdc214eaf8e0.png)

**Comment by tobi-or-not-tobi** [comment]
This should be done as part of the configurable-icons effort. @LTiger14 do we have 2 tickets for site context and navigation?

**Comment by LTiger14** [comment]
@tobi-or-not-tobi The site-context selectors were done already by you but I don't have a ticket for the navigation arrows. But I can create a ticket to replace the navigation carets with the site context ones.

**Comment by tobi-or-not-tobi** [comment]
I forgot...
Perhaps better to hang it all up on the ng-bootstrap related ticket.

**Comment by tobi-or-not-tobi** [comment]
Test this as part of #2135

**Comment by KateChuen** [comment]
Tested on dev2. Now there's only 1 type of arrow on the homepage.
<img width="1433" alt="homepageArroe" src="https://user-images.githubusercontent.com/45409515/58968129-81d20100-8783-11e9-971b-a9f3d32b7953.png">
