### ISSUE TITLE
Problems on the localization drop downs

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2240]
Description:  
 - There is not enough padding on the list options of the localization drop downs (language and currency) in desktop 
- The font Color is too light
 - The background is not pure white 
- The highlight color is blue background, not a red text change

How to duplicate: Open the persistent language dropdown in the upper header

![SNAG-0007](https://user-images.githubusercontent.com/44620139/56982573-a1a45280-6b4f-11e9-98e3-6d386f88437b.png)

**Comment by tobi-or-not-tobi** [comment]
This has been screencapt from a pretty old env. Please ask @Xymmer for an up-to-date env.

**Comment by Xymmer** [comment]
this has been fixed
