### ISSUE TITLE
Product names are not fully left justified in the list view

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2246]
Description:  All Product names are not fully left justified in the list view. They are slightly short of being aligned with the rest of the product content below

How to duplicate: Visit any catalog page – list view or grid view. See how the product name is inset from the rest of the product information...

![SNAG-0010](https://user-images.githubusercontent.com/44620139/56984318-bd115c80-6b53-11e9-92a8-304f386c3e24.png)

**Comment by WTPar** [comment]
I can not reproduce this, does this issue still exist?

![Screen Shot 2019-05-29 at 10 04 29](https://user-images.githubusercontent.com/51126454/58540305-68680c80-81f9-11e9-911c-951cc4eb74d7.png)

**Comment by Xymmer** [comment]
fixed
