### ISSUE TITLE
Filter by tags/chips are too big and are occupying a single line

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2247]
Description:  Filter by tags/chips in the catalog pages, which appear when a facet is selected, are too big and are occupying a single line. The font size is also too big. This feature should follow the visual guidelines.

How to duplicate: Visit any catalog page – list view or grid view. Select random facets and watch the tags appear under the “Filter by” title.

![SNAG-0017](https://user-images.githubusercontent.com/44620139/56984447-095c9c80-6b54-11e9-9dc4-b457eca45842.png)

**Comment by KateChuen** [comment]
Tested on dev17.
- The filter facets before:
![facetFilterBefore](https://user-images.githubusercontent.com/45409515/58729375-40bea300-83b7-11e9-82b5-afd93431613a.png)

- The filter facets now (the font size is smaller, previously 16, now 14. And they are not each on a single line)
![facetFilterNow](https://user-images.githubusercontent.com/45409515/58729366-3dc3b280-83b7-11e9-8e21-e4dc0ea47b55.png)
