### ISSUE TITLE
The Star icons on the PDP are too small

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2249]
Description:  The Star icons on the PDP are too small. Use the visuals provided to establish the correct size.

How to duplicate: Visit any product detail page and examine the review star icons.

<img width="398" alt="Screen Shot 2019-04-12 at 11 17 28 AM" src="https://user-images.githubusercontent.com/44620139/56990852-2dc07500-6b64-11e9-9927-4c3466b5737e.png">

![SNAG-0018](https://user-images.githubusercontent.com/44620139/56990907-59435f80-6b64-11e9-8a21-e2d11b0c7b15.png)

**Comment by tobi-or-not-tobi** [comment]
closed with #2273

**Comment by Xymmer** [comment]
Stars are bigger

**Comment by Xymmer** [comment]
Should we document how to configure this, or is it part of config icons work?
