### ISSUE TITLE
Product title and details position update

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2250]
Description:  Product name is 4 pt. sizes too big. It is currently 36 pt and should be 32 pt as per the visuals.

How to duplicate: View any Product Detail page.

![SNAG-0018](https://user-images.githubusercontent.com/44620139/56992082-441c0000-6b67-11e9-8fde-f74bfc9e616f.png)

**Comment by Xymmer** [comment]
it's weird that the header and the product page titles are big and the same and it's a waste of spacein mobile. Let's save some space by making product title same size as product ID and putting them in 1 row.

**Comment by mikelMHybris** [comment]
@Xymmer same size and one line in mobile only? The id size is pretty small. @vekterdude any input?

**Comment by mikelMHybris** [comment]
@vekterdude I'm seeing 29px for the product name on my local. What server are using?

**Comment by vekterdude** [comment]
We were using the one on the Github homepage. Bill later supplied us with a "gold standard" instance for us to report bugs, which we will use moving forward.

**Comment by Xymmer** [comment]
For 1.0, we're going to go with this:

![image](https://user-images.githubusercontent.com/4998145/58637998-c2340980-82c1-11e9-8ed7-d4a0660f537a.png)

**Comment by Xymmer** [comment]
maybe adjust the spacing to taste between review stars, id #, price
also make stars a bit smaller

**Comment by KateChuen** [comment]
Spacing between Review Stars, ID, and price wider now.
Review stars smaller.
![productStarsPdp](https://user-images.githubusercontent.com/45409515/58901134-91434280-86ce-11e9-8013-3bc472a62a65.png)
