### ISSUE TITLE
Problems with the review portion of the PDP

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2251]
Description: 
‘Show reviews’ should be underlined since it is a link.
‘Write Review’ link is missing.

How to duplicate: View any Product Detail page.

<img width="398" alt="Screen Shot 2019-04-12 at 11 17 28 AM" src="https://user-images.githubusercontent.com/44620139/56992329-c73d5600-6b67-11e9-80e3-c29ce8697db8.png">

**Comment by Xymmer** [comment]
we don't underline everything
write a review was removed on purpose
closing
