### ISSUE TITLE
'<#> in Stock' should be displayed in green if adequate stock

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2252]
Description:  ‘On the PDP, the number of in stock items should be displayed in green if there is adequate stock to cover the quantity and red if there is not. Currently the user may not enter a quantity higher than the available stock number.

How to duplicate: Go to PDP and enter a quantity greater that the available in stock.

![Screen Shot 2019-04-30 at 4 54 01 PM](https://user-images.githubusercontent.com/44620139/56992694-a1648100-6b68-11e9-929b-cd6281f8fe68.png)

**Comment by bgambocjaviniar** [comment]
I don't know if this is relevant, but when the user goes over the min/max, the input goes to the min/max. This is a feature that was created somewhere in January by someone before. 

Therefore, not needing to put the stock in red if it goes over. Maybe if you want to keep this feature, have the stocks be green?

**Comment by Xymmer** [comment]
won't fix, it's fine for now
