### ISSUE TITLE
Find a Store homepage require appropriately sized banner

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2255]
Description:  There is a banner slot on the Find a Store default page which is currently filled with a banner of inappropriate dimensions 

How to duplicate: Navigate to the Find a Store home page

**Comment by Xymmer** [comment]
seeing this right now

![image](https://user-images.githubusercontent.com/4998145/58567814-10350880-8201-11e9-8c38-30b1c5f647f9.png)

**Comment by Xymmer** [comment]
We won't display a banner in our sample store, but we have to fix this slot so it displays banner properly.
