### ISSUE TITLE
All Stores list dos not have adequate sample data

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2256]
Description:  The All Stores list view is broken down by countries, however our sample data only shows one country – japan. We are not showing off the capabilities developed and we cannot review the layout with only one data point for the page. We require a minimum of 4 countries with some data to properly assess the page functionality.

How to duplicate: Go to the Store finder and click on ‘All Stores’ option

**Comment by Xymmer** [comment]
we'll be updating sample data in the future but this is a slightly bigger task that will have to wait until after 1.0

**Comment by Xymmer** [comment]
closing as whatever we add to sample data will be what is done with storefinder effort
