### ISSUE TITLE
Fix padding and alignment in storefinder map list

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2257]
In storefinder map list (go to the Store finder and choose “use my location” view results):
- Text should be left-justified
- Padding should decreased

Note: Radhep previously did a pr for this.

<img src=https://user-images.githubusercontent.com/4998145/62537273-02fa5280-b81e-11e9-90f4-25992c4d9584.png width=400 />

**Comment by RadhepS** [comment]
PR: GH-2586
