### ISSUE TITLE
CMS text: Breadcrumb title in ‘register’ should be “Create an Account”

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2258]
Update June 13: Looks like the dupe line in register page was removed but the backend data wasn't updated. See comments below. Moving back to to do.
----
Description:  On the Create an Account page, the page is titled “Register page” and it should be titled: “Create an Account.” Create an Account should be removed from the body content area of the page and there should be less padding space between the breadcrumb and the first form content.

How to duplicate: Visit Create and account page by clicking on the register link in the header.

![SNAG-0014](https://user-images.githubusercontent.com/44620139/56993620-f1444780-6b6a-11e9-9cdb-003d500f2a44.png)

**Comment by tobi-or-not-tobi** [comment]
This is CMS driven and can be amended without changes in Spartacus. Still good to update our sample data though.

**Comment by marlass** [comment]
PR available here: https://stash.hybris.com/projects/C3PO/repos/spartacussampledataaddon/pull-requests/6/overview

**Comment by mszczepaniak** [comment]
After discussion with @Xymmer we have decided to remove the header, since after the sample data change it is duplicated with the breadcrumb (both display 'Create an account')

**Comment by WeizhengSap** [comment]
Please note that this spartacussampledataaddon is moved to github.

**Comment by KateChuen** [comment]
Tested on dev19. The header is removed now.
But the breadcrumb title says "Register". Should it say "Create an Account"?

<img width="1292" alt="Screen Shot 2019-06-13 at 1 39 00 PM" src="https://user-images.githubusercontent.com/45409515/59454783-d6f3bf80-8de0-11e9-9ee3-1dcea7df7b12.png">

**Comment by Xymmer** [comment]
Yeah register should be 'create an accout'. 
It has to be changed in spartacussampledata however
