### ISSUE TITLE
baseUrl config not loaded from meta tag when there's no config specified at all

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2261]
Since #1211 we are able to load the baseUrl for OCC from the `index.html`. However, when the application config is not provided at all in the StorefrontModule, the meta tag is not being read.

**Comment by Platonn** [comment]
QA steps:
- in the `storefrontapp/index.html` set the `content` of  `<meta name="occ-backend-base-url" content="...">` tag to some baseUrl
- verify in the console that OCC calls are made to the base url given in the `index.html`

- in the `app.module` replace `StorefrontModule.withConfig({...})` with simply `StorefrontModule` (don't worry that many features won't be configured then)
- verify in the console that OCC calls are made to the base url given in the `index.html`
