### ISSUE TITLE
Redo tab component using static configuration

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2264]

**Comment by LTiger14** [comment]
QA Steps:

1. Go to Backoffice > WCMS > Component Container > TabPanelContainer (for Spa electronics catalog)
2. Reorder the tabs so `deliveryTab` is first and press save
3. Go to spa (in another tab) and any PDP page (refresh if already there) the `Shipping` tab should be first
4. Go back to Backoffice and delete the `Product Details Tab` and click save
5. Go back to spa and refresh, the details tab should be gone
6. Go back to Backoffice, add the `Product Details Tab` and make `deliveryTab` last. Click save.
7. Go back to spa, refresh, the tabs should be back to normal

8. (Usability) Make sure the tabs behave like they use to

**Comment by KateChuen** [comment]
Tested on dev2.
- Changing the order of the tabs works.
![orderTabs](https://user-images.githubusercontent.com/45409515/58424505-87359a00-8065-11e9-9bf0-fd617fd0911c.png)

- Removing one tab works.
![removeTab](https://user-images.githubusercontent.com/45409515/58424509-8a308a80-8065-11e9-93c6-ccef4cc70fe1.png)

- Adding back the tab & re-arranging the order works. 
![normalTabs](https://user-images.githubusercontent.com/45409515/58424665-ea273100-8065-11e9-95de-227868ce7701.png)
