### ISSUE TITLE
Replace hard-coded Addtocart with cms component in PDP

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2267]

**Comment by LTiger14** [comment]
QA Steps:

Confirm that add to cart on PDP and product listing still works as before. 
- Try for various quantities
- Different products
- Also product with no stock should no show the add to cart, try for NV10 (553637)

**Comment by KateChuen** [comment]
Tested on dev17.
- Added product to cart from pdp and plp
- Added different quantities (max, min, >max, 0, +, -, remove)
- Out of stock products don't have "add to cart" option on both pdp and plp.
