### ISSUE TITLE
Add loading indicator in the UI when navigating from page to page

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2276]
Now that we seamlessly load components when we navigate from page to page, we need a loading indicator to help the user understand we're navigating.

We do not have a design spec, so we'll implement an ordinary loading bar, fixed to the top.

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- confirm during navigation of pages that we have a load bar on the top of the page
- the load bar should be sticky and always visible, in case the user scrolls down

**Comment by Xymmer** [comment]
Works, a bit subtle to see though
