### ISSUE TITLE
drop 404 in global message handler

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2282]
404 on pages are handled by rendering the not found page. Having both the not-found page and the global message is ambiguous. 
This is especially annoying during logout, where the not-found page is only rendered if available. Otherwise, the experience should silently navigate to the landing page.

**Comment by tobi-or-not-tobi** [comment]
This depends on CMSX-8516, which is ready in 1905

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- test whether an unknown page will show the not-found content, but doesn't display an error in the GlobalMessage panel (aka alert box)

**Comment by Xymmer** [comment]
passing, not found page doesn't show 404 global message
