### ISSUE TITLE
close-account text should be cms driven

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2284]
The close-account page is CMS driven, but the text itself is driven by i18n. We should move the retention text to a CMS paragraph component. 

The `CMSParagraphComponent` in the CMS can be localized by default.

I recommend adding a flex component to the close account page for the functionality (holding a small form with cancel and submit button).
With that change, route config and outlet can be dropped and still, everything is configurable and extendible.
Customer can then freely add more images, text, etc on the cms page or move this component to another page

**Comment by hackergil** [comment]
[Backend PR](https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/48/diff)
