### ISSUE TITLE
Notification preference

### ISSUE THREAD

**Issue by KevinSu89** [SAP/cloud-commerce-spartacus-storefront#2285]
As a customer, I want enable/disable the notification, so that I can receive the notification via my preferred channel(s)

- Create a new page called "Notification Channels" under "My account"
- Show the list of all the available channels and show a switch for each channel
- Be able to enable/disable a channel by clicking the switch
-- After click a switch of a channel, disable all the checkbox until getting the response from server, then update the page accordingly
- Anonymous user will be redirected to register/login page when he/she try to enter the "Notification Channels"
- By default, don't show "Site_Message" channel
- Please refer to the mock-up about the UI design

*NFR*
- This feature should be configurable

**Comment by Qingyu-Yang** [comment]
PR:
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2103

**Comment by KevinSu89** [comment]
The related jira item: https://jira.hybris.com/browse/PANDA-3072
