### ISSUE TITLE
Allow for first route parameter containing slash

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2293]
Angular implicitly splits segments given in the first passed-in value of `routerLink`'s array when it contains slashes. This causes a bug when the first configured route parameter contains value with slashes (i.e. product name `Camera Lenses f/1.8`).

**Comment by Platonn** [comment]
QA steps:
- in `app.module` change configured path for product page to contain `:name` as first param:
```
    routing: {
        routes: {
          product: {
            paths: [':name/product/:productCode'],
```
- go to the list of camera lenses:
![obraz](https://user-images.githubusercontent.com/4001059/57293388-dde23080-70c4-11e9-8d5c-f502779bf3fa.png)
- click the name of the product containing slash:
![obraz](https://user-images.githubusercontent.com/4001059/57293429-036f3a00-70c5-11e9-9740-e49bea3cb5e9.png)
- verify that you are in PDP page of this product

**Comment by tobi-or-not-tobi** [comment]
Works!
