### ISSUE TITLE
Personalization: Previous calculation timestamp

### ISSUE THREAD

**Issue by wgancarz** [SAP/cloud-commerce-spartacus-storefront#2316]
In #1990 we asked you to add the support for `Occ-Personalization-Id` header. We tested it - it works perfectly. Thank you for your help.

Unfortunately, during testing we found out that this header does not solve all of our problems.
We would also need to send the timestamp representing the last time the content was calculated for a user. The timestamp should be returned with each request - identically to the first header.

The new header's default name is `Occ-Personalization-Time`. We would like it to be configurable, just like `Occ-Personalization-Id`.

**Comment by WeizhengSap** [comment]
check https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1990 for how to enable personalization.

**Comment by WeizhengSap** [comment]
To make it work, we need personalization module version > RC4.

Note: the timestamp isn’t sent all the time.

If you send occ-personalization-id for the first time, this should trigger the personalization calculation asynchronously. Then, once it’s finished, your next request with the right occ-personalization-id will return the timestamp.

**Comment by Xymmer** [comment]
Doc input provided in https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/issues/50
