### ISSUE TITLE
Improve the ProductGuard Logic and its unit tests

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#232]
Investigation required.

We have a pattern in the ProductGuard that looks roughly like this:

```
Is data present in store?
  if yes, great!  Return it.
  if no, try to load the data in the store and wait for the result 
    if now the data is successfully loaded, great! Return it.
    if the data can't be loaded, react accordingly.
```
Right now, the issues we suspect our code to have are:
- It is more complex than it should.
- The code is hard to understand, debug and evolve.
- It's difficult to write unit tests for this piece of code.
- We are not sure if we can get in intfinite loop situations ( Looping on: "if we don't find it, try to load it" )
- We are not sure if we should deal with concurrency and the 'loading' state of the data we are looking up.
- We are not sure which part or the store calls are synchronous and which are asynchronous.
- The logic to handle retries should probably not be inside the route guard, Addis unnecessary complexity.

The goal of ticket is to improve the code according to the above criteria.  We need simple, reliable and testable code in the route guard's logic.

Below here is the code that needs improvements.  The code is directly in the route guard at the moment of writing this description, but the code will soon be moved to a facade service.  The problem will remain and the logic in the facade services should be improved/fixed.  To find the code just look which facade service function is called from the guard's canActivate function.

The checkStore function in the ProductGuard
```
   private checkStore(requestedProductCode: string): Observable<boolean> {
    let tryTimes = 0;
    return this.store.pipe(
      select(fromStore.getSelectedProductFactory(requestedProductCode)),
      map(product => {
        if (product) {
          return Object.keys(product).length !== 0;
        } else {
          return false;
        }
      }),
      tap(found => {
        if (!found) {
          tryTimes++;
          this.store.dispatch(new fromStore.LoadProduct(requestedProductCode));
        }
      }),
      filter(found => found || tryTimes === 3),
      take(1)
    );
  }

```

**Comment by plabadie** [comment]
A while ago, we discussed the guidelines for the store usage.

One thing that the team then decided is that it is not the purpose of the store to handle caching.

With that in mind, I think that pieces of logic that need to load data from the backend into the store should just do so, without adding complexity to the process.

This would simplify the route guard loading logic above.

Like it was suggested bu other devs,  we could implement loading state flags where it makes sense and pieced of code who want to react to it accordingly could.

**Comment by Xymmer** [comment]
possibly overlaps with #289

**Comment by Xymmer** [comment]
moving to future unless we think we need it sooner

**Comment by Platonn** [comment]
ProductGuard was removed, so I close the ticket
