### ISSUE TITLE
CMSLinkComponent should delegate to generic-link component

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2327]
The `cx-link` component currently only support internal (router) links. We should leverage the `cx-generic-link` so external links are supported. Additionally we should pass in the `styleAttributes` of the CMSLinkComponent.

**Comment by WeizhengSap** [comment]
`styleAttributes` is exposed. But, it is empty for almost all cms links in our sample data. I added some test value to it in backoffice. In the occ response, I can see it.
![Screen Shot 2019-05-21 at 10 03 47 AM](https://user-images.githubusercontent.com/44440575/58102829-f287f380-7baf-11e9-9a90-58217dbd1bf8.png)
