### ISSUE TITLE
Infinite loop when configured media base url is not responding

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2330]
Noticed during QA of #2212

**Comment by tobi-or-not-tobi** [comment]
to QA:
- configure media url to alternative url
- verify that the not found image is shown
- verify that we do not have infinite loops in the console

**Comment by KateChuen** [comment]
Tested on dev2. 
Added the meta tag in index.html. Then tested with an invalid media url in app.module.ts
![mediaMetaTag](https://user-images.githubusercontent.com/45409515/58196583-9baa1900-7c98-11e9-944d-d1f1c33893dd.png)
![invalidMediaUrlAppModule](https://user-images.githubusercontent.com/45409515/58196600-a4025400-7c98-11e9-8398-c77f25f4416b.png)

- Verified that the Not Found image is displayed 
![invalidMediaUrl1](https://user-images.githubusercontent.com/45409515/58196686-dd3ac400-7c98-11e9-8a49-fbc2707c6e96.png)
![invalidMediaUrl2](https://user-images.githubusercontent.com/45409515/58196687-dd3ac400-7c98-11e9-91ac-4f23fa4886ab.png)
![invalidMediaUrl3](https://user-images.githubusercontent.com/45409515/58196688-ddd35a80-7c98-11e9-9aed-9d6f152f988d.png)

- Verified that there's no infinite loops in the console. The errors are printed when the storefront was loading. After done loading, cleared the console, and no more errors generated. 
![consoleLoading](https://user-images.githubusercontent.com/45409515/58196724-ef1c6700-7c98-11e9-9d8e-f15ebaf030d0.png)
![consoleLoaded](https://user-images.githubusercontent.com/45409515/58196723-ef1c6700-7c98-11e9-9ad5-3bc4338bf713.png)


- Tested with valid media url, and verified the storefront is displayed correctly with the images.
