### ISSUE TITLE
Fix jumpy footer somehow

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2336]
When you are on a page, likely you don't see the footer if you have a laptop.
Click a link, footer jumps to the top as the body is deleted.
Then it goes back down.

I can think of 2 ideas:
1- preferred- display footer last (even though it's not changing, hide it along witht he rest of the page and display it last. almost always, the footer is below anyway)
2- i've seen other sites always set footer to the very bottom of the page, it works a bit better

anyway suggestions welcome, talk to tobias

**Comment by kacperknapik** [comment]
to test this:
- login
- open address book
- open order history
- keep switching between them, to see if the footer is jumpy

footer should now be at the bottom of the screen

**Comment by mirkosoft** [comment]
Tested, footer is not jumping.
