### ISSUE TITLE
[doesn't block release] SmartEdit (CMSX-8866)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2361]
https://jira.hybris.com/browse/CMSX-8866

Steps:
clone a homepage into a new variation page
Add time restriction starting in the future

Result: I land on a primary homepage
From the Pages view, I select to preview my variation page, I land on a primary homepage too.

Expected: I should land on a created page, even if restriction is not current. I should also land on selected page from a page list.

**Comment by WeizhengSap** [comment]
It works on my local. I can see the newly cloned page landed.
![Screen Shot 2019-05-09 at 4 29 32 PM](https://user-images.githubusercontent.com/44440575/57484679-acf62d00-7277-11e9-82ee-a5954db10e8a.png)

**Comment by WeizhengSap** [comment]
It doesn't work if time restriction starts in future. Which preview page loaded is decided by smartedit.
