### ISSUE TITLE
Radhep onboard

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2387]
### Setting up Development Environment

**Backend**
1. Install Java using [SapMachine](https://sap.github.io/SapMachine/)
2. Follow guidelines found on the [hybris wiki](https://wiki.hybris.com/pages/viewpage.action?spaceKey=acc&title=B2B+Accelerator+Environment+Setup+with+yenv) to set up your Backend Environment
      - Use the 'b2c_cms' template instead of 'b2b'
3. Run the backend by using command: yenv debug folderName
    - folderName should be replaced by the name of the folder you created

**Frontend**
1. Clone the [Spartacus repository](https://github.com/SAP/cloud-commerce-spartacus-storefront)
2. Install dependancies by using the command: yarn install
3. Launch the Storefront by using the command: yarn start

**Other**

[Wireframes Access](https://98qkkl.axshare.com/prototype/login/98qkkl#g=1&p=d_homepage)
[Spartacus installation and configuration documentation](https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Installing-Spartacus)

### Ramping up

**Spartacus** 

Review all Spartacus documentation which can be found in the [Spartacus Wiki](https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki)

**Angular**

Written:
- [Tour of Heroes by Angular.io](https://angular.io/tutorial)
- [Learn Angular 7 by Example by Gary Simon](https://coursetro.com/posts/code/171/Angular-7-Tutorial---Learn-Angular-7-by-Example)
- [The RxJS library by Angular.io](https://angular.io/guide/rx-library)
- [Official NgRx Store Guide by NgRx.io](https://ngrx.io/guide/store)
- [Angular Ngrx Store Tutorial - Learn Angular State Management by Gary Simon](https://coursetro.com/posts/code/151/Angular-Ngrx-Store-Tutorial---Learn-Angular-State-Management)

Video:
- [Angular Crash Course - 2019 by Traversy Media ](https://www.youtube.com/watch?v=Fdf5aTYRW0E)
- [Learn Angular 7 in 50 Minutes - A Free Beginner's Crash Course by Design Course](https://www.youtube.com/watch?v=5wtnKulcquA)
- [Learn RxJS in 60 Minutes for Beginners - Free Crash Course by DesignCourse](https://www.youtube.com/watch?v=PhggNGsSQyg)
- [Ngrx Store Tutorial for Angular - Learn State Management for Angular by DesignCourse](https://www.youtube.com/watch?v=9P5DTlg9oLc)

**Comment by RadhepS** [comment]
Task 1:

I was assigned a bug fix referring to the issue #2206. I corrected the bug but it was ultimately not merged due to it already being completed by someone else. The person who completed the task did not follow our protocol so we were unaware that it was completed.

**Comment by RadhepS** [comment]
Task 2:

Assigned the task to follow the [build process ](https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Building-the-Spartacus-Storefront-from-Libraries)indicated on the Wiki to ensure that it works properly. 
Tested and completed, it works as expected.
