### ISSUE TITLE
Global message icons, 'x' button and text are not aligned properly

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#2388]
On the attached images, the closing 'x' button and text are not aligned with the icon.

![Screen Shot 2019-05-09 at 14 45 54](https://user-images.githubusercontent.com/11561723/57479592-bf6a6980-726b-11e9-8f24-7fd6f09d6457.png)
![Screen Shot 2019-05-09 at 14 47 10](https://user-images.githubusercontent.com/11561723/57479593-bf6a6980-726b-11e9-9a6f-bd34d6fb60e1.png)
![Screen Shot 2019-05-09 at 14 52 01](https://user-images.githubusercontent.com/11561723/57479594-bf6a6980-726b-11e9-8760-9f9d25dbc6e2.png)

**Comment by developpeurweb** [comment]
@mikelMHybris @znikola be advised in order to tackle this one, we need GH-2220 and GH-2221 to be merged

**Comment by Xymmer** [comment]
success message looks good

bad credentials looks off still
![image](https://user-images.githubusercontent.com/4998145/58209777-b8a11500-7cb5-11e9-97d2-b53c68520f4c.png)

**Comment by Xymmer** [comment]
putting back into progress for last qa step and comment on bad credentials position. actually up close even the green checkbox looks a little low, but i'm being picky :)

**Comment by developpeurweb** [comment]
This is now fixed, the approach was change to using flexbox and automatically center elements vertically

**Comment by KateChuen** [comment]
Looks ok now. Tested on dev2.
![errorMsg](https://user-images.githubusercontent.com/45409515/58898750-4115b180-86c9-11e9-91d2-5d08ac0cc58b.png)
![successfulMsg](https://user-images.githubusercontent.com/45409515/58898751-4115b180-86c9-11e9-8859-bde2ab11588c.png)
