### ISSUE TITLE
For login user, refresh address-book page get 'You are not authorized to perform this action' error

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#2390]
As a login user, I refresh the address-book page in my-account, I can see the "You are not authorized to perform this action" error.

Same with payment management page.

![Screen Shot 2019-05-09 at 7 14 48 PM](https://user-images.githubusercontent.com/44440575/57492472-eede9d80-728e-11e9-8322-df62136d97fb.png)

**Comment by Zeyber** [comment]
Fixed by #2512

**Comment by giancorderoortiz** [comment]
I see a bug fix in ccv2 environment. 
Able to refresh/interact with address book page and payment details page. 🆗
