### ISSUE TITLE
Refactor closeAccount i18n to fit with current config structure

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#2394]
As it this functionality was added in the meantime of i18n refactor it should be refactored as well. So it is just about moving `projects/storefrontlib/src/translations/en/close-account.en.ts` to `myAccount` chunk and update it's usage in the view.

**Comment by Platonn** [comment]
See https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2284

**Comment by mirkosoft** [comment]
@Zeyber @Platonn @tobi-or-not-tobi can we get rid of that static translation from myAccount chunk? Asking as #2284 is already closed.

**Comment by Zeyber** [comment]
> @Zeyber @Platonn @tobi-or-not-tobi can we get rid of that static translation from myAccount chunk? Asking as #2284 is already closed.

I suppose its not necessary to keep the line now it is coming from cms. I recall that I put it there initially as cms was not returning the text so it was done as a temp fix for presentation purposes

**Comment by tobi-or-not-tobi** [comment]
I'm a bit far off of this topic, please align with @Platonn for this topic.

**Comment by Zeyber** [comment]
Reopening to remove no longer necessary translation

**Comment by Zeyber** [comment]
Close account is not fully cms driven and still requires translations
