### ISSUE TITLE
References to `.scss` files in `_index.scss` files are causing issues

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2398]
This is at least spotted with the latest library on stackblitz, but might not ben an issue with the node-sass parser.

**Comment by tobi-or-not-tobi** [comment]
Issue reported at Stackblitz: https://github.com/stackblitz/core/issues/966

**Comment by Xymmer** [comment]
it's building now, does this need test?
