### ISSUE TITLE
stackblitz doesn't seem to support postcss

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2400]
We've not been contributing a lot of cross-browser css fixes since we're using PostCSS to fill in those fixes automatically. 
Stackblitz doesn't seen to support PostCSS in the build.
The new star rating requires an important PostCSS fix, so we add it for demo purposes on stackblitz.

**Comment by Xymmer** [comment]
@marlass: is this done, can we move to done?
