### ISSUE TITLE
Blank page when following installation instructions for spa shell app

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#2406]
**Needs reproduction**

Using the guidelines from https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Building-the-Spartacus-Storefront-from-Libraries I created a new Spartacus based storefront.

I also attempted to use the `app.module.ts` from our spa install repo with the same result.

This storefront loads up without an error but when opening the site, the page is blank. The network calls to get pages are successful but the cms components don't seem to render. (see screenshots)

![Screen Shot 2019-05-10 at 11 33 10 AM](https://user-images.githubusercontent.com/10605724/57539015-8e477300-7317-11e9-97ef-258c5e4b1d24.png)
![Screen Shot 2019-05-10 at 11 33 30 AM](https://user-images.githubusercontent.com/10605724/57539022-90a9cd00-7317-11e9-8134-69c70f9ab0d3.png)

Browsers: Firefox & Chrome (latest)
Lib versions: (latest)
-     "@spartacus/core": "~0.1.0-alpha.5",
-     "@spartacus/storefront": "~0.1.0-alpha.7",
-     "@spartacus/styles": "~0.1.0-alpha.7"

**Comment by cinthiadavalos** [comment]
Hi @hackergil ! I fixed this issue adding:
`@angular/http@~7.2.11`

 and updating these dependencies:
`@ngrx/effects@~7.4.0
@ngrx/router-store@~7.4.0
@ngrx/store@~7.4.0 
@angular/pwa@^0.13.7
rxjs@^6.4.0 `

**Comment by hackergil** [comment]
@cinthiadavalos Yup I just found out this morning. A few more to update as well. Thanks!
