### ISSUE TITLE
api review - cart

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2410]
See GH-2140 for master plan.

**Comment by WeizhengSap** [comment]
I reviewed `cart` module in core lib; and `cms-components/checkout/cart` in storefrontlib. There are some `private` functions in components. I am not sure whether we can change them to `protected` if users extend the components.

**Comment by WeizhengSap** [comment]
In this ticket, we will not review occ module. We have a ticket to do it: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2514
