### ISSUE TITLE
[No changes - Please double check] api review - window

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2426]
See GH-2140 for master plan.

**Comment by LTiger14** [comment]
I took a look and made no changes. The reviewer could check if he would make a change and reply to this comment.

**Comment by kacperknapik** [comment]
> I took a look and made no changes. The reviewer could check if he would make a change and reply to this comment.

Since it's just a few browser methods, I would say it's fine to leave it as is 👍
