### ISSUE TITLE
Remove hard-coded routes

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2428]
Drop hard-coded routes in SPA that can are driven by content page labels.

**Remove hard-coded routes**
- address-book
- update-password
- update-email
- payment-details
- update-profile
- forgot-password
- reset-password

**Add AuthGuard**
- address-book component
- update-password component
- update-email component
- payment-method component
- update-profile
- forgot-password
- reset-password

Remove semantic routes for pages that are only driven by CMS.
Update sample data for pages that have not yet the `/my-account/` prefix in the label

**Comment by tobi-or-not-tobi** [comment]
PR for sampledata is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/46/overview

**Comment by tobi-or-not-tobi** [comment]
e2e is most likely blocked till we install new sample data.

**Comment by Xymmer** [comment]
tested all pages with /my-account/ 
when logged in:
- address-book (/)
- update-password
- update-email
- payment-details
- update-profile
- forgot-password > oops (correct)
- reset-password > oops (correct)

there's the 'not authorized to perform this action' for payment details, known issue.
