### ISSUE TITLE
Warnings in core build

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#2441]
New warnings came up in core build. They are about `side effects`.
Please inspect and try to fix those warnings.
Command to check ~`yarn build:core:lib`~ `ng build core`.

**Comment by Pucek9** [comment]
Problem occurred between `core-0.1.0-alpha.4` and `core-0.1.0-alpha.5`.
I suspected dependencies, but after verification it's not the reason.

**Comment by Pucek9** [comment]
here the problem begins https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2333/files

**Comment by Pucek9** [comment]
```
Dropping unreachable code [0:xxxxx,xx]
Declarations in unreachable code! [0:xxxxx,xx]
``` 
started after merge https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2207/files

**Comment by marlass** [comment]
Warning no longer appears in core build.
