### ISSUE TITLE
Register e2e test

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#2443]
We changed behavior for registration on the same email address.
- [x] Test checking for already creating an account can be changed to check if login is performed. 
- [x] Additionally, another test can be created to check if providing the wrong password with email (already registered) causes the error message.

**Comment by marlass** [comment]
The test is unstable. Often after clearing local storage store sync to local storage again. This causes second test to fail.

**Comment by giancorderoortiz** [comment]
I see the verification for attempting to create a user with same email fails, which is correct. 🆗 
Waiting for fix of this same test in https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2829 ℹ️

**Comment by giancorderoortiz** [comment]
The tests pass. However, I have reservations regarding automatic login when re-using an already used email address and password. And also, the handling when using an already used email address and wrong password.  Further discussion is needed.
