### ISSUE TITLE
incorrect peer dependencies when building fresh

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2451]
warning " > @angular/service-worker@7.2.15" has incorrect peer dependency "@angular/core@7.2.15".
warning " > @angular/service-worker@7.2.15" has incorrect peer dependency "@angular/common@7.2.15".
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning " > @spartacus/core@0.1.0-alpha.5" has incorrect peer dependency "@angular/common@~7.2.11".
warning " > @spartacus/core@0.1.0-alpha.5" has incorrect peer dependency "@angular/core@~7.2.11".
warning " > @spartacus/storefront@0.1.0-alpha.7" has incorrect peer dependency "@angular/animations@~7.2.11".
warning " > @spartacus/storefront@0.1.0-alpha.7" has incorrect peer dependency "@angular/common@~7.2.11".
warning " > @spartacus/storefront@0.1.0-alpha.7" has incorrect peer dependency "@angular/compiler@~7.2.11".
warning " > @spartacus/storefront@0.1.0-alpha.7" has incorrect peer dependency "@angular/core@~7.2.11".
warning " > @spartacus/storefront@0.1.0-alpha.7" has incorrect peer dependency "@angular/forms@~7.2.11".
warning " > @spartacus/storefront@0.1.0-alpha.7" has unmet peer dependency "@angular/http@~7.2.11".
warning " > @spartacus/storefront@0.1.0-alpha.7" has incorrect peer dependency "@angular/platform-browser@~7.2.11".
warning " > @spartacus/storefront@0.1.0-alpha.7" has incorrect peer dependency "@angular/platform-browser-dynamic@~7.2.11".
warning " > @spartacus/storefront@0.1.0-alpha.7" has incorrect peer dependency "@angular/router@~7.2.11".

**Comment by tobi-or-not-tobi** [comment]
No longer valid.
