### ISSUE TITLE
The product list item UI not matching the wireframes

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#2455]
The product price value should be below the star component. I think this happened due to refactoring of some stylings

![Screen Shot 2019-05-13 at 2 25 36 PM](https://user-images.githubusercontent.com/29099466/57645328-061dd380-758c-11e9-84a5-0d2ea6e4bd7a.png)

**Comment by RadhepS** [comment]
PR: GH-2458

**Comment by bgambocjaviniar** [comment]
Should the modal close on PDP page?
