### ISSUE TITLE
Console error after logout

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#2460]
After sign out we call request ``
GET https://dev-com-17.accdemo.b2c.ydev.hybris.com:9002/rest/v2/electronics-spa/cms/pages?fields=DEFAULT&pageType=ContentPage&pageLabelOrId=/logout&lang=en&curr=USD 404
`` and get response:
```json
{
   "errors" : [ {
      "message" : "No content page found matching the provided label or id: /logout",
      "type" : "CMSItemNotFoundError"
   } ]
}
```
In LogoutGuard there is:
```ts
return this.cms
      .hasPage({
        id: '/logout',
        type: PageType.CONTENT_PAGE,
      })
```

**Comment by Pucek9** [comment]
@tobi-or-not-tobi Please verify are changes necessary here

**Comment by tobi-or-not-tobi** [comment]
This actually works as expected, see https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1514. We'd like to get a list of "semantic" pages from the CMS in the future, once this feature is available, we know upfront whether there's a logout page or not.

**Comment by Pucek9** [comment]
Great, thank you. Lets close that.
