### ISSUE TITLE
Update Beauty store to use the latest libraries

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#2466]
### Please notify Bill once it's done

The beauty store is a store that uses the Spartacus libraries as a showcase. It's source code is in stash under team C3PO > Beautacus. (ask me if link is needed)

This ticket is to update the libraries used by the store and make sure it still works.

**Comment by RadhepS** [comment]
Updated and built Beautacus. It works as intended.

**Step 1:** 
Download source code from the stash in C3PO > Beautacus.
**Step 2:**
Follow steps in the [Adding Peer Dependencies to the Storefront](https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Building-the-Spartacus-Storefront-from-Libraries#adding-peer-dependencies-to-the-storefront) found on the Wiki.
**Step 3 (Optional):** 
In the event the store displays a blank screen, please update `@angular/http` to version `"@angular/http": "~7.2.11"`. A reference to this issues can be found [here.](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2406)

I have pushed my changes for Louis to review.

**Comment by RadhepS** [comment]
Updated and built Beautacus. 
**Step 1:** 
Download source code from the stash in C3PO > Beautacus.
**Step 2:**
Follow steps in the [Adding Peer Dependencies to the Storefront](https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Building-the-Spartacus-Storefront-from-Libraries#adding-peer-dependencies-to-the-storefront) found on the Wiki.
**Step 3 (Optional):** 
In the event the store displays a blank screen, please update `@angular/http` to version `"@angular/http": "~7.2.11"`. A reference to this issues can be found [here.](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2406)

I have pushed my changes for Louis to review.

**Comment by RadhepS** [comment]
There is an issue with the API endpoints for this application.
Louis said he will look into it.

**Comment by Xymmer** [comment]
In order to test we need backend Beauty sample data updated.
So after GH-2551 (by Wei) we can try the update Beauty storefront with it.

**Comment by Xymmer** [comment]
Update to the tasks in this ticket:

*Finish Beautacus / beautystore extension*
1. Wei updates beautystore extension sample data (GH-2551).
2. Test Beautacus (Spartacus-based app) against beautystore extension sample data (need to install beautacus in a local). Maybe Wei can test? this is beautacus stash: https://stash.hybris.com/projects/C3PO/repos/beautacus/browse

*Update scc staging*
1. Create release/19.05 from release/19.04 in here: 
https://enterprise-stash.hybris.com/projects/E2E/repos/e2e_staging/browse?at=release/19.04
2. Update beautacus in e2e_staging/js-storefront with our Spartacus-based Beauty storefront
3. Update beautystore in e2e_staging/core-customize with Wei's updated beautystore
4. Update spacceleratorsamplesaddon in e2e_staging/core-customize with latest spacceleratorsamplesaddon
5. Update manifest.json to include spacceleratorsamplesaddon (ask Gil for help) - need to the add to the extensions list and an entry in "storefrontAddons" for it (beauty is already there).
