### ISSUE TITLE
Support mixture of icon formats

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2472]
The configurable icons are currently based on a single configuration for the technical icon format. This is insufficient for our icons and more flexibility is required. This ticket brings a flexible solution that allows to mix SVG and font based icons in one storefront as well as different font libraries for the icons.

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- confirm both `fas` (i.e. search icon) and `fab` (i.e. visa icon) based icon formats are used in the storefront
- change configuration in development (see documentation) to support multiple font formats

**Comment by Xymmer** [comment]
- couldn't confirm multiple font formats, need a dev to do it.

- confirmed that fas (i.e. search icon) is used

- can't confirm visa yet, so this ticket can wait in qa for this release if that's all that's left.
