### ISSUE TITLE
Upgrade to Angular 8

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2482]

**Comment by SerkanSipahi** [comment]
Hi, do you guys also moving to NgRx v8 (simplified actions, reducers, @ngrx/data apdapter)?

**Comment by znikola** [comment]
Hi @SerkanSipahi,
You can track the ngrx8 upgrade progress in #2813

**Comment by Platonn** [comment]
Updated the installation script, see PR: https://stash.hybris.com/projects/C3PO/repos/spartacus-installation/pull-requests/25/overview
