### ISSUE TITLE
Fix SOP issue

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2486]
https://wiki.hybris.com/display/spar/Spartacus+SOP+Payment+Handling

**Comment by WeizhengSap** [comment]
Our current implementation is, SPA sends a POST request to the "/sop/response" endpoint if there is no error in the response from payment provider. So, if there is an error, no request will be sent.

From this: 
https://help.sap.com/viewer/9d346683b0084da2938be8a285c0c27a/1811/en-US/8c261cad866910149bcad3d2c5be5f37.html?q=payment
SPA can just send to OCC the response data got from payment provider, no matter the subscription created successfully or not.

**Comment by WeizhengSap** [comment]
To QA/code reviewer: 
In checkout step "Payment", create a new payment. When enter credit card info, you can enter some invalid data. You should be able to see the error message which is returned from occ.

**Comment by hackergil** [comment]
Looks good Wei. Can you create a ticket to follow up on displaying a better error message to the user? Thanks.

**Comment by WeizhengSap** [comment]
@hackergil : the error message is got from backend. We can create a backend ticket.

**Comment by WeizhengSap** [comment]
The new PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2532

Please do a full test.

**Comment by Xymmer** [comment]
new pr fixes the issue Mikel reported: GH-2529

**Comment by plabadie** [comment]
QA:  looks good!

I can see the error error message for an error in the credit card number:


<img width="1677" alt="Screen Shot 2019-05-21 at 1 31 36 PM" src="https://user-images.githubusercontent.com/7065346/58121390-55d84c80-7bd5-11e9-864a-8b9780934fcb.png">
