### ISSUE TITLE
Remove userId arguments in Checkout Facade.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2498]
See master ticket GH-1092

Remove the userId argument from these functions. Use the user id `current`instead inside the facade functions.

```
loadCheckoutDetails(userId: string, cartId: string)
```

Internally, get the userId from the CartDataService singleton.

We also need to refactor the components that use these functions and write down smoke test instructions for which feature we know we should look closer into for regression.

**Comment by plabadie** [comment]
PR #2624

**Comment by plabadie** [comment]
For tests, this feature is used in the guards that prevents the user from skipping ahead in the checkout process.

When starting checkout, you should not be able to skip ahead to the next steps:
http://localhost:4200/electronics-spa/en/USD/checkout/delivery-mode
http://localhost:4200/electronics-spa/en/USD/checkout/payment-details
http://localhost:4200/electronics-spa/en/USD/checkout/review-order

**Comment by KateChuen** [comment]
- Verified that from the UI, we cannot skip checkout steps.
- Tested going to specific checkout steps through url
-> The first time we go through the steps in the UI, if we try to skip steps by going to the url, it will redirect the user to the current step he was on. For eg, if I'm on the Step1/Shipping Address step, and I try to go to: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/checkout/review-order, it will redirect the user back to Step1 -> OK

-> However, if we go through each steps on the UI (except actually placing the order), then we go back to Step1/Shipping Address
-> -> On the UI, we still cannot skip step.
-> -> But we can skip directly to any step using the urls (so it takes all the previous selections). So I can go directly to the last step for eg, by going to: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/checkout/review-order
