### ISSUE TITLE
Create framework and component re-org tickets

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#250]
For framework and component re-org, Tobias said that the solution is known and we just need to create tickets. Would like to have some this week as we could refine them and assign to a team.

**Comment by tobi-or-not-tobi** [comment]
Instructions: 
We move the ngrx related stuff to the core module, to simplify the use of the component library and unit tests. Components will only interact with the facade layer (which is part of the core as well). 

The things we like to change during this move

Introduce core folder:
- Introduce a feature folder in the core library, i.e. `src/product` (singular)
- move the occ related services from the global occ folder to the feature folder in core: `[feature]/occ`

Move occ
- expose the occ services in an occ module: `[feature]/occ/[feature]-occ.module.ts`
- move ngrx store folder to the folder: `[feature]/store`

Move/refactor ngrx
- expose the store in a module: `[feature]/store/[feaure]-store.module.ts`
- move the facade folder to the core: `[feature]/facade`
- (refactor) move state out of the different ngrx files, to `[feature]/store/state.ts`
- (refactor) move selectors out from the reducers (if not done already) and move them to a `[feature]/store/selectors` folder

Other
- (optional) introduce config folder holding config interface (feature-config.ts) and default data (default-config.ts)
- move models inside `[feature]/model` folder (if needed)
- keep guards inside the UI component lib (storefrontlib)

Public API:
- expose all modules, services and config 
- expose only the ngrx state, actions and selectors in the public API (not the reducers and effects)

**Comment by Xymmer** [comment]
Moving this to Done, looks like all tickets created. Gladiators will take these tickets. We'll wait for Tobias and Stan to finish their one each. See https://github.com/orgs/SAP/projects/9?card_filter_query=label%3Aepic%2Flibreorg

**Comment by Xymmer** [comment]
This ticket now depends on #151 to be finished as it contains move to core.
