### ISSUE TITLE
Replace hardcoded pageLabels in logic with semantic urls from config

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2506]
In few places we have hardcoded `pageLabel`s / `pageContext.id`s of CMS routes:
- logout guard - `'/logout'`
- cms page guard - `'/not-found'`
- router reducer - `'/login'`, `'/login/register'`

We need to get them from the routes configuration.

Now we have only a method `UrlService.generateUrl()` returns an array of url commands to be passed to Angular's `routerLink` or `router.navigate`. This is not what we simply need here. We just need string with a page label for given named route.

To build a full bullet-proof solution we need considering:
- passing parameters
- URI-encoding segments of url
- supporting aliases
- supporting relative links

Or we can simply build a method that returns just a string from configuration (with leading slash).

**Comment by Platonn** [comment]
Things hardcoded in router serializer ('/login', '/login/register') should be handled in different ticket #2541

**Comment by KateChuen** [comment]
Can you add QA Steps please? Thanks :)

**Comment by giancorderoortiz** [comment]
Waiting for QA Steps.

**Comment by Platonn** [comment]
### Logout is configurable
- in app.module configure the logout route:
```
routing: {
  routes: {
    logout: { paths: ['my-logout'] }
  }
}
```
- login in the application
- type in the navigaiton bar `/my-logout`
- verify that you are logged out

### 'Page not found' route is configurable
- in app.module configure notFound route:
```
routing: {
  routes: {
    notFound: { paths: ['my-404'] }
  }
}
```
- in the backoffice change the page label `/not-found` to `/my-404`
- type in the navigaiton bar `/my-404`
- verify you see the 'Not found' page

**Comment by KateChuen** [comment]
Tested on dev2. 
- Configuring the logout route works. Going to /my-logout logs me out now and redirects me to the homepage (before I would stay logged in and get a not-found page)
- Configuring the notFound route works. Going to /my-404 displays the "NotFound" page. 
![404NotFoundRoute](https://user-images.githubusercontent.com/45409515/58905450-c3a56d80-86d7-11e9-8aee-abfab94153d0.png)
