### ISSUE TITLE
Repair CSS in suggested-addresses-dialog.component (verify your address)

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#2508]
After go to checkout -> add new address -> fill all fields with 'review' text.
![image](https://user-images.githubusercontent.com/8040837/57848846-1f1bc400-77da-11e9-8513-915b9e5e6989.png)

There was also missed translation (common.editAddress) but it has been solved in https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2504

**Comment by Xymmer** [comment]
verified
