### ISSUE TITLE
Remove userId arguments in User Facade - Update Password

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2509]
See master ticker GH-1092

Remove the userId argument from these functions. Use the user id `current`instead inside the facade functions.

* updatePassword( userId: string, oldPassword: string, newPassword: string ): void {

We also need to refactor the components that use these functions and write down smoke test instructions for which feature we know we should look closer into for regression.

**Comment by plabadie** [comment]
PR #2629

**Comment by plabadie** [comment]
For tests:

Make regression tests on the update password functionality.
Also, validate that the userId in the occ calls used do not contain the user email, but the 'current' string instead.

**Comment by KateChuen** [comment]
Tested on dev17.
- Update password now uses "current". 
<img width="1437" alt="currentUpdPwd" src="https://user-images.githubusercontent.com/45409515/58486987-df879d00-8134-11e9-9d20-b0cb00bd092a.png">

- Update password still works as before. (Update password, Cancel, Save, Wrong original password, mismatch new passwords, back button, logout, can login with new password)
