### ISSUE TITLE
Remove userId arguments in User Facade - Order History  functions

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2510]
See master ticker GH-1092
Remove the userId argument from these functions. Use the user id `current`instead inside the facade functions.
* loadOrderDetails(userId: string, orderCode: string): void {
* getOrderHistoryList( userId: string, pageSize: number ): Observable<OrderHistoryList> {
* loadOrderList( userId: string, pageSize: number, currentPage?: number, sort?: string ): void {

We also need to refactor the components that use these functions and write down smoke test instructions for which feature we know we should look closer into for regression.

**Comment by bgambocjaviniar** [comment]
PR: GH-2713

**Comment by bgambocjaviniar** [comment]
Test:

Make so there's no trace of userId in
loadOrderDetails(userId: string, orderCode: string): void {
getOrderHistoryList( userId: string, pageSize: number ): Observable {
loadOrderList( userId: string, pageSize: number, currentPage?: number, sort?: string ): void {
Make sure order history is still functional as it was before

**Comment by KateChuen** [comment]
Tested on Dev2.
- Verified that Order History is using "current" now for both getting all orders, and one specific order.
<img width="1436" alt="currentAllOrders" src="https://user-images.githubusercontent.com/45409515/58505310-a82be700-815a-11e9-8875-753e1a58e5e6.png">
<img width="1436" alt="currentAnOrder" src="https://user-images.githubusercontent.com/45409515/58505312-a8c47d80-815a-11e9-8b0f-1a0ac3913770.png">


- Verified that Order History works like before (can sort by date or order number, select an order).
