### ISSUE TITLE
Remove userId arguments in User Facade - Payment functions

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2511]
See master ticker GH-1092
Remove the userId argument from these functions. Use the user id `current`instead inside the facade functions.

* loadPaymentMethods(userId: string): void {
* setPaymentMethodAsDefault(userId: string, paymentMethodId: string): void {
* deletePaymentMethod(userId: string, paymentMethodId: string): void {

We also need to refactor the components that use these functions and write down smoke test instructions for which feature we know we should look closer into for regression.

**Comment by plabadie** [comment]
PR #2717

**Comment by plabadie** [comment]
For tests:

Regression test on displaying saved payment methods during checkout.

Regression test on displaying saved payment methods in the my account section, as well as setting one as default and deleting one.

All the occ requests driving the above features need to use the username "current" in their url instead of the email.

**Comment by KateChuen** [comment]
Tested on dev2.
- Verified that "current" is now used.

Add new payment during checkout
<img width="1437" alt="currentAddNewPayment" src="https://user-images.githubusercontent.com/45409515/58574416-ecc48a80-820d-11e9-8c40-f38a047444c6.png">


Select different payment during checkout
<img width="1422" alt="currentSelectPayment" src="https://user-images.githubusercontent.com/45409515/58574404-e46c4f80-820d-11e9-9be4-6f942f4bd695.png">

Load payment
<img width="1435" alt="currentGetPayment" src="https://user-images.githubusercontent.com/45409515/58574424-f2ba6b80-820d-11e9-9ef6-7372d07cce10.png">

Set default
<img width="1437" alt="currentSetDefaultPayment" src="https://user-images.githubusercontent.com/45409515/58574434-f6e68900-820d-11e9-838e-da1d3845cd4d.png">

Delete payment
<img width="1440" alt="currentDeletePayment" src="https://user-images.githubusercontent.com/45409515/58574444-fa7a1000-820d-11e9-9894-8d11e9e07041.png">

- Tested that payment works as before (get, add, set default, delete, select different payment at checkout, checkout, logout, login).
- One minor issue found which was there before this ticket. Created https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2759
