### ISSUE TITLE
Remove userId arguments in User Facade - Consent Management

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2513]
See master ticker GH-1092

Depends on GH-1578

Remove the userId argument from these functions. Use the user id `current`instead inside the facade functions.

* loadConsents(userId: string): void {
* giveConsent(     userId: string,     consentTemplateId: string,     consentTemplateVersion: number  ): void {
* withdrawConsent(userId: string, consentCode: string): void {
* and more if any other I missed

We also need to refactor the components that use these functions and write down smoke test instructions for which feature we know we should look closer into for regression.

**Comment by plabadie** [comment]
PR #2650

**Comment by KateChuen** [comment]
Tested on dev2. 
- Using "current" now
- Able to 
give consent
<img width="1353" alt="currentGiveConsent" src="https://user-images.githubusercontent.com/45409515/58634010-2c47b100-82b8-11e9-814e-33c940c68368.png">

withdraw consent
<img width="1371" alt="currentWithdrawConsent" src="https://user-images.githubusercontent.com/45409515/58634016-336ebf00-82b8-11e9-99bf-7823ab6b5498.png">

get consent
<img width="1349" alt="currentLoadConsent" src="https://user-images.githubusercontent.com/45409515/58634029-39fd3680-82b8-11e9-9f76-5d9bf59dd976.png">

- Consent works as before.
