### ISSUE TITLE
Search box suggestions still open after pressing enter

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#2517]
When we search for something and press enter, we go to search results page but search suggestions overlay does not close.

This is causing search e2e tests to fail.

![2517](https://user-images.githubusercontent.com/158500/57863907-e9baaa80-77c8-11e9-9bfc-84d72f5a7e93.png)

**Comment by bgambocjaviniar** [comment]
PR: GH-2518

**Comment by LTiger14** [comment]
Passed QA
