### ISSUE TITLE
Component interface has "modifiedtime" capitals: bug?

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2521]
Component interface has "modifiedtime" field but Hybris sends us a field "modifiedTime". Is it a typo?

**Comment by WeizhengSap** [comment]
We generate the data interface from swagger. The `ComponentWsDTO` has `modifiedtime`, but the `ComponentAdaptedData` changes it to `modifiedTime`. 
The best approach is to change the `ComponentAdaptedData` in cmsoccaddon. Or, we can change the SPA component model.

**Comment by WeizhengSap** [comment]
I created this ticket: https://jira.hybris.com/browse/CMSX-8953. If "modifiedTime" is changed back to "modifiedtime" in cmsoccaddon, then in SPA, we also need to change it back.

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2875

**Comment by WeizhengSap** [comment]
This https://jira.hybris.com/browse/CMSX-8953 was completed and it will be released for 2005.

**Comment by Xymmer** [comment]
Wei's PR was done a long time ago, so probably have to redo it.
Also make sure the fix is backwards compatible, as Spartacus might be used with both 1905 and 2005.

**Comment by WeizhengSap** [comment]
Backend changes were released in wcms-module-20.05.0-M20
