### ISSUE TITLE
Regression test May 23 2019 lib release

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2523]
- [x] Run all the E2E tests on the nightly branch on jenkins:
Note: Make sure that ALL the tests are being run (about 29 tests).
OR run them from your computer, pointing to dev17 server.

Additionally, do a quick smoke test (equivalent to the big happy path test) on:
- [x]   Safari
- [x]  Firefox

- [x] Install a new spa from libraries by running this command on dev17 or another server or locally:

> ./spartacus.sh install_shell_app

Script can be found here: https://stash.hybris.com/projects/C3PO/repos/spartacus-installation/browse/spartacus.sh

Run a quick smoke test, and, **update the doc if required**: 
https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Building-the-Spartacus-Storefront-from-Libraries

**Comment by bgambocjaviniar** [comment]
note: there's 28 tests + 10 for mobile, therefore 38 running in the nightly build in jenkins
