### ISSUE TITLE
payment details not saved

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2529]
using dev 17, chrome, may16. repro of bug found by Mikel.

Register new user, add to cart, check out
Order placed successfully but payment details not saved.

address details saved.

in backoffice, the payment details has 'saved' set to false.
set it to true amd save.

go back to spartacus and refresh payment details, it says not authorized for this transaction.
if you look in api call, it says 'undefined'.
https://dev-com-17.accdemo.b2c.ydev.hybris.com:9002/rest/v2/electronics-spa/users/undefined/paymentdetails?saved=true&lang=en&curr=USD

go to other pages and come back, it has my email in the url, but still no payments.

**Comment by Xymmer** [comment]
fixed with GH-2486
retest

**Comment by RadhepS** [comment]
QA: 

Works as expected
