### ISSUE TITLE
Use 'cxDate' pipe instead of native 'date' pipe

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2535]
Some templates still use the native `date` pipe, but should use our `cxDate` pipe, which is connected to our `LanguageService`.
Search for `| date` in templates and replace with `| cxDate`. 
Verify that the date is formatted differently after swtiching the langauge.

**Comment by marlass** [comment]
No use od `date` pipe in our codebase. Dates formatted correctly.
