### ISSUE TITLE
Fix e2e test. Check all of them

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2552]

**Comment by Zeyber** [comment]
Failing e2e tests:
cart-mobile.e2e.spec.ts
product-search-pricing-flow-mobile.e2e.spec.ts

**Comment by Zeyber** [comment]
register-mobile.e2e-spec.ts as well now

**Comment by Zeyber** [comment]
cart-mobile.e2e.spec.ts - should add product to cart as anonymous and merge when logged in:

![image](https://user-images.githubusercontent.com/11735817/58253057-d6c74d80-7d67-11e9-9725-e1a8284d65ba.png)

product-search-pricing-flow-mobile.e2e.spec.ts - should be able to search with price

![image](https://user-images.githubusercontent.com/11735817/58253145-0b3b0980-7d68-11e9-83d8-a319752be655.png)

register-mobile.e2e-spec.ts - should contain error when trying to register with the same email and different password

![image](https://user-images.githubusercontent.com/11735817/58253289-6240de80-7d68-11e9-8339-15e795bac645.png)

**Comment by Zeyber** [comment]
Opened tickets #2642 #2641 to fix cart-mobile and product-search-pricing-flow-mobile.
register-mobile will be fixed in #2442
