### ISSUE TITLE
Payment details cards 

### ISSUE THREAD

**Issue by mikelMHybris** [SAP/cloud-commerce-spartacus-storefront#2567]
The cards in payment details have a few styling issues.

- Card actions are missing margin

- if there is more than 2 cards the second row has no margin-top

- The default payment gray bar styling needs to be fixed. It has the wrong border radius and spacing on the right side.

<img width="1330" alt="Screen Shot 2019-05-20 at 11 10 08 AM" src="https://user-images.githubusercontent.com/30266610/58033534-a6c34480-7af2-11e9-8d04-8fe00760687f.png">

**Comment by Xymmer** [comment]
checked this on dev17 but i don't think it has the latest

**Comment by Xymmer** [comment]
checked with latest develop today, all good
