### ISSUE TITLE
Side effects warning in lib build script

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#2570]
When building lib you can notice 2 warnings about side effects
![image](https://user-images.githubusercontent.com/6259079/58076238-03ce0180-7baa-11e9-909f-05d3f09d505a.png)

**Comment by Pucek9** [comment]
Problem started from https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/50bdcd37d1129dff937c7c906a9e9a66789afa49

**Comment by marlass** [comment]
Build is clear of warnings.
