### ISSUE TITLE
[backend fix required] Payment method account holder name not used

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#2572]
Payment details account holder name is not used and saved anywhere. Instead, name from shipping address is used.
Look at `payment-methods.e2e-spec.ts`

--- May 23rd:
We have disabled the assertion on the account holder name, so the test doesn't fail everyday because the backend fix might take a while. 

Once we get the fix from https://jira.hybris.com/browse/RAY-334

**Comment by Zeyber** [comment]
Request to add payment method is sent with mockup_account_holder as the intended account name:
![image](https://user-images.githubusercontent.com/11735817/58170411-a7dfa780-7c93-11e9-83a2-2bf074ca1e53.png)

Server responds with shipping address name as card holder name:
![image](https://user-images.githubusercontent.com/11735817/58170633-3522fc00-7c94-11e9-860e-a8b80d0b2cf9.png)

**Comment by WeizhengSap** [comment]
https://jira.hybris.com/browse/RAY-334 is created.

**Comment by WeizhengSap** [comment]
I changed this property value, then it works.
![Screen Shot 2019-05-23 at 9 59 18 AM](https://user-images.githubusercontent.com/44440575/58264897-aaea9e80-7d4c-11e9-9337-dea9f5267532.png)

**Comment by KateChuen** [comment]
We have disabled the assertion on the account holder name in https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2648, so the test doesn't fail everyday because the backend fix might take a while. 

Once we get the fix from https://jira.hybris.com/browse/RAY-334:

### TO DO: Enable assertion on line 107 in `payment-methods.e2e-spec.ts` !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Before closing this ticket.

**Comment by KateChuen** [comment]
It's fixed. Tested with commerce-suite-2005.0.191127001.zip on dev10.

### Still need to update the e2e test once we've updated the backend on the server. 

<img width="901" alt="Screen Shot 2019-11-28 at 11 00 05 AM" src="https://user-images.githubusercontent.com/45409515/69820070-482c0100-11ce-11ea-8ead-9418d7ca7206.png">
