### ISSUE TITLE
Render the not found content instead of redirecting

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2581]
When the OCC CMS returns a 404, we currently redirect to the not-found route. This is actually inconvenient, as the original URL is never shown to the user. We like the content of the 404 to be shown on the original requested page.

**Comment by giancorderoortiz** [comment]
Test successful 🆗 
Content of 404 shown as intended on non-existing page. 
Attempted: /sales, /carts, etc...
