### ISSUE TITLE
Move cms store to core library

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#259]
The cms store is wired into the component library. As part of GH-250, we move ngrx store outside the component library and only interact with the facades.

To do:
- follow checklist in GH-250
- have a look at GH-257 for an example
- should be fine but if needed we can have a kickoff with tobias and/or stan

Dependency: Make sure the related facades #230 #322 #157 are done.

Acceptance criteria: 
- it builds :)
- everything in checklist done

**Comment by Xymmer** [comment]
Can start this one when facades refactoring is done
