### ISSUE TITLE
[DONE IN #151] Move storefinder store to core library [after 415]

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#262]
Do this one after #415.

The storefinder store is wired into the component library. As part of GH-250, we move ngrx store outside the component library and only interact with the facades.

To do:
- follow checklist in GH-250
- have a look at GH-257 for an example
- should be fine but if needed we can have a kickoff with tobias and/or stan

Dependency: Make sure the related facade is done.

Acceptance criteria: 
- it builds :)
- everything in checklist done

**Comment by Xymmer** [comment]
Can start this one when facades refactoring is done

**Comment by Matejk00** [comment]
Scope of this task was done during #151
