### ISSUE TITLE
Improve the payment details "Save as default" checkbox

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2620]
In the checkout, when we enter a new credit card, there is a checkbox labeled
"Save as default"

This can be confusing for the users, leading them to think that if they don't tick the checkbox, their payment info is not going to be saved in their account. See GH-2591.

One easy way to make it a little less misleading might be to use the same label as the address:
"Set as default", 

where the wording doesn't imply a choice of saving or not saving.

**Comment by KateChuen** [comment]
Tested on dev17. 
Checkbox is now "Set as default"
![paymentSetDefault](https://user-images.githubusercontent.com/45409515/58718597-d9dfc080-839b-11e9-89db-36e70c067aba.png)
