### ISSUE TITLE
Error when user logs out from the order confirmation screen.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2623]
Assessed on http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

Steps to repro:

* Place an order
* On the order confirmation page, sign out.

Expected:  No errors
Actual results: An error occurs.  It looks like a call is made to load the cart of user "undefined" with cart id "undefined" is made to OCC.

<img width="1679" alt="Screen Shot 2019-05-22 at 3 18 26 PM" src="https://user-images.githubusercontent.com/7065346/58202740-57257a00-7ca6-11e9-847a-81fc374183ca.png">

**Comment by WeizhengSap** [comment]
After checkout, I see "Cart not found" error.
![Screen Shot 2019-05-31 at 11 07 13 AM](https://user-images.githubusercontent.com/44440575/58715188-553d7400-8394-11e9-883d-cf1d0cfb0a34.png)

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2797

**Comment by RadhepS** [comment]
Checkout seems to be broken on localhost? Pressing "Continue" on the order screen does nothing.

**Comment by KateChuen** [comment]
Blocked by ticket #2867
