### ISSUE TITLE
Hide current modal bootstrap modal behind a service

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2645]
Our plan is to remove NgbModal completely from our app. To do so, we need to take care of few time-consuming things. But since we decided to postpone this process to post-alpha (or later) and we, at the same time, need to make sure these changes won't be 'breaking changes' in the future, we have to 'hide' modal service behind our own modal service - approach similar to facades.

The plan:
- [x] create `ModalService` as shared service and provided in root
- [x] make sure above service has exactly the same methods as current `NgbModalService`

Desired outcome:
- possibility to swap NgbModal with any other modal implementation
- guarding ourselves from possible breaking changes while replacing NgbModal in the future (post-alpha or later)

**Comment by giancorderoortiz** [comment]
Please add qa/test steps

**Comment by Pucek9** [comment]
open/close modals works as before
