### ISSUE TITLE
icons are not cleaning up existing classes correctly

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2653]
When an icon type changes at runtime, the icon classes are not cleaned up. This can lead to CSS specificity issues.

**Comment by tobi-or-not-tobi** [comment]
QA:
- Open PLP, toggle facets (collapse / expand facet sections)
- verify that the former icon classes are removed upon expand /collapse

**Comment by KateChuen** [comment]
Tested on dev17
- Able to collapse/expand facet sections, and looks ok.
<img width="1436" alt="facetCollapsed" src="https://user-images.githubusercontent.com/45409515/58508666-8b93ad00-8162-11e9-9c9b-848d494025e6.png">
<img width="1434" alt="facetExpanded" src="https://user-images.githubusercontent.com/45409515/58508667-8b93ad00-8162-11e9-93a2-c35ac915d167.png">

- Upon expanding/collapsing, the classes are either added or removed.
<img width="1436" alt="facetStoresCollapsed" src="https://user-images.githubusercontent.com/45409515/58508678-8fbfca80-8162-11e9-8eb5-3dd8ff5dd9ce.png">
<img width="1431" alt="facetStoresExpanded" src="https://user-images.githubusercontent.com/45409515/58508680-90586100-8162-11e9-9483-e59186e67a40.png">
