### ISSUE TITLE
A few search box bugs

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2659]
After testing #2136 

- when there are no suggestions returned, but there are products being found, the input value should appear as a suggestion
you're supposed to be able to click on the search suggestion but it wasn't working
- in wcms > component > search for 'search', choose 'searchbox' for spa-electronics online,
set to false any of these: display product images, display products, display suggestions
no effect
changing the max/min fields works

**Comment by tobi-or-not-tobi** [comment]
QA:
- when there are no suggestions returned from the backend, but there are products being found, the input value should appear as a suggestion. verify that you can click on such a suggestion and land at the PLP
- verify that changing display product images, display products, display suggestions will have effect in the UI

**Comment by giancorderoortiz** [comment]
- input value appears as suggestion 🆗 
- input value redirects to product listing page. 🆗 
- wcms modifications to search component work as expected. 🆗
