### ISSUE TITLE
Dynamic page layout handling

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2661]
Page Layout service will be able to filter page layout by optional `PageLayoutHandler`. The `PageLayoutHandler` will be able to modify the template given by the backend (or static config). 

One use case for this is the dynamic building of the cart page; while the cms provides statically a paragraph in case there's no cart entries, we cannot always show this. The `PageLayoutHandler` would be able to change this based on the cart entries.

**Comment by dunqan** [comment]
QA steps:
1. Check if cart page doen't display empty cart message when cart is not empty, and display cart items instead
2. Check if cart displays empty cart message when cart is empty

**Comment by giancorderoortiz** [comment]
Test successful. Cart status displayed correctly according empty/non-empty status 🆗
