### ISSUE TITLE
Spike/Implement strategy for unseen global messages

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#2663]
When editing forms and clicking submit, there are often times where the messages indicating responses (such as invalid form data, incorrect password, etc) are not seen because the user has scrolled down the page and does not see the status messages appearing at the top of the page making the form appear unresponsive.

A suggestion is to make the global messages appear statically at the top of the window until the user closes them or otherwise (likely determined by spike #124 ).

**Comment by Zeyber** [comment]
My suggestion:

Status message stays where it is when scrolled high enough on page.
![image](https://user-images.githubusercontent.com/11735817/58328778-46eed580-7e33-11e9-8005-731613b6714c.png)

Status message follows scroll at top of page:
![image](https://user-images.githubusercontent.com/11735817/58328979-c7153b00-7e33-11e9-9ee3-6664da396e3b.png)

**Comment by Zeyber** [comment]
In the situation where multiple messages are displayed and the user has scrolled, should we:
- Stack them: show all when scrolling but one on top of the other
- Overlap them: show a single message with the latest message on top
- Only have one: only ever have one global message
- Something else?

**Comment by Zeyber** [comment]
> In the situation where multiple messages are displayed and the user has scrolled, should we:
> 
> * Stack them: show all when scrolling but one on top of the other
> * Overlap them: show a single message with the latest message on top
> * Only have one: only ever have one global message
> * Something else?

Multiple message scenario should be handled in #124 so no need to consider it here.

**Comment by tobi-or-not-tobi** [comment]
I'd like a few changes:
- show only one similar messages (avoid duplicates)
- stack multiple different messages (if we have several)
- remove messages by different strategies (i.e. based on router change, after form resubmission). this could be strategy applied per type or instance of message.

**Comment by Zeyber** [comment]
> I'd like a few changes:
> 
> * show only one similar messages (avoid duplicates)
> * stack multiple different messages (if we have several)
> * remove messages by different strategies (i.e. based on router change, after form resubmission). this could be strategy applied per type or instance of message.

These issues are more related to and should be handled in #124

**Comment by Zeyber** [comment]
Blocked until #124 and consequential tickets are resolved due to overlap

**Comment by mirkosoft** [comment]
checked, message stays on top when page scrolled down.
