### ISSUE TITLE
Remove userId arguments in User Facade - Close Account

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2665]
See master ticker GH-1092

Remove the userId argument from these functions. Use the user id `current`instead inside the facade functions.

* remove(userId: string): void {

We also need to refactor the components that use these functions and write down smoke test instructions for which feature we know we should look closer into for regression.

**Comment by plabadie** [comment]
PR #2671

**Comment by plabadie** [comment]
For tests:

Make regression tests on the close account function.
Also, validate that the userId in the occ call to close the account does not contain the user email, but the 'current' string instead.

**Comment by KateChuen** [comment]
Tested on dev17.
- Verified that close account uses "current"
<img width="1436" alt="currentCloseAcc" src="https://user-images.githubusercontent.com/45409515/58491840-b7506c00-813d-11e9-8d53-8f4f652ee511.png">

- Verified that "close account" works as before (cannot login and register with the same uid after closing the account, cancel, back, logout, login
