### ISSUE TITLE
Carousel slider is loading products too long

### ISSUE THREAD

**Issue by RomeroDiver** [SAP/cloud-commerce-spartacus-storefront#267]
Steps to reproduce:
- Go to home page
- scroll to the product carousel

**Result**: The products appear only after a long delay

**Comment by Xymmer** [comment]
Note that wei opened #229 
Add productcarousel data to facade

**Comment by RomeroDiver** [comment]
At the moment it seems like the bug is gone. If it comes back, we will create a new one
