### ISSUE TITLE
Remove userId arguments in User Facade - Update User Details

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2672]
See master ticker GH-1092

Remove the userId argument from these functions. Use the user id `current`instead inside the facade functions.

* updatePersonalDetails(username: string, userDetails: User): void {

We also need to refactor the components that use these functions and write down smoke test instructions for which feature we know we should look closer into for regression.

**Comment by plabadie** [comment]
PR #2673

**Comment by plabadie** [comment]
For tests:

Make regression tests on the update personal details functionality.
Also, validate that the userId in the occ calls used do not contain the user email, but the 'current' string instead.

**Comment by KateChuen** [comment]
Tested on dev17.
- Update personal details now uses "current"
<img width="1440" alt="currentUpdPersDet" src="https://user-images.githubusercontent.com/45409515/58489831-04cada00-813a-11e9-97f1-e5e862ba3220.png">

- Verified that update personal details works as before (update personal details, missing fields, cancel, back, save, logout, login)
