### ISSUE TITLE
Remove userId arguments in User Facade - Update Email

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2674]
See master ticker GH-1092

Remove the userId argument from these functions. Use the user id `current`instead inside the facade functions.

* updateEmail(uid: string, password: string, newUid: string): void {

We also need to refactor the components that use these functions and write down smoke test instructions for which feature we know we should look closer into for regression.

**Comment by plabadie** [comment]
Update email e2e test will be fixed by GH-2678

**Comment by plabadie** [comment]
PR #2710

**Comment by plabadie** [comment]
For tests:

Make regression tests on the update email functionality.
Also, validate that the userId in the occ calls used do not contain the user email, but the 'current' string instead.

**Comment by KateChuen** [comment]
Tested on dev2.
- Updating email address uses "current" now
<img width="1330" alt="currentUpEmail" src="https://user-images.githubusercontent.com/45409515/58502845-5f256400-8155-11e9-822e-ca0fee271be3.png">

- Verified that "update email" works as before (update email, cannot login with old email, can login with new email, cancel, back, mismatch email, wrong password)
