### ISSUE TITLE
Failing regression tests:  Checkout as persistent user

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2677]
regression/checkout-as-persistent-user.e2e-spec: 18 failing

- [x] 1) should go to product page from category page
- [x] 2) should add product to cart
- [x] 3) should get cartId and add a payment method
- [x] 4) should proceed to checkout and select shipping address
- [x] 5) should choose delivery
- [x] 6) should select payment method
- [x] 7) should review and place order
- [x] 8) should display summary page
- [x] 9) should delete payment card
- [x] 10) should go to product page from category page
- [x] 11) should add product to cart
- [x] 12) should get cartId and add a payment method
- [x] 13) should proceed to checkout and select shipping address
- [x] 14) should choose delivery
- [x] 15) should select payment method
- [x] 16) should review and place order
- [x] 17) should display summary page
- [x] 18) should delete payment card

**Comment by KateChuen** [comment]
Still failing in jenkins

<img width="829" alt="checkoutTest" src="https://user-images.githubusercontent.com/45409515/59054875-9933eb80-8862-11e9-961e-eb00a2e2f95d.png">

**Comment by marlass** [comment]
Run few time this test on local. Passes every time. Closing PR, issue and moving to done
