### ISSUE TITLE
Failing regression tests: update email and password

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2678]
- [x] regression/my-account/update-email.e2e-spec: 1 failing
Update email when a user can login with the new email should be able to login with its new email:
CypressError: Timed out retrying: Expected to find element: 'cx-update-email', but never found it.
- [x] regression/update-password.e2e-spec: 1 failing
My Account - Update Password when a user is authenticated "before each" hook for "should display server error if old password is wrong.":
CypressError: Timed out retrying: Expected to find element: 'cx-login [ngbdropdown]', but never found it.

**Comment by plabadie** [comment]
regression/update-password.e2e-spec is fixed in GH-2509.
Once it is merged, we can assess the fix and tick the box for regression/update-password.e2e-spec

**Comment by RadhepS** [comment]
Both regression tests work using dev17
