### ISSUE TITLE
Failing regression tests: Order history orders flow

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2679]
regression/my-account/order-history-no-orders-flow.e2e-spec: 2 failing

- [ ] 1) Order History with no orders should go to Order History once user has logged in:
CypressError: Timed out retrying: expected 'http://localhost:4200/electronics-spa/en/USD/' to include '/my-account/orders'
- [ ] 2) Order History with no orders should be able to start shopping from an empty Order History:
CypressError: Timed out retrying: Expected to find element: '.btn.btn-primary.btn-block.active', but never found it.

**Comment by mirkosoft** [comment]
This test is not failing anymore, checked on latest develop, dev17. Hence moving to review.

**Comment by marlass** [comment]
Can confirm. Moving to done
