### ISSUE TITLE
Failing tests but no details in console log

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2681]
The following tests are listed in the table but can't find them in the report:

- [x] mobile/added-to-cart-modal-m…: 1 failing
- [x] mobile/cart-mobile.e2e-spec: 6 failing (1 issue in GH-2641)

**Comment by kacperknapik** [comment]
@marlass where is the PR?

**Comment by marlass** [comment]
Here ya go

**Comment by KateChuen** [comment]
Both mobile/added-to-cart-modal and mobile/cart-mobile tests are passing now.
<img width="827" alt="mobileCartTests" src="https://user-images.githubusercontent.com/45409515/59059070-1152df00-886c-11e9-85a4-e09ac0654c29.png">
