### ISSUE TITLE
Failing regression tests: Mobile tests

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2682]
All mobile tests (except for login) failed on the pipeline last night. 
- [ ] All mobile tests

Search box was refactored last week, so possibly this is part of the reason for failing tests.
- [x] mobile/product-search-mobile.e2e-spec: 1 failing
Search results "before all" hook for "should be able to search and get results":
CypressError: Timed out retrying: Expected to find element: 'cx-searchbox [aria-label="Search"]', but never found it.
- [x] mobile/product-search-product-type-flow-mobile.e2e-spec: 1 failing
Product search should be able to search with specific product type:
CypressError: Timed out retrying: Expected to find element: 'cx-searchbox [aria-label="Search"]', but never found it.
- [x] mobile/product-search-rating-flow-mobile.e2e-spec: 1 failing
Product search should be able to search and show product rating:
CypressError: Timed out retrying: Expected to find element: 'cx-searchbox [aria-label="Search"]', but never found it.
- [x] mobile/product-search-store-flow-mobile.e2e-spec: 1 failing
Product search should be able to search with store filtering:
CypressError: Timed out retrying: Expected to find element: 'cx-searchbox [aria-label="Search"]', but never found it.

The following failing mobile search test has a ticket: GH-2642
mobile/product-search-pricing-flow-mobile.e2e-spec: 1 failing
Product search should be able to search with price:
CypressError: Timed out retrying: expected '<a.cx-product-name>' to contain 'DSC-S930'

**Comment by plabadie** [comment]
Where is the PR?

**Comment by bgambocjaviniar** [comment]
The PR for product-search were done, but the others will be done as an incremental PR. Maybe you can take that if it's still needed
