### ISSUE TITLE
Update category headers on Beautacus

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#2684]
![Screen Shot 2019-05-27 at 10 17 55 AM](https://user-images.githubusercontent.com/34665674/58425955-3758d200-8069-11e9-83af-ee1feff59183.png)
The categories listed are not real categories and therefore they redirect to the homepage.
Replace these with real categories and have them display products in that category when clicked.

**Comment by RadhepS** [comment]
PR: https://stash.hybris.com/projects/C3PO/repos/beautystore/pull-requests/2/overview

**Comment by bgambocjaviniar** [comment]
Ask Bill or someone if the header is supposed to be those names or something other than those you linked in the impex

**Comment by WeizhengSap** [comment]
Can we just leave these empty categories there? We can add category links to them later.

**Comment by RadhepS** [comment]
For QA:

1. Click on every header

Expected result: Navigates to each category's page.

**Comment by KateChuen** [comment]
Tested on dev2. Now all the category links work: Face Powders, Eye Makeup, Concealers, Lipsticks, Makeup Removers
