### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2693]
1. open `/login` page
2. Log in

Then error appears in the console:
![obraz](https://user-images.githubusercontent.com/4001059/58414179-f2d63200-807a-11e9-9039-df96b0b07c5b.png)

**Comment by Platonn** [comment]
will be handled in #2541

**Comment by KateChuen** [comment]
Getting another error after login now (on dev17)
<img width="1296" alt="afterLoginError" src="https://user-images.githubusercontent.com/45409515/58582765-85fc9c80-8220-11e9-97a1-a8c79ae89ade.png">

**Comment by KateChuen** [comment]
Tested on dev19. No error displayed after login.
