### ISSUE TITLE
Create UserConsentConnector / Adapter

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#2696]
1. Extract UserConsentAdapter from UserAccountAdapter
2. Decouple ConsentTemplate backend / UI models
3. Use converters for consent template loading

**Comment by KateChuen** [comment]
Can you add QA Steps please? Thanks :)

**Comment by dunqan** [comment]
QA steps:
Check if user consent functionality works, i.e.:
1. Are consent templates loading?
2. Are consent setting saved?

**Comment by KateChuen** [comment]
Tested on dev2. 
- Verified that the Consent templates are loaded (whether I edit them, or add a new one, they are all loaded correctly). 
![newConsentTemplate](https://user-images.githubusercontent.com/45409515/58635606-4aafab80-82bc-11e9-96dc-d6ea54a688ea.png)

- Verified that the consent settings are saved.
