### ISSUE TITLE
Fix GET/POST errors when using 1811

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2705]
We updated Spartacus to work with cmsoccaddon for 1905, which uses GET instead of POST for getting cms information.

We found one issues when using 1811, after May 24 release:
405 errors returned when GET is used, and this results in severa "unknown errors" displaying in the frontend.
"TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
...." 

We have dev6 and dev7 we can use to test 1811.
https://wiki.hybris.com/display/acc/ROT+DataCenter+VMs

**Comment by bgambocjaviniar** [comment]
PR: GH-2709

**Comment by bgambocjaviniar** [comment]
For testing:

- point backend to https://dev-com-7.accdemo.b2c.ydev.hybris.com:9002
- make electronics as the default base site
- verify in the network tab that GET fails and POST returns 200 OK
- No global error message showing

**Comment by Xymmer** [comment]
Will be fixed and retested with GH-2746
