### ISSUE TITLE
Fix error that displays when searching for products in USD on Beautacus

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#2708]
Create sample data in USD that should prevent errors when searching for products in USD.

**Comment by RadhepS** [comment]
PR: https://stash.hybris.com/projects/C3PO/repos/beautystore/pull-requests/3/overview

**Comment by RadhepS** [comment]
On hold until we decide a short term fix to this problem

**Comment by RadhepS** [comment]
For QA:

1. Set currency to USD
2. Use the searchbar and search for any item

Expected result: List of items with their price in USD and no errors in the console. (The conversion value is not important).

**Comment by KateChuen** [comment]
Is there a reason why it's merged to feature/GH-2551 and not develop?

**Comment by KateChuen** [comment]
Tested on dev2. I still see some errors when I search:
![beautySearch](https://user-images.githubusercontent.com/45409515/58826825-95f4f180-860f-11e9-9e4f-70b398fbccf6.png)

**Comment by Xymmer** [comment]
Radhelp fixed latest issue with #2773

**Comment by KateChuen** [comment]
Tested on dev2. No more error. Able to search for product in USD.
