### ISSUE TITLE
Quantity Counter box on PDP is missing bottom border

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2712]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/product/DSC-T90/1992693

**Steps to Reproduce**
Navigate to the pdp of product 1992693.
Click on the upselling product.
![selectUpsellingProd](https://user-images.githubusercontent.com/45409515/58429900-5c534200-8075-11e9-92fc-c4bdc2bf3e79.png)

**Actual Result**
The Quantity Counter Box is missing the bottom border.
![QtyBox](https://user-images.githubusercontent.com/45409515/58429873-434a9100-8075-11e9-99ee-3bfe012fa98f.png)

**Comment by KateChuen** [comment]
Cannot reproduce on dev17.

**Comment by mikelMHybris** [comment]
@KateChuen I cannot replicate the issue. I also cannot access : http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/product/DSC-T90/1992693

**Comment by KateChuen** [comment]
Happens in my current viewport and if I zoom out. 
Doesn't happen on mobile viewport & if I zoom in.

**Comment by mikelMHybris** [comment]
This is a chrome bug. Zoom doesn't affect the border in FF or safari. I don't know of a fix for the chrome bug.

**Comment by Xymmer** [comment]
won't fix then
