### ISSUE TITLE
Cart Not Found after placing an order [fixed in #2623]

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2714]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/product/DSC-T90/1992693

**Steps to Reproduce**
Login.
Add a product to cart.
Place order.

**Actual Result**
On the order confirmation page, after the order is placed, there's a GET call that returns 400. 
And a "Cart not found" error displayed on the UI. 

![cartNotFound](https://user-images.githubusercontent.com/45409515/58432508-b1e11c00-8080-11e9-9ed1-43eae948a9e6.png)

**Comment by Xymmer** [comment]
maybe a logged in user should always have a cart? if you just bought something, your cart is converted to an order and i guess we lose the number

**Comment by giancorderoortiz** [comment]
"Cart not found error" message no longer displayed after placing order.
