### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined - in ProductImagesComponent

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2716]
In dev 17:
1. visit PDP, i.e.  `/product/DSC-WX1/3514521`

The error appears in the console few times:
![obraz](https://user-images.githubusercontent.com/4001059/58435050-f4294e00-80be-11e9-979a-f71fc3a45ab1.png)

**Comment by tobi-or-not-tobi** [comment]
will be fixed with #2692

**Comment by KateChuen** [comment]
Tested on dev2. No such error is displayed anymore.
