### ISSUE TITLE
Update the facades to provide functions only

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#272]
We currently have 3 mixed ways to provide features on out facade services:

- custom function, i.e. getXyz
- getter, i.e. get xyz()
- pubic exposed property

To provided consistency to our Api, we could only expose functions through our facade API.

The facade services are all the services in a `.../facade/` folder. 

List of pros:
- More consistent api between features of a same service facade and between different service facades.
- Seems that functions are easier to spy on and apply mock behaviours.

List of cons:

This could become a spike if we need to try things out to verify assumptions.

**Comment by Xymmer** [comment]
need final decision from Tobias, as go was given but then Stan made some new points.

**Comment by tobi-or-not-tobi** [comment]
Tickets to be created for facade refactor:
-  refactor public accessors into functions
- (optionally) rename functions to be short and into context (i.e. `productService.get()` rather then `productService.getProduct()`). Avoid redundancy. Additionally we are allowed to not mirror the commerce platform. 

Separate tickets
- we've refactors `productGuards`, but that's a side topic.

**Comment by Xymmer** [comment]
Stan to finish and merge, probably by Friday
Stan to create a checklist for gladiator devs to follow when doing the tickets

**Comment by dunqan** [comment]
How to add generic loading flags to an existing chunk of state:

1. Wrap default reducer with loaderReducer, for example:
loaderReducer('UNIQIUE_ENTITY_ID')
2. Use LoaderState to get type safety with wrapped state
3. Extend from LoaderActions to set required metadata for actions
4. Use selectors functions to get wrapped state (loaderValueSelector) or specific flags
(loaderLoadingSelector, loaderLoadingSelector, loaderSuccessSelector)

Checklist for entityLoaderReducers would be exactly the same,
the difference is that it wraps LoadReducers (above) with EntityReducer,
to support loading flags for multiple entities (like products or components)

**Comment by Xymmer** [comment]
Testing of this work will be done with the facade regression test ticket, #6
