### ISSUE TITLE
Release new libraries - /storefront: 0.1.0-prealpha.5 /styles: 0.1.0-prealpha.4 (Nov 13 2018)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#273]
Let's try releasing every sprint.

Current releases as of this writing are:
@spartacus/storefront: 0.1.0-prealpha.4
@spartacus/styles: 0.1.0-prealpha.3
https://www.npmjs.com/search?q=spartacus

New versions will be:
@spartacus/core: 0.1.0-prealpha.1
@spartacus/styles: 0.1.0-prealpha.4
@spartacus/storefront: 0.1.0-prealpha.5

**Comment by hackergil** [comment]
GH-232 and GH-289 are blocking this

**Comment by hackergil** [comment]
Pull request #312
