### ISSUE TITLE
Flickering after login/logout

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2733]
In dev17:

## Login
1. go to category page
2. click "sign in / register" link
3. sign in 

Then the login page is refreshed and eventually we are redirected back to category page. (The reload of the login page was unnecessary).

---
# Logout
1. go to category page
2. click "Sign out" link

Then we are NOT redirected to the home page (as we should) and the error apprears in the console:
![obraz](https://user-images.githubusercontent.com/4001059/58479498-b1b44f80-8158-11e9-89d1-d1a123fe2135.png)

*Note*: the error doesn't occur when you log out when being on the i.e. `/sale` page

**Comment by dunqan** [comment]
I would say, that we have to reload the page, as it's a generic cms page (and it's data could change after login) so making exception for login page (or register) is no good way to fix this. 
Page reload after login is a primal requirement, redirect after login is a sub-primal one, specific to pages with certain components.

**Comment by dunqan** [comment]
QA steps:
1. Login page/form should not flicker when logging in
2. Logging out on category page should not cause an error in the console

**Comment by KateChuen** [comment]
Tested on dev17
- I don't see this error anymore when logging out. But I do see this now:
<img width="1295" alt="logOutError" src="https://user-images.githubusercontent.com/45409515/58582936-d3790980-8220-11e9-9b4d-e8eb2ad151bb.png">

- As for the flickering, I see the login form for a split second when I login and it's loading the homepage.

**Comment by KateChuen** [comment]
Moving it back to "To do" so a dev can take another look at it.

**Comment by dunqan** [comment]
It's not an error, it's expected behavior, when there is no logout page in CMS (which is optional).
