### ISSUE TITLE
Fix store finder on Beautacus

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#2734]
Store finder does not currently display anything

**Comment by RadhepS** [comment]
PR: https://stash.hybris.com/projects/C3PO/repos/beautystore/pull-requests/4/overview

**Comment by RadhepS** [comment]
Storefinder will probably look buggy if you're using the cloud commerce front-end because the Storefinder is being hidden. It's also buggy on electronics-spa. Once the header link is gone it won't be a problem because people won't go to it. 

I think it's good to merge it nonetheless so that when we eventually bring back the storefinder after release, we'll have the code in the beautystore backend.

This is how it looks when using the Beautacus front-end (it isn't updated to the latest version of the storefront yet, it will be if/when a new storefront script is made).

![Screen Shot 2019-06-04 at 4 00 28 PM](https://user-images.githubusercontent.com/34665674/58969594-f60da400-8785-11e9-8d44-a45af5a4763f.png)

**Comment by KateChuen** [comment]
Tested on dev2. 
StoreFinder Page looks buggy like Radhep predicted.
![beautyStoreFinder](https://user-images.githubusercontent.com/45409515/59042422-6d0b7100-8848-11e9-9490-bfc555658958.png)


But I still see the "Find a store" link on the beautacus storefront (I have the latest frontend and I don't see it on electronics-spa). 
So sending it back to Radhep to remove the link.

**Comment by RadhepS** [comment]
PR: https://stash.hybris.com/projects/C3PO/repos/beautystore/pull-requests/10/diff

Removed store-finder link

**Comment by RadhepS** [comment]
Changes have been merged. Please make sure to get the newest version of the beautystore from the Github repo.

**Comment by KateChuen** [comment]
Tested on dev2. Don't have "Find a Store" link anymore. 
![beautyStoreLinkGone](https://user-images.githubusercontent.com/45409515/59123878-4de60f80-892c-11e9-8278-4fb0eff84aea.png)
