### ISSUE TITLE
user redirected to previously viewed account page after logging out

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2737]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
_Scenario 1_
Login.
Update password.
Logout.
Login.

_Scenario 2_
Login.
Go to update password page.
Click cancel.
Logout.
Login

_Scenario 3_
Login.
Go to update password page.
Click on Back Browser Button.
Logout.
Login

**Actual Result**
Upon updating password successfully or clicking cancel, user is redirected to homepage. 
But then, after user logouts and logs in again, user is redirected to "update password" page again. 

**Expected Result**
I was kinda expecting to be redirected to homepage instead. 
I know all this will change in the future when we'll have myaccount page. But in the meantime? 

**Note**
Same thing for other myaccount pages (for eg, udpate personal details)

**Comment by marlass** [comment]
Checked those scenarios also for other my account pages and didn't notice this behavior. I was always redirected to home page, which is expected behavior.
@KateChuen Could you confirm it one more time?

**Comment by KateChuen** [comment]
Yes indeed, now the user is redirected to homepage.

**Comment by KateChuen** [comment]
Yep, tested on dev2, and it's not happening anymore.

**Comment by KateChuen** [comment]
Actually it still happens, but only for "Update Email Address" now. Because I guess the user was redirected to the login page after the update, vs the homepage for the other account features.

**Comment by bgambocjaviniar** [comment]
PR: GH-3731

**Comment by bgambocjaviniar** [comment]
FOR QA:

- login
- hover or click my account
- navigate to update email page by clicking email address
- change your email to something new or same one
- try to login with the 'new' email

It should redirect you to home

**Comment by KateChuen** [comment]
Tested on dev2 on chrome, safari & firefox. 
User is redirected to home now. 
Also verified the other pages of myAccount. All still redirects to homepage after login.

**Comment by bgambocjaviniar** [comment]
GH-3839

Will revert back to this when we can handle the breaking change
