### ISSUE TITLE
Login form displayed after logged in

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2738]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Click on the Login link.
On the login page, click on "Register"
On the "Register page", click on "I already have an account. Sign In"
Login with a valid user

**Actual Result**
User is logged in successfully. But the login form is displayed.
<img width="1064" alt="loginForm" src="https://user-images.githubusercontent.com/45409515/58491685-75272a80-813d-11e9-99db-b848082a94ca.png">

**Expected Result**
Homepage should be displayed.

**Comment by Matejk00** [comment]
@KateChuen I tried to reproduce this bug, but every time I'm redirected to the homepage and all seem to work as expected. Can you do re-check?

**Comment by KateChuen** [comment]
Tested on dev2 today, looks like it's not an issue anymore.
