### ISSUE TITLE
cart not found error after updating email address

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2739]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login.
Add a product to cart. 
Update the email address. (MyAccount -> Email Address)

**Actual Result**
"Cart not found" error is displayed. 
<img width="1290" alt="currentEmail" src="https://user-images.githubusercontent.com/45409515/58502210-1c16c100-8154-11e9-858a-8679147933c6.png">

**Comment by kacperknapik** [comment]
cannot reproduce.

changed email, logged in, cart was there, changed email again, logged in, cart again there. no errors

**Comment by marlass** [comment]
Also cannot reproduce

**Comment by KateChuen** [comment]
Tried on dev19 today, couldn't reproduce it. So closing this ticket.
