### ISSUE TITLE
Add config for using cms GET/POST and allow use with 1811

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#2746]
Instead of having a fallback that introduces errors and which is just a workaround, we will now use a config where the user can choose between true/false if they're using a legacy backend (1811) or the up to date one (1905+)

This will close GH-2705 and GH-2589

**Comment by bgambocjaviniar** [comment]
QA:

- Make sure we can switch between POST and GET by changing the value in app.module.ts of legacy (true/false). Verify in the network tab (dev tools) if legacy is false (which is the default if not specified in app module), you will see in the network tab that the components?fields=.. is using the GET request. If it is true, then the user is saying they're using a legacy backend, such as 1811, and make sure in the network tab (dev tools), shows a POST request for the components.

- Also, point your environment to an 1811 backend server, such as https://dev-com-17.accdemo.b2c.ydev.hybris.com:9002, and look at the network tab again to see that the post is being used and not failing.

**Comment by bgambocjaviniar** [comment]
PR: GH-2747

**Comment by Xymmer** [comment]
default is GET right?

**Comment by giancorderoortiz** [comment]
Please assign to me for testing.

**Comment by giancorderoortiz** [comment]
I am unable to confirm bug fix when deploying storefront from a linux dev-server and connecting to an 1811 backend. 
I will let other team members verify as well and accept their decision.

**Comment by Xymmer** [comment]
this works for 1905, so we'll pass the ticket
i'll create a follow up for 1811

**Comment by Xymmer** [comment]
assigning to Brian for doc input

**Comment by Xymmer** [comment]
i was able to verify by pointing to dev5 and showing 'method' column in network tab, indeed we are using post when legacy = true and GEt when it's fasle
it kind of threw me because all the cms content was still appearing
