### ISSUE TITLE
Rename spacceleratorsamplesaddon to spartacussampledataaddon

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2756]
New name: spartacussampledataaddon

This addon will contain all spartacus sample data, including future changes for apparel or others.

To start, create a new repo with a copy of spacceleratorsamplesaddon
Then later we'll delete the old one

Might have to do it in new github, talk to Joy

Also need to change the copyrights:

> Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. The files in this addon are licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.

**Comment by WeizhengSap** [comment]
The spartacussampledataaddon is here: https://stash.hybris.com/projects/C3PO/repos/spartacussampledataaddon/browse

yenv template PR is here:https://stash.hybris.com/projects/INFRA/repos/yenv/pull-requests/96/overview

To test it, it is better you use yenv to create a new env. 
1. Make sure there is no "spacceleratorsamplesaddon" in the new env.
2. Make sure SPA works (no need test page by page, the impex files are just copied. So, open homepage, change language/currency, register, login/logout.)

**Comment by plabadie** [comment]
Looks good, works well.

The one comment I have is about the copyright header.  I did a few spot-checks in spartacussampledataaddon and the headers seem unchanged.  Do we intend to do so like this description seems to suggest?

**Comment by WeizhengSap** [comment]
copyright replacement PR is here: https://stash.hybris.com/projects/C3PO/repos/spartacussampledataaddon/pull-requests/3/overview
