### ISSUE TITLE
Hide no-value or redundant global messages

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2767]
- on address management page, when i click 'set default', don't display 'success' global message
- when i place an order and we show confirmation, don't show 'order placed successfully'
- anything that says 'an unknown error occured'

Note that Asterix has a few tickets related to Global Messaging.

**Comment by giancorderoortiz** [comment]
Multiple "an unknown error occurred" messages when the security certificate has not been accepted are redundant. One message suffices. It's a bad first impression.

**Comment by giancorderoortiz** [comment]
"Bad credentials. Please login again" wrong message displayed when user attempts to register with an email address already used.

**Comment by Xymmer** [comment]
1) Multiple messages > we have a task in Asterix to resolve duplicate messages.
2) Bad credentials> that's more of a bug than for this list.

**Comment by KateChuen** [comment]
Tested on dev2 and dev17. No more messages displayed for when
- setting address/payment as default
- placing an order
- unknown error
