### ISSUE TITLE
Fix error when using the search bar and pressing enter on Beautacus

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#2773]
There is currently an error that displays when entering data into the search bar instead of using the search functionality. 

![Screen Shot 2019-05-31 at 11 48 12 AM](https://user-images.githubusercontent.com/34665674/58717810-11e60400-839a-11e9-9571-5925dcfd9d65.png)

**Comment by tobi-or-not-tobi** [comment]
Please provide the error or a way to reproduce.

**Comment by RadhepS** [comment]
> Please provide the error or a way to reproduce.

Sorry for the late response, I've added a screenshot of the error.
Please note that this is an issue on Beautacus and not the main application Spartacus.

**Comment by WeizhengSap** [comment]
Please change "search" from CategoryPage to ContentPage.

**Comment by RadhepS** [comment]
PR: https://stash.hybris.com/projects/C3PO/repos/beautystore/pull-requests/7/overview

**Comment by KateChuen** [comment]
Tested on dev2. It works now. No more error when searching.
