### ISSUE TITLE
Avoid error while retrievening Open ID token

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#2777]
There's an error in console that's shows when registering and retrieving Open ID token.

**Comment by znikola** [comment]
PR: #2778

**Comment by znikola** [comment]
QA:
1. Make sure the kyma OAuth client is defined on the testing server
2. After logging in/registering there should not be an error displayed as a global message, nor an error in the console/network tab related to `/token` endpoint.

**Comment by KateChuen** [comment]
Tested on dev2. Works now. No . more token error.
![tokenGood](https://user-images.githubusercontent.com/45409515/58817964-fe85a380-85fa-11e9-9592-07aec369f909.png)
