### ISSUE TITLE
Release Testing Overall Ticket

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2779]
- [x] Device Testing: Add to Home Screen. Works on Android (samsung galaxy) Doesn't work on iphone (ticket:)

- [x] Browser Testing: Exploratory

- [x] Device Testing: Exploratory

- [x] Install SPA using npm libs

- [ ] Security Scan

**Comment by Xymmer** [comment]
closing this one as the subtasks hae their own tickets in 1.0 b ucket
