### ISSUE TITLE
Update checkout backend 'need help' in other languages

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2780]
The 'need help' in checkout is good in English but the other languages aren't up to date.
The changes needed in Spartacus sample data (Electronics will be fixed separately):

HelpParagraphComponent:
- English is: 
```<strong>Need Help with your checkout process?</strong> <span>Contact Us or Call phone number.</span>```
- Copy this same to JA, DE, ZH. We'll get it translated later.

**Comment by Xymmer** [comment]
#2804 for front-end strings

**Comment by WeizhengSap** [comment]
Backend PR is here: https://stash.hybris.com/projects/C3PO/repos/spartacussampledataaddon/pull-requests/5/overview

**Comment by plabadie** [comment]
Backend PR is here:  https://github.tools.sap/cx-commerce/c3po-legacy-spartacussampledataaddon/pull/2

**Comment by plabadie** [comment]
Works:
![checkout](https://user-images.githubusercontent.com/7065346/59206975-18cbfe00-8b74-11e9-9fba-9cf8c95bb5bd.png)

**Comment by KateChuen** [comment]
Tested on dev19. It's ok in other languages now.
<img width="1055" alt="Screen Shot 2019-06-13 at 1 43 06 PM" src="https://user-images.githubusercontent.com/45409515/59454993-49649f80-8de1-11e9-8587-02d652e6a6b8.png">
