### ISSUE TITLE
Exploratory Session #1 [all devs]

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2781]
modelT env ready to test: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

Pick a device/browser, and Update the table with your name please:

- [x] Mac/Safari -----> Wei
- [x] Mac/Chrome -----> Michał G
- [x] Mac/Firefox -----> Michał G
- [x] Ipad Pro/Safari -----> GC
- [ ] Ipad Pro/Chrome -----> GC
- [x] Ipad Air/Safari -----> Bill
- [x] Ipad Air/Chrome ------> Bill
- [x] Iphone SE /Safari ------> Kris
- [x] Iphone 6 /Safari ------> Patrick
- [x] Iphone 6 /Chrome -----> Mateusz
- [x] Iphone 8+ /Safari -----> Gil
- [x] Iphone 8+ /Chrome -----> Kate (sw v 12.2)
- [x] Iphone XR/XS Max /Safari -----> Stan
- [x] Iphone XR/XS Max /Chrome -----> Stan
- [x] Windows/Chrome -----> Farzin
- [x] Windows/Firefox -----> Kate
- [x] Windows/Edge -----> CAINE
- [x] Samsung Galaxy S6?/Chrome -----> Louis
- [x] Samsung Galaxy S6?/Firefox ----->Louis
- [x] Huawei p20 pro / Galaxy S8/S9/Chrome -----> Nik
- [x] Huawei p20 pro / Galaxy S8/S9/Firefox -----> Michal Sz
- [x] Samsung Galaxy S10+/Chrome -----> Kate
- [x] Samsung Galaxy S10+/Firefox -----> Kate
- [x] Samsung Tablet/Chrome -----> Radhep
- [x] Samsung Tablet/Firefox -----> Brian
- [ ] Sony Xperia X5 Compact/Chrome -----> Miro
- [ ] Sony Xperia XA1/Chrome -----> Miro
- [x] Moto X Style (Android 7.0) Firefox -----> Marcin
- [x] Moto X Style (Android 7.0) Chrome -----> Marcin
- [x] Xiaomi Redmi 4/Chrome  -----> Caine
- [x] Xiaomi Redmi 4/Firefox  -----> Caine
- [x] Doogee s80 (Android 8.1) Chrome/PWA -----> Michał G

- [x] Windows tablet: Stan (Chrome/Edge)

**Comment by dunqan** [comment]
It would be good to specify OS versions for Android and IOS devices used for testing.
