### ISSUE TITLE
Conditionally enable kyma integration

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#2782]
Depends on #2777 
To avoid showing errors when kyma client is not defined on the backend, we should make kyma integration configurable.

**Comment by znikola** [comment]
PR: #2789

**Comment by znikola** [comment]
To QA:
If the flag is `false` in `app.module.ts`, we should not issue the request to get the open id token. To verify this, check the network tab.
If the flag is on, and the kyma is configured on the server, we should get the token, just like we did before.

**Comment by KateChuen** [comment]
Tested on dev2. 
- With kyma disabled, there's only one regular token request sent.
<img width="1303" alt="regularToken" src="https://user-images.githubusercontent.com/45409515/58977546-fadb5380-8797-11e9-8e6f-4e209fb18bc7.png">

- With kyma enabled, there's the openid token request sent on top of the regular token request. 
<img width="1314" alt="openIdToken" src="https://user-images.githubusercontent.com/45409515/58977556-00d13480-8798-11e9-85f8-bea257856c0b.png">
