### ISSUE TITLE
Sample Data Changes to Allow Better Fit in the Header

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2786]
At present, the main menu items in SPA do not fit across the header and are breaking the design, and are either very crowded or breaking the design.

This story is about changing the sample data to reflect best practices and resolve the fit issues.

NOTE: THE SCREENSHOT ATTACHED IS ONLY A REFERENCE FOR CHANGES TO SAMPLE DATA. NOT FONTS, COLORS ETC...

Currently, the categories are:
Brands
Digital Cameras
Film Cameras
Hand Held Camcorders
Webcams
Power Supplies
Flash Memory
Camera Accessories & Supplies*
*and the subcategories under this are:
Accessories
Supplies

We would like to make the following changes:
Brands
Digital Cameras
Film Cameras
Camcorders
Webcams
Accessories*
*and the subcategories under Accessories are
Gear*
Supplies
*under Gear we would add
Flash Memory (formerly a level 1 category, now a subcategory)
Power Supplies (formerly a level 1 category, now a subcategory)

Justifications
1 All camcorders are pretty much hand held (unnecessary modifier)
2 Flash is an unnecessary modifier of Memory
3 Accessories & Supplies (too long and localisation does not like & ampersands)
4 Subcategories: It is not best practices to have a Category and a Subcategory with the same label. Since we are renaming the main menu item to Accessories, the Subcategory menu item cannot be a duplicate. We propose renaming it to "Gear" and the other subcategory to remain as "Supplies"
5 Flash memory and Power supplies are 'technically' Accessories

**Comment by vekterdude** [comment]
![Sample_Data_updates](https://user-images.githubusercontent.com/44620139/58656822-fb34a400-82ea-11e9-922e-bf470f2e76e3.jpg)

**Comment by vekterdude** [comment]
@tobi-or-not-tobi 
I assigned this to you for concept approval, feasibility etc.. If you are ok with it, please re-assign to an appropriate dev team member, or tackle it yourself!
Cheers! :-)

**Comment by vekterdude** [comment]
![Sample_Data_updates](https://user-images.githubusercontent.com/44620139/58661114-08ef2700-82f5-11e9-8eb5-7a7de1778588.jpg)

**Comment by tobi-or-not-tobi** [comment]
closed with #2135
