### ISSUE TITLE
Remove 'Done' from consent page

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2788]
'Done' button on consent page doesn't seem to do anything besides go to home. Let's remove it for now. I know we were supposed to have a 'my account' home.

**Comment by KateChuen** [comment]
Tested on dev2. No more "Done" button on consent page.
<img width="975" alt="consentDone" src="https://user-images.githubusercontent.com/45409515/58976666-03cb2580-8796-11e9-876e-f0c5a6d4c2e4.png">
