### ISSUE TITLE
User facade get() function loads user under the hood.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#2796]
The User facade get() function must load the user under the hood if no user is found in the app state.

**Comment by plabadie** [comment]
PR #2832

**Comment by plabadie** [comment]
For tests.

This is an under the hood change.  The tests should essentially make sure that the user details are properly loaded in the store.  For that, you can:
- Sign in and sign out and assess that the greeting in the header reacts accordingly ( toggling between the greeting and the link to sign in )
- Update user details and verify that the update was successful.

**Comment by KateChuen** [comment]
Tested on dev2. 
- Updating user details works.
- Greeting and signIn links in the header are displayed accordingly and work well.
