### ISSUE TITLE
Hide Storefinder feature

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2805]
For storefinder, there are just too many issues to get it done for beta/release.

Let's hide the page for now, for e.g. (devs please correct me here):
- hide the link
- guard the page label so it goes to Home?
- don't need to hide the module, just label it as unfinished? or do we not include it at all?

We'll quickly get back to it after 1.0 release.

**Comment by znikola** [comment]
Backend PR: https://stash.hybris.com/projects/C3PO/repos/spartacussampledataaddon/pull-requests/1/diff

**Comment by znikola** [comment]
QA: navigating directly to the store finder page (via URL) should result in 404 message. None of the store finder features should be visible.

**Comment by KateChuen** [comment]
Tested on dev2. 
We don't have a "Find a store" link on the storefront anymore. 
<img width="1018" alt="noStoreFinder" src="https://user-images.githubusercontent.com/45409515/58959028-2d725580-8772-11e9-99a4-6788e8754b02.png">

And if we navigate to the storefinder url directly, we get a "notFound" page. 
<img width="1018" alt="storeFinder404" src="https://user-images.githubusercontent.com/45409515/58959032-306d4600-8772-11e9-8513-ff9c902a4e2b.png">

Same thing for all storefinder pages: 
https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/store-finder
https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/store-finder/find?query=
https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/store-finder/view-all
https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/store-finder/country/JP
https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/store-finder/country/JP/region//Tokio%20Cerulean%20Tower%20Tokyu%20Hotel
https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/store-finder/find?useMyLocation=true
