### ISSUE TITLE
Enable storefinder in sample data

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#2811]
In #2805 we disabled the storefinder feature. In this ticket we need to enable it back.

Search for `TODO:#2811` in the `spaacceleratorsampleaddon` and uncomment everything.
Search for the same string across the spartacus code base and do the same.

**Comment by Matejk00** [comment]
Storefinder sample data enabled on dev-22. For update sample data repo we have other ticket: #3855
