### ISSUE TITLE
[depends on #2482] Upgrade to ngrx 8

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#2813]
https://next.ngrx.io/guide/migration/v8

Depends on #2482

**Comment by Xymmer** [comment]
Tobias and Nik say we can do this after beta release, and after move to Angular 8

**Comment by znikola** [comment]
We encountered a bug in ngrx: https://github.com/ngrx/platform/issues/1902 which is now fixed.
Per [this comment](https://github.com/ngrx/platform/issues/1902#issuecomment-498255851) we will proceed with the upgrade by pulling the nightlies until ngrx team releases a new RC version.

**Comment by SerkanSipahi** [comment]
Do you guys thinking about to drop your own entity adapter by replacing it with ngrx enitiy adapter? I think its easier to user for angular, ngrx devs. They will know where to look when information about it is needed (documentation). The entity lib will be maintained by active and hundreds of developers. Bug fixes will be fixed immediately.

**Comment by znikola** [comment]
We are considering it, but it's not decided yet.

**Comment by SerkanSipahi** [comment]
I could help! I know spartacus by heart because we build a frontend for an industry customer based on spartacus (our custom module). I invested a lot of hours (last 5 month) in your code to understand it :)

**Comment by znikola** [comment]
Excellent, that's great! I will reach out to you when I start working on it. Thank you!

**Comment by znikola** [comment]
PR: #3013

**Comment by SerkanSipahi** [comment]
Docs PR Link is not working.

**Comment by znikola** [comment]
The docs repo is private.

**Comment by znikola** [comment]
To QA:
Everything should work in the same way as before.

**Comment by KateChuen** [comment]
Tested on dev19. Did a smoke test, everything looks fine.
