### ISSUE TITLE
Change pageLabels for cart, order confirmation and order details

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#2816]
Change pageLabels for cart, order confirmation and order details pages.

Those should match page URL.

**Comment by marlass** [comment]
Addon PR: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/54/overview

**Comment by mirkosoft** [comment]
tested, works as intended.
