### ISSUE TITLE
-Muhammad- Navigation positioned offscreen

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#2822]
There is an issue with navigation on smaller viewports.
![image](https://user-images.githubusercontent.com/6259079/58792786-21ad5480-85f5-11e9-9787-a5ca9254979a.png)

It is always positioned right, even if there is no space for it.

**Comment by Matejk00** [comment]
After #2792 changes problem still exists. 

We decided with @tobi-or-not-tobi to leave it for now and back to the topic after beta release. It can be fixed temporaily by sample data change.

**Comment by Xymmer** [comment]
looks like this is fixed

i did a test by making the german text longer 

![image](https://user-images.githubusercontent.com/4998145/65169327-4e567200-da14-11e9-8d75-57beb03de9d5.png)

**Comment by Xymmer** [comment]
can't repro now, likely fixed in a previous release
