### ISSUE TITLE
User address form: infinite loop call for regions (it's back, linux only?)

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#2825]
## Steps to Reproduce
Go to address book and either:
* click 'Add New Address' -> select any country from the dropdown
or
* click 'Edit' on existing address card

## Observed Results
In the devtools network tab you can see infinite loop calls are happening:
![image](https://user-images.githubusercontent.com/788092/58799374-7658cb80-8605-11e9-8212-3e2c87951def.png)

**Comment by mszczepaniak** [comment]
The issue with the infinite loop is not present anymore:
![address book country](https://user-images.githubusercontent.com/4272069/59973369-6cd8d880-959f-11e9-87bb-3e8957dbe86a.png)

**Comment by kacperknapik** [comment]
this problem reappeared. we need to check that again

**Comment by Xymmer** [comment]
as mentioned by Brian, looks like it might be Linux only. See #3802. Brian could not repro on Mac/Chrome.

**Comment by bgambocjaviniar** [comment]
NOTE: 

master/develop branch is working perfectly, but on the build on model-t is most likely old. Shouldn't be a problem if we re-deploy a new build to model-t.
Since in model-t, the infinite request calls exists, but not other backends

**Comment by kacperknapik** [comment]
Windows 10 + dev-17 is broken for me

**Comment by mrSingh007** [comment]
hi just for info:
I think it might be better to check 'null' instead of object length. For Example this method will also create endless loop if empty object is received from backend

```
 getSupportedDeliveryModes(): Observable<DeliveryMode[]> {
    return this.checkoutStore.pipe(
      select(CheckoutSelectors.getSupportedDeliveryModes),
      tap(deliveryModes => {
        if (Object.keys(deliveryModes).length === 0) {
          this.loadSupportedDeliveryModes();
        }
      }),
      shareReplay({ bufferSize: 1, refCount: true })
    );
  }
```
Better would be to put **initial state value in reducer as null** and then above on if you would check null instead of length. As null would be only once, when backend call was not happen at all.

**Comment by psmul** [comment]
Steps for QA:
1. Log in
2. Go to Address Book
3. Create new or click edit existing one
4. Select any country from dropdown component

Browsers shouldn't crash anymore & Network tab in Developer Tools shouldn't make a lot of calls for the same region list endpoint.

**Comment by mszczepaniak** [comment]
Tested successfully.
