### ISSUE TITLE
Failing E2E: checkout as persistent user test

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2828]
Check the checkout as persistent user test. It's failing in jenkins

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2919

**Comment by RadhepS** [comment]
Required handling a merge conflict so it needs to be approved again.
Patrick is off for the day so placing back into code review for someone else to take a look again.
