### ISSUE TITLE
Failing E2E: register test

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2829]
The register test is failing in jenkins.

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2915

**Comment by RadhepS** [comment]
Referencing other ticket that is in Server QA in the Asterix team table to make them aware I fixed the test. https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2443
