### ISSUE TITLE
Warning when building for production

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#2831]
There a few warning when perform a production build:
```
'Observable' is imported from external module 'rxjs' but never used
'FormGroup' is imported from external module '@angular/forms' but never used
```
<img width="643" alt="Screen Shot 2019-06-03 at 11 24 32" src="https://user-images.githubusercontent.com/11561723/58813690-4e13a180-85f2-11e9-88e7-0deedec78f95.png">

These are most likely coming from `projects/storefrontlib/src/lib/checkout/components/payment-method/billing-address-form/billing-address-form.component.ts`

We have two properties in the component:
```
  @Input()
  billingAddress: FormGroup;
  @Input()
  countries$: Observable<Country[]>;
```

In the generated `dist/storefrontlib/esm2015/lib/checkout/components/payment-method/billing-address-form/billing-address-form.component.js` file we end up with imports that are not used.

**Comment by reyhanehsalkhi** [comment]
It seems to be related to this bug in angular. 

https://github.com/angular/angular/issues/21280

**Comment by reyhanehsalkhi** [comment]
The warnings are probably related to the known issue here angular/angular#21280 closing the issue.
