### ISSUE TITLE
Payments not saved as default

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2833]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Add items to cart
Proceed to checkout
During checkout, click on "Set as default" for payments
Go to MyAccount -> Payment Details -> There are 2 copies of that payment info

Add more items to cart
Proceed to checkout
During checkout, add a new payment. Click on "Set as default"
Go to MyAccount -> Payment Details -> The new payment is NOT set as default

**Comment by Pucek9** [comment]
I can't reproduce first issue, second confirmed

**Comment by Pucek9** [comment]
Mapping I got on `https://dev-com-19.accdemo.b2c.ydev.hybris.com:9002/rest/v2/electronics-spa/users/current/carts/00000246/payment/sop/request?responseUrl=sampleUrl&lang=en&curr=USD` 

```
  "entry" : [ {
         "key" : "hybris_billTo_country",
         "value" : "billTo_country"
      }, {
         "key" : "hybris_card_expiration_year",
         "value" : "card_expirationYear"
      }, {
         "key" : "hybris_combined_expiry_date",
         "value" : "false"
      }, {
         "key" : "hybris_sop_decision",
         "value" : "decision"
      }, {
         "key" : "hybris_card_expiry_date",
         "value" : "card_expirationDate"
      }, {
         "key" : "hybris_card_expiration_month",
         "value" : "card_expirationMonth"
      }, {
         "key" : "hybris_billTo_street1",
         "value" : "billTo_street1"
      }, {
         "key" : "hybris_sop_card_number",
         "value" : "card_accountNumber"
      }, {
         "key" : "hybris_sop_uses_public_signature",
         "value" : "true"
      }, {
         "key" : "hybris_card_cvn",
         "value" : "card_cvNumber"
      }, {
         "key" : "hybris_billTo_lastname",
         "value" : "billTo_lastName"
      }, {
         "key" : "hybris_sop_subscriptionID",
         "value" : "paySubscriptionCreateReply_subscriptionID"
      }, {
         "key" : "hybris_billTo_firstname",
         "value" : "billTo_firstName"
      }, {
         "key" : "hybris_sop_amount",
         "value" : "amount"
      }, {
         "key" : "hybris_sop_currency",
         "value" : ""
      }, {
         "key" : "hybris_card_type",
         "value" : "card_cardType"
      }, {
         "key" : "hybris_sop_reason_code",
         "value" : "reasonCode"
      }, {
         "key" : "hybris_sop_public_signature",
         "value" : "paySubscriptionCreateReply_subscriptionIDPublicSignature"
      }, {
         "key" : "hybris_separator_expiry_date",
         "value" : ""
      }, {
         "key" : "hybris_account_holder_name",
         "value" : "mockup_account_holder"
      }, {
         "key" : "hybris_card_number",
         "value" : "card_accountNumber"
      }, {
         "key" : "hybris_billTo_phone_number",
         "value" : ""
      }, {
         "key" : "hybris_billTo_city",
         "value" : "billTo_city"
      }, {
         "key" : "hybris_billTo_region",
         "value" : ""
      }, {
         "key" : "hybris_billTo_postalcode",
         "value" : "billTo_postalCode"
      } ]
```
There is no default payment position, I don't know how to apply it to request.

**Comment by Xymmer** [comment]
Looks like OCC can't do default payment because of use of SOP request, I just saw a chat between OCC guys. so using a second request is all we can do for the moment.

**Comment by WeizhengSap** [comment]
There is `defaultPayment` flag in `SopPaymentDetailsWsDTO`. So, when SPA sends the second request `/{cartId}/payment/sop/response`, this flag is passed to backend.

I tested this ticket on my local. The `create payment details` needs to send 2 requests, which may take several seconds to finish. So, I click the button, and I didn't see the response, then I click again. In the "My account", I can see 2 copies of the payment info. So, I think, we should disable the button until the requests complete to prevent the double click.

For the second issue, in `occ-checkout-payment.adapter.ts`, add this line (line 65): 
```
fromPaymentProvider['defaultPayment'] =paymentDetails.defaultPayment;
```
after this `fromPaymentProvider['savePaymentInfo'] = true;`

**Comment by KateChuen** [comment]
Tested on dev19. Works now.
