### ISSUE TITLE
Automate deploying spartacussampledataaddon to github

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2839]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  
- Browser: 
- OS: 
- Device: 
- Other environment details:

**Comment by marlass** [comment]
Done with #5840
