### ISSUE TITLE
Fix image sizes on Beautacus

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#2841]
Some images on the Beautacus store are extremely large. Reduce their size.

**Comment by WeizhengSap** [comment]
Where is the PR?

**Comment by RadhepS** [comment]
Sorry about that, thought I posted it.

PR: https://stash.hybris.com/projects/C3PO/repos/beautystore/pull-requests/8/overview

**Comment by KateChuen** [comment]
Tested on dev2. 
The image size is ok now. Sure, they are not all the same size, but they are no longer hugely disproportionate. 
![paginationBeauty2](https://user-images.githubusercontent.com/45409515/59038202-a3dd8900-8840-11e9-821d-ec850af730e5.png)

And on pdp, it's not aligned properly. But that will be fixed later.
