### ISSUE TITLE
Switch to using RegistrationOptions [ang8 only]

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#285]
In [this PR](https://github.com/angular/angular/pull/26002) angular is preparing to expose `RegistrationOptions`.

Instead of using a clunky import `ɵangular_packages_service_worker_service_worker_b as RegistrationOptions` (see #197 ), we will be able to just use `RegistrationOptions` as soon as the linked PR is merged.

**Comment by Xymmer** [comment]
what release of angular is their change for? maybe this is in the future bucket?

**Comment by znikola** [comment]
It doesn't say for which version, but the PR seems to be done.
Regardless, it can be moved to next bucket, I will periodically check the state of the PR.

**Comment by Xymmer** [comment]
also requires angular 7

**Comment by znikola** [comment]
Angular team will probably NOT port this to Angular 7, it's only available for Angular 8.
See https://github.com/angular/angular/pull/26002#issuecomment-492360922

**Comment by Platonn** [comment]
Will be done in #2482
