### ISSUE TITLE
Fix e2e language tests

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/cloud-commerce-spartacus-storefront#2850]

**Comment by mszczepaniak** [comment]
![2019-06-04 12_03_33-storefrontapp-e2e-cypress](https://user-images.githubusercontent.com/4272069/58871959-4bcd4800-86c3-11e9-9472-6267ae85cb72.png)

**Comment by giancorderoortiz** [comment]
ran several times with browser visible and headless. Test successful 🆗
