### ISSUE TITLE
No footer links on the mobile

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#2852]
Links are missing in the footer on the mobile:
![image](https://user-images.githubusercontent.com/788092/58874598-83d78980-86c9-11e9-8e1d-1a6e9ad9ed01.png)

**Comment by mirkosoft** [comment]
For the Server QA apart from the footer please also check other dropdown menus work fine (desktop and mobile)

**Comment by giancorderoortiz** [comment]
Test successful 🆗 
- Tested on iPhone7 (chrome, safari), iPadPro (chrome, safari), Chrome Desktop breakpoint simulator in dev-tools. 👍 
- footer links available.
