### ISSUE TITLE
Navigation dropdown not loosing focus on other click [desktop only]

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#2853]
## Steps to Reproduce
* Open any navigation dropdown by clicking (not just hovering; to put a focus on it) on the opening link for example this one ("Digital camertas"):
![image](https://user-images.githubusercontent.com/788092/58875364-99e64980-86cb-11e9-9985-ed2be1fbf35b.png)
* open adjacent one by just hovering ("brands" in this case):
![image](https://user-images.githubusercontent.com/788092/58875504-02352b00-86cc-11e9-9128-e1bb640a2ac7.png)

## Observed Results
Menus are overlapping

## Expected Results
Previous menu ("Digital camertas" in this case - the one with focus) should close when new dropdown is opened.

**Comment by Zeyber** [comment]
Waiting for #3275 merge to check if it fixes a potential ui issue

**Comment by Zeyber** [comment]
QA Steps:
1. Hover navigation items and check dropdown works
2. Click a navigation item, should dropdown
3. Hover another navigation item, that item should now dropdown and clicked should not be dropped down anymore
4. Move mouse away from all navigation items, last clicked/hovered item should stay dropped down
5. Click outside navigation items, dropdown should disappear

**Comment by KateChuen** [comment]
Tested on dev2. 

- [x] Hover navigation items and check dropdown works
- [x] Click a navigation item, should dropdown
- [x] Hover another navigation item, that item should now dropdown and clicked should not be dropped down anymore
- [x] Move mouse away from all navigation items, last clicked/hovered item should stay dropped down 
-> Last clicked nav item stays open.
-> But if hovered, it closes when we move away from it (which is ok).

- [x] Click outside navigation items, dropdown should disappear
