### ISSUE TITLE
Selected filters on search result page reset after selecting a page form the pagination

### ISSUE THREAD

**Issue by MMerwar** [SAP/cloud-commerce-spartacus-storefront#2857]
## Environment Details

- Spartacus:  0.1.0-alpha.6
- Browser: Chrome / v74
- OS: Windows 10
- Device: Laptop
- Other environment details: Angular CLI 7.3.9, Angular 7.2.15, Node 10.16.0, yarn 1.16.0

## Steps to Reproduce

- Enter "power" into the search bar
- Go to the search result page
- Select the filters Stores:Chiba and Stores:Choshi
- Select page 2 at the pagination

## Observed Results

The second page of the search results will be shown, but the filters have been reset and the shown number of results is the number of results before I selected a filter.

## Expected Results

The second page of the search results should be shown with the selected filters and the shown number of search results also should not change.

## Repository Used

- Release 0.1.0-alpha.6
- Branch "develop" / commit: 154e6bcc52b682bdebdf37cc18a14093aded1d17 

## Offer to Fix

No (Angular knowledge not good enough yet)

## Additional Information
-

**Comment by Xymmer** [comment]
this was fixed before, but it's back (GC also saw this)

**Comment by giancorderoortiz** [comment]
Selected facets no longer disabled during pagination. 🆗 
Same amount of search results is kept throughout pagination process. 🆗
