### ISSUE TITLE
Beautacus: Cannot add product from pdp

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2858]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Search for lipsticks for eg.
On plp, you see that there's "Add to cart" button and you're able to add to cart. 
Click on the first product on plp for eg. 

**Actual Result**
On pdp, it shows out of stock.
![beautyPdp](https://user-images.githubusercontent.com/45409515/58887297-5da6ef00-86b3-11e9-97bd-104e960266e8.png)

Same product On plp:
![beautyPlp](https://user-images.githubusercontent.com/45409515/58887345-757e7300-86b3-11e9-8370-a06d337683c1.png)

**Comment by RadhepS** [comment]
PR: https://stash.hybris.com/projects/C3PO/repos/beautystore/pull-requests/9/overview

**Comment by WeizhengSap** [comment]
Changes was merged to the new github repo.

**Comment by KateChuen** [comment]
Tested on dev2. Able to add product to cart from pdp now.
![pdpBeautyAddCart1](https://user-images.githubusercontent.com/45409515/59124371-73bfe400-892d-11e9-8062-85ef114b91ef.png)
![pdpBeautyAddCart2](https://user-images.githubusercontent.com/45409515/59124373-74587a80-892d-11e9-9e40-ae461cea2565.png)
