### ISSUE TITLE
[retest] Store finder page displays only title and image

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2861]
For dev17 backend, open `/store-finder` page. Then the apge displays only the title and image.

![obraz](https://user-images.githubusercontent.com/4001059/58888037-01f65900-86e7-11e9-8cb4-03f49405ec6f.png)

**Comment by Xymmer** [comment]
let's go to notfound for now

**Comment by developpeurweb** [comment]
This may or no be related to this other ticket GH-2255

**Comment by developpeurweb** [comment]
![Screen Shot 2019-06-04 at 11 08 46 AM](https://user-images.githubusercontent.com/15113219/58892197-cb571900-86bb-11e9-875d-c064cc2e354b.png)

**Comment by Xymmer** [comment]
we need to remove the label from the backend for now

**Comment by KateChuen** [comment]
"Find a store" link has been removed. Navigating to its url gives a 404 page. See ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2805 for more details.
