### ISSUE TITLE
404 on Order Confirmation & Order Details Page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2867]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login
Place an order

**Actual Result**
On Order Confirmation Page, it displays 404. 
![orderConfirmation](https://user-images.githubusercontent.com/45409515/58897746-01e66100-86c7-11e9-89a7-794d591e2883.png)

**Comment by marlass** [comment]
I changed the label for that page. From the screenshot, I see that it is about `dev-com-2` server. I did the changes on `dev-com-17` and updated `spartacussampledataaddon`, when I merged PR. My guess is that `dev-com-2` wasn't updated with newest addon.

**Comment by KateChuen** [comment]
Tested on updated dev2 today. Not an issue anymore.

**Comment by KateChuen** [comment]
Is the issue back? Seeing this on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com
