### ISSUE TITLE
[retest] Bug: Can't register a new account using Safari

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#287]
## Steps to repro:

- Une Safari
- Go to the registration page
- Leave the "Title" drop down untouched to use the default value 'Ms'
- Fill all the other fields appropriately.

## Expected result:
- The register button is enabled to allow me to register

## Observed results:
- The register button is still disabled.
- If I change the value in the "Title" field drop down list, the register button is then enabled.

<img width="628" alt="register-button-disabled" src="https://user-images.githubusercontent.com/7065346/48501049-3a494f00-e80a-11e8-87ea-fbf6baf1790f.png">

**Comment by Xymmer** [comment]
On Chrome the title menu is blank until you select one, I guess Safari is handling that differently.
I want to make salutation optional but until backend is fixed we're stuck with it.

**Comment by Xymmer** [comment]
assigning to myself for now, as i want to get the backend changed

**Comment by mirkosoft** [comment]
Can't reproduce as on register page load the title dropdown is not set:
![image](https://user-images.githubusercontent.com/788092/56727856-d714fe80-6751-11e9-9b1a-5b0e471c8c82.png)
so you have to choose smth and whatever you choose new account can be created. Tested here: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Comment by Xymmer** [comment]
retested, works
