### ISSUE TITLE
Changing language makes each cms component re-loaded

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#2870]
After changing language, instead of reloading all cms components, the cms page should be reloaded.

**Comment by WeizhengSap** [comment]
QA step:
In homepage, change language, make sure there is no cms component loaded in "network".

**Comment by giancorderoortiz** [comment]
fix not yet seen on dev-com17 (June 17 @ 2:15 pm EST)

**Comment by giancorderoortiz** [comment]
Saw significant reduction in dev-com2. 
ccv2: 58/96
dev-com2 6/51

![after-dev-com2](https://user-images.githubusercontent.com/46171897/59629146-33701b00-9110-11e9-8483-4b3de67e7044.png)
![before-ccv2](https://user-images.githubusercontent.com/46171897/59629148-33701b00-9110-11e9-9df0-c9e358a2724e.png)
