### ISSUE TITLE
Bug: Registration navigates away from the storefront.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#288]
## Steps to Reproduce

- Point your browser to a different web site than the storefront, for example www.google.com.
- From there, paste the registration page in your browser's bar
- Fill the registration for appropriately and then press the register button.

The way I accidentally stumbled on this issue is: While on the registration page, I went in Chrome's settings to clear the browsing data before registering.  Upon clicking the register button, I was taken back in the Chrome settings.

## Expected Results

- Registration is a success and I enter the storefront as an authenticated user.

## Observed Results

- I'm redirected back to www.google.com.
- If I manually head back to the storefront, looks like I'm properly registered and authenticated.  The redirection logic seem to be at fault.

**Comment by Xymmer** [comment]
Before delving too much into this one, ask Krzys if his routing work affects/solves/causes this problem.
