### ISSUE TITLE
Restyle header as a result of ng-bootstrap removal

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#2880]
Realign, add paddings and margins to header elements.

![Screen Shot 2019-06-04 at 10 02 37 AM](https://user-images.githubusercontent.com/15113219/58906684-770f6180-86da-11e9-9e50-f5695d269604.png)

**Comment by KateChuen** [comment]
Not sure how the header should look like now. But now I see this: #2907 
@Xymmer Please take a look.
