### ISSUE TITLE
Move cms config of ProductDetailsTabComponent to ProductDetailsTabModule

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2896]
Currently `ProductDetailsTabComponent`:
- has the `cmsComponents` config defined `ProductTabsModule`, 
- but is declared in the `ProductDetailsTabModule`

We should move the config to the `ProductDetailsTabModule` module.

**Comment by Platonn** [comment]
QA steps: smoke testing around PDP. Especially tabs

**Comment by giancorderoortiz** [comment]
Smoke test successful 🆗
