### ISSUE TITLE
New application without (optional) base href is failing

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2903]
Whenever a brand new application is created without a base href specified throws a blocking error:
`Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.`

There are 2 workarrounds to solve this:
- add the base href to the `index.html` (`<base href="" />`)
- add the base href provider in the application module (`{provide: APP_BASE_HREF, useValue: '/'}`)

**Comment by znikola** [comment]
The `<base href>` is required: https://angular.io/guide/deployment#the-base-tag
However, there's a third option: https://github.com/angular/angular-cli/wiki/angular-cli
```json
...
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "baseHref": "/",
...
```
