### ISSUE TITLE
[HOLD] Category Link in header nav is cut (TBD)

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2907]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
The last category nav link doesn't fit properly in the header.
Maybe it's already fixed...

<img width="1439" alt="headerCut" src="https://user-images.githubusercontent.com/45409515/58966134-b93eae80-877f-11e9-834c-532f92388b50.png">

**Comment by Xymmer** [comment]
on purpose? they shortened the number of categories, but we don't spill to a second line anymore? @vekterdude

**Comment by hackergil** [comment]
We have less categories now so it looks better. If the client decides to have more categories this is still an issue. @Xymmer let us know what you want to do with this one

**Comment by Xymmer** [comment]
closing as we support just one line and customers either must show less or fix it to 2, for now. we'll get feedback on how to improve this.
