### ISSUE TITLE
Spartacus with angular 8 does not work with a shell app

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#2911]
I tried to deploy the latest spa on dev17. It compiles and starts fine but we don't get a response from the server.

**Comment by giancorderoortiz** [comment]
There are no warnings nor error messages in server console either

**Comment by marlass** [comment]
Here is a fix for it: https://stash.hybris.com/projects/C3PO/repos/spartacus-installation/pull-requests/27/overview

One thing was that we changed our main module from `StorefrontModule` to `B2cStorefrontModule`.

Other issue is that new cli sets the target to `es2015` and spartacus currently doesn't work with it in production mode. Develop mode works tho. Temporary I added template `tsconfig` with old `es5` target set.

Also updated dev-com-17 with this fix and it works.

I will add a note to docs about changing the generated target from `es2015` to `es5`.

**Comment by marlass** [comment]
@gladius-mtl Changes to docs in `feature/GH-2911` wiki branch.
- Renamed `StorefrontModule` to `B2cStorefrontModule`
- Changed info about translations to import from new library `@spartacus/assets`
- Added paragraph about `es5` target in `tsconfig.json` required for Spartacus to work properly.

**Comment by Xymmer** [comment]
i updated the spartacus setup docsc to include a section on using incremental libraries with angular 8 (bottom of https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Building-the-Spartacus-Storefront-from-Libraries)
