### ISSUE TITLE
load baseSites only in smartedit mode

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#2912]
BaseSites data is only used in smartedit. So, it would not be used / loaded when we're in ordinary browsing mode, but only in smartedit mode

**Comment by WeizhengSap** [comment]
To code reviewer/QA:
1. open SPA, check "network" in browser, make sure there is no`basesites` request sent; or check "redux", the baseSite details data is empty.
![Screen Shot 2019-06-05 at 1 08 02 PM](https://user-images.githubusercontent.com/44440575/58975537-358ebd00-8793-11e9-9b69-7100b3bcfc3c.png)
2. open SPA in smartedit, check "network" in browser, you should see one 'basesites' request sent; and open "redux", the baseSite details has data.

**Comment by KateChuen** [comment]
Tested on dev2. 
- On SPA, no more basesites request sent.
- SPA in Smartedit sends 1 basesites request only.
![basesiteSE](https://user-images.githubusercontent.com/45409515/59057195-dcdd2400-8867-11e9-936a-1ec9b2b782a7.png)
