### ISSUE TITLE
[HOLD] Order Details: have a myAccount:orderDetails.deliveryStatus displayed

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2917]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login
Add Item to cart
Place an order
Go to Order History
Click on an order
There's a "[myAccount:orderDetails.deliveryStatus]" displayed.

Maybe something recently changed and I need to update my backend... 

<img width="1049" alt="deliveryStatusOrderDetails" src="https://user-images.githubusercontent.com/45409515/58981313-26623c00-87a0-11e9-8ee2-cb60e9e287b3.png">

**Comment by Xymmer** [comment]
@Pucek9 could you comment if this is a bug or we're likely to see this fixed in an updated server?

**Comment by KateChuen** [comment]
Does not happen anymore.
