### ISSUE TITLE
Cannot access address book

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2918]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login
Go to MyAccount -> Order History for eg
then MyAccount -> AddressBook 

**Actual Result**
The previous page's header is still displayed, but with no data.

Error in console

> AddressBookComponent.html:2 ERROR TypeError: Cannot read property 'length' of null
    at Object.eval [as updateDirectives] (AddressBookComponent.html:3)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:36043)
    at checkAndUpdateView (core.js:35055)
    at callViewAction (core.js:35421)
    at execComponentViewsAction (core.js:35349)
    at checkAndUpdateView (core.js:35062)
    at callViewAction (core.js:35421)
    at execEmbeddedViewsAction (core.js:35378)
    at checkAndUpdateView (core.js:35056)
    at callViewAction (core.js:35421)
View_AddressBookComponent_0 @ AddressBookComponent.html:2
proxyClass @ compiler.js:19199
logError @ core.js:36330
handleError @ core.js:7239
(anonymous) @ core.js:32080
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:30818
tick @ core.js:32077
(anonymous) @ core.js:31915
invoke @ zone-evergreen.js:359
onInvoke @ core.js:30892
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
run @ core.js:30757
next @ core.js:31912
schedulerFn @ core.js:27834
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:27796
checkStable @ core.js:30835
onLeave @ core.js:30953
onInvokeTask @ core.js:30876
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1629
AddressBookComponent.html:2 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 2, nodeDef: {…}, elDef: {…}, elView: {…}}

<img width="1274" alt="addressBook" src="https://user-images.githubusercontent.com/45409515/58982074-a3da7c00-87a1-11e9-94f3-a4527e5caaa7.png">

**Comment by giancorderoortiz** [comment]
I don't see a fix yet for this issue on dev-com17 which was updated today. (June 6 10 am EST).
However, I see a fix in ccv2 env, whose deployed code is a bit older.

**Comment by giancorderoortiz** [comment]
Saw a fix on dev-com6 with deployment on June 6 11am EST. 
Test successful 🆗
