### ISSUE TITLE
Dropdown content is overlapped by global message

### ISSUE THREAD

**Issue by Matejk00** [SAP/cloud-commerce-spartacus-storefront#2922]
Every dropdown wrapper is overlapped by global message. Probably it's z-index problem.

![example-1](https://user-images.githubusercontent.com/6958810/59016447-865cef00-8841-11e9-9136-c374e98932e9.png)

**Comment by giancorderoortiz** [comment]
I don't see a fix yet in dev-com17.  Same as before. 🆖 
Deployed different server dev-com6. Still same issue 🆖

**Comment by KateChuen** [comment]
Tested on dev2. Works now.
![menuOverlay](https://user-images.githubusercontent.com/45409515/59054612-0b580080-8862-11e9-8845-b3953128389e.png)
![menuOverlay2](https://user-images.githubusercontent.com/45409515/59054613-0b580080-8862-11e9-8cdc-4d11b4982dfb.png)
