### ISSUE TITLE
typo in normalizer name CMS_PAGE_NORMALIZE

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2924]
Rename injection token `CMS_PAGE_NORMALIZE` -> `CMS_PAGE_NORMALIZER`

**Comment by KateChuen** [comment]
Is that something we can test? If so, how?

**Comment by Platonn** [comment]
It's just a typo fix. App should just work just like before - smoke e2e covers that.

**Comment by KateChuen** [comment]
Smoke test done!
