### ISSUE TITLE
Add support for TabPanelContainer, used in Apparel

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2928]
to be defined, Miro to add screenshots
we could probably re-use existing Spartacus tab component

**Comment by mirkosoft** [comment]
See the difference in `components: "ProductDetailsTabComponent ProductSpecsTabComponent ProductReviewsTabComponent deliveryTab"` vs `components: "TabPanelContainer"`

Electronics:
![image](https://user-images.githubusercontent.com/788092/59030002-009c6c00-8860-11e9-8c11-3432f3ffad2b.png)

Apparel:
![image](https://user-images.githubusercontent.com/788092/59030238-b5368d80-8860-11e9-8c2c-c4cd73307e25.png)

**Comment by Xymmer** [comment]
for now spartacus will ignore the errors produced by the fact that we don't yet support that component
