### ISSUE TITLE
unsafe scripts warning when starting smartedit

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#293]
From Olga: For SmartEdit support, we need to address security concerns on how SPA handles the preview ticket and enables the webApplicationInjector script. The webApplicationInjector script is needed part of the SmartEdit contract, but it should not be enabled on a production website.

Another approach would be to not use preview ticket in OCC call, Tobias to follow up with SmartEdit team on viability of that approach.

SmartEdit team is also looking into this - see CMSX-7969.

**Comment by WeizhengSap** [comment]
backend PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/44/overview

**Comment by WeizhengSap** [comment]
To reviewer/QA:

To run spa, using: `npm run start:ssl`. This will make SPA running using HTTPS.
In smartedit, open "homepage", you should not see the warning.

**Comment by bgambocjaviniar** [comment]
Removing myself as reviewer because I do not have access to stash due to my account being deactivated. I'll do the other one since it only requires the frontend and not the backend changes

**Comment by LTiger14** [comment]
No warning in SmartEdit and it's working 😉
