### ISSUE TITLE
Failing E2E: Update Password

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#2931]
regression/update-password.e2e-spec.ts is failing on Jenkins.

 - /data/jenkins/jobs/spartacus-regression-tests/workspace/projects/storefrontapp-e2e-cypress/cypress/screenshots/regression/update-password.e2e-spec.ts/My Account - Update Password -- when a user is authenticated -- should cancel bring back to the home page (failed).png (1280x720)

**Comment by RadhepS** [comment]
Placing ticket back because I need to complete some tasks for Beautacus. Will come back to it after if it hasn't been done yet.

**Comment by plabadie** [comment]
Can't repro running against dev17.  I'll keep an eye on the next report  ( last one ran while the backend was down so all the tests failed. )

<img width="747" alt="updatepwdspec" src="https://user-images.githubusercontent.com/7065346/59128545-55abb100-8938-11e9-89fa-18602e33b8d6.png">

**Comment by plabadie** [comment]
Test still passes on the nightly run.  No fix required for now.

Still, I pushed a PR to move the change password e2e test with the others "My Account" tests.

PR #3022
