### ISSUE TITLE
Pagination does not change pointer on hover

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#2933]
When mouse is over a valid page number in pagination, the mouse cursor should change to pointer to indicate that the button is clickable.

**Comment by KateChuen** [comment]
Tested on dev17. Mouse cursor changes to pointer on pagination now.
![pointerPagination](https://user-images.githubusercontent.com/45409515/59111784-bd99d180-890f-11e9-9a97-255e941a8af2.png)
