### ISSUE TITLE
Beautacus: No result displayed if we navigate to other categories from 2nd page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2934]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/beauty/en/USD/

**Steps to Reproduce**
Go to "Face Powders" Category. 
On the plp, go to the 2nd page. 
Now from there, click on the "Lipsticks" Category. 

**Actual Result**
It looks like there's no result returned. But if you look at the facets, there are some results returned. 
![paginationBeauty](https://user-images.githubusercontent.com/45409515/59036827-0b460980-883e-11e9-88a3-4b4f2993ecd0.png)

If you go back to "Face Powders" Category, and go back to the first page in the result plp. 
Then go to Lipsticks Category, then it works, and you get 10 results returned. 
![paginationBeauty2](https://user-images.githubusercontent.com/45409515/59036816-06815580-883e-11e9-9c81-2d8479b31aed.png)

**Comment by Xymmer** [comment]
won't work on beautacus anymore
