### ISSUE TITLE
Fix error that displays when logging in and refreshing page

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#2937]
How to reproduce:

1. Log in sucessfully
2. Refresh the page

![Screen Shot 2019-06-06 at 10 54 13 AM](https://user-images.githubusercontent.com/34665674/59043012-78ab6780-8849-11e9-9007-965d5b8e4bf8.png)

**Comment by KateChuen** [comment]
Tested on dev17. No more "base site" error displayed now.
But on dev2 (which i believe is more recent), the user gets logged out upon refreshing the page.

**Comment by KateChuen** [comment]
Local pointing to dev2 works. 
I'll close this one, since it doesn't display any error anymore.
I'll open a new ticket to check if it's also happening on other servers in the next couple of days or to retest on this server after we update.
