### ISSUE TITLE
Beautacus: Order Confirmation notFound 

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2938]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/beauty/en/USD/

**Steps to Reproduce**
Place an order

**Actual Result**
On the order confirmation page, it's the not-found page displayed. 

![beautyOrderConfirmation](https://user-images.githubusercontent.com/45409515/59043267-ec4d7480-8849-11e9-93a5-c9c4b010673b.png)

**Comment by Xymmer** [comment]
Won't wokr on beautacus anymore
