### ISSUE TITLE
Store the SmartEdit preview token, include it in all OCC CMS calls, add contracts

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#294]
Dependency on CMSX-7968 and after #493 and #517

Spartacus must store the SmartEdit preview token and include it in all the backend calls to OCC.
Some info here: https://wiki.hybris.com/display/CxM/SmartEdit+Support+for+Spartacus

> Tobias: I was thinking of passing it as a query param, similar to what we currently do for the accelerator storefront. for example:
> - https://localhost:9002/yacceleratorstorefront?site=electronics&cmsTicketId=123456
> - http://localhost:4200?cmsTicketId=123456

- receive preview token
- where do we store it
-- Should be very similar to language interceptor
-- Put it somewhere in ngrx store, use language interceptor as example

-------------------
- create http interceptor in occ module, add it to each call 
should not always be running, should not run on public available site

----
Pages/slot/component contracts was added in this ticket

QA:
- In SmartEdit, no console errors
- In SmartEdit, you see the slots you can see the highlights when you point at cms components
- Cannot edit yet

**Comment by WeizhengSap** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/667
