### ISSUE TITLE
Language: MyAccount menu doesn't get reloaded back to EN

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2940]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login
Change the language to Japanese for eg.
Hover on "MyAccount" 
Change the language . back to English
Hover on "MyAccount"

**Actual Result**
MyAccount menu did not get reloaded

![langMyAcc](https://user-images.githubusercontent.com/45409515/59047176-61707800-8851-11e9-8278-717500bac167.png)

**Comment by marlass** [comment]
Checked on dev-com-17. Everything is working correctly. User menu is reloaded in the correct language.
Can someone confirm?

**Comment by KateChuen** [comment]
Retested on ccv2, doesn't happen anymore. Can close this ticket.
