### ISSUE TITLE
Pagination Invalidates Selected Facets

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#2941]
**Steps to Reproduce:** 

1. Navigate to Spartacus storefront. 
2. Enter any search query such as "camera" and press enter
3. On product listing page (PLP), select any facets whose results are > 30. 
4. Paginate to next page. 

**Expected result:**
4. Same number of results are still in place, with facet selected, but in next page. 

**Actual results:**
4. Facet selection is cleared. Pre-faceting search results are displayed.

**Comment by Xymmer** [comment]
dupe of #2857
