### ISSUE TITLE
Refactor product (reference) carousel to be reusable for other carousels

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#2951]
The current product and reference carousels are copies and have quite unnecessary complex logic. The intend of the carousel is to be reusable. 

CDS needs to reuse this component, which is why we like to have this in the 1.0 release.

**Comment by tobi-or-not-tobi** [comment]
QA:
- validate that both product carousel (home page) and product reference component work as intended
- validate that carousels that do not need navigation will not show it (no prev / next and circle indicators)
- validate that the icons are build with `cx-icon` component

**Comment by KateChuen** [comment]
Tested on dev17.

- [X] validate that both product carousel (home page) and product reference component work as intended

- [X] validate that carousels that do not need navigation will not show it (no prev / next and circle indicators)
![carouselNoNav](https://user-images.githubusercontent.com/45409515/59115269-ef626680-8916-11e9-8e5e-15adce312f1b.png)

- [X] validate that the icons are build with cx-icon component
product carousel:
![productCarouselDev2](https://user-images.githubusercontent.com/45409515/59115331-11f47f80-8917-11e9-9280-f01f5e7497b4.png)

product reference:
![productReferenceDev2](https://user-images.githubusercontent.com/45409515/59116822-6816f200-891a-11e9-8075-731c2cebcdcd.png)
