### ISSUE TITLE
Change url for terms and conditions

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2955]
Currently we have a page label `/termsAndConditions` in backend, but for consistency with other routes we should use `-` to separate words. So let's change it to `/terms-and-conditions` in CMS and to `terms-and-conditions` in our `default-routing-config.ts`.

**Comment by marlass** [comment]
PR for addon https://github.tools.sap/cx-commerce/c3po-legacy-spartacussampledataaddon/pull/3

**Comment by giancorderoortiz** [comment]
Verification on dev-com17 fails. Currently getting 404. 

![Screen Shot 2019-06-18 at 11 54 33 AM](https://user-images.githubusercontent.com/46171897/59700026-94572c00-91c0-11e9-848a-fc8d071fd618.png)
![Uploading Screen Shot 2019-06-18 at 11.55.26 AM.png…]()

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-06-18 at 11 55 26 AM](https://user-images.githubusercontent.com/46171897/59700106-b05acd80-91c0-11e9-84ba-4a0fff389ba4.png)

**Comment by giancorderoortiz** [comment]
Retest successful on dev-com17. 
Terms and conditions page found in ../electronics-spa/en/USD/terms-and-conditions

![dev-com17-fix](https://user-images.githubusercontent.com/46171897/59707587-eacc6680-91d0-11e9-97f9-3b876a8e37ef.png)
![dev-com17tandc](https://user-images.githubusercontent.com/46171897/59707588-eacc6680-91d0-11e9-83c4-afbcb9ff8426.png)
