### ISSUE TITLE
Missing translation for add to home screen banner

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#2956]
This key is not used: `addToHomeScreenDescription`.
This key `addSapStorefront` is used in add to homescreen banner, but we don't have translation for it. Maybe `addToHomeScreenDescription` should be used there.

To preview the component you need to run app in pwa mode. (`yarn start:pwa`)

**Comment by KateChuen** [comment]
Tested on ccv2, on samsung 10+. (It did not work on iphone).
I do see "Add to Home". 
But am i supposed to see the translation in other languages? Or it's always in EN for now?

![f2ed630b-d7f3-47e6-9924-b93cbe2a824b](https://user-images.githubusercontent.com/45409515/59850862-3d289700-9339-11e9-829d-667eaf93f142.JPG)

The add to home dialog:

![9068d49e-c955-44d6-afe0-a8ffadf33630](https://user-images.githubusercontent.com/45409515/59850861-3d289700-9339-11e9-87e3-506a8fac5673.JPG)

**Comment by hackergil** [comment]
Currently we don't have translations for any other language than english. I was able to test this locally by creating mock translations for german

![add_to_home_de](https://user-images.githubusercontent.com/158500/59933250-16d92900-9417-11e9-8e8f-0ac8858d34c2.png)

**Comment by hackergil** [comment]
In order for us to be able to test this, we have to generate mock translations for any non-english language on a QA server.

**Comment by marlass** [comment]
The ticket was just about one translation key issue (different key in template and translations).
No need to check it for other languages. English check is enough to test it.

I saw that now all the texts are correctly translated and each translation key is used and translation for it is provided.
