### ISSUE TITLE
Add support for merchandising carousel component

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2961]
Merchandising carousel is used for displaying personalized product rereferences derived from CDS (Context Driven Services). See https://help.hybris.com/cds/latest/31de9a4b15d44755bcdba88713822aa6.html.

**Comment by znikola** [comment]
Done as part of https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5338, closing.
