### ISSUE TITLE
[closed with #4432] CartService.addEntry doesn't support consecutive calls

### ISSUE THREAD

**Issue by josecervera** [SAP/cloud-commerce-spartacus-storefront#2966]
## Environment Details

- Spartacus: alpha-0.8

Other details shouldn't be relevant

## Steps to Reproduce
Trying to implement a small component to add a list of products to the cart, we used a simple "forEach" product cartService.addEntry(productCode, quantity).

## Observed Results
The products are not added when there is more than one product in the list.

## Expected Results
All the products are added to the cart

## Offer to Fix
Not savy enough

## Additional Information
Looking at the cartService, it seems strange to have the internal callback function redefined every time.
Maybe the addEntry could return an observable, so the caller knows when to continue?
Ideally, implement a method addEntries, where you can provide a list of these tuples. Problem is OCC itself doesn't support this at the moment.

**Comment by WeizhengSap** [comment]
When adding the first product into cart, we need to check whether user's cart exist or not. If there is no cart, then the first thing is to create a new cart. After cart created, the product can be added. 

For a list of products, you have to wait the first product is really added (if there is no cart), before adding others. So, you can call `getActive()` which returns `Observable<Cart>`. Subscribe it, and if it has value, then that means the cart exist. So, the other products can be added.

**Comment by josecervera** [comment]
Thanks for the reply. But isn't this a bad abstraction from the client's point of view? Why does the client have to check if the cart exists or not, if it's going to be created for him? Wouldn't it make sense to return Observable<Cart> also for the addEntry call?

**Comment by jpsierens** [comment]
+1 for adding an observable to the `addEntry` method, this way we can know when the entry has been added in order to add more products

Or just add support for adding multiple products at once, e.g. `addEntries()`

**Comment by marlass** [comment]
API of the function did not change.

Calls are now queued in effects and cart loading/creation happens only once if the cart does not exist.

QA steps:
- try to add multiple entries to the cart at the same time
- verify that cart have everything you added

**Comment by Zeyber** [comment]
QA Check:
- Throttled Network
- Navigated to product list page
- Clicked `Add to Cart` on multiple items
- No requests cancelled in network log and no added items lost in checkout
