### ISSUE TITLE
Address Form Misaligned in other languages

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2972]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login
Add item to cart
Proceed to checkout
On Address form page, change the language to Japanese

**Actual Result**
The form is misaligned.
![addressFormJP](https://user-images.githubusercontent.com/45409515/59125465-6c4e0a00-8930-11e9-8b8c-3a1ae3dedf2d.png)

**Comment by mikelMHybris** [comment]
This looks like the data is the issue. I can make the text wrap like this. But the english/shorter text will wrap strange.
<img width="842" alt="Screen Shot 2019-06-12 at 12 40 00 PM" src="https://user-images.githubusercontent.com/30266610/59369909-6e88dd80-8d0f-11e9-9584-fc93b865f234.png">
<img width="777" alt="Screen Shot 2019-06-12 at 12 40 39 PM" src="https://user-images.githubusercontent.com/30266610/59369910-6e88dd80-8d0f-11e9-9ffa-c3e3340aded5.png">

**Comment by developpeurweb** [comment]
@Xymmer can we have your feedback on this one. It seems unlikely to fit horizontally, this seems like something the client will have to customize depending on their i18n/l10n ... should we ask Manu for alternatives?

**Comment by Xymmer** [comment]
whoops i shouldn’t have let that one go through, i’m closing as won’t fix. sorry about that.

the reason it goes too wide is because thekeycode is displayed, but in regular usage a space or 2 will appear and it won’t do that.
