### ISSUE TITLE
User gets logged out after refreshing the page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2973]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login
Refresh the page

**Actual Result**
The user is logged out.

-> To verify on dev2 after we update again in the next couple of days.
-> To verify on other servers after they get updated in the next couple of days

Because right now, it only happens on 
dev2 frontend pointing to dev2 backend

Doesn't happen on
local, pointing to dev2 backend
dev17 frontend&backend

**Comment by Xymmer** [comment]
there's also #2981, refresh and lose cart

**Comment by marlass** [comment]
Dev-com-2 doesn't work. On dev-com-17 the issue doesn't exist.
Waiting for server to be back online.

**Comment by KateChuen** [comment]
Doesn't happen on ccv2. Can close this ticket.
