### ISSUE TITLE
Category navigation isn't working

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#2980]
* Most of elements in the category dropdown appears as heading (not clickable):
![image](https://user-images.githubusercontent.com/788092/59159903-61ca7680-8ad0-11e9-8a01-e37a67b08664.png)
* those clickable ones (clicked "belts" from the above picutre) responses with 400 error:
`{
      "message" : "The value provided is not allowed.",
      "reason" : "invalid",
      "subject" : "code",
      "subjectType" : "parameter",
      "type" : "ValidationError"
   }`

**Comment by tobi-or-not-tobi** [comment]
QA:
- confirm apparel header navigation is working properly
- confirm all brand links are listed in columns (max 10 shown)
- confirm the max number of items listed can be controlled in cms (using the `wrapAfter` property)

**Comment by KateChuen** [comment]
Tested on dev19 on apparel-de.
The header navigation works now. 
<img width="990" alt="Screen Shot 2019-06-13 at 4 25 57 PM" src="https://user-images.githubusercontent.com/45409515/59465156-4032fd00-8df8-11e9-85b0-238c884795a1.png">

However, when clicking on them, the search result is weird.
<img width="989" alt="Screen Shot 2019-06-13 at 4 25 12 PM" src="https://user-images.githubusercontent.com/45409515/59465200-5476fa00-8df8-11e9-819a-2863a2c0e2ae.png">

Brand links are listed in columns. 
<img width="988" alt="Screen Shot 2019-06-13 at 4 24 12 PM" src="https://user-images.githubusercontent.com/45409515/59465162-43c68400-8df8-11e9-9834-51b9f7f6580e.png">

Could not verify changing the max number.

**Comment by KateChuen** [comment]
Tested changing the max number to 5:
![Screen Shot 2019-06-14 at 8 52 19 AM](https://user-images.githubusercontent.com/45409515/59510490-ccd5cd80-8e81-11e9-871b-3026610a670e.png)
