### ISSUE TITLE
cart page: proceed to checkout falls to 2 lines

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2982]
should be wide enough to fit on one
![image](https://user-images.githubusercontent.com/4998145/59165681-8719ad80-8aed-11e9-8e6e-7e5e2fbd7b90.png)

**Comment by developpeurweb** [comment]
**Server QA:** this happened when we had a short product name.
Choose a product with a short name (ex. 1298094) > Add to Cart > View Cart

**Comment by KateChuen** [comment]
Tested on dev2, it's fixed now.
![Screen Shot 2019-06-17 at 9 56 06 AM](https://user-images.githubusercontent.com/45409515/59609843-2a6a5400-90e6-11e9-8201-569c39b49c7e.png)

**Comment by KateChuen** [comment]
Actually, i just noticed that it's still happening for products without images, for eg: 1992697

![Screen Shot 2019-06-17 at 1 04 41 PM](https://user-images.githubusercontent.com/45409515/59623021-1aac3900-9101-11e9-801b-ae4378dbc409.png)

**Comment by KateChuen** [comment]
Tested on dev2. It's fixed now.
<img width="951" alt="Screen Shot 2019-06-20 at 2 01 57 PM" src="https://user-images.githubusercontent.com/45409515/59870720-0c118c00-9364-11e9-8dc2-127292eaccd6.png">
