### ISSUE TITLE
[still happening?] Duplicated calls for cms pages

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#2984]
While opening category page or product page in the network tab you can see `/pages` endpoint is called twice:
![image](https://user-images.githubusercontent.com/788092/59178767-40b16680-8b60-11e9-8788-f80a4fc456a4.png)

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3096

**Comment by tobi-or-not-tobi** [comment]
@WeizhengSap @mirkosoft I'm still able to reproduce this (or similar) behaviour locally, using latest development branch.

**Comment by dunqan** [comment]
QA steps:
check in network tab for dubplicate page loads
When entering home page there should be only one request for page (two entries in network tab, one for OPTIONS and one GET)

**Comment by giancorderoortiz** [comment]
Test successful. Two calls seen as specified in qa steps (dev-com17) 🆗 
Public server has 5 cms calls. 

![pageload-homepage](https://user-images.githubusercontent.com/46171897/60028125-c6f39f80-966c-11e9-88d8-073356c0370b.png)
![pageload-pdp](https://user-images.githubusercontent.com/46171897/60028126-c6f39f80-966c-11e9-9bec-6814d4f287dc.png)
