### ISSUE TITLE
Use WinRef in product intro component

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2990]
In `ProductIntroComponent` we use implicit global `document` which breaks SSR. Instead, we should use the `WindowRef` wrapper object and it's `document` property.

This is broken SSR view:
![obraz](https://user-images.githubusercontent.com/4001059/59190562-54b79100-8b7d-11e9-97e6-353fdee3b07a.png)

**Comment by KateChuen** [comment]
How to test this? We just to go any PDP page with SSR enabled?

**Comment by KateChuen** [comment]
Started dev2 with SSR by following these steps: 
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/current_drafts/ssr.md
Made sure there's no "service workers" in the browser's app (Application -> Service Workers)
Able to view pdp correctly.
![Screen Shot 2019-06-19 at 11 31 09 AM](https://user-images.githubusercontent.com/45409515/59779172-c9798200-9285-11e9-8f4b-b5405091e363.png)
