### ISSUE TITLE
Use WinRef in YotpoService to avoid breaking ssr

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2991]
In `YotpoService` we use the implicit global `document` which may break SSR. Instead, we should use the `WindowRef` wrapper object and it's `document` property.

**Comment by qjimmy** [comment]
**Muhammad: ** Fix ready. Waiting for access to generate PR.

**Comment by mazamcodes** [comment]
PR https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4753

**Comment by KateChuen** [comment]
QA Steps required please.
