### ISSUE TITLE
category title doesn't use i18n

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#2997]
in ProductListComponent there are some old code like
```data.pagination.totalResults + ' results for ' + this.categoryTitle;```
probably it's not used

**Comment by KateChuen** [comment]
How to test? Just make sure category title is displayed correctly? Should we check in other languages too?

**Comment by Pucek9** [comment]
> How to test? Just make sure category title is displayed correctly? Should we check in other languages too?

I think yes - ensure that category title is displayed as before

**Comment by giancorderoortiz** [comment]
Test ok
