### ISSUE TITLE
Spike refactor routes and configurability

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3]
The route configuration requires several enhancements:
- configurable routes – the routes are hardcoded, which means it cannot be customised
- localised routes – different languages or brands requires localised routes for the same route
- nested routes – only first-level routes are used with a single route outlet, we should consider nested outlets

**Comment by Platonn** [comment]
General investigation is done. Implementation will be in other tickets
