### ISSUE TITLE
Spike extending business logic

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#300]
and create tickets for asterix :)

info to come

**Comment by dunqan** [comment]
Doc input regarding components (and component's logic) extensibility was added here:
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/storefrontlib/src/lib/occ/docs/cms-component-implementation.md

**Comment by gladius-mtl** [comment]
Doc input looks good! Follow up doc ticket GH-764 created. 
Moving this ticket now to QA.
