### ISSUE TITLE
Global delay in seconds before hiding a message

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3005]
Set these defaults for messages:
- 3 seconds for confirmation and info
- 7 seconds for error

We'd love to hide the message when you go to another page, we'll do that in the future.

This change should go into release/beta as well as develop, so that we test with this configuration for messages.

![image](https://user-images.githubusercontent.com/4998145/59207854-e15e5100-8b75-11e9-9da6-ff453857c11f.png)

**Comment by plabadie** [comment]
PR #3011

**Comment by KateChuen** [comment]
Tested on dev19. 
- tested error: login with bad credentials & invalid card security code 
- tested confirmation: created new address, update email add, and update consent
- there's no scenario with info message, so couldn't test this.
