### ISSUE TITLE
[master ticket] Cart Total does not include sales tax and other mysteries

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3008]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login
Add product 3595723 to cart, qty 2. 
Go to cart page

**Actual Result**
The cart total is not including the sales tax. 

4004.96 - $20 discount = 3984.96
Did not add the sales tax $189.76
<img width="1203" alt="salesTaxCartTotal" src="https://user-images.githubusercontent.com/45409515/59206143-4e6fe780-8b72-11e9-816b-7a1a59dc2339.png">

**Comment by Xymmer** [comment]
i thought all this info comes from backend... let Bill know what you find.

**Comment by hackergil** [comment]
@Xymmer here's what comes back from the cart OCC call

>  "subTotal" : {
         "formattedValue" : "$1,982.48"
      },
      "totalDiscounts" : {
         "formattedValue" : "$20.00"
      },
      "totalItems" : 1,
      "totalPrice" : {
         "currencyIso" : "USD",
         "formattedValue" : "$1,982.48",
         "value" : 1982.48
      },
      "totalPriceWithTax" : {
         "currencyIso" : "USD",
         "formattedValue" : "$1,982.48",
         "value" : 1982.48
      },
      "totalTax" : {
         "formattedValue" : "$94.40"
      },

**Comment by Xymmer** [comment]
two issues:
- Net vs Gross (Base Commerce > Base Store > Electronics > Essenntial Properties):
When Net = true, total price does not include taxes.
When Net = false, total price includes taxes.

To make things more confusing, after you change this in Backoffice, the boolean is cached somehow, so the only way you can see the change seems to be to make a new cart (perhaps updating the quantity will do so as well).

Second problem: discounts should not be part of subtotals unless they are entry level.

**Comment by Xymmer** [comment]
changes to make:
- #3244 - setting net to true makes the subtotal look correct (taxes are not part of subtotal when net = true)
- what accelerator does: 
when net = false, display a line under totals that says "Your total includes $#.## tax"; when 
when net = true, display tax as part of the list

**Comment by Xymmer** [comment]
taken care of by other tickets
