### ISSUE TITLE
There should be only one ICON_TYPE enum

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#3009]
As part of the configurable icons functionality an enum was created to contain the list of icons available within Spartacus. At some point the mechanism was refactored but an error remains.

At the moment there are two enums ICON_TYPE and ICON_TYPES. We should only have `ICON_TYPE`.

This ticket is to:
- Remove `ICON_TYPES` and all of it's references
- Move types present only in `ICON_TYPES` that are used
- Make the names in `ICON_TYPE` more semantic. For example, `ICON_TYPE.TIMES` is not clear and should be `ICON_TYPE.CLEAR` or `ICON_TYPE.CLOSE`

**Comment by LTiger14** [comment]
QA Steps:
- Open all the dialogs and make sure there is a close button (add-to-cart, suggested-address, facets [on mobile], close-account)
- Make sure the global message still has a close button
- Make sure the facets toggle + and - are visible

**Comment by KateChuen** [comment]
QA Steps:

- [x] Open all the dialogs and make sure there is a close button (add-to-cart, suggested-address, facets [on mobile], close-account)

- [x] Make sure the global message still has a close button
Tested with both successful and error messages

- [x] Make sure the facets toggle + and - are visible. 
Works on desktop, not on iphone: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3053
