### ISSUE TITLE
[Master ticket] Implement mechanism for making error objects serializable and refactor user module

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#3010]
## Problem

ngrx8 introduced some strict runtime checks, such as `strictStateImmutability`, `strictActionImmutability`, `strictStateSerializability` and `strictActionSerializability`.
In #2813 we enabled all of them expect the `strictActionSerializability`.

`strictActionSerializability` flag checks whether the action is serializable. Currently, almost every `*FailAction` is NOT serializable because it takes an http error object which is not serializable (i.e. contains `Map`).
To solve this, we can create a utility function `makeSerializable<T>(obj: T): T` that will convert the non-serializable object into a serializable one.

The implementation is yet to be decided. It can be something as simple as using `JSON.stringify` and `JSON.parse`, or a completely custom one.

This ticket will require changing a lot of files. While we are at it, we should take care of all occurences of `error.json()`.

## Other tickets
In this ticket `user` module should be refactored. For the rest see these tickets:
- [ ] auth - #3260 
- [ ] cart - #3262
- [ ] checkout - #3263 
- [ ] cms - #3264 
- [x] global-messages - #3265 
- [ ] kyma - #3270 
- [ ] product - #3266 
- [x] routing - #3267 
- [ ] site-context - #3268
- [ ] store-finder - #3269

## QA
We can QA all the tickets when all the work is done. Since this is just a refactor, the goal is that app should look and feel as before.

**Comment by znikola** [comment]
To QA: 
We can QA all the tickets when all the work is done. Since this is just a refactor, the goal is that app should look and feel as before.

**Comment by KateChuen** [comment]
Tested on dev2. Haven't seen anything broken so far.
I did notice that the product carousels on homepage have disappeared. Maybe not related to this ticket? Will need to confirm. 
Will do a few more tests...

**Comment by KateChuen** [comment]
Updated dev2 again today. Carousels are back. Everything looks ok.
