### ISSUE TITLE
Changing Language/Currency in checkout in delivery-mode has an infinite loading issue

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#3016]
## Steps to Reproduce
- Use dev-17 or dev-19
- register/login if you have an account
- add a product
- proceed to checkout
- fill up the shipping address in checkout or proceed to next step if you already have a shipping address

- change the language or currency in delivery-mode (this is show the infinite loading).

## Observed Results

- Infinite loading icon

## Expected Results

- should show different 'site-context' in delivery-mode

**Comment by giancorderoortiz** [comment]
Test successful 🆗 .

**Comment by giancorderoortiz** [comment]
![english](https://user-images.githubusercontent.com/46171897/59707228-35011800-91d0-11e9-86fa-f5dd2702aa6d.png)
![german](https://user-images.githubusercontent.com/46171897/59707237-37637200-91d0-11e9-9c70-30ea6b714cea.png)
