### ISSUE TITLE
Add type safety to ProductModule

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#302]
Typesafety should be added wherever possible. A few suggestions where type safety should be added:

* method parameters
* method return values
* if there's no return value for method (it's void), add `void` as the return to make it more specific
* test files
* object literals
* if you need OCC types, take a look at #301's PR
* if working with CMS components, as a generic type use `<T extends Component>`, where `Component` is an interface from `projects/core/src/occ-models/occ.models.ts`

The goal is to have a completely type safety code.

**Comment by MitchellScottSandre** [comment]
Hey @znikola would you be able to provide some more details / specifics as to where specifically to add the type safety?

**Comment by znikola** [comment]
@MitchellScottSandre everywhere, where it makes sense: mostly focus on the facade layer, but also other services can be improved.
In the case of the product module, there are some converters as well.

**Comment by MitchellScottSandre** [comment]
PR: GH-302
