### ISSUE TITLE
search box navigation thru results with up/down keys doesn't work

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#3028]
Tested on mac only so far

**Comment by Zeyber** [comment]
QA Steps:

1. Type 'dsa' into searchbox
2. When products or suggestions are loaded, press up key, check highlights last product in list
3. Press up key again, check highlights second last product in list
4. Press down key, check highlights last product in list
5. Press down key again, check highlights first product in list
6. Press enter, check navigates to highlighted option and closes searchbox

**Comment by giancorderoortiz** [comment]
Test successful

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-07-09 at 7 08 52 AM](https://user-images.githubusercontent.com/46171897/60883597-94bf7180-a218-11e9-8b95-866bdf82615d.png)

**Comment by Zeyber** [comment]
Need to fix breaking changes and deprecate

**Comment by Zeyber** [comment]
PR contains breaking change fixes. Breaking changes for later in #3827

**Comment by Zeyber** [comment]
To revert changes for now as we don't know how to deal with breaking UI changes

**Comment by Zeyber** [comment]
QA Steps: Search dropdown should no longer be navigable with arrow keys

**Comment by mirkosoft** [comment]
checked on dev-17: it's not possible to navigate with arrow keys

**Comment by Xymmer** [comment]
community member reported #4448 
check if it's a duplicate of this one
