### ISSUE TITLE
Error while showing error message

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3029]
1 Go to checkout / create shipping address
2 Remove attr disabled from continue button and click
```
TypeError: Cannot read property 'forEach' of undefined
    at BadRequestHandler.handleError (main.js:12709)
   ...
```
`response.error.errors.forEach((error, index) => {`

**Comment by KateChuen** [comment]
Tested on dev19. 
- Tested without country and we get one global msg, same as what's returned in the response.
![Screen Shot 2019-06-14 at 9 46 59 AM](https://user-images.githubusercontent.com/45409515/59513970-f0047b00-8e89-11e9-9125-6171c4498e53.png)


- But if we select the country, we still get one general global msg, but we have more errors returned in the response. Should we have a global message for each one, like in #2863 
![Screen Shot 2019-06-14 at 9 48 28 AM](https://user-images.githubusercontent.com/45409515/59513982-fabf1000-8e89-11e9-9618-c1f1f3f41f01.png)

**Comment by KateChuen** [comment]
Created ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3192. Can close this one.
