### ISSUE TITLE
Add type safety to GlobalMessageModule, RoutingModule and AuthModule

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#303]
Created from #274. See also #7 .

Use the models from #301.

**Comment by Jim-Yang** [comment]
@znikola Not seeing any facade/store that can be used with the models created in #301

**Comment by Jim-Yang** [comment]
I'm not seeing an interface that models token types in #301, does it exist elsewhere in the project?

**Comment by znikola** [comment]
Yes, it's in `auth/models`.

**Comment by plabadie** [comment]
Looks good.  

I have a small question: I just did a few spot checks in the modules in scope of the ticket.
I wondered if types could be added to those files:
```projects/storefrontlib/src/lib/auth/services/user-error/user-error-handling.service.ts -> in handleExpiredToken() perhaps
projects/core/src/routing/facade/routing.service.ts```
