### ISSUE TITLE
-Muhammad- Pagination items hidden

### ISSUE THREAD

**Issue by MMerwar** [SAP/cloud-commerce-spartacus-storefront#3032]
## Environment Details

- Spartacus:  beta + develop branch (d4da767d7f304bec7daf004bd8ad5c54ef48d1a9)
- Browser: Chrome v75
- OS: Windows 10
- Device: Laptop
- SAP Commerce: 1905 + Spartacus Sample Data Addon
- Other environment details: Angular 8, yarn 1.16, node 10.16.0

## Steps to Reproduce

- Open the storefront
- Type 'test' into the search bar
- 90 results found
- Result 1: Pagination shows the following items "1", "2", "3", "...", "9"
- Select a filter (for example Stores:Chiba)
- 51 results found
- Result 2: Pagination shows the following items "1", "2", "3"
- Select pagination item "3"
- Result 3: Pagination shows the following items "1", "2", "3", "...", "6"
- Remove the filter
- Result 4: Pagination shows the following items "1", "2", "3", "...", "5"
- Select pagination item "5"
- Result 5: Pagination shows the following items "1", "...", "4", "5", "6", "...", "9"

## Observed Results

The pagination items seems to be built correctly at the initial page load and after an pagination item has been clicked, but selecting or removing a filter seems to break the visible pagination items.

## Expected Results

- Results 1 and 5 seems ok
- The other results (2 - 4) seems to be broken
-- Result 2 should also show "..." and "6"
-- Result 3 should also show "4" (in my opinion)
-- Result 4 should be "1", "2", "3", "...", "9" instead of "1", "2", "3", "...", "5"

## Repository Used
https://github.com/SAP/cloud-commerce-spartacus-storefront.git

**Comment by Xymmer** [comment]
possibly fixed with #2857, repo first

**Comment by mazamcodes** [comment]
The issue mentioned here has been resolved, however, improvement is still possibility as it concerns usability. Opened an improvement item #4632 to address this separately.

**Comment by Xymmer** [comment]
can't repro now, likely fixed in a previous release
