### ISSUE TITLE
carousel styles breaks if more then 4 items are shown

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3036]
The layout of carousel items is controlled with CSS, and breaks in case more than 4 items per slide are shown.

**Comment by LTiger14** [comment]
QA Passed
![Screen Shot 2019-06-13 at 2 41 03 PM](https://user-images.githubusercontent.com/10605724/59458851-5f765e00-8de9-11e9-99d6-d0c458b186ad.png)
