### ISSUE TITLE
Can't access to certain pages on pagination nav

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#3045]
If you want to click on 4th page button (dots) you can't - it's not clickable. Dots shouldn't be there actually. Looks like corner case (we got 5 pages here total) but indeed needs to be fixed.

To reproduce: type `shirt` in the search input, hit enter and go to 3rd page. Used dev5 env.

![image](https://user-images.githubusercontent.com/788092/59294942-ea891400-8c82-11e9-9478-1890712e0814.png)

**Comment by Xymmer** [comment]
Similar improvements being made in #4632

**Comment by plabadie** [comment]
Closing.  Expected to be fixed in 2.0.

**Comment by Xymmer** [comment]
fixed in 2.0 with #6060
