### ISSUE TITLE
Alignment of PlaceOrder Button in Checkout

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#3049]
- Add a few items to cart -> Checkout -> Last step of checkout -> Alignment of PlaceOrder Button
<img width="1411" alt="reviewPageAlignment" src="https://user-images.githubusercontent.com/45409515/58815801-45bd6580-85f6-11e9-9f40-303f6044ab0c.png">

Originally part of GH-2835
cc @KateChuen

**Comment by Xymmer** [comment]
the checkbox and submit button should show up right after the total.
the display of promotions is being removed fromthat area

**Comment by KateChuen** [comment]
I still see this issue, on both dev2 which I updated this morning, and dev17. 
Even after clearing cache & in a new incognito window.

**Comment by KateChuen** [comment]
Tested on dev17.
![Screen Shot 2019-07-03 at 11 18 29 AM](https://user-images.githubusercontent.com/45409515/60603936-ade1a180-9d84-11e9-8123-6f7534718d57.png)
