### ISSUE TITLE
Iphone: Tabs misaligned on PDP

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3050]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Go to a pdp of a product for eg: 1981415
Click on "Show Reviews" on top.
Scroll slightly up

**Actual Result**
The alignment is off.
![iphoneTabAlignment](https://user-images.githubusercontent.com/45409515/59299048-c95ffd80-8c59-11e9-86d7-039a6c37c2f9.PNG)

**Comment by developpeurweb** [comment]
This bug was reproducible using Desktop Safari in a Mac. 
For what it seems like a webkit bug the `text-indent` property was rendered ineffective from the `h3` tag once clicking on it, for all 4 tabs. Not so the paddings, so I changed the approach and used `left-padding` instead.

**Comment by developpeurweb** [comment]
This has been merged into `develop`, pls retest after being deployed to Model-T
Since it's a very small change, pls clear cache before testing or try in an incognito window.

**Comment by KateChuen** [comment]
Tested on dev19. This has been fixed now.
