### ISSUE TITLE
[Maybe-not-a-DUPE] Order History page: Improve Order Details Styling - bottom background

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#3052]
- Go to orderHistory -> Order Details -> Are we missing some styling? No clear separation between the sections
<img width="1429" alt="orderDetailsStyling" src="https://user-images.githubusercontent.com/45409515/58816027-a9e02980-85f6-11e9-9d86-47509c644ebe.png">
<img width="1425" alt="orderDetailsStyling2" src="https://user-images.githubusercontent.com/45409515/58816028-a9e02980-85f6-11e9-811b-47e2042ccd01.png">

- Mobile View of it:
<img width="654" alt="mobileOrderDetails" src="https://user-images.githubusercontent.com/45409515/58820761-72c34580-8601-11e9-8966-bae1b5e3ee31.png">

Originally part of GH-2835
cc @KateChuen

**Comment by developpeurweb** [comment]
It seems the "status" it's being duplicated, this below is what we have as mockup, although it seems like an older version (has the old logo), we might need Manu's feedback here.
cc @Xymmer 

<img width="1669" alt="Screen Shot 2019-06-11 at 3 02 49 PM" src="https://user-images.githubusercontent.com/15113219/59299417-90745880-8c5a-11e9-914a-2fac0eb4c0f9.png">

**Comment by Xymmer** [comment]
we're hiding the dupe progress
can you sync with whoever is working on #3055 ?

**Comment by developpeurweb** [comment]
As per chat with @Xymmer the dupe status process is to be **removed** on the TS side, and not just hiding it with CSS.

**Comment by developpeurweb** [comment]
@Xymmer mockups have a grey background on the user details, do we fix this or was it dropped at some point?

![Screen Shot 2019-06-13 at 10 40 26 AM](https://user-images.githubusercontent.com/15113219/59442165-ae130080-8dc7-11e9-861d-acc4aaf41b2a.png)

**Comment by Xymmer** [comment]
i don't know why it was removed so yes let's match the visual

**Comment by KateChuen** [comment]
Tested on dev10, on 3 different browsers (chrome, firefox, safari). 
It's fixed now.

![Screen Shot 2019-11-07 at 3 17 02 PM](https://user-images.githubusercontent.com/45409515/68424705-8a839480-0172-11ea-81b1-a7616c512cb8.png)
![Screen Shot 2019-11-07 at 3 19 20 PM](https://user-images.githubusercontent.com/45409515/68424707-8a839480-0172-11ea-966d-4f46b37347b8.png)
![Screen Shot 2019-11-07 at 3 19 28 PM](https://user-images.githubusercontent.com/45409515/68424708-8b1c2b00-0172-11ea-93f0-1ff4e4d557f2.png)
