### ISSUE TITLE
Upselling products don't disappear if navigate to it

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3054]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Go to a pdp of a product for eg: 1981415
Click on one upselling product, for eg, PL60 Pink

**Actual Result**
You end up on the PL60 PDP page, but it still shows the upselling products from before:
![pdpPLPinkUpselling](https://user-images.githubusercontent.com/45409515/59299653-2dcf8c80-8c5b-11e9-923c-ae17cf805987.jpeg)

This is the pdp of the same product if you navigate to it directly (no upselling products displayed)
![pdpPLPink](https://user-images.githubusercontent.com/45409515/59299663-31631380-8c5b-11e9-8ddb-5d87069e24a4.PNG)

**Comment by LTiger14** [comment]
For reviewer/QA:
- Search for 816802 and open this product (blue Cyber-shot W55)
- Click on the black camera, it should have no references
- Go back click on the pink one, it should have the blue Cyber-shot W55 as reference

**Comment by LTiger14** [comment]
This issue is not only on mobile and for some reason is happening on the ccv2 backend and my local but not dev-17 🤷‍♂

**Comment by giancorderoortiz** [comment]
Test successful on dev-com17 and dev-com2
