### ISSUE TITLE
Order Details: Order status displayed twice

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3055]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Place an order
Go to its Order Details

**Actual Result**
Looks like the order status is displayed twice. On an iphone, it's even more ambiguous since those 2 lines are displayed one after the other.

<img width="1432" alt="orderStatusDetails" src="https://user-images.githubusercontent.com/45409515/59300118-586e1500-8c5c-11e9-80a2-9dfc789f0225.png">

**Comment by Xymmer** [comment]
Remove the status under the order number

**Comment by developpeurweb** [comment]
As per chat with @Xymmer the dupe status process is to be **removed** on the TS side, and not just hiding it with CSS.

**Comment by WeizhengSap** [comment]
They are not duplicate status. One is order status, and the other one is consignment/unconsignment status.

The business logic is this (in our legacy storefront):
- When order only contains consignments:
   -- For each consignment,

**Comment by WeizhengSap** [comment]
In our current SPA, for order containing consignments, it works fine (a few of fields are missing)
![Screen Shot 2019-07-17 at 2 13 14 PM](https://user-images.githubusercontent.com/44440575/61399910-21170780-a89d-11e9-9822-98e7f0f1bae1.png)

But, for order containing unconsignmentEntries, it dose not work as our legacy storefront. But, I think that's fine.
![Screen Shot 2019-07-17 at 2 23 04 PM](https://user-images.githubusercontent.com/44440575/61400563-80c1e280-a89e-11e9-877a-104c86d97405.png)

**Comment by WeizhengSap** [comment]
For order containing unconsignmentEntries, our old legacy storefront has this:
![Screen Shot 2019-07-17 at 2 07 15 PM](https://user-images.githubusercontent.com/44440575/61400656-bb2b7f80-a89e-11e9-9abb-9494514ac868.png)

**Comment by WeizhengSap** [comment]
In this ticket, I will change "unconsignmentEntries" status from `In process..` to `Pending` to make it different from order status. 
We need UI devs to separate order headline and items.

**Comment by WeizhengSap** [comment]
Need move this ticket to UI board.

**Comment by Xymmer** [comment]
back to ui team

**Comment by Xymmer** [comment]
#3055 and #3713 are probably the same issue

**Comment by mikelMHybris** [comment]
this ticket was already merged. So i'll close it and do the styling in another ticket.
