### ISSUE TITLE
Styles not kicking in for filter on mobile

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#3057]
- On tablet/mobile view -> Hamburger menu -> Digital cameras -> Compact cameras -> Filter -> Need spacing.
<img width="935" alt="spacingFilterFacets" src="https://user-images.githubusercontent.com/45409515/58818350-c9c61c00-85fb-11e9-8ffd-e2e791f87bfb.png">

Originally part of GH-2835
cc @KateChuen

**Comment by developpeurweb** [comment]
First screenshot "find a store, sale etc" doesn't seem to be an issue anymore.

Second issue is mainly the styles not kicking-in, since we moved the styles to the storefrontstyles lib it now needs the `<cx-product-facet-navigation>` element to be created inside the modal, not sure how can we make that happen, @Xymmer can we please get a dev to look into this?
An alternative would be to include the facet navigation styles in a global styles file such as forms.scss or modal.scss, but it kind of seems unrelated to the element.

**Current arrangement:**

![Screen Shot 2019-06-21 at 3 47 59 PM](https://user-images.githubusercontent.com/15113219/59948153-41d67380-943d-11e9-9ce9-d88f8d00abea.png)

**Suggested Solution:**
(If I insert the <cx-product-facet-navigation> element inside the modal body with the Chrome inspector, the styles immediately kick-in)

![Screen Shot 2019-06-21 at 3 47 22 PM](https://user-images.githubusercontent.com/15113219/59948252-7e09d400-943d-11e9-8bd9-cf8604d50353.png)

**Comment by KateChuen** [comment]
Tested on dev2. 
Looks good now.

![Screen Shot 2019-07-12 at 11 41 42 AM](https://user-images.githubusercontent.com/45409515/61141093-c8a9c980-a49a-11e9-88ef-19857782f901.png)
![Screen Shot 2019-07-12 at 11 41 54 AM](https://user-images.githubusercontent.com/45409515/61141094-c8a9c980-a49a-11e9-8886-a738146f6faf.png)

**Comment by Matejk00** [comment]
Should be reverted because of breaking change.
