### ISSUE TITLE
Filter tags distribution in mobile view

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#3059]
- On tablet/mobile view -> Hamburger menu -> Digital cameras -> Compact cameras -> Filter -> Apply as many filters -> Sizing of the applied filter tags?
<img width="969" alt="appliedFilters" src="https://user-images.githubusercontent.com/45409515/58818513-17428900-85fc-11e9-8093-f55f55b6d938.png">

Originally part of GH-2835
cc @KateChuen

**Comment by developpeurweb** [comment]
Can't seem to find any mockups on this one, maybe we need Manu's feedback on this?
It should be clear if we are to equalize the heights, what happens when very long vs short labels in different order, etc.
cc @Xymmer

**Comment by Manurod2018** [comment]
Attached are some example with long names, the ‘tag’ labels don’t overflow on a second line. Maximum width is based on the width of the page (or column on desktop). If the label is longer than we show ellipsis.

![Mobile – RESULTS GRID](https://user-images.githubusercontent.com/37299626/59377201-bca5dd00-8d1f-11e9-9104-b2b805e8c33e.png)
![Tablet - RESULTS GRID](https://user-images.githubusercontent.com/37299626/59377202-bd3e7380-8d1f-11e9-9cfd-7150a624e8a2.png)
![Web 1920 – RESULTS GRID](https://user-images.githubusercontent.com/37299626/59377203-bd3e7380-8d1f-11e9-8dab-96f97e74d6ad.png)

**Comment by KateChuen** [comment]
Tested on dev2. 
The filter tags are ok now. 
tablet view: 
<img width="707" alt="Screen Shot 2019-06-20 at 2 25 37 PM" src="https://user-images.githubusercontent.com/45409515/59873986-34e94f80-936b-11e9-8066-8b6d6e735639.png">

mobile view:
<img width="451" alt="Screen Shot 2019-06-20 at 2 25 53 PM" src="https://user-images.githubusercontent.com/45409515/59873988-34e94f80-936b-11e9-948c-12700192dc0f.png">

However, i did noticed that the padding disappears in a specific view. Opened ticket #3308
