### ISSUE TITLE
Update deployment to include cache-control, also document (was: The 'Consent management' dialog is empty)

### ISSUE THREAD

**Issue by zebercut** [SAP/cloud-commerce-spartacus-storefront#3061]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  Beta
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/
- Browser: 
- OS: 
- Device: 

## Steps to Reproduce
1. From the menu, open Consent Management' 
2. The page opens and it is empty

## Additional Information

![image](https://user-images.githubusercontent.com/6307948/59301565-e4357080-8c5f-11e9-9f91-b68fc6af0444.png)

**Comment by Xymmer** [comment]
config issue
need to add the following to `corsfilter.ycommercewebservices.allowedHeaders`
cache-control

**Comment by Xymmer** [comment]
to do:
- make sure deployments include this config
- make sure all cors settings are documented, including this one (it's special)

**Comment by plabadie** [comment]
to do:

make sure deployments include this config
- Internal dev server recipe has the correct property:
https://github.tools.sap/cx-commerce/c3po-legacy-devconfigs/blob/master/spartacus/build.gradle#L35
- CCV2 has the correct property:

make sure all cors settings are documented, including this one (it's special)
