### ISSUE TITLE
"Proceed to Checkout" button is broken

### ISSUE THREAD

**Issue by zebercut** [SAP/cloud-commerce-spartacus-storefront#3064]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  Beta
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/
- Browser: 
- OS: 
- Device: 

## Steps to Reproduce

1. Add one item to the cart
2. go to shopping cart
3. See the screenshot
## Additional Information

![image](https://user-images.githubusercontent.com/6307948/59302346-c537de00-8c61-11e9-8ce0-603dc9232b8e.png)

**Comment by Xymmer** [comment]
already fixed
