### ISSUE TITLE
Confirmation order message goes under the search dialog result

### ISSUE THREAD

**Issue by zebercut** [SAP/cloud-commerce-spartacus-storefront#3066]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details
- Spartacus:  Beta
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/
- Browser: 
- OS: 
- Device: 

## Steps to Reproduce
1. Add few items to the cart
2. Proceed to check out and complete checkout
3. It shows the confirmation message and a confirmation number
4. While you are on the same confirmation page, search for an item in the search box
5. The search list shows and it goes under the confirmation message
See the screenshot

## Additional Information

![20190611_161234](https://user-images.githubusercontent.com/6307948/59303613-92dbb000-8c64-11e9-9c32-e84cbd553bc2.jpg)

**Comment by Xymmer** [comment]
can searching kill the global message? whether we fix this to show on top or not, the user is obviously onto other things

**Comment by reyhanehsalkhi** [comment]
PR: GH-5838

**Comment by KateChuen** [comment]
Tested on dev10 on chrome, firefox, safari. Looks ok now. ✅
<img width="1202" alt="Screen Shot 2020-04-07 at 10 26 07 AM" src="https://user-images.githubusercontent.com/45409515/78681422-b4c0b600-78ba-11ea-96c9-cee802e1392d.png">
