### ISSUE TITLE
Failing E2E: Update Profile

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3071]
regression/my-account/update-profile.e2e-spec.ts fails when running locally pointing to dev17 backend. (May be inconsistent results).

**Comment by bgambocjaviniar** [comment]
I don't see a problem with it, and it is passing in the nightly builds. I'll check back tomorrow morning

**Comment by bgambocjaviniar** [comment]
PR: GH-3082
