### ISSUE TITLE
Failing E2E: Product Search Rating Flow

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3074]
regression/product-search/product-search-rating-flow.e2e-spec.ts is failing when running locally pointing to dev17.

```    CypressError: Timed out retrying: expected '<cx-product-list-item.cx-product-search-list>' to contain 'DSC-W180'```

**Comment by marlass** [comment]
I remember that we had to often change assertions for products there.
My guess is that `solr` is not deterministic and sometimes you get results in a different order (for example with products with identical rating).

Might be worth to use data from API response to make those assertions.
Example here: `product-search-product-type-flow.ts`

**Comment by bgambocjaviniar** [comment]
PR: GH-3109

- added fix for product pricing-flow too because I'm re-using the assertion that Gil created for this problem.
