### ISSUE TITLE
Failing E2E: Cart Mobile

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3077]
mobile/cart-mobile.e2e-spec.ts fails when running locally pointing to dev17.

```  CypressError: Timed out retrying: Expected to find element: 'cx-product-summary .quantity', but never found it.```

**Comment by bgambocjaviniar** [comment]
PR: GH-3081

**Comment by bgambocjaviniar** [comment]
Closing duplicate GH-3020
