### ISSUE TITLE
In mobile (landscape orientation) the added to cart modal background is too small

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#3079]
**Maybe this is a bit of stretch.** 

### To reproduce

If you use Spartacus on mobile (can be seen in browser mobile testing view)and click add to cart the modal will be higher than the screen so the buttons will not be visible at first. When you scroll down, to reveal the buttons there is no background.

![Screenshot_20190611-150955](https://user-images.githubusercontent.com/10605724/59308931-4ac28a80-8c70-11e9-81b3-590c524aeb56.png)

### Expected behaviour 

It should be white behind the buttons.

**Comment by KateChuen** [comment]
Tested on dev19. The issue with the background is fixed now. It's white.
However, the issue with the size of the "add to cart" modal isn't fixed. So, I either only see the top half of the modal, or the bottom half of it. And scrolling did not help in this case. Created ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3458 to address this:
