### ISSUE TITLE
Add type safety to UserModule

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#308]
Typesafety should be added wherever possible. A few suggestions where type safety should be added:

* method parameters
* method return values
* if there's no return value for method (it's void), add `void` as the return to make it more specific
* test files
* object literals
* if you need OCC types, take a look at #301's PR
* if working with CMS components, as a generic type use `<T extends Component>`, where `Component` is an interface from `projects/core/src/occ-models/occ.models.ts`

The goal is to have a completely type safety code.

**Comment by plabadie** [comment]
Please create a PR and get a green build.

**Comment by MitchellScottSandre** [comment]
PR: GH-373
