### ISSUE TITLE
Avoid creating a shallow copy of the state in storage-sync.reducer

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#3097]

**Comment by znikola** [comment]
To QA:
login, check the `localStorage` (there should be a token). Open a new tab, the user should still be logged in. Logout, and check the storage - the token should not be there.

**Comment by KateChuen** [comment]
Tested on dev19. 
When logged in, there's a token in LocalStorage.
<img width="1437" alt="Screen Shot 2019-06-13 at 1 57 47 PM" src="https://user-images.githubusercontent.com/45409515/59456044-76b24d00-8de3-11e9-94d2-641561e1c1ea.png">

Stays logged in in other tabs too.

When logged out, no token in LocalStorage.
<img width="1438" alt="Screen Shot 2019-06-13 at 1 58 01 PM" src="https://user-images.githubusercontent.com/45409515/59456118-a4979180-8de3-11e9-85d1-f369c5bbb0b0.png">
