### ISSUE TITLE
Add to cart: message is misleading if you add qty more than 1

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3101]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Mac
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Login
Go to a product that's not currently in your cart.
Add Qty 2 of the product

**Actual Result**
You get a message that the product was already in your cart and the qty has been updated. 
Doesn't happen if you add qty1. 
![addQty2](https://user-images.githubusercontent.com/45409515/59355573-32488380-8cf5-11e9-8a95-1448fc8beed2.png)

**Comment by Xymmer** [comment]
it's a bug

**Comment by mirkosoft** [comment]
QA steps:
While adding product to cart, the popup has a title with message (added or quantity updated). Product can be added to cart at the PDP or PLP. Check the right message is displayed when:
- adding one product
- adding many products (PDP, quantity >1)
- adding product which is already in the cart

**Comment by giancorderoortiz** [comment]
Test successful. Message correctly shown only when same product is already in cart.
