### ISSUE TITLE
iphone8+: unhandled error message does not fit on the screen

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3105]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Login
Add item to cart
Proceed to checkout
On the payment step of checkout, choose a expiry date in the past.

**Actual Result**
The message does not fit on the screen. But I know that this error will be fixed in ticket #2971. But thinking more in the future, if we've missed an error and have a similar case. Maybe we should handle it better?
![IMG_8300](https://user-images.githubusercontent.com/45409515/59358339-5bb7de00-8cfa-11e9-92f1-2fda8db9a148.PNG)

**Comment by Xymmer** [comment]
won't happen when translation is done
