### ISSUE TITLE
iphone8+: No search suggestions displayed in other languages

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3112]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Change language to DE for eg.
Click on the search icon.
And type canon

**Actual Result**
There's no suggestion in other languages, probably because the unlocalized name is displayed?
![IMG_8304](https://user-images.githubusercontent.com/45409515/59366998-367e9c00-8d09-11e9-9198-df79b5b6950a.PNG)

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3162

**Comment by RadhepS** [comment]
Suggestions do not appear on any language including English.
Spoke with Tobias about this, he informed me that the suggestions were intentionally disabled on Mobile.
He said it was decided by the UI/UX team as well as Bill.
