### ISSUE TITLE
iphone8+: looks ugly when we change the language

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3113]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Go to Register Form page, or PLP or any page.
Change language to DE

**Actual Result**
1. Not very user-friendly. Once the page is reloaded in another language, user has to figure out how to close the disproportionate menu. 
2. Once the menu is finally closed, the storefront is kinda ugly. 

When are we getting translations?

![IMG_8303](https://user-images.githubusercontent.com/45409515/59367146-878e9000-8d09-11e9-838d-aaf9b9c310fe.PNG)

**Comment by Xymmer** [comment]
we haven't done translation and we had ccv2 server in dev mode not production
