### ISSUE TITLE
iphone8+: Grid view icon on PLP is misaligned

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3118]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Search for "Camera"

**Actual Result**
Is the "grid view" icon properly positioned? It looks like it was supposed to be on the same line as the pagination? 

![IMG_B8C35F852409-1](https://user-images.githubusercontent.com/45409515/59375828-f75a4600-8d1c-11e9-83ec-96914ef6c0e8.jpeg)

**Comment by Xymmer** [comment]
happens on regular 8 as well
maybe it should be 
[SORT]   [GRID]
[PAGINATION]

also when i tap on sort, i'm wondering why my iphone doesn't display the special list

**Comment by marlass** [comment]
Also switching between grid/list on small viewports don't give real value. Only little stylistic changes are visible. You are seeing one product after another in both modes.
Maybe we remove the button on smaller viewports.

**Comment by tobi-or-not-tobi** [comment]
Fixed with 2.0

**Comment by Xymmer** [comment]
fixed in 2.0 with #6060
