### ISSUE TITLE
product search: filter is removed when we sort

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3119]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Mac or Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Search for "Camera" -> 144 results
Filter by store "Chiba" -> 79 results
Sort by anything, for eg (price lowest)

**Actual Result**
The search filter disappears and it's back to 144 results.

**Comment by Xymmer** [comment]
similar issue as completed bug #2857

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3166

**Comment by giancorderoortiz** [comment]
no fix yet seen on dev-com17 (June 17, 2pm EST)

**Comment by KateChuen** [comment]
probably because backend wasn't updated. You can validate on https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Comment by giancorderoortiz** [comment]
Test on dev-com2 successful 🆗
