### ISSUE TITLE
Fix translation languages when Spartacus is running in production mode

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3123]
## Environment Details

- Spartacus:  Beta
- Browser: All
- OS: All
- Device: All

## Steps to Reproduce
Click on translation dropdown

## Observed Results
![Screen Shot 2019-06-12 at 3 53 21 PM](https://user-images.githubusercontent.com/34665674/59381765-3c38a980-8d2a-11e9-9f98-fa7f163b1ad0.png)

We see translation languages that are used for development purposes. These should not be shown in production mode, only the fallback languages if defined should show up.

**Comment by Xymmer** [comment]
the server is running in dev mode so that's why you see them on model t server.
in prod they don't appear

**Comment by Xymmer** [comment]
#2758 deals with setting a default language
let's use this ticket to ensure the default language is set for releases to model t, and we use prod and not develop

**Comment by Xymmer** [comment]
i forgot about this ticket and created another
closing this one
