### ISSUE TITLE
Incorrect exports from modules

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#313]
The code base shows a number of times where an ngModule is imported and exported. While this is a good pattern for shared modules, it is not a common practice when a module depends on other modules. 

We should not export our imported modules. This needs to be fixed at:
- [x] CartModule
- [x] CheckoutModule
- [x] MyAccountModule
- [x] OrderModule
- [x] ProductModule
- [x] SiteContextModule
- [x] StorefrontModule
- [x] LayoutModule
- [x] UiModule

**Comment by Xymmer** [comment]
Nik believes the change only needs to be done in `*module.ts` files, which are not touched in Gladiator facade tickets... let's go for it

**Comment by tobi-or-not-tobi** [comment]
We also need to not export the FooterComponent in the MainModule...
