### ISSUE TITLE
Wasted space on checkout review page - can we fit all review info in one line? (iPad Air Safari vertical)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3136]
Seen in iPad Air Safari vertical

**Comment by Xymmer** [comment]
![IMG_0025](https://user-images.githubusercontent.com/4998145/59394402-90a15080-8d4d-11e9-9517-4015c77663a4.PNG)

**Comment by hackergil** [comment]
Needs clarification
