### ISSUE TITLE
Search doesn't work from breadcrumb

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3149]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Mac 
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Go to any pdp, for eg: product 1981415
From the breadcrumb, click on Samsung.
<img width="1409" alt="Screen Shot 2019-06-12 at 8 58 21 PM" src="https://user-images.githubusercontent.com/45409515/59396113-31473e80-8d55-11e9-87f0-a09cb07e47c7.png">

**Actual Result**
The search result is 0:
<img width="1315" alt="Screen Shot 2019-06-12 at 8 58 29 PM" src="https://user-images.githubusercontent.com/45409515/59396134-44f2a500-8d55-11e9-8646-27ce15e2fec9.png">

However, if you actually search for "samsung" in the search box, you get this result:
<img width="1358" alt="Screen Shot 2019-06-12 at 8 58 43 PM" src="https://user-images.githubusercontent.com/45409515/59396139-48862c00-8d55-11e9-9b13-c7a8d12d9f63.png">

**Comment by giancorderoortiz** [comment]
I see that functionality has been fixed in dev-com17. 🆗 
However, I do see random delays, where if navigating to a category first time around, it takes between 3-5 seconds to actually get results.  ⚠️
