### ISSUE TITLE
PdP: qty should be reset to 1 if qty removed and clicked outside

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3150]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Mac 
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Go to any pdp, for eg: product 1981415
Put cursor in the qty box and remove the input. 
Click outside.
Click on Add to cart

**Actual Result**
Able to add to cart, with qty1. 
When the cursor's focus comes out of the qty box, the qty should be reset to 1. 
<img width="1283" alt="Screen Shot 2019-06-12 at 9 03 09 PM" src="https://user-images.githubusercontent.com/45409515/59396256-e2e66f80-8d55-11e9-9117-9bad6dd4b81d.png">

**Comment by qjimmy** [comment]
PR #5982
