### ISSUE TITLE
Compile problem with Beta version

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#3163]
Hi,
when I am compiling my code its get failed cause following issue:

`ERROR in node_modules/@spartacus/core/src/cart/store/selectors/cart.selector.d.ts(22,69): error TS2314: Generic type 'MemoizedSelector<State, Result>' requires 2 type argument(s)`

![image](https://user-images.githubusercontent.com/16721438/59445212-86d82580-8dff-11e9-9fcf-3e784fb89215.png)

## Environment Details
- Node: 10
- Angular: 8
- Spartacus: ~0.1.0-beta.0
- Browser: chrome
- OS:  Centos7 (Linux)

## Steps to Reproduce
After `npm install` just try to start server with `npm start``

My Json File looks like:
```
{
  "name": "spartacus",
  "version": "0.0.1",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1",
    "@spartacus/core": "~0.1.0-beta.0",
    "@spartacus/styles": "~0.1.0-beta.0",
    "@spartacus/storefront": "~0.1.0-beta.0",
    "@spartacus/assets": "~0.1.0-beta.3",
    "@angular/pwa": "^0.800.2",
    "@angular/service-worker": "~8.0.0",
    "@ng-bootstrap/ng-bootstrap": "4.1.0",
    "@ng-select/ng-select": "^2.13.2",
    "@ngrx/effects": "~7.4.0",
    "@ngrx/router-store": "~7.4.0",
    "@ngrx/store": "~7.4.0",
    "bootstrap": "^4.2.1",
    "i18next": "^15.0.6",
    "i18next-xhr-backend": "^2.0.1",
    "jquery": "1.9.1 - 3",
    "popper.js": "^1.14.7",
    "core-js": "^2.5.7"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.2",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "~8.0.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}
```

**Comment by Platonn** [comment]
We should add a missing type here https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/core/src/cart/store/selectors/cart.selector.ts#L88

**Comment by KateChuen** [comment]
Having this issue on dev2 also. 
I pulled the latest, removed my node_modules, did an npm cache clean, yarn cache clean, yarn. 
but when i run ng build, i get this error.

**Comment by LTiger14** [comment]
This issue is happening because your ngrx versions are wrong. As specified here https://sap.github.io/cloud-commerce-spartacus-storefront-docs/Building-the-Spartacus-Storefront-from-Libraries/ in the `Adding Peer Dependencies to the Storefront` section the versions should be:
```
"@ngrx/effects": "~8.0.0",
"@ngrx/router-store": "~8.0.0",
"@ngrx/store": "~8.0.0",
```

**Comment by KateChuen** [comment]
Confirmed, after updating the versions of ngrx, it works. no more compiling issues. Can close.

**Comment by znikola** [comment]
I believe this was for the previous version of our libraries (beta0) which is using the older ngrx `~7.4.0`
