### ISSUE TITLE
To speed up first time add-to-cart, create a cart earlier

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3164]
We see that adding to cart the first time takes a few seconds. Also see #2966.

When adding the first product into cart, we need to check whether user's cart exist or not. If there is no cart, then the first thing is to create a new cart. After cart created, the product can be added.

One of the improvements we can do is make sure there is a cart for any user, before they hit add to cart. That way we they don't spend time waiting for a new cart to be created.

Check with Tobias and figure out when this check should occur.

**Comment by WeizhengSap** [comment]
I think, it is a better way that we check cart exists or not when adding the first product. If we create a cart for any user, before they hit add to cart, that will create many useless carts. And, for login users who already have carts, the cart merge has to be done.

Creating a cart when adding the first product only makes the first "add to cart" a little bit slower. So, my PR only fixes this issue: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2966

**Comment by WeizhengSap** [comment]
To QA:

Test on "add to cart".

**Comment by giancorderoortiz** [comment]
I do see an improvement. 
Test successful 👍
