### ISSUE TITLE
Avoid subscribing in user token interceptor

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#3168]
There's a subscription in `user-token.interceptor.ts` that can lead to memory leaks.

**Comment by znikola** [comment]
PR: #3169

**Comment by znikola** [comment]
To QA: since this interceptor is being used for adding authentication token to each request, it's enough to just do a couple of API calls that do require authentication, and everything should work just like before.

**Comment by KateChuen** [comment]
Tested on dev2. Did login, logout, accessed my account pages, and placed an order.
Verified that trying to access myaccount pages while logged out redirects me to the login page.
