### ISSUE TITLE
[dev2] Smartedit can launch Spartacus 

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#317]
SmartEdit shows you a list of sites on launch. We need to tweak preview URL.

- Create new cms site impex to connect Spartacus Electronics to SmartEdit. 
-- Need to specify unique regex for cms site to listen to.
-- Come up with regex and validate with Tobias.
- Refer to same product/content catalogs.
- Don't override existing so that we still have access to Accelerator electronics. 
- Preview url (what smartedit uses to launch the site in the iframe): set up for cms site (get it from a config property)
- Update whitelist config of smartedit
- Use spacceleratoraddon.

Maybe SmartEdit has such an impex we can use?

Riry set up Spartacus for a demo at CX Live 2018.
SmartEdit team is ready and able to help us.
Attempts were done here by Tobias: https://wiki.hybris.com/display/pskb/Manage+external+storefront+with+SmartEdit
If needed, talk to Tobias and/or our contact in SmartEdit, who is Fred/Riry.

Acceptance criteria:
- can see the storefront
- can't do anything yet in SmartEdit
- come up with the qa installation procedure that runs the impex. (GH-368)
- Get it installed in one our dev servers (#365). Talk to Gil/Giancarlo about that.

It's understood that the the configuration is hardcode for now, we'll have to make it more easily configurable later.

One possible issue: if you load storefront in smartedit, communication goes through injector. Injector may or may not be needed for the purposes of this ticket, but eventually it is needed to get SmartEdit to work.

**Comment by WeizhengSap** [comment]
In hac, import:

$siteUid=electronics
$productCatalog=electronicsProductCatalog
$contentCatalog=electronicsContentCatalog
$contentCV=catalogVersion(CatalogVersion.catalog(Catalog.id[default=$contentCatalog]),CatalogVersion.version[default=Staged])[default=$contentCatalog:Staged]
$storeUid=electronics
$siteMapLangCur=jaJpy,jaUsd,enJpy,enUsd,deJpy,deUsd,zhJpy,zhUsd
$siteMapPage=Homepage,Product,CategoryLanding,Category,Store,Content,Custom
$customSiteMapUrls=/Open-Catalogue/c/1?q=%3AtopRated%3AallPromotions%3ABOGOFElectronics%3AallPromotions%3A10DiscountCanonEOS450D%3AallPromotions%3AMultiBuyElectronics%3AallPromotions%3APerfectPartnerElectronics%3AallPromotions%3AProductBundleElectronics,/Brands/c/brands?q=%3Arelevance%3Abrand%3Abrand_5%3Acategory%3A575,/Open-Catalogue/Cameras/Hand-held-Camcorders/c/584?q=%3Arelevance%3Abrand%3Abrand_2,/Open-Catalogue/Components/Power-Supplies/c/816?q=%3Arelevance%3Abrand%3Abrand_5,/Open-Catalogue/Data-storage/Flash-Memory/c/902?q=%3Arelevance%3Abrand%3Abrand_18

$spaSiteUid=electronics-spa
$spaContentCatalog=electronics-spaContentCatalog
$fullPathElectronics=http://localhost:4200
$language=en


# Content catalog for spartacus
INSERT_UPDATE ContentCatalog;id[unique=true];supercatalog(id)
;$spaContentCatalog;$contentCatalog

UPDATE ContentCatalog;id[unique=true];name[lang=$language]
;$spaContentCatalog;"Electronics Content Catalog SPA"

# CatalogVersion for spartacus
INSERT_UPDATE CatalogVersion;catalog(id)[unique=true];version[unique=true];active;languages(isoCode);writePrincipals(usergroup.uid)[mode=append];readPrincipals(usergroup.uid)[mode=append]
;$spaContentCatalog;Staged;false;$language;electronics-cmsmanagergroup,cmsmanagergroup;
;$spaContentCatalog;Online;true;$language;;electronics-cmsmanagergroup,cmsmanagergroup;

# site for spartacus
INSERT_UPDATE CMSSite;uid[unique=true];theme(code);channel(code);stores(uid);contentCatalogs(id);defaultCatalog(id);defaultLanguage(isoCode);siteMapConfig(configId);urlPatterns;active;previewURL;startingPage(uid,$contentCV);urlEncodingAttributes;defaultPromotionGroup(Identifier)[default=electronicsPromoGrp]
;$spaSiteUid;;B2C;$storeUid;$contentCatalog,$spaContentCatalog;$productCatalog;$language;electronicsSiteMapConfig;;true ;$fullPathElectronics;homepage

UPDATE CMSSite;uid[unique=true];name[lang=$language]
;$spaSiteUid;"Spartacus Electronics Site"

**Comment by WeizhengSap** [comment]
In the Site list, you will see: 'Spartacus Electronics Site'

![screen shot 2018-11-28 at 2 54 37 pm](https://user-images.githubusercontent.com/44440575/49178375-9d180b80-f31d-11e8-948f-704101d49e74.png)

**Comment by WeizhengSap** [comment]
Click 'homepage', you will see SPA launched. The page launched is "page not found". To launch homepage, "previewServlet" should not be appended into url. There is a smart edit ticket to fix it: CMSX-6017.
If you see this error in console: "Mixed Content: The page at 'xxxx' was loaded over HTTPS, but requested an insecure script 'xxxx'. This content should also be served over HTTPS." To solve this, you need click on the red security icon on the right of the URL text field and Allow Mixed Content requests.

![screen shot 2018-11-28 at 2 54 59 pm](https://user-images.githubusercontent.com/44440575/49178522-f4b67700-f31d-11e8-9a58-74350a1f722b.png)

**Comment by WeizhengSap** [comment]
PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/5/overview
