### ISSUE TITLE
Ipad Pro. Double Tapping Required Throughout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3170]
Observed double tapping required throughout application to make buttons/links work. 
It's specially noticeable when working with myAccount links as it requires double tapping, sometime more. It's a bit frustrating. 

In PDP, when switching tabs at bottom of page user perceives an intermediate step where he's neither in step a, nor b. 

iPad Pro
iOS 11.0.3

![myaccountsticky](https://user-images.githubusercontent.com/46171897/59451071-9c862480-8dd8-11e9-94a4-259eb594919b.png)
![PDPdoubletapping](https://user-images.githubusercontent.com/46171897/59451081-a27c0580-8dd8-11e9-9647-12634c57db7c.png)

**Comment by bgambocjaviniar** [comment]
Can't reproduce both issues with my IPad pro
server: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/

IOS version: 12.3.1
Safari: 12.1.1 
Chrome: 75.0.3770.85

It is for sure related to the the IOS version. Most likely version 11 and below does not have the new change that safari included in version 12 that made all IOS devices not let them go through the double clicks as it was a feature for them in browser. 

Moreover, for each ios version, safari will be the same major version. Example, ios version is 12.x.x, therefore Safari mobile will also be 12.x.x. If it were an ios version of 11.x.x, then the safari mobile would be 11.x.x as well.

Note: I can't say for sure if it is a problem relating to version 11 until I get the Ipad pro with that version.

**Comment by bgambocjaviniar** [comment]
@giancorderoortiz was told by Bill for you to re-test just in case, but my guess is due to the safari version / ios version

**Comment by giancorderoortiz** [comment]
Upgrading OS version in iPad Pro and re-checking.

**Comment by giancorderoortiz** [comment]
Improvement seen throughout with iOS version 12.3.1. 
However myAccount menu still doesn't disappear. Will create a separate issue for that.

**Comment by giancorderoortiz** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3299
