### ISSUE TITLE
Equip Page Meta resolvers with more standard functionality

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3186]
Currently, individual page meta resolvers aggregate the metadata by implementing the `resolve()` method. This method is responsible for calling different resolvers with the required data. This makes it cumbersome to extend, since whenever you like to extend the list of resolvers, you must override (and reimplement) the resolve method. Moreover, the data required by different resolvers might differ, which leads also to reimplementing the `resolve` method. 

We like to allow for easy implementation of those meta resolvers. This means that 
- the `PageMetaService` should call the individual resolvers (if available) on the resolver class
- the individual resolvers must gather the data themselves; we no longer will pass in data through arguments

This change will lead to a breaking changes in the API, which we cannot before 2.0. We must either postpone this until 2.0 or have a temporary backwards compatible feature in place. 

Stretch goals:
- make the list of resolvers configurable for the `PageMetaService`, so that custom/future resolvers can be added without touching the implementation cross all resolvers
- execute some resolvers only for SSR or dev mode, to further optimise the runtime

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- Ensure that you can implement any resolver interface with featureLevel > 1.3, without overriding the `resolve()` method of a specific resolver

**Comment by Matejk00** [comment]
After consultation with @tobi-or-not-tobi, QA done and implemented resolvers works as expected.
