### ISSUE TITLE
Samsung Tablet-Firefox: Loading

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#3188]
server: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/

## Observed Results

Loading takes like (~20 seconds) when
- you try to access the web page
- when you refresh

First time loading some components, you can see it loading slowly when
- you add to cart and the modal open, the image is loaded very slowly. You can see text instead of the image. But after 2-5 seconds, the image is shown.
- Similar to category page with all the images
- Similar to the search suggestions

## Expected Results
- We should not see the text placeholder for the images for 5 seconds before it shows the image
- We should be able to access the web page under 5 seconds or so.

**Comment by Xymmer** [comment]
would like to know why this is happening on these devices, on my ipad and iphone, loading is reasonable.

**Comment by hackergil** [comment]
Dupe with #3492
