### ISSUE TITLE
Bullet points and spacing on medium sized screens on filters

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#3189]
## Steps to Reproduce
All browsers and medium-sized devices
Go to any category page and make the screen size < 992 px

## Observed Results
Spacing and bullet points on the checkboxes

<img width="789" alt="Screen Shot 2019-06-14 at 8 22 42 AM" src="https://user-images.githubusercontent.com/29099466/59508940-9c8c3000-8e7d-11e9-8274-4ba8edea0a66.png">

## Expected Results
Should not show bullet points and have proper spacing between the checkbox and text

**Comment by Xymmer** [comment]
dupe
