### ISSUE TITLE
[Blocked] Run modelt spartacus as pwa

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3197]
unless there's a reason not to? we're trying to test add to home feature but also customers are trying it out.

**Comment by hackergil** [comment]
I tested this yesterday. After making a few changes to CCv2 and spartacus installation, I found a couple of issues:
* Service worker is not being registered
* Add to home banner is not showing up

Blocking this ticket until we have a fix for the above

**Comment by hackergil** [comment]
Fixed with #3290
