### ISSUE TITLE
Update release script to release any library

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#320]
Currently, our release script can only release the storefront library. Update it so that we can use it to release core, and any future angular-based libraries as well

**Comment by hackergil** [comment]
Pull request #321

**Comment by WeizhengSap** [comment]
It was merged. So, I moved it to Doc.

**Comment by hackergil** [comment]
Some changes were not merged to develop. Creating a new PR for this.

**Comment by plabadie** [comment]
Approved PR #450
