### ISSUE TITLE
Make apparel-spa [need help from Gladiators]

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3202]
We'd like an apparel-spa like we have electronics-spa.
The idea is to use apparel sample data that's included in the ootb zip and make certain changes.
Let's re-use the spartacussampledataaddon for this, with these requests:

- If sample data not found, just skip with warning (e.g. maybe I only have electronics installed)
- Provide parameters to:
-- choose which sample data to modify (I may have both installed but only want electronics-spa created)
-- modify electronics or apparel directly instead of copying (because copying electronics to electronics spa greatly increases initialization time)

For the parameters maybe it can be all one parameter per sample data:
spartacussampledataaddon.electronics-spa.synctask=
- update-existing (which would mean Accelerator doesn't work well)
- create-duplicate (which takes longer because you have 2 electronic sample datas)
- ignore (don't create electronics-spa)

**Comment by mirkosoft** [comment]
closing as sampledataaddon feature branch with apparel-uk-spa has been merged to develop
