### ISSUE TITLE
Add videos links to index.html intro section

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3209]
Our public videos are starting to come online. 
- Add links to intro videos on the welcome page

All our videos are hosted here: https://enable.cx.sap.com/tag/tagid/spartacus
but appear in random order or order in which they were added (most recent first).

**Comment by Xymmer** [comment]
Created PR #17 for adding links to index.html
(btw agree that this page should just redirect to a welcome page)

**Comment by gladius-mtl** [comment]
Above PR (GH-17) takes care of this ticket.
