### ISSUE TITLE
Create page for listing videos

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3210]
Our public videos are starting to come online. 
- Dedicate a page to listing them and describing what they are about so people can find them. 

All our videos are hosted here: https://enable.cx.sap.com/tag/tagid/spartacus
but appear in random order or order in which they were added (most recent first).

**Comment by Xymmer** [comment]
Created PR https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/pull/18

**Comment by gladius-mtl** [comment]
Can now be viewed here: https://sap.github.io/cloud-commerce-spartacus-storefront-docs/spartacus-videos/
