### ISSUE TITLE
Failing/Unstable E2E: Language My Account Pages

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3220]
regression/site-context/language/language-my-account-pages.e2e-spec.ts is unstable when running locally pointing to dev17.

Fix it so that the test is consistently passing.

**Comment by RadhepS** [comment]
Going to take over this ticket from Miro as his priority right now is working with the apparel

**Comment by RadhepS** [comment]
Merged to develop (prior to 1.0.1 branch change)

**Comment by giancorderoortiz** [comment]
I don't see a fix neither on dev-com17, nor dev-com19. 

![Screen Shot 2019-06-28 at 6 08 52 PM](https://user-images.githubusercontent.com/46171897/60373913-f0dff580-99cf-11e9-88e8-5db377a0cb37.png)
![Screen Shot 2019-06-28 at 6 09 12 PM](https://user-images.githubusercontent.com/46171897/60373914-f0dff580-99cf-11e9-8c6c-34ec0509ab86.png)

**Comment by bgambocjaviniar** [comment]
adding the 2 - needs a fix in here from GH-3525
order-history-no order
and language-my-account 

Above ss is not related because they are working.

**Comment by bgambocjaviniar** [comment]
PR: GH-3528
