### ISSUE TITLE
Translation chunks user and cart unnecesarily loaded on homepage

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#3221]
The translation chunks `cart` and `user` are unnecesarily loaded on the homepage.

The key `miniCart` (with subkeys) should be moved from chunk `cart` to `common`.
The key `login` (with subkeys) should be renamed to `miniLogin` and moved from chunk `user` to `common`.

**Comment by Platonn** [comment]
### QA steps:
1. Generate JSON translations assets: `yarn build:assets`
2. Copy JSONs to to the storefrontapp assets folder
  `cp dist/assets/i18n-assets/ projects/storefrontapp/src/assets/ -r`
3. start app: `yarn start`
4. In the Chrome dev tools go to `Network` panel and filer by the phrase `.json`
5. Open spartacus in the browser and verify that only `common.json` file was loaded for the homepage (not `cart.json`, nor `user.json`k)

**Comment by giancorderoortiz** [comment]
Test successful 👍 

![resources](https://user-images.githubusercontent.com/46171897/60051562-469b6180-96a1-11e9-954f-de2efcfb176a.png)
