### ISSUE TITLE
[DUPE of GH-3627] theme colors are not added every where

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3236]
I've spotted 2 occasions where the css variables aren't added used for theme colours:
- pagination on PLP
- submit button on (invalid) form

**Comment by LTiger14** [comment]
### QA steps

1. Open the login page
2. Open your dev tools
3. Go to this section
![Screen Shot 2019-06-20 at 3 51 25 PM](https://user-images.githubusercontent.com/10605724/59877332-aa591e00-9373-11e9-9433-ca169e569a47.png)

4. Change the value for `--cx-color-primary` to `blue`, the login button should be blue
5. Go to the PLP, when hovering over another page number in the pagination, the button should become red (or blue if you kept the variable from step 4) and the number should remain white

**Comment by KateChuen** [comment]
Tested on dev19.
- After changing the value of --cx-color-primary to blue, the  color is reflected on login button & page number button on hovering. 

![Screen Shot 2019-06-28 at 3 29 23 PM](https://user-images.githubusercontent.com/45409515/60366559-e0bd1b80-99b9-11e9-9f3e-17e222abf4f7.png)
![Screen Shot 2019-06-28 at 3 30 02 PM](https://user-images.githubusercontent.com/45409515/60366560-e0bd1b80-99b9-11e9-9191-1c87c93015a3.png)

**Comment by tobi-or-not-tobi** [comment]
@KateChuen I can still see the red on the first pagination button, that seems wrong actually.

**Comment by giancorderoortiz** [comment]
@tobi-or-not-tobi  yes, I see the first pagination button colored red after the color change. 
Setting back to ToDo per your comments.

**Comment by mikelMHybris** [comment]
I took a look but I can't replicate the issue. 
<img width="1527" alt="Screen Shot 2019-07-01 at 2 26 49 PM" src="https://user-images.githubusercontent.com/30266610/60458324-4ef91c80-9c0c-11e9-8bc4-bb543ad68114.png">

**Comment by KateChuen** [comment]
My bad. I thought the color should only change on hover for the pagination buttons. I will retest this on my side again.

**Comment by KateChuen** [comment]
I can constantly reproduce it on dev19, on chrome....

**Comment by mikelMHybris** [comment]
I have the latest from develop on my local and I can't get the same results.

**Comment by KateChuen** [comment]
I also pulled from develop on my local, pointing to dev17 & dev19 for backend. And I see this issue (i'm confused). 
I also see this issue on dev17 & dev19 frontend. 
I opened in incognito window too and still same issue :(

**Comment by mikelMHybris** [comment]
@KateChuen can you check this branch again?

**Comment by KateChuen** [comment]
I deployed feature/GH-3236 branch locally, and it looks good. I see the pagination in blue. 
But will need to wait until it's merged with develop and have it deployed on a server to do the real final test.

**Comment by developpeurweb** [comment]
Fixed by GH-3627

**Comment by KateChuen** [comment]
Tested on dev10, with theme calydon enabled. 
It's now fixed. 
![Screen Shot 2019-11-13 at 3 15 54 PM](https://user-images.githubusercontent.com/45409515/68800832-d2019900-0628-11ea-9a36-244dd4661f5f.png)
