### ISSUE TITLE
Structure public API of ngrx selectors

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#3239]
Currently we have many ngrx selectors with general names exported from `@spartacus/core`, i.e.:
- `getDetails` to get user details
- `getRefresh` to get flag `refresh` in cart state
- `getIndex` to get page index for CMS page data

We should review all our selectors and make sure they have precise names. We can consider typescript namespaces.

**Comment by marlass** [comment]
Some fixes for cart selectors in #3083

**Comment by Platonn** [comment]
It also applies to the actions, i.e. `AddEntry` is a ngrx action for adding entry to the cart.

**Comment by znikola** [comment]
The ticket for ngrx actions is #3318
PR: #3311
