### ISSUE TITLE
PDP only displays a list of [product:CMSTabParagraphContainer.tabs.TabPanelContainer]

### ISSUE THREAD

**Issue by josecervera** [SAP/cloud-commerce-spartacus-storefront#3240]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  0.1.0-beta
- Commerce: 1905

## Steps to Reproduce
Connect to the PDP

## Observed Results

A very long list of divs with the text [product:CMSTabParagraphContainer.tabs.TabPanelContainer]
![image](https://user-images.githubusercontent.com/1150648/59678411-a9d25300-91cc-11e9-8faf-f97dfc07d8d6.png)

## Expected Results
The regular PDP

**Comment by LTiger14** [comment]
Resolved by using the latest version of the `spartacussampledataaddon`.

**Comment by arunnair1991** [comment]
Hi,
I tried addon from below link, still I have the same issue. 
https://sap.github.io/cloud-commerce-spartacus-storefront-docs/assets/other/spartacussampledataaddon.zip
Could you see the reason for this?

**Comment by LTiger14** [comment]
@arunnair1991 This provided zip contains all of the right CMS changes. Did you follow all the steps in the guide https://sap.github.io/cloud-commerce-spartacus-storefront-docs/installing-sap-commerce-cloud in the `Installing the Spartacus sample data addon` section?

Also, did you specify in you `app.module.ts` to use the `electronics-spa` content catalog?

**Comment by devzom** [comment]
Look into https://github.com/SAP/spartacus/issues/7079#issuecomment-1049780638
