### ISSUE TITLE
Add `details` option for `getActive` in `cart.service.ts`

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3241]
To simplify things I decided to use everywhere `loadCart` with details.

Proper API for this looks like this.

`getActive(details?: Boolean = true`)`

We could then only load basic information about cart if every call will be with `false` flag. If one component would need details, then we switch to details mode.

Improvement for #2981

**Comment by Platonn** [comment]
The difference between loading mini cart and detailed cart was dropped in PR https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3083 . So I close this ticket - won't do
