### ISSUE TITLE
Updates to subtotals: Handle net=true, fix discount confusion

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3244]
1. Handling net=true or false
2. Avoiding confusion related to discounts 
In all locations where subtotal is displayed

Example of final:
<img src=https://user-images.githubusercontent.com/4998145/59715138-34bd4880-91e1-11e9-9428-1be2d3c1e648.png width=500>

**1. The "net" setting in basestore** 
`Base Commerce > Base Store > Electronics > Essential Properties`
handles whether tax is added in cumulative totals or is kept separate from totals.
Ootb it's set to false.

To explain further, given the following (ignoring the "discounts" problem):
Subtotal = $100
Shipping = $5
Tax = 10%

With **Net=true**, we should be displaying:
Subtotal = $100
Shipping = $5
Tax (10%) = $10.50
Total with tax = $115.50

With **Net=False**, we should be displaying:
Subtotal = $100
Estimated shipping = $5
Total = $105.00
_The total does not include tax of $10._

To do for 'net' setting:

When net=false, hide the "sales tax" row, and display
"The order total does not include tax of $10."

When net=true, display sales tax line, and totals will look logical.

**2. Discounts in subtotals are confusing**

Currently we list:
Subtotal
Shipping
**Discount**
... but the subtotal returned by OCC already includes the discount.

_Display the following instead:_
Subtotal after discounts: $ OCC `subtotal`
Shipping: $
Sales tax (if net=true): $
Total: $

(Note: we wanted to display "total before discounts") but we don't get that value from backend yet.

Note that the subtotal includes coupon discounts too, for e.g. if it's an order discount, it's in orderDiscounts field.

**3 remove the display of the promotion text e.g. Hide "Buy over $200"...**

**Comment by WeizhengSap** [comment]
When `net=false`:
![Screen Shot 2019-06-18 at 4 12 21 PM](https://user-images.githubusercontent.com/44440575/59716367-e2c9f200-91e3-11e9-89d3-fe7c148ae7f4.png)

When `net=true`:
![Screen Shot 2019-06-18 at 4 05 55 PM](https://user-images.githubusercontent.com/44440575/59716395-ee1d1d80-91e3-11e9-8d09-ea15dabd4d4c.png)

My branch is: feature/GH-3244
Will ask UI devs to make the cart summary section look better.

**Comment by giancorderoortiz** [comment]
QA comments:
When "net = true"
1. The label "Total with tax" is not displayed. 🆖 
2. The "Total" calculation doesn't include shipping costs. Therefore, for case in description $110.50 is shown insteaf of $115.50 (which includes $5 for shipping) 🆖 

**Discounts:**
1. "Subtotal" label changes to "Subtotal after discount"correctly 🆗 
2. Shipping cost is initially set to "TBD", which is ok. ℹ️ 
3. Once shipping method is selected, "Shipping" cost is updated with correct amount 🆗 
4. However, when shipping method is changed/switched, the subtotal amount changes. This is an additional bug. See https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3350 🆖 

**Promotion Text"
1. Promotion text "Buy over $200..." is still visible, making the whole thing very very confusing.

**Comment by giancorderoortiz** [comment]
![promotion-still-visible](https://user-images.githubusercontent.com/46171897/60042565-04b3f080-968c-11e9-9b7a-463822a31578.png)
