### ISSUE TITLE
Page Title is not replaced in Main Page

### ISSUE THREAD

**Issue by tbaiocco** [SAP/cloud-commerce-spartacus-storefront#3247]
When using custom meta resolver (as shown in training: https://github.com/tobi-or-not-tobi/spartacus-bootcamp) the Main Page remains with the last page title if navigating thru the link in Left upper corner (SAP).

## Environment Details

- Spartacus:  0.1.0-beta.1
- Browser: Chrome 75.0.3770.90
- OS: macOS 10.14.5
- Device: macBook Pro
- Other environment details: none

## Steps to Reproduce
Use the code of training, click in Login and after clicking on the link to the home page (SAP in the top left corner)

## Observed Results
Title remains the as previous page

## Expected Results
Title of the Main Page should be shown

## Repository Used
https://github.com/tobi-or-not-tobi/spartacus-bootcamp

## Offer to Fix
NO

## Additional Information
None

**Comment by hackergil** [comment]
Unable to reproduce using the latest spa libs (1.0.1)
