### ISSUE TITLE
Password validator to match backend regex

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#3253]
## Steps to Reproduce

Go to register page
add the special characters, such as -
- is accepted in the backend, but not in the frontend

## Observed Results

- is accepted in the backend, but not in the frontend
Therefore, you get an error validation saying that we still need to include one special character

## Expected Results

- Should allow special missing characters from the backend

## Additional Information

Found in custom-form-validators.ts - frontend takes 
<img width="124" alt="Screen Shot 2019-06-18 at 3 09 46 PM" src="https://user-images.githubusercontent.com/29099466/59712432-3b48c180-91db-11e9-87b1-4bd7ea0fa16a.png">

Found in validators-v2-spring.xml - backend takes
<img width="127" alt="Screen Shot 2019-06-18 at 3 11 04 PM" src="https://user-images.githubusercontent.com/29099466/59712483-50255500-91db-11e9-9a0e-48bd8633266e.png">

**Comment by bgambocjaviniar** [comment]
PR: GH-3254

**Comment by bgambocjaviniar** [comment]
For QA:

- go to register page,
create an account with the usual password as before, but for the special character, test using the *-* instead.

For more extra testing, try creating an account with each of those special characters shown above.

**Comment by giancorderoortiz** [comment]
Waiting for confirmation from Tobias and Bill.

**Comment by Xymmer** [comment]
The validation in storefront should match the OCC rules

**Comment by giancorderoortiz** [comment]
Test successful 👍
