### ISSUE TITLE
Fix being unable to pay for an item when you have a default payment method

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3255]
How to reproduce:

1. Start the process of purchasing an item
2. When entering payment details, select that you want to set it as default
3. Continue as usual and place the order
4. Start the process of purchasing a second item
5. When on the payment details page, select the default payment and press continue (error)
6. Add another payment
7. Continue as usual and place the order
8. Start of the process of purchasing a third item
9. When on the payment details page, select ANY payment and press continue (error)

![Screen Shot 2019-06-18 at 3 12 22 PM](https://user-images.githubusercontent.com/34665674/59712595-8a8ef200-91db-11e9-9ede-6ea2f29bd93c.png)

**Comment by LTiger14** [comment]
While fixing this error I discovered that the billing address is broken as a whole. It's not possible to have separate billing address on a payment method and the form does not have regions so can't add Canada or US.

Will fix by using the generic address form.

**Comment by LTiger14** [comment]
QA Steps:

1. In a new account
2. Add a product to cart and checkout. Create a first payment method (set it as default). Finish checkout
3. Add another product to cart and checkout with a new payment method (set a different billing address than shipping). You should not see any errors in the console.
4. In the order summary make sure the billing address is not the same as the shipping address.

**Comment by LTiger14** [comment]
### Note

There is an issue with the billing address in the backend. The sop mapping for the `hybris_billTo_region` returns an empty string but it should be `billTo_state`. There was a backend issue RAY-234 that was done, it will be reopened to fix the issue.

In the meantime to test it the value can be hardcoded in HAC:

1. Open HAC
2. Go to Platform > Configuration
3. Create a property with key `mockup.payment.label.billTo.region` with value `billTo_state` & add it

**Comment by LTiger14** [comment]
### QA Steps

See above comment ⬆️ before beginning the steps make sure this value exists on the test server

In a new account
1. Add a product to cart and checkout. Create a first payment method (set it as default). Finish checkout
2. Add another product to cart and checkout with a new payment method (set a different billing address than shipping). You should not see any errors in the console.
3. In the order summary make sure the billing address is not the same as the shipping address.

**Comment by giancorderoortiz** [comment]
I see a fix now. 
However inconsistencies with how billing region/state is stored in backend need to be taken care of. 
Shipping region/state is stored in backend instead of the one used with payment method. 

![order](https://user-images.githubusercontent.com/46171897/59934086-c4990780-9418-11e9-9f7a-0a2ec12f022e.png)
![billingaddress_backoffice](https://user-images.githubusercontent.com/46171897/59934084-c4007100-9418-11e9-814b-c35095ae238e.png)
![billingaddress_state](https://user-images.githubusercontent.com/46171897/59934085-c4007100-9418-11e9-828e-fe0999e9f684.png)
