### ISSUE TITLE
Cart-level promotions don't appear for certain promotions

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3258]
Enable this promotion and disable all others: order_threshold_free_gift_main

Add LEGRIA HF S100 (product ID 1986316) to the cart.
A tripod is automatically added to the cart at 0$ - it's a free gift.

But the cart page isn't displaying any cart level promotion info:
![image](https://user-images.githubusercontent.com/4998145/59724491-06973300-91f8-11e9-88dc-1895fb1185e1.png)

But the $20 off over $200 one is working
![image](https://user-images.githubusercontent.com/4998145/59724662-abb20b80-91f8-11e9-9f78-4475d76a6013.png)

For the buy over 500, get tripod free, the occ call returns promo info 
```
{
    "type": "cartWsDTO",
    "appliedOrderPromotions": [],
    "appliedProductPromotions": [
        {
            "consumedEntries": [
                {
                    "adjustedUnitPrice": 0,
                    "orderEntryNumber": 1,
                    "quantity": 1
                }
            ],
            "description": "Buy over $500.00 get 1 Remote Control Tripod VCT-80AV free",
            "promotion": {
                "code": "order_threshold_free_gift_main",
                "couldFireMessages": [],
                "description": "A free gift (Product) is added to the cart when the threshold order value is exceeded",
                "firedMessages": [],
                "promotionType": "Rule Based Promotion"
            }
        }
```

**Comment by RadhepS** [comment]
![Screen Shot 2019-06-21 at 11 06 44 AM](https://user-images.githubusercontent.com/34665674/59932263-ca8ce980-9414-11e9-8ea9-6acdb45272f4.png)

Now that we display free products, removing the free product results in an error. (This case was not handled before)
This needs to be fixed before I push my changes.

**Comment by RadhepS** [comment]
Merged to develop (prior to 1.0.1 branch change)

**Comment by RadhepS** [comment]
QA steps:

1. Navigate to backoffice
2. Go to Marketing > Promotion Rules
3. Disable/Enable some or all promotions that are in the Rule Group 'orderPromotionGroup' or 'productPromotionGroup'.
4. Add items to cart that should trigger those promotions
5. Go to the cart page

Expected result:
Promotion messages for those promotions should appear

**Comment by giancorderoortiz** [comment]
Overall, I see a fix for this issue. 
I tested with promotion: "Spend over $500 and get a remote controlled tripod free". 🆗 
I see the promotion applied correctly in cart. 🆗 

However, the free item (i.e. tripod) is left as a removable item in cart, and when the "remove" button is clicked, the cart becomes stale and quantities cannot be changed afterwards for any other of the cart items. 🆖 🙅‍♂ 
Please disable "remove" or qty update for free item.

**Comment by giancorderoortiz** [comment]
![promotion1](https://user-images.githubusercontent.com/46171897/60397130-918cfd00-9b17-11e9-9b81-c335d750c0c7.png)
![removebtn_ng](https://user-images.githubusercontent.com/46171897/60397131-92259380-9b17-11e9-811d-8cd3759effec.png)
![wrong-remove-btn](https://user-images.githubusercontent.com/46171897/60397132-92259380-9b17-11e9-9ef4-6296a962dced.png)

**Comment by RadhepS** [comment]
A ticket for this has been created already. Spoke with Bill about it previously and he said it was OK.
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3435

Closed

**Comment by giancorderoortiz** [comment]
Well, in fact, further testing is needed. I stopped once I saw this issue.

**Comment by KateChuen** [comment]
I can update the qty of the free product. 
![Screen Shot 2019-07-05 at 12 30 52 PM](https://user-images.githubusercontent.com/45409515/60735390-21b8b100-9f21-11e9-9faa-8ad466032a8e.png)

The first time I update it, I get an error during checkout. Although the error isn't clear to the customer, the qty gets reset to 1. 
![Screen Shot 2019-07-05 at 12 24 13 PM](https://user-images.githubusercontent.com/45409515/60735407-309f6380-9f21-11e9-8b2f-84e96c809260.png)

The second time I update it, I don't even get an error during checkout and the qty gets reset to 1.

**Comment by giancorderoortiz** [comment]
waiting for fix of #3435

**Comment by KateChuen** [comment]
To be tested after #3435 is fixed.

**Comment by giancorderoortiz** [comment]
Test successful 🆗 
Cart behaves properly with/without promotion enabled. 
However, performance hit is seen when promotion is enabled and quantities are modified in cart. 
(This should be investigated further).
