### ISSUE TITLE
Styling: placeholder thumbnail in PDP too high

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#3272]
Using devcom19 as a backend.
Go to PDP `/electronics-spa/en/USD/product/3514521/DSC-WX1`

![obraz](https://user-images.githubusercontent.com/4001059/59750919-e01cda80-927f-11e9-87e5-844544e0cac2.png)

**Comment by Xymmer** [comment]
has been fixed
