### ISSUE TITLE
[ready to retest] "Battery Chargers" breadcrumb in PDP returns a 404  

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3274]
**Steps to Reproduce:**
1. Search for chargers. 
2. In product listing page, click on any of the available results. 
3. In product details page, click on "battery chargers" breadcrumb. 

**Expected Results:**
3. Product listing page of "battery chargers", or "chargers". 

**Actual Results:** 
3. 404. 

Related to https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3149

![pdp_a](https://user-images.githubusercontent.com/46171897/59761473-f36d7d00-9262-11e9-82f4-8433d36ee5c8.png)
![404](https://user-images.githubusercontent.com/46171897/59761483-f9635e00-9262-11e9-89bc-11b34698ed14.png)
![404_a](https://user-images.githubusercontent.com/46171897/59761484-f9635e00-9262-11e9-92b7-7511c3c8bffc.png)

**Comment by Pucek9** [comment]
There is missing Battery-Chargers category. It probably should indicate to Power-Supplies ~`Open-Catalogue/Components/Power-Supplies/Battery-Chargers/c/829`~
`Open-Catalogue/Components/Power-Supplies/c/816`

**Comment by bgambocjaviniar** [comment]
problem is missing that because of the request being invalid. Checking why the backend does not support the code for 829

**Comment by bgambocjaviniar** [comment]
created a ticket for smartedit / cmsocc 
https://jira.hybris.com/browse/CMSX-8984

**Comment by KateChuen** [comment]
Tested on dev19, with Commerce Suite 2005.0.200114002.
It works now. No more 404.
Please note that the fix is only in 2005. If you use 1905, you'll still see the 404 error.
