### ISSUE TITLE
Navigation links are smaller than hoverable components

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3275]
After hover on navigation, css is changed but I can't click link
![image](https://user-images.githubusercontent.com/8040837/59766079-b70c4200-929f-11e9-8ed4-9af04c7588e4.png)
Link is available only after hover text inside
![image](https://user-images.githubusercontent.com/8040837/59766159-dc00b500-929f-11e9-9130-c76eacaa1f17.png)

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3287

**Comment by KateChuen** [comment]
Tested on dev17. Now the link is available when hover on navigation, and able to click and go to the category page. 
<img width="1100" alt="Screen Shot 2019-06-25 at 10 27 18 AM" src="https://user-images.githubusercontent.com/45409515/60107260-9d05b000-9734-11e9-8d0d-1a33da1ee6a5.png">
