### ISSUE TITLE
add to home on ios - improvements

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3292]
You can add to home from Safari now on iOS from the share button, but we don't see the popup. Add to Home support on iOS was iffy at the start so maybe something broke our implementation.

See for e.g.
https://stackoverflow.com/questions/54001523/is-add-to-home-screen-feature-of-pwa-supports-in-ios

Add to Home works on Android and our site passes all related PWA tests, like having a manifest.

**Comment by znikola** [comment]
There's still no way to show a prompt for add to home in safari.
Added splash screen images, but waiting for UI team to provide the proper images.

**Comment by Xymmer** [comment]
if this is in code review, was something done?

**Comment by znikola** [comment]
I added a few meta tags for iOS devices and added splash screen image support with an example splash screen for all iOS device screen sizes.
