### ISSUE TITLE
[HOLD] Ipad Pro. My Account Menu Fails to Collapse/Close/Disappear. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3299]
Device: iPad Pro. 
iOS: 12.3.1

Unable to collapse my Account menu with either single tap, double tap, triple tap, etc. 
User has to tap away onto any other component that receives tap/click events. 

It appears to be reproducible in desktop as well. 

![doubletapping_ipadpro](https://user-images.githubusercontent.com/46171897/59853898-cd69da80-933f-11e9-9f5d-021ef4ff7dc6.png)

**Comment by KateChuen** [comment]
I believe this has been fixed through https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3473
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3473 was tested on mac and iphone8+.
Please retest this ticket on ipad pro.

**Comment by giancorderoortiz** [comment]
Retest successful 👍
