### ISSUE TITLE
Unstable E2E: Payment Methods

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3300]
regression/my-account/payment-methods failed on Jenkins because it is unstable.

`576p resolution - Payment Methods should go to payment details page for login user should see payment method card:
     CypressError: Timed out retrying: Expected to find element: 'cx-address-form', but never found it.`

**Comment by bgambocjaviniar** [comment]
ran it like 8 times in headless, and a few times in the UI. No problemo so far
