### ISSUE TITLE
Failing E2E: Currency Checkout Page

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3301]
regression/site-context/currency/currency-checkout-page.e2e-spec.ts failed on Jenkins because it is unstable.

You can take a look at this[ build ](https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/lastBuild/)on Jenkins to see the list of errors

**Comment by RadhepS** [comment]
This e2e test is failing because checkout is broken.

Once https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3255 is merged, I will re-check to make sure it works.

**Comment by Xymmer** [comment]
#3255 is merged

**Comment by RadhepS** [comment]
Test still does not work because checkout is broken.

Closing the ticket as the test is functional but the underlying feature us broken.
