### ISSUE TITLE
[retest] User A's Order Number Visible After Registering User B. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3315]
**Steps to Reproduce:** 
1. Navigate to Spartacus storefront. 
2. Login as userA. 
3. Add items to cart and checkout. 
4. From My Account, select Order History
5. Click on order placed on step 3. 
6. Sign out. 
7. Click on Sign In / Register button in homepage. 
8. Register user B. 

**Expected Results:** 
8. User B is redirected to homepage. 

**Actual Results:**
8. User B is redirected to order details page within the context of user A. 🆖 
8.a. Order details are not visible, yet the order number is visible both through error message and api method response in dev-tools. 

This is an access violation situation. 

See below images. 
![userA-orderDetails](https://user-images.githubusercontent.com/46171897/59924591-0ff4eb00-9404-11e9-9769-91d50db5e9e9.png)
![orderDetailsPage-userB_1](https://user-images.githubusercontent.com/46171897/59924603-17b48f80-9404-11e9-97a2-9da4c9111aad.png)
![redirect-afterregistration-userB](https://user-images.githubusercontent.com/46171897/59924604-17b48f80-9404-11e9-8615-7d0afa01dacf.png)

**Comment by Pucek9** [comment]
@giancorderoortiz 
I can't reproduce that situation.
In point 8. after sign out/sign in I'm redirecting to home page

**Comment by giancorderoortiz** [comment]
Unable to reproduce any longer. 
Issue seems to be fixed. 
Tested with dev-com17, dev-com19
