### ISSUE TITLE
Index 5 out of bound error when searching

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3316]
Was able to trigger a weird message from backend. Although a customer would only see this if he were trying to hack the storefront, is there a security mitigation we can do?

```
        routing: {           routes: {             product: {               paths: ['product/108803_medieval_blue', 'product/300495178']                  }             }         },
```

![image](https://user-images.githubusercontent.com/4998145/59933990-81d72f80-9418-11e9-9947-a2b4b82b8f8e.png)

**Comment by hackergil** [comment]
Let's try to reproduce with the given settings

**Comment by LTiger14** [comment]
I don't get the same error. I can see some errors in the console and the search stops working until I refresh the page. Will investigate.

**Comment by LTiger14** [comment]
I was able to reproduce this. This is the message returned by the backend so it's not our issue.

**Comment by LTiger14** [comment]
This is backend related. Opened RAY-375. Needs retesting after fix.

**Comment by KateChuen** [comment]
https://jira.hybris.com/browse/RAY-375 was closed as won't fix, since they weren't able to reproduce it. 
We need to investigate further on our side, and verify if we're sending this data in a weird way.

**Comment by KateChuen** [comment]
Bill said to close it, the issue had to do with an apparel product, and we didn’t work well with variants back when.
