### ISSUE TITLE
Fix add to cart fonts and spacing

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3317]
We'll have a review of this important area in the future, but for now do something like this:
- price/qty/total: not bold, smaller, gray color like cart page
- Remove button: move to right, use a link color, try not being bold, we don't want to draw attention to it
- Adjust spacing so that the labels look like they belong to their numbers, right now my eye goes straight down.

![image](https://user-images.githubusercontent.com/4998145/59934464-97008e00-9419-11e9-9e59-f786d908bc2c.png)

**Comment by mikelMHybris** [comment]
@Xymmer t
![Screen Shot 2019-06-26 at 10 47 32 AM](https://user-images.githubusercontent.com/30266610/60190982-8da06880-9801-11e9-92d3-4eeb36f83a53.png)
he component that is used to show the product information in the add to cart modal is also used for the cart page. I can change the font weights for the labels but to change the html structure to change the remove link will affect the cart page.

**Comment by Xymmer** [comment]
it's fine as is for now then

**Comment by KateChuen** [comment]
Tested on dev17. Add to cart modal is as per screenshot that Bill is ok with for now. 
The rest of the improvements will be done in the future.
Also noticed that one field isn't named correctly. Opened ticket #3451
