### ISSUE TITLE
[ready to retest] Retest billing address when RAY-234 is fixed

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3322]
When https://jira.hybris.com/browse/RAY-234 is fixed, let's retest to make sure setting billing address works ok.

**Comment by Xymmer** [comment]
RAY-234 is in 1905.1
We can retest this now with our Model T as long as that server is updated (ask Gil about it)

**Comment by KateChuen** [comment]
CCv2 currently has 1905.0

**Comment by Xymmer** [comment]
no longer needs testing specifically on modelt

**Comment by KateChuen** [comment]
Tested on dev3, with 1905.10 backend. It works now.
Tested with a canadian shipping address, and a united states billing address.
