### ISSUE TITLE
Unable to add a payment method + billing address issue

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3323]
![Screen Shot 2019-06-21 at 3 51 49 PM](https://user-images.githubusercontent.com/34665674/59947915-86154400-943c-11e9-9df9-17ac078281f5.png)

Payment details throws an error after you enter your details and press "continue".
This also prevents the user from continuing the order process.

**Comment by bgambocjaviniar** [comment]
error is not related to unserializable
fix for that will be in GH-3263, but adding payment details is broken for another unknown reason

**Comment by kacperknapik** [comment]
this bug was introduced with this PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3294

@LTiger14 	why do we exactly add region to billing address? we discussed it with @WeizhengSap 	and the final decision was not to add it. 

additionally you changed the whole step logic and `router.go()` is never called

**Comment by Xymmer** [comment]
Louis' ticket was #3255

**Comment by LTiger14** [comment]
We need the regions in billing address to support a billing address from a different country than the shipping address when one has regions.

The additional improvements to the step logic do not cause this issue so they can remain as they fix other issues.

**Comment by bgambocjaviniar** [comment]
Fix for this is because you forgot to import the StateModule in cart-store.module.ts

**Comment by LTiger14** [comment]
### QA Steps:

*Before QA*: go to HAC and create a property with key `mockup.payment.label.billTo.region` with value `billTo_state` & add it

- Create a new account
- Add a product to cart and checkout (full checkout) with a new address and new payment method
- Add a product to cart and checkout (full checkout) same address, new payment with separate billing address from a different country (with region)
- Go to backoffice and check the orders
- You should see the correct payment address with the region

**Comment by KateChuen** [comment]
Tested on dev2

- [x] go to HAC and create a property with key mockup.payment.label.billTo.region with value billTo_state & add it
- [x] Create a new account
- [x] Add a product to cart and checkout (full checkout) with a new address and new payment method
- [x] Add a product to cart and checkout (full checkout) same address, new payment with separate billing address from a different country (with region)
- [x] Go to backoffice and check the orders. You should see the correct payment address with the region

- Please note that if we don't add the key in HAC, then it won't work. User won't be able to add another payment method with a different billing add. And this is documented in https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/issues/145
