### ISSUE TITLE
Hamburger menu's overlay doesn't cover pagination button

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3335]
Need to update z-index
![image](https://user-images.githubusercontent.com/8040837/60013292-5c4b5f80-967e-11e9-90f7-6a48c677b6a5.png)

**Comment by RadhepS** [comment]
Merged to develop (prior to 1.0.1 branch change)

**Comment by giancorderoortiz** [comment]
Test ok.
