### ISSUE TITLE
Friendly pipe for PDP url

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3336]
Some special pipes are introduced to control semantic links in Spartacus. For example, a link to a PDP can be created with the following syntax:

```html
<a [routerLink]="{ cxRoute: 'product', params: item } | cxUrl">link</a>
```

The `cxUrl` pipe ensures that the correct PDP link is created, based on routing configuration and available data. While this is all fine, the syntax is quite generic to allow for all kinds of router link. Customers could benefit from an easier to remember url. The new syntax for PDP links could be:, but it's just an initial proposal.

```html
<a [routerLink]="item | cxProductUrl">link</a>
```

**Comment by reyhanehsalkhi** [comment]
Instructions to test:

1- Replace the cxUrl Pipe (anywhere in the code where there is link to PDP page) with the cxProductURL syntax. 

example : inside the <code>product-list-item.component.html<code>

**Comment by KateChuen** [comment]
Tested locally. It works.
