### ISSUE TITLE
Internal server error (500) is not captured in UI

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3340]
After try login (dev-17) I got 500, and there is no handler shows global message for that code (unknown-error.handler supports only console warn in developer mode).
```
{
  "error" : "server_error",
  "error_description" : "Internal Server Error"
}
```

**Comment by WeizhengSap** [comment]
To code reviewer/QA:
To simulate "internal server error (500)", I did this:
In `getPage()` function inside `de.hybris.platform.cmsoccaddon.controllers.PageController.java`, change this `@ResponseStatus(HttpStatus.OK)` to `@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)`.

**Comment by KateChuen** [comment]
Tested on dev2.
Now, the 500 error is handled on the UI.
<img width="1432" alt="Screen Shot 2019-07-25 at 11 03 16 AM" src="https://user-images.githubusercontent.com/45409515/61891366-87241000-aed7-11e9-83a4-e547215ddd34.png">

**Comment by RadhepS** [comment]
This ticket is being reverted because it's a breaking change: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3844

**Comment by WeizhengSap** [comment]
new PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3852
