### ISSUE TITLE
[mtl] two global-messages.scss files error with incremental libs

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3342]
using latest incrementals to build a new storefront app
is this really an error or just a release issue?

angular says:

```
@import './global-message';
       ^
      It's not clear which file to import. Found:
  node_modules/@spartacus/styles/scss/components/content/global-message/_global-message.scss
  node_modules/@spartacus/styles/scss/components/content/global-message/global-message.scss
```

![image](https://user-images.githubusercontent.com/4998145/60026825-564b8380-966a-11e9-8a53-41a7ce52c88b.png)

**Comment by Zeyber** [comment]
For me when I pull the latest @sparticus/styles, I only have `global-message.scss` while all have preceeding `_`.

![image](https://user-images.githubusercontent.com/11735817/60080658-9e34de00-9730-11e9-87bf-157594535faf.png)

@Xymmer Do you have both files?

**Comment by marlass** [comment]
Looked at incremental builds and our repository.
It is an issue with releasing incremental builds. Deleted files are not removed.
I am not familiar with incremental build publishing, but in our repository everything is correct.

@hackergil How are those libs build?

**Comment by marlass** [comment]
Nevermind, I found the script. I will check it and fix the issue.

**Comment by giancorderoortiz** [comment]
please add QA steps.

**Comment by marlass** [comment]
To test:
- Check here (https://github.com/SAP/cloud-commerce-spartacus-storefront-styles-builds/tree/master/scss/components/content/global-message) if only one global-message file exists
- check if incremental libs are still working correctly
- git history for incremental libs should be preserved

**Comment by bgambocjaviniar** [comment]
Code is good, but need to merge to further test because everything snapshot is taken from develop, therefore there is still two global message on that link above.

**Comment by KateChuen** [comment]
Tried to test this by following this doc (https://sap.github.io/cloud-commerce-spartacus-storefront-docs/building-the-spartacus-storefront-from-libraries/), but getting compilation errors like: 
ERROR in node_modules/@ngrx/effects/src/actions.d.ts(7,103): error TS1005: ';' expected.
node_modules/@ngrx/effects/src/actions.d.ts(7,150): error TS1005: '(' expected.
node_modules/@ngrx/effects/src/actions.d.ts(32,106): error TS1005: '>' expected.
node_modules/@ngrx/effects/src/actions.d.ts(32,158): error TS1005: ')' expected.
node_modules/@ngrx/effects/src/actions.d.ts(32,162): error TS1005: ';' expected.

Letting @giancorderoortiz or @Xymmer try.

**Comment by Xymmer** [comment]
works so passing but interested in the error Kate returned
