### ISSUE TITLE
Add check for baseSite selectors

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#3345]
Just add check (because of CDS breaking):
`state && state.baseSite && state.baseSite.activeSite` in the `core/src/site-context/store/selectors/base-site.selectors.ts`

**Comment by giancorderoortiz** [comment]
Please add QA steps.

**Comment by mirkosoft** [comment]
Hmm, not sure as it was only with the cds functionality, tight @tobi-or-not-tobi ?

**Comment by giancorderoortiz** [comment]
Manual smoke test successful 🆗
