### ISSUE TITLE
Move opinionated config of translation chunks to the assets library

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#3347]
The translation resources are optional so were moved to the `@spartacus/assets` library in https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1775. But the default translation chunks config (which tightly depend on the opinionated translation resources) still lives in our `@spartacus/core`. We should also move it (from the `default-i18n-config.ts`) to the public_api of the `assets` library and export by name i.e. `translationChunksConfig`. The `chunks` key should be removed from the `default-i18n-config.ts` then.

As a result, the app.module should look like:

```typescript
import { translations, translationChunksConfig } from '@spartacus/assets';

...

      i18n: {
        resources: translations,
        chunks: translationChunksConfig
      },
```

The documentation and the `spartacus-installation` script should be also updated.

**Comment by KateChuen** [comment]
How to test this? Just a smoke test to make sure it didn't break anything?

**Comment by Platonn** [comment]
QA steps: just smoke tests that i18n still work.

**Comment by KateChuen** [comment]
Tested on dev2
Smoke tests ok. 
Just one issue found but it was there before this change:
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3414
And a few styling tickets:
#3415, #3416, #3417
