### ISSUE TITLE
Subtotal should not include shipping

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3350]
We fixed issues with discounts in #3244.
Not sure it was always like this, but shipping should not be part of the subtotal.
Check cart, checkout, confirmation, order details.
Remember e2e tests.

<img src=https://user-images.githubusercontent.com/4998145/60037206-f01d2b80-967e-11e9-857c-5373ed34fde1.png width=200>

From what i can see, the subtotal.value response doesn't include shipping.
We want to avoid calculating this in Spartacus because we lose the "formatted value".

```
    "deliveryCost": {
        "currencyIso": "USD",
        "formattedValue": "$11.99",
        "priceType": "BUY",
        "value": 11.99
    },
```
and

```
   "subTotal": {
        "currencyIso": "USD",
        "formattedValue": "$79.11",
        "priceType": "BUY",
        "value": 79.11
    },
    "totalDiscounts": {
        "currencyIso": "USD",
        "formattedValue": "$0.00",
        "priceType": "BUY",
        "value": 0
    },
    "totalItems": 1,
    "totalPrice": {
        "currencyIso": "USD",
        "formattedValue": "$91.10",
        "priceType": "BUY",
        "value": 91.1
    },
    "totalPriceWithTax": {
        "currencyIso": "USD",
        "formattedValue": "$91.10",
        "priceType": "BUY",
        "value": 91.1
    },
    "totalTax": {
        "currencyIso": "USD",
        "formattedValue": "$4.34",
        "priceType": "BUY",
        "value": 4.34
    },
```

**Comment by giancorderoortiz** [comment]
QA Comments when "net=true":
1. In Checkout -> Delivery mode, once selected, Estimated shipping should update immediately, and not after clicking on "continue" button. 🆖 
2. Using product ID 4812254 (500D + 18-55mm...) as reference
2.a. Before shipping method is selected. Subtotal = $863.70
2.b. After Standard Delivery is selected Subtotal = $873.69
2.c. After Premium Delivery is selected Subtotal = $880.69

**Comment by giancorderoortiz** [comment]
![BeforeShippingSelection](https://user-images.githubusercontent.com/46171897/60045552-22d11f00-9693-11e9-90bf-2d1a2c5a1364.png)
![cart-view](https://user-images.githubusercontent.com/46171897/60045553-22d11f00-9693-11e9-8ead-63ea53a497fc.png)

**Standard Shipping Selection:** 
![StandardShipping](https://user-images.githubusercontent.com/46171897/60045584-33819500-9693-11e9-8ac7-98c5ae5cc1c4.png)

**Premium Delivery Selection:** 
![PremiumDelivery](https://user-images.githubusercontent.com/46171897/60045615-45633800-9693-11e9-8d32-c262eea1ff1b.png)

**Comment by Xymmer** [comment]
For (1), improvement to be done after 1.0 in #3351
For (2), you're confirming that subtotal displayed is including shipping when we don't want it right?

**Comment by giancorderoortiz** [comment]
Yes, correct for #2.

**Comment by Zeyber** [comment]
QA Steps:
- Add product to cart
- Go through checkout process to Review Order step
- Check order summary shows correct subtotal, shipping and total

**Comment by giancorderoortiz** [comment]
Test successful. 
Able to see that Subtotal doesn't include shipping cost. 
Much better now :-)
