### ISSUE TITLE
Remove ServerConfig

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3362]
The initial configuration for Spartacus contained the server config, which is why the root configuration was named `ServerConfig`. This is no longer the case and it's not logical to have any config extending from the ServerConfig. 
Also, because now ServerConfig contains only production flag, we should consider dropping it completely and switching to `isDevMode()` if possible.

**Comment by KateChuen** [comment]
How to test this ticket? Just a smoke test?
