### ISSUE TITLE
Failing E2E tests: The site context tests are failing

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3383]
the checkout site context tests are failing.
- currency-checkout-page.e2e-spec.ts
- language-checkout-page.e2e-spec.ts

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3387

**Comment by RadhepS** [comment]
Gil merged fixes to develop that also fixed this error so I am closing this ticket.
