### ISSUE TITLE
Remove old --cx-g-colors

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3398]
--cx-g-colors are no longer used by us in styles and should be updated to --cx-colors.

![image](https://user-images.githubusercontent.com/11735817/60158274-0b0fad00-97f1-11e9-8c71-dab664b6f3e1.png)

**Comment by RadhepS** [comment]
Merged to develop (prior to 1.0.1 branch change)

**Comment by giancorderoortiz** [comment]
ok
