### ISSUE TITLE
Add type-safe OCC endpoint configuration 

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3399]
In order to configure the endpoints for OCC, the dev needs to know the endpoint keys. These keys are currently any string, and the dev can only look at source code to understand the keys that must be used. 

Since OCC is fairly static, we can add the different keys in the model, and leave it open to add any strings. This small improvement will improve dev experience and saves a lot of time.

**Comment by LTiger14** [comment]
PR #3645

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by LTiger14** [comment]
Don't think this requires QA as it's an internal type.
