### ISSUE TITLE
Failing E2E Tests

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3404]
Following tests are failing:
cart-mobile.e2e-spec.ts
cart.e2e-spec.ts
currency-cart-page.e2e-spec.ts
currency-product-search-page.e2e-spec.ts
language-cart-page.e2e-spec.ts
language-product-search-page.e2e-spec.ts

**Comment by Xymmer** [comment]
Investigate the source of the problem and let Bill know if it's something we have to do in first RC or minor and can do later. Also recall that the footer was changed somehow and had caused commit-e2e-tests to fail.

**Comment by hackergil** [comment]
PR for cart tests above
Site context tests still failing due to #3413

**Comment by mirkosoft** [comment]
reviewing cart...

**Comment by mirkosoft** [comment]
cart PR #3420 approved
