### ISSUE TITLE
Language and currency changes don't refresh CMS data on the PLP

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#3413]
When you load the PLP for any given language or currency you can see the data is displayed correctly. If you change the language (or currency) the text driven by frontend translation updates but the product info remains in the original language.

![Screen Shot 2019-06-26 at 1 36 08 PM](https://user-images.githubusercontent.com/10605724/60201907-79676600-9817-11e9-892c-544ae692e01e.png)

After some digging I found the issue originated with the merge of this issue #3218

**Comment by Xymmer** [comment]
we had this ticket, now closed: #2870

**Comment by Xymmer** [comment]
i'm using a fresh source and dev17 and it's working for me
i put this int retest with actual server to get the deciding vote on if it's a bug

**Comment by KateChuen** [comment]
I've just tried on dev2 and it looks good on my side too.
I've changed the language & currency, back and forth, and reloaded the page, and it's reflected on pdp.

**Comment by marlass** [comment]
This is still an issue. I don't see any request to `search` endpoint after changing language or currency.

**Comment by giancorderoortiz** [comment]
I see a fix. 
Minor variations on order of products according to language is observed. 
Yet, that may be how backend returns list.
