### ISSUE TITLE
Homepage after registration is loaded in EN

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3414]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Go to homepage
Change the language to DE for eg.
Go to Register Page, and register a new user.

**Actual Result**
After the registration was successful, the homepage is loaded, but in EN.

**Comment by znikola** [comment]
Can't reproduce: after registration, homepage was shown on German.
