### ISSUE TITLE
Review stars are misaligned if 'Show reviews' is long

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3415]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
viewport 1100x710
Go to homepage
Change the language to DE for eg.
Go to a pdp page, eg: product 3595723

**Actual Result**
The star reviews are misaligned.

<img width="992" alt="Screen Shot 2019-06-26 at 2 02 31 PM" src="https://user-images.githubusercontent.com/45409515/60203921-bcc3d380-981b-11e9-8efa-d79bcd5cd9da.png">
<img width="1343" alt="Screen Shot 2019-06-26 at 2 03 41 PM" src="https://user-images.githubusercontent.com/45409515/60203922-bcc3d380-981b-11e9-87a9-16b8a9f44c1f.png">

**Comment by Xymmer** [comment]
will be fixed with translation
