### ISSUE TITLE
Orders placed on modelt remain in progress

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3428]
Very likely backend/modelt issue and not Spartacus, but we should fix it.
![image](https://user-images.githubusercontent.com/4998145/60262770-001a5280-98ad-11e9-9954-fd584a770f71.png)

**Comment by Pucek9** [comment]
@Xymmer 
We can config that in translations. There is one more "in process" occurence, should I update it? 
![image](https://user-images.githubusercontent.com/8040837/60423914-80afba80-9bef-11e9-9ede-7972250c18f2.png)

**Comment by Xymmer** [comment]
Hey Michal, not sure what you mean?

**Comment by WeizhengSap** [comment]
The order status or consignment status come from backend. This is a duplicate ticket of this: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3055
