### ISSUE TITLE
Allow for any carousel items [maybe 1.0.1]

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3430]
The current carousel is tightly coupled to products. In the image carousel on the PDP, there's already a misbehaviour, this ticket is about making the carousel flexible to render any items, including banner components. This will allow for introducing the rotating image component, that rotates over banners (which are actually (any)components).

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- Validate that the product carousel (homepage), product references and product images are rendered.
- (optional and not promised) validate on dev-19 the new rotating image component.

**Comment by KateChuen** [comment]
Tested on dev2. 

- [x] Validate that the product carousel (homepage), product references and product images are rendered.

- [x] (optional and not promised) validate on dev-2 the new rotating image component.
![Screen Shot 2019-06-28 at 11 43 07 AM](https://user-images.githubusercontent.com/45409515/60354325-f884a780-9999-11e9-9a14-509b95bebdba.png)
