### ISSUE TITLE
Unable to delete promotion item

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3435]
Problem: Unable to delete an item when it is applied via a promotion.
It is also not possible to continue the order process with this item in the cart.

![Screen Shot 2019-06-27 at 10 41 43 AM](https://user-images.githubusercontent.com/34665674/60275648-403afe80-98c8-11e9-8db7-3975eaaf5353.png)

How to repro:
1. Navigate to backoffice
2. Go to Marketing > Promotion Rules
3. For ease, disable all promotions except for `order_threshold_free_gift_main`
4. Trigger this promotion by adding products with a total sum larger than $500
5. Delete the tripod from the cart

Expected result: 
Deletes the tripod

Actual result: 
Error is thrown and item is not deleted

More information:
While looking into the issue, it seems like the back-end does not want to delete giveaway items.
There's a check to see if it is a giveaway item, if it is then don't delete.

**Comment by giancorderoortiz** [comment]
What is in fact more serious, is that no other cart items can be removed or changed quantities. 
Having a promotion must not invalidate the status of other cart items not participating in promotion bundles.

**Comment by RadhepS** [comment]
Yes, that is also the case.
Further note, a user is unable to place an order when they have a giveaway item in the cart.

**Comment by gladius-mtl** [comment]
What is the source of the problem? 

Once we know that, let's figure out the appropriate solution.

**Comment by giancorderoortiz** [comment]
Blocks testing of #3258

**Comment by plabadie** [comment]
Assessed that a non editable item according to the backend is not editable in the UI:

<img width="1280" alt="Screen Shot 2019-07-16 at 4 09 24 PM" src="https://user-images.githubusercontent.com/7065346/61326437-c02bf880-a7e4-11e9-903b-4a1c528986e0.png">

**Comment by giancorderoortiz** [comment]
Side effect of not being able to edit quantities of other cart items has been fixed. 
Test successful. :ok
