### ISSUE TITLE
Cover cxOutletRef usage with e2e tests

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#3441]
cxOutlets are first class extensibility mechanism, we should have it covered with e2e tests, to make sure they work correctly in all releases.

**Comment by kacperknapik** [comment]
- needs documentation
- add use cases to the shell app

**Comment by Platonn** [comment]
Docs for cxOutlet (and cxOutletRef) https://sap.github.io/cloud-commerce-spartacus-storefront-docs/page-layout/#using-outlets-to-override-page-templates
