### ISSUE TITLE
"ERROR in Expected array when reading property imports" when ivy is enabled

### ISSUE THREAD

**Issue by SerkanSipahi** [SAP/cloud-commerce-spartacus-storefront#3453]
## Environment Details
- Spartacus:  0.1.0-beta.1

## Steps to Reproduce
tsconfig.json
```
{
   "angularCompilerOptions": {
    "enableIvy": true,
  },
}
```
1.) `rm -rf node_modules`
2.) `npm i`
3.) `npm run start`

## Observed Results

```bash
ERROR in Expected array when reading property imports
```
## Expected Results
Compiled successfully.

## Offer to Fix
https://github.com/angular/angular/issues/29835

## Additional Information
Spread Syntax in modules should be avoided!

## I would be willing to submit a PR to fix this issue

[x] Yes
[ ] No

**Comment by SerkanSipahi** [comment]
Any infos, updates?

**Comment by Xymmer** [comment]
@znikola is this related to the work on ivy you're doing?

**Comment by znikola** [comment]
Sure @Xymmer, I'll take care of it.

**Comment by SerkanSipahi** [comment]
@znikola  FYI: Angular v8.1 is released an Ivy is enabled by default!

**Comment by znikola** [comment]
Thank for letting me know @SerkanSipahi !

**Comment by znikola** [comment]
This solves it: https://github.com/angular/angular/issues/29361#issuecomment-511050660

**Comment by znikola** [comment]
Can't reproduce. Since this is an older issue, it might have been fixed in the meantime. However, I encountered another error in the console, see: #3741 .
