### ISSUE TITLE
PDP: Qty doesn't get reloaded when we navigate to an upselling product

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3456]
**Environment Details**
Spartacus: Release 1.0
Browser: Chrome
Device: mac
Happens on: https://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Go to pdp of a product that has upselling products, for eg 1981415
Change the qty to anything, for eg 3
Click on an upselling product from that page

**Actual Result**
The quantity on the upselling product is set to 3. 
![Screen Shot 2019-06-28 at 11 21 32 AM](https://user-images.githubusercontent.com/45409515/60353319-cc682700-9997-11e9-95e1-de5289659f7d.png)

**Expected Result**
The qty should be by default 1.

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3573

**Comment by RadhepS** [comment]
QA steps:

1. Navigate to a product that has up-selling enabled (816802)
2. Increase the counter on this product
3. Navigate to one of the up-selling products

Expected result:
Counter is reset to 1

**Comment by KateChuen** [comment]
Tested on dev2. 
Counter is reset to 1 now.
