### ISSUE TITLE
Cart Page: Promotion displayed twice after cart merge

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3457]
**Environment Details**
Spartacus: Release 1.0
Browser: Chrome
Device: mac
Happens on: https://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login
Add 1 product >$200 to cart, for eg: 816802
Sign out
Add another product to cart
Click on "Proceed to checkout"
Login
Go to cart page.

**Actual Result**
The promotion is displayed twice
![Screen Shot 2019-06-28 at 11 30 15 AM](https://user-images.githubusercontent.com/45409515/60353819-d9394a80-9998-11e9-900d-416d9caf2bc1.png)

**Comment by Pucek9** [comment]
@KateChuen I can't get these promotions.
The minimum is `Buy over $500.00 get 1 Remote Control Tripod VCT-80AV free` and it isn't duplicated.
Additionally, after going to check out (merge) I got an error message
`item 8796134146092 no longer valid (was removed): object no longer valid`

**Comment by KateChuen** [comment]
I've reconfigured the promotions to what it was before. 
So you should be able to see it on dev19 now. 
I just reproduced the issue there again.

**Comment by Pucek9** [comment]
I verified that and it's a backend response.
```
"appliedOrderPromotions" : [ {
      "consumedEntries" : [ ],
      "description" : "Buy over $200.00 get $20.00 discount on cart",
      "promotion" : {
         "code" : "order_threshold_fixed_discount_main",
         "promotionType" : "Rule Based Promotion"
      }
   }, {
      "consumedEntries" : [ ],
      "description" : "Buy over $200.00 get $20.00 discount on cart",
      "promotion" : {
         "code" : "order_threshold_fixed_discount_main",
         "promotionType" : "Rule Based Promotion"
      }
   } ],
```
If we would like to avoid workarounds, we should fix it on the backend.

**Comment by gladius-mtl** [comment]
Remove one of the duplicate promotions. Use the promotion code to identify the duplicate.

Also create a ticket for the SAP Commerce Cloud Promotions team to fix this in the back end.

**Comment by WeizhengSap** [comment]
In my PR, I removed the duplicate promotions from cart data. But, it is definitely a backend issue. So, I created this ticket in jira: https://jira.hybris.com/browse/RAY-367

**Comment by giancorderoortiz** [comment]
Test successful. Cart promotion only shown once. 🆗 
However, upon cart merge I see a "cart not found" error message. 
The cart is eventually merged correctly.
