### ISSUE TITLE
[retest] Forgotten Password: Link to reset password in email redirects to login page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3459]
**Environment Details**
Spartacus: Release 1.0
Browser: Safari
Device: mac
Happens on: https://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Click on Forgot password
Enter your email add and click 'Send'
Go to the email and click on the link to reset password

**Actual Result**
The link brings you to the Login Page instead of the Reset password page. 
However the link in the email is ok, it's
http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/login/pw/change?token=Tgv4JbOoP4Wzqd6ov%2BtIRL%2BOaTVnCh8P%2Bwi5LIWpmVBBr2ngB19WZaAh7kFtO4PQlIcSAenKpPZ9lLhuDBV%2FDKMMAtaS6us6OxrS5dN5R66YIIbTfsYj34LZfWdUAkzA9BVreLIWiHFwGgUaJOyB99zjxQdMGu5qL54%3D

But when I click on it, it redirects me to this link which then displays the login page: (Notice the extra "electronics-spa/en/USD" part in the link. 
http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/login/pw/change?token=Tgv4JbOoP4Wzqd6ov%2BtIRL%2BOaTVnCh8P%2Bwi5LIWpmVBBr2ngB19WZaAh7kFtO4PQlIcSAenKpPZ9lLhuDBV%2FDKMMAtaS6us6OxrS5dN5R66YIIbTfsYj34LZfWdUAkzA9BVreLIWiHFwGgUaJOyB99zjxQdMGu5qL54%3D

**Comment by kacperknapik** [comment]
@Platonn @dunqan can u take a look? It might be connected to routing

**Comment by Xymmer** [comment]
Note that when you reset with Accelerator, the login/pw also gets pushed to the end of the URL:

https://electronics.dev-com-19.accdemo.b2c.ydev.hybris.com:9002/
yacceleratorstorefront/electronics/en/login/pw/change?token=....

Is "login/pw/change" special? maybe it needs special handling

**Comment by Xymmer** [comment]
also note i tried to trick dev19 by using local spartacus with no site context, so i got this:
http://localhost:4200/login/pw/change?token=Cb
it still went to login page

**Comment by Platonn** [comment]
The url sent in the email is wrong - `/login/pw/change`. The correct one is `/login/reset-password`
![obraz](https://user-images.githubusercontent.com/4001059/60498425-d4390b80-9cb6-11e9-8a56-30de925f09ff.png)

Note: When we visit `/login/sw/change` and there is no page with such a page label in the backend, we get back the data for the page with best-matching label (which is `/login` in the case). This feature was built in to backend to support child routes handled in Spartacus.

**Comment by KateChuen** [comment]
Tested on dev19. 
When I change the url to login/reset-password instead of login/pw/change, it works (http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/login/reset-password?token=Ct7msIqMoEEZu0bsRFsVHYQjFwHM0I0Jff%2FQJomRwkOo1pZVUOWW5lE4jvmFERMQxH28S9dETWAlkZSk9u%2F9ZKAylm2ABKLqKrDRa6HdEMTB7aqCEGpT0cMeumMR7DqU9z%2BdU5V2tOUwsOVKqkVsXK7zk0j24WaxyzM%3D)

So reset password works.
But how did we misconfigure this in the backend to start with?

**Comment by WeizhengSap** [comment]
`/login/pw/change` is hard-coded in backend. So, when email is generated, this url is written into the email content. So, we should use this "/login/pw/change" instead of "/login/reset-password" as the page label.

**Comment by Xymmer** [comment]
tested dev19 with Wei's theory that changing the label of 'resetPassword' cms page to:
/login/pw/change
fixes the problem.
works
