### ISSUE TITLE
[Pls RE-TEST] [firefox][mac] selected radio doesn't have dot inside

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3464]
![image](https://user-images.githubusercontent.com/8040837/60436056-7e5b5980-9c0b-11e9-9159-ee297b200b5c.png)

**Comment by KateChuen** [comment]
Tested on dev10, with the develop branch of spartacus. 

I still don't see the fix on firefox with and without calydon.
<img width="1023" alt="Screen Shot 2020-01-24 at 1 08 06 PM" src="https://user-images.githubusercontent.com/45409515/73092572-dfe65c80-3eaa-11ea-9a33-7726cd6869fd.png">



And now on Chrome, I see the dot is kinda weird now.
![Screen Shot 2020-01-24 at 1 08 01 PM](https://user-images.githubusercontent.com/45409515/73092586-e5dc3d80-3eaa-11ea-9bfc-7864583ed9d2.png)

**Comment by KateChuen** [comment]
Assigning it to Miguel since he told me he will check it. And moving it back to "To Do".

**Comment by developpeurweb** [comment]
I've checked this and it seems `calydon` is definitely **not** kicking-in on the deployed server, no idea why really, when i test in my local it does work by uncommenting the line in this screenshot below but not sure if there's something else you need to do when deploying as prod.

![Screen Shot 2020-01-24 at 3 57 03 PM](https://user-images.githubusercontent.com/15113219/73585654-4e11bd00-4471-11ea-8342-c18412123171.png)

This is how it looks in my local, both Chrome/FF and the overriding value that fixes the issue

![Screen Shot 2020-01-24 at 3 26 05 PM](https://user-images.githubusercontent.com/15113219/73585671-6b468b80-4471-11ea-9e5b-217c632366ea.png)

This is how it looks in the deployed server, both Chrome/FF and there's no overriding value anywhere, so it seems like calydon is not being included.

![Screen Shot 2020-01-24 at 3 26 52 PM](https://user-images.githubusercontent.com/15113219/73585680-7f8a8880-4471-11ea-8f1d-d9ef69529509.png)

**Comment by developpeurweb** [comment]
Same display issue found in GH-4324, although there: the fix is missing in the `epic/accessibility`

**Comment by developpeurweb** [comment]
This works on my local for all browsers, please re-test.

**Comment by KateChuen** [comment]
Tested on dev12, on firefox, chrome, and safari, with calydon enabled.
