### ISSUE TITLE
Clicking 'expiration year' focuses 'expiration month' select

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3467]
There is strange behavior after click year select, we can see that month is focused.
![image](https://user-images.githubusercontent.com/8040837/60437336-6933fa00-9c0e-11e9-8559-57c2e01c7211.png)
Then after press key arrow down is month is expanded:
![image](https://user-images.githubusercontent.com/8040837/60437420-9385b780-9c0e-11e9-9193-507abfd2a4c6.png)

**Comment by KateChuen** [comment]
Tested on dev2. It's fixed now.'
<img width="767" alt="Screen Shot 2019-07-09 at 10 54 22 AM" src="https://user-images.githubusercontent.com/45409515/60899300-402bee80-a238-11e9-87ea-7fb53d28a39b.png">
