### ISSUE TITLE
[safari][mac][iphone] Server did not respond, please try again errors, when adding to cart

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#3470]
A quick way to reproduce:

1. Open storefront
2. Go to PDP
3. Click add to cart
4. Increment number of items in add to cart modal
5. App freezes, we get `Gateway Timeout` in a console.

Bug occurs also in mobile safari on IOS, doesn't happen on mobile Chrome.
Version of this bug is visible during checkout, although it's not critical (you can do successful checkout despite of "Server did not responded, please try again" errors).
I also makes impossible to increment number of items on a cart page (basically disabling that operation at first attempt, until doing page reload browser).

Last note: opening that erroneous url in browser tab works, so I suspect some issue with some xhr polyfill used in safari.

<table><tr><td>
<img src=https://user-images.githubusercontent.com/5839835/60440516-49ec9b00-9c15-11e9-9bc9-888be6b884df.png width=400 border=1 color=black/> 
</td></tr><tr><td>
<img src=https://user-images.githubusercontent.com/5839835/60441609-a486f680-9c17-11e9-945b-6f29bd325f41.png width=400 /> 
</td></tr><tr><td>
<img src=https://user-images.githubusercontent.com/5839835/60441440-42c68c80-9c17-11e9-9561-f62d140519f6.png width=400 /> 
</td></tr><tr><td>
<img src=https://user-images.githubusercontent.com/5839835/60441520-71446780-9c17-11e9-9816-bac328afa0c2.png width=400 /> 
</td></tr></table>

**Comment by Xymmer** [comment]
it's a bug with installation script, not spartacus itself

**Comment by hackergil** [comment]
The problem is being caused by the following:

> [Error] Fetch API cannot load https://storefront.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/rest/v2/electronics-spa/users/anonymous/carts/bb225309-91ce-43d3-b932-814154519fdf?fields=DEFAULT,potentialProductPromotions,appliedProductPromotions,potentialOrderPromotions,appliedOrderPromotions,entries(totalPrice(formattedValue),product(images(FULL),stock(FULL)),basePrice(formattedValue)),totalPrice(formattedValue),totalItems,totalPriceWithTax(formattedValue),totalDiscounts(value,formattedValue),subTotal(formattedValue),deliveryItemsQuantity,deliveryCost(formattedValue),totalTax(formattedValue),pickupItemsQuantity,net,appliedVouchers,productDiscounts(formattedValue)&lang=en&curr=USD due to access control checks.

[Error] Failed to load resource: Request header field If-None-Match is not allowed by Access-Control-Allow-Headers. (bb225309-91ce-43d3-b932-814154519fdf, line 0)

This is a request the Service worker is doing. It is related to PWA and it seems to be happening in Safari only.

**Comment by hackergil** [comment]
Adding `if-none-match` header to the list of access control allowed headers in the backend solves this issue.
