### ISSUE TITLE
[mobile][ios][windows] Facets/Filter by dialog is not style properly

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#3471]
List is not styled properly.

![image](https://user-images.githubusercontent.com/5839835/60441542-7f928380-9c17-11e9-8739-d4985a397fc2.png)

![image](https://user-images.githubusercontent.com/5839835/60441563-89b48200-9c17-11e9-9765-ca37fcebda9f.png)

**Comment by Xymmer** [comment]
duplicate of existing known issue. styling not loaded
