### ISSUE TITLE
DUPE RE-TEST [mobile][ios][chrome][safari] Place order button cuts it's label

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#3472]
`Place Order` label is not fully visible on mobile horizontal view. 
![image](https://user-images.githubusercontent.com/5839835/60441683-cf714a80-9c17-11e9-8f55-2cabfc522491.png)

**Comment by KateChuen** [comment]
Also happens in Android, Firefox.

**Comment by developpeurweb** [comment]
This probably got fixed in GH-3049 you will have to wait for the next Model-T deployment for retesting

**Comment by KateChuen** [comment]
Tested on dev2. 
Place order button is fixed now. Tested with mobile viewport on chrome & safari. 
<img width="336" alt="Screen Shot 2019-07-15 at 1 27 25 PM" src="https://user-images.githubusercontent.com/45409515/61237211-f8113e00-a707-11e9-8966-3cb241a61a3c.png">
