### ISSUE TITLE
[ios][android][chrome][safari] You should be able to close menu by clicking outside of it

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#3473]
Currently, you can only close the hamburger menu using a close icon, which is placed at the top (and often not visible when scrolled down). You should be able to close menu also by clicking anywhere below it. 

![image](https://user-images.githubusercontent.com/5839835/60441815-165f4000-9c18-11e9-8e32-fece8f30a859.png)

**Comment by Xymmer** [comment]
also #3299

**Comment by Zeyber** [comment]
QA Steps (in mobile view):
1. Click to open menu
1a. Click links to check they work as before
2. Click anywhere outside menu, menu should close

**Comment by KateChuen** [comment]
Tested on dev2. 
- Verified on chrome, safari & firefox (mobile/tablet view) on mac, and safari on iphone8+. 
- The menu now closes when click outside.
- The links inside the menu still work. 
- One tiny issue was found with the nav arrows in mobile/tablet view when we have a banner carousel on the page. Opened ticket #3665
