### ISSUE TITLE
[windows][edge] Spinner is moving all over the screen

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#3475]
Spinner is behaving strangely, i.e. it's doing circles and flying all over when visible:

![image](https://user-images.githubusercontent.com/5839835/60442881-4a3b6500-9c1a-11e9-8cda-a1e7c1d23940.png)

**Comment by Zeyber** [comment]
I also see this behaviour:

![image](https://user-images.githubusercontent.com/11735817/60495743-b321ec00-9cb1-11e9-9307-0f459e810a22.png)

**Comment by Xymmer** [comment]
seems better now. not perfectly centered sometimes but not that you'd notice
