### ISSUE TITLE
"Out of stock" text shown before product is loaded

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3477]
When navigating to a product for the first time, I first saw the "Out of stock" text for a second before the product details were loaded. I should not see this text at all unless the product is actually out of stock.

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3529

Note: I don't believe this is a device specific bug. I've experienced it on my Mac using Chrome.

**Comment by giancorderoortiz** [comment]
I've seen it throughout. Looks a bit worse in mobile devices. Hopefully will be fixed now.

**Comment by KateChuen** [comment]
Tested on dev2. It's fixed now.
