### ISSUE TITLE
[windows][chrome][pwa] Infinite cart loading issue

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#3478]
This bug has occured when the app was tested as installed (using add to home screen PWA functionality) on windows. But it could be probably reproduced in a normal browser mode - more investigation has to be done. 

The cart should not trigger another a reload, when the previous attempt returned 400 (cart not found)., it seems it's not the case currently, so when cart id is somehow not valid anymore, this will likely to happen. 

Observed the wrong behavior: 
1. `Cart not found` error appearing and disappearing infinitely.
2. An infinite loop of networks calls for a cart returning 400 not found error code.

![image](https://user-images.githubusercontent.com/5839835/60443249-190f6480-9c1b-11e9-914b-00a71f20403c.png)

![image](https://user-images.githubusercontent.com/5839835/60443255-1dd41880-9c1b-11e9-98c1-7e59d41e6110.png)

**Comment by mrSingh007** [comment]
listening to LOAD_CART_FAIL in cart reducer solved my problem.

As cart load is failed, you can return empty content & entries (like initial state). This would update local storage as main problem comes from there. (As cart is no more valid and storage key not updated).
but listen to fail action will empty cart id from storage and new will be added as soon as you add product to cart.

**Comment by marlass** [comment]
That's a one way to fix this issue. This action will be dispatched for all kinds of errors and sometimes we would like to preserve some data (server returns 500, we are not logged in and would like to keep `guid` in local storage until API server is back online).

I think that we would stick for now with new action `CLEAR_CART` dispatched only in case of `Cart not found` error.

**Comment by KateChuen** [comment]
How can we test this? 
Is there a way to reproduce this issue consistently (before the fix)?

**Comment by Platonn** [comment]
Steps to reproduce of original issue (before fix):
1. Login and add something to cart
2. On an another device (or browser) login to the same account and complete the checkout - so cart is archived(removed) in backend
3. On the first device refresh the page - and you got 'Cart not found' error with infinite loop

**Comment by KateChuen** [comment]
Tested on dev2. 
Now the "cart not found" error disappears after a few seconds. 
Tested by logging in to the same account but on a different browser.
