### ISSUE TITLE
[Xiaomi/Chrome] - Homepage Product Images look pixelated

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3480]
Image links look pixelated on chrome on my phone for some reason. 

![image](https://user-images.githubusercontent.com/11735817/60444074-bfa83500-9c1c-11e9-91f6-ab02075f7995.png)

Also, the image links with "view" button give a somewhat dated impression with "view" being part of the image.

**Comment by Xymmer** [comment]
sample data is old and some images are low-rez
