### ISSUE TITLE
samsung s10+ firefox: slow loading gives issues

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3492]
**Environment Details**
Spartacus: Release 1.0
Browser: Firefox
Device: samsung s10+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/de/USD/

**Steps to Reproduce**
In general, it takes a long time to load. 
So trying to click on some fields generate issues.

**Clicking on Title on Checkout Out Shipping Address**
![b9f83e4e-c3f8-4b6f-82ce-5bb5e5fcee4b](https://user-images.githubusercontent.com/45409515/60473262-4f101100-9c3a-11e9-8826-2e5e06018268.JPG)

**Going to PDP Page loads without Show Reviews link**
![2bd36d79-f99f-49b6-923e-4b7b92918773](https://user-images.githubusercontent.com/45409515/60473294-6e0ea300-9c3a-11e9-9a2a-f287ab3f1d03.JPG)

**Comment by hackergil** [comment]
Unable to reproduce in Firefox on a Samsung S7
