### ISSUE TITLE
RE-TEST Samsung s10+ firefox: there's no space between the text and the dollar sign

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3494]
**Environment Details**
Spartacus: Release 1.0
Browser: Firefox
Device: samsung s10+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/de/USD/

**Steps to Reproduce**
Place an order. 

**Actual Result**
The text is too close to the $. 

![e82bee40-f983-49d0-af5d-3ad43f868656](https://user-images.githubusercontent.com/45409515/60473485-410ec000-9c3b-11e9-89b0-0261d6b0f9c1.JPG)

**Comment by developpeurweb** [comment]
This probably got fixed in GH-3049 you will have to wait for the next Model-T deployment for retesting

**Comment by KateChuen** [comment]
Tested on dev2 through #3496
