### ISSUE TITLE
RE-TEST Order summary doesn't use whole space

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3496]
Tested on Moto X Style

In checkout order summary only takes half a screen or less.
This doesn't look good. Too much word wrapping and bad usage of available space.

![storefrontapp marlas now sh_(iPhone X) (2)](https://user-images.githubusercontent.com/6259079/60489783-75b76180-9ca5-11e9-9c24-4c54ca045322.png)

**Comment by developpeurweb** [comment]
This probably got fixed in GH-3049 you will have to wait for the next Model-T deployment for retesting

**Comment by KateChuen** [comment]
Tested on dev2 on chrome (was able to reproduce it there using a narrow mobile viewport before the fix). 
Looks fixed now. 
<img width="336" alt="Screen Shot 2019-07-15 at 1 27 25 PM" src="https://user-images.githubusercontent.com/45409515/61235800-55a38b80-a704-11e9-98cb-9818ad131fe7.png">
