### ISSUE TITLE
hide pagination in use cases where we have only one page

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3497]
We should hide pagination in use cases where we have only one page.

Reproduction steps:

- create new account
- place order
- go to order history

We have 2 paginations which are useless because there is only one order in history.

Keeping pagination makes sense for catalog (to prevent flickering on filter change)

On order history page it doesn't really give any value and only takes screen space.

**Comment by RadhepS** [comment]
Before Changes:
![Screen Shot 2019-07-10 at 9 34 21 AM](https://user-images.githubusercontent.com/34665674/60973504-6ca64000-a2f6-11e9-8acd-f41ee2a489bc.png)

After changes:
![Screen Shot 2019-07-10 at 9 33 06 AM](https://user-images.githubusercontent.com/34665674/60973515-72038a80-a2f6-11e9-959f-155e2d23304b.png)

When there is only one page on the Order History page, it shows no pagination.

-----------------------------------------
Pagination is ALWAYS shown on Product List pages. This means that if this ticket is approved, we will have inconsistencies on how pagination will appear between pages.

![Screen Shot 2019-07-10 at 9 36 06 AM](https://user-images.githubusercontent.com/34665674/60973609-96f7fd80-a2f6-11e9-97ad-2eac8379774c.png)

Wireframes:
![Screen Shot 2019-07-10 at 9 37 23 AM](https://user-images.githubusercontent.com/34665674/60973629-9e1f0b80-a2f6-11e9-841c-0b4a42b7046f.png)


@developpeurweb

**Comment by RadhepS** [comment]
Mobile:

Before changes: 
![Screen Shot 2019-07-10 at 9 53 22 AM](https://user-images.githubusercontent.com/34665674/60974774-abd59080-a2f8-11e9-812d-0a51a6b467a1.png)
-------------
-------------
After changes:
![Screen Shot 2019-07-10 at 9 53 44 AM](https://user-images.githubusercontent.com/34665674/60974781-b001ae00-a2f8-11e9-8fb1-61b36754c76d.png)
-------------
-------------
Wireframes: 
![Screen Shot 2019-07-10 at 9 54 58 AM](https://user-images.githubusercontent.com/34665674/60974843-d0ca0380-a2f8-11e9-928c-5f7509418891.png)

**Comment by developpeurweb** [comment]
@vekterdude @manurod2018 can we please get your feedback on this change. Please review initial comments and those with screenshots. Thanks

**Comment by Manurod2018** [comment]
That is correct, pagination should be hidden when there is only one page, as it does not provide any functionality.

**Comment by vekterdude** [comment]
Precisely what Manurod2018 said.

We ALWAYS show pagination in wireframes and visuals so that their 'need' is understood and UI devs know where to place them. We do not do 2 separate wires (one with pagination hidden and another with pagination shown as this would ballon our wireframe set needlessly. 

Pagination only shows up (in the implementation) when there are too many records to fit on one page. In a wireframe setting (and often visuals too) we show enough records to establish all the page requirements and we include pagination, I repeat, so that their need is established for production, and the UI devs know where to place them in relation to other elements.

Many users (shoppers) will never see the pagination, but ones with a longer buying history will see it and require it. 

It is also 100% essential in B2B.

**Comment by developpeurweb** [comment]
@RadhepS Thank you for bringing this to our attention. Please proceed as per designers feedback.

**Comment by RadhepS** [comment]
Awesome, thanks for the input guys. 

Approved :)

**Comment by Zeyber** [comment]
QA Steps:
- [ ] Check Order History with only one page worth of orders has no pagination
- [ ] Check Order History with MORE than one page worth of orders has pagination (from 2+ pages)
- [ ] Check Product Catalogues always have pagination (1+ pages)

**Comment by KateChuen** [comment]
Tested on dev2. 
- when there's less than 5 orders (all fit on 1 page), there's no pagination.
<img width="1071" alt="Screen Shot 2019-07-11 at 3 19 11 PM" src="https://user-images.githubusercontent.com/45409515/61079319-93e13800-a3f0-11e9-810c-416e3e15705e.png">

- the moment we have a 6th order (now needs 2 pages), we have pagination. 
<img width="1066" alt="Screen Shot 2019-07-11 at 3 26 14 PM" src="https://user-images.githubusercontent.com/45409515/61079301-8a57d000-a3f0-11e9-9ab9-963815a70af6.png">

- PLP **always** have pagination. 
<img width="1076" alt="Screen Shot 2019-07-11 at 3 24 01 PM" src="https://user-images.githubusercontent.com/45409515/61079297-86c44900-a3f0-11e9-9e2b-f03c869e429d.png">

**Comment by Zeyber** [comment]
Need to fix breaking changes

**Comment by Zeyber** [comment]
Breaking Change Check: I would consider NOT to be a breaking change as it introduces a toggle input defaulting to as-before component functionality. The user can choose to add this feature or not.

**Comment by Zeyber** [comment]
After talking with @dunqan , we discussed this as being a breaking change because it modifies the html template

**Comment by Zeyber** [comment]
Consult #3856 for instructions on how to reimplement breaking changes

**Comment by Zeyber** [comment]
QA Steps: Pagination should now always show on order history page

**Comment by mirkosoft** [comment]
checked od dev-17: they're visible

**Comment by Pucek9** [comment]
> checked od dev-17: they're visible

confirmed
