### ISSUE TITLE
Button styling in personal details page

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3498]
No margin/space between buttons in personal details page on the mobile viewport.

Same in update password, update email page.

![storefrontapp marlas now sh_(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/6259079/60490225-671d7a00-9ca6-11e9-94ec-2cc049ffc749.png)

**Comment by Xymmer** [comment]
dupe of another ticket
