### ISSUE TITLE
[Need ccv2 deployment] Use numeric keyboard for numeric inputs

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3499]
For cart number, security code we could show numeric keyboard on mobile.

That would help with filling those fields in mobile, provide better UX for users.

Currently, in all fields, we show the default keyboard.

**Comment by marlass** [comment]
inputmode attribute could be used if we don't want to use input type="number"

**https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode**

**Comment by psmul** [comment]
After consulting with @kacperknapik, I will take this one. Assigned by comment due to lack of repository access yet.

**Comment by giancorderoortiz** [comment]
Please add detail instructions for qa.

**Comment by psmul** [comment]
To provide better user experience we should be displaying proper numeric input keyboard for certain fields.
Changes were applied for Card number and CVV inputs.

When on mobile.
Add items to cart and go to checkout. Proceed through address and delivery steps.
While on Payment step, focus Card Number and CVV Number fields. Proper numeric keyboard should appear on mobile devices for those inputs.

**Comment by giancorderoortiz** [comment]
waiting for ccv2 deployment

**Comment by Matejk00** [comment]
Not able to QA. Reverted with #3829 from develop.

**Comment by Matejk00** [comment]
New ticket: #3826
