### ISSUE TITLE
In spacceleratoraddon, add cms data for language/currency

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#350]
We'd like language/currency selectors to be cms. They're currently in the footer in electronics sample data; we want them in the header.

To do:
In spacceleratoraddon:
- Create 1 new type of component named "SiteContextSelectorComponent" (java)
purpose: to represent any kind of list/selection, not just language or currency.
- Create new language/currency slot (impex)
- Create 2 instances of component for "SiteContextSelectorComponent" type inside this slot (impex)
- Remove fake data that's in storefront now in header (sitecontext-slot.interceptor.ts) (Tobias added it temporarily to unblock himself)

Acceptance criteria:
- Can get slot/components in OCC API.
- Can see slot/components in backoffice.

Make sure to document use of this new component in our guidelines.

**Comment by WeizhengSap** [comment]
SPA PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1207

**Comment by WeizhengSap** [comment]
In get cms page response, you should be able to see "SiteContextSlot" and 2 components inside it.
![screen shot 2019-02-05 at 2 15 35 pm](https://user-images.githubusercontent.com/44440575/52298270-a55d7a00-2950-11e9-8605-75ffc07c34fd.png)

"Change Language" and "Change currency" in product search result page should not have any console error.

**Comment by plabadie** [comment]
<img width="698" alt="screen shot 2019-02-07 at 3 57 10 pm" src="https://user-images.githubusercontent.com/7065346/52442681-cf01d700-2af1-11e9-9173-4f9dea0e14ea.png">

**Comment by Pranavbhartia** [comment]
Hi @WeizhengSap, @Xymmer, Is there a reference to the documentation for this? Couldn't find an impex or anything related to this on the documents and the stash.hybris.com link doesn't work. Could you please provide a reference to the impex for this.
