### ISSUE TITLE
Order confirmation page translations

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3500]
The order confirmation page is not refreshed on site context change.

Changing currency/language doesn't reload the order confirmation page. Translations are not updated, values on currency also.

**Comment by Pucek9** [comment]
@marlass 
I don't think so we should convert currency in confirmation.
I got translated breadcrumb to Bestellbestätigung, rest is still in english because flag has been changed and now if we dont have translations, english is default
