### ISSUE TITLE
mobile clear search input icon not position well on firefox

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3501]
To reproduce:

- open firefox
- simulate mobile browser
- open search box
- type something
- clear icon is not positioned correctly

Couldn't screenshot it, because clicking outside search hid it.

**Comment by developpeurweb** [comment]
![Screen Shot 2019-10-07 at 7 50 19 PM](https://user-images.githubusercontent.com/15113219/66357151-cb9e4400-e93b-11e9-994f-a6f385b919ea.png)

**Comment by KateChuen** [comment]
Tested locally with theme calydon enabled.
It's aligned now. 
<img width="411" alt="Screen Shot 2019-10-10 at 9 53 48 AM" src="https://user-images.githubusercontent.com/45409515/66578576-5acc7700-eb49-11e9-9f32-aee36f55c09d.png">
