### ISSUE TITLE
Default Shipping Address not selected automatically

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3503]
Default Shipping Address should be autoselected when proceeding to checkout and reaching the Select Shipping Address stage. The user should not have to select it.

![image](https://user-images.githubusercontent.com/11735817/60502025-4876ad80-9cbd-11e9-920e-85fdb0ce26ac.png)

**Comment by Pucek9** [comment]
Hint for dev: Logic in initiation should set `selected = cached || default`

**Comment by Zeyber** [comment]
QA Steps: 
- [ ] Go to checkout with a default shipping address in your account. At shipping address section, check that default has been selected and you can click continue.

**Comment by KateChuen** [comment]
Tested on dev2. 
Default shipping address is selected by default (even when i have more than 1 address in my address book).
