### ISSUE TITLE
[narrow screen] Proceed to checkout button styling issue

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#3507]
In a narrow screen (320px / iphoneSE), add something to cart and go to /cart page.
Then the look of the button *Proceed to checkout* is broken:

![obraz](https://user-images.githubusercontent.com/4001059/60505059-33048200-9cc3-11e9-9cb7-9fd342427fea.png)

**Comment by KateChuen** [comment]
Tested on dev10. 
Button is ok now.
![Screen Shot 2019-11-07 at 3 03 54 PM](https://user-images.githubusercontent.com/45409515/68423602-5ad38d00-0170-11ea-8b8d-fb518c3810f8.png)
