### ISSUE TITLE
[Desktop/Edge] Stuck in checkout page with error when no products in cart

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3508]
When the user tries to go to any url with `/electronics-spa/en/JPY/checkout` and no products are in the cart, the user gets stuck on a page that keeps responding with cart not found and refreshing. Should return to homepage at this point.

![image](https://user-images.githubusercontent.com/11735817/60504900-d0ab8180-9cc2-11e9-8cb3-cbcb3fbdc09a.png)

**Comment by Zeyber** [comment]
Also found this same issue happens when going to `/electronics-spa/en/JPY/cart`

**Comment by Zeyber** [comment]
Could not reproduce on Chrome so seems to be Edge specific

**Comment by gladius-mtl** [comment]
Can it be reproduced in browsers other than Edge?

**Comment by RadhepS** [comment]
I can't seem to reproduce this using Mac/Edge.

What device did you try this on?

**Comment by Zeyber** [comment]
This was likely fixed by #3590 (same issue)

**Comment by giancorderoortiz** [comment]
Unable to reproduce in Windows 10 / Edge, or Windows 10 / Chrome.
