### ISSUE TITLE
In storefront, implement language/currency selectors as cms

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#351]
Depends on #350.

To do:
- Add new language/currency select slot to Spartacus in place of currency/language we have now.
- Remove hardcoded selectors currently there.

Acceptance criteria:
- Can see language/currency in same place in Spartacus.'
- Can change language/currency.

**Comment by tobi-or-not-tobi** [comment]
The behaviour after this change should be:
- load the language components dynamically based on the existence of the language cms component
- load the currency components dynamically based on the existence of the currency cms component
- only show the language when there is more then 1 language available
- only show the currency when there is more then 1 currency available

**Comment by tobi-or-not-tobi** [comment]
The CMS data should reflect the model as implemented in the temporary `HardcodedSiteContext` interceptor. With this ticket, the interceptor must be removed.

**Comment by Xymmer** [comment]
to be done in #350
