### ISSUE TITLE
RE-TEST [Xiaomi/Chrome] - Place order costs overlap

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3515]
Happens in Chrome on Xiaomi Redmi Note 4

![image](https://user-images.githubusercontent.com/11735817/60509535-6d731c80-9ccd-11e9-9af7-debf47c366a7.png)

**Comment by developpeurweb** [comment]
This probably got fixed in GH-3049 you will have to wait for the next Model-T deployment for retesting

**Comment by KateChuen** [comment]
It's fixed. Tested through #3496
