### ISSUE TITLE
RE-TEST [Xiaomi/Chrome] - Place order button text cut off

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3516]
Happens in Xiaomi Redmi Note 4 on Chrome

![image](https://user-images.githubusercontent.com/11735817/60509608-a612f600-9ccd-11e9-9145-ab22c82c5b45.png)

**Comment by developpeurweb** [comment]
This probably got fixed in GH-3049 you will have to wait for the next Model-T deployment for retesting

**Comment by KateChuen** [comment]
It's fixed. Tested through #3472
