### ISSUE TITLE
In spacceleratoraddon, add cms data for top-right links (sale, contact us, help)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#352]
For each of the links at top right:
![image](https://user-images.githubusercontent.com/4998145/48840757-99a0e500-ed5d-11e8-9282-a9753479a2d5.png)

Need cms data added to **spacceleratoraddon** (not regular sample data) for getting the link and for the page data itself.
- find a store (already there, already goes to the right page)
- sale (new)
- contact us (there is a link for this already, but we want it to go to a page; the same link in footer can go to same page)
- help (new)

To do:
- Create new nav component for the header
-- Check if we have these links for other sites, and copy that structure. We have contact us and help links, but not sale
-- note: help link might be specific to checking out, this new help is for general help, so if not the same, make a new one.
- Create new page data with dummy text for each of them: sale, contact us, help

Acceptance criteria:
- Can get slot/components in OCC API
- Can see slot/components in backoffice

The task to implement in Spartacus is #353.

**Comment by tobi-or-not-tobi** [comment]
The CMS data should reflect the model as implemented in the temporary Hardcoded `HardcodedSiteLinks` interceptor. With this ticket, the interceptor must be removed.
This includes the storefinder link. 
For each link, a content page should be returned as well.

**Comment by WeizhengSap** [comment]
3 Content Pages are created. Page Labels are: "sale", "help", and "contactUs"

**Comment by LTiger14** [comment]
Passed QA
