### ISSUE TITLE
RE-TEST [Xiaomi/Firefox] - Overflowing whitespace on order confirmation

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3520]
Xiaomi Redmi Note 4 Firefox - On the order confirmation page, the user is able to scroll horizontally past the content to see white space. They should not be able to scroll at all.

![image](https://user-images.githubusercontent.com/11735817/60511120-7fef5500-9cd1-11e9-9271-babae0e9ccd9.png)

**Comment by developpeurweb** [comment]
This probably got fixed in GH-3049 you will have to wait for the next Model-T deployment for retesting
