### ISSUE TITLE
Change cms label from reset-password to the pw/change

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3526]
**Environment Details**
Spartacus: Release 1.0
Browser: Safari
Device: mac
Happens on: https://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Click on Forgot password
Enter your email add and click 'Send'
Go to the email and click on the link to reset password

**Actual Result**
The link brings you to the Login Page instead of the Reset password page. 
However the link in the email is ok, it's
http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/login/pw/change?token=Tgv4JbOoP4Wzqd6ov%2BtIRL%2BOaTVnCh8P%2Bwi5LIWpmVBBr2ngB19WZaAh7kFtO4PQlIcSAenKpPZ9lLhuDBV%2FDKMMAtaS6us6OxrS5dN5R66YIIbTfsYj34LZfWdUAkzA9BVreLIWiHFwGgUaJOyB99zjxQdMGu5qL54%3D

But when I click on it, it redirects me to this link which then displays the login page: (Notice the extra "electronics-spa/en/USD" part in the link. 
http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/login/pw/change?token=Tgv4JbOoP4Wzqd6ov%2BtIRL%2BOaTVnCh8P%2Bwi5LIWpmVBBr2ngB19WZaAh7kFtO4PQlIcSAenKpPZ9lLhuDBV%2FDKMMAtaS6us6OxrS5dN5R66YIIbTfsYj34LZfWdUAkzA9BVreLIWiHFwGgUaJOyB99zjxQdMGu5qL54%3D

**Note**
The reason this happens is because the url is misconfigured in the backend. Kris says: "The url sent in the email is wrong - /login/pw/change. The correct one is /login/reset-password." 
More info in ticket #3459 

So we will need to update this to make sure we have the right configuration going forward. 
But Wei says there is no way to configure what the url pattern is for reset password, her solution is to change the cms label from reset-password to the pw/change. 

So this ticket is to do just that.

**Comment by Xymmer** [comment]
I tested this theory on dev19, wei is correct
she said she'd update the sample data

**Comment by WeizhengSap** [comment]
PR is here:
https://github.tools.sap/cx-commerce/c3po-legacy-spartacussampledataaddon/pull/5

**Comment by KateChuen** [comment]
Can you also update the reset-password.e2e-spec.ts test to reflect the new label please?
Line 5: cy.visit('/login/pw/change');
Line 15: cy.url().should('match', /\/login\/pw\/change$/);
Line 27: cy.url().should('match', /\/login\/pw\/change$/);

**Comment by KateChuen** [comment]
Tested on my local by running the e2e tests.
