### ISSUE TITLE
Unable to debug code with 'chrome debugger'

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#3539]
Hi, 
I am using your master branch and want to debug code with a 'Visual studio code' extension, which is known to all und thats 'chrome debugger'. 
On master branch there is already a folder for its configurations, which is '.vscode'. The 'launch.json' file is also correct but when starting debugger all the breakpoints get disabled and showing 'unverified breakpoint', cause of that debugger never stops on breakpoint.

## Environment Details

- Spartacus:  master branch (1.0.0-RC.0)
- Browser: chrome debugger

## Steps to Reproduce
Checkout master branch
yarn install
npm run build:core:lib
npm run start:qa

now start chrome debugger after storefront is there

**Comment by Xymmer** [comment]
not sure this is something we can fix, but investigate if there is a workaround. if there is one, add to existing developer setup documentation. if not, add a note to same doc stating so.

**Comment by mrSingh007** [comment]
if it can not be fixed, please provide another way to debug code? 
 -> Note: I am not using library, I want to debug your source code from Repo

**Comment by hackergil** [comment]
@mrSingh007 This is related to visual studio code and not Spartacus.

As a workaround, you can build Spartacus in dev mode using sourcemaps and debug directly in chrome dev tools
