### ISSUE TITLE
PLP breaks in SSR

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#3541]
0. disable JavaScript in your browser
1. set baseUrl to modelt
2. run ssr
```
yarn build:core:lib
yarn build
yarn build:ssr
yarn start:ssr
```
3. Go to http://localhost:4200/electronics-spa/en/USD/Open-Catalogue/Cameras/Digital-Cameras/c/575

Then the rendered page is broken. When you refresh the page, you may get differently broken page. It looks like it breaks asynchronously in some moment and nothing is rendered later. A few examples here:
![obraz](https://user-images.githubusercontent.com/4001059/60579436-60b10000-9d83-11e9-99ce-69fc115bdfde.png)
![obraz](https://user-images.githubusercontent.com/4001059/60579452-6870a480-9d83-11e9-9fcf-4293fd633d30.png)
![obraz](https://user-images.githubusercontent.com/4001059/60579457-6c9cc200-9d83-11e9-86b7-f321b8ad7afd.png)

---
the last example looks as not broken:
![obraz](https://user-images.githubusercontent.com/4001059/60579490-7de5ce80-9d83-11e9-8f2a-ac7ec7fbc6fd.png)

---

### Note: the header looks ok, becasue SSR renders the mobile version of page

**Comment by Zeyber** [comment]
Likely has something to do with this error when loading `http://localhost:4200/electronics-spa/en/USD/Open-Catalogue/Cameras/Digital-Cameras/c/575`

![image](https://user-images.githubusercontent.com/11735817/61633543-9b75cc00-ac8f-11e9-8229-3449efd82794.png)

**Comment by Zeyber** [comment]
Issue also occurs on Product Page. Load with JS disabled only reaches this point in rendering:

![image](https://user-images.githubusercontent.com/11735817/61692913-dda21a80-ad2e-11e9-8893-1135cbf09107.png)

**Comment by Zeyber** [comment]
It looks like there is a problem with the reviews stars. They are commonly never loaded on product and plp pages no matter after how many attempts.

**Comment by giancorderoortiz** [comment]
excludes checkout flow pages?

**Comment by Zeyber** [comment]
> excludes checkout flow pages?

Yes, checkout flow pages are beyond the scope of this ticket and should be resolved in a new one.

**Comment by mirkosoft** [comment]
checked: still fails for me with the same errors.
