### ISSUE TITLE
Add type safety to cms module

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#355]
Typesafety should be added wherever possible. A few suggestions where type safety should be added:

* method parameters
* method return values
* if there's no return value for method (it's void), add `void` as the return to make it more specific
* test files
* object literals
* if you need OCC types, take a look at #301's PR
* if working with CMS components, as a generic type use `<T extends Component>`, where `Component` is an interface from `projects/core/src/occ-models/occ.models.ts`

The goal is to have a completely type safety code.

**Comment by plabadie** [comment]
Please do these 2 things to get the ticket in a reviewable state:
- Create a PR and link it in this ticket.
- Get a green pipeline build on the PR.

**Comment by plabadie** [comment]
We agreed to do another pass since there are still many occurrences of the any keyword
Also, we want to add return types to functions that don't have one.

**Comment by MitchellScottSandre** [comment]
PR: GH-355
