### ISSUE TITLE
PDP: Thumbnail carousel pagination is not reloaded when navigating from one product to another

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3553]
**Environment Details**
Spartacus: Release 1.0
Browser: Chrome
Device: mac
Happens on: http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
Go to pdp of product 1934793
Click on the upselling product 1934796 (3rd on the carousel with price $110.88)
Click on the right arrow on the thumbnail carousel
Click back on the browser 
Click on the arrow on the upselling carousel, and click on the last upselling product (product 1934795)

**Actual Result**
The thumbnail carousel is displaying the 2nd page

**Note**
Also happens when we navigate from one product to another when we select the product from the search autocomplete.

**Comment by giancorderoortiz** [comment]
I see a fix. Tested on dev-com6. 
Using Camera 1: 2934302 & Camera 2: 1934796.
First page of thumbnails seen when switching between products.
