### ISSUE TITLE
cors config for consent management is missing when install from spartacus gradle recipe (decision?)

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3556]
**Environment Details**
Spartacus: Release 1.0 + hotfix
Browser: Chrome
Device: mac
Happens on: http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
Login.
Go to MyAccount -> Consent Management

**Actual Result**
It's empty because it doesn't have the config. 
Go to HAC, look for "corsfilter.ycommercewebservices.allowedHeaders"
It should have "cache-control" added to it.

**Expected Result**
It should be configured automatically when we install with the recipe of a commerce suite.

**Comment by znikola** [comment]
It's specified here: https://github.tools.sap/cx-commerce/c3po-legacy-devconfigs/blob/master/spartacus/build.gradle#L35

**Comment by Xymmer** [comment]
Gil says: properties are there, but they are not propogated when install is run
need someone to investigate what's going on

**Comment by plabadie** [comment]
The spartacus recipe has the config: https://github.tools.sap/cx-commerce/c3po-legacy-devconfigs/blob/master/spartacus/build.gradle#L35

Tested it locally and it works as intended.

**Comment by plabadie** [comment]
The changes do not propagate automatically, the recipe update will make it so new environments created with the recipe will have the right config.

For existing environments dev17 and dev22 are already ok.  Dev19 did not have the proper config.  I added it both in HAC and local.properties.
