### ISSUE TITLE
fix reset-password e2e test after cms label change

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3559]
Ticket #3526 is changing the cms label for reset-password.
So we need to fix the e2e test, otherwise it will fail. 

So to be merged AFTER ticket #3526

**Comment by KateChuen** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3561

**Comment by gladius-mtl** [comment]
Already done, already merged.
