### ISSUE TITLE
Date format doesn't change when we change language

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3563]
**Environment Details**
Spartacus: Release 1.0 + hotfix
Browser: Safari
Device: mac
Happens on: https://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login
Place an order
Go to MyAccount -> Order History
Change the language to DE

**Actual Result**
The date format doesn't change.
It's still July 3, 2019.
It should be something like 3 Juli 2019 (used to be like that before)

**Comment by KateChuen** [comment]
Still reproducible on dev2, dev17 & dev19.

**Comment by LTiger14** [comment]
Was able to reproduce the bug on 17 & 19 but this was working on my local. Maybe someone can test again on 17 & 19 once it gets updated.

**Comment by WeizhengSap** [comment]
It works on my local as well.

**Comment by giancorderoortiz** [comment]
I don't see a fix yet. 
Switching language from English to German still leaves date in the same format. 
Frontend dev-com6. Backend: dev-com19. 

![Screen Shot 2019-07-16 at 7 44 41 PM](https://user-images.githubusercontent.com/46171897/61337210-663a2b80-a802-11e9-9d21-e2fcada4c20f.png)
![Screen Shot 2019-07-16 at 7 45 00 PM](https://user-images.githubusercontent.com/46171897/61337211-66d2c200-a802-11e9-868f-1d8a0470ca00.png)

**Comment by KateChuen** [comment]
I know it works locally. But can we please investigate why it doesn't work on the server?
Maybe it's a config issue? 
But we need to solve this, because otherwise, the e2e test checking the date format when we change the language will fail.

**Comment by LTiger14** [comment]
I was able to repro!

**Comment by LTiger14** [comment]
Basically this is cause by the fact that we only provide one local in the Spartacus install script. If this is required to be fixed on our servers I can add the german local.

**Comment by LTiger14** [comment]
PR is 3 in the Spartacus-installation repo.

**Comment by plabadie** [comment]
Approved.  Works locally.  We just need to redeploy on the dev servers for the fix to be applied.

**Comment by LTiger14** [comment]
QA Steps:

**Comment by KateChuen** [comment]
Tested on dev2. Works now! 
<img width="1126" alt="Screen Shot 2019-07-23 at 10 40 58 AM" src="https://user-images.githubusercontent.com/45409515/61721397-653f5780-ad36-11e9-991f-75f8dc84abcb.png">
