### ISSUE TITLE
Global messages disappear in the wrong order

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3570]
Scenario:
1 go to Consent Management,
2 check the option (appear "Consent successfully given.")
3 uncheck the option (appear "Consent successfully withdrawn.")
4 disappear "Consent successfully withdrawn."
5 disappear "Consent successfully given."

It can be easily fixed by
![image](https://user-images.githubusercontent.com/8040837/60661328-ff0f9500-9e59-11e9-9b44-aedc9a900f31.png)
**But it is not enough**, it provides a new problem:
1 check the option (appear "Consent successfully given.")
2 uncheck the option (appear "Consent successfully withdrawn.")
3 check the option
4 disappear "Consent successfully given."
5 disappear "Consent successfully withdrawn."

---------------------------------------------------------------------

Additional found problem:
1 check the option 1 (appear "Consent successfully given.")
2 after e.g 2.8s check the option 2
3 after 0.2s "Consent successfully given." disappear

Probably to solve both issues we should create an effect for add new message, and it should remove duplicate from the existing state. Now the responsibility is in reducer, which just ignores the duplicate.

~I'm not sure, but then probably we should use an index of the newly added message (last one) like now.~

**Comment by kacperknapik** [comment]
please take a look at this comment: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3583#discussion_r304946078
