### ISSUE TITLE
Empty search page contains incorrect elements

### ISSUE THREAD

**Issue by alex-dobre** [SAP/cloud-commerce-spartacus-storefront#3572]
## Environment Details 

- Spartacus:  1.0.0-RC.1
- Browser: Chrome Version 75.0.3770.100, Mozilla Firefox 67.0
- OS: Windows 10 Pro
- Device: Dell notebook

## Steps to Reproduce
Go to any page other than Home, for example PDP, cart etc
Click and the search field, make sure it is empty and hit Enter

## Observed Results
It can be noticed that the empty results page contains also the header of the previously visited component.

## Expected Results
Header of the previously visited component is not visible

![image](https://user-images.githubusercontent.com/52537066/60669855-03e34180-9e78-11e9-9d6b-b2af3f8a88cd.png)

## Offer to Fix
No

**Comment by qjimmy** [comment]
**Muhammad:** Fix ready. Waiting for access to generate PR.

**Comment by mazamcodes** [comment]
PR https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4752

**Comment by mazamcodes** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4752
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4804

**Comment by mazamcodes** [comment]
Spoke with @KateChuen and @WeizhengSap about merging this but then creating another improvement ticket and getting UX feedback regerading the behavior. It doesn't make sense to allow blank search if we cannot click on the Search icon and execute a blank search. Perhaps, this functionality shouldl be removed.

**Comment by KateChuen** [comment]
User should not be able to perform an empty search. on the old accelerator, we cannot perform an empty search either. so it will be consistent with that behavior.
