### ISSUE TITLE
In SmartEdit: should get baseSite data before go to preview page

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#3576]
When open product/category pages in SmartEdit, sometimes, the default preview product/category is not loaded. The reason for this issue is, baseSite data is not received when `goToPreviewPage` function is called.

**Comment by KateChuen** [comment]
Tested on dev2. siteID is now returned in the preview call. 
Both pdp and plp are displayed properly.

<img width="1439" alt="Screen Shot 2019-07-11 at 2 34 41 PM" src="https://user-images.githubusercontent.com/45409515/61076055-5b8a2b80-a3e9-11e9-810d-69d10614c019.png">
<img width="1440" alt="Screen Shot 2019-07-11 at 2 36 04 PM" src="https://user-images.githubusercontent.com/45409515/61076057-5c22c200-a3e9-11e9-8786-1642fe1a02e4.png">
