### ISSUE TITLE
Product List/Grid: Only the top portion of product titles are clickable

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3577]
##Environment Details

- Browser: Chrome
- Device: Mac

## Steps to Reproduce

1. Navigate to product list or grid view.
2. Hover your mouse on the bottom of a product title and then slowly bring it up. 

## Observed Results

The text is only clickable when it's slightly higher than half way up the text.

## Offer to Fix
Yes, all it requires is removing the line `padding: 15px 0` from "_star-rating.scss"

![IMG_20190704_144324119](https://user-images.githubusercontent.com/34665674/60684579-8534d700-9e6c-11e9-91ab-f977ca520ede.jpg) (Had to use my phone camera because screenshots removed the cursor)

**Comment by KateChuen** [comment]
Tested on dev10, with calydon enabled. Verified on all 3 browsers (chrome, safari, firefox) on both the product list and grid. 
it's fixed now.
![Screen Shot 2019-11-13 at 2 08 20 PM](https://user-images.githubusercontent.com/45409515/68795513-21db6280-061f-11ea-8b50-c81c15aa3300.png)
