### ISSUE TITLE
Load current cart after "Cart not found" for logged user

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3592]
In #3478 we fixed the issue with an infinite loop.
However, we can improve the UX, by loading the current cart after catching "Cart not found" error.
This will help in some cases with cart synchronization, but it will be still possible to have multiple carts on one user account when using multiple devices/browsers.

**Comment by Platonn** [comment]
According to https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/issues/203#issuecomment-510088647, i think we should avoid multiple carts for signed-in user. So for logged user we should always try to load exising cart (in case that on other device it has already been created). And we should also load it from backend before trying to create a new cart.

**Comment by KateChuen** [comment]
Tested it on dev17.

- On device/browser 1, logged in, and added an item to cart (a new cart with id 00010269 is created). 
- On device/browser 2, logged in with same user, and gets the same cart id 00010269). Placed order with that cart. After the order is placed, it sends a call to get cart but no cart is returned. 
![Screen Shot 2019-08-13 at 3 31 06 PM](https://user-images.githubusercontent.com/45409515/62971353-96fc8900-bddf-11e9-8739-8a6661146572.png)
![Screen Shot 2019-08-13 at 3 24 21 PM](https://user-images.githubusercontent.com/45409515/62971363-9c59d380-bddf-11e9-8743-30066e669189.png)
- On device/browser 
<img width="206" alt="Screen Shot 2019-08-13 at 3 35 41 PM" src="https://user-images.githubusercontent.com/45409515/62971509-07a3a580-bde0-11e9-8352-a62a6dd58dd1.png">
1, refresh the page. A get call for the previous cart 00010269 is sent, but 400 returned (Cart not found error displayed). - as expected.
<img width="793" alt="Screen Shot 2019-08-13 at 3 31 25 PM" src="https://user-images.githubusercontent.com/45409515/62971429-dc20bb00-bddf-11e9-8654-40f5707161e2.png">

Then another get call for the cart is sent, and a successful response returned with no cart. 
<img width="796" alt="Screen Shot 2019-08-13 at 3 31 36 PM" src="https://user-images.githubusercontent.com/45409515/62971433-df1bab80-bddf-11e9-99d5-e750591a2a01.png">
