### ISSUE TITLE
Native title dropdown instead of customized one

### ISSUE THREAD

**Issue by Matejk00** [SAP/cloud-commerce-spartacus-storefront#3595]
For every select in our store we are using customized dropdown f.e.:
<img width="631" alt="Screen Shot 2019-07-08 at 14 36 36" src="https://user-images.githubusercontent.com/6958810/60811188-094dce00-a18f-11e9-8a4c-dc72f895e158.png">

But, currently we have one exception on registration page (example in safari):
<img width="681" alt="Screen Shot 2019-07-08 at 14 37 01" src="https://user-images.githubusercontent.com/6958810/60811246-22ef1580-a18f-11e9-9470-2e800f276b1d.png">
<img width="843" alt="Screen Shot 2019-07-08 at 14 37 07" src="https://user-images.githubusercontent.com/6958810/60811247-2387ac00-a18f-11e9-9cf1-c8b2c5489653.png">

Shouldn't we adapt here customized dropdown as well?

**Comment by psmul** [comment]
After consulting with @kacperknapik, I will take this one. Assigned by comment due to lack of repository access yet.

**Comment by psmul** [comment]
Also I've noticed that this change is required in another place, Update Personal Details view. Will be fixed as extension for scope of this task.

(example from Chrome)
![image](https://user-images.githubusercontent.com/10993491/60888996-4d58d580-a258-11e9-8c34-fadd814c2218.png)

**Comment by giancorderoortiz** [comment]
This successful. 
Tested in Mac Chrome & FF. 
Also tested on Windows 10 Chrome and Edge.
