### ISSUE TITLE
New theme to avoid breaking changes

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#3598]
As per Tobias request, I'm creating this ticket to add a new theme to start testing de inclusion of CSS breaking changes.

**Comment by developpeurweb** [comment]
@tobi-or-not-tobi 
 For the purpose of this example I followed along with ancient greek city names since it's a very long list that may come handy... so, my blind finger chose "**calydon**" for this example theme.
https://en.wikipedia.org/wiki/List_of_ancient_Greek_cities
 
I've setup the new theme, but not sure if this is the intended way, probably not. Please feel free to pull this branch and make updates.

I have some questions based on different scenarios:

1. **Forgotten components:** The issue presented in GH-3521 ticket and that I'm trying to fix in this other ticket is a simple one; we missed to style an existing component, not a new one, so the selector `cx-update-password` is not part of the Sparta theme `$selectors`. So I've included it in the new theme… but also added a file to `storefonrtstyles` folder… but maybe this is not where it needs to be added, but instead in the actual `_calydon-theme.scss` file as a placeholder `%cx-update-password-calydon` … I tried both ways, so please review both alternatives reflected in the first and third commit. Either way the bug does get fixed in this page `http://localhost:4200/electronics-spa/en/USD/my-account/update-password` (mobile bug).

2. **Existing components:** How do we bugfix existing components using the new theme? for example GH-3052 where selectors are not set as placeholders in `_order-detail-page.scss` or in files like `_order-confirmation-totals.scss` where I'm realizing we still have non-global css variables we missed to refactor, which will be a common case where we need to change values in an existing component.

3. **New components:** What happens when we create a brand new component? do we have to align with devs so new components will have html tags like `<cx-new-component-calydon>` or will this only be reflected in the placeholder name and/or css class `<cx-new-component class"this-component-calydon">`

**Observation:** If all fixes will happen in the same theme file, we might end up having very long theme files.

**Comment by developpeurweb** [comment]
@mikelMHybris @LTiger14 you may want to be in the loop for this one

**Comment by tobi-or-not-tobi** [comment]
love the greek cities!

@developpeurweb I put a quick example together at https://github.com/SAP/cloud-commerce-spartacus-storefront/tree/feature/GH-3598-example

Please be aware of:
- all theme placeholder selectors are imported (currently only calydon)
- only if the theme is set, it will be used. The new theme is set in `styles.scss`

The result is a border below banner comp, only if you opt-in to calydon.

**Comment by developpeurweb** [comment]
@tobi-or-not-tobi @LTiger14 
Adding up to the previous questions, let's consider the following too:

4. **Versioned components aftermath:** Let's pretend we need to adjust or restyle a component created during the "calydon" theme version, if we have added the calydon suffix to the html, as it evolves and later we're using theme "andros", how will we manage current and all following theme suffixes.

5. **Original components changing throughout theme versions:** Aligned with the previous one, if we need to adjust or restyle a component created during the first theme version "sparta" and as it evolves, now we are 2 themes away from "sparta" using by then theme "andros", and we have changes to that styles of that component during "calydon" too... how will all these 3 version add up, and how do we manage the suffixes.
In the screenshot below I can see "calydon" overriding "sparta", based on this premise, if we have 11 themes after "sparta" updating a specific area everytime, we will have 11 overrides, is this what's expected?

![Screen Shot 2019-08-14 at 3 11 55 PM](https://user-images.githubusercontent.com/15113219/63355410-13d5b880-c334-11e9-92d3-fc13a7e7b7c5.png)

**Comment by developpeurweb** [comment]
To QA:
In this file: `projects/storefrontapp/src/styles.scss`

Uncomment line 4:

![Screen Shot 2019-09-05 at 9 49 21 AM](https://user-images.githubusercontent.com/15113219/64348111-9d3aeb00-cfc2-11e9-8ed2-42a72949c924.png)

**From this point forward most of the visual bug fixes should have the calydon theme enabled in order to be validated.**

New theme structure to be found here:
`projects/storefrontstyles/scss/themes/calydon`
and the following strucutre should be in place:

![Screen Shot 2019-09-05 at 9 56 19 AM](https://user-images.githubusercontent.com/15113219/64348594-73ce8f00-cfc3-11e9-97f2-b0489852c285.png)

**Comment by KateChuen** [comment]
Tested on dev10. 
For the purpose of this ticket, i'm only checking that the theme structure is there. The rest will be verified in #3455 & #3521. 

This is what I see. And confirmed with Miguel. The fact that "cxbase" and "layout" are not displayed on mine is probably because those folders are currently empty. 

<img width="756" alt="Screen Shot 2019-09-05 at 11 17 36 AM" src="https://user-images.githubusercontent.com/45409515/64355333-0a547d80-cfcf-11e9-8b10-f79e6eb21fac.png">


![Screen Shot 2019-09-05 at 11 21 24 AM](https://user-images.githubusercontent.com/45409515/64355492-51db0980-cfcf-11e9-82a7-b46dfe7ea144.png)
