### ISSUE TITLE
TM - Authentication (tokens)

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3610]
**Spartacus Threat Modelling Workshop.**
Date: June 14, 2019.
Participants: Bill, Gil, Tobias, Stan, Hernando, Felix, GC

_SAP Product Standard Required Compliance:_
https://wiki.wdf.sap.corp/wiki/display/PSSEC/SEC-276

_Threat Pattern:_
Threat: In case of no authentication in place, confidential data / resources could be accessed by illegimitate requesters. That would allow illegitimate requesters to steal, change or delete these resources or confidential data.

(As informed/discussed/reported by security team during workshop)

**TM Comments:**

Frontend client accesses Oauth Server of Commerce cloud, gets token, and stores it (access_token, refresh_token, expriy, scope,uderID) in the Local Storage.
The refresh token is currently stored within the same JSON, but this is meant to be removed (tiken open).
These tokens are then used to authN/authZ requests to OCC (Commerce RestApi)
Login to protected resources is enforced by OCC due to auth tokens being necessary.

**Identified Threats:**

Token is not protected in any way in the local storage, so remove refresh token.
Localstorage is locked down to same origin and protocol by default, but browser bypasses are possible

**TM Required Actions:**

1. Remove refresh token.

**Comment by giancorderoortiz** [comment]
See this ticket for implementation of abovementioned change request: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3187

**Comment by hackergil** [comment]
This was done in #3187
