### ISSUE TITLE
TM - Authentication - HTTPS

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3611]
Reference: https://github.tools.sap/cx-commerce/spasec/issues/4

**Comment by giancorderoortiz** [comment]
Shouldn't https be enabled by default?

**Comment by hackergil** [comment]
Spartacus is distributes as an npm library. Customers create their own application and import the libraries as dependencies. We need to strongly recommend to enable HTTPS on their end.

**Comment by gladius-mtl** [comment]
Should be documented in security guideline.

See https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/issues/217
