### ISSUE TITLE
TM - Authentication - Password Handling

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3612]
**Spartacus Threat Modelling Workshop.**
Date: June 14, 2019.
Participants: Bill, Gil, Tobias, Stan, Hernando, Felix, GC

_SAP Product Standards / Guides Required Compliance:_
https://wiki.wdf.sap.corp/wiki/display/itsecurity/SOAR+Category+Operations#SOARCategoryOperations-AdminUserManagement

SecOPs-074, SecOps-075, SecOps-076, SecOps-077, SecOps-078, SecOps-079, SecOps-080
SecOps-081, SecOps-082, SecOps-083, SecOps-084, SecOps-085

_Threat Pattern:_
Threat - Spoofing the identity of an administrator or highly privileged people.

(As informed/discussed/reported by security team during workshop)

**TM Comments:**

**TM Required Actions:**

1. TODO: Document necessity for Encryption, password policies / rotation, etc. Other aspects are operational however.

**Comment by gladius-mtl** [comment]
All of this is handled by the back end. We do not store any user data in Spartacus. Should not be documented in Spartacus.
