### ISSUE TITLE
TM - Code (URL) Generation

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3617]
Reference: https://github.tools.sap/cx-commerce/spasec/issues/1

**Comment by gladius-mtl** [comment]
GC to create end-to-end test ticket.

**Comment by giancorderoortiz** [comment]
Need a doc ticket for Spartacus security management and concerns.

See SAP/cloud-commerce-spartacus-storefront-docs#217
