### ISSUE TITLE
TM - Exposing Systems Internal Data

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3618]
**Spartacus Threat Modelling Workshop.**
Date: June 14, 2019.
Participants: Bill, Gil, Tobias, Stan, Hernando, Felix, GC

_SAP Product Standard Required Compliance:_
https://wiki.wdf.sap.corp/wiki/display/PSSEC/SEC-236

_Threat Pattern:_
Threat: If system internal information is provided to illegitimate users/attackers, then that information can be misused to get unauthorized access to your application and even use your product as basis to launch future attacks against other product installations.

(As informed/discussed/reported by security team during workshop)
**TM Comments:**

1.No sensitive data logged

**TM Required Actions:**

1. TODO: Validate (potentially automatically in Checkmarx)
2. TODO: Enable Checkmarx scans

**Comment by gladius-mtl** [comment]
Checkmarx scans have been enabled.
