### ISSUE TITLE
[DUPE] Pagination colour not using the variable

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#3627]
As seen on the screenshot the colour on the number in the pagination isn't using the css variables.

![Screen Shot 2019-07-10 at 11 26 44 AM](https://user-images.githubusercontent.com/10605724/60982259-c6623680-a305-11e9-85c2-8bd7fcd701b1.png)

This is because the code is as follows:
```css
    background-color: #fe5757;
    border-color: #fe5757;
```

it should be:

```css
    background-color: var(--cx-color-primary);
    border-color: var(--cx-color-primary);
```

I don't think this is a breaking change.

**Comment by developpeurweb** [comment]
@mikelMHybris you might want to take this one, I think it's related to GH-3236

**Comment by mikelMHybris** [comment]
It looks like the old scss are coming in from somewhere. 
![Screen Shot 2019-07-11 at 1 48 56 PM](https://user-images.githubusercontent.com/30266610/61073133-b2d8cd80-a3e2-11e9-8a84-1c55d8a3fe6f.png)

**Comment by developpeurweb** [comment]
@mikelMHybris Breaking changes were detected, let's park this one here for a little while until we decide how to include `cx-base` changes in new themes.

**Comment by developpeurweb** [comment]
Moving back to **To Do**, we now have access to `components` and `layout` in Calydon for this kind of fixes.

**Comment by developpeurweb** [comment]
I just realized this issue is actually in the `cxbase`, i already fixed some issues there so i'll take this one

**Comment by KateChuen** [comment]
Tested on dev10, with theme calydon enabled. 
It's now fixed. 
![Screen Shot 2019-11-13 at 3 15 54 PM](https://user-images.githubusercontent.com/45409515/68801009-2ad13180-0629-11ea-8d38-9e8008e6b294.png)
