### ISSUE TITLE
ProductReferencesComponent not filled properly

### ISSUE THREAD

**Issue by J0hnsn** [SAP/cloud-commerce-spartacus-storefront#3628]
## Environment Details

- Spartacus:  1.0.0
- Browser: Chrome
- OS: macOS Mojave 10.14.5
- Device: Macbook Pro

## Steps to Reproduce

I have multiple product references components with different product Reference types (CONSISTS_OF, ACCESSORIES, SPAREPART, and BASE_PRODUCT) on my PDP.

As soon as there is just one reference of any type, all components are filled with the same products. This means:
For a product, having one related product of type ACCESSORIES, all referenceComponents are shown with this product. For a product having multiple referenced products of different types, all referenceComponents, show the same related products, but just of one type.

## Observed Results

When checking the network tab on my browser, i can see that the related products are retrieved correctly. This means that after every successful request for references, all of the referenceComponents are filled/overwritten with the products of the response.

## Expected Results

Each ProductReferencesComponent should only display the referenced products of its type.

**Comment by bgambocjaviniar** [comment]
Duplicate to a ticket in JIRA
