### ISSUE TITLE
Checkmarx - Jquery Outdated Version chai-jquery-1.1.35

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3631]
**Scan Date:**
June 18, 2019.

**Report**
https://cx.wdf.sap.corp/CxWebClient/ViewerMain.aspx?scanId=4547096&ProjectID=63198

**File:**
\cloud-commerce-spartacus-storefront-develop\projects\storefrontapp-e2e-cypress\yarn.lock

**Line:**
650

**Checkmarx Severity**
Medium

**Violations:**
1

Issue:
Flagged use of chai-jquery-1.1.35.

**Comment:**
Method "https://registry.yarnpkg.com/@types/chai-jquery/-/chai-jquery-1.1.35.tgz#9a8f0a39ec0851b2768a8f8c764158c2a2568d04" in cloud-commerce-spartacus-storefront-develop\projects\storefrontapp-e2e-cypress\yarn.lock, at line 650, calls an obsolete API, 35. This has been deprecated, and should not be used in a modern codebase.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-07-10 at 5 29 19 PM](https://user-images.githubusercontent.com/46171897/61006413-473a2600-a338-11e9-85ca-c42c74faf263.png)

**Comment by tobi-or-not-tobi** [comment]
Non issue when it comes to our production builds and library distribution. We do not distribute our e2e tests (and obviously we do not use jquery in our libs).
