### ISSUE TITLE
[reenable tests] Shipping Address component clean up

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3641]
The shipping address component has functions with confusing names and multiple subscriptions that may not be necessary. To look into and clean up this component where possible.

**Comment by Zeyber** [comment]
Should merge with #3656 to avoid double-doing work.

**Comment by Zeyber** [comment]
Carries many breaking changes. Need to think about how to handle this before merging.

**Comment by Zeyber** [comment]
Please check #3921 for breaking changes code when performing review

**Comment by Zeyber** [comment]
QA: Check that shipping address features work as they did before merging this

**Comment by giancorderoortiz** [comment]
checkout cypress tests for registered user, express checkout successful on dev-com17.

**Comment by giancorderoortiz** [comment]
manual test successful
