### ISSUE TITLE
Set up an internal dev server that has SmartEdit pointing to Spartacus [depends on 317]

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#365]
After #317

This server will be internal to SAP.

GC will provide a server for us.

**Comment by hackergil** [comment]
Dev2 has been setup for this. Sprint demo was done on it.

http://dev-com-2.accdemo.b2c.ydev.hybris.com:9002/smartedit
http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200
