### ISSUE TITLE
Default shipping address is always selected automatically

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3656]
1. Start order process and go to the shipping address step
2. Make sure you have atleast 2 shipping addresses (one of them should beloca default)
3. Select the shipping address that is NOT the default
4. Press continue
5. Now go back to the shipping address page (back button on browser or by clicking the "1. Shipping Address" banner.

Result:
The default payment is selected

Expected result:
The payment that we originally selected should be selected.

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3664

**Comment by RadhepS** [comment]
QA Steps:
Have atleast 1 shipping address

1. Start order process
2. Create new shipping address, after creation it should be selected
3. Restart order process
4. The default address should be selected
5. Manually select the other shipping address
6. Press continue
7. Press the browser's back button, the second address should still be selected

**Comment by KateChuen** [comment]
Tested on dev2. 
Verified that after selecting a non-default shipping add, the selection is saved
 - when clicking on the shipping address tab again
 - clicking on the browser's back button
 - clicking on the cart page and proceeding to checkout
 - logging out and logging back in, clicking on the cart and proceeding to checkout
  - logging out and logging back in on another browser, clicking on cart and proceeding to checkout

Verified that after placing the order with the non-default shipping add, the next checkout is back to the default one being selected.
