### ISSUE TITLE
[need release of backend fix] Revoke access token when user logs out

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#3663]
endpoint is /oauth/revoke.
Expected Param name is "token"

**Comment by znikola** [comment]
Not in 1905 yet.

**Comment by meeque** [comment]
An `/oauth/revoke` endpoint according to [RFC 7009](https://tools.ietf.org/html/rfc7009) is now implemented in the oAuth2 extension of SAP Commerce. However, this feature has not been released yet.

So far, I can only provide the information in [HORST-5600](https://jira.hybris.com/browse/HORST-5600), with restricted access.

**Comment by Xymmer** [comment]
have to wait until it's in a release
