### ISSUE TITLE
Add the webApplicationInjector to Spartacus

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#367]
SmartEdit's webApplicationInjector is a js file needed for SmartEdit to do its thing. You load it into your html and it will try to connect to SmartEdit.

Speak to SmartEdit contact about where we find this file and get latest version. 

Copy into our source, link into our html. We'll refine later on how and when to load it.

Acceptance criteria:
- No error in console.
- Otherwise we can't see anything yet. We don't have the contract yet so we won't see blue boxes yet.
- Can see in debugger that new js file is downloaded.

**Comment by WeizhengSap** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/484

**Comment by WeizhengSap** [comment]
webApplicationInjector.js is loaded in app.
![screen shot 2018-11-29 at 7 57 40 pm](https://user-images.githubusercontent.com/44440575/49261689-44299f80-f411-11e8-8a16-097fa15eb971.png)

**Comment by plabadie** [comment]
Strange, there are unit test failures.

**Comment by plabadie** [comment]
Thanks I didn't know that.  The should pass when we re-run them.

**Comment by WeizhengSap** [comment]
Create https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/507 for improvement.

**Comment by plabadie** [comment]
The webApplicationInjector is indeed added to spartacus.

However, the latest version of webApplicationInjector seems to have a bug in it.  We see an errors in the console.  A ticket is open for the smartedit team.

Here is what it looks like:

<img width="1349" alt="screen shot 2018-12-04 at 2 21 39 pm" src="https://user-images.githubusercontent.com/7065346/49467748-26718700-f7d1-11e8-8b20-c0ad485e7f52.png">

**Comment by WeizhengSap** [comment]
Create one smart edit ticket: https://jira.hybris.com/browse/CMSX-8096

**Comment by plabadie** [comment]
The most severe errors are solved by the latest version of the webAppInjector file.

There are a few warnings left that we will need to take a look at when we further stabilize the smartedit integration.

<img width="1677" alt="screen shot 2018-12-04 at 5 09 08 pm" src="https://user-images.githubusercontent.com/7065346/49476259-78bda280-f7e7-11e8-8bd2-4444e001d4cc.png">

**Comment by WeizhengSap** [comment]
I reopen it, because I found that webApplicationInjector.js is not added into dist folder.

Now, I can see it in dist
![screen shot 2018-12-05 at 9 04 41 am](https://user-images.githubusercontent.com/44440575/49518522-d8aa5c80-f86c-11e8-9889-0da0fd695922.png)
