### ISSUE TITLE
Monitor e2e regression tests [master]

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#3674]
The following e2e *regression* tests are failing and need to be fixed:

- billing-address
- my-account/payment-methods
- reset-password
- register

https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/234/console

**Comment by RadhepS** [comment]
Ticket for billing address: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3687

**Comment by RadhepS** [comment]
Billing Address: Bug fix ticket created for it #3687 
Payment-Methods: I'm not able to fail this locally
Reset-Password: Requires dev17 to be updated
Register: I'm not able to fail this locally

Going to hold this ticket as I'll try to fail these tests. If I can't fail them then I'll bring it up in stand-up. A solution may be to add waits() as that is the likely reason for these tests failing on Jenkins.

**Comment by RadhepS** [comment]
Closing because neither Payment-Methods or Register have failed on Jenkins.

**Comment by hackergil** [comment]
Tests are still failing in the Jenkins job that we just ran. If different tests are failing, it is ok to change this ticket description and create follow up tickets but please do not close this one until regression tests are stable

**Comment by RadhepS** [comment]
New tests to fix:
regression/my-account/update-profile.e2e-spec.ts 
regression/site-context/language/language-registration-page.e2e-spec.ts 
regression/site-context/language/language-cart-page.e2e-spec.ts 
mobile/register-mobile.e2e-spec.ts

**Comment by RadhepS** [comment]
All e2e tests failing on Jenkins have either been fixed or already have tickets created to fix them.

This ticket will remain open and I will continue to monitor Jenkins.

**Comment by RadhepS** [comment]
Re-ran Jenkins.

Added new tests that are failing that have not previously been mentioned.

mobile/product-search-store-flow-mobile.e2e-spec.ts - Fixed (https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3705)

**Comment by RadhepS** [comment]
New failure(s) on Jenkins:
language-my-account-pages.e2e-spec.ts

**Comment by RadhepS** [comment]
New failure(s) on Jenkins:
mobile/register-mobile.e2e-spec.ts

**Comment by RadhepS** [comment]
New failure(s) on Jenkins:
regression/my-account/payment-methods.e2e-spec.ts
regression/register.e2e-spec.ts
mobile/cart-mobile.e2e-spec.ts

**Comment by RadhepS** [comment]
New failure(s) on Jenkins:

New locale failure(s):
regression/my-account/order-history-orders-flow.e2e-spec.ts - Fixed (https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3807)

**Comment by RadhepS** [comment]
New failure(s) on Jenkins:
regression/my-account/payment-methods.e2e-spec.ts - Created (https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3970)

**Comment by hackergil** [comment]
Closing this ticket since most of these have been already fixed and there is an ongoing e2e remediation going
