### ISSUE TITLE
Create/modify angular directive to use digits only in the numeric field

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/cloud-commerce-spartacus-storefront#3679]
Currently, we have the type"number" in some fields like i.e. CVV or Card Number, but it does not prevent us from writing "+-.," there. The solution would be to either modify the existing "cxOnlyNumber" directive (if any other use case does not require those symbols" or creating the new directive.

Something similar to: https://codeburst.io/digit-only-directive-in-angular-3db8a94d80c3

**Comment by psmul** [comment]
Steps for QA:

1. Add items to cart
2. Proceed to checkout and Payment details
3. You shouldn't be able to input any special characters like "+-.,"

**Comment by KateChuen** [comment]
Tested on dev17. Not able to input these special chars anymore, only numbers are allowed.
