### ISSUE TITLE
Old shipping address state/province is used when creating a new payment address

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3687]
How to reproduce:

1. Start order process
2. Create shipping address with the following (Country: Canada, State: Quebec).
3. Continue to the payment details page
4. Create a new payment and use a new shipping address. (Country: United States, State: California).
5. Press continue

Expected result:
New payment detail with the address containing the country as United States and the state as California.

Observed result:
Error.
<img width="1440" alt="Screen Shot 2019-07-16 at 3 02 49 PM" src="https://user-images.githubusercontent.com/34665674/61322273-46434180-a7db-11e9-9c4d-5b87c490302f.png">

It attempts to create a payment address using United States as the country and Quebec as the state. It should be creating payment address that has United States as its country and California as its state.

**Comment by plabadie** [comment]
Can not repro.

**Comment by RadhepS** [comment]
Update:
Spoke with Patrick about this.
The original steps no longer produce an error. However, when looking at the e2e test there seems to be a new failure that has the same root cause as this issue.

1. Start order process
2. Create shipping address with the following (Country: Canada, State: Quebec).
3. Continue to the payment details page
4. Create a new payment and use a new billing address. (Country: Poland).
5. Press continue

Expected Result:
Creates new payment detail with Poland as its country and no state.

Observed Result:
Error banner appears and unable to continue:
`RegionModel with country, isocode 'PL, PL-QC' not found!`

**Comment by plabadie** [comment]
A) For steps in the ticket description: for the billing address to be in a different country/region, a server side config must be in place.  So it's a backend config issue.

For the backend to support a billing address in a different country than the shipping address, this config needs to be defined: 
```
mockup.payment.label.billTo.region = billTo_state
```

**Comment by plabadie** [comment]
PR #3712

**Comment by giancorderoortiz** [comment]
This issue is now fixed. :-)

**Comment by RadhepS** [comment]
Ticket will be reverted as it's a breaking change: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3841
