### ISSUE TITLE
Fix E2E tests that go on registration page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3691]
These tests go on registration page, and fail when it needs to click on the dropdown menu of "TitleCode" with this error:
CypressError: cy.click() cannot be called on a <select> element. Use cy.select() command instead to change the value.

Please fix it:
- billing-address.e2e-spec.ts
- order-history-no-orders-flow.e2e-spec.ts
- update-password.e2e-spec.ts
- register.e2e-spec.ts

**Comment by KateChuen** [comment]
@psmul Are the broken tests related to your ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3595? 
If so, can you fix the tests please?
And please please please, next time, can you spare a few minutes to run the related e2e tests to make sure that your changes haven't broken them? 
If they are not related to your changes, I apologize, and you can unassign yourself from the ticket. 
Thank you :)

**Comment by psmul** [comment]
@KateChuen 
billing-address.e2e-spec.ts - has broken tests, however thay are not related to #3595. I'm working currently on it in issue #3402 
For:
order-history-no-orders-flow.e2e-spec.ts, update-password.e2e-spec.ts, register.e2e-spec.ts- all tests passed on my local machine.

Changes for #3595 have been merged to develop 2 days ago, including adjustments in e2e test regarding registration method.

**Comment by KateChuen** [comment]
These test fail when we run them pointing to dev17 for both frontend and backend. 
Although I know the billing test fail for another reason later on (region missing). But when I ran them against dev17, they failed much earlier, at step1, with the same titleCode drop down menu cause. 
Looks like the result is different today. Will try again.

**Comment by KateChuen** [comment]
Re-ran them today. Now they are ok. 
Billing test will be fixed in another ticket.
