### ISSUE TITLE
Error at checkout payment step when billing address does not have a region

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3693]
**Environment Details**
Spartacus: 1.0.1
Browser: Firefox
Device: mac 
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Login
Add item to cart
Proceed to checkout
On Shipping Add Step, use a US address
On Payment Step, use a billing address that does not have a region, for eg: Poland.

**Actual Result**
The error "RegionModel with country, isocode 'PL, PL-NY' not found!" is displayed.

I've tried with and without this config: 

> mockup.payment.label.billTo.region with value billTo_state

<img width="1164" alt="Screen Shot 2019-07-17 at 10 52 37 AM" src="https://user-images.githubusercontent.com/45409515/61385871-39792900-a881-11e9-805d-c4e1687e478d.png">

**Comment by LTiger14** [comment]
This happens because for some reason the shipping region seems to be sent as billing region when no billing region is specified.

![Screen Shot 2019-07-17 at 11 01 50 AM](https://user-images.githubusercontent.com/10605724/61386647-a4772f80-a882-11e9-9c40-24d9adc79059.png)

This should be nothing ⬆️

**Comment by RadhepS** [comment]
Duplicate ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3687

Closing
