### ISSUE TITLE
[Revert] Failing E2E: language-registration-page.e2e-spec.ts

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3699]

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3700

**Comment by KateChuen** [comment]
Ran the newly fixed test against dev17. Works!

**Comment by RadhepS** [comment]
Revert PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3867
