### ISSUE TITLE
Improvement for SmartEdit contract for slots 

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#371]
Current contract was added in dynamic-slot.component.html.
We want to generate slot contract in dynamic-slot.component.ts.
Also check, if no cmsTicketId (SPA not started from smart edit), do not add contract.

**Comment by Xymmer** [comment]
There is no contract for slots
https://wiki.hybris.com/pages/viewpage.action?spaceKey=CxM&title=SmartEdit+Contract+for+Storefronts+-+1811#SmartEditContractforStorefronts-1811-HTMLMarkupContract

**Comment by Xymmer** [comment]
Example:

```
<smartedit-element
   class="smartEditComponent"
   data-smartedit-component-id="Section1Slot-Homepage"
   data-smartedit-component-type="ContentSlot"
   data-smartedit-catalog-version-uuid="electronicsContentCatalog/Staged"
   data-smartedit-component-uuid="eyJpdGVtSWQiOiJTZWN0aW9uMVNsb3QtSG9tZXBhZ2UiLCJjYXRhbG9nSWQiOiJlbGVjdHJvbmljc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJTdGFnZWQifQ==" data-smartedit-element-uuid="c4ee82b2-6a20-4bb8-969f-071e9de0febc"
   ... >
```

**Comment by WeizhengSap** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/703
