### ISSUE TITLE
Compile Error when building SSR

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3723]
When attempting to do the following steps to build ssr:

`yarn build:core:lib`
`yarn build`
`yarn build:ssr`

The last step issues this error:
![image](https://user-images.githubusercontent.com/11735817/61616773-a7e72e00-ac69-11e9-9c1f-c1b206da07a9.png)

**Comment by Zeyber** [comment]
QA Steps:
1) Set base url to model-t
2) Run `yarn build:core:lib`
3) Run `yarn build`
4) Run `yarn build:ssr`

Error should no longer occur

**Comment by KateChuen** [comment]
Able to reproduce the error _before_ the fix.
_After_ the fix, the error is gone. Tested locally. 
<img width="794" alt="Screen Shot 2019-07-23 at 10 01 01 AM" src="https://user-images.githubusercontent.com/45409515/61718827-be58bc80-ad31-11e9-9598-17e748ffe844.png">
