### ISSUE TITLE
Interaction inconsistence: Coupons, shopping cart

### ISSUE THREAD

**Issue by joseegm** [SAP/cloud-commerce-spartacus-storefront#3726]
## Environment Details
Branch: origin/feature/PANDA-3191-apply-coupon-component

## Steps to Reproduce
Add items to the shopping cart -> navigate to the shopping cart -> Click "Enter or remove your coupon codes." link.

## Observed Results
The page scrolls to the coupon component.

## Expected Results
The focus should be set on the "Coupon Code" input line.
![Screen Shot 2019-07-22 at 14 59 03](https://user-images.githubusercontent.com/22662903/61634309-55ba0300-ac91-11e9-9d4a-9fe4989c2cad.png)

## Repository Used
main repo, branch: origin/feature/PANDA-3191-apply-coupon-component

**Comment by kate1zheng** [comment]
fixed
click the anchor, scroll to enter coupon with focus
![image](https://user-images.githubusercontent.com/43032959/66549533-0ee3f700-eb76-11e9-82c3-5bbacd8a5742.png)

**Comment by Xymmer** [comment]
we ended up moving the coupon entryto right side,clsoing
