### ISSUE TITLE
Visual inconsistence: Coupons Shopping cart

### ISSUE THREAD

**Issue by joseegm** [SAP/cloud-commerce-spartacus-storefront#3727]
## Steps to Reproduce
Add items to the shopping cart -> Navigate to the shopping cart page -> Add a coupon code

## Observed Results
The added coupons are displayed.
![Screen Shot 2019-07-22 at 15 01 14](https://user-images.githubusercontent.com/22662903/61634560-d7aa2c00-ac91-11e9-9050-107a3afb19fc.png)

## Expected Results
The "X" button on the right of the coupon element is not vertically centered.
![Screen Shot 2019-07-22 at 15 01 28](https://user-images.githubusercontent.com/22662903/61634599-edb7ec80-ac91-11e9-8f45-7374044252c1.png)

## Repository Used
Main repo, branch: origin/feature/PANDA-3191-apply-coupon-component

**Comment by kate1zheng** [comment]
correct css
![image](https://user-images.githubusercontent.com/43032959/66549403-c9bfc500-eb75-11e9-91c5-bb21d2fe3bab.png)

**Comment by Xymmer** [comment]
we moved coupons to right side and are doing other fixes, closing
