### ISSUE TITLE
Visual inconsistence: Coupons info on the shopping cart overview

### ISSUE THREAD

**Issue by joseegm** [SAP/cloud-commerce-spartacus-storefront#3729]
## Steps to Reproduce
Add items to the shopping cart -> add some coupon codes 

## Observed Results
Spacing between the coupons info is too close to the rest of the shopping cart overview info
![Screen Shot 2019-07-22 at 15 05 43](https://user-images.githubusercontent.com/22662903/61634841-877f9980-ac92-11e9-8812-6290c1982bc3.png)

## Expected Results
![Screen Shot 2019-07-22 at 15 05 29](https://user-images.githubusercontent.com/22662903/61634859-923a2e80-ac92-11e9-9d88-cf212ecc49ec.png)

## Repository Used
Main repo, branch: origin/feature/PANDA-3191-apply-coupon-component

**Comment by kate1zheng** [comment]
fixed
![image](https://user-images.githubusercontent.com/43032959/66549647-4fdc0b80-eb76-11e9-8816-72058b38afe1.png)
