### ISSUE TITLE
Undefined Error and Cart Error on logout in Order Confirmation Page

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#3735]
## Environment Details

On dev-17

## Steps to Reproduce

1st)
-Checkout and place your order until you have reached the order confirmation page.
- sign out from that page

2nd)
- After signing out, and being an anonymous user, try to add a item to a cart

## Observed Results

1st)
- console error will show many errors

2nd)
- it will show a global message error saying 'Cart Not Found'

## Expected Results
No error should have occurred

## Additional Information

1st)
![Screen Shot 2019-07-22 at 3 21 52 PM](https://user-images.githubusercontent.com/29099466/61659274-21484600-ac95-11e9-86a5-8885bc72ce0e.png)

2nd)
![Screen Shot 2019-07-22 at 3 27 49 PM](https://user-images.githubusercontent.com/29099466/61659359-4b9a0380-ac95-11e9-9fa1-e68de76bb575.png)

**Comment by plabadie** [comment]
Sounds similar to GH-2673

**Comment by LTiger14** [comment]
Also requires to QA this use case #4635

**Comment by LTiger14** [comment]
### For QA:

1. Turn on guest checkout
2. Make a checkout as regular user
3. On the order confirmation page, logout with the console open
4. You should not see errors
5. Do a guest checkout and create an account on the order confirmation page with the console open
6. You should not see errors

**Comment by giancorderoortiz** [comment]
Test successful. 
No errors seen in console except 404 on 9002/rest/v2/electronics-spa/cms/pages?fields=DEFAULT&pageType=ContentPage&pageLabelOrId=/logout&lang=en&curr=USD, which I'll log as a separate issue.
