### ISSUE TITLE
Meta tags for safari

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#374]
Add to home screen works pretty nice on Chrome browser and other supporting it. We can enhance experience for Safari users with proper meta tags.

Docs here: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

You can also check tags on https://mobile.twitter.com

More info about add to home screen feature: https://caniuse.com/#search=manifes

**Comment by gladius-mtl** [comment]
Thank you for the doc input, @marlass ! I have created a doc ticket to follow up: GH-379.

**Comment by Xymmer** [comment]
@marlass : what was the fix we did here, so it shows up in the "share/send" button menu in ios?
