### ISSUE TITLE
Add support for assets library snapshot builds

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#3744]

**Comment by KateChuen** [comment]
Tested on dev2. 
Able to deploy spa shell app that uses a snapshot build for assets library. 
Compiled and started the app without error.
Ran a quick smoke test, OK. 

<img width="682" alt="Screen Shot 2019-07-25 at 2 00 08 PM" src="https://user-images.githubusercontent.com/45409515/61899742-1cc89b00-aeea-11e9-8287-de04cb7bda84.png">
