### ISSUE TITLE
Splash Screens for iOs

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#3775]
@Manurod2018 as discussed previously: Nikola requested some splash screens for iOS devices, which is related to this ticket GH-3292.

He provided [this generator](https://appsco.pe/developer/splash-screens?source=post_page---------------------------) and suggests it could be as simple as a white background with the Spartacus logo in the middle. 
Since it's a visual, I suggested we should get your insight and creative suggestions first.
I understand you may have some concerns regarding this topic, can you please elaborate on that.

cc. @znikola @Xymmer

**Comment by Manurod2018** [comment]
Hi Miguel, we are actually in the process of creating a brand for Spartacus and get it to be approved by SAP.Until something is officially approved we can’t release a temporary logo and need to use the generic SAP logo on the storefront. Therefore I would wait until we have something final. This has to go through the proper channels.

**Comment by znikola** [comment]
@Manurod2018, ok thanks. As a temporary solution that will serve as a showcase, we can have the Spartacus logo on a white background? Or does it have to be SAP logo?

And later down the road, once you have the proper splash screens we can just replace the old images.

**Comment by Xymmer** [comment]
our Spartacus logo is fine for now

**Comment by developpeurweb** [comment]
@znikola 
As per Bill's comments we'll use current Spartacus logo for now.
That said, white feels a bit plain to me, how about blue background so it matches our Spartacus shirts?
Pls find zip file attached. I believe you can take the html from the generator page, otherwise let me know.

[splashscreens-spartacus.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3442578/splashscreens-spartacus.zip)
