### ISSUE TITLE
1.d Add form validation to the checkout login form

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#3784]
The checkout login form already exists but does not have any form validation. See guidelines for actions to see how the form should act.

We need a valid email and both should match.

---
From @vekterdude:
* email validation messages: inline
* No elements on the page should be grayed out
* If the form is submitted with terms and conditions checkbox not checked, a global error message should show up

--- 
From @vekterdude  on 8/8
* Guest checkout should not comply with terms and conditions. Please remove the checkbox.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-08-25 at 6 46 40 PM](https://user-images.githubusercontent.com/46171897/63656974-57cc2180-c769-11e9-9856-0b70dd171c8b.png)

**Comment by giancorderoortiz** [comment]
Test successful
