### ISSUE TITLE
Doc input required (Gladiators)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3786]
The following Gladiators tickets still need doc input. 
The tickets were closed and part of 1.0 release so I moved them to Accepted 1907-04 sprint (https://github.com/SAP/cloud-commerce-spartacus-storefront/projects/48).
After reviewing the issue, add a comment here indicating to Matt if there is anything to do.
When all reviewed, assign this ticket to Matt.

- [x] #2744 (Gil)
- [x] #2911 (Marcin)
- [x] #169 (Nik)
- [x] #2793 (Gil)

**Comment by gladius-mtl** [comment]
There are no comments from any of the reviewers, so I assume this ticket can be closed...
