### ISSUE TITLE
Framed tickets that require doc input (Louis)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3789]
The Framed project will be retired.
https://github.com/SAP/cloud-commerce-spartacus-storefront/projects/4

We have many tickets in doc input still.

**Comment by LTiger14** [comment]
Found one ticket with doc required. Created this https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/issues/247.

Will track there.
