### ISSUE TITLE
Doc input still needed for issue #3244

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3793]
The following tickets from the big Release 1.0 board still need doc input.
The tickets were closed and part of 1.0 release so I moved them to Accepted 1907-04 sprint (https://github.com/SAP/cloud-commerce-spartacus-storefront/projects/48).
After reviewing the issue, add a comment here indicating to Matt if there is anything to do.
When all reviewed, assign this ticket to Matt.

- [x] #3244 (Wei?)

**Comment by gladius-mtl** [comment]
There are no comments indicating further work is needed, so I will close this ticket now...
