### ISSUE TITLE
Accessibility Feature 1 (Kacper) (keyboarding first?)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3797]
This is the master ticket for Accessibility.
Keyboarding is probably first releasable chunk.

See the project: https://github.com/SAP/cloud-commerce-spartacus-storefront/projects/40

**Comment by kacperknapik** [comment]
### QA steps
NOTE: I recommend to check 'happy path' first.

#### Preparation
1. checkout to `develop` branch
2. turn on `calydon` theme

#### Steps
1. go to the home page
2. check tabbing (go through the app with `TAB` key)
  - you can also try `SHIFT + TAB` (tabbing backwards)
3. check focus (all elements should be visibly focused)
4. check the skip links element
  - click on the URL bar in your browser
  - press `TAB` key
  - you should see the skip links element
  - play around with it
5. check auxiliary keys (arrows, space, etc)
  - go to header navigation menu
  - navigate to menu element with a dropdown, using `TAB` key
  - press `SPACE` key
  - try to play with arrow keys

#### Important
We are still working on some bugs from a11y, so please check firstly if certain problem was already found.
