### ISSUE TITLE
Shipping address page is sending endless requests when country is selected

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#3802]
Hi,

when going through checkout process and when a country is selected for shipping address , the endlos requests are triggered. Page gets freezed and nothing works

## Environment Details

- Spartacus-Repo:  Master and develop Branch
- Browser:  chrome
- OS: Linux (Centos7)

## Steps to Reproduce
* Checkout master branch and start server in dev mode : 'ng serve'
* Add article to cart and click on 'proceed to checkout' button
* On Shipping address page select country 'Germany' 
(now page will freez)

## Offer to Fix
NO

(As this request have empty response https://storefront.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/rest/v2/electronics-spa/countries/DE/regions?fields=regions(name,isocode,isocodeShort)&lang=en&curr=USD  new request is sent, which ends-up into endless loop)

**Comment by kacperknapik** [comment]
are you able to confirm that this behavior is also visible in any other places with `country` select or is it just `shipping-address` page's problem?

**Comment by kacperknapik** [comment]
Duplicate #2825

**Comment by Xymmer** [comment]
a little info on #2825: we saw an endless looping scenario and thought it was fixed. we have reopened that issue and are looking into it.
