### ISSUE TITLE
Merchandising carousel [master]

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3810]
scope was just merch carousel, if you can prove it’s working, that’s enough for the moment

**Comment by bgambocjaviniar** [comment]
Change to my branch that I used of what Tobias did because his branch did not work
https://github.com/SAP/cloud-commerce-spartacus-storefront/tree/feature/test-cds-demo

**Comment by bgambocjaviniar** [comment]
QA:

https://wiki.hybris.com/display/spar/CDS%2C+Anonymous+Consent%2C+Merchandising+Carousel

in the comment section :)
