### ISSUE TITLE
Production flag for environment config files not working

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#383]
The production flag in environment.x.ts files seems to be ignored. If it's set to false on the ci or qa files and you run a build, the javascript is still bundled and minified.

**Comment by LTiger14** [comment]
From what I've seen, this flag doesn't affect the actual building and bundling of the app. This is actually used inside of the storefront to enable or disable certain feature based on if the app is running in production mode or not. One example of that is the features related to PWA. According to what I can see this seems to be working as intended.

**Comment by znikola** [comment]
As @LTiger14 pointed out, this flag is used only internally in Angular (during runtime) and not during the build time.
However, there's a way to make the `yarn start -c=ci` to use the source maps and not to minify the code with the following setup in `angular.json`:
```
            "ci": {
              "fileReplacements": [
                {
                  "replace": "projects/storefrontapp/src/environments/environment.ts",
                  "with": "projects/storefrontapp/src/environments/environment.ci.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": false,
              "aot": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false,
              "tsConfig": "projects/storefrontapp/tsconfig.app.json"
            },
```

**Comment by hackergil** [comment]
Yes let's make this change.
