### ISSUE TITLE
Unable to checkout on new model T

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#385]
We are unable to checkout (pay) when testing against the new Model T.

On the new Model T, we are using the sop-mock payment gateway instead of cybersource (which is what the Walkers model T is using).

In the HTML response of the sop-mock endpoint (once the payment info is sent) we can see the following missing fields:

* card_cardType
* card_cvNumber
* card_expirationYear
* card_expirationMonth

Therefore, the transaction is rejected.

OCC endpoint: https://storefront.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Comment by plabadie** [comment]
Fixed. 

Here is the solution in case we need to refer to if in the future:

There were no mappingLabels sent/returned by the mock payment provider.

To solve this I went in Backoffice -> Base Commerce -> Base Store -> Electronics
Then in the PAYMEN PROVIDER section, I set the value to `Mockup`.
