### ISSUE TITLE
Smoke testing the libs

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#386]
Use this server: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/

Keep the browser's console open at any time and monitor for errors.

Perform the following smoke tests:
* Register, logout, login with the previously registered user
* Go through checkout flow with the previously registered user:
  *  Search for a product and open it
  *  Check all tabs (product details, specs, reviews and shipping)
  *  Add it to cart
  *  Search for any other product and add it to cart directly from the search results page (don't open the product, just click on "add to cart")
  *  Change quantity
  *  Create a new shipping address
  *  Create a new payment method
  *  Repeat for an existing user (any user that was registered before the smoke testing)
 * Check all other functionality/pages and observe is basic functionality broken, are there any UI elements broken, etc.:
    * Order history page
    * Change language/currency
    * Sort
    * When searching, use facets and filters
    * Check pagination

**Comment by Jim-Yang** [comment]
Checkout process fails at adding a new payment

CORS seems to be disabled

```
Access to XMLHttpRequest at 'https://testsecureacceptance.cybersource.com/silent/pay' from origin 'http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by Xymmer** [comment]
we released the libs, but let's investigate if the checkout problem was temporary. i tried just now and it worked.
