### ISSUE TITLE
PR from Walkers: Store-Finder - impossible to go to store-description page

### ISSUE THREAD

**Issue by eliztrinh** [SAP/cloud-commerce-spartacus-storefront#388]
Refer to E2EC-1177. 
PR is #391

**Comment by Xymmer** [comment]
Chris says: 
Please ignore the PR above, the fix doesn’t work for countries that do not have regions (e.g. Japan). I am working on another fix.

**Comment by ChrisXJH** [comment]
PR is up again: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/391
