### ISSUE TITLE
Setup dev server for this feature branch

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#3890]
Talk with Gil about finding which server to use. Make sure the backend is up to date with the latest 1905. 
No special configurations are needed in the backend.
The server should deploy the feature branch.

**Comment by giancorderoortiz** [comment]
6 dev-servers made available for feature dev. 
Pick and choose. 
See https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4030

**Comment by hackergil** [comment]
Epic branch installed on http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200

**Comment by giancorderoortiz** [comment]
deployed in dev-12

![Screen Shot 2019-08-23 at 7 27 21 PM](https://user-images.githubusercontent.com/46171897/63628726-165a3b80-c5dc-11e9-8a10-dbdd0a56e540.png)
