### ISSUE TITLE
[AFTER #1179]Update Guest Checkout Guard to let the user through once he added his email

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#3893]
This ticket is to update the guest guard (#1182) to let a guest user though once an email exists in the cart.*

***Note** A guest user will have a user in the cart like follows, if it's the case, the guest checkout guard should let the customer proceed to checkout. In order to get this you have to add `fields=user` to the cart request.

`user {
   "name": "guest",
   "uid": "472099c7-ade1-44ab-8e62-33ef66d6bd9a|xxxxxx@acme.com"
}`

When the email is added to the cart a guest user is created in the backend.

### Acceptance criteria
- Once the email is in the cart the checkout guard should let the user access the checkout

**Comment by LTiger14** [comment]
QA Steps:
- Login 
- Add an item to cart
- Checkout
- Logout
- Add an item to cart
- Click proceed to checkout -> Guest login
- Enter email & confirm email (validation not tested here)
- Submit
- You should go to address form

Know issues #4008

**Comment by giancorderoortiz** [comment]
Test successful

**Comment by giancorderoortiz** [comment]
Tested on dev-com6. Deployed epic/guestcheckout-fr1 branch
