### ISSUE TITLE
Failing e2e tests

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#3898]
Below specs are failing (tested with dev-17, release branch `release/1908-01`):

**regression/my-account/update-profile.e2e-spec.ts**, update profile when a user is logged in:
- should be able to update its profile `CypressError: cy.click() cannot be called on a <select> element. Use cy.select() command instead to change the value.`
- should be able to see the new updated profile `CypressError: Timed out retrying: Expected to find element: 'cx-update-profile-form .ng-value .ng-value-label', but never found it.`

**regression/site-context/language/language-my-account-pages.e2e-spec.ts**, Language switch - my-account pages:
- should change language in the page `CypressError: cy.click() cannot be called on a <select> element. Use cy.select() command instead to change the value.`

**regression/site-context/language/language-registration-page.e2e-spec.ts**, Language switch - registration page:
- should change language in the page `CypressError: cy.click() cannot be called on a <select> element. Use cy.select() command instead to change the value.`

**Comment by RadhepS** [comment]
This tests have already been handled in the Gladiator's sprint board.

Update-Profile: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3871
language-my-account-pages: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3868
language-registration-page: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3870
