### ISSUE TITLE
[Wait for other anonymous consents issues to be done] Write e2e tests for anonymous consents

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#3900]
# General

See master ticket for more details: #3800

Create a PR against the master feature branch.

## Cases to cover

The e2e tests should cover the following cases:

- Moving from Anonymous User to Logged In Customer - once the user logs in, the consents that were given as an anonymous user are ignored, and the consents of the currently logged in user are restored, see ["Moving from Anonymous User to Logged In Customer"](https://help.sap.com/viewer/9d346683b0084da2938be8a285c0c27a/1905/en-US/fbf047927e8845038581d49c22d37bc3.html)
- The case when a user is moving from an anonymous user to a registered user, the consents _should_ be transferred (see [Moving from Anonymous User to Registered Customer](https://help.sap.com/viewer/9d346683b0084da2938be8a285c0c27a/1905/en-US/fbf047927e8845038581d49c22d37bc3.html)). E.g. if an anonymous user gave a tracking consent, and then the user decided to register, the tracking consent should be _automatically given on the back-end_ once the user registers. However, this is not working as intended when using the OCC APIs. Check if it was fixed in the meantime, if not skip this. _UPDATE_ - we will implement a workaround for this, so this case can still be covered.
- In the old accelerator, when an authenticated user logs out, the previously given consents are restored (when the user was anonymous, i.e. was not logged in). See ["Moving from Logged In Customer to Anonymous User When Logging Out"](https://help.sap.com/viewer/9d346683b0084da2938be8a285c0c27a/1905/en-US/fbf047927e8845038581d49c22d37bc3.html)
- The language change should not affect the anonymous consents state. The language of the consents should change, but not their `consentState` values.
- Giving consent on the registration page
- Maybe it would be a good idea to test a required consent (#4462), but not sure how to change the configuration in the run-time, and mark one of the sample consents as required.

**Comment by znikola** [comment]
PR: vhttps://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4959

**Comment by bgambocjaviniar** [comment]
PR: GH-4981
