### ISSUE TITLE
Setup a dev server with ASM work in progress.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#3910]
Setup dev02 with an asm enabled backend is done in : GH-3911

The goal of this ticket is to deploy the frontend on dev2 on the `epic/asm` branch.
We need to make sure we have the means to regularly update the server with the latest development on the `epic/asm-mvp-1` branch

**Comment by giancorderoortiz** [comment]
Several dev-servers made available. 
See https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4030

**Comment by plabadie** [comment]
We'll deploy manually when the epic branch is updated.  The script supports that we specify a branch to deploy

**Comment by plabadie** [comment]
Applied it on dev2 with the epic branch.

**Comment by giancorderoortiz** [comment]
what is the url in spartacus for enabling asm?
