### ISSUE TITLE
Log in customer support agent in the storefront.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#3914]
As a customer support agent, I want to authenticate in the storefront.

* Make an asm component draft and call it's selector directly from the shell app.  How we end up implementing the component will be revisited.
* I use the asm form/component to provide the cs agent's credentials and sign in as an customer support agent.
* The rest of the storefront still behaves as if there were no customer authenticated.
* The asm login form is replaced by a logout button.
* The agent uses the log out button in the asm ui to sing out.

Other acceptance criteria:
For local smoke test only: In redux dev tools I can see the agent token. (state slice : auth.csagentToken.token)

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by plabadie** [comment]
For tests:
- For QA I will set up the dev2 Spartacus to deploy the epic/asm-mvp-1 branch.
- For review, you can point a local Spartacus instance to the dev2 backend.

Functionalities:
- See the ticket description for the overall idea of what we expect the feature to do.

Additional info:
- The component's visuals is a very rough draft.  For now, it always appears at the top of the page.
- Proper visuals ore obviously not there, they will be added later.
- Both username and password fields are mandatory. Form validation behaviour should follow the site guidelines.

**Comment by plabadie** [comment]
PR #4034
