### ISSUE TITLE
Add Express Checkout service

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3917]
Express checkout service should verify is possible to do the express checkout (any shipping address, any payment method).
- If yes, it should set up the default shipping address, delivery mode and payment method by endpoints #1617
- For now, the delivery mode should be configurable by store owner (storefront config #3923). Later it can use also #3915/#3920.

This service should have a method for setting default checkout options.
We'll re-use existing checkout button / page label.

**Comment by Pucek9** [comment]
@Xymmer 
I have some new edge cases, which should be chosen in:
```typescript
defaultDeliveryMode: [DeliveryModePreferences.FREE, 'premium-gross'],
```
If there is no free option, should it take first cheapest or iterate to next and take the most expensive? 
What has a bigger priority?

**Comment by Xymmer** [comment]
first cheapest

**Comment by Pucek9** [comment]
@Xymmer 
After discussing with Marcin, we can see the handicap of this solution. 
We used an array for allowing prioritize options, first matching will be chosen.
The previous example means, what if store owner want to set free, or most expensive (if free is not available), similar to ``defaultDeliveryMode: [DeliveryModePreferences.FREE, DeliveryModePreferences.MOST_EXPENSIVE],``

I know that it is an edge case, but we should still support it. Else, arrays have sense only with codes. Still if the store owner set only ``defaultDeliveryMode: [DeliveryModePreferences.FREE]`` then will be chosen least.
What do you think about it?
