### ISSUE TITLE
Update Checkout configuration with default delivery mode

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3923]
Similar to enabling the feature itself, provide some way for seller to configure default delivery

For now we can't get or save delivery config in backend.

- By default, or if not configured, use free or least expensive delivery option
- Configuration options: free option, least expensive non-free option, most expensive option, OR
specify code of delivery option to use by default (however if this doesn't exist, default to our default)

**Comment by Pucek9** [comment]
@Xymmer 
What is the difference between free and least expensive?
If we have config 'free' and there is no free option should it use the least expensive or do something else?
What if we config 'least expensive' and there will be a free option too?

**Comment by Xymmer** [comment]
I see three options:
- free
- least cost (cheapest price for shipping that still costs money)
- most cost

**Comment by Pucek9** [comment]
We can allow for set list of preferences, the first match will be chosen.
```typescript
defaultDeliveryMode: ['code1'],
// or
defaultDeliveryMode: [DeliveryModePreferences.FREE, 'code1', 'code2'],
```
Should we still support?
```typescript
defaultDeliveryMode: 'code1',
// or
defaultDeliveryMode: DeliveryModePreferences.FREE,
```

**Comment by Pucek9** [comment]
After discuss with @marlass and @dunqan we decide to not support simplified setting here. 
We do not support it anywhere, so if we want to change it, we should update all occurrences of this case.
