### ISSUE TITLE
Determine configurable endpoints feature has breaking changes

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3932]

**Comment by LTiger14** [comment]
Unfortunately I can see 6 breaking changes. Two are from adding a new property to the constructor (https://github.com/SAP/cloud-commerce-spartacus-storefront/compare/epic/configurableoccendpoints#diff-885e862edc484dc665b7da7a341c5b55R13 & https://github.com/SAP/cloud-commerce-spartacus-storefront/compare/epic/configurableoccendpoints#diff-113c4babe45e0628f27d1a6ffced82d3R15). 

The other four are from removing `protected` methods, IMHO these methods should have been private. (https://github.com/SAP/cloud-commerce-spartacus-storefront/compare/epic/configurableoccendpoints#diff-5cc7bc26b65675a42c8ee7f06d40d749L23 & https://github.com/SAP/cloud-commerce-spartacus-storefront/compare/epic/configurableoccendpoints#diff-708f5f2222b115ef82585cc78d6b1832L93 & https://github.com/SAP/cloud-commerce-spartacus-storefront/compare/epic/configurableoccendpoints#diff-a5aac1f2718c8f5b04849742d60e14f1L27 & https://github.com/SAP/cloud-commerce-spartacus-storefront/compare/epic/configurableoccendpoints#diff-8dff449a3307a65f72470e79caff288cL18)

**Comment by LTiger14** [comment]
A mitigation mechanism was put in place
