### ISSUE TITLE
Can not use 'product-list-component.service' as provider

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#3935]
As in ProductListComponentService the RELEVANCE_CATEGORY value is hardcoded, which can not be changed by any other-way, so I decided to write my own CustomProductListComponentService and copied all code and changed the value of relevance category. 
Now i am providing my custom class in providers as following:
```
@NgModule({
  imports: [
    B2cStorefrontModule.withConfig({
    ....
  ],
  declarations: [AppComponent],
  entryComponents: [],
  providers: [{
  {
    provide: ProductListComponentService,
    useClass: CustomProductListComponentService
  }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
The ProductListComponentService get imported from following path
```import { ProductListComponentService } from '@spartacus/storefront/cms-components/product/product-list/container/product-list-component.service ```

On compile time i getting following error:
```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '@spartacus/storefront/cms-components/product/product-list/container/product-list-component.service' in '/mypath/myApp/src/app'
```
## Environment Details
- Spartacus:  
    "@spartacus/core": "~1.0.1",
    "@spartacus/styles": "~1.0.1",
    "@spartacus/storefront": "~1.0.1",
    "@spartacus/assets": "~1.0.1"
- Browser: chrome
- Platform: Linux (Centos 7)

Expected:
1. It should be possible to override this class by a provider
2. or as a workaround for now, how can I set RELEVANCE_CATEGORY 
 to  ':relevance:xyzCategory:' ?

## Offer to Fix
NO

**Comment by marlass** [comment]
This service is not yet ready to be public.
You can use a hack with importing not public export and aliasing it.
Example for 1.0.1 : `import { ɵf as ProductListComponentService } from '@spartacus/storefront';`

We need to take a closer look at this service and improve it before adding it to public API.

**Comment by johntday** [comment]
@mrSingh007 I had this same issue when trying to extend `ProductListModule`
