### ISSUE TITLE
Spike geolocation based on IP using Google maps

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3941]
When customer gets to storefinder, we'd like to display something right away:
- if we can guess their location, display stores based on that location
- otherwise display the regions list ('view all stores')

Using Google maps can we submit customers IP and get a location?

Also can this be used to avoid us having to trigger location permission in Google maps?

**Comment by psmul** [comment]
Few conclusions after investigating topic:

1. Displaying something right away
Displaying google maps is blocked/hidden till we don't have a response from the server regarding list of positions/stores which should be shown.

2. Sadly (on client's side) we cannot omit step with asking users for their permission for Geolocalization (https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API).

3. Trying to retrieve client's ip via google maps might be considered security breach. Still, it's not available to do so.

4. Geolocalization is still not as accurate, as we would like it to be. After couple of tests made, none of them showed specific location, based on IP address, where request was made. All of them resulted in pointing places 2-3 streets away from specified location (via geolocation web api).

Proposed solution:
Adjust backend /stores query request to accept parameter something like "geoPoint(ipAddress)" which will indicate backend to provide functionality to get client's ip address from request and parse it to geolocation and then return matched store list in this area.
