### ISSUE TITLE
Wrong Message/Handing when Re-Registering

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3945]
Follow up to https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2799

**Steps to Reproduce (From Kasper)**

1. Open the app
2. Go to register form
3. register a completely fresh user (at this point you should be redirected to login page and have global message with success info)
4.log out
5. Go to register form again
6. Register THE SAME user as above (you also should be redirected to login page with the same global message)

**From Kate:** 
Registering the same existing user (with both the correct and wrong passwords) give the same message on the login page.

**From GC:** 
When attempting to re-register a user, after redirection to login page the wrong error message says "Please login with your new credentials", which is false. There are no new credentials.
Here, a decision is needed as follows:
1.a. Show nothing and redirect to login page.
1.b. Show error message stating email is already in use and remain in registration page.
1.c. Show error message and redirect to login page.

Don't understand the REST POST call /rest/v2/electronics-spa/users/?lang=en&curr=USD after redirection. It contains the user data of the previous registration attempt.

**Comment by kacperknapik** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2799#issuecomment-519011442
