### ISSUE TITLE
[probably fixed, waiting to see if truly fixed] Sonarcloud status check not working

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#3946]
Our github repository is not getting notifications from SonarCloud. Therefore, our PRs can't be merged at the moment.

I've disabled the SonarCloud check for all branches at the moment but this needs to be fixed.

**Comment by marlass** [comment]
I recently updated 5 PRs and all of them get a proper status check from SonarClooud.

Is it still an issue?

**Comment by hackergil** [comment]
Sonar checks are disabled for develop and epic branches at the moment. I will enable it back to add some sample PRs or disregard this.
