### ISSUE TITLE
[Discussion needed] What should we do with checkout data when we empty cart?

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#3955]
There is strange behavior with the cart (dev-17).

1 After deleting all products, cart/checkout state is not cleared.
2 After refreshing the page, cart status is clean
3 After adding other product to cart, it loads from backend old cart data (id and e.g. shipping method, delivery mode if chosen)

The only finalization of checkout process can clean cart status.

**Comment by Pucek9** [comment]
We need to call delete on /{baseSiteId}/users/{userId}/carts/{cartId}
after remove last item

**Comment by KateChuen** [comment]
Please follow up with Gil & Wei whether a new cart should be created right away.

**Comment by KateChuen** [comment]
Follow up with Michal to confirm our understanding.

**Comment by Matejk00** [comment]
After talk with @marlass he decided to put this ticket "on hold", because of the cart refactor job.

**Comment by Xymmer** [comment]
cart refactor done or almost done, let's take another look and do something, or close

**Comment by psmul** [comment]
After some investigation and coming back to this task, some fields can be still found filled even with an empty cart. E.g. we have data coming from backend about a selected price for shipping method, however, those fields are re-initialized when we proceed to checkout steps.

Decision is required whether we should manually deal with clearing checkout steps if user will empty his cart or should we report this issue to the backend?

**Comment by tobi-or-not-tobi** [comment]
I don't think we should clear the cart after the (last) item is removed. Specifically, the following scenario might happen quite often:

1. user adds item to the cart
2. user needs help and asks a service agent
3. service agents impersonates user and starts helping the user

In the above flow, either the user or the user agent might remove items from the cart to replace it with the right item. In case we'd remove the cart upon such action, the user or agent would no longer have access to the cart.

**Comment by psmul** [comment]
After discussion with @marlass and @dunqan this topic will be closed and divided into 2 issues:
- unnecessary clearing of delivery mode when proceeding to checkout ( #6059 )
- replacing total price value taken from cart object ( #6061 )
