### ISSUE TITLE
Refactor breadcrumb component to use CmsComponentData

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#397]
See #401 for description and acceptance criteria.

**Comment by maazahmed12** [comment]
Hi! I implemented breadcrumbs but faced an issue around CMSComponentData which I raised here, https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/834! here is my work for it can you kindly review the breadcrumb component
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/823
