### ISSUE TITLE
Update modeltserver: latest 1905, ssr, smartedit

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3982]
[ ] - Latest 1905 (not Gil)
[ ] - SSR (need help from ModelT) (Gil) (done by https://jira.hybris.com/browse/MTD-8912)
[ ] - SmartEdit (not Gil)
[x] - PWA

Update on SSR: a new application definition containing a new builder is coming. Once that’s available in production, they will update our server. Bill to keep track, but ssr on hold for the moment.

**Comment by Xymmer** [comment]
yi's doc: https://help.sap.com/viewer/DRAFT/a16cd2c987ef45f183065aa694733efe/DEV/en-US/cd5b94c25a68456ba5840f942f33f68b.html

**Comment by hackergil** [comment]
SSR deployment is not working on CCv2. Waiting for the Model T team to tell us why.

**Comment by Xymmer** [comment]
The plan is to roll our modelt back so that it's working for now.
We get help on getting ssr working.
We move modelt to latest 1905 patch + latest Spartacus.
MANUALLY test Spartacus because we know the e2e tests will fail.
Then we can have someone adjust e2e tests to work both with dev17 and modelt.

**Comment by hackergil** [comment]
CCv2 server deployed as part of #5448 (sorry, it was me again)

https://spartacus.c39j2-walkersde1-d3-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/
