### ISSUE TITLE
Slot content is not cleared when navigating to a new page

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3987]
We've noticed in #3938 that when a slot position is used on the page, and remains being used on the next page, the content of the former page is (re)rendered even if the new page doesn't provide content for the slot. It seems that the page slot content is not cleared. 

All page slots that are not used in the next page should be cleared. Other slots however should remain to benefit performance.

**Comment by dunqan** [comment]
The bug was caused by a broken component. If the component works correctly, the bug doesn't happen.
