### ISSUE TITLE
Revert exclusions config change from #3527 that made it into 1.0.2

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3998]
(Stan to refine as needed)

Goal:

Revert config change (first, because it's breaking, 2nd it's not a good idea that default config utilizes exclusions), and for the actual feature -> it's not so critical, so can stay (but if we do clean up anyway, we can be strict about it also). 
Let's inform this customer afterward.

Backstory:

As reported by Stan, we released a feature in 1.0.2(3):
https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/8e89ffedc9fb7efdb7e2ada59151dba91815757f

The config part is problematic here.
1. We had no exclusion mechanism in 1.0, so we only defined what to sync (sync only parts of the user token)
2. We released config exclusion mechanism (feature, but non breaking) + new default config that basically says: sync whole user token, BUT exclude refresh token
And because that exclusion mechanism unfortunately takes precedence, old config where customer included refresh token in sync, stopped to work in 1.0.2

exclusion mechanism is already covered in published docs: https://sap.github.io/cloud-commerce-spartacus-storefront-docs/configurable-state-persistence-and-rehydration/ (edited)

**Comment by marlass** [comment]
To test:
- excludeKey should not work
- you could add refresh_token to synced keys in app and it would be synced
