### ISSUE TITLE
Add smartedit contract to web components

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#4005]
Currently we add smartedit contract only for angular cms components. 
We should explore if it's possible to add it also to cms web components, to make them work with smartedit. 

To work on the functionality and tests, it's possible to use web components from this repo:
https://github.com/dunqan/react-cms-web-component

**Comment by WeizhengSap** [comment]
I will do some testing on it. I think, smartedit does not support this kind of purely frontend component.

**Comment by WeizhengSap** [comment]
To QA:

The steps are:
1. get `bundle.js`. You can get it from here: https://github.com/dunqan/react-cms-web-component (clone then build). Or you can ask Stan or Wei directly for this js file.
2. put this `bundle.js` into `storefrontapp/src/asset`
3. add 
```
cmsComponents: {
        BreadcrumbComponent: {
          component: 'assets/bundle.js#breadcrumb-cmp',
        },
        CMSParagraphComponent: {
          component: 'assets/bundle.js#cms-data',
        },
      },
```
into app.module
4. start SPA, and go to `sale` or `faq` page, you should be able to see the paragraph component containing the json text.

5. Go to smartedit, in `sale` or `faq` page, you should be able to edit the paragraph component.
![Screen Shot 2019-08-12 at 10 10 51 AM](https://user-images.githubusercontent.com/44440575/63095737-f8d10600-bf39-11e9-9825-ed6f657252bf.png)

**Comment by KateChuen** [comment]
Tested on dev10, on both the sale & faq pages.
Could see, edit, clone & remove the component on smartedit.
<img width="1278" alt="Screen Shot 2019-08-15 at 1 32 07 PM" src="https://user-images.githubusercontent.com/45409515/63114218-482b2c80-bf62-11e9-868e-3d470780727d.png">
<img width="1427" alt="Screen Shot 2019-08-15 at 1 33 50 PM" src="https://user-images.githubusercontent.com/45409515/63114219-482b2c80-bf62-11e9-9325-909e1a0748e8.png">
