### ISSUE TITLE
Fix issue with starting guest checkout and trying to login

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#4008]
There is a know issue that occurs if a user begins the guest checkout process and tries to login once an email is assigned to the cart. Spartacus attempts to merge the carts but since the cart is not anonymous, an error is thrown. There is a backend ticket for this RAY-392.

Possible solutions/mitigations:

- Backend change to allow the merge or allow cart to be made anonymous again
- Wei: Stop the user from login in, Bill: Maybe not the best UX
- Bill: Clone the cart

**Comment by WeizhengSap** [comment]
Only stop user from login when user in checkout process.

In Spartacus side, if user is "guest", after login, not do the cart merge. The guest's cart becomes user's current cart. (need an occ call)

In occ side, need add method "replaceCartAssignedUser" in controller.

**Comment by giancorderoortiz** [comment]
I agree with Wei's comments. User shouldn't be able to login when a guest checkout operation is in process. 

![Screen Shot 2019-08-11 at 2 58 03 PM](https://user-images.githubusercontent.com/46171897/62838496-1c9b0000-bc4b-11e9-95d6-711cf7adf3bf.png)
![Screen Shot 2019-08-11 at 2 58 26 PM](https://user-images.githubusercontent.com/46171897/62838497-1c9b0000-bc4b-11e9-9b58-4e4bc272734e.png)

**Comment by giancorderoortiz** [comment]
Observed:
1. If a guest checkout email has been provided, but cart is subsequently cleared, then the "guest checkout state" is kept for the subsequent checkout operation. It appears to me that if there are no items in cart (empty cart), then the state here should return back to initial state, where the user is given a choice whether to checkout as guest, or registered user.

**Comment by Xymmer** [comment]
To cover this corner case we'd need to copy cart contents to a new cart, since there is no way to clear guest checkout. But we'd ask occ team for a way to do this in the future.

**Comment by Xymmer** [comment]
talked with michael, we'll allow guest checkout with any email as long as we can verify that the order is not associated with an existing account.

**Comment by giancorderoortiz** [comment]
A simple use case is an user that suddenly remembers he has an account, and aborts the guest checkout process and attempts login. In this scenario, he's stuck with current implementation.

**Comment by LTiger14** [comment]
### For QA/Review:

1. Add product to cart
2. Proceed to checkout and select Guest Checkout
3. Enter an email and click proceed
4. Go to login page
5. Login
6. The cart should contain the contents of the guest cart and of the old user's cart

**Comment by LTiger14** [comment]
The intended behavior for this issue is as follows:

When a customer begins to checkout as guest by providing his email and signs in, only the content of the guest cart will be kept. Spartacus will create a new cart for the user and copy the content of the guest cart. The guest cart will subsequently be deleted. Therefore the user's cart will only contain the items that he started the guest checkout with.

A future improvement will come with the feature of Selective Cart (save for later). The items from the old user cart could be saved for later. This way they are removed from the cart but not lost. _To be discussed further._

**Comment by LTiger14** [comment]
Clarifications:
Guest to login from any of the checkout steps -> redirects to start of checkout.
From order confirmation... well you can't see it anymore because you don't have access so homepage.

**Comment by LTiger14** [comment]
### QA

1. Add products to cart
2. Start guest checkout
3. Do all the steps until billing form
4. Login
5. The cart should contain only the products that were in the guest cart & you should be redirected to the first shipping step

**note** https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4622

**Comment by giancorderoortiz** [comment]
I still see a “cart not found” error popping up. Is this intended?

**Comment by KateChuen** [comment]
Found an issue where the 2nd time that the user tries to checkout as guest, then logins, he's not redirected to the first step of checkout. created #4634
