### ISSUE TITLE
Refactor product carousel component to use CmsComponentData

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#401]
Note: This ticket is also master description ticket for all tickets in this group if tasks.

1. Inject CmsComponentData instead of extending AbstractCmsComponent

2. Try to leverage observables if possible + async pipe in templates:
  a) component data is exposed as an observable (data$ property od CmsComponentData) 
  b) using async pipe with ChangeDetectionStrategy.OnPush works without any additional calls to ChangeDetectorRef
  c) if you decide that you need to subscribe to observable, make sure to unsubscribe in ngOnDestroy

More info: see https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/storefrontlib/src/lib/occ/docs/cms-component-implementation.md

Some refactoring might be needed.

Acceptance criteria:
- No longer extends from AbstractCmsComponent
- Most of the time, no need to unsubscribe from data observable (want to use async pipe directly in the logic)
- Ideally have a constructor with only CmsComponentData

Can follow up with Stan, but team can do own peer review.

Testing: If it works as before, we're done.

**Comment by Pucek9** [comment]
Acceptance criterion referenced to get rid of subscriptions are passed in #884
QA done
