### ISSUE TITLE
Handle agent token expiry

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#4012]
Handle token expiry when agent calls an employee only endpoint.

When a request is made with an expired token, the agent is logged out and an error message displays that the session is expired.

The agent has to sign-in again if he needs to continue using the system.

---

Remove the csagent token header removal logic from the csagent interceptor:
https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/4cf88941c2b315ee44aebb19f1c06fbc7f1aeaa8#diff-1d1d12ebb3f3c06cd58b7813b2983b3b

Instead, do the removal in `auth-error.interceptor.ts` like we do for the client token header because the auth error hailing needs to know what kind of request it it dealing with: https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/core/src/auth/http-interceptors/auth-error.interceptor.ts#L36-L38

**Comment by giancorderoortiz** [comment]
How to qa?

**Comment by plabadie** [comment]
PR #4456

**Comment by giancorderoortiz** [comment]
I agree. The error message is displayed when the ASM agent token is expired. 

![Screen Shot 2019-09-18 at 12 09 36 PM](https://user-images.githubusercontent.com/46171897/65165705-51019900-da0d-11e9-8e1c-035582239330.png)

**Comment by giancorderoortiz** [comment]
Found a minor issue during testing: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4640
