### ISSUE TITLE
Replicate sonarqube quality profile into sonarCloud

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#403]
Until before moving to github, Spartacus was being analyzed with SonarQube Droid quality profile. Such rules need to be replicated in sonarcloud.

**Comment by hackergil** [comment]
Quality profiles have been created in sonarcloud and applied to spa.

**Comment by marlass** [comment]
These profiles look good. In the future, we could enable additional rules for even more strict check.
