### ISSUE TITLE
Introduce excludeKeys once again (after revert #3998)

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#4036]
Introduce exclude keys once again to spartacus.

It was reverted in https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4035

Note: do not change default config, so when users add `some_key` to synchronization it will work without disabling this key from `excludeKeys` config first.

**Comment by Zeyber** [comment]
Added auth storage keys to excludeKeys in default-config. User session was no longer preserved on refresh.

**Comment by marlass** [comment]
Docs are no longer needed as we replace storage sync with different mechanism.
