### ISSUE TITLE
registration form url encoding issue

### ISSUE THREAD

**Issue by edwin-denk** [SAP/cloud-commerce-spartacus-storefront#4038]
## Environment Details

- Spartacus:  1.0.2
- Browser: Chrome 
- OS: 75.0.3770.142
- Device: Macbook Pro 2015
- Other environment details: Angular 8.2.0

## Steps to Reproduce
Click on Register
Use email address with special character: like jon.doe+test123@gmail.com

## Observed Results

Form submit changes  "jon.doe+test123@gmail.com" to  "jon.doe test123@gmail.com"
Bad Credentials error message is shown

## Expected Results
registration should work as expected and create the account without an error

## Repository Used
installed from libs, as described in the installation guide

## Additional Information
![image](https://user-images.githubusercontent.com/54066245/62939787-55191600-bdd2-11e9-914d-918ff942e43f.png)

**Comment by hackergil** [comment]
Spartacus does not support email addresses with special characters, as established in RFC-5322

**Comment by meeque** [comment]
I don't think that a literal `+` sign is forbidden in email addresses. This seems to be more of a URL encoding issue, as originally indicated. 

It seems that we have similar problems with other API requests, see #4260.

**Comment by Xymmer** [comment]
closed as won't fix as it duplicates #4260

**Comment by meeque** [comment]
Are you sure that this is a duplicate? #4260 seems to be related to the login form, while this issue is related to the registration form!

Yes, a solution might look similar, but it will have to be implemented and tested separately for each individual case!
