### ISSUE TITLE
Graceful failure for cart calls

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#4043]
See comment: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1792#issuecomment-519247141

As mentioned in the comment above when certain calls to the cart fail, the site can enter an infinite loop. This is not a configurable endpoints issue but it can be reproduced using the feature as described in the comment above.

The storefront should fail gracefully if the calls return errors.

**Comment by LTiger14** [comment]
### For review/QA:

Execute steps from https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1792#issuecomment-519247141

**Comment by LTiger14** [comment]
### For QA:

1.Before starting, add the feature flag in app.module.ts as follows
```
features: {
 configurableOccEndpoints: true
}
```
2. Modify the endpoints and restart server

**Comment by giancorderoortiz** [comment]
Test successful. 
Infinite loop not seen. 🆗 
Cart fails within reason throughout. 🆗 
Test done on dev-19
