### ISSUE TITLE
In spacceleratoraddon, update existing nav component: remove unused nodes and pages

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#406]
In spacceleratoraddon, remove unused nodes and pages.
We're left with this for now, in this order:
- Orders
- Addresses
- Payment Methods
- Sign Out

There will be an 'account profile' home page that leads to modular functionality. We'll add back what we need. New pages will be added as needed when we do account profile topic.

![image](https://user-images.githubusercontent.com/4998145/48952341-ddd3e700-ef0f-11e8-8b36-609944ddb919.png)

**Comment by Xymmer** [comment]
can we control the order? would like to see:
* Orders
* Addresses
* Payment Methods
* Account Profile
* Sign Out

Don't want to see close account, email, etc.

**Comment by plabadie** [comment]
PR: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/14/overview

After initialization, the My Account menu should look like this:

<img width="368" alt="screen shot 2019-02-07 at 2 26 36 pm" src="https://user-images.githubusercontent.com/7065346/52437393-cce54b80-2ae4-11e9-993f-a3468de4f9b3.png">
