### ISSUE TITLE
[Phase 3] Complete Infinite Scroll Feature 

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#4069]
Add button configuration that will allow the user to press "show more" to retrieve more items instead of automatically retrieving them after a scroll operation.

**Comment by RadhepS** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4041

**Comment by RadhepS** [comment]
QA Steps:

Set the following in app.module.ts:
```
  pagination: {
        infiniteScroll: {
          active: false,
          showMoreButton: false,
          limit: 0,
        },
  }
```

Since active is false, default pagination will be used.

Pagination:
1. Navigate to a category page and look to see if it behaves as expected
2. Switch between pages
3. Toggle filters
4. Change sort
5. Use the product search for an item. Ex: "Canon".
6. Repeat steps 1-4.

Infinite Scroll:
1. Set active to true, showMoreButton to false, and limit to 0 in app.module.ts
2. Navigate to a category page
3. Scroll down the page and expect products to be appended to the list
4. Toggle filters - this should reset the list
5. Change sort - this should reset the list
6. Change view from list to grid or vice versa - this should reset the list
7. Scroll down the page until no more items are available - you should see a "Back to Top" button.
8. Use the product search for an item. Ex: "Canon".
9. Repeat steps 1-7.

Infinite Scroll with Limit:
1. Set active to true, showMoreButton to false, and limit to a value above 0
2. Navigate to a category page
3. Scroll down and expect to be able to scroll down until the number of products in the list is greater than or equal to the limit you set. - Expect "Back to Top" and "Show More" buttons to appear when this limit is reached.
4. Press "Show More" - another set of items should be appended
5. Toggle Filters - this should reset the list
6. Change sort - this should reset the list
7. Change view from list to grid or vice versa - this should reset the list
8. Scroll down the page until no more items are available - you should only see a "Back to Top" button.
9. Use the product search for an item. Ex: "Canon".
10. Repeat steps 1-8.

Infinite Scroll with Button:
1. Set active & showMoreButton to true in app.module.ts
2. Navigate to a category page
3. Scroll down the page and expect "Back to Top" and "Show More" buttons to appear
4. Press "Show More" - another set of items should be appended
5. Toggle Filters - this should reset the list
6. Change sort - this should reset the list
7. Change view from list to grid or vice versa - this should reset the list
8. Scroll down the page until no more items are available - you should only see a "Back to Top" button.
9. Use the product search for an item. Ex: "Canon".
10. Repeat steps 1-8.

**Comment by KateChuen** [comment]
Tested on dev3. 
All the scenarios described work well. 
Tried with different values for the productLimit. 
If limit<=10, then it retrieves 10 products at a time.
If limit=15, then it retrieves 20 products at a time. 


If ShowMoreButton is true, then it ignores the Limit value. It's always 10. 
The only very very minor issue found was that the cursor should be a 'hand' when the focus is on the "BACK TO TOP" & "SHOW MORE" buttons. (#4360 )
