### ISSUE TITLE
[retest] In product details page, click Shipping tab, there is console error

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#408]
![screen shot 2018-11-23 at 2 06 29 pm](https://user-images.githubusercontent.com/44440575/48957790-01eff200-ef29-11e8-8eef-5aa9c519fa88.png)

**Comment by Xymmer** [comment]
echeck if this is still happening, this is an old issue

**Comment by Xymmer** [comment]
no longer occurs, tested apr25 with dev17
