### ISSUE TITLE
Make it possible to change config at runtime

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4086]
In order to test the toggle feature, we would need to be able to provide any config at runtime. Therefore to achieve this, we need to do this:
- module in our app, that will read config from some json in index.html, or some JS file -> we will enable it in our test app

**Comment by Platonn** [comment]
QA steps:
- change the line 33 in file `product-details.e2e-spec.ts`
  from:
  ```typescript
    cy.visit('/product/266685');`
  ```
  to:
  ```typescript
    cy.cxConfig({
      routing: { routes: { product: { paths: ['test/:productCode'] } } },
    });
    cy.visit('/test/266685');
  ```
- verify that e2e tests for this test suite run against route `/test/266685` (so we changed configurable product route)
- verify that next test suite (line 43) is untouched - run against the normal route `/product/266685`
