### ISSUE TITLE
Refactor asm component to move to a new folder

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#4090]
At the moment the asm component is not a CMS component but it is in `storefrontlib/src/cms-components`. Issue #3909 should be done first to figure out if it should be a cms component.

This ticket is to find a place to put it. If it became a cms component it can stay where it is, if not, it might be necessary to create a new folder.

**Comment by plabadie** [comment]
PR #4313
