### ISSUE TITLE
Support partial migration of accelerator's routes

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#4106]
Many customers will migrate step-by-step (route-by-route) from accelerator to spartacus which means using different systems to drive parts of the storefronts at the same time at the same domain.
(See slack discussion https://spartacus-storefront.slack.com/archives/CCTA558AX/p1562059435105400 )

We would like to support having configurable routes with an option to escape from SPA and reload page to allow for backend-driven response (based on the URL patterns).

As long as we are in the scope of SPA, we perform only 'inside' navigations due to usage of Angular's `routerLink` which doesn't do full reload by design.

However we can define virtual `Route` with `Guard` that imperatively preforms a full reload for configured paths. 

### Support of redirects to other domain
*Note*: Some Customers may have Spartacus and Accelerator deployed on different domains. It's debatable whether we should support it by more sophiticated config or just by an extension point - because it can be considered an edge case. Nevertheless, for SEO, backend sholuld also perform http redirect from white-listed SPA routes to ACC in a different domain - for deep links and crawling bots.

### Cache
Need to ensure that browser cache or PWA won't break the full reload by serving SPA again.

**Comment by Platonn** [comment]
## QA steps
### Basic
1. set baseUrl to model T
2. import optional module `RoutingMigrationModule` from `@spartacus/core` in your shell app
3. provide config chunk (using `B2cStorefrontModule or ConfigModule):
```
  routing: {
    migration: {
          paths: ['', 'login/register', 'product/:productCode/:productName'],
          type: RoutingMigrationConfigType.INTERNAL,
        },
    }
  }
```
4. For easier testing (not to get into infinite loop of flickering page reload), deffer the page reload by extending `RoutingMigrationGuard`:
```typescript
@Injectable()
export class CustomRoutingMigrationGuard extends RoutingMigrationGuard {
  redirect(route, state) {
    setTimeout(() => {
      super.redirect(route, state);
    }, 5000);
  }
}
```
and providing it in your app module:
```typescript
 providers: [
    { provide: RoutingMigrationGuard, useClass: CustomRoutingMigrationGuard },
  ],
```
5. run application
6. verify that visiting above configured paths renders as usual
7. verify that visiting any other path results in the page reload (infinite loop of reloads occurs due to missing backend rules which would normally render different storefront based on URL patterns)

### Production with PWA and SSR
8. To verify that we perfrom 'hard' reload so the server can render the response (meaning it's not hijacked by PWA caching), please add dummy counter and console.log in the `server.ts` file:
![image](https://user-images.githubusercontent.com/4001059/63700901-22d0d500-c824-11e9-972c-a7f44d98db55.png)
9. (please ensure you use model T as baseUrl) and build libraries, shell app, SSR and run it:
```bash
yarn build:core:lib
yarn build
yarn build:ssr
yarn start:ssr
```
Repeat regular QA steps for SSR+PWA and verify page reloads are served by server (not service worker) by observing the incrementing numbers in the terminal of the SSR process.

**Comment by Platonn** [comment]
To bypass service worker for reloading of specific routes, one need to add property `navigationUrls` to the config file `ngsw-config.json`:
```json
"navigationUrls": [
    // angular defaults:
    "/**",
    "!/**/*.*",
    "!/**/*__*",
    "!/**/*__*/**",

    // custom exclusion rules
    // ! for exclusion
    // prefix `/*/*/*/` for site context like `/electronics-spa/en/USD/`
    "!/*/*/*/"
    "!/*/*/*/login/register",
    "!/*/*/*/product/*/*",
  ]
```
See Angular docs: https://angular.io/guide/service-worker-config#matching-navigation-request-urls.

TODO: add here inclusive config

**Comment by Pucek9** [comment]
Worked as in QA steps ✔
