### ISSUE TITLE
Site context / routing issue

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#4149]
when you go to url like `/contextParam1/contextParam2/?any=thing` - it redirects to `/contextParam1/contextParam2/contextParam2?any=thing`

**Comment by dunqan** [comment]
QA steps:
- open url `/electronics-spa/en/USD/?test=param` and check if homepage loads correctly
Also it could work for all the following urls:
- `/electronics-spa/en/USD?test=param`
- `/electronics-spa/en/USD#fragment`
- `/electronics-spa/en/USD/#fragment`
- `/electronics-spa/en/USD?test=param#fragment`
- `/electronics-spa/en/USD/?test=param#fragment`

**Comment by Matejk00** [comment]
QA done, all following url's works properly.
