### ISSUE TITLE
Add typesafety to Storefinder module [after 151]

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#415]
Do this one after #151.

Typesafety should be added wherever possible. A few suggestions where type safety should be added:

* method parameters
* method return values
* if there's no return value for method (it's void), add `void` as the return to make it more specific
* test files
* object literals
* if you need OCC types, take a look at #301's PR

The goal is to have a completely type safety code.

**Comment by Xymmer** [comment]
Nik is main contact and possible reviewer

**Comment by Matejk00** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/956

**Comment by Matejk00** [comment]
Most of typesafety issues have been resolved during #151. Nevertheless i added missing types and comments for methods in facade.
