### ISSUE TITLE
Guest checkout shipping address population

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#4152]
After #1180, during the checkout process as guest once a user enters his shipping information he can proceed forward. The issue is if he goes back to the shipping address page using the back button or the checkout steps navigation the form is empty.

Looking at the accelerator, if a user follows the steps above he will see an address book option with the address that he entered. Spartacus should have a similar behaviour if an address was already entered.

**Comment by WeizhengSap** [comment]
There is no way to retrieve guest's addresses. We need add one OCC API to `getSupportedDeliveryAddresses`, which can retrieve addresses from cart's user.

**Comment by WeizhengSap** [comment]
The workaround is: when back to "shipping address", the `shipping address form` was populated with the value user just input.

**Comment by giancorderoortiz** [comment]
Good for usability (specially mobile)
Issue fixed 🆗
