### ISSUE TITLE
Hide login/register links in header

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#4155]
In some cases, we need hide login/register links in header. For example, during checkout steps, users should not be able to login/register.

![Screen Shot 2019-08-21 at 1 51 44 PM](https://user-images.githubusercontent.com/44440575/63464314-fd5f5800-c42c-11e9-9f93-4350920ca1df.png)

**Comment by giancorderoortiz** [comment]
This means exactly same behaviour as old accelerator, correct?

**Comment by Xymmer** [comment]
this is actually a separate feature parity task, closing

**Comment by marlass** [comment]
This ticket should only hide login/register links?
Right now as a logged user I lost access to My Account links. Is it intended?

**Comment by WeizhengSap** [comment]
It should not hide "my account" link. I will fix it.

**Comment by WeizhengSap** [comment]
actually, I check the legacy storefront. During checkout, the "my account" link is hidden.
![Screen Shot 2019-09-23 at 8 19 30 AM](https://user-images.githubusercontent.com/44440575/65425015-00a68480-dddb-11e9-9e75-0712ee27cb50.png)

**Comment by Xymmer** [comment]
That's a configurable option in Accelerator, let's not do this for now.
Same header all the time during checkout, at the moment.
