### ISSUE TITLE
Create tickets for focused elements not providing visual feedback

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#4170]
Check each one of these app sections that all focusable elements provide visual feedback so that the user can visually see where they have navigated via focus in the app. Tick checked sections once all appropriate elements provide this feedback in each corresponding section.

**Checklist**
- [x] Header (Desktop) 
	- #4148 Need to fix and close
	- #4146 Need to fix and close
- [x] Header (Mobile)
- [x] Footer
- [x] Home
- [x] Sign In
- [x] Reset Password
- [x] Register
- [x] Product
	- [x] View Product
	- [x] Product List
	- [x] Add to cart
- [x] Cart
- [x] Checkout
	- [x] Shipping Address
		- [x] Choose Shipping Address
		- [x] Add New Address
	- [x] Delivery Mode
	- [x] Payment Details
		- [x] Choose Payment Method
		- [x] Add New Payment
	- [x] Review Order
	- [x] Order Confirmation
- [x] My Account
	- [x] Order History
	- [x] Address Book
		- [x] Addresses
		- [x] Add New Address
		- [x] Edit Address
	- [x] Payment Details
	- [x] Personal Details
	- [x] Change Password
	- [x] Email Address
	- [x] Consent Management
	- [x] Close Account
- [x] Miscellaneous/General
	- #2216 Need to fix and close
	- #3777 Need to fix and close
_Note: Remove pages coming from cms from this list_

**Comment by developpeurweb** [comment]
All ticket have been created
