### ISSUE TITLE
check if site context links and header links are configured improperly for apparel (dev-15)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#4171]

**Comment by mirkosoft** [comment]
Site Context controls are not present in the header as for the apparel-uk base store there is only one language and one currency defined. After adding more (Base Commerce->Base Store->apparel-uk) items respectively menu appears:
![image](https://user-images.githubusercontent.com/788092/65584796-bdd2e100-df81-11e9-93af-500c951139fb.png)
![image](https://user-images.githubusercontent.com/788092/65584822-c9260c80-df81-11e9-81a9-75c9e70f3268.png)
@Xymmer - it needs decision, seems reasonable for me as it's apparel-**uk** not the apparel global (like electronics).

**Comment by mirkosoft** [comment]
Site links "Sale" and "Help" has missing labels in the BE.
"Find a Store" is disabled as it was disabled until StoreFinder has been released.

All above are already fixed in the feature branch for sampledataaddon for apparel-uk (impex).

**Comment by mirkosoft** [comment]
closing as checked and fixed with impex.
