### ISSUE TITLE
Need to deploy the Spartacus in docker. Environment Details Spartacus: Version - 2 Browser: Chrome OS: Centos Device: Widescreen  Other environment details:-Hybris 1905 Patch -1  

### ISSUE THREAD

**Issue by ShrutikaL** [SAP/cloud-commerce-spartacus-storefront#4196]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  
- Browser: 
- OS: 
- Device: 
- Other environment details:

**Comment by Xymmer** [comment]
please ask this question in our slack channel
https://join.slack.com/t/spartacus-storefront/shared_invite/enQtNDM1OTI3OTMwNjU5LTRiNTFkMDJlZjRmYTBlY2QzZTM3YWNlYzJkYmEwZDY2MjM0MmIyYzdhYmQwZDMwZjg2YTAwOGFjNDBhZDYyNzE
