### ISSUE TITLE
Change y- prefixes to cx- in code

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#42]
- Change y- prefixes to cx- in component selectors in .ts and in .html.
- Update tslint rule to remove y-.
- Run automated tests after.

Separate ticket for styling: #43.

Previous internal ticket: SPA-1218
Main selector was changed in: SPA-1219

**Comment by RomeroDiver** [comment]
What about prefixes in css classes? I think we should remove those as well

**Comment by kacperknapik** [comment]
If there are any `y-` prefixes left, we have #43 FYI
