### ISSUE TITLE
Errors in documentation for SSR configure from libraries

### ISSUE THREAD

**Issue by franciszekb** [SAP/cloud-commerce-spartacus-storefront#4222]
## Environment Details
- Spartacus:  ~1.0.0
- Browser: Chrome 75

## Steps to Reproduce
1. Configure SSR for Sparatcus from libraries according to documentation: https://sap.github.io/cloud-commerce-spartacus-storefront-docs/server-side-rendering-in-spartacus/
2.  Build and run nodejs server: `npm run build:ssr && npm run serve:ssr`
3. Open homepage

## Observed Results

1. Error during build: `npm run build:ssr`
`ERROR in ./server.ts
Module not found: Error: Can't resolve '@nguniversal/module-map-ngfactory-loader' in '../spartacus-1-0-2/spa-ssr'
 @ ./server.ts 20:0-76 23:16-32`

Module is imported in `server.ts`.

2. Transfer state doesn't work.
![Screen Shot 2019-08-23 at 12 07 38](https://user-images.githubusercontent.com/1172073/63585228-f2c4d000-c59e-11e9-947f-f1aeda235a84.png)

## Expected Results
1. Build is successful

2. State is transferred and there are no additional XHR calls 

## Solution
1. In package.json add dependency to ` "@nguniversal/module-map-ngfactory-loader": "^7.1.1"`

2. In `app.module.ts` add:
- `import { BrowserModule, BrowserTransferStateModule } from '@angular/platform-browser';`
- `BrowserTransferStateModule,`

**Comment by gladius-mtl** [comment]
Closed with https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/issues/319
