### ISSUE TITLE
Test release 1.1.0

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#4270]
- [x] Run all the E2E tests on the nightly branch on jenkins:
Note: Make sure that ALL the tests are being run (about 51 tests).
OR run them from your computer, pointing to dev17 server.

Additionally, do a quick smoke test (equivalent to the big happy path test) on:

- [x] Safari
- [x] Firefox

- [x] Check published packages

**Comment by kacperknapik** [comment]
safari done
