### ISSUE TITLE
Make maintenance branches protected

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#4303]
To avoid changes that breaks our standards/tests maintenance branches `release/*.x` protected.

Making them protected would also make it impossible to merge  (normal merge, not squash) release branches after release (normal merge would be better because git tags would be still working correctly).

Combination of protected branches and option to merge normally (squash should still be the default) should help us with maintenance of those branches.

**Comment by hackergil** [comment]
Branches made protected. Requiring all status checks before merging (except for code review/approval)
