### ISSUE TITLE
Test QA Express Checkout

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#4305]
1 checkout to `feature/express-checkout-fr1`
2 add to app.module config
```
checkout: { express: true },
```
3 check the positive scenario: 
- when we have at least 1 address in the address book and 1 payment, after click proceed to checkout, we should see review summary

4 check the negative scenario:
- the flag is not set or set to false
- we don't have address or payment method 
then we should be redirected to 1st step in the checkout

5 Additional things:
- we can also change (app.module config) preferred delivery modes. 
```
defaultDeliveryMode: [<values>],
```
It's an array with possible values:
```
DeliveryModePreferences.FREE,
DeliveryModePreferences.LEAST_EXPENSIVE,
DeliveryModePreferences.MOST_EXPENSIVE,
<code>,
```
It is prioritized in order, will use the first matched option.
Verify the behavior of set default delivery mode while express checkout

**Comment by KateChuen** [comment]
- [ ]  we don't have address or payment method, then we should be redirected to 1st step in the checkout

- [ ] we have 1 address in the address book and no payment saved, then we should be redirected to 1st step in the checkout

- [ ] we have no address in the address book and 1 payment saved, then we should be redirected to 1st step in the checkout

- [ ] we have 1 address in the address book and 1 payment, after click proceed to checkout, we should see review summary

- [ ] we have >1 address in the address book and >1 payment saved, after click proceed to checkout, we should see review summary

- [ ] the flag is not set or set to false, then we should be redirected to 1st step in the checkout

delivery modes set to: 
- [ ] Not set
- [ ] DeliveryModePreferences.FREE,
- [ ] DeliveryModePreferences.LEAST_EXPENSIVE,
- [ ] DeliveryModePreferences.MOST_EXPENSIVE,
