### ISSUE TITLE
"Action Link" style needs to be finished and accessible

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#4340]
So far detected, we only have a couple of **Action Links** as per screenshot below, both version differ in style and accessibility level. Therefore, a standard style needs to be applied.

![Screen Shot 2019-08-29 at 9 36 28 PM](https://user-images.githubusercontent.com/15113219/63987339-c67ce800-caa5-11e9-93a0-3214a229ee90.png)

![Screen Shot 2019-08-29 at 9 35 17 PM](https://user-images.githubusercontent.com/15113219/63987334-c250ca80-caa5-11e9-9922-64aeae2db01e.png)

Below is the original style provided in the initial theme specification for Action Links.

![Screen Shot 2019-08-29 at 9 37 28 PM](https://user-images.githubusercontent.com/15113219/63987404-080d9300-caa6-11e9-857f-2934d0c06868.png)

**Comment by kacperknapik** [comment]
Already fixed in `epic/accessibility`
