### ISSUE TITLE
Handle Customer Emulation Token Expiry

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#4385]
Handle an expiring token while a customer emulation is in progress.

**Comment by plabadie** [comment]
PR #4404

Note: The effect unit test was silently failing to begin with: bug ticket created:




On the develop branch, the refresh token does not work.  When the token expires, Spartacus should refresh the token, but in my tests, the server returns this response to the refresh token request:

{
  "error" : "invalid_grant",
  "error_description" : "Invalid refresh token: 80fef7cc-c241-40ff-bb8c-bc0005b17a40"
}

There is a bug ticket for that.

Therefore, when the customer session expires ( either a real customer session or a customer emulation session ), the user will be signed out of the storefront and the login page is displayed.

Expected result if the refresh token would work:
The customer emulation session continues seamlessly with the refresh token.  The refresh token carries the same customerId as the expired token before it.

**Comment by giancorderoortiz** [comment]
Refresh token working as expected. 🆗
