### ISSUE TITLE
Update Spartacus setup instructions for 1811

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#44]
When we moved Spartacus to open source, we concentrated on 1808.

The instructions are similar but not the same for 1811, so would be good to make a copy and label them 1808 and 1811 respectively.

Some things I know so far:
- We're still telling people to download the spaccelerator impex.
- Fixes were done in 1811 that solve the issues of checkout, so those parts should be removed.
- Would be good to retest the instructions on 1811 and remove anything else that might not be needed, that was special for 1808. Good to involve interns again.

**Comment by MitchellScottSandre** [comment]
I'm assuming you mean these instructions.. https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/setupandinstallation.md

**Comment by MitchellScottSandre** [comment]
Can't find any instances of `SAP Commerce 1811` available for download on the SAP Downloads page. https://support.sap.com/en/my-support/software-downloads.html

**Comment by Jim-Yang** [comment]
@spartacus/core is missing after adding 

```
$ yarn add @spartacus/styles
$ yarn add @spartacus/storefront
```

**Comment by Jim-Yang** [comment]
Questions: 

Checkout issue being described in setup document still exists it seems.

![image](https://user-images.githubusercontent.com/9470994/49544720-92bfb980-f8a9-11e8-80be-3ff9ca1f5348.png)

The build.gradle file included in the setup document does not work, using that recipe says that the tdd tests does not exist.

**Comment by Xymmer** [comment]
latest RC for 1811 is https://repository.hybris.com/hybris-release/de/hybris/platform/suite/commerce-suite/1903.0.27081/

but it's about to be release to sap download

**Comment by Xymmer** [comment]
For doc, let's keep an archive of instructions for previous commerce suite releases.
So current instructions are renamed 1808- maybe, or in a subfolder, whatever.

**Comment by Jim-Yang** [comment]
PR: GH-689

**Comment by MitchellScottSandre** [comment]
Get dozens of errors similar to `ERROR in /Users/i500566/c/test/AppleStore/node_modules/@spartacus/storefront/lib/store-finder/store/reducers/index.d.ts (8,32): Generic type 'ActionReducerMap' requires 3 type argument(s).`

And get hundreds of errors similar to `ERROR in /Users/i500566/c/test/AppleStore/node_modules/@spartacus/core/src/occ-models/occ.models.d.ts (3602,15): In ambient enum declarations member initializer must be constant expression.`

**Comment by Jim-Yang** [comment]
Just retried the instructions and it works fine for me ☹️

**Comment by Xymmer** [comment]
Comments from Bill:
- duplicate existing instructions and rename "setupandinstallation.md_1808" (let's keep all setup instructions for each cs release but add a note saying it's no longer being updated with latest spartacus)
- current "setupandinstallation.md" should always reflect latest cs release, but it should mention in the doc what release it is for
- I'm trying out the 1811 setup instructions and will write any comments here for matt

**Comment by Xymmer** [comment]
@gladius-mtl 
sent you a word file with my comments.
