### ISSUE TITLE
titleCode does not exist on get addresses response

### ISSUE THREAD

**Issue by Matejk00** [SAP/cloud-commerce-spartacus-storefront#440]
While working on #67 i noticed that during GET user/addresses request information about titleCode (Mr., Ms., Rev., etc...) is missing. Object does not exists on endpoint response.

In checkout when user is adding new address this value is required.

Would be good if titleCode will be also available in address details object.

**Comment by Xymmer** [comment]
for now we're goingto hard code a title code, so we can finish those pages.
There's a ticket to make titlecode not mandatory RAY-74 which would allow us to not show titlecodes at all (which was the goal).
but eventually we'd still need to get it as we're supposed to support it. so i'll follow up on that.

**Comment by Xymmer** [comment]
update: RAY-74 was put on hold while waiting for a milestone, i've asked for it to get back on track

**Comment by Xymmer** [comment]
Stingrays ticket closed Feb 22. Just have to check if dev17 has this (not sure when it was added to csp).

**Comment by Xymmer** [comment]
Not sure the status of the frontend... check if this is still a problem, close if not, fix if so.

**Comment by mirkosoft** [comment]
closing this as outdated. Currently address detail object in the response contains title: 
![image](https://user-images.githubusercontent.com/788092/58546210-2e046c80-8205-11e9-9ddf-319a8e3bd768.png)
Also for new address there is endpoint just for getting all possible title values.
