### ISSUE TITLE
Effects unit test silently failing

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#4405]
There is an effects unit test silently failing.

The problem is with this test: "_should refresh a user token_":
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/core/src/auth/store/effects/user-token.effect.spec.ts#L72-L82 

It is a short test and a rather simple effect.  In the effect, the token returned via the success action will inevitably have a userId attribute set to `current`.
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/core/src/auth/store/effects/user-token.effect.ts#L51

However, in the tests we asses the success with what seems to be a token with the userId set to 'xxx'.  The customerId will always be `current` and the test should fail otherwise (but it doesn't ).  

 It seems there is a flaw with this test that does not run the logic that is supposed to be tested.

**Comment by hackergil** [comment]
@plabadie Looking at your comments, how can this test be wrong if "current" is never returned nor set as part of the current test? All of the dependencies for the effect are mocked, and the effect doesn’t change the customerId.

Thoughts?

**Comment by plabadie** [comment]
It was more obvious when the effect returned a constant for the value of userId.
See:
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/29ae1d21123f46b9297923e0fa443a18c2fe9d89/projects/core/src/auth/store/effects/user-token.effect.ts#L51

Since it is determined that the userId is always "current" in the effect result, it seemed impossible that the test would pass when comparing the result to a test token with the userId value of 'xxx'

https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/29ae1d21123f46b9297923e0fa443a18c2fe9d89/projects/core/src/auth/store/effects/user-token.effect.spec.ts#L78

https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/29ae1d21123f46b9297923e0fa443a18c2fe9d89/projects/core/src/auth/store/effects/user-token.effect.spec.ts#L16

This led me to think there was an excess of mocking and that the effect function was not called.
