### ISSUE TITLE
fix warnings while build

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#4418]

**Comment by Pucek9** [comment]
since https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/2826
```
'Observable' is imported from external module 'rxjs' but never used
'FormGroup' is imported from external module '@angular/forms' but never used
```

**Comment by Platonn** [comment]
#### :white_check_mark: core
```
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@spartacus/core'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built @spartacus/core
```
---
#### :warning: storefront
```
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@spartacus/storefront'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
WARNING: 'Observable' is imported from external module 'rxjs' but never used
WARNING: 'FormGroup' is imported from external module '@angular/forms' but never used
Bundling to FESM5
WARNING: 'Observable' is imported from external module 'rxjs' but never used
WARNING: 'FormGroup' is imported from external module '@angular/forms' but never used
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built @spartacus/storefront
```

Those 2 warnings still present:
```
WARNING: 'Observable' is imported from external module 'rxjs' but never used
WARNING: 'FormGroup' is imported from external module '@angular/forms' but never used
```

**Comment by Pucek9** [comment]
> #### ✅ core
> ```
> Building Angular Package
> 
> ------------------------------------------------------------------------------
> Building entry point '@spartacus/core'
> ------------------------------------------------------------------------------
> Compiling TypeScript sources through ngc
> Bundling to FESM2015
> Bundling to FESM5
> Bundling to UMD
> Minifying UMD bundle
> Copying declaration files
> Writing package metadata
> Built @spartacus/core
> ```
> 
> #### ⚠️ storefront
> ```
> Building Angular Package
> 
> ------------------------------------------------------------------------------
> Building entry point '@spartacus/storefront'
> ------------------------------------------------------------------------------
> Compiling TypeScript sources through ngc
> Bundling to FESM2015
> WARNING: 'Observable' is imported from external module 'rxjs' but never used
> WARNING: 'FormGroup' is imported from external module '@angular/forms' but never used
> Bundling to FESM5
> WARNING: 'Observable' is imported from external module 'rxjs' but never used
> WARNING: 'FormGroup' is imported from external module '@angular/forms' but never used
> Bundling to UMD
> Minifying UMD bundle
> Copying declaration files
> Writing package metadata
> Built @spartacus/storefront
> ```
> 
> Those 2 warnings still present:
> 
> ```
> WARNING: 'Observable' is imported from external module 'rxjs' but never used
> WARNING: 'FormGroup' is imported from external module '@angular/forms' but never used
> ```

Yep, we were not able to fix that now.
