### ISSUE TITLE
Qualtrics Integration [master]

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#4423]
Integrate Qualtrics into Spartacus, and make sure it is configurable for the user

**Comment by giancorderoortiz** [comment]
Is there a separate board for this?
Where is work detailed?

**Comment by bgambocjaviniar** [comment]
> Is there a separate board for this?
> Where is work detailed?

1- yes, it is in the projects directory/page 
2- work detailed as in what tickets it needs to be done? If yes, it is in its own board. Small feature that can be done, but other tickets/features were priority, such as finishing infinitescroll e2e / fix e2e tests, helping out code reviewing guestcheckout / configurable endpoints (which is done), etc. All I can say from what I did so far for this ticket is that we have a seamless integration, but I still need to create a injection for customers to be able to enable qualtrics on pages they want. But other than that, everything is done in the qualtrics side as in having it always enabled.

**Comment by Xymmer** [comment]
Qualtrics integration done, no longer needed
