### ISSUE TITLE
Make qualtrics configurable for the user

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#4424]
Create flags to enable qualtrics

**Comment by bgambocjaviniar** [comment]
PR: GH-4848

**Comment by bgambocjaviniar** [comment]
QA:

before testing
- To enable Qualtrics, you need to insert a FlexComponent Type named QualtricsComponent to a slot. The slot must exists as long as the page exist. For example, in the pdp page, I already put a QualtricsComponent in the UpSellingSlot, because UpSellingSlot will only exist in that page. Another example is to put it in the plp page, you can place the Cms Component in a slot like RefinementFacetComponentSlot because it is unique to that page.
- Conclusion for above is that, you need to apply the cms component to a page in a unique slot pertaining to that page. 

- test on dev-12 (already deployed)


testing: 
- Go to any pdp page, and qualtrics will be enabled and show the survey (To enable the integration of Qualtrics)
- test Qualtrics features? Maybe? But I don't think we need to since the customers will set it up, however, I will send you the credentials on qualtrics portal to test the different options for displaying the survey

**Comment by bgambocjaviniar** [comment]
Additional information: 
-- test locally

- change branch to feature/GH-4848-for-server
- remove configs and make sure all works as usual without qualtrics being called

**Comment by KateChuen** [comment]
Tested on dev12 on pdp and with the extended service when cart has 1 entry. 
The survey is being displayed when need be, and it's recording the responses. 
Only thing to note is that we need to document the fact that the app needs to be started with SSL for qualtrics to work on safari if we're using a server.
Also ran a smoke test without the qualtrics feature. Also ok.
