### ISSUE TITLE
Host compodocs on github pages

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#4446]
A request came from the community to host the output of compodocs somewhere public. Having an overview of all available modules/services (e.g. CurrentProductService) without having to search through the code is great and could help in general to get a better overview of the whole architecture

Let's host it in our github pages for spa.

+ just publish every release (automate? up to Louis) (make sure this is in our list of release steps)

**Comment by LTiger14** [comment]
To see the final result, you can look at :
- https://github.com/LTiger14/cloud-commerce-spartacus-storefront/tree/gh-pages
&
- https://ltiger14.github.io/cloud-commerce-spartacus-storefront/index.html

**Comment by LTiger14** [comment]
### PR 
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4847
