### ISSUE TITLE
Keyboard up and down arrow keys to select the product in search field, does't work.

### ISSUE THREAD

**Issue by vinodkumarsingh208** [SAP/cloud-commerce-spartacus-storefront#4448]
When I use Keyboard up and down arrow keys to select the product in search field, it does't work. Is this feature available in Spartacus. Please see the difference on Accelerator and Spartacus storefront during selection of products.

![Screenshot 2019-09-05 at 11 13 52 AM](https://user-images.githubusercontent.com/7273535/64348354-55818700-cff5-11e9-84d6-1dab80afdc1b.png)
![Screenshot 2019-09-05 at 11 14 39 AM](https://user-images.githubusercontent.com/7273535/64348355-55818700-cff5-11e9-9b95-8dd0f028d1f2.png)

**Comment by Zeyber** [comment]
This was implemented in #3028. You need to import optional parameter `WindowRef` into the searchbox component constructor in order to enable the navigation functionality. The functionality will be permanent with the next major release.
