### ISSUE TITLE
Styling for guest register form

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#4449]
In #1178 a form was added to the order confirmation page that allows a guest user to supply only a password to create an actual user.

At the moment the form is not styled. It should be styled to reflect the UI mocks (minus the fancy form validation). Be careful about breaking changes. The form's HTML might have to change to prevent breaking changes to the CSS.

**Comment by giancorderoortiz** [comment]
Adding some images - pre-styling. 

![Screen Shot 2019-09-05 at 2 08 40 PM](https://user-images.githubusercontent.com/46171897/64368067-878bec80-cfe7-11e9-8509-a35c9b95e427.png)
![Screen Shot 2019-09-05 at 2 09 16 PM](https://user-images.githubusercontent.com/46171897/64368068-878bec80-cfe7-11e9-85d3-7623ef04af45.png)
![Screen Shot 2019-09-05 at 2 09 29 PM](https://user-images.githubusercontent.com/46171897/64368069-878bec80-cfe7-11e9-880c-065e4495993d.png)

**Comment by giancorderoortiz** [comment]
Images after styling: 

![Screen Shot 2019-09-17 at 7 07 01 PM](https://user-images.githubusercontent.com/46171897/65086117-962aba00-d97e-11e9-9898-92127b3c26ab.png)
![Screen Shot 2019-09-17 at 7 07 27 PM](https://user-images.githubusercontent.com/46171897/65086118-96c35080-d97e-11e9-9e5c-803898980d5f.png)
![Screen Shot 2019-09-17 at 7 07 49 PM](https://user-images.githubusercontent.com/46171897/65086119-96c35080-d97e-11e9-9e8c-7f589dac3a74.png)
