### ISSUE TITLE
The message of another type causes that messages not disappear

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4469]
**Environment Details**
Spartacus: feature/express-checkout-fr1 branch
Browser: chrome
Device: mac
Happens on: http://dev-com-21.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
- Enable express checkout
- Login.
- Place an order (with 1 saved address and 1 saved payment)
- Now go to MyAccount -> Address Book
- Delete the address
- Add a product to cart, proceed to checkout
- Add and save an address and place the order

**Actual Result**
the "address deleted successfully" message doesn't disappear, even after 8-10s. 

**Expected Result**
The message should disappear. Can't remember if it's configured to be 8 or 10 seconds. Unless this has been changed?

![Screen Shot 2019-09-06 at 9 25 25 AM](https://user-images.githubusercontent.com/45409515/64431630-d342a280-d088-11e9-9b54-b8d690efe1b6.png)

Sometimes we get a "Cart Not Found" error right after, and it doesn't disappear. So looks like the last message displayed is the one that doesn't go away.

**Comment by KateChuen** [comment]
error msg: 7s
confirmation msg 3s

**Comment by KateChuen** [comment]
Michal tried to reproduce it on develop branch. 
With this scenario: 
"yeah, then we can select delivery mode and got error Delivery Mode [standard-gross] is not supported for the current cart . this error will not disappear. refreshing page repair problems with not disappearing GMs"

But it's not related to EC.

**Comment by Pucek9** [comment]
The easiest way to reproduce that bug is to:
1 try login with bad credentials(error "Bad credentials. Please login again."), then register a new account - "Please log in with provided credentials." will not disappear
2 Or do same in reverse order

If we generate 2 successful messages (eg. in Consent Management) they are going to disappear, same with 2+ error messages (refresh is important).

**Conclusions**
 The problem occurs if we display messages different type than before

**Comment by Pucek9** [comment]
Local QA steps:

add that e.g in breadcrumb.component
```
<button (click)="addConfirmation()">addConfirmation</button>
<button (click)="addError()">addError</button>
<button (click)="addInfo()">addInfo</button>

  addConfirmation() {
    this.globalMessageService.add(
      'msg_' + this.counter++,
      GlobalMessageType.MSG_TYPE_CONFIRMATION
    );
  }
  addError() {
    this.globalMessageService.add(
      'msg_' + this.counter++,
      GlobalMessageType.MSG_TYPE_ERROR
    );
  }
  addInfo() {
    this.globalMessageService.add(
      'msg_' + this.counter++,
      GlobalMessageType.MSG_TYPE_INFO
    );
  }
```
and click x times for every button.
Messages should disappear in the same order, with delay specified in config - every delay starts when the previous message disappears.

**Comment by Zeyber** [comment]
Confirmed messages appearing and disappearing in numerical order
