### ISSUE TITLE
Price of delivery method isn't updated during checkout

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4472]
**Environment Details**
Spartacus: feature/express-checkout-fr1 branch
Browser: chrome
Device: mac
Happens on: http://dev-com-21.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
- Enable express checkout
- Login.
- Have 1 saved USA address, and 1 saved CANADIAN address.
- Set the USA address as default.
- Have 1 saved payment.
- Add product to cart
- Click on "Proceed to checkout"
- Now click on the 1st step to checkout and select the CANADIAN address instead.
- Click Next

**Actual Result**
It now goes to the Payment cards page. But the price of the delivery method hasn't changed.
![Screen Shot 2019-09-06 at 9 46 08 AM](https://user-images.githubusercontent.com/45409515/64433069-c2dff700-d08b-11e9-8b8e-0913a102eb84.png)
  
However, if you go ahead and place the order, then you'll see the price of the delivery method changed. 
![Screen Shot 2019-09-06 at 9 48 35 AM](https://user-images.githubusercontent.com/45409515/64433078-c6737e00-d08b-11e9-8778-94b83131b100.png)

**Expected Result**
The price of the delivery method should be updated during the checkout steps.

**Comment by Pucek9** [comment]
After verification similar scenario on dev-17, that issue is not related to Express Checkout

**Comment by KateChuen** [comment]
Tested on dev10. It's fixed now. The Shipping cost resets to TBD after step1 of checkout, until we re-select the shipping method, then it gets reflected in the shipping cost.
