### ISSUE TITLE
Product Details E2E tests / SPA-1026

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#45]
- Test adding different quantities. (1,2,3) and assess that there is a correct number difference on the minicart.

- Test the different operations the user can do from the add to cart modal
-- change qty
-- close
-- view cart
-- procede to checkout

- Asses that the following are as expected:
-- title.
-- ID
-- Price
-- Short desc
-- stock level
-- pictures
-- Tabs have the expected content:
--- Product details
--- Specs
--- Shipping
--- Reviews
---- Assess that we can submit a review without an error (and ideally asses that the review displays. May depend on the default backend settings, reviews need to be approved in backoffice before thay are displayed )

**Comment by kacperknapik** [comment]
I can't test if this one works, because e2e are failing atm. Let's wait for e2e to work again

**Comment by marlass** [comment]
Things listed in the description are checked in E2E tests. All tests pass.
