### ISSUE TITLE
Enable frontend asm in spartacus installation script ( ci + dev servers )

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#4512]
Enable frontend asm in spartacus installation script ( ci + dev servers )

**Comment by plabadie** [comment]
For smoke test: dev2 was deployed using this script.  If the asm ui shows up, its a success.

**Comment by giancorderoortiz** [comment]
Is the feature on or off by default?

**Comment by plabadie** [comment]
> Is the feature on or off by default?

On.
