### ISSUE TITLE
Prepare powertools-spa sample data

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#4519]

**Comment by giancorderoortiz** [comment]
@Xymmer  master ticket and separate board not required?

**Comment by WeizhengSap** [comment]
Sample data PR is here: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/13

**Comment by WeizhengSap** [comment]
Getting user's order details (use api: /users/{userId}/orders/{code}) does not check order expired or not. Only get guest's order (use api: /orders/{code}) checks order expiration. 

Now, we use api: /users/{userId}/orders/{code}, because getting guest's order need "ROLE_TRUSTED_CLIENT".

**Comment by WeizhengSap** [comment]
To start powertools (https://localhost:4200/powertools-spa/en/USD/), go to branch: feature/GH-4519.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-10-04 at 12 44 10 PM](https://user-images.githubusercontent.com/46171897/66225128-abedee00-e6a5-11e9-88b1-db39b482fce7.png)
![Screen Shot 2019-10-04 at 12 46 55 PM](https://user-images.githubusercontent.com/46171897/66225129-abedee00-e6a5-11e9-9bf1-c4a90e8375a8.png)

**Comment by giancorderoortiz** [comment]
It's a go... ✅
