### ISSUE TITLE
Guest login page should not be accessible if user in cart

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#4548]
### Steps to reproduce

1. As anonymous, add product to cart
2. Proceed to checkout, select guest checkout
3. Enter email and proceed
4. Press the browser back button
5. You go back to the add email page
6. You cannot actually change the email

### Intended behavior

The add email page should redirect if there is a user in the cart.

**Comment by bgambocjaviniar** [comment]
Sorry, I took the wrong ticket, but I was on GH-4458

**Comment by giancorderoortiz** [comment]
I see a fix. 
After going back in browser, anonymous user is redirected to cart
