### ISSUE TITLE
Doc improvement: Need to set CORS filter when deploying for Spartacus

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#455]
In the setup guides that if you are to deploy spartacus anywhere you need to change the following property in your Hybris build:
`corsfilter.ycommercewebservices.allowedOrigins=http://localhost:4200 https://localhost:4200`

Otherwise none of your CORS requests will work outside of the development server.

**Comment by maazahmed12** [comment]
Hi! the property was already set in ycommercewebservices/project.properties but it is still giving the same CORS error

**Comment by joezhuojiang** [comment]
hey, 
I have a question here, if Hybris occ is deployed in public cloud (AWS) and I want to use that from my local dev machine. what is the property value  I need to replace  in corsfilter.ycommercewebservices.allowedOrigins

from my local, I am also accessing spartacus frontend via http://localhost:4200/
shall I put http://myip:4200 https://myip:4200 in that property ? 

the benefit is that as frontend developer , we don't even need to install Hybris 1808 locally for development.

**Comment by marlass** [comment]
If you use `localhost:4200` to access your public server it should still be set to `localhost:4200`. If you would set it to `myip:4200` you would then need to access it in your browser with `myip:4200`. 

CORS is a browser mechanism. It only checks if the response from cross domain server specifies `Access-Control-Allow-Origin` header with a value that is equal to your current location (domain part).

This article may help with understanding how CORS work: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by gladius-mtl** [comment]
Added a link in https://github.com/SAP/cloud-commerce-spartacus-storefront/wiki/Installing-SAP-Commerce-Cloud to point to https://help.hybris.com/1811/hcd/8c91f3a486691014b085fb11c44412ff.html which describes how to configure the `corsfilter` settings.
