### ISSUE TITLE
Separate the mobile and desktop from one e2e to the proper folder [only for my account tests]

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#4556]
We need to remove the mobile tests that are all in one and move them to the mobile folder

**Comment by giancorderoortiz** [comment]
but mobile tests will continue to run?
Is it possible to run them twice with mobile and then tablet breakpoints?

**Comment by KateChuen** [comment]
Yes, the tests will continue to run on the mobile breakpoint. Now they will be in their dedicated mobile folder. 
It it possible, but not necessary since the paths (the buttons clicked) are the same for mobile and tablet. We are not testing the ui (the look) here unfortunately.

**Comment by KateChuen** [comment]
Starting with MyAccount tests first

**Comment by KateChuen** [comment]
PR https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4586

**Comment by KateChuen** [comment]
PR https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4677
