### ISSUE TITLE
ASM Styling 

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#4558]
ASM Styling Step 1 - Create styles ASM

Add styling except for 
* media queries
* fix spinner

Which will both be addressed in their own ticket.

Rough styling guide in this diagram: https://wiki.hybris.com/display/spar/UI+-+MVP1

**Comment by plabadie** [comment]
pr #4697

**Comment by developpeurweb** [comment]
Styling for this ticket is all done and also fixes GH-4564, GH-4559, GH-4560
