### ISSUE TITLE
Variants "add to cart" on PLP/SRP check

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#4572]
This ticket is about ensuring that each item listed in the PLP/SRP is "purchasable" (not a base product nor style without size).

**Comment by mirkosoft** [comment]
@Xymmer AFAIR we agreed "Add to cart" button on the PLP is just an CTA linked to PDP. However, I can see that in electronics spa this is not the case: It does what it says - adds product to cart and proper popup is displayed: 
![image](https://user-images.githubusercontent.com/788092/65506559-1e074b80-decc-11e9-9916-b5caaa59ad89.png)
Therefore please confirm what's the path here to follow.

**Comment by psmul** [comment]
After analyzing available sample data and functionality, I wasn't able to find any `purchasable: flase` product cases.
