### ISSUE TITLE
Variant style icons at SRP/PLP

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#4574]
as mentioned in the last comment of #1787 let's consider adding variants icons to PLP/SRP as it;s done in the accelerator (this is just informative, tooltip with style name is displayed when over the icon):
![image](https://user-images.githubusercontent.com/788092/65235330-a6ee4380-dad6-11e9-8a0f-6a47de04b347.png)

**Comment by mirkosoft** [comment]
Let's check with UX how it could be represented on the mobile (as tooltips don't work there); let's also  consider do we need such thing at all in case of they're not needed on the mobile in that shape.

**Comment by Xymmer** [comment]
this might be a case where the tooltip is not available in mobile
ideally we'd display the name but we make another decision to not do so because there is no room

**Comment by vekterdude** [comment]
I don't understand this issue at all.
I also don't recognize the page above from anything I've ever seen in commerce.
As far as I can tell..it's not "a thing"
Also: tooltips are for help, not marketing.

**Comment by mirkosoft** [comment]
@vekterdude screenshot is taken from the accelerator, just open it:
https://dev-com-17.accdemo.b2c.ydev.hybris.com:9002/yacceleratorstorefront/?site=apparel-uk
and select any PLP, for example:
https://dev-com-17.accdemo.b2c.ydev.hybris.com:9002/yacceleratorstorefront/en/Categories/Streetwear-youth/T-Shirts-youth/c/270100?q=:relevance:brand:Billabong
