### ISSUE TITLE
Consistent occ user constants

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#4591]
We have `USERID_CURRENT` and `ANONYMOUS_USERID`. One is available in public API and other not.

Move `ANONYMOUS_USERID` to `occ-constants`. Keep it public until 2.0 and rename it in our code to `USERID_ANONYMOUS`.

**Comment by marlass** [comment]
Ticket for removal in 2.0 `ANONYMOUS_USERID` from public API: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4593

**Comment by Zeyber** [comment]
QA: Found no remaining instances of `ANONYMOUS_USERID` or `USERID_CURRENT`
