### ISSUE TITLE
Introduce closed store functionality

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#4594]
A lot of B2B storefronts need a closed store, which you cannot enter without logging in. There will be typically at least one page (login) public, or a few (such as register, help, support, etc.).

In order to achieve this we will configure in our libraries the Login related pages (login, register, forget password) as a public routes,  In order to enable/disable the closed storefront we introduce one configuration to close the storefront.

**Comment by Platonn** [comment]
### QA steps:
1. Configure closed storefront in app.module:
```typescript
routing: {
   protected: true,
   /* ... */
}
````
2. Verify that visiting any standard page results in the redirection to the login page.
3. Verify that you can normally open login-related pages: login, register, forgot password
4. Please login and verify that you are redirected to the page that you opened (or tried to open but was protected) just before the login page
5. Set `protected:false` for the `product` route and verify that all aliases of the product routes are public the same as login page (please ignore the product suffix , it's another story and Customer needs to extend our service to make them public - not in the scope of QA):
```typescript
routing: {
   protected: true,
   routes: {
     product: {
       protected: false,
       /* ... */
    }
   /* ... */
}
```

**Comment by Platonn** [comment]
### Notes for production use cases
1. Customer will need to adjust page template for login-related pages:
a) hide navigation links (reason: UX/security)
b) hide components that expose data, i.e. searchbox with suggestions (reason: security)_

2. Ideally in future we have secured OCC endpoints that don't expose data.

**Comment by KateChuen** [comment]
Tested on dev10:
- [x]  Configure closed storefront in app.module:
- [x] Verify that visiting any standard page results in the redirection to the login page.
- [x] Verify that you can normally open login-related pages: login, register, forgot password
- [x]  Please login and verify that you are redirected to the page that you opened (or tried to open but was protected) just before the login page
- [x] Set `protected:false` for the `product` route and verify that all aliases of the product routes are public the same as login page (please ignore the product suffix , it's another story and Customer needs to extend our service to make them public - not in the scope of QA):
- [x] Set `protected:false` for the `home` route and verify that it's public.

Found 2 issues, opened tickets #4765 & #4764.
