### ISSUE TITLE
Cart page E2E tests / SPA-1028

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#46]
For other E2E tests, we decided to focus on where backend adds value or can influence or cause breakage.

The assumption is that these kinds of tests are in addition to what Stan already is working on, so check with him. E.g. you can register successfully, and the user is logged in.

----

Make sure not to redo what was already done with the big happy path that stan did, but here are some E2E cart ideas.
 * Changing quantities updates all cart calculations to a predicted total, with expected effect on promotions as well.
 ** Example: ootb promotion is $20 off if over $200. Increasing product quantity before tax over $200 means the promotion is applied; decreasing product quantity below $200 means the promotion is removed (but appears as potential promotion).
 * Clicking remove removes the item from the cart, and same rules for quantity changes apply for calculations and promotions.
 * When all items are removed from cart, the page states there are no items, and you can't go to checkout.

----
Is the following implemented? If not create a spa ticket for future.
 * If item A is added to the cart, and at the time there was stock, but then you load the cart later and the item becomes out of stock, we display a message stating that the item was removed from the cart due to out of stock.

**Comment by wishfulthinkerme** [comment]
I've talked with Stan that the test below should be done here, instead of here https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/59: 

**Cart merging tests that aren’t in big e2e test**

Anonymous user has items in cart, logs in, new cart has all items
Logged in user adds items to cart, logs out, adds items to cart, logs in, carts merged

**Comment by marlass** [comment]
✔️ Tests pass.
✔️ Functions mentioned in descriptions are tested in tests.
