### ISSUE TITLE
Package i18n-lint unavailable - replace it or drop

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#4602]
https://github.com/jwarby/i18n-lint seems to be no longer maintained:
- last changes in the codebase 4 years ago
- **package disappeared from npm**

We need a quick spike, whether we can replace it with some other tool that looks for hardcoded texts in templates or we just drop `i18n-lint`.

**Comment by Platonn** [comment]
Waiting for the response of the author of the library https://github.com/jwarby/i18n-lint/issues/14

**Comment by Pucek9** [comment]
The author, after he learned that we were using his package, decided to make it public on npm

**Comment by Zeyber** [comment]
QA: Running `npm run i18n-lint` works as expected. Modifying a component html file with plain untranslated text is caught by the linter in `storefrontlib`.
