### ISSUE TITLE
 cart module: refactor public accessors into functions and rename functions

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#461]
Originating from #272 and discussed in Nov 29 refinement.

- Refactor public accessors into functions.
- If needed, rename functions to be short and into context
i.e. productService.get() instead of productService.getProduct()
Avoid redundancy. 
Additionally we are allowed to not mirror the commerce platform.

There is a follow up ticket for facades to load once in the store (epic/loadonceinstore).

**Comment by Xymmer** [comment]
All facades work will be tested with one ticket, #6.

**Comment by Jim-Yang** [comment]
PR: GH-562

**Comment by znikola** [comment]
Also, please add comments to methods.

**Comment by Jim-Yang** [comment]
> Also, please add comments to methods.

To which methods? All methods in the module or just the ones that I added?
