### ISSUE TITLE
checkout module: refactor public accessors into functions and rename functions

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#462]
Originating from #272 and discussed in Nov 29 refinement.

- Refactor public accessors into functions.
- If needed, rename functions to be short and into context
i.e. productService.get() instead of productService.getProduct()
Avoid redundancy. 
Additionally we are allowed to not mirror the commerce platform.

There is a follow up ticket for facades to load once in the store (epic/loadonceinstore).

**Comment by Xymmer** [comment]
All facades work will be tested with one ticket, #6.

**Comment by plabadie** [comment]
Please address the issue in the lint step of the pipeline.

**Comment by MitchellScottSandre** [comment]
Fixed the issue in the line step of the pipeline. Pipeline is now failing due to timeout issues.

**Comment by plabadie** [comment]
As agreed in standup, let's add comments on the facade functions.  Otherwise, the rest is good.

**Comment by plabadie** [comment]
The unit test/sonar step fails on the pipeline.
