### ISSUE TITLE
Update shell SSR config files

### ISSUE THREAD

**Issue by psmul** [SAP/cloud-commerce-spartacus-storefront#4630]
SSR config files can be updated as there are some differences with current (ngUniversal) files.
Changes should be mostly applied for files: server.ts, webpack.server.config.ts

**Comment by dunqan** [comment]
Please update these docs accordingly:
https://sap.github.io/cloud-commerce-spartacus-storefront-docs/server-side-rendering-in-spartacus/

+ add a recommendation to use schematics to generate the app with ssr support.
