### ISSUE TITLE
Pagination window should be centered on current page

### ISSUE THREAD

**Issue by mazamcodes** [SAP/cloud-commerce-spartacus-storefront#4632]
## Environment Details

- Spartacus:  1.1.1
- Browser: Any
- OS: Any
- Device: Desktop
- Other environment details: 

## Steps to Reproduce

When navigation using the pagination links on the search results page like so:
1. Click on the last numbered page link
2. Click on the link for the second from the last page
3. The pagination links do not show the previous page but rather shows ellipsis making it impossible to navigate to the previous page with numbered links.

## Observed Results

The previous/next links window for pagination does not shift correctly.
<img width="332" alt="Screen Shot 2019-09-18 at 6 35 22 AM" src="https://user-images.githubusercontent.com/39602213/65153412-8e026700-d9de-11e9-8743-b519ffd8d9cc.png">

## Expected Results

Previous/next links window for pagination should shift to remain centered on the current page.

The behavior should be as follows:
1. Click on the last numbered page link
2. Click on the link for the second from the last page
3. The pagination links should now shift to show links for one page previous as well.

<img width="505" alt="Screen Shot 2019-09-18 at 6 20 51 AM" src="https://user-images.githubusercontent.com/39602213/65152731-5e069400-d9dd-11e9-949c-845b512b6538.png">

**Comment by Xymmer** [comment]
can't repro now, likely fixed in a previous release

**Comment by Xymmer** [comment]
whoops closed wrong issue

**Comment by tobi-or-not-tobi** [comment]
Fixed with 2.0

**Comment by Xymmer** [comment]
fixed in 2.0 with #6060
