### ISSUE TITLE
guest user is not redirected to the first step of checkout after login

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4634]
**Environment Details**
Spartacus: feature guest checkout
Browser: Chrome
Device: mac
Happens on: http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Add a product to cart
- Proceed to checkout as Guest
- On _Order Confirmation_ page, create an account.
- Add a product to cart 
- Logout
- Add another product to cart
- Proceed to checkout as Guest
- On _Order Review_ page, click on Sign In
- Sign in -> You're back on the first step of checkout which is expected.
- Complete the checkout process.
- Go to cart page -> the item previously in the logged in user's cart is there
- Logout
- Add a product to cart
- Proceed to checkout as Guest
- On _Order Review_ page, click on Sign In
- Sign in 

**Actual Result*
This time, you're redirected to the last step of checkout (the _Order Review_ page), instead of the first step of checkout. And info like the shipping method is missing on that page:

![Screen Shot 2019-09-18 at 9 44 17 AM](https://user-images.githubusercontent.com/45409515/65154205-12fa7a00-d9f9-11e9-998f-8432e3c89bd0.png)

**Note**
Same thing happens if guest user logs in on other step of checkout, for eg, the billing form. He's redirected there instead of the first shipping checkout step.

**Comment by KateChuen** [comment]
I guess it's a bit of an edge case, so it can be fixed between 1.2 RC and 1.2.0 release.

**Comment by WeizhengSap** [comment]
I really think guest should not be able to login during checkout. When user login, we delete the guest cart, and create a new cart for the login user. So, the checkout cart is not the guest cart any more (different `guid/code`). So, that's why you see "Cart not found" error.

**Comment by WeizhengSap** [comment]
I will prevent guest login in this ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4155

**Comment by WeizhengSap** [comment]
I will reopen it.

**Comment by WeizhengSap** [comment]
I tested it with the steps provided. I can see that it redirect to the first step of checkout.

**Comment by KateChuen** [comment]
Yeah, seems like it's no longer reproducible. Can close.
