### ISSUE TITLE
TypeError in the console after a guest creates an account

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4635]
**Environment Details**
Spartacus: feature guest checkout
Browser: Chrome
Device: mac
Happens on: http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Add a product to cart
- Proceed to checkout as Guest
- On _Order Confirmation_ page, create an account.

**Actual Result*
Some TypeError in the console:
![Screen Shot 2019-09-18 at 9 19 17 AM](https://user-images.githubusercontent.com/45409515/65153886-86e85280-d9f8-11e9-9de2-77fe9f069005.png)

**Comment by LTiger14** [comment]
Duplicate as this #3735. Resolved in this ticket.

**Comment by giancorderoortiz** [comment]
TypeErrors no longer seen.
