### ISSUE TITLE
Header Category Tab Key Navigation

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#4636]
Need to make category navigation accessible by keyboard.

**Comment by KateChuen** [comment]
Tested locally.
Can navigate the header categories using the Tab Key now.

However, the top and bottom border on some are not that visible. @developpeurweb Is this being tackled in another ticket?
![Screen Shot 2019-10-02 at 1 47 19 PM](https://user-images.githubusercontent.com/45409515/66068689-107d4180-e51c-11e9-9fb5-40174175bc93.png)

**Comment by developpeurweb** [comment]
@KateChuen I'll tackle the uneven visual focus in this other ticket GH-4810
