### ISSUE TITLE
Mobile: Slots on homepage not properly displayed with calydon enabled

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4639]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: http://localhost:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Enable calydon by uncommenting line 4 in this file: projects/storefrontapp/src/styles.scss
- Run a yarn
- Start your app
- Load the storefront on a mobile view

**Actual Result**
Some slots are not aligned properly.

![Screen Shot 2019-09-18 at 11 39 14 AM](https://user-images.githubusercontent.com/45409515/65163781-91f7ae80-da09-11e9-9d83-7c14008433d7.png)
![Screen Shot 2019-09-18 at 11 39 22 AM](https://user-images.githubusercontent.com/45409515/65163782-91f7ae80-da09-11e9-82c9-2439ed25e99e.png)

**Comment by mazamcodes** [comment]
![Homepage-check-mobile-calydon-theme](https://user-images.githubusercontent.com/39602213/72387325-1e745e00-36d8-11ea-9637-83ce5ea8276d.jpg)
Looks fixed. Unable to reproduce in latest `develop`.

**Comment by KateChuen** [comment]
Tested on dev3. Ok now.
