### ISSUE TITLE
Set the currently selected variant label

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#4648]
UX question: should we display those texts or just indicate visually current selection? Ie. border for style (for size it's already selected option)?

If yes, those values should be extracted from the response.

![image](https://user-images.githubusercontent.com/788092/65233584-5de8c000-dad3-11e9-8208-cb9179ded063.png)

**Comment by psmul** [comment]
About QUESTION.
After some consultations we will leave Style label, but remove second part of Size label (<selected size>).
