### ISSUE TITLE
Add occ userId logic to loadOrderDetails

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#4657]
There was a solution in the asm epic branch that can be used to minimize deprecations and function signature changes on the develop branch for the guest checkout feature.

**Comment by plabadie** [comment]
PR #4660

**Comment by LTiger14** [comment]
For QA:

**Comment by KateChuen** [comment]
Tested on dev10. 
Order Details works for both guest and registered user.
- Checkout as a guest, then create an account -> can see the order details properly.
- Checkout as a logged user -> can see the order details properly.
- Checkout as a guest -> Don't see the order details when logged in later.
- Start checkout as a guest, then login, and complete the checkout -> can see the order details properly.
- Checkout as a logged user (who was registered through the regular registration flow) -> can see the order details properly.
