### ISSUE TITLE
Toggle feature

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#4659]

**Comment by WeizhengSap** [comment]
sample data PR is here: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/42

By default, "order cancellation/return" is disabled. So, there is no "cancel/return" button in "order details" page.

To enable this feature, you can import this from hac:
```
$contentCatalog=electronics-spaContentCatalog
$contentCV=catalogVersion(CatalogVersion.catalog(Catalog.id[default=$contentCatalog]),CatalogVersion.version[default=Online])[default=$contentCatalog:Online]

# Make AccountOrderDetailsActionsComponent visible
INSERT_UPDATE CMSFlexComponent;$contentCV[unique=true];uid[unique=true];visible
;;AccountOrderDetailsActionsComponent;true

# This UPDATE will make the order history page contain tabs
UPDATE ContentSlot;$contentCV[unique=true];uid[unique=true];cmsComponents(uid, $contentCV)
;;BodyContent-orders;AccountOrderHistoryTabContainer
```
Or, in backoffice, make `AccountOrderDetailsActionsComponent` visible; and replace the component inside `BodyContent-orders` slot to `AccountOrderHistoryTabContainer`.

**Comment by KateChuen** [comment]
Tested on dev10.
