### ISSUE TITLE
order-history-flow failing e2e tests

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4663]
after merging the new features to develop on sept19 (release 1.2.x) , the following tests have been failing and need to be fixed:

regression/my-account/order-history-flow.e2e-spec.ts

**Comment by marlass** [comment]
Order-history tests (mobile, regression) looks stable. 5 runs for each and 100% success rate.
Last 3 nightly jobs didn't fail on those tests.

**Comment by KateChuen** [comment]
Closing since they haven't failed on the nightly builds
