### ISSUE TITLE
Inconsistent CMS data for Storefinder

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#4666]
We tried to test store finder on dev17 and we noticed the following:
* store finder link is marked as invisible
* Label for store finder page is wrong
* Endpoint to get list of stores is not being called

Perhaps there's missing sample data?

**Comment by WeizhengSap** [comment]
sample data PR is here: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/14

**Comment by mirkosoft** [comment]
I've run the Impex change done by @WeizhengSap against the online catalog and it worked fine. Also have proposed one change in that PR so the page label is correct now (also run it against online).
All issues listed in this ticket should be gone now at the online catalog version on dev17.

**Comment by Matejk00** [comment]
PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/14 with new data for storefinder was merged.

**Comment by KateChuen** [comment]
Tested on dev17. Works now! I can see the link, it goes to the storefinder page, and I see stores there.
The storefinder e2e tests are passing.
