### ISSUE TITLE
express-checkout.e2e-spec.ts failing

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4668]
**after merging the new features to develop on sept19 (release 1.2.x) , the following tests have been failing and need to be fixed:
regression/express-checkout.e2e-spec.ts

it's expecting the cart to have 1 product, but the cart is empty, so it fails.

**Comment by marlass** [comment]
Fails because of this issue: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4155#issuecomment-534010526

On hold

**Comment by KateChuen** [comment]
It's fixed now. Test is passing in the nightly builds, and also when I run it locally against dev17.
