### ISSUE TITLE
Error when signing out from Order Details Page

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#4685]
### Steps to reproduce

1. Login
2. Execute a purchase
3. Go to order history
4. Select order details
5. Sign out

You will see the following error
<img width="1419" alt="Screen Shot 2019-09-20 at 4 15 59 PM" src="https://user-images.githubusercontent.com/10605724/65356251-fe1d1280-dbc1-11e9-8f40-4e07a89f9085.png">

### Expected behavior

This error should not be visible

**Comment by Pucek9** [comment]
@LTiger14 Cannot reproduce on default env. Could you check again? Maybe additional configuration (guest checkout) is necessary?

**Comment by Xymmer** [comment]
to louis to agree can't repro or try to repro

**Comment by LTiger14** [comment]
Could not reproduce either.
