### ISSUE TITLE
Header Category Aux Key Navigation

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#4686]
Should follow typical navigation guidelines as described here: 
https://wiki.hybris.com/display/spar/Key+interactions+for+General+keyboard+navigation

**Comment by KateChuen** [comment]
Tested on dev3. 
- Chrome
- Firefox
- Safari

Only have a couple of observations: 
- ESC does not close the category menu, but SPACEBAR does #6513 
- Extra focus shown after drop down menu on firefox only #6514
