### ISSUE TITLE
Breaking Changes since v1.3: Header Category Tab Key Navigation (#4636)

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#4687]
- [x] Remove `featureConfigService?` from constructor.

- [x] Remove deprecation code from `isTabbable()` method:

```protected isTabbable(node: any) {
    //TODO(issue:#4687) Deprecated since 1.3.0
    if (!(this.featureConfig && this.featureConfig.isLevel('1.3'))) {
      return false;
    }
    return this.flyout && node.children && node.url;
  }
```

**Comment by kacperknapik** [comment]
additionally remove `isLevelBool` variable, `MockFeatureConfigService` class, and the usage of said class in `providers`

**Comment by KateChuen** [comment]
Tested on dev3, on chrome, safari & firefox.
