### ISSUE TITLE
product module: refactor public accessors into functions and rename functions

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#469]
Originating from #272 and discussed in Nov 29 refinement.

- Refactor public accessors into functions.
- If needed, rename functions to be short and into context
i.e. productService.get() instead of productService.getProduct()
Avoid redundancy. 
Additionally we are allowed to not mirror the commerce platform.

There is a follow up ticket for facades to load once in the store (epic/loadonceinstore).

**Comment by Xymmer** [comment]
All facades work will be tested with one ticket, #6.

**Comment by MitchellScottSandre** [comment]
PR: GH-547

**Comment by plabadie** [comment]
Please resolve the conflicts on the PR.

**Comment by MitchellScottSandre** [comment]
I resolved the conflicts
