### ISSUE TITLE
Product References in product Detail Page 

### ISSUE THREAD

**Issue by ayoubElmoussaoui** [SAP/cloud-commerce-spartacus-storefront#4693]
Product References in product Detail Page are  not displayed as expected 

## Environment Details

- Spartacus:  1.0.0
- Browser: google chrome
- OS: Mac OS Mojave v 10.14.6
- angular-devkit/architect    0.803.4
- angular-devkit/core         8.3.4
- angular-devkit/schematics   8.3.4
- schematics/angular          8.3.4
- schematics/update           0.803.4
- rxjs                         6.4.0
- SAP commerce cloud : v19.05

## Steps to Reproduce
prerequisites : spartacussampledataaddon installed, freshly initialized out of the box  electronics accelerator , Spartacus points to electronics-spa ,  
1. chose a product visible on the front end.
2. add some product references of type CrossSelling and UpSelling to it.
3. set up ProductReferencesComponent and ContentSlot. to make it easy for you import  the following impex : 
```
$spacontentCatalog = electronics-spaContentCatalog
$spacontentCV = catalogVersion(CatalogVersion.catalog(Catalog.id[default=$spacontentCatalog]), CatalogVersion.version[default=Staged])[default=$spacontentCatalog:Staged]
$contentCatalog = electronicsContentCatalog
$contentCV = catalogVersion(CatalogVersion.catalog(Catalog.id[default=$contentCatalog]), CatalogVersion.version[default=Staged])[default=$contentCatalog:Staged]
$enLang = en


INSERT_UPDATE ProductReferencesComponent; $spacontentCV[unique = true]; uid[unique = true]; name          ; productReferenceTypes(code); maximumNumberProducts; &componentRef; title[lang = $enLang]
                                        ;                             ; CrossSelling      ; Cross Selling ; CROSSELLING                ; 5                    ; CrossSelling ; CrossSelling
                                        ;                             ; UpSelling         ; UpSelling     ; UPSELLING                  ; 5                    ; UpSelling    ; UpSelling


INSERT_UPDATE ContentSlot; $spacontentCV[unique = true]; uid[unique = true]; cmsComponents(&componentRef)
                         ;                             ; UpSellingSlot     ; UpSelling
                         ;                             ; CrossSellingSlot  ; CrossSelling

INSERT_UPDATE ProductReferencesComponent; $contentCV[unique = true]; uid[unique = true]; name          ; productReferenceTypes(code); maximumNumberProducts; &componentRef; title[lang = $enLang]
                                        ;                          ; CrossSelling      ; Cross Selling ; CROSSELLING                ; 5                    ; CrossSelling1 ; CrossSelling
                                        ;                          ; UpSelling         ; UpSelling     ; UPSELLING                  ; 5                    ; UpSelling1    ; UpSelling


INSERT_UPDATE ContentSlot; $contentCV[unique = true]; uid[unique = true]; cmsComponents(&componentRef)
                         ;                          ; UpSellingSlot     ; UpSelling1
                         ;                          ; CrossSellingSlot  ; CrossSelling1

```
4. 
sync electronics content catalog staged to electronics content catalog online 
sync spa electronics content catalog staged to spa electronics content catalog online

5. open Product Detail page for the selected product (1.) 

## Observed Results
when visiting the product details page in Spartacus : 

<img width="791" alt="Screen Shot 2019-09-24 at 14 24 19" src="https://user-images.githubusercontent.com/21149396/65511297-2ca73000-ded7-11e9-98ec-76a6190928c9.png">

when visiting the product details page in the yacceleratorstorefront :

<img width="791" alt="Screen Shot 2019-09-24 at 14 24 34" src="https://user-images.githubusercontent.com/21149396/65511275-1c8f5080-ded7-11e9-8328-08580e5ce7cc.png">

## Expected Results
the product references should be the same as in yacceleratorstorefront product details page

**Comment by mazamcodes** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4809

**Comment by hackergil** [comment]
@mazamcodes Please add a unit test for the last fix (empty array)

**Comment by mazamcodes** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5070

**Comment by mazamcodes** [comment]
To test, open Backoffice, add product references under Category System tab of Product Cockpit for desired product. You should now see that product references added as CrossSelling or Upselling are corectly displayed in the corresponding carousel on the PDP.

To test when no references are present, there should not be any errors thrown, either in the console of developer tools in the browser nor in the console for the running application.

**Comment by KateChuen** [comment]
Tested on dev17. 
Upselling and Cross-selling products displayed correctly in pdp's carousel.
<img width="768" alt="Screen Shot 2019-10-24 at 12 24 09 PM" src="https://user-images.githubusercontent.com/45409515/67505929-27fea480-f65a-11e9-8238-05090013ff96.png">
<img width="1016" alt="Screen Shot 2019-10-24 at 12 27 14 PM" src="https://user-images.githubusercontent.com/45409515/67505931-27fea480-f65a-11e9-8830-3a3e28cf2780.png">
<img width="1013" alt="Screen Shot 2019-10-24 at 12 27 24 PM" src="https://user-images.githubusercontent.com/45409515/67505933-28973b00-f65a-11e9-8596-8b26aa0227cf.png">

Even having no product references for that product is ok, no error displayed.

**Comment by ayoubElmoussaoui** [comment]
Thank You Spartacus team for fixing this bug,
on which release version can we get this fix ?

**Comment by Xymmer** [comment]
@ayoubElmoussaoui it will come with 1.3.0 which is planned for about 2 weeks.
If it's urgent we can do a hotfix and put it in 1.2.x, pls let me know.

**Comment by ayoubElmoussaoui** [comment]
Thanks @Xymmer , i think we can go with 1.3.0 
Regards,
