### ISSUE TITLE
Reintroduce login link during checkout

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#4694]
Login link was removed during checkout but it should be brought back.

**Comment by KateChuen** [comment]
Tested on dev10 with this config:

`      features: {`
    `    level: '1.2',`
`      },`
`      checkout: {`
`        express: true,`
   `     guest: true`
   `   }`

SignIn/Register link is available during checkout, and guest user can login at any step of checkout.
