### ISSUE TITLE
auth module: only load once in the store

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#470]
Originating from #272 and discussed in Nov 29 refinement.

Only load once in the store (like what we did in product store).
Not every module needs it. Close if not with a comment.
To be done after **epic/accessors>functions**

See #272 for example and checklist from Stan. Direct questions to Stan.

**Comment by plabadie** [comment]
To align with a team decision to implement the load state management progressively and only needed, the following small changes are be done to the Client Token loading mechanism.
- The `loading` flag is removed because it was only used to synchronize requests.  An `exhaustMap` operator is doing that instead.
- The loaded flag was only used to know if the request was over from within the service only in the case of a token refresh.  Clearing the expired token before refreshing will remove the need for the loaded flag.

**Comment by plabadie** [comment]
PR #1036

**Comment by plabadie** [comment]
Case 1 : To test the client token load: 
* Clear the browsing data of the browser and reload the storefront
* Assess in the redux dev tools that no client token is already loaded ( in auth-> clientToken )
perform a registration.
* Assess that there was a http request made to acquire the token.  You can filter the requests with the work ’token’ in the chrome devtools. A client token request has the form data  payload of:
```
client_id: mobile_android
client_secret: secret
grant_type: client_credentials
```
Case 2: To test the client token reuse:
* Logout the current user and register 
* Clear the network activity tab in the chrome dev tools
* Register a new user.
* Assess that the same client token as before is in the store ( in auth-> clientToken )
* Assess that no new request was made to the backend to acquire a client token.
Case 3a: Setup to test the client token refresh: 
* Use these commerce suite configs to have the token expire after 20 seconds
```
oauth2.accessTokenValiditySeconds=20
oauth2.idTokenValiditySeconds=20
oauth2.refreshTokenValiditySeconds=20
```
* After you restart the commerce suite, you will need to delete all the auth tokens via backoffice.
* Repeat all the steps in Case 1.
* Assess that the client token expires in a few seconds ( should be around 19 ) 
Case 3b: Test the client token refresh
* Logout the user created in Case 3a.
* Wait at least 20 seconds for the client token to expire.
* Register a new user.
* Assess that a client token request was made.
* Assess that the client token is updated in the store ( in auth-> clientToken ).
