### ISSUE TITLE
Variant selector UX improvement

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#4706]
Change the logic re-applied from the accelerator: currently you can't see the "Add to cart" button unless you select size after picking a style.
Expected behavior is to automate things a bit: let the component guess the size and select it so user immediately can see the "Add to cart" button instead of "out of stock" text.

Notes:
- there is also stock level check on which "Add to cart" button appearance depends - this is OK but pls keep in mind
- please also check the case where product has just one variant dimension (style OR size); this ticket shouldn't apply here but let's ensure it's fine

**Comment by mirkosoft** [comment]
Considering the broader picture of variants future development let's just improve UX here but do not over complicate things with redirections behide the scenes. For now user will be notified (by setting focus on "size") in case of trying add to cart not `purchasable` product.

**Comment by psmul** [comment]
QA steps:
1. Find & go to base product (e.g. ``)
2. Select different product style

*Expected result:*
Should redirect straight to view with auto-selected size from dropdown.

Example products:
`apparel-uk-spa/en/GBP/product/300441355`
`apparel-uk-spa/en/GBP/product/300399588`
