### ISSUE TITLE
cart module: only load once in the store

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#471]
Originating from #272 and discussed in Nov 29 refinement.

Only load once in the store (like what we did in product store).
Not every module needs it. Close if not with a comment.
To be done after **epic/accessors>functions**

See #272 for example and checklist from Stan. Direct questions to Stan.

**Comment by WeizhengSap** [comment]
The loading/loaded flags are messed up by this ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/512

**Comment by WeizhengSap** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1098
