### ISSUE TITLE
Product Search e2e test is failing (smoke test)

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#4720]
The product search smoke test is failing. Since it is a smoke test it prevents merging to develop.

These are the errors from Jenkins. It seems to be that the Stores facets are missing in the product search page. Going to the product search in de-17 the Stores facet is not visible

![Screen Shot 2019-09-24 at 10 12 15 AM](https://user-images.githubusercontent.com/10605724/65519442-eb515900-deb3-11e9-8079-ecf097906afd.png)

**Comment by plabadie** [comment]
Pulled the latest sample addon to grab this fix: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/17

and re-initialized the instance.
