### ISSUE TITLE
"Cart Not Found" error when choosing a default address

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#4722]
Assessed on dev-17 on 2019-09-24

Steps to repro:

- Sign in with a user ( or register one )
- Have 2 addresses in his address book. ( create them if needed )
- From the address list, click "Set as default" on the address card.

Actual Result:
- The "Set as default" operation works, but generates a "Cart not found." error.

<img width="1268" alt="Screen Shot 2019-09-24 at 3 32 50 PM" src="https://user-images.githubusercontent.com/7065346/65544833-1c488280-dee2-11e9-9512-4791729684e3.png">

Expected result:
- The "Set as default" operation works and no error occurs.

**Comment by KateChuen** [comment]
Tested on both dev10 and dev17. I don't see the 'cart not found' error any more in this scenario.
