### ISSUE TITLE
cms module: only load once in the store

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#473]
Originating from #272 and discussed in Nov 29 refinement.

Only load once in the store (like what we did in product store).
Not every module needs it. Close if not with a comment.
To be done after **epic/accessors>functions**

See #272 for example and checklist from Stan. Direct questions to Stan.

**Comment by WeizhengSap** [comment]
After discussing with Stan, we decided only to add `entityLoaderReducer` to cms component and navigation.

**Comment by WeizhengSap** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/1055

Note:
In this ticket, we only apply "load once" to navigation nodes. For cms component, we created another ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1029
