### ISSUE TITLE
Add Token Revocation Support on Logout.

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#4739]
The token revocation backend endpoint is available since version 1905.6

To improve security, the Spartacus storefront needs to trigger a token revocation request when a user logs out.

Here is the expected behaviour:
* When a regular customer logs out, a token revocation request is sent.
* When an emulated customer logs out (ASM), no revocation request should be sent (the token belongs to the cs agent)
* When a customer support agent logs out, a token revocation request.

Constraints and requirements to consider:

- The backend does not fail silently.
The revocation endpoint does not fail silently.  Moreover, the backend requires that the revocation request is made only with a token that is still valid, otherwise it returns a http 401 error.  Revocation calls with expired tokens will happen from time to time and 401 errors will happen.

-- Mitigation: Spartacus must fail silently when the revocation request returns an error.  There is no recovering from these errors.

- Backwards compatibility:
Spartacus needs to be backwards compatible with versions prior to 1905.6 in spite of the endpoint not being present in previous versions.

-- Mitigation: Spartacus must fail silently when the revocation request returns an error.  There is no recovering from these errors.

**Comment by plabadie** [comment]
There is a gap between how the revocation endpoint works vs our expectations.
See https://wiki.hybris.com/display/spar/Spartacus+Token+Revocation+Support

The Spartacus implementation could go like this:

Standard customer logout: call revocation, ignore the potential error returned.
Asm Customer emulation logout: just do a local logout, like we do currently in all cases.
Asm customer support agent: call revocation, ignore the potential error returned.

**Comment by plabadie** [comment]
For Tests/QA:

There are 3 use cases to try on 2 backend versions.

|   | Version >= 1905.06 | Version < 1905.06 |
| ------------- | ------------- | ------------ |
| Customer Logout  | Send revocation request  | Send revocation request (but revocation will never succeed)  |
| Emulated Customer Logout  | No revocation request (preserve csagent token)  | No revocation request (preserve csagent token) |
| CS Agent Logout   | Send revocation request for agent token | Send revocation request for agent token (but revocation will never succeed)  |


* To assess if the revocation request is done by Spartacus, use the network tab in the dev tools and look for a POST request to the endpoint `/authorizationserver/oauth/revoke`

* To assess the success of the request on the server, use the token section of backoffice ( System -> OAuth ->. OAuth Access Tokens  ).  If you delete all existing tokens first, you will see a new token appear when you sign in via Spartacus.  Then, when you sign out, if the token revocation request is a success, you ran refresh the search in backoffice and you will see the token disappear.

* In any case, in Spartacus, a revocation request should fail silently in Spartacus.

**Comment by giancorderoortiz** [comment]
Feature test successful. 
Tested against < 1905.7. Token revocation fails silently as designed. 
Tested against 1905.7. Token is in fact revoked after logout and it can't be used any longer.
