### ISSUE TITLE
Add structured data to different pages / components

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#4748]
Structured data provides a concept for the web to expose content in a more semantic way. Where html5 only provides the technical semantics (i.e. `img` vs `svg`), structured data provides a way to understand whether the content represents a product, a review, a person, etc. Without this level of detail, crawlers like Google, Pinterest, Twitter, etc. have a hard time to understand the content. Therefor they're not able to add the content to the right context. This is where schema.org comes in.

The schema.org standard provides a few technical standards to add the metadata Spartacus will use `json-ld` as the technical format to add schema's:
- it's the recommended format by Google
- it's most easiest to add in Spartacus
- it can be nicely separated from the UI and doesn't pollute the UI (css)
- can be controlled (extended) outside the component context

We will find the right placed to add schema's, but either way we need to make sure that it's extensible by customers, as the model is quite big. 

We will not have a data set available for all schema's we like to add. We could consider to add  these schema's statically (i.e. add a schema to router data), but ideally customers add this through Google Tag Manager. Most customers are used to this approach anyway, and it gives more flexibility to the business users. That being said, whenever we have an automated way to add the data (i.e. on PDP), we should do this in Spartacus.

We could add the following schema's:
- Each page could have a [breadcrumb schema](https://schema.org/BreadcrumbList)
- The PDP should be exposed with [product, offer, rating and review schemas](https://schema.org/Product).
- The local POS could be exposed in [local business](https://schema.org/LocalBusiness) schemas. [See also google dev](https://developers.google.com/search/docs/data-types/local-business)

**Comment by tobi-or-not-tobi** [comment]
Schema's are not by default build with the out of the box `B2cStorefrontModule` for smooth adaption of this feature. The `JsonLdBuilderModule` is needed to build schema's. 

QA steps
- validate that schema's are added in dev mode or SSR mode
- validate that schema's are not added in prod outside of SSR

How to validate?
- There are 3 schema's: breadcrumbList and product (including rating, reviews and offer)
- Make sure `JsonLdBuilderModule` is imported in app (i.e. in `app.module.ts`)
- Use a chrome plugin to validate schema's (i'm using https://chrome.google.com/webstore/detail/structured-data-testing-t/kfdjeigpgagildmolfanniafmplnplpl)

**Comment by psmul** [comment]
QA results:
Schemas are added in dev mode - **Correct**
Schemas are added in SSR mode - **Correct**
Schemas are NOT added in prod mode - **Correct**


**Although** there are some errors and warnings appeared while testing:

1. Product without any reviews (product/1978440_md/DSC-H20_MD)
```
ratingValue	     (MISSING_FIELD_WITHOUT_TYPE)
ratingCount	   0  (NON_POSITIVE_FIELD)
reviewCount	   0  (NON_POSITIVE_FIELD)
```

2. Product with reviews (product/1934793/PowerShot%20A480)
No significant errors, however few warnings appeared.
```
priceValidUntil	     (MISSING_RECOMMENDED_FIELD)
url	             (MISSING_RECOMMENDED_FIELD)
gtin8, gtin12, 
gtin13, gtin14, mpn, isbn     MISSING_PRODUCT_ID
```


I believe that at least errors should be fixed before release.

**Comment by psmul** [comment]
After consultation with Tobias, currently reported concerns about errors are not blocking for release. Will be fixed with another release. Issue: #5153
