### ISSUE TITLE
Early Login: Should user be able to open the Terms And Conditions page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4764]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: https://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/login

**Steps to Reproduce**
- enable early login
```typescript
routing: {
   protected: true,
   /* ... */
}
````
- Click on Register
- On registration page, click on the 'Terms and Conditions' link

**Actual Result**
The user is redirected to the login page in the new tab. Since the user is creating a new account, I believe he should be able to have access to the Terms and Conditions. But maybe it's more for the customer to configure on their side?

**Comment by Platonn** [comment]
@KateChuen, I've answered a similar quesiton in the Pull Request:
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4651#discussion_r326126771

**Comment by KateChuen** [comment]
Ah, sorry missed it. Alright, closing this ticket then.
