### ISSUE TITLE
Early Login: Homepage is displayed after signing out

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4765]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: https://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/login

**Steps to Reproduce**
- enable early login
```typescript
routing: {
   protected: true,
   /* ... */
}
````
- Sign in
- Sign out

**Actual Result**
Upon signing out, the homepage is displayed. 

**Expected Result**
The login page should be displayed instead.

**Comment by kacperknapik** [comment]
![image](https://user-images.githubusercontent.com/22354613/70142753-3a78ee80-169a-11ea-926b-401bb6f4d6cf.png)
Currently we might not have `/logout` page in CMS.

Will look into that
