### ISSUE TITLE
ASM documentation

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#4768]
ASM documentation

**Comment by developpeurweb** [comment]
In order for clients to change the ASM component logo they will have to go to this file
`projects/storefrontapp/src/styles.scss`
And write the following code which hides the current SAP logo image and sets a new logo as background.
`width`, `height` and `background-image` are to be changed by those specific to the client's case.

![Screen Shot 2019-10-01 at 10 33 39 AM](https://user-images.githubusercontent.com/15113219/65972656-2c0f1c00-e438-11e9-8f56-54a9f7ef4bac.png)

The example above will result in this logo replacement:

**BEFORE**
![Screen Shot 2019-10-01 at 10 45 17 AM](https://user-images.githubusercontent.com/15113219/65972999-a17aec80-e438-11e9-95b1-e73ff94e8113.png)

**AFTER**
![Screen Shot 2019-10-01 at 10 34 10 AM](https://user-images.githubusercontent.com/15113219/65973018-a8a1fa80-e438-11e9-80d5-98acdbf4f985.png)
