### ISSUE TITLE
Lacking Session Sharing Mechanism for External Routing

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#4797]
(Mentioned during threat modelling of external routing feature)
How to share sessions when using external routing? 

Details pending. 

fyi @Platonn

**Comment by Platonn** [comment]
It's not a bug. We agreed that to transfer the session of logged in user between 2 systems we need 3rd party authorization integrated both in Spartaucs and in Accelerators.

Moreover the anonymous users should share somehow the same cart guid, which can be more challenging.

That being said, the routing migration works OK, if you use it only for content pages (not personalized). So it's only a partial solution. It's a matter of priorities if we want to push

**Comment by KateChuen** [comment]
Not a threat modeling issue since we don't share sessions.
