### ISSUE TITLE
[Retest after 4619] TM: Slash "/" Issue in Product Details Page. Wrong Encoding

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#4798]
(Found during threat modelling of external routing functionality)

"/" is not being used properly in product details page. 
Details pending.

**Comment by KateChuen** [comment]
Could be fixed with https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4619. Please retest after https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4619 has been fixed.

**Comment by Xymmer** [comment]
@giancorderoortiz : need QA steps for what we are looking for, for:
  "/" is not being used properly in product details page.

I tried putting %2F in the URL; Spartacus displays not found but then 2 blank global errors.
At the same time Kate wrote that  #4619 might fix the problem but it's not closed yet.

**Comment by Xymmer** [comment]
GC says don't hold the release for this ticket and he'll come back to it next week

**Comment by LTiger14** [comment]
Could not repro with new encoding
