### ISSUE TITLE
console errors after refresh on checkout address form page / SPA-1285

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#48]
(Using backend dev-com2 and just-registered user without any addresses added before):

When a user goes to checkout (address form) and refreshes, then after reload there are many errors in console of the same type:
{code:java}
ERROR TypeError: Cannot read property 'childs' of undefined (NavigationComponent.html:2){code}

**Comment by Xymmer** [comment]
Giancarlo wrote in spa ticket:
I got this error in screenshot after placing an order (already saved address/credit card) and signing out.
On dev-com19 http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/

**Comment by Xymmer** [comment]
screenshot from spa ticket
![image](https://user-images.githubusercontent.com/4998145/47605469-c9660280-d9d4-11e8-8335-879ca3659e34.png)

**Comment by Matejk00** [comment]
QA done, Can't reproduce.
