### ISSUE TITLE
[Fixed in GH-6052] Uneven Visual Focus on Menu Navigation

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#4810]
Visual focus seems to tight and uneven as per screenshot

![66068689-107d4180-e51c-11e9-9fb5-40174175bc93](https://user-images.githubusercontent.com/15113219/66070622-a8305f00-e51f-11e9-99da-acc1b23926fa.png)

**Comment by KateChuen** [comment]
Tested on dev3.
- Chrome 
- Firefox
- Safari

On the homepage, it's fine (confirmed with Miguel that it's ok that it's spreading to the other category too. He said it's ok as long as it's not cut).
<img width="862" alt="Screen Shot 2020-02-17 at 9 57 42 AM" src="https://user-images.githubusercontent.com/45409515/74664928-abde1e80-516c-11ea-87e8-66cb379a7024.png">



- So here's my question, the bottom of the focus is cut when i'm on a different page, for eg, PLP or StoreFinder page. Should that be fixed???? @developpeurweb 

<img width="872" alt="Screen Shot 2020-02-17 at 9 57 28 AM" src="https://user-images.githubusercontent.com/45409515/74664938-b00a3c00-516c-11ea-8df4-585c763ad312.png">

**Comment by developpeurweb** [comment]
This is now fixed for all 3 browsers:

![Screen Shot 2020-03-09 at 3 41 54 PM](https://user-images.githubusercontent.com/15113219/76250956-9795ba80-621c-11ea-98c3-b5f1b9b09215.png)

![Screen Shot 2020-03-09 at 3 41 32 PM](https://user-images.githubusercontent.com/15113219/76250957-9795ba80-621c-11ea-8e3a-1e5c28ce294a.png)

**Comment by KateChuen** [comment]
Tested on dev10. 
Verified on chrome, safari & firefox.
OK on homepage, plp, pdp, account page, login page, store finder page.
