### ISSUE TITLE
asm e2e tests are broken

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#4812]
A recent change on the develop branch breaks the asm e2e tests. ( ran against  devcom2) 

<img width="573" alt="Screen Shot 2019-10-02 at 3 56 49 PM" src="https://user-images.githubusercontent.com/7065346/66077119-4b3ba580-e52d-11e9-9043-cd228f5d5f32.png">

**Comment by plabadie** [comment]
PR #4813

**Comment by KateChuen** [comment]
Works now!
