### ISSUE TITLE
Refactor item-counter

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#4819]
The item-counter component is a low-level component used in several places in the UI. It's used do increase or decrease the quantity of a cart item, during or after the add-to-cart action. While it's a super simple component, the implementation is quite complicated. As part of a wider cart refactor, we like to refactor this code. 

Refactoring:
- simplify DOM (it's just 2 buttons and an input)
- simplify component logic
- rely on formControl for quantity _state_ (i.e. disabled) and quantity _savedValues_
- use the number input type to benefit form numeric support
- drop bootstrap for the UI

Additionally, there are a few functional changes we propose:
- allow for submitting the quantity form by using the `enter` key
- move the buttons outside the keyboard control for a11y – if the mouse cannot be used, the focus on the input is enough to control the quantity with numeric keyboard, arrow keys, or plus and minus keys

Stretch:
- In some business fractional units are used for quantity, while this is rare, it would be great if we can support this. 
- We might want to introduce validation messages
- we might want to take the existing cart count into account; currently only the stock value is used for the max number, this is however invalid in case the item is already added to the cart.

**Comment by tobi-or-not-tobi** [comment]
This is a follow up on #830

**Comment by tobi-or-not-tobi** [comment]
fixed with #4863

**Comment by KateChuen** [comment]
QA steps please.

**Comment by tobi-or-not-tobi** [comment]
Let's keep QA on hold until we finished #7056
