### ISSUE TITLE
Can add "out of stock" item using "Add To Cart" button at PLP/SRP

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#4821]
Go to either SRP or PLP:
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/search/tripod
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/Open-Catalogue/Cameras/Camera-Accessories-26-Supplies/Tripods/c/587

and click "Add to Cart" for the below product:
![image](https://user-images.githubusercontent.com/788092/66119770-a5924000-e5d9-11e9-8875-239b721fe4e6.png)

Product gets added but in fact it's out of stock, see the PDP:
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/product/23355/Flagship%20tripod%20with%20remote%20control%20and%20pan%20handle

It can be reproduced on dev17 as well.

**Comment by mirkosoft** [comment]
related to #4572

**Comment by psmul** [comment]
The same issue as in #3044

**Comment by psmul** [comment]
After more investigating the issue, I believe the current problem lies in the backend side:
For endpoint /products with parameters fields=products and stock(FULL) response with list of products not always contains field stockLevel, which should be always returned, even when value is 0.

Investigated on dev-17 and dev-15.

Few example items: (product codes)

- 1978440_blue
- 1494590
- 1776947

**Comment by tobi-or-not-tobi** [comment]
@psmul It's a bug in the component logic actually, I've created a PR, you mind reviewing? 

@mirkosoft FYI

**Comment by tobi-or-not-tobi** [comment]
QA:
- verify that the add-to-cart button on the PLP is missing for products that do not have stock (i.e. search for "flagship tripod")

**Comment by mirkosoft** [comment]
QA tested, issue is gone.

**Comment by tobi-or-not-tobi** [comment]
Interestingly the product 23355 (tripod) is **IN STOCK**, both when we query SOLR as well as straight to the DB:

- https://storefront.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/rest/v2/electronics-spa/products/23355?fields=code,stock(FULL,stockLevel)
- https://storefront.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/rest/v2/electronics-spa/products/search?fields=products(code,stock(FULL,stockLevel))&query=23355

We're fixing this as part of #5167.
