### ISSUE TITLE
Spike an infinite scroll option for search and category lists

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#483]
Infinite scroll is known to increase user retention or at least maintain their attention for longer.

Let's spike what it would take to provide a configurable option that allows infinite scroll in search and category lists. Some options:
- Don't display any pagination; only do infinite scroll
- Keep pagination but limit infinite scroll to a certain upper limit
- Other options to be fleshed out

**Comment by RadhepS** [comment]
We will implement a toggle that will allow users to decide whether they want to use pagination or infinite scroll.

We will use one and hide/disable the other to reduce confusion.
If infinite scroll is enabled, pagination will be disabled.
