### ISSUE TITLE
ASM: cannot start a customer session with uppercase chars

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4830]
**Environment Details**
Spartacus: epic/asm-mvp-1
Browser: Chrome
Device: mac
Happens on: http://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/?asm=true

**Steps to Reproduce**
- Have an existing customer with all lowercase chars, eg kate.dev2@acme.com
- Login as asagent/12345
- In the customer field, type 'Kate.dev2@acme.com'

**Actual Result**
An error message that the user doesn't exist is displayed. 
However, if you login with 'Kate.dev2@acme.com' from the login page, it works.

**Expected Result**
It should work for asm too. 

<img width="997" alt="Screen Shot 2019-10-03 at 11 53 07 AM" src="https://user-images.githubusercontent.com/45409515/66143170-b42a2880-e5d4-11e9-9694-47613c05e52d.png">

**Comment by plabadie** [comment]
PR #4832

**Comment by KateChuen** [comment]
Tested on dev2. Works now. Can find a customer using either uppercase or lowercase chars.
