### ISSUE TITLE
Improve spartacus sample data release process

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#4842]
The Spartacus release process has some shortcomings that we should address:

- Release is a manual process.
- The release is not part of the Spartacus release process in spite of features requiring up to date sample data to work properly.
- The sample data is not versioned
- The sample data is distributes in a non-versioned zip file buried on the documentation site, where it is not obvious where to find it.

**Comment by plabadie** [comment]
One solution that was suggested is that the sampledata addon sources could be part of the Spartacus angular code repo (thus being integrated in all the branching going on there)

We still need to figure out the right way to release, ( automate it, where to host it, how to stamp a version )

**Comment by hackergil** [comment]
- Release for addon has been automated with release-it
- test data has been removed from initialization
- addon is now being distributed as part of github assets
- addon is now being versioned
