### ISSUE TITLE
Is it mandatory to use "AngularJS", or its flexible enough to change the JS framework?

### ISSUE THREAD

**Issue by OmarZeidan** [SAP/cloud-commerce-spartacus-storefront#485]

**Comment by Xymmer** [comment]
sorry it took so long to respond, but the goal is for developers to be able to use any framework they want, and import our published libraries. we aren't quite there yet but it's our way forward.

if you are forking the source code, you do need to use angular (v7 as of this writing). however we highly recommend people use our libraries instead.
