### ISSUE TITLE
reviews.impex seems missing for apparel [SImonLim]

### ISSUE THREAD

**Issue by psmul** [SAP/cloud-commerce-spartacus-storefront#4890]
reviews.impex files seems to be missing for BaseSite Apparel's:
https://github.tools.sap/cx-commerce/b2caccelerator/tree/develop/apparelstore/resources/apparelstore/import/sampledata/productCatalogs/apparelProductCatalog

We need to provide a file into folder to be sure that reviews are available for products for apparel.

**Comment by mirkosoft** [comment]
it's related to #4101

**Comment by WeizhengSap** [comment]
Apparel store doesn't have `reviews.impex`. But, customers can add review, right?

**Comment by mirkosoft** [comment]
Yes, customer can add review. This ticket is about having reviews for apparel store in sample data.

**Comment by giancorderoortiz** [comment]
Added to sample data: https://jira.hybris.com/browse/C3PO-1927

**Comment by mirkosoft** [comment]
closing as confirmed this is present in the sample data
