### ISSUE TITLE
Visuals for Group Skipping Links

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#4903]
Hi Manu,

As discussed in person, can you please provide mockups for the Group Skipping links. These are similar to action links since they trigger functionality on the same page as opposed to regular links that take you somewhere else. 

In [this link](https://wiki.hybris.com/display/spar/Spartacus+ACC-269+Group+Skipping) you will find more details about the intent of this requirement as well as some screenshots of similar features in other websites.

Please let me know if any doubts.

**Comment by Manurod2018** [comment]
You said we will have 3 links, can we display them at the same time like on the example above? 

![Skip Navigation – D](https://user-images.githubusercontent.com/37299626/66427893-ed9ed180-e9e2-11e9-98be-2db070f71eeb.png)

**Comment by developpeurweb** [comment]
@Manurod2018 they should show up one at the time as in the provided examples.

**Comment by kacperknapik** [comment]
mocks provided via Zeplin
