### ISSUE TITLE
Sonar. Storefinder. Array Sort Operation

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#4906]
**Sonarcloud URL:** 
https://sonarcloud.io/project/issues?fileUuids=AWhXcCIqgRG8__GgXCj-&id=sap_cloud-commerce-spartacus-storefront&open=AW0lNvEhKlufeJTiiE0T&resolved=false

**File:**  
projects/core/src/store-finder/store/effects/view-all-stores.effect.ts

**Severity:** 
Major

**Issues:** 
1

**Comment by Matejk00** [comment]
QA Steps:
Go to sonar and check if issue does not exist anymore: https://sonarcloud.io/project/issues?fileUuids=AWhXcCIqgRG8__GgXCj-&id=sap_cloud-commerce-spartacus-storefront&open=AW0lNvEhKlufeJTiiE0T&resolved=false

**Comment by psmul** [comment]
Fix confirmed, no more error visible in Sonar.
