### ISSUE TITLE
Sonar. CMS Components. Array Sort Operation

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#4907]
**Sonarcloud URL:**
https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&open=AW2rnQ2hW03GBz-nf6kP&resolved=false&types=BUG

**File:** 
projects/storefrontlib/src/cms-components/user/register/register.component.ts

**Severity:**
Major

**Issues:**
1

**Comment by Matejk00** [comment]
QA Steps:
Go to sonar and check if issue does not exist anymore: https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&open=AW2rnQ2hW03GBz-nf6kP&resolved=false&types=BUG

**Comment by psmul** [comment]
Fix confirmed, no more error visible in Sonar.
