### ISSUE TITLE
Sonar. Shipping Address. Array Sort Operation

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#4908]
**Sonar URL:** 
https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&open=AW2rnQvRW03GBz-nf6kO&resolved=false&types=BUG

**File:** 
 projects/.../components/shipping-address/address-form/address-form.component.ts

**Severity:**
Major

**Issues:**
1

**Comment by Matejk00** [comment]
QA Steps:
Go to sonar and check if issue does not exist anymore: https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&open=AW2rnQvRW03GBz-nf6kO&resolved=false&types=BUG

**Comment by psmul** [comment]
Fix confirmed, no more error visible in Sonar.
