### ISSUE TITLE
[dev2] SmartEdit cx-preview route

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#493]
The existing launch mechanism of storefront in SmartEdit fails short for the JS storefront, as it's launches the so-called /previewServlet. This route is not available in the JS storefront and is too java-ish. 

We could request a change for JS storefront, but we've came up with an easy approach

- Rename the current PREVIEW_TOKEN in CMSFilter from /previewServlet to /cx-preview
(this is something customer do not change, so it's not a change that will break during upgrades)
(we do not use /preview as this could be a real url for some customers)
- Redirect to the new /cx-preview url and provide the preview token (/cx-preview?cmsTicketId=123)
Introduce a dedicated route in the JS storefront for /cx-preview
- Use the route to add some logic (i.e. reading preview ticket token from query param and load the preview ticket details from the backend)
- Redirect to requested route, which is provided by the backend response

We can implement this in tickets:
Ticket 1: introduce preview route, using existing /previewServlet so that we can already launch the storefront in SmartEdit now. 
Ticket 2: rename the route to /cx-preview as soon as SmartEdit team renamed it
Ticket 3: listen to the cmsTicketId and load the preview ticket response from the new endpoint (whenever ready), and redirect to the route given in the ticket response.

**Comment by Xymmer** [comment]
To clarify:

Ticket 1: introduce preview route, using existing /previewServlet so that we can already launch the storefront in SmartEdit now.
>>>> this ticket
- Ticket 2: rename the route to /cx-preview as soon as SmartEdit team renamed it
>>>> new ticket
Ticket 3: listen to the cmsTicketId and load the preview ticket response from the new endpoint (whenever ready), and redirect to the route given in the ticket response.
>>>> probably #294 but Wei is checking with Tobias

**Comment by WeizhengSap** [comment]
![screen shot 2018-12-03 at 3 38 08 pm](https://user-images.githubusercontent.com/44440575/49400193-7d178c00-f711-11e8-8cb2-36505c592e44.png)

**Comment by WeizhengSap** [comment]
Get answer from Riry. We do not need Ticket 3. #294 is OK.

**Comment by tobi-or-not-tobi** [comment]
@WeizhengSap I'm unsure how that would work. SmartEdit would always launch the root (homepage) with the preview ticket id, but often the user expects to launch a specific deeplink. The preview response will provide the deeplink URL, which can be used in a redirect.

**Comment by WeizhengSap** [comment]
smartedit team added 'cx-preview' back. So, we need introduce the preview route, using '/cx-preview'.

**Comment by WeizhengSap** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/849

To code reviewer/tester:
1. update smartedit to latest version
2. check that: without this fix, smartedit will launch "not found" page; while with this fix, smartedit launch "homepage".
