### ISSUE TITLE
TypeScript 3.2 - implicit any suggestions and “infer from usage” fixes [need Ang7]

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#494]
https://blogs.msdn.microsoft.com/typescript/2018/11/29/announcing-typescript-3-2/#editing-improvements - TypeScript 3.2 introduces implicit `any` suggestions and “infer from usage” fixes: Implicit any suggestions and “infer from usage” fixes.

We should enable it once we upgrade to TS 3.2.

Before enabling this, check how it behaves whether it does anything? if so then maybe write a comment about it and then go for it.

**Comment by bgambocjaviniar** [comment]
PR #1385
