### ISSUE TITLE
[Mateusz Ostafil] Display some label when there is no reviews for product

### ISSUE THREAD

**Issue by psmul** [SAP/cloud-commerce-spartacus-storefront#4949]
To be discussed:
Id there is not a single review for product/variant we should display some label instead of grayed stars. Maybe something like: "No reviews yet".

**Comment by psmul** [comment]
Simple solution with label looks good for PLP:
![image](https://user-images.githubusercontent.com/10993491/69564894-22c3ab00-0fb4-11ea-9523-36b9a31cdebe.png)

However, I'm not fully convinced about PDP view and labels next to each other:
![image](https://user-images.githubusercontent.com/10993491/69564939-3bcc5c00-0fb4-11ea-9669-e45bff984bc4.png)

**Comment by psmul** [comment]
QA steps:

- go to any PLP page
- look for product without reviews

*Expected result:*
- on PLP there should be "No reviews yet" label visible for products without reviews
- on PDP there should be "No reviews yet" label visible and link "Show reviews" should be hidden

**Comment by Matejk00** [comment]
QA done, working as expected.
