### ISSUE TITLE
Submit review does not provide user feedback for submission result

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#4964]
After writing a review and clicking submit, the form is reset and closed and a submission request sent whether the data is valid or invalid. The server response should provide the user with feedback as to whether they need to edit the form to make a valid request or have the form closed and reset after the submission is succussful.

**Comment by KateChuen** [comment]
duplicate of #

**Comment by kacperknapik** [comment]
NOTE: work on products' reviews submitions in general - errors, global messages' translations, etc

**Comment by kacperknapik** [comment]
Will have to split the work into smaller tickets. Parking this ticket for now.

**Comment by kacperknapik** [comment]
This will be closed in #6742
