### ISSUE TITLE
[retest] Checkout: The Continue button remains disabled on the Address Details Page if the fields are prefilled

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#498]
## Environment Details

- Spartacus:  develop branch
- Browser: chrome Version 70.0.3538.110 (
- OS: MacOS 10.14.1
- Device: 
- Other environment details: 

## Expected Results
The "Continue" Button should be enabled if all the required fields are filled

## Observed Results

The "Continue" button remains disabled

## Steps to Reproduce
Prerequisite: Have performed a checkout previously where you saved your info on the browser.
Go to Homepage
Add a product to cart
Go to cart page
Proceed to checkout, use the same info as before, and choose to use the "prefilled" values.
Make sure all the required fields are not empty.

## Additional Information

![checkout-shippingpage-continuebutton](https://user-images.githubusercontent.com/45409515/49379218-9baf6000-f6dc-11e8-9259-6ce9e60eed24.png)

**Comment by developpeurweb** [comment]
This is not UX as there are no styling issues, although I tested it and it seems to work now.
The prefill in chrome doesn't seem to support elements from select fields, therefore al text inputs get prefilled but it isn't until a country gets chosen that it make the button active.

![Screen Shot 2019-03-25 at 1 53 27 PM](https://user-images.githubusercontent.com/15113219/54942715-0a236280-4f06-11e9-991e-255dff6bc586.png)

![Screen Shot 2019-03-25 at 1 53 44 PM](https://user-images.githubusercontent.com/15113219/54942702-04c61800-4f06-11e9-87aa-687c1bcb4072.png)

**Comment by KateChuen** [comment]
Yeah it's been fixed now. The "Continue" button becomes active now. Before it wasn't. Can close.
