### ISSUE TITLE
PDP: 1 Item is added to cart when manually change the Qty value to 0 or greater than max

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#499]
## Environment Details

- Spartacus: develop branch
- Browser: chrome Version 70.0.3538.110 (
- OS: MacOS 10.14.1
- Device:
- Other environment details:

## Expected Results
Maybe the "Add to cart" button should be disabled when the value is invalid?

## Observed Results

User is able to click on the "Add to cart" button, and 1 item is added to cart. 

## Steps to Reproduce
- Go to Homepage
- Go to PDP page, for eg, http://localhost:4200/product/779841
- In the Qty field, manually change it to 0
- Click "Add to cart"
- In the Qty field, manually change it to > than max
- Click "Add to cart"

## Additional Information

![pdp-qty0](https://user-images.githubusercontent.com/45409515/49379676-acaca100-f6dd-11e8-97b3-1552f1095bec.png)
![pdp-qtymorethanmax](https://user-images.githubusercontent.com/45409515/49379678-acaca100-f6dd-11e8-8972-2043876631b8.png)
![pdp-itemadded](https://user-images.githubusercontent.com/45409515/49379674-acaca100-f6dd-11e8-9c0f-36835053f814.png)

**Comment by KateChuen** [comment]
**Bug Triage:**
Proposed solution: When clicking on "Add to cart" button, validate the input. 
1) Display global message "Please correct the quantity"
2) Trigger the error message underneath the input

**Comment by Xymmer** [comment]
we're going a bit crazy with this :) 

i tested it, works fine, if i type 0 it shows 1.

except i can't press backspace now, which is weird. so i have to type 13 and then backspace over the 1 or select the 1 and type 3. can this be fixed?

**Comment by Xymmer** [comment]
looks good! if i change the value to 0, it resets 1.
if i set the value to higher than max, it changes to the max.
there is some ux improvement to be done here but this ticket passes.
tested on github.io server.

**Comment by bgambocjaviniar** [comment]
@Xymmer So the logic for this was done and taken by testing other e-commerce platform, as well as the accelerator. So when the user goes below the minimum number of stocks <= 0, then it will adjust the value to 1. Also, when it goes above the maximum > stocks, then it will set it to max. I believe this helps the user stay between the min and max of the product stocks
