### ISSUE TITLE
Add Payment Method Continue button should not be disabled

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#4994]

**Comment by Zeyber** [comment]
QA Steps: 
- Enable feature level 1.5 in app.module.ts
- Register a new user and login
- Go to checkout step payment details
- Confirm that Continue button on payment form is not disabled

**Comment by KateChuen** [comment]
Tested on dev10 on chrome(dekstop & mobile), safari & firefox.
The Continue button on the checkout payment form is now enabled. 

<img width="914" alt="Screen Shot 2019-11-20 at 3 35 56 PM" src="https://user-images.githubusercontent.com/45409515/69275999-8a8c8700-0bab-11ea-8547-30677c4ba94a.png">
