### ISSUE TITLE
Consent is not displayed as selected on registration page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5004]
**Environment Details**
Spartacus: epic/anonymous-consents branch
Browser: chrome
Device: mac
Happens on: http://dev-com-14.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
- On homepage, scroll down and click on "Consent Preferences"
- Click on Accept All.
- Click on Sign/Register link and click on "Register" 

**Actual Result**
On Registration page, the marketing consent is unchecked. 

**Expected Result**
Since we previously selected all 3 consents, the consent should be checked on registration page.

**Comment by znikola** [comment]
Please test again on the server, I deployed a fix.

**Comment by KateChuen** [comment]
It's fixed on dev14. Closing.
