### ISSUE TITLE
[BLOCKER]Consents are displayed as unchecked if logout from any form page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5005]
**Environment Details**
Spartacus: epic/anonymous-consents branch
Browser: chrome
Device: mac
Happens on: http://dev-com-14.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
- On homepage, scroll down and click on "Consent Preferences"
- Click on Accept All.
- Click on Sign/Register link and Register a new user.
- Login with that user. 
- Go to Consent Management Page -> All 3 consents are checked as expected.
- Logout

**Actual Result**
- _Minor Issue_: You will see the consents unchecked for 1 second, right before redirecting to the homepage. 
- _Big issue is_: If you login again after that, and go to Consent Management page, you will see the contents as unchecked (when they are checked in the backend). 
- If you try to check one of them, you will get an error msg that "it already exists" since it is already given in the backend. 

![Screen Shot 2019-10-11 at 2 29 34 PM](https://user-images.githubusercontent.com/45409515/66846148-5afcb600-ef3f-11e9-9298-85518a5d4eef.png)

**Comment by giancorderoortiz** [comment]
This is in fact a blocker issue. Consent management functionality cannot be used given consents cannot be granted nor withdrawn. Which is not in compliance with GDPR.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-10-15 at 8 01 17 PM](https://user-images.githubusercontent.com/46171897/66878163-98386680-ef86-11e9-9aa6-4cc19c9f9263.png)

**Comment by znikola** [comment]
Please test again on the server, I deployed a fix.

**Comment by KateChuen** [comment]
Tested on dev14. Works now!
