### ISSUE TITLE
Infinite loop issue in checkout step1 and step3 for new user

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#501]
For new registered users, who don't have addresses and payment infos. In checkout step 1 (add shipping addresses) and step 3 (add payment details), there will be infinite loop issue.

**Comment by marlass** [comment]
I created a new test account and tried to buy one product.
In checkout I didn't noticed any infinite loop.
No duplicate requests found.
Could you provide some more information about the issue?
![image](https://user-images.githubusercontent.com/6259079/49436452-79d7db00-f7b9-11e8-8bd9-d1ca30783565.png)

**Comment by plabadie** [comment]
PR: #556

**Comment by KateChuen** [comment]
Tested. Registered a bunch of new users, added new shipping & payment details. Also tested with registered users. Haven't encountered any infinite loop. Was able to checkout.
Created [ticket 669](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/669) for small issue found.
