### ISSUE TITLE
Move coupon interaction field [layout issue]

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5011]
For coupon feature, we'd like to move the interaction to the summary.

Currently you add coupons at bottom of the screen.
<img src='https://user-images.githubusercontent.com/4998145/66863564-46c9b080-ef61-11e9-83d4-cc589dae4b4d.png' width='500' />

And they appear in summary:
<img src='https://user-images.githubusercontent.com/4998145/66863550-3e717580-ef61-11e9-8b56-269d499ffabf.png' width='250' />

Example of new location (careful with mobile too):
![image](https://user-images.githubusercontent.com/4998145/66917195-eda65f00-efea-11e9-9eaa-11b3735771ed.png)

Note: 
- The added coupons appear above the field, with an X to remove them.
- The "Enter a coupon" link is removed
- Will require a change to sample data, talk to Wei for help.

**Comment by giancorderoortiz** [comment]
I don't see the coupon label and input field moved yet to the summary. 
Moving back to in-progress

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-10-28 at 9 38 44 AM](https://user-images.githubusercontent.com/46171897/67683067-09a0ed80-f967-11e9-8f3d-51179d0c3554.png)

**Comment by giancorderoortiz** [comment]
Rephrasing, I see the coupon label and input field in the summary column, but not necessarily adjacent vertically speaking to the summary information itself.

**Comment by Xymmer** [comment]
closing as this issue is captured in another ticket
