### ISSUE TITLE
'End Session' button

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5012]
In Spartacus ASM, currently to end a user session, you have to click My Account > Sign out.
We'd like to add a button to the ASM bar to make this easier.

- Talk to Patrick about how to trigger end session. See sprint review demo for what the behavior is after ending session (same as Sign Out).
- Talk to Miguel about the styling, you can do it if you want but Miguel has to review.

Desktop/Tablet horizontal/wide desktop:
![image](https://user-images.githubusercontent.com/4998145/66867157-b000f200-ef68-11e9-8bb8-712701fc1229.png)

Mobile/Tablet vertical:
<img src='https://user-images.githubusercontent.com/4998145/66867179-c0b16800-ef68-11e9-8d8e-82c541c6dfb8.png' width=300 />

**Comment by plabadie** [comment]
PR #5071
