### ISSUE TITLE
ASM search box - show list of matching names as you type

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5013]
![image](https://user-images.githubusercontent.com/4998145/66867290-f9e9d800-ef68-11e9-89ec-a9e6778b52b6.png)

Some ux examples have dates and dashes, what info is this, do we get it from api?
![image](https://user-images.githubusercontent.com/4998145/66868325-21da3b00-ef6b-11e9-9626-e8aa0c44f845.png)
Update: the API does not provide the data to display the dashes (last 4 digits of customer's default credit card number if any) and the date (account creation date).

Styling needs:
- The search results need to appear like in mockups, search suggestion style.
- The disabled “Start Session” button must be graded out.
- The spinner might need to be different.

**Comment by plabadie** [comment]
PR #5212

**Comment by plabadie** [comment]
For tests:
- The agent must chose a customer within the search results to start a customer emulation session.
- Until a customer is selected, the "start session" button is disabled.
- The default max result from the customer search is 20.  It can be changes via configuration in app.module by adding the asm.customeSearch. maxResults property:
```
      asm: {
        customeSearch: {
          maxResults: 20,
        },
      },

```

**Comment by KateChuen** [comment]
Tested on dev10 on all 3 browsers (chrome, safari, firefox).
The only issue found was when we change the config to 0, opened ticket #5306.
And one styling ticket: #5286.
