### ISSUE TITLE
Can minimize ASM UI 

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5014]
Little double-arrow thingy
![image](https://user-images.githubusercontent.com/4998145/66868034-8fd23280-ef6a-11e9-83cd-273b5f63e3b8.png)

Styling needs:
* The expand/collapse button.

**Comment by plabadie** [comment]
PR #5255

**Comment by KateChuen** [comment]
Tested on dev10, on all 3 browsers (chrome, firefox, safari)
Expand/collapse button now exists and is functional. 
Some styling issues found #5335
