### ISSUE TITLE
ASM Timeout and Reset

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5015]
Session timeout seen at top right, with reset button:

Desktop/Horizontal tablet/wide desktop:
![image](https://user-images.githubusercontent.com/4998145/66867348-15ed7980-ef69-11e9-84c9-e07dc540d232.png)

Mobile/vertical tablet:
<img src='https://user-images.githubusercontent.com/4998145/66867421-433a2780-ef69-11e9-9a10-8f82f6bf47e9.png' width=150 />

Customer session ends automatically when timeout reaches 0.
Customer rep clicks reset button to restart the timer.
Timer is configurable on backend I  think.

Styling needs:
- The main title "Assisted Service Mode" and "Session Timeout" should not display for small screen widths.
- The timer must be styled and played out as per the mockup.
- We have to find the proper icon for the reset button

**Comment by plabadie** [comment]
PR #5244

**Comment by plabadie** [comment]
For tests:

The logout button now appears during customer emulation as well.  The behaviour is the following:
- It will logout the cs agent.
- If there is a customer session in progress, it will also logout the customer

New Session Timer:
- the session timer starts counting down when the customer agent signs in.
- when the agent navigates to a new page, the timer resets.
- when the agent clicks the reset button, the timer resets.
- when the time is up, a logout is performed with a logic identical to the logout button (described above)
- the default timer delay is 600 seconds (10min)
- the default time delay can be configured in app.module via the proper: asm.sessionTimer. startingDelayInSeconds.

```
      asm: {
        sessionTimer: {
          startingDelayInSeconds: 600,
        },
      },

```

**Comment by KateChuen** [comment]
Tested on dev10 on chrome, safari & firefox.
Only issue found was the timer not being reset when we start a customer's session #5311.
Otherwise ok.
