### ISSUE TITLE
OccProductAdapter requests performance optimization

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#5024]
Optimize occ product adapter to take advantage of changes introduced in https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3666

**Comment by dunqan** [comment]
QA steps:
1. Verify if product payload for carousel is smaller than for full PDP
1. Navigating from carousel to PDP should result in slightly less payload size that entering PDP directly

**Comment by Matejk00** [comment]
QA done, performance optimization is working as expected.
