### ISSUE TITLE
Add TTL option to product scopes

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#5025]
Some product details data like price or stock have to be reloaded more frequently, to keep them fresh. 
We should be able to configure `TTL` for the specified scope, so it will be reloaded if is considered not fresh anymore.

**Comment by tobi-or-not-tobi** [comment]
We like to have this as a generic option for backend consumption, since customers have different requirements for the TTL. A classic example next to product stock and price is the update of the order status.
