### ISSUE TITLE
fix the site context e2e tests

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5027]
these tests are failing: 
regression/site-context/currency/currency-checkout-page.e2e-spec.ts
regression/site-context/language/language-checkout-page.e2e-spec.ts

Oct 30: 
See comments below. 
This now is expanded to make sure all site-context tests pass and are repeatable.

**Comment by Zeyber** [comment]
Which branch does to these errors occur on and what are the errors exactly? I ran both e2e tests a dozen times on fast and throttled networks and was not receiving any error.

**Comment by KateChuen** [comment]
On jenkins in the nightly builds. 
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/479/console

**Comment by Zeyber** [comment]
Closing as these tests passed in the next three builds.

**Comment by giancorderoortiz** [comment]
I agree. However, I must say, tests are not as repeatable as I had hoped. 
An R&R study should be done. @Xymmer 

![Screen Shot 2019-10-29 at 4 09 24 PM](https://user-images.githubusercontent.com/46171897/67805049-98e0fa80-fa66-11e9-9877-3836fcaabb6a.png)

**Comment by marlass** [comment]
Prepared a potential fix for this tests stability: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5278

If tests would be stable for one week after merging this we can close this issue ;)
