### ISSUE TITLE
fix the payment e2e tests

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5029]
these tests are failing:
mobile/my-account/payment-methods-mobile.e2e-spec.ts
regression/my-account/payment-methods.e2e-spec.ts

**Comment by psmul** [comment]
Couldn't reproduce e2t tests fails. Please provide enviroment or instructions.
Tested on Win10, Cypress with Electron.

**Comment by KateChuen** [comment]
It was happening on jenkins nightly builds. https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/479/console

**Comment by psmul** [comment]
I wasn't able to reproduce errors for **payment-methods-mobile.e2e-spec.ts**, however I've found issues in 2 others e2e files:
- regression/checkout-as-guest.e2e-spec.ts
- regression/store-finder.e2e-spec.ts
