### ISSUE TITLE
Reviews Page - More and Less buttons when there are 2 reviews

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#503]
## Environment Details

- Spartacus: develop branch
- Browser: chrome Version 70.0.3538.110 (
- OS: MacOS 10.14.1
- Device:
- Other environment details:

## Steps to Reproduce
- Go to a product with 2 reviews, for eg: http://localhost:4200/product/1934793
- Click on the "Write a review" on top
-- Nothing happens
-- Should redirect user to the "Review Form"
- Click on the "Reviews" Tab 
-- Scroll down, and click on "More"
--- Nothing more is displayed
![reviewmore](https://user-images.githubusercontent.com/45409515/49381576-3e1e1200-f6e2-11e8-9102-779e78b09d8b.png)

-- Click on "Less" 
--- Nothing less is displayed
![reviewless](https://user-images.githubusercontent.com/45409515/49381583-41b19900-f6e2-11e8-8ab9-fdb3ce257eca.png)

**Comment by Xymmer** [comment]
note that to test the reviews, if you submit a review, it has to be approved (doesn't say that in ui). under marketing in backoffice

**Comment by Xymmer** [comment]
@bgambocjaviniar , i added 2 reviews to kate's sample and it shows all 4 reviews. was it fixed to show all?

**Comment by Xymmer** [comment]
tested with jan30 lib rc, passed
but i'm creating tickets to do some improvements.
1. the link 'write a review' should be 'show reviews' and just show the tab without showing the 'write a review'
2. would love infinite scroll on the reviews or pagination
