### ISSUE TITLE
Add coupons to powertools and apparel sample data sections of spartacussampledataaddon

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5031]
Wei merged powertools to spartacussampledata recently, and KungFu team added coupons to electronics. The goal is to clone coupon changes to powertools.

Also, similar changes for apparel will likely be merged by Miro soon. Either in this ticket or in another ticket, add coupons to apparel data as well. Sync with Miro on timing as he still has to merge his changes.

**Comment by mazamcodes** [comment]
https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/28

**Comment by mazamcodes** [comment]
Added coupons impex to powertools store. Since apparel store was not merged yet, coupons impex to be added to apparel store in this ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5145

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by mazamcodes** [comment]
How to test:
Create a coupon and promotion first:
1. Open backoffice
2. Go to Marketing --> Coupon Management -> Coupons
3. Create a new single code coupon
4. Be sure to set it to active and Save
5. Go to Marketing -> Promotion Rules
6. Create a new rule
7. Go to Conditions & Actions
8. Drag coupon code to conditions and select the coupon just created
9. Drag percentage discount on cart to actions and enter 10% (this is just an example to test).
10. Publish the rule.

1. Open the powertools store
2. Add a product to cart
3. Go to cart page
4. You should see "Have a coupon?" under order totals in right column.
5. Enter the coupon code earlier and hit apply
6. The applied coupon should be displayed under the field with an X allowing to remove it.
