### ISSUE TITLE
Group Skipping

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#5048]
**Tab Skipper**

**Introduction**
Tab Skipping allows users to quickly navigate via keyboard to important areas of a page without having to navigate through each element making the ux more friendly and site navigation faster.

**Appearance**
![image](https://user-images.githubusercontent.com/11735817/67951024-00c04e00-fbeb-11e9-81fb-32b4fe36ba5b.png)

**Skipper Settings**
We can use a skipper config in module configurations as a way of adding Skipping to specified elements. Elements can be identified via slots and layouts.

```
    ConfigModule.withConfig(<CmsConfig>{
      	groupSkipper: {
			groupSkipperElements: [
				{
					type: GroupSkipperType.SLOT,
      				name: 'ExampleSlot',
      				title: 'groupSkipper.titles.main',
				},
				{
					type: GroupSkipperType.LAYOUT,
				    name: 'ExamplePageTemplate',
				    title: 'groupSkipper.titles.main',

				},
			]
		}
	}
```

**Skipper Options**
- type: string - PageSlot or PageLayout
- name: string - Element identifier
- title: string - Text translation key shown as the name of the component being skipped to

**Default Elements which will use Group Skipping**
We have default components with group skipping as it is standard practice for a11y in similar sites to skip to these areas via keyboard:
- Header
- Main (page-specific)
- Footer
- Product List
- Product Facets

**Adding to DOM**
Anchor tags are added to the top of the `body` in order to be the first accessible elements by pressing the `tab` key. Pressing `retun` while focused on these anchors will skip to the component on the page with the corresponding ID.

```
<cx-group-skipper>
	<a>Skip to Element 1</a>
	<a>Skip to Element 2</a>
	<a>Skip to Element 3</a>
</cx-group-skipper>
```

**Comment by kacperknapik** [comment]
![image](https://user-images.githubusercontent.com/22354613/67208318-9868b400-f415-11e9-86a4-18edcd34c1de.png)

NOTE: naming, flow, other elements can still change

**Comment by Zeyber** [comment]
QA Steps: 
- Load home page
- Press tab key
- Group skipper should appear with "Skip to Header"
- Press tab key two more times should reveal "... Main Content", "... Footer"
- Press tab one more time, Group skipper should disappear.
- Press shift + tab, Group skipper should reappear with "Skip to Footer" text
- Press return key, should scroll to bottom of page and group skipper disappears

**Comment by marlass** [comment]
Tested and tried to configure my own skip links.
✔️ Everything works as specified.

Docs are needed and config in issue description is a bit outdated.
