### ISSUE TITLE
getting error when there are no product references on the page

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5054]
Looks like we have an error on dev branch related to the product references

when there are no product references on the page, i'm getting this error:
ERROR TypeError: list is not iterable
which is caused by the LOAD_PRODUCT_REFERENCES_SUCCESS
I guess we need a check on whether the list is not null

**Comment by plabadie** [comment]
How to smoke test?

**Comment by plabadie** [comment]
How to smoke test?

Please add a unit test to lock down the fixed behaviour, thanks!

**Comment by KateChuen** [comment]
Tested with #4693. No errors when there's no product references on a pdp.
