### ISSUE TITLE
[Wait for #5079] Styling: Cursor focus on Consent Preferences

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5058]
**Environment Details**
Spartacus: epic/anonymous-consents branch
Browser: chrome
Device: mac
Happens on: http://dev-com-14.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
- On homepage, scroll down and place the cursor on "Consent Preferences"

**Actual Result**
- The cursor is not the right one. 

<img width="1425" alt="Screen Shot 2019-10-17 at 11 15 08 AM" src="https://user-images.githubusercontent.com/45409515/67023174-5a475980-f0d0-11e9-8ff9-c1edae2cf0df.png">

**Expected Result**
- The cursor should be a hand like this one:
<img width="1045" alt="Screen Shot 2019-10-17 at 11 20 31 AM" src="https://user-images.githubusercontent.com/45409515/67023167-57e4ff80-f0d0-11e9-85c9-6e69d5f2f772.png">

**Comment by znikola** [comment]
There's a plan to try and convert this footer into a CMS component. In case this is possible, this ticket can be closed, as the footer link styles will automatically applied to the Consent Preferences.

**Comment by znikola** [comment]
Fixed in #5079
