### ISSUE TITLE
Styling: toggle alignment on consent management page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5059]
**Environment Details**
Spartacus: epic/anonymous-consents branch
Browser: chrome
Device: mac
Happens on: http://dev-com-14.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
- Login
- Go to MyAccount -> Consent Management

**Actual Result**
- The toggles are not aligned properly with the text. I find them a bit too high. 

<img width="433" alt="Screen Shot 2019-10-17 at 11 13 30 AM" src="https://user-images.githubusercontent.com/45409515/67023528-f40f0680-f0d0-11e9-84f2-e405b2a4fe05.png">
<img width="637" alt="Screen Shot 2019-10-17 at 11 14 17 AM" src="https://user-images.githubusercontent.com/45409515/67023530-f40f0680-f0d0-11e9-93cf-cd59c9297a23.png">

**Comment by znikola** [comment]
We moved back to check-boxes
