### ISSUE TITLE
Small issues css and typos and others

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#508]
## Environment Details

- Spartacus: develop branch
- Browser: chrome Version 70.0.3538.110 (
- OS: MacOS 10.14.1
- Device:
- Other environment details:

## Steps to Reproduce

1. Changing the qty on cart page
- Add an item to cart. 
- Go to cart page
-- Change the qty of the item by typing something else in the box. 
--- The change is not reflected. If we cannot change the qty, maybe should not allow user to change it this way?
![qtyeditedcartpage](https://user-images.githubusercontent.com/45409515/49385840-4713e100-f6ec-11e8-92ca-83bd4da6d875.png)

2. The Qty box on PDP page
- Go to pdp page
-- Is it on purpose that the box is not enclosed completely?
![pdpqtybox](https://user-images.githubusercontent.com/45409515/49385816-3ebba600-f6ec-11e8-9d61-1d22c7ea63bf.png)

3. The Language & Currency arrows
- Click on the dropdown arrow next to the Lang and Currency. 
-- We have to click on the actual Lang and Currency for the dropdown menu to be displayed. 

4. Missing pages
- Some pages are missing, for eg:
-- the FAQ page
-- This product page: http://localhost:4200/Open-Catalogue/Cameras/Webcams/QuickCam-for-Notebooks-Pro/p/479742
--- maybe remove them? Or add an empty page for them?

5. Fix typo on missing page
- Should be Oops instead of Opps.
![missingpage](https://user-images.githubusercontent.com/45409515/49385779-31062080-f6ec-11e8-827d-a3b64466e98e.png)

**Comment by Xymmer** [comment]
Please create separate tickets for:
- 1
- 2,3 
- 4(2) product page
- 5 Opps (although I'm tempted to leave it :) )

Known issues, tickets exist, can close:
- 4(1) missing faq

**Comment by KateChuen** [comment]
Created tickets 512-515 for the issues. Closing this one.
