### ISSUE TITLE
Anonymous consents - Improve e2e tests

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#5081]
The existing e2e tests could be improved by covering more use-cases:
- add e2e that covers the required consent - both anonymous and on the registered consent management page. 
--> done

- We can also cover the case when the required consents are configured and the user tries to withdraw / withdraw all anonymous / withdraw all registered consents
--> done

- Cover filtering configuration property - configure some anonymous consent to not show on the consents management page and verify that.
--> done

- Configure another anonymous consent to be registered consent and test the whole again: is that consent present on the registration page? is it given once the user registers and logs in? can it be toggled on/off again?
--> don't think we need to test the whole thing again from the 'normal flow' to the 'config flow'. config flow for the required, changed consent, and hiding consents  and normal flow tests the whole flow like the implementation (don't need to do it twice) 

- Turn of `showLegalDescriptionInDialog` configuration property and verify that there's no legal message at the top of the dialog.
--> done

- We also might want to consider the test when the anonymous consents feature is turned off
--> don't think we need this

- Try to remove the 5s timeout and see if it works
--> cool

**Comment by bgambocjaviniar** [comment]
PR: GH-5216
