### ISSUE TITLE
Anonymous consents - create a common form component for both anonymous and registered consents

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#5082]
Ideally, we can try to create a common consent-form.component.ts and consent-form.component.html that can be used in both anonymous and registered consents.
The problem here could be templates, backwards compatibility and stylings.

If this is not possible, the second best option is to create a `consent-helper.ts` that can contain the common logic for both the registered and anonymous consent forms. As this is mainly going to be used in the form components (which are presentation components that don't inject services), it should have only static methods.

Tests should be moved to this common component.

The existing form component can just delegate the calls to the helper class.

**Comment by LTiger14** [comment]
This will be tested by #5104
