### ISSUE TITLE
Cannot create a branch on a fresh clone

### ISSUE THREAD

**Issue by corey-aloia** [SAP/cloud-commerce-spartacus-storefront#5095]
When using a fresh clone and running `git checkout -b my-b` I get: `warning: refname 'HEAD' is ambiguous`. When running `git show-ref` I can then see that there is a tag called 'HEAD' which is causing this. To resolve, I can run `git tag -d HEAD`

To reproduce, run `git clone https://github.com/SAP/cloud-commerce-spartacus-storefront.git`, and then `git checkout -b my-b`

I am running this on a Mac

**Comment by marlass** [comment]
We are aware of this problem, but it's hard to remove it from every existing spartacus clone and prevent everyone from pushing this tag once again to the repo, but we will try to do our best and remove it.

**Comment by marlass** [comment]
I think we finally solved the problem with the HEAD tag. Closing this ticket.
