### ISSUE TITLE
Product with 'force in stock' stock status is shown as out of stock

### ISSUE THREAD

**Issue by kate1zheng** [SAP/cloud-commerce-spartacus-storefront#5106]
## Environment Details

- Spartacus:  1.2
- Browser: Google Chrome Version 76.0.3809.132
- OS: MacOS jave version 10.14.6
- Device: laptop

## Steps to Reproduce
1. change the stock status as force in stock
![image](https://user-images.githubusercontent.com/43032959/67269748-d7683980-f4e9-11e9-8844-47f1aff8521f.png)
2. go to PDP for this product

## Observed Results
the product is shown as out of stock
![image](https://user-images.githubusercontent.com/43032959/67269800-f36bdb00-f4e9-11e9-8570-b65887fd9b25.png)

## Expected Results
should show 'available online' like on-premise

**Comment by kate1zheng** [comment]
when setting the stockstatus as 'force in stock', the response is:
"stock" : {
      "stockLevelStatus" : "inStock"
   },
when setting the stock status as 'not specified', the response is:
  "stock" : {
      "stockLevel" : 22,
      "stockLevelStatus" : "inStock"
   },

however, in add-to-cart component, the stock logic is
this.hasStock =
      product.stock &&
      product.stock.stockLevelStatus !== 'outOfStock' &&
      product.stock.stockLevel > 0;
it doesn't consider the situation 'force in stock'

**Comment by KateChuen** [comment]
Investigate if it's a spartacus issue or if we need to request an update in the api.

**Comment by josecervera** [comment]
+1
Besides, in SAP Commerce, if you don't associate any warehouse to the basestore, it will generate by default a stock with StockLevel == 0 (see de.hybris.platform.commercefacades.product.converters.populator.StockPopulator), so the condition on (product.stock.stockLevel > 0) fails.

**Comment by bgambocjaviniar** [comment]
Looks like it fixed:

QA: 

When changing the stocks, it takes a while before it updates its in the backend. Wait ~45s and refresh the product page or navigate to it if you closed it.

- Used 358639 product
- change available amount to 0
- change in stock status to force in stock
- in spartacus, it should be show in stock for that product

**Comment by KateChuen** [comment]
Tested it on dev10 with hybris-commerce-suite-1905.6.zip (and develop branch of spartacussampledataaddon and commercewebservicesdata).

It is working like you describe it. 

- Setting it to 'force in stock', then going back to PDP, I can see that the product is in stock.
I can add it to cart, and place an order. 
Sometimes it's just slow and you just have to wait a bit like Brian said... ~45s. 

![Screen Shot 2019-11-15 at 2 52 15 PM](https://user-images.githubusercontent.com/45409515/68971515-a8c34300-07b7-11ea-829e-7c5382ef5025.png)
