### ISSUE TITLE
Refactor ASM Main UI component.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#5117]
The main UI component is getting large.  Consider breaking it apart by creating one component for  "asm emulation" state

Styling need:
 We will add a component for the customer emulation state.  This will add a tag that will replace a styled div.  We need to make sure the style is properly "migrated" to the new tag.

**Comment by plabadie** [comment]
PR: #5223

**Comment by plabadie** [comment]
To test: Make sure there is no regression in the Asm UI in the state where a customer emulation is in process.

You should see the customer name and email + the "End Session" button.

**Comment by KateChuen** [comment]
Tested on dev10. Looks good.
