### ISSUE TITLE
Add return confirmation page in SPA

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#5119]
After clicking the button in "order return" page, customer should go to "order return confirmation" page.

In #5103, cms pages are added.

Check the wireframe in here: https://wiki.hybris.com/pages/viewpage.action?spaceKey=spar&title=Cancellations+Returns+UX+Summary

The `returnPrice` in `orderEntry` should be calculated in frontend.

In this page, there is "submit request" button. You only need to add a dummy button. The implementation of the button will be done in ticket #5121

**Comment by KateChuen** [comment]
Tested on dev10, on the epic branch, on chrome, firefox, safari.

And the total item price is being calculated correctly. 

<img width="851" alt="Screen Shot 201
9-12-02 at 2 40 51 PM" src="https://user-images.githubusercontent.com/45409515/69989623-fd81f000-1511-11ea-94ec-92bac088aa47.png">
