### ISSUE TITLE
Changing the qty on cart page is not reflected

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#512]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus: develop branch
- Browser: chrome Version 70.0.3538.110 (
- OS: MacOS 10.14.1
- Device:
- Other environment details:

## Steps to Reproduce
- Add an item to cart.
- Go to cart page
-- Change the qty of the item by typing something else in the box.
--- The change is not reflected. If we cannot change the qty, maybe should not allow user to change it this way?
![qtyeditedcartpage](https://user-images.githubusercontent.com/45409515/49392330-1cca1f80-f6fc-11e8-9e40-9a16ea4f42f6.png)

**Comment by KateChuen** [comment]
**Bug Triage**
The +- buttons are working. But the input doesn't. The cart is not updated when we lose focus. Check on safari also, to make sure it works.

**Comment by marlass** [comment]
Changes triggers recalculation. Found some issues with a11y. Created issue for this: #994
