### ISSUE TITLE
Submit return request

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#5121]
Implement this in OCC, store and facades layer. 

A dummy button was added in #5119, you need to make sure that clicking this button, submit request works. Customer will be redirect to "order return request details" page. The "order return request details" page will be added in #5477. So, this "redirect" will be refactored in #5477.

**Comment by KateChuen** [comment]
Tested on dev10. Tested on the epic branch, on chrome, safari & firefox. 

The 'submit' button works. But user is redirected to the "Order History" page instead. 
@WeizhengSap to confirm this behavior please?

**Comment by KateChuen** [comment]
Wei says it's being redirected to Order History now because the "order return request details" page does not exist yet. When this page will be created, then it will be redirected there.

**Comment by KateChuen** [comment]
Now that the order return request details page exists, it goes there after submitting a return request.
