### ISSUE TITLE
Extendability of multi-provided classes

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#5129]
Currenlty the multi-provided classes like normalizers or http interceptors are often provided with the option `useClass`, which hardcodes the class reference and doesn't allow for any extendability, nor for switching off those classes.

To solve those issues, we should simply provide those tokens with the option `useExisting` instead of `useClass` and and mark the class with `providedIn: 'root'` in the `@Injectable` decorator.

### Example:

1. file `product-occ.module.ts`

    Instead of:
    ```typescript
   {
      provide: PRODUCT_NORMALIZER,
      useClass: ProductNameNormalizer,
      multi: true,
    },
    ```
    let's do:
    ```typescript
    {
      provide: PRODUCT_NORMALIZER,
      useExisting: ProductNameNormalizer,
      multi: true,
    },
    ```
and

2. file `product-name.normalizer.ts`

    Instead of:
    ```typescript
    @Injectable()
    export class ProductNameNormalizer ...
    ```
    let's do:
    ```typescript
    @Injectable({ providedIn: 'root' })
    export class ProductNameNormalizer ...
    ```

---
Link to the original discussion in the slack: https://spartacus-storefront.slack.com/archives/CD16V16FR/p1568635837012900

**Comment by mazamcodes** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5374

**Comment by mazamcodes** [comment]
Closed #5374 as the change should only apply to case where multiple providers may be present. Opened https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5380.

**Comment by mazamcodes** [comment]
QA: This is not really testable by QA other than that there should be no negative impact to the storefront and all the tests should pass.

**Comment by KateChuen** [comment]
Running the e2e tests on dev10 had many failures. 
Therefore did some quick smoke tests manually. Looks ok.
the one e2e test that i tried manually because it failed on cypress is the consignment tracking, but i think it's just data issue.
