### ISSUE TITLE
[retest] Css issues: Qty box on pdp and Lang&Currency Arrows

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#513]
## Environment Details

- Spartacus: develop branch
- Browser: chrome Version 70.0.3538.110 (
- OS: MacOS 10.14.1
- Device:
- Other environment details:

## Steps to Reproduce
1. The Qty box on PDP page
- Go to pdp page
-- Is it on purpose that the box is not enclosed completely?
![pdpqtybox](https://user-images.githubusercontent.com/45409515/49392454-7c282f80-f6fc-11e8-9f03-df8249213062.png)

2. Inconsistency in the Qty box on cart page (probably related to the above issue on pdp page)
<img width="1045" alt="qtyboxcartpage" src="https://user-images.githubusercontent.com/45409515/53426021-3229af80-39b4-11e9-891e-14e0c4f506e6.png">

3. The Language & Currency arrows
- Click on the dropdown arrow next to the Lang and Currency.
-- We have to click on the actual Lang and Currency for the dropdown menu to be displayed.

**Comment by mikelMHybris** [comment]
I could not recreate any of the issues.

**Comment by KateChuen** [comment]
1&2 got fixed by ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/887 I think
3 seems to no longer be an issue. 
Closing this ticket.
