### ISSUE TITLE
Update sampledataaddon/apparel-uk to reflect latest changes in electronics and powertools

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#5147]
This ticket is about reviewing all changes done over last few weeks in sampledataaddon (electronics/powertools: ASM, coupons, wording, etc).
After review (I already did it partially) changes should be applied into apparel-uk.

**Comment by mirkosoft** [comment]
This has been done mostly during the #3202, missings are test data for:
[] anonymous consent tracking
[] coupons

**Comment by hackergil** [comment]
I think we should reconsider our approach for this. Our e2e tests are very coupled and targeted to the electronics catalog. If we want to do the same with apparel, we’d have to replicate (and maintain) a lot of the test data for apparel. Let's discuss with the leads.

**Comment by Xymmer** [comment]
agreed let's try to reduce our work here. we need to prove it works but not necessarily have them working in every store.
