### ISSUE TITLE
(for intern) Minor typos on storefront

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#515]
Fix typo:
- on missing page
-- Should be Oops instead of Opps.
![missingpage](https://user-images.githubusercontent.com/45409515/49392636-01134900-f6fd-11e8-95cb-854c7ca82af0.png)

- on checkout pages when there's only 1 item
-- Maybe write item(s)? 
![checkout1item](https://user-images.githubusercontent.com/45409515/49392653-12f4ec00-f6fd-11e8-8337-0b1dec77a6bc.png)

**Comment by KateChuen** [comment]
**Bug Triage**
Proposed solution: Can just change the text to only "Checkout". No need to put number of items.

**Comment by Xymmer** [comment]
looks like we say 1 item and 2 items, passing (tested on 17)
