### ISSUE TITLE
Fix coupons e2e tests

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#5154]
Most of the e2e tests for coupons (mobile and regression) were disabled, because of changes in UI.
We should fix and reenable them.

**Comment by mazamcodes** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5178

**Comment by giancorderoortiz** [comment]
Tests successful

![Screen Shot 2019-11-01 at 11 35 53 AM](https://user-images.githubusercontent.com/46171897/68036482-26596000-fc9c-11e9-917b-3a56ccc9e02e.png)
![Screen Shot 2019-11-01 at 11 38 26 AM](https://user-images.githubusercontent.com/46171897/68036484-26596000-fc9c-11e9-9cb9-aada32adaa02.png)
