### ISSUE TITLE
Input elements not growing to 100% because they are wrapped inside labels

### ISSUE THREAD

**Issue by Sarikai** [SAP/cloud-commerce-spartacus-storefront#5156]
## Environment Details

- Spartacus:
    "@spartacus/assets": "~1.2.0-next.0",
    "@spartacus/core": "~1.2.0-next.0",
    "@spartacus/schematics": "^0.1.0-beta.1",
    "@spartacus/storefront": "~1.2.0-next.0",
    "@spartacus/styles": "~1.2.0-next.0",
- Browser: Google Chrome Version 77.0.3865.120 (Official Build) (64-bit) 
- OS: macOS
- Device: MacBook Pro (Mid 2015)
- Other environment details:
    "@angular/core": "~8.2.7",

I am currently working on a separate theme, so i am not including all the custom element styles that come with spartacus. I am using customised bootstrap input elements styles and they don't grow to fill all the available space.
<img width="654" alt="Screen Shot 2019-10-24 at 17 23 12" src="https://user-images.githubusercontent.com/6187541/67501305-585b3880-f684-11e9-9685-4afa30a66643.png">

The reason for this seems to be that bootstrap doesn't like these input elements to be wrapped inside label elements and bootstrap does advise to keep these separated in their [official documentation](https://getbootstrap.com/docs/4.3/components/input-group/).
One example is the login-form component [login-form component](https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/storefrontlib/src/cms-components/user/login-form/login-form.component.html).

Including additional stylings from spartacus will break my designs so this is not an option.
I did only customise the bootstrap components with scss variables. No fancy additional styles added.

A solution would be to move all labels before their respective input field instead of wrapping them around.

**Comment by kacperknapik** [comment]
Personally I'm not a big fan of changing input-label implementation. Currently I'm working on accessibility topic within Spartacus, so I do like this solution (input inside label). Long story short, you don't have to think about a field ID, you just put the input inside the label and both are automagically connected. Additionally we are not polluting window object if we don't use IDs (elements' IDs are accessible in window object).

W3C is actually letting us use this solution (bottom of the section): https://www.w3.org/TR/html401/interact/forms.html#edef-LABEL

Please check the following link for some help about inputs and labels while working with Bootstrap: https://stackoverflow.com/a/43790094

**Comment by Sarikai** [comment]
The stackoverflow solutions is looking good. Will you apply this solution to the spartacus components?
