### ISSUE TITLE
Wish List master ticket

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#5187]
This is the master ticket for creating a wish list in Spartacus.

Nb. To be updated as new tickets are created.

**Comment by LTiger14** [comment]
The biggest issue concerning this feature is that there are no backend APIs yet for this. An alternative would be to used the saved cart APIs but it would not be best as it would add complexity to Spartacus and intentionally misuse some APIs.

**Comment by tobi-or-not-tobi** [comment]
As long as we do not have a backend available for the wishlist, we should not misuse other APIs to bring this feature to live. What we can do in the meantime:
1. create the UI portion for the wish list
2. build the storage for anonymous wish list (local or session storage) 
3. design the APIs (yaml) for the backend, so that customers, consultants or the product team can build the feature.

**Comment by tobi-or-not-tobi** [comment]
We need to do some requirements gathering here to better understand if we can reuse the saved cart API at all. 

To bring a few requirements to the table:
- we should have an anonymous WishList
- we should allow for a single non-labelled wish list by default
- we should merge an anonymous wish list with a stored WishList
- we should allow for multiple labelled WishLists.
- we should allow for additional information on a WishList item, as some experiences require you do provide some information before loading items on a PLP or PDP (i.e. in travel or insurance, some information is added to configure the right product)
- we must allow for adding an WishList item to the cart
- we could allow for adding a full WishList to the cart
- we could allow for a checkout from WishList without going to the checkout

**Comment by LTiger14** [comment]
Upon further investigation into the requirements that were brought forth for the wish list and with regards to the current and planned capabilities of the saved cart APIs this is what I found.

Requirements that can be met with current APIs:

- Create a default wish list
- Add an entry to wish list
- Remove a product to the wish list
- View items from wish list
  - Information on stock & merchantability (purchasable) is provided
- Transfer to active cart
- Add all to cart
- Multiple wish lists
- Wish list naming & description (current set of APIs require a naming convention to distinguish the wish list)
- Go to checkout from wish list

Short comings:

- Creating a saved cart is a two step process. Create empty cart -> save cart (ticket RAY-466 will fix it)
- So far the only way to distinguish the wish list is using a naming convention (ticket RAY-466)
- Out of stock product CANNOT be added to the wish list
- CANNOT add products not sold separately  (might not be an issue?)
- Anonymous wish list: it is possible to create an anonymous cart but there is an error when saving it. Swagger hints at it being possible but it returns an error ("Cart identifier: cart code for logged in user, cart guid for anonymous user, ‘current’ for the last modified cart")
<img width="698" alt="Screen Shot 2019-10-29 at 2 52 06 PM" src="https://user-images.githubusercontent.com/10605724/67799425-b3fa3d00-fa5b-11e9-8354-5b44a9dff8ed.png">
In the mean time the anonymous wish list could use local storage with a spartacus based merging mechanism
- Carts seem to have an expiration date when saved. Is this configurable? what happens when the time expires? 
<img width="402" alt="Screen Shot 2019-10-29 at 12 14 33 PM" src="https://user-images.githubusercontent.com/10605724/67799599-0b98a880-fa5c-11e9-9269-78d06f25bb8c.png">
