### ISSUE TITLE
Apply coupon to anonymous cart returns Cart not found

### ISSUE THREAD

**Issue by mazamcodes** [SAP/cloud-commerce-spartacus-storefront#5189]
## Environment Details

- Spartacus: 1.3.x
- Browser: Chrome 78

## Setup
in Backoffice, enable and publish promotion rule "coupon_code_fixed_discount".
Make sure coupon SUMMER69's validity and redemptions are greater than 0, and not already used.

## Steps to Reproduce
Go to spa storefront
Ensure you are not signed in
Add product to cart
Go to Cart page
Enter coupon code and click Apply
Note the error Cart not found and that the coupon does not apply.

## Observed Results

Cart not found message banner is shown and the coupon is not added to Cart

## Expected Results
Coupon should be applied, giving success message and Cart updated with Coupon and totals recalculated.

**Comment by mazamcodes** [comment]
This layout issue is another breaking css change that requires adding some styles to the container to address laying out items one after the either (at the start of the component). Created https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5193 to track this.

**Comment by giancorderoortiz** [comment]
I see the fix. 
Able to checkout as guest user. 
![Screen Shot 2019-11-01 at 9 27 47 AM](https://user-images.githubusercontent.com/46171897/68034205-a9c48280-fc97-11e9-9719-088316528940.png)
