### ISSUE TITLE
Coupons Applied/Removed Messages Not Removed After x Seconds

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5190]
**Setup:**
in Backoffice, enable and publish promotion rule "coupon_code_fixed_discount".
Make sure coupon SUMMER69's validity and redemptions are greater than 0, and not already used.

**Steps to Reproduce:** 

1. Navigate to Spartacus storefront. 
2. Login as registered user. 
2. Add products to cart 
3. Navigate to cart page. 
4. Apply SUMMER69 coupon. 
5. Remove SUMMER 69 coupon. 

**Expected Results:** 
4. Applied coupon message appears for a few seconds, then disappears. 
5. Removed coupon message appears for a few seconds, then disappears. 
Note: Colours should be different here. Removing a coupon should be yellow/red because it's increasing the overall total to pay. 

**Actual Results:** 
4. Applied coupon message appears and remains until manually closed. 
5. Same as above.

**Comment by psmul** [comment]
@giancorderoortiz sadly, I wasn't able to reproduce those errors. Sometimes it might feel as stuck, however, it's just default config which keeps global messages alive for 3-7 seconds (depends on the type of message)

Env: dev-17, branch: develop

**Comment by KateChuen** [comment]
Tested on dev10. Now the messages disappear after a few seconds. And the colors are different when we add and remove a coupon. 


![Screen Shot 2019-11-07 at 9 58 01 AM (2)](https://user-images.githubusercontent.com/45409515/68402098-cbff4a00-0148-11ea-9e57-63d4425c935d.png)


![Screen Shot 2019-11-07 at 9 52 31 AM (2)](https://user-images.githubusercontent.com/45409515/68402097-cbff4a00-0148-11ea-8c5f-485f23bdf71e.png)
