### ISSUE TITLE
Applied Coupons Don't Appear Below Order Summary During Checkout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5191]
**Setup:** 
In Backoffice, enable and publish promotion rule "coupon_code_fixed_discount".
Make sure coupon SUMMER69's validity and redemptions are greater than 0, and not already used.

**Steps to Reproduce:** 
1. Navigate to Spartacus storefront.
2. Add items to cart.
3. In cart page, add coupon "SUMMER69".
4. Proceed to checkout.
5. Stop at shipping address step.

**Expected Result:** 
5. View applied coupon information below order summary. Discounts are clearly visible. 

**Actual Result:** 
5. Applied coupon information is not available.

**Comment by giancorderoortiz** [comment]
Old accelerator: 

![old-acc-ship-coupon](https://user-images.githubusercontent.com/46171897/67707991-d6278880-f991-11e9-97f6-cbe949c2ac62.png)

**Comment by giancorderoortiz** [comment]
Spartacus: 

![spa-checkout-no-coupons](https://user-images.githubusercontent.com/46171897/67708211-2272c880-f992-11e9-8357-cbb05b17c403.png)

**Comment by giancorderoortiz** [comment]
Same is true for checkout steps: Delivery Mode, Payment Details and Review Order.  (!)

**Comment by giancorderoortiz** [comment]
Old accelerator order review page: 
![old-acc-review](https://user-images.githubusercontent.com/46171897/67708609-cb212800-f992-11e9-9c09-125a3a842897.png)

**Comment by giancorderoortiz** [comment]
Spartacus order review Page: 
![spartacus-order-review](https://user-images.githubusercontent.com/46171897/67708797-25ba8400-f993-11e9-8b12-4a35eac879e1.png)

**Comment by giancorderoortiz** [comment]
Order confirmation page also doesn't show applied coupons.

**Comment by psmul** [comment]
@giancorderoortiz 
Fixed in #5154, please re-check with newest develop

**Comment by giancorderoortiz** [comment]
Right, I see the fix. 
But the layout is not ideal. Given the necessity of releasing this feature, we can use it as is. 
However, there is room for improvement as far as the layout and/or spacing of coupons and/or promotions information.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-10-31 at 3 46 49 PM](https://user-images.githubusercontent.com/46171897/68024868-b76f0d80-fc81-11e9-85b1-6cd99dd326fc.png)

**Comment by giancorderoortiz** [comment]
Created ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5252 for stying improvements
