### ISSUE TITLE
Cart page summary and coupon should render from start of column [depends on #5159]

### ISSUE THREAD

**Issue by mazamcodes** [SAP/cloud-commerce-spartacus-storefront#5193]
Depends on #5159

## Environment Details

- Spartacus:  1.3.x
- Browser: Chrome 78

## Steps to Reproduce
Visit spa storefront
Add many items (5+) to Cart
View Cart page
Notice that coupons and summary have empty white space separating them.

## Observed Results

Extra spacing between summary and coupon in center of right column.

## Expected Results
Coupon should be immediately beneath summary.
![image](https://user-images.githubusercontent.com/39602213/67709445-3232e280-f97b-11e9-84c7-d28fbc4b8603.png)

**Comment by mazamcodes** [comment]
This has been addressed as a result of changes Tobias made this morning and by enabling the calydon theme which applies the correct flexbox styles to adjust flow.

![Screen Shot 2019-11-01 at 1 19 18 PM](https://user-images.githubusercontent.com/39602213/68053892-4ee85680-fcaa-11e9-9d4f-c789489a4167.png)

**Comment by mazamcodes** [comment]
Also added a few fixes in https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5259

**Comment by KateChuen** [comment]
Tested on dev10. 
It's fixed now. 

![Screen Shot 2019-11-07 at 2 57 28 PM](https://user-images.githubusercontent.com/45409515/68423050-59559500-016f-11ea-8f07-ffbe13bf93f9.png)
