### ISSUE TITLE
feature flag the coupon label that appears in summary

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5198]
Stan requests: Adding the little label in the order summary html is technically a breaking change. 
Add *cxFeatureLevel='1.3' directive to that label to be on a safe side

**Comment by psmul** [comment]
Will be done in related issue #5191

**Comment by psmul** [comment]
QA steps:
1. Change features level to 1.2

Expected result:
Coupons labels shouldn't appear.

**Comment by KateChuen** [comment]
Tested on dev10. 
With feature flag set to 1.2, we see the coupon input field, and can apply coupons. We do not see the 'applied coupon' label as intended. 
Proceeding through checkout removes the coupon, and there's no more coupon related label. 
And confirmed that on the order review page, the 'applied coupon' label is not displayed.
<img width="1172" alt="Screen Shot 2019-11-15 at 9 02 26 AM" src="https://user-images.githubusercontent.com/45409515/68950147-93372480-0789-11ea-8396-f4139bb34082.png">
<img width="1030" alt="Screen Shot 2019-11-15 at 9 03 03 AM" src="https://user-images.githubusercontent.com/45409515/68950148-93372480-0789-11ea-930c-cbb452237602.png">



With feature flag=1.3, we can see the 'applied coupon' label on the cart page, and all the checkout pages, and the coupons are applied.

<img width="1006" alt="Screen Shot 2019-11-15 at 9 08 48 AM" src="https://user-images.githubusercontent.com/45409515/68950162-98946f00-0789-11ea-9dd3-7f337636d84c.png">
<img width="1055" alt="Screen Shot 2019-11-15 at 9 09 07 AM" src="https://user-images.githubusercontent.com/45409515/68950163-98946f00-0789-11ea-8271-e9d95aa2b71a.png">
