### ISSUE TITLE
Nik|Patrick: Big contribution guidelines review

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#52]
Bill created CONTRIBUTING.md for early October; Wei did a preliminary review (see SPA-1367) and I made updates. 

We need all developers to study and provide feedback to ensure the process reflect our working model and improves efficiency.

- [x] Wei
- [x] Gil
- [ ] Nik
- [x] Patrick
- [x] Louis
- [x] Kate

**Comment by hackergil** [comment]
Pull request #420

**Comment by plabadie** [comment]
Section "How We Process Issues"

This part isn't clear for me: "The release that contains the fix will be noted in the comments and the release changelog."
