### ISSUE TITLE
Reviews stars overlaps product title on the PLP/SRP

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#5205]
So part of the title link is not clickable:
![image](https://user-images.githubusercontent.com/788092/67768984-ee5fdc00-fa53-11e9-9f0d-24d11a34575a.png)

**Comment by KateChuen** [comment]
This is fixed in ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3577
You just need to have theme calydon enabled.
