### ISSUE TITLE
PageLayoutHandler is not consistent 

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#5221]
Hi,
I am overriding CartPageLayoutHandler. I have written my CustomCartPageLayoutHandler (copy of CartPageLayoutHandler). Now in app.module used it instead of default handler as 
```
{
      provide: CartPageLayoutHandler,
      useClass: CustomCartPageLayoutHandler
    }

```
but still somehow CartPageLayoutHandler also getting triggered, as the slots which my CustomHandler receive are already filtered. I also tried to override CartComponentModule and use my class for page_layout_handler.
``` 
providers: [
    {
      provide: PAGE_LAYOUT_HANDLER,
      useClass: CustomCartPageLayoutHandler,
      multi: true,
    }
  ],
```
Even like this, I guess `CartPageLayoutHandler` is still called, as slots are filtered.

(Slots are filtered mean, EmptyCartMiddleContent is not present if cart not empty, but PageLayoutService have called handle method with this slot, which mean somehow in between this slot has been removed. Which can only done by default CartPageL.Handler).

## Environment Details

- Spartacus:  1.2.1
- Browser: chrome

## Steps to Reproduce
Try to override/replace CartPageLayoutHandler with your customHandler and debug when `cart.totalItems` are checked

## Expected Results
Should be possible to replace/override CartPageLayoutHandler sothat all slots 'TopContent', 'CenterRightContentSlot', 'EmptyCartMiddleContent' can be received in handle method

## Offer to Fix
NO

## Additional Information
Target is to render 'TopContent'  and not to render 'EmptyCartMiddleContent' when cart is Empty. (Because my cart have quick add functionality).

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- override the `CartPageLayoutHandler`
- ensure the ootb `CartPageLayoutHandler` isn't used anymore
