### ISSUE TITLE
[wait for 250 move to core] Type safety second pass master ticket

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#523]
Depends on #250 and all of its `move * module to core lib` tickets.

Focus on the following:
* Types in test files - test files have a low type-safety coverage
* Change `any` to a type, i.e. in `projects/core/src/auth/store/selectors/user-token.selectors.ts`
* Add types to `*Config` constants, i.e. `MockAuthConfig` in `projects/core/src/auth/services/client-authentication/client-authentication-token.service.spec.ts`
* In test, instead of `useValue` strive to `useClass` as it brings more type safe syntax
* Check for method return types. If the method doesn't return a value, use `void`
* Add types to store actions `payload` parameter. Consult the swagger docs when not sure which type to use.
  *  After adjusting actions, adjust corresponding test files as well
  *  Note: there are some spots where `any` can't be avoided, which is usually the case with error actions
* Double check are the cms components done in a generic way (using `<T extends ...> syntax)
* Do a general pass on all module's files

As we've now splitted modules across the libs, check module's files in both `core` and `storefrontlib` projects.

**Comment by Xymmer** [comment]
this was a placeholder, we can close it now.
