### ISSUE TITLE
Searchbox 'transparent/clear' black overlay not taking full height

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#5258]
## Steps to Reproduce

type anything on the searchbox, and have the suggestions trigger

## Observed Results

the 'transparent/black' overlay is not taking the full height. When you scroll, you will see it stops at 'x' height.

## Expected Results

Overlay background should take the full page

## Offer to Fix

remove the absolute positioning and the positioning for left and right in cx-storefront:before

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- use the searchbox
- ensure that you can scroll the page while the overlay with search-as-you-type results are open
- ensure that the overlay covers the full page while you scroll
