### ISSUE TITLE
ASM does not handle standard customer sessions

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#5283]
ASM doesn’t not handle the case where and ASM agent is authenticated + a regular customer session is in progress.

To repro:
- Sign in asm as a customer support agent.
- Sign in the storefront as a regular customer using a username and password in the storefront login form.

Then:
- Observe what the Asm UI displays the same thing as when an emulation session is in progress.
- Observe that when the agent logs out, the standard customer session is also terminated.

ASM can handle the case by:
* Instead of the UI that is displayed during customer emulation, display a message that a regular customer session is in progress.
* In the case of a regular customer session, when the agent logs out, only log out the agent, not the regular customer session.

**Comment by plabadie** [comment]
PR #5284

**Comment by plabadie** [comment]
To test:

Case 1: Emulation
- Sign in asm as a customer support agent.
- Start a customer emulation session

Then:
- Observe that the Asm UI displays the name and email of the emulated customer.
- Observer that when the agent signs out, the emulated customer session is also terminated.

Case 2: Standard customer session
- Sign in asm as a customer support agent.
- Sign in the storefront as a regular customer using a username and password in the storefront login form.

Then:
- Observe that the Asm UI displays a message that the customer has to sign out for the agent to use asm.
- Observer that when the agent signs out, only the csagent is signed out.

**Comment by KateChuen** [comment]
Tested on dev10. 
Verified on all 3 browsers (chrome, firefox, safari). 
- agent logs in, starts customer session, agent signs out, the customer's session is also ended.
- agent logs in, starts customer session, end customer session still works.
- agent signs in, customer signs in through login form, agent signs out, the customer is still signed in.
- customer signs in through login form, agent signs in, agent signs out, customer is still signed in.
- agent signs in, customer signs in through login form, customer signs out through myaccount, agent starts another customer's session, agent signs out, customer's session is also ended.

Also verified on mobile, it's ok. the spacing is just a bit too wide, but it's very unlikely that a user will use asm on a mobile. 

<img width="417" alt="Screen Shot 2019-11-12 at 1 31 00 PM" src="https://user-images.githubusercontent.com/45409515/68699895-f2125900-0551-11ea-8133-ff726af65749.png">
<img width="417" alt="Screen Shot 2019-11-12 at 1 31 31 PM" src="https://user-images.githubusercontent.com/45409515/68699897-f2125900-0551-11ea-9ef3-7791ae557bdd.png">
