### ISSUE TITLE
Add wish list CMS related components to apparel-uk

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#5285]
Some new CMS was added to the spartacussampledataaddon for powertools and electronics in #5239. This issue is to add it to apparel-uk. (only uk as de is not done)

PR where CMS items were added: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/33

**Comment by hackergil** [comment]
PR here: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/35
