### ISSUE TITLE
Enable multisite in schematics

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#5300]
Now to enable auto-config, customer needs just to omit the config for `context.baseSite` (thanks to https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1810).
At the same time it's recommended not to have any `context` config, because it will be overwritten with the one from backend.
So we need a way to omit producing config for `context.baseSite` in schematics - just to enable auto config of the site.

**Comment by psmul** [comment]
QA steps: 
- build local schematics pack
- use schematics pack on fresh angular app without defining baseSite

Expected result:
Schematics should apply Spartacus adjustments & omit context property in Storefront configuration
