### ISSUE TITLE
asm: the value 0 isn't sent in the customer search request

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5306]
**Environment Details**
Spartacus: develop branch
Browser: Safari
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/?asm=true

**Steps to Reproduce**
- Add this config in your appmodule
`asm: {`
      ` customeSearch: {`
     `    maxResults: 0,`
     `  },`
 `    },`

- Login as an agent (asagent/123456)
- Start typing a customer's email address to get a search result, for eg, 'cus'

**Actual Result**
The value isn't sent in the request. 
`https://dev-com-10.accdemo.b2c.ydev.hybris.com:9002/assistedservicewebservices/customers/search?baseSite=electronics-spa&query=kate`

<img width="1431" alt="Screen Shot 2019-11-05 at 3 28 21 PM" src="https://user-images.githubusercontent.com/45409515/68306513-ace4b780-0077-11ea-8431-393278cf88a0.png">

**Expected Result**
The value should be sent in the request, and should let the backend handle it. 
`https://dev-com-10.accdemo.b2c.ydev.hybris.com:9002/assistedservicewebservices/customers/search?baseSite=electronics-spa&query=kate&pageSize=0`

**Note**
And also, please fix the typo in the config. 

`asm: {`
      ` customeSearch: {`
     `    maxResults: 0,`
     `  },`
 `    },`

It should be **_customerSearch_**..

**Comment by plabadie** [comment]
PR #5333

**Comment by KateChuen** [comment]
Tested on dev10.

Verified that 
- the config typo 'customerSearch' is fixed.
- _pageSize=0_ is sent in the request and no result is returned as expected.
- '_sort: byNameAsc_' is now sent in the request

Request sent:
![Screen Shot 2019-11-13 at 9 51 48 AM](https://user-images.githubusercontent.com/45409515/68774624-63f2ad00-05fb-11ea-9fbf-bacb3dca65e7.png)

Header:
<img width="360" alt="Screen Shot 2019-11-12 at 3 41 55 PM" src="https://user-images.githubusercontent.com/45409515/68774649-6a812480-05fb-11ea-903b-1a29d4f16f4f.png">

Response:
<img width="322" alt="Screen Shot 2019-11-12 at 3 41 39 PM" src="https://user-images.githubusercontent.com/45409515/68774074-8d5f0900-05fa-11ea-85e7-a3a9f6135d28.png">


The only thing I noticed is that, when we _sort: byNameAsc_, the list returned displays the names in Uppercase first, then Lowercase. So, _Kate 2_ is returned before _kate 1_. But it's all backend.
<img width="550" alt="Screen Shot 2019-11-12 at 2 41 25 PM" src="https://user-images.githubusercontent.com/45409515/68775001-debbc800-05fb-11ea-8981-f5459cac5b33.png">
