### ISSUE TITLE
asm: sort the customer search result by name asc

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5310]
**Environment Details**
Spartacus: develop branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/?asm=true

**Steps to Reproduce**
- Login as an agent (asagent/123456)
- Start typing a customer's email address to get a search result, for eg, 'cus'

**Actual Result**
The search result is sorted by uid-asc. 

<img width="1052" alt="Screen Shot 2019-11-05 at 2 11 07 PM" src="https://user-images.githubusercontent.com/45409515/68315169-5f6f4700-0085-11ea-8c38-097c899ffdc1.png">

**Expected Result**
It would be better to have it sorted by name-asc.

**Comment by plabadie** [comment]
Fixed by GH-5306
