### ISSUE TITLE
asm: the session timer does not get reset when we start a customer's session

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5311]
**Environment Details**
Spartacus: develop branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/?asm=true

**Steps to Reproduce**
- Login as an agent (asagent/123456)
- Start a customer's session

**Actual Result**
The session timer isn't reset.

**Expected Result**
The session timer should be reset. 

because i do see the timer get reset when we end a customer's session

it would make sense to have it reset when we start one too.
it might take the agent time to type in the customer's email add, and to find the customer...
Plus in the old acc, the timer gets reset.

**Comment by plabadie** [comment]
pr #5339

**Comment by KateChuen** [comment]
Tested on dev10, on all 3 browsers (chrome, safari, firefox). It's fixed now.
