### ISSUE TITLE
Add "use latest features" flag

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#5327]
During minor release we introduce new features in various ways:
- data driven (currently mainly CMS driven)
- configuration feature flag
- CSS theme
- Start features in an incubator library (new, not yet implemented)

We need this fine-grained control in order to not introduce breaking changes for existing customer. Other developer activities for training, POCs, innovative projects, new customers, demo's, etc. are however bothered unnecessary with this fine-grained control. 
It would therefor be nice to introduce one * (astrix) flag to opt-in of the latest features. This flag is most likely required for both typescript and CSS. 

We should also introduce this flag during the creation of a new Spartacus app with the CLI schematics.

**Comment by psmul** [comment]
QA steps:

For latest flag in feature level:
- change feature level to latest ('*')

Expected result:
- app should works just fine, all features should be available


For negation flag:
- set feature level to 1.3
- find component feature with 1.3 and change notation from '1.3' to '!1.3'

Expected result:
- component or feature shouldn't be visible anymore

**Comment by mszczepaniak** [comment]
tested successfully
