### ISSUE TITLE
Revert asm collapse toggle PR

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#5349]
We need to review the design, so we are removing the feature from develop and we'll reintroduce it in a future release.

We essentially need to remove the toggle buttons added in this PR: #5255 from ticket GH-5014
See certain overlap challenges in GH-5335

**Comment by KateChuen** [comment]
Tested on dev10 on all 3 browsers (chrome, safari, firefox).
No more expand/collapse button for asm.
