### ISSUE TITLE
Revert ASM being CMS driven

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#5367]
The new ASM module is currently CSM driven (my bad!). The result of this is that ASM is currently being loaded for every user. While we generally like (CMS) data driven features, in case of ASM, we're loading a bunch of components in production for every end user. Even though we do not visualise ASM to those users, it's bad practice to load unnecessary data and static resources when it's not needed. 

Hence, we like to improve this. In order to do so, we've added 2 features to add ASM without CMS structure:
- add components dynamically to outlets, so ASM can be added without polluting the html unnecessarily (#5355 )
- add a storefront outlet, so ASM can be loaded before the full storefront experience (see #5357 )

With these new techniques we can silently add ASM into the experience, only if needed.

**Comment by plabadie** [comment]
GH-5382 removes the cms component from the sample data.

**Comment by plabadie** [comment]
For QA:  Test alongside GH-5382, which means you need to use the very latest sample data from spartacussampledataaddon.

**Comment by KateChuen** [comment]
Tested it through https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5382
