### ISSUE TITLE
Update Asm Spartacus sample data

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#5382]
- remove the Asm CMS component.
- remove the added user rights for asagentgroup since this was added in 1905.5

**Comment by plabadie** [comment]
PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/37

**Comment by KateChuen** [comment]
Tested on dev10, with the updated spartacussampledata. 
- Verified that asm works in general (can place an order on behalf of a customer, change his personal details etc)
- Verified that asm's timer still works.
- Verified that asm's customer search still works.
-  Verified starting the customer's session through asm or login page.
- Verified on 3 browsers (chrome, firefox, safari).
