### ISSUE TITLE
Keep ASM styles in the UI component

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#5383]
While the style rules in Spartacus are isolated in the styles library, for ASM, we like them to be part of the components. The reason for this is, that, even if a customer doesn't use any Spartacus styles for the storefront, ASM should remain as-is. 
With this change, we will also break-up the heavy `_asm-main-ui.scss` file as it will be spread over the various components we have. 

That being said, we like the styles to be extendable. Therefor, the components should not have any view encapsulation, such as the angular emulated view encapsulation. 

For this, we should:
1. move component styles from style library to the ASM components
2. add `encapsulation: ViewEncapsulation.None` to the components that have styles to avoid any emulated view encapsulation.

**Comment by KateChuen** [comment]
Tested on dev10. 
Found 2 issues, one about the width of the "Standard customer in session" message. #5473 
And one about the form validations #5471 
Other than these 2, it's ok. 
Verified on chrome (desktop & mobile), safari and firefox.
