### ISSUE TITLE
Clean up ASM styles

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#5384]
The current ASM styles and component DOM is not aligned with how we intend Spartacus styling to be implemented:
- Avoid BEM
- Use a very clean DOM, avoid unnecessary nesting of elements
- Avoid `right` and `left` for directionality (19 occurrences of right or left)
- Use modern css layout tools, such as flexbox or grid. Avoid float completely.
- Avoid vendor specific style rules (vendor  prefixes), as postCss will fill them in (using postcss/autoprefixer)

In order to keep up with the quality, we need to refactor the CSS.

**Comment by developpeurweb** [comment]
This ticket will be fixed in GH-5383

**Comment by KateChuen** [comment]
Tested in #5383
