### ISSUE TITLE
Differential loading of Product Features

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#5407]
With differential loading of product data in place for the product data, we should take advantage of this for the product features. The product features are a potential large chunk of data and are typically only being shown below the fold or in a separate tab. 

While we do not have lazy loading of components in place yet, we should prepare our components to lazy load product data.

**Comment by tobi-or-not-tobi** [comment]
blocked by #3666

**Comment by SerkanSipahi** [comment]
For me is differential loading something different in angular context, see: https://dev.to/lacolaco/differential-loading-a-new-feature-of-angular-cli-v8-4jl
Maybe i misunderstood you.

**Comment by tobi-or-not-tobi** [comment]
@SerkanSipahi I'm fully aware of that feature, just thought it's a cool name to use. But strictly speaking, you're right, it's more a simple lazy loading feature for product content. 

We're planning Lazy loading for 2.0.

**Comment by SerkanSipahi** [comment]
Any approximately release date for 2.0? ...and is in 2.0 angular v9 included?

**Comment by tobi-or-not-tobi** [comment]
@SerkanSipahi 2.0 will be indeed for Angular 9. 
We target 2.0 for feb / march.

**Comment by tobi-or-not-tobi** [comment]
**QA**:

Use spartacus without feature flag < 1.4
1. open a PDP
2. open "specs" tab
3. ensure that product attributes are listed

Use spartacus with feature flag 1.4
1. open a PDP
2. clean the network tab
3. ensure that the product detail response does not include classifications 
4. open the "specs" tab
5. ensure that a separate backend call was done for loading (only) classifications
6. ensure that product attributes are listed

**Comment by bgambocjaviniar** [comment]
QA: 

< 1.4 
they are listed

1.4 and >

product/product# response still includes classifications
