### ISSUE TITLE
Favorites Wishlist UI

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5415]
We created a barebones UX - Anthony review and give your thoughts.
https://wiki.hybris.com/display/spar/Feature%3A+Wish+List

**Comment by vekterdude** [comment]
Wish List on Catalog Page:
https://me3xoy.axshare.com/#id=uibxcx&p=t_wish_list_in_catalog&g=1
 
Wish List on PDP:
https://me3xoy.axshare.com/#id=0sr8vk&p=t_pdp_w_wish_list&g=1
 
Wish List:
https://me3xoy.axshare.com/#id=qx1ev9&p=t_wish_list&g=1


Wish List Confirmation Added to Cart:
https://me3xoy.axshare.com/#id=m1qbgy&p=t_added_to_cart_from_wish_list_no_x_sell&g=1

Recommend a configuration to either remove or persist the item in the Wish List if it is added to the Cart. A favorites tool would persist, but a classic wish list would remove it upon Cart add.

Also: What about: shareability?

**Comment by Xymmer** [comment]
thanksAnthony!
sharability for future
updates done, moving to done
