### ISSUE TITLE
Update Jenkins

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5430]
Infra has a cookbook but we're using something that's too old.
So they don't support us right now because we're using something too old.
So our task is to update Jenkins to use one of their cookbooks.
+ update pipeline.

Gil + Brian(?)

**Comment by hackergil** [comment]
Infra recommended not to create a new Jenkins since we'll stop using their infrastructure very soon. We'll address our current Jenkins problems in the meantime.
