### ISSUE TITLE
Remove ASM authentication related from Generic Auth Service

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#5444]
With ASM we have introduced complexity to the more generic `AuthService`. This makes the `AuthService` unnecessary complex and adds complexity when someone wants to further customise the `AuthService`. ASM is an optional module, and we should isolate ASM specific code. Therefor we should:

- introduce a `AsmAuthService` for ASM specific auth handling
- move ASM related stuff to the ASM core implementation (interceptor logic, error handling)
- interact with the ASM Auth Service only from asm components
- drop any references to the asm auth service from the standard auth handling

**Comment by giancorderoortiz** [comment]
Retest successful
