### ISSUE TITLE
Payment Methods e2e specs failing even after Cart Refactor (for mobile and desktop)

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#5459]
Requests made during those tests sometime cause the test to fail. Need to make sure request are done before moving onto the next commands in cypress.

cx-submit-review cannot be found in _payment-method.ts_ , must make cypress wait for page to load before asserting.

_projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/payment-methods.e2e-spec.ts_

Logs here: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/560/consoleFull

<img width="1212" alt="Screen Shot 2019-12-02 at 11 10 11 AM" src="https://user-images.githubusercontent.com/30666844/69975979-3f9d3880-14f6-11ea-8741-e9bdf3982ab1.png">

Maybe the cancelled delete request has something to do with this failure?

<img width="1214" alt="Screen Shot 2019-12-02 at 11 24 13 AM" src="https://user-images.githubusercontent.com/30666844/69976008-4af06400-14f6-11ea-9f84-4447f3c76c4f.png">

**Comment by Matejk00** [comment]
Such e2e tests are working randomly, sometimes they pass however sometimes following error appears: "RegionModel with country, isocode 'US, US-undefined' not found!". 

The key here might be a timeout and for purpose of this fix was increased and changed to constant variable. 

It's for sure not a best and elegant solution, we have to back and investigate this problem in a future.

**Comment by giancorderoortiz** [comment]
Error for this test seen in dev-com6 develop branch dec_10_2019. 

[payment-methods.e2e-spec.ts.mp4.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3946100/payment-methods.e2e-spec.ts.mp4.zip)

**Comment by Matejk00** [comment]
After conversation with @qjimmy we decided to not merge PR, because tests are now passing. However let's keep this ticket and think about better (not hardcoded) solution in case of errors in the future.
