### ISSUE TITLE
[2.0] asm: Missing form validations

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5471]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/?asm=true

**Steps to Reproduce**
- Click on "Sign In" in the asm section

**Actual Result**
There's no form validation done. 
No error is displayed for sending empty forms. 

**Expected Result**
Validation should be done, and an error should be displayed. 

<img width="982" alt="Screen Shot 2019-11-19 at 11 26 28 AM" src="https://user-images.githubusercontent.com/45409515/69165572-ccd89a00-0abf-11ea-858a-d87028ed9b10.png">

**Comment by Xymmer** [comment]
let's fix this for 1.3.1 release if not so complicated breaking-change-wise

**Comment by plabadie** [comment]
The logic to display the error message is intact.

The messages don't display because the `div` with the class  `invalid-feedback` have a a display-none.

Needs further investigation on the right way to fix this in the styling.

**Comment by plabadie** [comment]
For tests:

This is a 2.0 fix.  Therefore, testing the fox needs to be done with the calydon theme.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-02-13 at 2 38 18 PM](https://user-images.githubusercontent.com/46171897/74471742-bd72ae00-4e6e-11ea-9437-e5e2f9399779.png)
![Screen Shot 2020-02-13 at 2 38 31 PM](https://user-images.githubusercontent.com/46171897/74471745-bea3db00-4e6e-11ea-9cc9-1370eaa9fc9a.png)
![Screen Shot 2020-02-13 at 2 39 12 PM](https://user-images.githubusercontent.com/46171897/74471747-bf3c7180-4e6e-11ea-8ae2-7cc2141fe86a.png)

Test successful
