### ISSUE TITLE
Add "order return request" details page

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#5477]

**Comment by WeizhengSap** [comment]
To code reviewer/QA:
1. please also review/test the "return confirmation" page, especially "submit return".
2. you need to pull the latest `ycommercewebservice` extension, otherwise you will not see `subtotal` in "return request details".
3. in "return request details" page, "request submitted" date cannot be displayed (check my comment at https://wiki.hybris.com/pages/viewpage.action?spaceKey=spar&title=Cancellations+and+Returns+UX+MVP+1+for+Dec2019)
4. In "Return Totals" section, there is text "The totals are estimates...". This text will be added in ticket #5635

**Comment by KateChuen** [comment]
Tested on dev10. Because we're waiting for M10 of commercewebservices to be released, we don't have:
- product image on order return request details page
- subtotal is empty on the same page
