### ISSUE TITLE
Spartacus on github works in Firefox, Safari but not Chrome (for some people)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#548]
https://sap.github.io/cloud-commerce-spartacus-storefront/
For Bill/Matt: Doesn't work on Chrome
For Gil: Works on Chrome

What's the diff?

I tried using CORS plugin to disable CORS blocking but no effect.

On the other hand, Firefox gives a CORS message yet allows the site anyway:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://storefront.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/rest/v2/electronics/languages?lang=en&curr=USD. (Reason: CORS request did not succeed).[Learn More]
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://storefront.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/rest/v2/electronics/cms/pages?pageType=ContentPage&pageLabelOrId=homepage&lang=en&curr=USD. (Reason: CORS request did not succeed).[Learn More]
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonts.gstatic.com/s/opensans/v15/mem8YaGs126MiZpBA-UFVZ0bf8pkAg.woff2. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://storefront.c39j2-walkersde1-d2-public.model-t.cc.commerce.ondemand.com’).[Learn More]

**Comment by Xymmer** [comment]
timebox to 2-3 days and come to the team a standup, if not resolved

**Comment by Xymmer** [comment]
investigate cors configuration some more?

**Comment by hackergil** [comment]
corsfilter.default.allowedOrigins needed to be updated in HAC (it was pointing to localhost)

**Comment by Xymmer** [comment]
it works in chrome when i open an incognito mode but not in regular 
i cleared my cookies and still same

**Comment by Xymmer** [comment]
Looks like it's just Bill, works with matt, gil, scott, jim

**Comment by Xymmer** [comment]
finally figured this out. i have an extension, privacy badger, that was blocking the modelt server from dropping a cookie. once i whitelisted it, it worked
