### ISSUE TITLE
Update schematics to set to 1.3

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5480]
When i tried schematics recently, i saw that it set the version to 1.1.
If schematics is always using latest libraries, let's set this to 1.3 (I know it has the ^)
More importantly, let's add as many feature flags as possible, like infinite scroll or guest checkout. Set most of them to true, unless the change is very different like infinite scroll.

**Comment by tobi-or-not-tobi** [comment]
I created #5327 recently, so we can avoid changing the feature flags for every schematics release. I' prefer to go this route. 

Regarding the version, we could use the `^1.0.0` version, to always create the latest version. It would also align with our recommended update approach (always use latest minor/patch).
