### ISSUE TITLE
Mobile: PLP missing spacing on pages 4 and above

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5487]
**Environment Details**
Spartacus: develop
Browser/Device: Chrome/Mobile

**Steps to Reproduce**
- Go to Digital Cameras -> Shop all digital cameras
- Go to page 4.

**Expected result:** 
Spacing is ok on pages 1-3.
![Screen Shot 2019-11-07 at 2 46 33 PM](https://user-images.githubusercontent.com/45409515/68422158-a0428b00-016d-11ea-8574-e306187d5a90.png)

But then on page 4 and onwards, there's no spacing.

![Screen Shot 2019-11-07 at 2 46 12 PM](https://user-images.githubusercontent.com/45409515/68422149-9d479a80-016d-11ea-87a7-782161789124.png)

Mikel says: "The problem is coming from the pagination. It looks like when too many page numbers are shown in the mobile view the page width takes the width of the pagination. In the mobile view can we limit the number of pages are in the pagination? Like "<|1|2|...|18|>". It seems like that is the maximum amount of pages we can use with out it breaking the page at the smallest view port."

**Comment by tobi-or-not-tobi** [comment]
Fixed with 2.0

**Comment by Xymmer** [comment]
fixed in 2.0 with #6060
