### ISSUE TITLE
AutoFocusDirectiveModule not exported

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5490]
From Singh:
in version 1.3.0, AutoFocusDirectiveModule is not exported :disappointed: (add to cart module can not be overrided)
Workaround would be: import { ɵn as AutoFocusDirectiveModule } from '@spartacus/storefront';

**Comment by Pucek9** [comment]
QA steps: try to import { AutoFocusDirectiveModule } from @spartacus/storefrontlib
