### ISSUE TITLE
Avoid deep merge behaviour for customer configuration

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#5492]
While the deep merge behaviour of the ConfigModule is very convenient for Spartacus feature development, it is not always easy to understand by developers who start developing with Spartacus. The following application configuration illustrates the classic problem:
```typescript
@NgModule({
  imports: [
    ConfigModule.withConfig({
        // custom config
   }),
    B2cStorefrontModule
})
export class AppModule {}
```

In this example, the intend is to configure Spartacus with some _custom config_.  This would work fine if there's no default configuration for the given custom configuration available in Spartacus, however this is often not the case. The deep merge behaviour of The ConfigModule will take both the _custom config_ and all the default configs (from `B2cStorefrontModule` or any underlying modules) into account. As a result, the _custom config_ get's lost. 

In order to make it more apparent, we could introduce a new API for the ConfigModule that will not use deep merge, but instead prioritise the given configuration. Alternatively, we can introduce an API that could be used to introduce a default _fallback_ configuration, that will only be used in case there's no other configuration be given. 

The first solution seems more useful, as we do not need to change existing code in Spartacus. 
The various storefront modules should use this new API.

**Comment by tobi-or-not-tobi** [comment]
Closing this ticket. We took a slightly different approach with the implementation, but with the same goal in mind: ensure that customer configurations not get lost by overrides from the library. 

@dunqan will you add some QA steps here?

**Comment by dunqan** [comment]
QA steps:
1. Add
```
    ConfigModule.withConfig(<StorefrontConfig>{
      cmsComponents:
        {
          SimpleBannerComponent: {
            component: null
          },
        },
    }),
```
before `B2cStorefrontModule` import in `app.module`
2. SAP logo component should not appear on the page
(we should be able to overwrite default configuration without worrying about the order of module imports)

**Comment by KateChuen** [comment]
Tested on dev10. 
After adding the configuration, the SAP logo does not appear.

<img width="1031" alt="Screen Shot 2020-03-25 at 11 23 18 AM" src="https://user-images.githubusercontent.com/45409515/77553665-76270680-6e8b-11ea-94d2-df9059e6c3e5.png">

Verified that adding the config at different positions still works, before and after B2cStorefrontModule import, before and after BrowserTransferStateModule import.
