### ISSUE TITLE
Spartacus does not start on dev servers

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#5499]
Tried on dev2 and dev17.  Get the same error upon startup.

<img width="1202" alt="Screen Shot 2019-11-21 at 12 12 35 PM" src="https://user-images.githubusercontent.com/7065346/69361861-5375ae80-0c5b-11ea-9b80-61e028a5be3f.png">
<img width="1158" alt="Screen Shot 2019-11-21 at 12 05 26 PM" src="https://user-images.githubusercontent.com/7065346/69361865-540e4500-0c5b-11ea-9de4-318c08dd330c.png">

**Comment by hackergil** [comment]
Fixed the installation script (config files needed to be updated)
