### ISSUE TITLE
Release to npm from Travis CI / SPA-1413

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#55]
Come up with a mechanism to release our libraries to npm from Travis CI using a specific set of branches or tags

**Comment by hackergil** [comment]
After doing some research today, I realized Travis does not have support for npm deployments from a monorepo.

https://github.com/travis-ci/travis-ci/issues/3540

We need to find a way to leverage our existing scripts on a custom deployment from Travis or do our deployments from elsewhere
