### ISSUE TITLE
Reconsider the standard URLs

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#550]
While we heavily refactor the routing of the storefront, we've seen a number of optimisations we can do. It's related to usability in general, developer usability (understand what functionality is behind router name) and SEO. 

As an example, we currently have:

- /login
- /register
- /reset-new-password
- /reset-password

In order to provide more clarity we could optimise these, by changing it to:

- /account/login
- /account/newuser
- /account/details
- /account/forgot-password
- /account/reset-password

This ticket requires to go through the list of URLs and improve them. Also the technical names and configuration options related to this should be aligned as we change. 

Special attention is needed to change the CMS driven pages:
- termsAndConditions
- contact
- help
- sale

Those should not be part of the hardcoded app as they're driven by CMS only.

**Comment by Xymmer** [comment]
this was done with other tickets
