### ISSUE TITLE
Wish list feature QA

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#5506]
The QA ticket for the wish list feature. Please QA on dev-12.

The details on the requirements as well as the intended behavior and visuals can be found here: https://wiki.hybris.com/display/spar/Feature%3A+Wish+List.

**Comment by KateChuen** [comment]
PDP
- [x] Verify that from pdp, Upon page load, detect if a product is already in the wishlist; if so change "Add to Wish List" to "Remove from Wish List"
- [x] Verify that from pdp, if user is logged in, you can add to wish list.
- [x] Verify that from pdp, if user is logged in, after adding to wishlist, it's now "remove from wish list" and the heart is now full.
- [x] Verify that from pdp, if user is logged in, you can remove from wish list.
- [x] Verify that from pdp, if user is logged in, after clicking remove from wish list, the item is removed from wish list and puts command back to original state
- [x] Verify that from pdp, if user is logged in, the heart in front of the "add to wish list" is empty if product is not in the wish list. 
- [x] Verify that from pdp, if user is not logged in, The link is "Sign in to add to your wish list"
with empty heart and clicking on it displays login page
- [x] Verify that from pdp, if user is logged in and the item is out of stock, there's no "add to wish list" 
- [x] Verify that from pdp, if user is logged in and the item is out of stock and in the wish list, there's no "remove from wish list" 
- [x] Verify that from pdp, if user is not logged in and the item is out of stock, there's no "add to wish list" -> #5732 

MyAccount
- [ ] Verify that the wishlist command is available from MyAccount menu
- [ ] Verify that A list of items is displayed in my wishlist (same way as in cart)
- [ ] Verify that you see the product image, title , price, variants in the wishlist
- [ ] Verify that you can Add an item to cart from the wish list - there's a "add to cart" button 
- [ ] Verify that upon clicking on "add to cart", the "added to cart" modal is displayed.
- [ ] Verify that you can remove an item from the wish list by clicking on the Remove link
- [ ] Verify that you can configure to remove the item from wish list after it was added to cart.


- [ ] Different browsers
