### ISSUE TITLE
Upgrade to Node 10 LTS

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#554]
Currently, we are using Node 8.9, but the latest Node is 10.14.1 - https://nodejs.org/en/

What should be done: 
* Inform all developers to upgrade their Node env to 10
* Upgrade `engines.node` in `package.json`
* Upgrade the Node version in `.travis.yml`
* If everything is building and passing, then it's ok, no testing required
* Update docs

**Comment by hackergil** [comment]
Assigning to @gladius-mtl to update our docs with the new node version (10.14.1)

**Comment by gladius-mtl** [comment]
Documentation updated in GH-673. Affected files were _contributorsetup.md_ and _setupandinstallation.md_.
