### ISSUE TITLE
Fix 1.3.0 breaking change caused by authService.getOccUserId() usage

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#5543]
> After the upgrade we are getting a lot of there errors in the console log: Cannot read property 'getOccUserId' of undefined. Comes from   this.authService.getOccUserId(), 

We should investigate, as the error suggests that `AuthService` is undefined for some reason, not that it lacks that method.

**Comment by marlass** [comment]
My guess: this happens in services with deprecated constructors where AuthService can be not provided. I don't see checks in methods for authService being defined. I saw those in user services.

**Comment by panukangas** [comment]
Yes the issue was that the constructor in UserService had changed and we extended the old one. Maybe delete the obsolete ones directly, because the old one will cause these issues

**Comment by plabadie** [comment]
PR #5637 

Doc PR: https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/pull/432

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by giancorderoortiz** [comment]
test successful.  getOccUserId console error no longer seen.
