### ISSUE TITLE
[not a bug?] ASM bug: Unauthorized type access. Reason: User does not have permissions to read an instance of type MediaFormat

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#5550]
## Environment Details

- Other environment details: https://dev-com-17.accdemo.b2c.ydev.hybris.com:9002/

## Steps to Reproduce
- Enable ASM
- Login as agent
- Emulate a customer (for example: _user_pocd3xp7b_39353510355@ydev.hybris.com_)

## Observed Results
A certain global message error appears saying: <br>
**Unauthorized type access. Reason: User does not have permissions to read an instance of type MediaFormat**

![Screen Shot 2019-11-27 at 3 20 33 PM](https://user-images.githubusercontent.com/30666844/69760398-7956f380-1132-11ea-8a1b-e34a878c139d.png)

ASM e2e tests are crashing because of this.

**Comment by qjimmy** [comment]
Issue is caused by sample data.

**Comment by plabadie** [comment]
The clean solution to this is to use a commerce suite version 1905.5+ on dev17 (which has the sample data that will fix this issue).

We can also add the data via the console, but it will be lost each time we initialize, which isn't really viable on the long run.

**Comment by CarlEricLavoie** [comment]
Any idea if this will fix https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5819?

**Comment by plabadie** [comment]
As mentioned in the comment above, this is not a bug with Spartacus, but rather some permissions missing on the backend.

@CarlEricLavoie see more explanation in #5819
