### ISSUE TITLE
Issue with complete media URL

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#5559]
if from Backend we receive full product image URL then in `ProductImageNormalizer` it is concatenated with baseURL. Which is wrong.
for example if image have following url 

`https://externalImageServer/images/product/001.jpg`
and base Url ist `localhost:9002` then the final image url is produces as 

`https://localhost:9002https://externalImageServer/images/product/001.jpg`

Problem is here in class --> ProductImageNormalizer at linke 57
```
image.url =
          (this.config.backend.media.baseUrl ||
            this.config.backend.occ.baseUrl ||
            '') + image.url;
```
## Environment Details

- Spartacus:  1.3.*

## Offer to Fix
YES

**Comment by Pucek9** [comment]
I re-created PR because of missing commiter's account (license problem)

**Comment by tobi-or-not-tobi** [comment]
@Pucek9 The issue with the account was already fixed by @mrSingh007, the problem left are captured at #4386. I'd rather like to get the contribution from @mrSingh007 merged.
