### ISSUE TITLE
Missing MyAccount Stock Notification & MyInterests Preference

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5566]
Server: dev-com11. 
Branch: https://github.com/SAP/cloud-commerce-spartacus-storefront/tree/feature/notification-preferences_my-interests_stock-notification

**Steps to reproduce:** 
1. Navigate to dev-com11. 
2. Sign in as registered user. 
3. Enable notification preference. 
4. Navigate to an sku without stock and enable notification. 
4.a. (726511)
5. Switch language to any non-English language available. 
6. Click on MyAccount. 

**Expected Results:** 
6. My Interests and Notification Preference options are available. 
6.a. (Either they remain in English if no translation available, or text.field.etc.... )

**Actual Results:** 
6. My Interests and Notification Preference options are not available. 

German:
![german-myaccount](https://user-images.githubusercontent.com/46171897/69811641-87e9ed00-11bc-11ea-8739-102bbbc82a9c.png)

Chinese:
![chinese-myaccount](https://user-images.githubusercontent.com/46171897/69811657-90422800-11bc-11ea-81c2-60a4cc8ff3c5.png)

English:
![english-myaccount](https://user-images.githubusercontent.com/46171897/69811680-99cb9000-11bc-11ea-98be-e3da33bcc73f.png)

**Comment by giancorderoortiz** [comment]
Related to #5123

**Comment by KevinSu89** [comment]
@giancorderoortiz 
This bug was found before and we have fixed it. But we forgot to update the code in the dev server.
Now, you can double check on the dev 11 server about this.

Sorry for the confusion and thanks for pointing this out.

**Comment by giancorderoortiz** [comment]
I'll double check.

**Comment by KateChuen** [comment]
To retry in production mode.

**Comment by giancorderoortiz** [comment]
Issue has been fixed
![Screen Shot 2020-01-06 at 11 35 25 AM](https://user-images.githubusercontent.com/46171897/71832412-dd959d00-3078-11ea-8411-7f95401d21f2.png)
