### ISSUE TITLE
TBR. Backend Default Spartacus Recipe Update Required. Stock Notification

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5569]
Extension being used on dev-com11 to allow stock notification and my interests:

extension name='notificationoccaddon
extension name='customerinterestsoccaddon
extension name='stocknotificationservices'

This list needs to be confirmed by dev so that spartacus backend server recipe can be updated accordingly.  See https://github.tools.sap/cx-commerce/c3po-legacy-devconfigs/blob/master/spartacus/build.gradle

This dependency on backend extensions should be clearly documented as well.

**Comment by kate1zheng** [comment]
Hi GC,
thanks for your reminder. 
it is our DoD. and will merge the doc after we merge the code. (you can see we did the same doc update when done consignment tracking)
and also we have already committed the doc PR https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5572
