### ISSUE TITLE
[testonly] Reload data when user login, user logout, change language and change currency

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#558]
When user login, user logout, change language and change currency, most of data should be reloaded. We create metaReducers in `reducer/index.ts` to listen to these kinds of actions. For examples, in ProductModule, we have this:
```
export function clearProductsState(
  reducer: ActionReducer<any>
): ActionReducer<any> {
  return function(state, action) {
    if (action.type === CURRENCY_CHANGE || action.type === LANGUAGE_CHANGE) {
      state = undefined;
    }
    return reducer(state, action);
  };
}
```
So, when context change or user login/logout, we clear state to its initial state. In the components, we have something like this:
```
    this.countries$ = this.userService.allDeliveryCountries$.pipe(
      tap(countries => {
        if (Object.keys(countries).length === 0) {
          this.userService.loadDeliveryCountries();
        }
      })
    );
```
In this example, if `countries` object is empty, then we will load countries data again. So, each time, we change language from `address-form` page, countries data is cleared from ngrx store, then data will be reloaded.

In this ticket, we will get to know:
1. When user login/logout, what data need to be cleared or reloaded (e.g. cms data need to be reloaded; user data need to be cleared when logout)
2. when change language/currency, what data need to be reloaded
3. for data which will be reloaded, how we will handle the reloading (clear data from ngrx store, then reload them from component? Or use some other ways to do this? we need discussion)

**Comment by plabadie** [comment]
For point 3. "how we will handle the reloading" : I think we need another mechanism than to check is the data is empty because some data may legitimately be empty, even after loading it from the backend.  Therefore we need to find something else, like a "loaded" flag perhaps.

**Comment by Xymmer** [comment]
let's do a qa of this scenario and make sure everything is ok
talk to wei about what to look for

**Comment by KateChuen** [comment]
Found a case where the data wasn't reloaded: 
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2202

Other than this, it looks ok. The only problem is that localization is missing in most places.
