### ISSUE TITLE
[After variants] Validate support for variants

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#5593]
After the variants epic is merged to develop, update epic branch and validate the wish list support variants.

See `wish-list-item` line 29

**Comment by LTiger14** [comment]
### For review/QA:

Check items in the wish list for electronics and apparel.
For electronics there should be no changes
For apparel, the wish list should display the variants (for items with a variant)

**Comment by giancorderoortiz** [comment]
Variants & wishlist seem to interact well on apparel store
(http://dev-com-15.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/my-account/wishlist)

Certain console errors to be handled separately and not related to this interaction. 

Overall, I am able to add product variants to wishlist and subsequently checkout those variants. 

![Screen Shot 2020-01-07 at 4 10 29 PM](https://user-images.githubusercontent.com/46171897/71930008-d1890880-3168-11ea-9b99-cf4f29b53bd8.png)
![Screen Shot 2020-01-07 at 4 10 41 PM](https://user-images.githubusercontent.com/46171897/71930009-d1890880-3168-11ea-9a51-1d47f9eb0219.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-01-07 at 4 17 36 PM](https://user-images.githubusercontent.com/46171897/71930225-40666180-3169-11ea-812e-d0d6eba2bb75.png)
