### ISSUE TITLE
URL doesn't change after manual context change (for automatic site config)

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#5599]
Steps to reproduce:
1. set backend base url to devcom17
2. remove `context` chunk from Spartacus configuration (to enable automatic site configuration)
3. run `yarn start --disableHostCheck` (to allow for domains other than `localhost`)
4. open url `electronics-spa.localhost:4200`
5. Change the language or currency with a dropdown in top left menu and verify that URL doesn't change

Note: With hardcoded `context` configuration the URL changes properly whenever language or currency changes

**Comment by Zeyber** [comment]
QA: Url not changing on language and currency change
