### ISSUE TITLE
Prepare Datepicker component

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#5605]
In regards to creating/edit budget form, we need date picker component https://98qkkl.axshare.com/#p=d_budgets_add&g=1

**Comment by tobi-or-not-tobi** [comment]
I am very hesitated to introduce a date picker here. Date pickers aren't consider great anymore and come with issues for accessibility. mobile usage. 

I'd prefer to use the native date capabilities that come with the html5 date:
- provides a native experience
- work great for mobile
- doesn't bring an overkill of custom html/js/css 


Safari desktop does not yet support this, mobile does. See browser support: https://caniuse.com/#feat=input-datetime

For a long-term fix, I'd like to rely on the dynamic form library we're planning.
