### ISSUE TITLE
Remove TopHeaderSlot

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#5606]
We have a bug.  The `TopHeaderSlot` in the storefront template was added in 1.3.0 unintentionally.  We need to revert and remove it.

**Comment by plabadie** [comment]
PRs:
Release maintenance: #5609
develop: #5612

**Comment by plabadie** [comment]
For tests:

Quick regression on ASM is enough.  If this caused an issue, the ASM UI would not show at all.

**Comment by giancorderoortiz** [comment]
ASM Regression tests successful
![Screen Shot 2019-12-04 at 6 33 13 PM](https://user-images.githubusercontent.com/46171897/70190702-a3755c00-16c4-11ea-88f7-bee99ce93f82.png)

**Comment by giancorderoortiz** [comment]
manual qa successful.
