### ISSUE TITLE
The "deploy to GitHub pages" step runs for feature branches.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#561]
The "deploy to GitHub pages" step runs for feature branches.

See this run as an example:
https://travis-ci.org/SAP/cloud-commerce-spartacus-storefront/builds/464472542

It probably should only run on develop.  This reduce the run time by 5 minutes on all the feature branch builds.

**Comment by hackergil** [comment]
Pull request #566
