### ISSUE TITLE
Update dev17 to 19.05.7 release.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#5615]
We need to update the backend on dev17 to the latest patch version, which 19.05.7 as of now.

Features that are now in Spartacus depend on a commerce suite version of 1905.5+ and 1905.6+

Right now we have an older version of the backend on dev17

**Comment by giancorderoortiz** [comment]
This is no longer possible due to e2e test issues. 
Decision for now has been to use < 1905.7, which causes token revocation to fail silently.
