### ISSUE TITLE
Deprecated code since 1.3: ASM Customer Emulation Support

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#5628]
This is the deprecation cleanup ticket related to GH-5543

ASM customer emulation logic added a new AuthService dependency in these services:

- UserService
- UserAddressService
- UserConsentService
- UserOrderService
- UserPaymentService

To make the logic backwards compatible, if the new AuthService dependency is undefined because and extended version of the service uses the deprecated constructor, we fall back to the previous logic in some functions.

When we remove the deprecated constructor that doesn't have the AuthService dependency, we also need to remove the backwards compatible logic in many functions.

The pattern is the following:

```
if (this.authService) {. // remove the if statement     
                         // keep what's in the if, it is new logic that is ASM compatible
} else {                 // remove the else statement
                         // remove this, deprecated logic is inside the else.
}                        // remove the else statement

```

For example, this function:
```
load(): void {
    if (this.authService) {
      this.authService
        .getOccUserId()
        .pipe(take(1))
        .subscribe(occUserId =>
          this.store.dispatch(new UserActions.LoadUserDetails(occUserId))
        )
        .unsubscribe();
    } else {
      this.store.dispatch(new UserActions.LoadUserDetails(OCC_USER_ID_CURRENT));
    }
}
```

Would become:
```
load(): void {
      this.authService
        .getOccUserId()
        .pipe(take(1))
        .subscribe(occUserId =>
          this.store.dispatch(new UserActions.LoadUserDetails(occUserId))
        )
        .unsubscribe();
}
```

**Comment by bgambocjaviniar** [comment]
PR: GH-6889
