### ISSUE TITLE
Tablet: Pagination from plp is displayed on the menu

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5631]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/?asm=true

**Steps to Reproduce**
- Go on a tablet viewport
- Go in a category listing page, for eg: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/Open-Catalogue/Cameras/DigitalCameras/Digital-Compacts/c/576
- Click on the hamburger menu

**Actual Result**
The pagination is displayed on top of the open menu.

<img width="817" alt="Screen Shot 2019-12-03 at 11 58 05 AM" src="https://user-images.githubusercontent.com/45409515/70072034-3a0e2400-15c4-11ea-8998-4c2fad316e94.png">

**Comment by KateChuen** [comment]
Haven't tried on an actual tablet.

**Comment by tobi-or-not-tobi** [comment]
Fixed with 2.0

**Comment by Xymmer** [comment]
fixed in 2.0 with #6060
