### ISSUE TITLE
TM. SSR. Missing HTML Encoding in Json-LD

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5636]
Refer to ticket https://github.tools.sap/cx-commerce/spasec/issues/33 for further details

**Comment by tobi-or-not-tobi** [comment]
@giancorderoortiz would be good if you can verify again

**Comment by Xymmer** [comment]
i changed this to 1.4 as it probably didn't go into 1.3

**Comment by giancorderoortiz** [comment]
Looks good.
