### ISSUE TITLE
Clearing product state on Login/Logout: improvement 

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#5644]
As different user have different prices, we should clear product state on login/logout (anonymous don't have prices).

But right now as soon as user is logged in the product state is not reloaded and because of this prices are not displayed/changed.

Please provide a way to clear the product state. Currently its not possible to clear product state as it is done through entity state and to clear entity state 'product codes' need to be passed. (not a good way)

Either it should clear automatically the product state or there should be a method which do it. So that we can use this service method to reset/clear product state.

## Environment Details
- Spartacus:1.3

## Offer to Fix
no

**Comment by dunqan** [comment]
It is possible to clear the product's state, either by using meta reducer or in effect (it's possible to remove all entites without  the need to provide all codes with `EntityRemoveAllAction` dispatched with `PRODUCT_DETAIL_ENTITY` as an entity type)

**Comment by mrSingh007** [comment]
@dunqan 
can not import 'EntityRemoveAllAction'

**Comment by znikola** [comment]
You have to import `StateEntityActions` and then do `new StateEntityActions.EntityRemoveAllAction()`

**Comment by KateChuen** [comment]
Sounds like this isn't a bug. Please let us know if the solution proposed does not work.
