### ISSUE TITLE
Cart not found issue - post cart refactor

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#5647]
There is a case when after merge cart on checkout pages you can get `Cart not found` issue. That happens, because cartId is checkout stream responsible for that call is still old (before login).

**Comment by marlass** [comment]
QA steps:
- go to guest checkout first step
- login
- checkout calls should happen only after cart merge procedure
- `Cart not found` error should not happen

**Comment by Zeyber** [comment]
Added items to cart
Logged in with guest checkout
No cart error shown when redirected to shipping address
