### ISSUE TITLE
Style Cancellations and Returns pages

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#5661]
Style the following pages:
- [x] Order History - Tabs
- [x] Order Details (Request Return/Cancel) - Buttons alignment (w/Calydon instance)
- [x] Return/Cancel Order - Table styling
- [x] Return/Cancel Order Confirmation - Table styling
- [x] Return Request Details
- [x] Final round for overall consistency

**Notes:**
- Some of these UIs/files may have been affected by Calydon work done previously.
- [UX & Wires](https://wiki.hybris.com/display/spar/Cancellations+and+Returns+UX+MVP+1+for+Dec2019)

**Comment by developpeurweb** [comment]
All pages have been styled and merged to epic branch through the following tickets: GH-5855, GH-5859, GH-5860 which contain the QA issues, therefore this ticket can be move to DONE when all of the aforementioned are done.

**Comment by KateChuen** [comment]
Not happy about certain things. There are some inconsistencies:
- "Request A Return" and "Cancel Item" buttons are white, while other primary buttons are red. 
- the buttons are only at the bottom of the page for "request return" and "Cancel Items" pages. While they are both on top and bottom of the page on their respective confirmation pages, and on "Cancel Return Request" Page.

But talked with Bill, and agreed to live with it for now.
