### ISSUE TITLE
Move the cms data specific to SPA into the sub catalog created

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#567]
In smartedit integration phase 1, I created a new site "**electronics-spa**" and catalogs (**electronics-spaContentCatalog:Staged** and **electronics-spaContentCatalog:Online**)

**Comment by WeizhengSap** [comment]
Impex to create sync job:
```
### sync electronicContentCatalog:staged to spaContentCatalog:staged
$syncJob=sync $contentCatalog:Staged->$spaContentCatalog:Staged
$sourceContentCV=sourceVersion(catalog(id[default=$contentCatalog]),version[default='Staged'])[unique=true,default='$contentCatalog:Staged']
$targetContentCV=targetVersion(catalog(id[default=$spaContentCatalog]),version[default='Staged'])[unique=true,default='$spaContentCatalog:Staged']

INSERT_UPDATE CatalogVersionSyncJob;code[unique=true];$sourceContentCV;$targetContentCV;syncPrincipals(uid)[mode=append];syncPrincipalsOnly[default=false];removeMissingItems;createNewItems;rootTypes(code)[mode=append]
;$syncJob;;;cmsmanagergroup,electronics-cmsmanagergroup;;true;true;CMSItem,CMSRelation,Media,MediaContainer

### sync spaContentCatalog:staged to spaContentCatalog:online
$spaSourceContentCV=sourceVersion(catalog(id[default=$spaContentCatalog]),version[default='Staged'])[unique=true,default='$spaContentCatalog:Staged']
$spaTargetContentCV=targetVersion(catalog(id[default=$spaContentCatalog]),version[default='Online'])[unique=true,default='$spaContentCatalog:Online']
INSERT_UPDATE CatalogVersionSyncJob;code[unique=true];$spaSourceContentCV;$spaTargetContentCV;
;sync spaContentCatalog:Staged->Online;;;;
```

**Comment by tobi-or-not-tobi** [comment]
- Not sure how much you know about multi-country CMS? That module allows to support a hierarchy of content catalogs. We could evaluate this as an alternative, as duplicating 99% of the CMS data isn't great. Moreover, we need to do something similar as soon as we move into multiple sites. 
- We have a number of improvements in mind when it comes to the site structure (pages, tempates, slots). If we go down this route, I'd like to be involved.

**Comment by WeizhengSap** [comment]
I know how multi-country CMS work :). Actually, I follow the same way. The new catalog I created is a sub catalog of `electronic-ContentCatalog`. But, it is empty. In smart edit, if you select one multi-country site (e.g. Electronic Site US), in `Pages`, there is nothing. 

![screen shot 2018-12-07 at 12 45 51 pm](https://user-images.githubusercontent.com/44440575/49663947-4fd32280-fa1e-11e8-8a68-446a79371fa0.png)

**Comment by tobi-or-not-tobi** [comment]
You must add both content catalogs to the cms site; the sub catalog structure was added later, but I believe both content catalogs must be connected anyway. The idea would be that only changes would add up in the spartacus specific content catalog. We could have alternative page(template)s, overridable slotes, custom components, etc.

**Comment by WeizhengSap** [comment]
PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/8/overview

**Comment by WeizhengSap** [comment]
1. install spacceleratorsamplesaddon
2. initialize the system
3. in `projects/core/src/occ/config/default-occ-config.ts`, change to `baseSite: 'electronics-spa'`
