### ISSUE TITLE
Breaking changes since 1.5: Applied Promotions (#3796)

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/cloud-commerce-spartacus-storefront#5670]
TBD

**Comment by mszczepaniak** [comment]
**QA Steps:**

Check promotions on the develop branch, verify (on dev 12 or 17) that order (more than 200USD in the cart)and product (i.e. Canon EOS 450D) promotions are working on the following:

- [x] added to cart modal dialog
- [x] cart itself
- [x] checkout
- [x] review-submit (last step before placing an order)
- [x] order confirmation
- [x] order history

**Comment by Matejk00** [comment]
QA done, works as expected.
