### ISSUE TITLE
In sample data, we need to change IDs for cancel/return pages

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#5677]

**Comment by WeizhengSap** [comment]
PR is here: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/50

**Comment by bgambocjaviniar** [comment]
works and did not find any import error as well relating to this in the console while initializing locally

Below, can see an example of it working

<img width="1440" alt="Screen Shot 2019-12-10 at 8 09 16 PM" src="https://user-images.githubusercontent.com/29099466/70582669-36ad0680-1b89-11ea-865d-0d58cc28ed6a.png">

**Comment by WeizhengSap** [comment]
To QA:

Please do smoke tests of SPA.

**Comment by KateChuen** [comment]
Tested on dev10.
