### ISSUE TITLE
Retest: wrong cursor and no highlight on hover

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/cloud-commerce-spartacus-storefront#568]
## Enviroment Details
- Spartacus
- Browser: Chrome 70.0.3538.110
- OS: Windows 10

## Expected Results
Sign Out should be highlighted and cursor should have property "pointer"

## Observed Results
No highlight and cursor property "text"

## Steps to Reproduce
1. Sign in
2. Try to sign out

## Additional Information
Please take a look at the gif
![signout_bug](https://user-images.githubusercontent.com/4272069/49658584-aeaa9300-fa42-11e8-84d0-0adfd9cb5899.gif)

**Comment by Xymmer** [comment]
looks like this is fixed, retest

**Comment by KateChuen** [comment]
Retested. It's fixed now. SignOut gets highlighted as well as the others in the menu. Sign Out still functional too. 
<img width="811" alt="signOutHighlighted" src="https://user-images.githubusercontent.com/45409515/54631624-c5558280-4a52-11e9-9b4a-0d3a2600f625.png">
