### ISSUE TITLE
Facet topValues support

### ISSUE THREAD

**Issue by mtchorz** [SAP/cloud-commerce-spartacus-storefront#5692]
Following guidelines:
- https://sap.github.io/cloud-commerce-spartacus-storefront-docs/installing-sap-commerce-cloud/
- https://sap.github.io/cloud-commerce-spartacus-storefront-docs/building-the-spartacus-storefront-from-libraries/

I've installed locally spartacus with cloud commerce.

It looks like spartacus doesn't support facet topValues. No matter how many topValues records OCC returns, SPA shows first 6 values and 'show more ...' link.

## Environment Details

- Spartacus:  1.3
- Browser: Chrome
- OS: Mac OS Catalina
- Device: MacBook Pro
- EC Commerce Suite: 

## Steps to Reproduce
1. Go to Backoffice
2. Open AdaptiveSearch perspective
3. Choose electronics product catalog online
4. Choose defaultElectronicsProduct catalog
5. Select defaultElectronics profile
6. Override any Facet
7. Edit facet and open Facet Values tab
8. Select defaultTopValuesProvider.

## Observed Results
Spartacus storefront displays each time top 6 facet values instead take under consideration topValues from response.

## Expected Results
With described backoffice electronics setup, OCC should start send 5 topValues elements.

Those 5 facet values should be displayed and 'show more...' link
![Screenshot 2019-12-06 at 16 54 46](https://user-images.githubusercontent.com/4405725/70337981-57edba00-184c-11ea-8ae6-3bddd8a64a8d.png)

**Comment by tobi-or-not-tobi** [comment]
QA:
- setup a facet filter for a list of facets with more then 5 values  (see above a description for the setup) 
- confirm that the number of facet values is 5

**Comment by tobi-or-not-tobi** [comment]
Reopened as it hasn't been resolved. I've been working on this but the linked PR was not the solution.

**Comment by tobi-or-not-tobi** [comment]
QA:
- Configure topValues in the backend (i.e. backoffice adaptive search) for a specific facet
- ensure that the topValue list is used as the direct visible facets (all of them before the "more" button)
- ensure that the maximum is 6 in case there is no value given from the backend

**Comment by KateChuen** [comment]
Tested on dev10.
Before configuration:
<img width="1048" alt="Screen Shot 2020-02-27 at 9 27 50 AM" src="https://user-images.githubusercontent.com/45409515/75455835-cae86780-5947-11ea-8c9d-c5913e7c2b09.png">

After configuring the topValues, I get 5 facets before the "Show More".
<img width="1085" alt="Screen Shot 2020-02-27 at 9 32 29 AM" src="https://user-images.githubusercontent.com/45409515/75455863-d50a6600-5947-11ea-819c-96c2d5782255.png">


@tobi-or-not-tobi How can I test this?
_ensure that the maximum is 6 in case there is no value given from the backend_

**Comment by KateChuen** [comment]
Tested on dev10.
Before configuration:
<img width="1048" alt="Screen Shot 2020-02-27 at 9 27 50 AM" src="https://user-images.githubusercontent.com/45409515/75455835-cae86780-5947-11ea-8c9d-c5913e7c2b09.png">

After configuring the topValues, I get 5 facets before the "Show More".
<img width="1085" alt="Screen Shot 2020-02-27 at 9 32 29 AM" src="https://user-images.githubusercontent.com/45409515/75455863-d50a6600-5947-11ea-819c-96c2d5782255.png">


@tobi-or-not-tobi How can I test this?
_ensure that the maximum is 6 in case there is no value given from the backend_

**Comment by KateChuen** [comment]
Tested that when there’s no facet configuration for the topValues, the backend should not return top values at all. In this case, the default = 6

Without facet configuration:
<img width="801" alt="Screen Shot 2020-03-02 at 10 55 36 AM" src="https://user-images.githubusercontent.com/45409515/75693040-6ba29400-5c74-11ea-8830-f9956ac78f8b.png">

<img width="476" alt="Screen Shot 2020-03-02 at 10 53 43 AM" src="https://user-images.githubusercontent.com/45409515/75693113-82e18180-5c74-11ea-87db-36783c7aca97.png">

With facet configuration:
<img width="736" alt="Screen Shot 2020-03-02 at 10 48 50 AM" src="https://user-images.githubusercontent.com/45409515/75693152-9260ca80-5c74-11ea-9d0c-dfa2e4e250d6.png">
<img width="409" alt="Screen Shot 2020-02-27 at 9 39 05 AM" src="https://user-images.githubusercontent.com/45409515/75693162-955bbb00-5c74-11ea-8ae8-e701e974a747.png">
