### ISSUE TITLE
regression Checkout As Guest e2e specs failing after cart refactor

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#5695]
in the _it should keep guest cart content and restart_ part, the second login does not show the shipping page but rather, it redirects to the homepage for some reason. 

The cy.wait() for the _getShippingPage_ alias never finds the alias and fails.

Running against dev-17

![Screen Shot 2019-12-06 at 2 42 37 PM](https://user-images.githubusercontent.com/30666844/70351359-be67dd80-1836-11ea-8b32-0465d657a910.png)

Logs here: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/621/console

**Comment by kacperknapik** [comment]
**QA results**: test is working correctly, tried couple of times
