### ISSUE TITLE
Language checkout AND Currency checkout e2e spec failing after Cart Refactor

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#5696]
The e2e should be able to switch language from the shipping page. However, it seems to have been redirected to the homepage after doing so, breaking an assertion.

Ran against dev-17

![Screen Shot 2019-12-06 at 2 58 29 PM](https://user-images.githubusercontent.com/30666844/70352286-cf195300-1838-11ea-8c33-a334d9cca558.png)

Logs here : https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/621/console

**Comment by kacperknapik** [comment]
**QA results**: test is working correctly, tried couple of times
