### ISSUE TITLE
Broken memoization in entityProcessesLoaderStateSelector for fallback value.

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#5706]
The object is constructed inline and new reference is always returned.

**Comment by marlass** [comment]
QA steps:
- set `multi-cart.active` property in local storage to `fresh`
- check if `entityProcessesLoaderStateSelector` returns every time reference to the same object (initialProcessesLoaderStateValue) and does not create new object on every emission.

**Comment by Pucek9** [comment]
QA done
