### ISSUE TITLE
Variants: An error should be displayed is no size is selected

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5712]
**Environment Details**
Spartacus: variants branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-15.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP

**Steps to Reproduce**
- On chrome, go to product 300760754 (http://dev-com-15.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/product/Girl%20On%20Feather%20Tank%20Top%20Women%20coco%20S/300760754)
- In the size menu, select "Please select size".
- Click on "Add to Cart"

**Actual Result**
The default variant is added to cart. 

**Expected Result**
Should not be able to add an item to cart. Should display an error to ask the user to select a size. 

![Screen Shot 2019-12-09 at 12 23 01 PM](https://user-images.githubusercontent.com/45409515/70457817-d762cf80-1a7e-11ea-8153-7fa4b566c547.png)
![Screen Shot 2019-12-09 at 12 23 07 PM](https://user-images.githubusercontent.com/45409515/70457818-d762cf80-1a7e-11ea-9f29-d0c0d47445a1.png)

**Comment by psmul** [comment]
After some discussion, we decided to remove the label as it's only would be time-consuming to implement a workaround for it.

**Comment by KateChuen** [comment]
Tested on dev15. Now there's no "Please select size" label.
