### ISSUE TITLE
Variants: Add to cart buttons are misaligned on the grid view of PLP

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5715]
**Environment Details**
Spartacus: variants branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-15.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP

**Steps to Reproduce**
- On chrome, go to a category listing page, for eg: http://dev-com-15.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/220000
- Go to grid view

**Actual Result**
The alignment of the "Add to cart" button
![Screen Shot 2019-12-09 at 10 55 02 AM](https://user-images.githubusercontent.com/45409515/70465857-e43bef00-1a8f-11ea-9b2a-3358bf687b9f.png)
 is not consistent.

**Comment by Xymmer** [comment]
asking Anthony

**Comment by Xymmer** [comment]
after talking with jeanne and miguel, 
step 1:
- with pictures aligned to the top, align the Addtocart buttons to the bottom of the imaginary box
(if you need help from miguel we'll wait for next week)

step 2:
- the layout gets quite airy (add to cart button seems connected to the image underneath for example); let's put a box or a line around the items in the grid. however Miguel will investigate the easiest/best/safest approach to this and then we'll share findings.

so for this ticket, let's do step 1.

**Comment by mirkosoft** [comment]
QA steps: go to category http://localhost:4200/apparel-uk-spa/en/GBP/category/330700
and switch view to grid. Compare what you see with develop and ticket description.

**Comment by psmul** [comment]
QA done, Confirmed that misalignment is gone.
