### ISSUE TITLE
Variants: reviews don't work

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5716]
**Environment Details**
Spartacus: variants branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-15.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP

**Steps to Reproduce**
- On chrome, go to a product page, for eg: http://dev-com-15.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/product/Multilogo%20Good%20Looking%20SS%20Women%20heather%20grey%20S/300495181
- Write and approve a review for that variant.

**Actual Result**
The review is never displayed on the page. 
Also, could not find a variant with reviews. 

![Screen Shot 2019-12-09 at 2 24 34 PM](https://user-images.githubusercontent.com/45409515/70466247-b5724880-1a90-11ea-9e07-6772ab2ba5b0.png)

**Comment by psmul** [comment]
Couldn't reproduce a problem. Added review in a reported product, approved it in backoffice and after refresh, it was visible in reviews tab.

**Comment by KateChuen** [comment]
So the reason why it didn't work on the server is because it was pointing to a different backend than where the frontend is deployed.
Confirmed that reviews work, and it's tied to an individual SKU.
