### ISSUE TITLE
Stock notification prevents add to cart on Firefox

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#5741]
### Steps to reproduce
On Firefox

1. Go to a product details page with stock (example 300938)
2. Try to add to cart

It is not possible to click the button

### Expected behavior

Should be able to add to cart like on Chrome

### Issue

The issue is that the `stock-notification` component overlays the `add-to-cart` component

![Screen Shot 2019-12-10 at 4 13 39 PM](https://user-images.githubusercontent.com/10605724/70569554-2a648180-1b68-11ea-9ede-de57c0101f25.png)

**Comment by giancorderoortiz** [comment]
Any updates on this issue?
