### ISSUE TITLE
[Needs Re-Testing] consenttemplates request sending anonymous user id, when logged in

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#5748]
As I saw the logic, the `/rest/v2/store/users/anonymous/consenttemplates` request should not be triggered  when user is logged in. Thats might be the reason that `anonymous` is hardcoded. 

Now the problem arises when user is not logged in and he get empty array of consenttemplates. When user is logged in and refresh the page then this request is triggered with `anonymous` userId  and from backend the response comes with `Access is denied`.

## Problem flow
Here how the problem arises: 
in `AnonymousConsentManagementBannerComponent` template `isBannerVisible` method called. Which have method `getTemplatesUpdated()` and that call further to `getTemplates(true)`. 
And now here the boolean check `if (!Boolean(templates))` trigger `loadTemplates` function. 
In this flow its not checked if user is anonymous or not!! The `templates` object comes with undefined and which passes the boolean check.

## Environment Details

- Spartacus:  1.3
- Browser: chrome

## Steps to Reproduce
1. when user is not logged in get this response :
`{ "consentTemplates" : [ ]}` 
2. Now login with user
3. Now refresh the page. Request will be triggered with userid 'anonymous'

## Expected Results

Either request should not be triggered when user is logged in OR it should pass current instead of anonymous after logged in.

## Offer to Fix
Yes: but want to know first, in which way we should proceed:-

1. passing correct user id instead of hardcoded anonymous
2. Adjusting `getTemplates` method and checking if user is logged in

**Comment by KateChuen** [comment]
@znikola Can you provide a comment on this please?

**Comment by bgambocjaviniar** [comment]
No error in develop and maintenance branch, it is most likely fix and will verify with Louis.
