### ISSUE TITLE
[BLOCKER]The products in wishlist are used to checkout, not the products in cart

### ISSUE THREAD

**Issue by kate1zheng** [SAP/cloud-commerce-spartacus-storefront#5792]
## Environment Details

- Spartacus:  1.4.0-next.1 develop branch
- Browser: chrome
- OS: macOS Catalina
- Device: macbook

## Steps to Reproduce
1. login storefront
2. add product a in cart
3. add product b in wishlist
4. go to cart and checkout

## Observed Results
1. the product b is in the order

## Expected Results
1. the product a should be in the order

**Comment by marlass** [comment]
Happens when last update operation is done on cart different than active.

**Comment by Pucek9** [comment]
SQA done
