### ISSUE TITLE
coupon apply button is far away from proceed to checkout button in cart when there are many products in cart

### ISSUE THREAD

**Issue by kate1zheng** [SAP/cloud-commerce-spartacus-storefront#5793]
## Environment Details
- Spartacus:  1.4.0-next.1 develop branch
- Browser: chrome
- OS: macOS Catalina
- Device: macbook

## Steps to Reproduce
1. add 1 or 2 products in the cart
2. the place of coupon apply button looks fine
![image](https://user-images.githubusercontent.com/43032959/70787528-d2c55080-1dc9-11ea-856c-4bb1f20e25a6.png)
3. add more than 10 products in cart, then place of the button is moved down
![image](https://user-images.githubusercontent.com/43032959/70787594-fb4d4a80-1dc9-11ea-8d4a-16b49799ab6f.png)

## Observed Results
1. the place of coupon apply button is changed if the product count is changed in cart

## Expected Results
1. the place of coupon apply button should be fixed. near by the proceed to checkout button

**Comment by KateChuen** [comment]
It's fixed if you enable the calydon theme.
