### ISSUE TITLE
error is reported after re-login in cart

### ISSUE THREAD

**Issue by kate1zheng** [SAP/cloud-commerce-spartacus-storefront#5796]
## Environment Details

- Spartacus: 1.4.0-next.1 develop branch
- Browser: chrome
- OS: macOS Catalina
- Device: macbook

## Steps to Reproduce
1. add product 300938 in the cart using a login user
![image](https://user-images.githubusercontent.com/43032959/70788031-f341da80-1dca-11ea-86aa-25b36aeb6ffe.png)
2. logout and add product 1776948 in the cart as guest, and go to cart.
3. login again using the user in step1

## Observed Results
1. you can see the products are merged in cart, but report an error
![image](https://user-images.githubusercontent.com/43032959/70790937-0192f500-1dd1-11ea-962e-83786278d462.png)

## Expected Results
1. no error after login back in cart

**Comment by KateChuen** [comment]
Known issue, that will be fixed in 2.0.
