### ISSUE TITLE
Form labels should focus the form control / SPA-1265

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#58]
In angular we don't use the class element IDs and therefor we can't do:
{code:java}
<label for="FORM_CONTROL_ID">label text</label>
<input id="FORM_CONTROL_ID">{code}
Instead, we should ideally do:
{code:java}
<label>
  label text
  <input>
</label>
{code}
This is both a fix as well as a simplification. 

This should be fixed in the various forms we have (login, address forms, checkout, etc.)

**Comment by Matejk00** [comment]
Facets also can be change with the same style. New issue created #200.

**Comment by kacperknapik** [comment]
Labels in various forms (login, register, checkout, etc) are focusing their inputs. Closing and moving to accepted
