### ISSUE TITLE
Add retry (maybe) and capture screenshots

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#580]
1. Add retry mechanism to failed tests. 
There's already an existing package, maybe we can use that? Or something else?
https://www.npmjs.com/package/protractor-flake

2. Add screenshots to capture the screen where the test fails.

**Comment by KateChuen** [comment]
I tried one retry mechanism, using the protractor-retry package, as described here:
https://www.npmjs.com/package/protractor-retry

But that did not work for me. Furthest I got was this (looks like it does try to run the test again, but fell short):

----------------
1) Product details should be able to add different quantities of product to cart
  - Expected '5' to be '4'.

Executed 6 of 6 specs (1 FAILED) in 5 secs.
[15:05:53] I/launcher - 0 instance(s) of WebDriver still running
[15:05:53] I/launcher - chrome #01 failed 1 test(s)
[15:05:53] I/launcher - overall: 1 failed spec(s)


 Re-running tests , attempt :  1
 Re-running the following test files : /Users/i839943/myRepo/mySPA/cloud-commerce-spartacus-storefront/projects/storefrontapp-e2e/src/regression/product-details.e2e-spec.ts


node_modules/@angular-devkit/build-angular/src/utils/run-module-worker.js: line 1: /Applications: is a directory
node_modules/@angular-devkit/build-angular/src/utils/run-module-worker.js: line 2: CONTRIBUTING.md: command not found
node_modules/@angular-devkit/build-angular/src/utils/run-module-worker.js: line 3: CONTRIBUTING.md: command not found
node_modules/@angular-devkit/build-angular/src/utils/run-module-worker.js: line 4: CONTRIBUTING.md: command not found
node_modules/@angular-devkit/build-angular/src/utils/run-module-worker.js: line 5: CONTRIBUTING.md: command not found
node_modules/@angular-devkit/build-angular/src/utils/run-module-worker.js: line 6: CONTRIBUTING.md: command not found
node_modules/@angular-devkit/build-angular/src/utils/run-module-worker.js: line 7: ci-scripts/: is a directory
node_modules/@angular-devkit/build-angular/src/utils/run-module-worker.js: line 9: syntax error near unexpected token `'message','
node_modules/@angular-devkit/build-angular/src/utils/run-module-worker.js: line 9: `process.on('message', (message) => {'
[15:05:53] E/launcher - Process exited with error code 2
An unexpected error occurred: undefined

**Comment by Xymmer** [comment]
should we split this one?

**Comment by KateChuen** [comment]
Closing this one since we've moved to Cypress and it's already capturing screenshots & videos. 
No need for retry mechanism yet, tests have been stable.
