### ISSUE TITLE
WishList Checkout e2e Test

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5808]
An e2e test is required for WishLists that confirms checkout functionality has not been affected. 
See blocker bug: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5797

**Therefore:**

**Given** a registered user
**And** there are  X items stored/added to wishlist
**And** other Y items stored/added to cart
**When** checkout is done
**Then** only Y items in cart are in order
**AND NOT** items in wishlist.

**Comment by giancorderoortiz** [comment]
Expanding on: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5421

**Comment by giancorderoortiz** [comment]
Video of issue provided by panda team. 
[2019-12-13_16-35-06.mp4.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3961338/2019-12-13_16-35-06.mp4.zip)

**Comment by LTiger14** [comment]
Handled in #5810
