### ISSUE TITLE
Wishlist Customer Journeys e2e Tests

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5810]
E2E requests that mimic a real customer journey using the e2e functionality as follows: 

_1. Wishlist and checkout_

- **Given** a registered user
- **When** he/she adds n items to wishlist
- **And then** adds all of them to the cart from wish list page
- **Then** he/she is able to checkout all items previously in wishlist
- **And** confirms it in order details page. 

_2. Wishlist, cart and checkout._ 
- **Given** a registered user
- **When** he/she adds n items to wishlist . (i.e. cameras)
- **And** directly some m items to cart (ie. tripods)
- **And** subsequently adds n items in wishlist to cart (i.e. cameras to cart)
- **Then** he/she is able to checkout all items in cart
- **And** confirms it in order details page. 

(Purpose here is a situation where items from wishlist and cart can be checkout together)

_3. Repeat test 1 above in mobile breakpoint._ 

_4. Repeat test 2 above in mobile breakpoint._

**Comment by LTiger14** [comment]
I'm not sure about the use of mobile tests for this checkout flow. The flow is the same as the regular checkout and it's tested on mobile in another e2e. 

Also the only change in mobile is related to visual styling. This does not affect the behavior or cypress.
