### ISSUE TITLE
[not a bug?] ASM - Can't access account links 

### ISSUE THREAD

**Issue by CarlEricLavoie** [SAP/cloud-commerce-spartacus-storefront#5819]
## Environment Details

- Spartacus:  1.3.0
- Browser: Chrome

## Steps to Reproduce
1.Log into ASM
2.Start emulating a user session

## Observed Results
1.Account menu is not visible

![2019-12-14_23-09-29](https://user-images.githubusercontent.com/7239120/70858016-6e88b680-1ec7-11ea-9ae2-ee37d4b36263.png)

## Expected Results
The agent should see the account links.

## Offer to Fix
If it's accepted as a bug, I might have some time to investigate the invalid data.

## Additional Information
This is mostly due to wrong permissions for the agent.
Might be fixed in https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5550
haven't had time to update.

**Comment by KateChuen** [comment]
@CarlEricLavoie Can you please retest with the latest patch and read the latest asm doc that defines the permissions.

**Comment by plabadie** [comment]
This is the error generated when the the agent starts an emulation session and the agent lacks the permissions to read cms data from occ.

For info on how to make sure the right permissions are in place, see `Granting asagentgroup CMS Permissions` in the asm doc: https://sap.github.io/cloud-commerce-spartacus-storefront-docs/asm/#granting-asagentgroup-cms-permissions
