### ISSUE TITLE
Anonymous Consent Error

### ISSUE THREAD

**Issue by CarlEricLavoie** [SAP/cloud-commerce-spartacus-storefront#5820]
## Environment Details

- Spartacus: 1.3

## Steps to Reproduce
1. Do not enable anonymous consent feature in the app.module.ts
2. Clear storage to prevent any existing cookie / storage from displaying the banner
3. Load any page

## Observed Results
'View details' is displayed in the cookie tracking banner

## Expected Results
The details should not be accessible for anonymous user given that I have not enable anonyous consent.
Also, if the user clicks on 'select all' or chooses some values and closes the modal, an error will appear in the log because 'consentState' doesn't exist.

![2019-12-15_11-51-59](https://user-images.githubusercontent.com/7239120/70865987-d247c980-1f31-11ea-8961-8d08e6268d20.png)

## Offer to Fix
No

**Comment by CarlEricLavoie** [comment]
On a side note, clicking 'view details' currently dismisses the cookie banner which results in user 'approving' of cookies, which in my opinion is not the case. The user should have to explicitly approve.

**Comment by KateChuen** [comment]
@znikola Can you comment please? We should not see the banner at all, right?

**Comment by bgambocjaviniar** [comment]
PR develop: GH-6800
PR maintenance: GH-6801

console error has already been fixed, but PR includes the issue above on hiding banner when anonymous config feature is not enabled

**Comment by bgambocjaviniar** [comment]
Closing as it is CMS-driven and please look at the documentation https://sap.github.io/cloud-commerce-spartacus-storefront-docs/anonymous-consent/#enabling-anonymous-consent 

The banner is part of the cms component, therefore you can either remove or add it depending on you needs
