### ISSUE TITLE
Order cancellation: Should redirect to login page if anonymous tries to access Order History page directly

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5841]
**Environment Details**
Spartacus: epic/order-return-cancel branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Login
- Place an order
- Go to Order History (wait until you see your order appear).
- In another browser, as an anonymous, go to this url: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/my-account/orders

**Actual Result**
The Order History page is displayed
![Screen Shot 2019-12-16 at 2 46 29 PM](https://user-images.githubusercontent.com/45409515/70938015-5faf1a80-2013-11ea-9219-9ff3eeba0b0e.png)

**Expected Result**
It should redirect to login page.

**Actual Result**
If you now login with that user, and go to Order History page, the page is also empty for that user, when it should have displayed the orders placed.
![Screen Shot 2019-12-16 at 2 47 46 PM](https://user-images.githubusercontent.com/45409515/70938031-6342a180-2013-11ea-90c3-cdd1540bf3f9.png)

**Comment by WeizhengSap** [comment]
To code reviewer: 
I have to move `AuthGuard` to page. I know it is not what we expect. But, it seems that the `AuthGuard` only can be applied to cms component type. I cannot add `AuthGuard` only to one of the tabs (Now, there are 2 tabs in our project).

**Comment by KateChuen** [comment]
Tested on dev10. It redirects to the login page now.
