### ISSUE TITLE
Order Return: Styling improvements on Return Request Details page

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5855]
**Environment Details**
Spartacus: epic/order-return-cancel branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Have a return request
- Go to Order History
- Select the return request

**Actual Result**
- The "The totals are estimated and may not include applicable taxes or other charges." should be aligned to the right.
- The item price is misaligned.
- When the return request is cancelled, there's only one "back" button, the alignment looks odd. 

<img width="1038" alt="Screen Shot 2019-12-17 at 10 28 36 AM" src="https://user-images.githubusercontent.com/45409515/71009719-b1f64700-20b8-11ea-8213-264b4a0c00cb.png">
<img width="1037" alt="Screen Shot 2019-12-17 at 10 31 16 AM" src="https://user-images.githubusercontent.com/45409515/71009720-b1f64700-20b8-11ea-8d3c-42837d51f263.png">

**Comment by developpeurweb** [comment]
An exact alignment will be hard to achieve as columns for some reason are just only approximative and change according to media queries as per screenshots below:

Large screen
![Screen Shot 2019-12-17 at 2 58 22 PM](https://user-images.githubusercontent.com/15113219/71029758-0bbd3800-20de-11ea-9ae0-c25c36b67d1a.png)

Medium screen
![Screen Shot 2019-12-17 at 2 58 57 PM](https://user-images.githubusercontent.com/15113219/71029766-1081ec00-20de-11ea-9d59-86062b8b03f8.png)

**Comment by KateChuen** [comment]
Tested on dev10.
The message "The totals are estimated and may not include applicable taxes or other charges." is . now aligned to the right.
And the back button is now aligned properly. 
The alignment of the columns too looks better now.
