### ISSUE TITLE
Order Return: Order History Page reloads after Clicking on "Back" from the Return Request Details

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5856]
**Environment Details**
Spartacus: epic/order-return-cancel branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Have a return request
- Go to Order History
- Go to the returns tab
- Select the return request
- Click on "Back" button

**Actual Result**
- The Order History page is displayed for a second, then reloads.

**Expected Result**
- Should not flick. Should be more smooth than this.

**Comment by WeizhengSap** [comment]
This issue is caused by the components contained in the tab are created twice.

**Comment by KateChuen** [comment]
Tested on dev10. It's ok now.
