### ISSUE TITLE
Styling on Order Return Pages

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5859]
**Environment Details**
Spartacus: epic/order-return-cancel branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Go to Order History
- Select an order with a product without an image

<img width="1040" alt="Screen Shot 2019-12-17 at 11 08 51 AM" src="https://user-images.githubusercontent.com/45409515/71012999-f6381600-20bd-11ea-8b7d-6fc86bba8448.png">

- Click on "Request a Return"
<img width="1039" alt="Screen Shot 2019-12-17 at 11 09 05 AM" src="https://user-images.githubusercontent.com/45409515/71013046-094ae600-20be-11ea-8d8b-a839dce7233f.png">

- Click on "Submit Request"
<img width="1041" alt="Screen Shot 2019-12-17 at 11 12 22 AM" src="https://user-images.githubusercontent.com/45409515/71013179-43b48300-20be-11ea-90d7-0337a11c69c1.png">

**Comment by developpeurweb** [comment]
This is the same bug about header and items not matching columns, this below reflect the current state:

![Screen Shot 2019-12-17 at 4 22 54 PM](https://user-images.githubusercontent.com/15113219/71036241-47123380-20eb-11ea-849c-900aa4234e64.png)

**Comment by developpeurweb** [comment]
An exact alignment will be hard to achieve as columns for some reason are just only approximative and change according to media queries as per screenshots below:

![Screen Shot 2019-12-17 at 8 41 43 PM](https://user-images.githubusercontent.com/15113219/71048634-e6e0b900-210d-11ea-9c57-690f448ec1fd.png)

**Comment by KateChuen** [comment]
Tested on dev10. Like Miguel said, not 100% aligned, but it looks better now.
