### ISSUE TITLE
Remove spartacus libs from the project's package.json.

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#586]
Lets remove the spartacus dependencies in the projects main package.json

```
    "@spartacus/core": "^0.1.0-prealpha.3",
    "@spartacus/storefront": "^0.1.0-prealpha.8",
    "@spartacus/styles": "^0.1.O0-prealpha.5",
```

Make sure they are also removed from yarn.lock, likely by using a yarn command to remove them.

**Comment by hackergil** [comment]
Pull request #592
