### ISSUE TITLE
Styling on Order Cancel Pages

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5860]
**Environment Details**
Spartacus: epic/order-return-cancel branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Go to Order History
- Select an order with a product without an image

<img width="1040" alt="Screen Shot 2019-12-17 at 11 06 16 AM" src="https://user-images.githubusercontent.com/45409515/71013397-a0b03900-20be-11ea-820f-967c6d5147c8.png">

- Click on "Cancel Items"
<img width="1036" alt="Screen Shot 2019-12-17 at 11 06 30 AM" src="https://user-images.githubusercontent.com/45409515/71013473-be7d9e00-20be-11ea-8a96-278fbe7b6a61.png">

- Click on "Continue"
<img width="1044" alt="Screen Shot 2019-12-17 at 11 06 55 AM" src="https://user-images.githubusercontent.com/45409515/71013519-cf2e1400-20be-11ea-943d-7fbd46fabf88.png">

**Comment by developpeurweb** [comment]
This is the same bug about header and items not matching columns, this below reflect the "bug" state:

![Screen Shot 2019-12-17 at 4 33 57 PM](https://user-images.githubusercontent.com/15113219/71036278-5d1ff400-20eb-11ea-8595-77d80f156a3d.png)

**Comment by KateChuen** [comment]
Tested on dev10. Like Miguel said, not 100% aligned, but it looks better now.
