### ISSUE TITLE
Order Cancellation: Try to cancel items from an order that's completed

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5861]
**Environment Details**
Spartacus: epic/order-return-cancel branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Place an order
- Go to Order History
- Select the order
- CLick on 'Cancel Items'
- Click on 'Continue'
- Wait until the order has been completed -> You get an error that it's not cancellable. 
- Click on "Back" -> No items is displayed, but the "Continue" button is enabled. 

I don't know which behaviour would be best. Maybe have a link to go back to the Order details? Or Order History? Or maybe we need a Cancel button? 

<img width="1029" alt="Screen Shot 2019-12-17 at 11 33 38 AM" src="https://user-images.githubusercontent.com/45409515/71015843-42855500-20c2-11ea-9664-ef56a4b409b2.png">
<img width="1035" alt="Screen Shot 2019-12-17 at 11 33 49 AM" src="https://user-images.githubusercontent.com/45409515/71015844-42855500-20c2-11ea-925e-07481fb01ba8.png">

**Comment by Xymmer** [comment]
If somehow someone gets to cancel page but there are no cancellable items, 
- Display message that there are no cancellable items
- Back is enabled (goes back to order details)
- Continue is grayed out

**Comment by LLink-dev** [comment]
QA steps:
•	Place an order
•	Go to Order History
•	Select the order
•	Click on 'Cancel Items'
•	Click on 'Continue'
•	Go to backoffice in a new tab and open the order. You can find orders on the left side of the navigation
•	Go to payment and delivery tab: set orderstatus to ready and save
•	in consignments tab: double click consignment, click properties tab, set to ready and save
•	Go back to the storefront and click 'Submit Request'. An error that the order is not cancelable should appear.
•	Click the back button

Expected result:
•	Page should show no entries
•	Page should show an error message, that there are no cancellable items
•	Continue button is disabled 
•	Back button is enabled
