### ISSUE TITLE
x-anonymous-consents missing in CORS config

### ISSUE THREAD

**Issue by CarlEricLavoie** [SAP/cloud-commerce-spartacus-storefront#5866]
## Environment Details

- Spartacus:  1.3
- Browser: Chrome
- OS: MacOsx

## Steps to Reproduce
Enable anonymous consent on Spartacus
Go to SmartEdit
Go Homepage (staged or online)
Use preview perspective
Click on a link to another page
## Observed Results
Error happens in the console and page does not load properly. This issue also happens through other steps.

Error in the console : 

Access to XMLHttpRequest at 'https://localhost:9002/rest/v2/electronics-spa/cms/pages?fields=DEFAULT&pageType=ContentPage&pageLabelOrId=homepage&lang=en&curr=USD' from origin 'https://localhost:4200' has been blocked by CORS policy: Request header field x-anonymous-consents is not allowed by Access-Control-Allow-Headers in preflight response.
spartacus-core.js:25301 Unknown http response error: -1

## Expected Results
The page related to the link should be opened without any error

## Offer to Fix
Yes, I will open a PR.

**Comment by Xymmer** [comment]
@CarlEricLavoie we state you have to add this in the docs
https://sap.github.io/cloud-commerce-spartacus-storefront-docs/anonymous-consent/#page-title
what would the fix be? to add to default ootb 1905?

**Comment by CarlEricLavoie** [comment]
Hi Bill I opened a PR on the documentation repo. See linked PR above

**Comment by CarlEricLavoie** [comment]
Ah sorry I miss read you are correct I missed it. Closing this ticket
