### ISSUE TITLE
Payment methods failing due to delivery mode DOM element not found

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#5867]
At times, the payment method cannot find the input with id _#deliveryMode-standard-gross_ and the e2e test will fail.

Maybe find a different way to get that element? Maybe different selector is more consistent?

projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/payment-methods.e2e-spec.ts

Logs here: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/560/consoleFull

**Comment by Matejk00** [comment]
Solution for this ticket provided in #6152
