### ISSUE TITLE
Add note about update delay after submitting cancel or return

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5881]
When submitting a cancellation or return request, display a note under the buttons

"Please note that it may take a few moments for your order to reflect the request."

**Comment by KateChuen** [comment]
Tested on dev10. Now there's a note when we submit a return request, or a cancel item request. 

![Screen Shot 2020-01-03 at 1 49 00 PM](https://user-images.githubusercontent.com/45409515/71825651-47f31100-306a-11ea-9010-fa63994af70a.png)

![Screen Shot 2020-01-03 at 1 54 39 PM](https://user-images.githubusercontent.com/45409515/71825652-47f31100-306a-11ea-979c-0c3bdad16ff0.png)


We don't have a note when we cancel a return request (but then again, there's no confirmation page for this request. Once we click on the button, it goes through). @Xymmer should we have one there?
