### ISSUE TITLE
CmsComponentData returning undefined for uid and data$

### ISSUE THREAD

**Issue by JaveedShaiks** [SAP/cloud-commerce-spartacus-storefront#5883]
```typescript
import { CmsComponentData } from '@spartacus/storefront';
import { CmsComponent } from '@spartacus/core';


export class customComponent extends CmsComponentData<CmsComponent> {
  component: any;

  public getText(): any {
    console.log('text', this.uid);
    return this.uid;
  }
}
```

uid and data$ returning undefined

**Comment by JaveedShaiks** [comment]
`export class customComponent implements OnInit {
  ComponentData = {};
  constructor(
    public component: CmsComponentData<CmsComponent>
  ) {}

  ngOnInit(): void {
    this.getText();
  }
  public getText(): any {
    return this.component.data$.subscribe(data => {
      return this.ComponentData = data;
    })
  }
}`

**Comment by tobi-or-not-tobi** [comment]
correct, the `CmsComponentData` is not a class you can extend from. It's injected in the component injector tree, so you can use make a reference in the component constructor. 

btw, I'd refactor to (assuming there's a `text` property):

```
export class customComponent implements OnInit {
  text$: Observable<string> = this.component.data$.pipe(map(data => data.text));

  constructor(
    private component: CmsComponentData<CmsComponent>
  ) {}
}
```

so, you can use `{{text$ | async}}` in your view.
