### ISSUE TITLE
Update Spa CCv2 configuration properties

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#589]
Update the manifest to include the following properties:

* electronics store url (http)
* electronics store url (https)
* CORS filter for all extensions (should be specific for localhost:4200 and github pages)

**Comment by hackergil** [comment]
Will be tested on the next deployment to CCv2 (1905)

**Comment by plabadie** [comment]
Added comment on the commit

**Comment by hackergil** [comment]
CCv2 Deployment is failing. Looking for some help internally.

**Comment by hackergil** [comment]
After chatting with @plabadie we decided to skip CORS configs for now
