### ISSUE TITLE
Order Details: Move Back/Cancel/Return row to bottom

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#5894]
For Order Details page, the mission was to add Cancel/Return actions but not make them prominent.  Currently they are very prominent when you get to order details.

Two changes Miguel and I agreed on:
1) Move the order actions (cx-order-details-actions) to the bottom
2) The Cancel and Return buttons, don't make them primary (so they appear white I think)

Reasoning: 
For doing (1), this is the simplest option given we we are trying to release an RC asap. "Back" is a process button (to go back to order listing) but cancel/return buttons are not - they should have been separated, but we're looking at "least change" because of time.

For (2), the buttons that initiate a cancel or return can appear at the same time. However, neither button is a primary action (unlike Check Out on Cart page). I'd rather these be links even but we're trying to keep changes to a minimum.

Current visual with Sparta styling (Calydon looks better :) 
<img src=https://user-images.githubusercontent.com/4998145/71184103-38409380-2247-11ea-9b45-5cf8daf75366.png width=600/>

**Comment by WeizhengSap** [comment]
sample data PR is this: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/56

**Comment by developpeurweb** [comment]
This is done. It should now look like this:

![Screen Shot 2019-12-19 at 1 17 42 PM](https://user-images.githubusercontent.com/15113219/71200296-c4fa4a00-2265-11ea-920c-49a8fd01ec67.png)
![Screen Shot 2019-12-19 at 1 19 57 PM](https://user-images.githubusercontent.com/15113219/71200297-c4fa4a00-2265-11ea-939a-bb2888a09e72.png)
