### ISSUE TITLE
Registration E2E tests / SPA-1021

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#59]
For other E2E tests, we decided to focus on where backend adds value or can influence or cause breakage.

The assumption is that these kinds of tests are in addition to what Stan already is working on, so check with him. E.g. you can register successfully, and the user is logged in.
h2. 1. Error situation + check what happens when user tries to register with existing username
 * Register a user with an email that is already registered
 * Should get an error message (global messaging for registration)
 * Angular page stays on same page; user can keep trying to register
 * Most information remains on page
 * And the valid user should not be blocked from logging in
 ** Unless there is some kind of protection if you try 5 times or more
 * Because if this breaks: something changed in the backend
 * Future: Captcha?

h2. T&C link
 * Clicking T&C gives you the page and OK response

h2. Cart merging tests that aren’t in big e2e test
 * Anonymous user has items in cart, logs in, new cart has all items
 * Logged in user adds items to cart, logs out, adds items to cart, logs in, carts merged

The following would be Angular unit tests as they don't touch the backend.
 * Not allowing submit if salutation not chosen, fields don't meet requirements, etc.
 * Email or password validation
 * Not allowing submit if T&C not checked

**Comment by marlass** [comment]
Changes only in test code. E2E tests pass and it follows the provided scenario. Closing.
