### ISSUE TITLE
Orders not refetched on language change

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#5906]
Orders are not refetched when changing language on the orders history page.

I am assuming that this part of the code was responsible for that: https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/09178e236c0e8ab3103d0f764226a74499ab4eff#diff-4af0ef5ee6b5e8728fa6e5bb985ff8e8

**Comment by WeizhengSap** [comment]
OrderHistory data is not `misc` data. So, in effect, it's better not listen to this `UserActions.CLEAR_USER_MISCS_DATA` action, but listen to the context change actions.

**Comment by kacperknapik** [comment]
**QA results:** works as expected
