### ISSUE TITLE
cxOutletRef not displaying component on navigation

### ISSUE THREAD

**Issue by morinellipy** [SAP/cloud-commerce-spartacus-storefront#5942]
When using cxOutletRef and cxOutletPos, component does not get rendered on navigation.

## Environment Details

- Spartacus:  1.3.1 and 1.4rc
- Browser: Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- Other environment details: Angular v8.2.14

## Steps to Reproduce
1) Use outlet like so in app.component.html:
`<ng-template cxOutletRef="LandingPage2Template" cxOutletPos="before">
  hello world
</ng-template>`

2) Start on cart page.

3) Navigate to home page.

Stackblitz example:
 1) Go to https://spartacus-cd-w5gv3z.stackblitz.io/cart . Please make sure this is your starting point.

2) Click on SAP logo (go to home page), you should navigate to https://spartacus-cd-w5gv3z.stackblitz.io/

3) "hello world" does not display as defined on app.component.html through cxOutletRef

**Stackblitz reference**: https://stackblitz.com/edit/spartacus-cd-w5gv3z
Please check app.component.html where cxOutletRef="LandingPage2Template" cxOutletPos="before" is defined

## Observed Results

Hello world text is not displayed

## Expected Results
Hello world text should be displayed

## Offer to Fix
NO

**Comment by marlass** [comment]
Findings for solution:
- cxOutletPos is not needed. Happens on every option `before`, `after` and replace.

**Comment by Zeyber** [comment]
Server QA: 
- Start on cart page, no "hello world" text.
- Navigate to landing page, there is "hello world" text.
- Navigate away from landing page, "hello world" text disappears.
