### ISSUE TITLE
NavigationNodes(cx-category-navigation) with CMS restrictions(e.g. loggedInUser) not shown until a Browser refresh

### ISSUE THREAD

**Issue by gitshamster** [SAP/cloud-commerce-spartacus-storefront#5969]
## Environment Details

- Spartacus:  1.3.0 (but should be the same in 1.4.0-RC.0
- Browser: Firefox 64.0.2 , Chrome 79.0.3945.88
- OS: Windows 10 1909
- Device: Dell Precision 7530
- Other environment details: Angular 8.2.9

## Steps to Reproduce
1. Configure one of the existing Navigation Links with a user restriction ('Logged in User') in BackOffice or SmartEdit. e.g. CamerasFlashesCategoryLink
2. The link is not shown for anonymous user in Spartacus. 
3. Login with registered user
4. The link is still not visible.
![inititial-screen_with_user_restrictions_noLink](https://user-images.githubusercontent.com/29032953/71680431-5ac7c600-2d8a-11ea-81d2-baa93dfa797e.png)

## Observed Results
 Even though I could see the Link value in the JSON responses, the same is not rendered in the Category Header of SPA.

The intended Navigation Link is rendered only if I refresh the browser window

## Expected Results
After login. The user should be able to see the Navigation Link (for example - CamerasFlashesCategoryLink )
While there are related bugs on this topic - #4603 and #3769 

It would be great if we could have some hint to a temporary solution while waiting for a fix in a future release

## Additional Information - Things tried out so far: 
1. Overritten the category-navigation-component and printed time-stamp to see if the component is actually updated. The time-stamp is printed correctly, but yet the ''CamerasFlashesCategoryLink'' is still not shown in the Category Header.

2 . I have tried with calling cmsService.refreshPage() and cmsService.refreshComponent('CamerasFlashesCategoryLink') but that too did not succeed

Sample code
`this.auth.isUserLoggedIn().pipe(
      distinctUntilChanged(),
      filter(( isLoggedIn: boolean ) => {
          return isLoggedIn === true;
      }),
      map((event: boolean) => {
        console.log('Login Changes in SwitchMap..');
        this.categoryNavigationService.setLoadPage(true);
        return event;
      })
    ).subscribe(
      (loggedIn: boolean) => {
        console.log('Login Changes..');
        this.reloadPage = loggedIn;
        //this.cmsService.refreshComponent('NavigationBar');
        //this.cmsService.refreshComponent('CategoryNavigationComponent');
        //this.cmsService.refreshComponent('AriCategoryNavigationComponent');
        this.cmsService.refreshComponent('CamerasFlashesCategoryLink');
        setTimeout(()=>{
          this.cmsService.refreshLatestPage();
          this.cmsService.refreshComponent('CamerasFlashesCategoryLink');
          this.cmsService.refreshPageById('homepage');
        },3000);`

![Not_loaded](https://user-images.githubusercontent.com/29032953/71680392-44216f00-2d8a-11ea-8dfc-300605021735.png)

**Comment by marlass** [comment]
I will take a look into this issue. Thanks for reporting it

**Comment by Xymmer** [comment]
Hey Marcin, can you assess this and see if we can fix for 1.5.0 release, otherwise we can fix for 1.5.1.

**Comment by giancorderoortiz** [comment]
Retested with "Blank Videotapes" subcategory. It works as expected. 

Anonymous user: "Blank Videotapes" not shown. 
![Screen Shot 2020-02-13 at 5 41 39 PM](https://user-images.githubusercontent.com/46171897/74485311-742f5800-4e88-11ea-973f-9747484aceba.png)

Signed-In user: "Blank Videotapes" shown. 

![Screen Shot 2020-02-13 at 5 42 58 PM](https://user-images.githubusercontent.com/46171897/74485345-8dd09f80-4e88-11ea-9567-2ccb15fbceb3.png)
![Screen Shot 2020-02-13 at 5 43 05 PM](https://user-images.githubusercontent.com/46171897/74485357-8f9a6300-4e88-11ea-91ce-f62385f86083.png)
