### ISSUE TITLE
Improve product loading performance for variants logic

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#5972]
Currently, variant guard uses an unscoped product data which is not optimal. We should:
1. Use scope to get product data
2. Consider creating specialized scope for variant data

**Comment by mirkosoft** [comment]
QA steps:

- When opening a PLP page with variants (or not purchasable one), additional call for product data should contain only minimum required fields (no categories, classifications, etc.)
