### ISSUE TITLE
Regression test all new facades

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#6]
This ticket is to regression test all facades.
Documentation is #416.

Original master description:

While we're using ngrx store inside, we like customers to not necessarily be bother with the complexity of ngrx. Moreover, we might want to move (partially) to other state management solutions in the future. We've already started to build a facade layer on top of ngrx store, and must finalise this for all ngrx services.

- add facades as services in a facade folder
- all methods should be public or protected (assess as we go)
- any components/services outside store should use facades instead of use store directly
- update all tests (outside store) to use facades, remove StoreModule from tests if possible

Spike was done as part of #140. Tobias and Wei working on it and probably done eod Nov 1.
It can be used as an example for the facade (but not the move).

**Comment by Xymmer** [comment]
closing this one as we will do one regression test for load once, facades, and all the other recnet refactoring work.
