### ISSUE TITLE
Currency E2E test / SPA-945

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#60]
For other E2E tests, we decided to focus on where backend adds value or can influence or cause breakage.

The assumption is that these kinds of tests are in addition to what Stan already is working on, so check with him. E.g. you can register successfully, and the user is logged in.

----

For E2E purposes, some suggestions:
 * Check that the menu is there and populated (even if there is only 1 currency right now it's still there I think)
 * Changing the currency refreshes pricing only

 * 
 ** ...but stay on same page/view/screen.
 ** In fact if you are in the middle of checking out, adding an address in a form, and change the currency, your entire form should remain the same.

Product details page is a good one to make assertions from. Check that prices updated to expect new amounts. But also, a checkout form like shipping address to ensure the user's data isn't erased.

Also: do a browser refresh after switching the currency/language, to make sure the change sticks beyond the explicit change request from the user. (and doesn;t fall immediately back to the default).

The backend sample data has US dollars and Japanese Yen, 

Note that language and currency e2e tests are similar in scope - see SPA-944.

**Comment by Matejk00** [comment]
QA done, currency switcher e2e tests provided.
