### ISSUE TITLE
Change schematics versioning to more automatic with pulling version from package.json

### ISSUE THREAD

**Issue by psmul** [SAP/cloud-commerce-spartacus-storefront#6001]
As we want to keep our Schematics version aligned with other Spartacus libs, we need to automate version bumping.
The proposed approach is to take the current lib version from package.json file.

**Comment by psmul** [comment]
QA steps:
- go to `projects/schematics`
- (only for a time of QA) change version in *package.json* to 1.1.1
- build project, run command `yarn build`
- pack project with the command `npm pack`
- go to a different folder (outside of the project) and create new, clean angular application (preferably with SCSS styling)
- go to fresh project main folder and run the command 
`ng add <path to packed schematics tar.gz file> `


Expected result:
- the newly created application should have spartacus@1.1.1 in it's package.json

**Comment by Matejk00** [comment]
QA done, after QA steps _spartacus@1.1.1_ packages exists in package.json, so it's working as expected.
