### ISSUE TITLE
cart e2e tests failing due to global message not appearing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6018]
During the daily regression test run, the cart e2e test has been consistently failing for a while.

Logs here: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/727/consoleFull

<img width="1050" alt="Screen Shot 2020-01-08 at 10 23 44 AM" src="https://user-images.githubusercontent.com/30666844/71990197-fa5cdc80-3200-11ea-933c-8a9a96650911.png">

![Screen Shot 2020-01-08 at 10 36 12 AM](https://user-images.githubusercontent.com/30666844/71991209-b8349a80-3202-11ea-8e82-e3fcebe5cb43.png)

**Comment by Zeyber** [comment]
Tested against dev-17 on develop. All tests pass.
