### ISSUE TITLE
prevent upgradability issues for cancel and returns

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#6019]
For 2.0 we're changing several patterns. With the release of the cancel/returns feature we try to prevent a lot of refactoring or breaking changes. We've taken the following into account:
- the item counter is refactored for release 2.0 and is driven by form controls. We'll refactor the code base to ensure we have a smooth transition. 
- we leverage for validation for the quantity added rather than implementing custom logic
- reuse the form validation logic during page guarding
- we've dropped hard-coded routes so that cancel and return routes can be controlled by the CMS
- fixed a bug with the redirect from the confirmation pages, as the orderCode is not available in the route
- leverage form data for the state
- avoid a form array for the order entries since the future cart entries do not have index based order entries
- improve templates
- delegate control logic to services
- avoid too much constructor arguments and component inputs
- moved hardcoded content to CMS content from the confirmation pages.

**Comment by tobi-or-not-tobi** [comment]
PR for CMS sample data added: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/59

**Comment by KateChuen** [comment]
QA steps please?
