### ISSUE TITLE
Add `withdrawOn` to public API

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#6038]
`withdrawOn` RxJS operator might be handy to developers creating ngrx effects that want to take into account context change in the middle of processing. This could avoid incorrect states. Apart from publishing it in public API we need to document this (in docs, mention about this operator would be helpful in doc related to language/currency change, site context) operator behavior and present simple use cases to explain it usefulness.

**Comment by kacperknapik** [comment]
**QA results**
- `withdrawOn` is available in public API
