### ISSUE TITLE
[kate retest] both consignments get cancelled when we cancel only one item from one consignment

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#6047]
(also see #6065)

**Environment Details**
Spartacus: develop branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD
_**With basic fulfillment process.**_

**Steps to Reproduce**
- Place an order with the following products (1 of each): _816261_, _816323_, _812888_
- Go to order history and go to the order.
- Might need to wait a bit, and do some refreshing, until the order is displayed in consignments.
- Then go ahead, and cancel 1 item from the first consignment.
- Then wait until the order is completed. 

**Actual Result**
You'll then see that both consignments have the status "Cancelled". And the Qty won't be updated.

![Screen Shot 2020-01-10 at 1 26 18 PM](https://user-images.githubusercontent.com/45409515/72176934-91ff2e00-33ad-11ea-904f-6324405fc027.png)

**Comment by KateChuen** [comment]
In the console: 

https://dev-com-10.accdemo.b2c.ydev.hybris.com:9002/rest/v2/electronics-spa/users/current/orders/00000130/cancellation?lang=en&curr=USD
Request Method: POST
Status Code: 200 
cancellationRequestEntryInputs: [{orderEntryNumber: 0, quantity: 1}, {orderEntryNumber: 1, quantity: 0},…]
0: {orderEntryNumber: 0, quantity: 1}
1: {orderEntryNumber: 1, quantity: 0}
2: {orderEntryNumber: 2, quantity: 0}

Server Logs:
INFO   | jvm 1    | main    | 2020/01/10 19:12:59.773 | INFO  [hybrisHTTP26] [10.6.35.246] [DefaultWarehouseAdapterMock] MOCK: Order cancel request is being sent to the Warehouse. Cancel will proceed after a response from the Warehouse is received
INFO   | jvm 1    | main    | 2020/01/10 19:12:59.773 | INFO  [hybrisHTTP26] [10.6.35.246] [WarehouseProcessingCancelRequestExecutor] order: 00000130 is being cancelled

**Comment by Xymmer** [comment]
Testing 1: Saw this error, unrelated (and saw notification)
ERROR [hybrisHTTP8] [RestHandlerExceptionResolver] item 8796093485973 no longer valid (was removed): object no longer valid

**Comment by Xymmer** [comment]
Testing Kate's steps locally with 1905.9 b2c_acc_plus + oms + sample data addon: 
- Added the 3 products, waiting for consignments, cancelled 1st product (white camera):
- Result: First product cancelled, others still waiting for delivery.

![image](https://user-images.githubusercontent.com/4998145/72295770-32f81e00-3626-11ea-968a-4d1d9b7e0831.png)

**Comment by KateChuen** [comment]
Cannot reproduce with omsfulfillment. 1905.9 with spartacus recipe, with 2005 occ extensions. 
Now I see the same behavior as Bill. Can close.
