### ISSUE TITLE
Display cancelled consignments last + other improvements

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#6051]
As received, at top
  IN_TRANSIT = ‘IN_TRANSIT’,
  READY_FOR_PICKUP = ‘READY_FOR_PICKUP’,
  READY_FOR_SHIPPING = ‘READY_FOR_SHIPPING’,
  WAITING = ‘WAITING’,
  DELIVERING = ‘DELIVERING’,
  PICKPACK = ‘PICKPACK’,
  PAYMENT_NOT_CAPTURED = ‘PAYMENT_NOT_CAPTURED’,
  READY = ‘READY’,
  DELIVERY_REJECTED = ‘DELIVERY_REJECTED’,
  SHIPPED = ‘SHIPPED’,
  TAX_NOT_COMMITED = ‘TAX_NOT_COMMITED’,
2nd Last
  PICKUP_COMPLETE = ‘PICKUP_COMPLETE’,
  DELIVERY_COMPLETED = ‘DELIVERY_COMPLETED’,
Last
  CANCELLED = ‘CANCELLED’,
VERY LAST >>>> new ticket
  Unconsigned, but cancelled (quantity=0) (edited) 

old description:
When part of a consignment is cancelled with OMS, OMS strategy is to cancel the entire consignment and create a new one based on what products are left. 
![image](https://user-images.githubusercontent.com/4998145/72190285-2a58db00-33cd-11ea-8536-2de32a578f34.png)

One solution: Let's move these to the bottom.
1. Items in progress at the top
2. Items picked up or shipped / done in middle
3. Items cancelled at the bottom
3a. Items never had consignments at the very bottom (#6066)

because... if a consignment is cancelled, it's no longer used.
However it still contains all the things that are supposed to be shipped.

**Comment by bgambocjaviniar** [comment]
PR: GH-6084

Rules changed from above. PR still reflects old conditions.

New Rules:
```
Theme:
at the top: any incomplete status
middle: we know it’s delivered or picked up
last: cancelled items (2 of them)
Randomly at top
  IN_TRANSIT = ‘IN_TRANSIT’,
  READY_FOR_PICKUP = ‘READY_FOR_PICKUP’,
  READY_FOR_SHIPPING = ‘READY_FOR_SHIPPING’,
  WAITING = ‘WAITING’,
  DELIVERING = ‘DELIVERING’,
  PICKPACK = ‘PICKPACK’,
  PAYMENT_NOT_CAPTURED = ‘PAYMENT_NOT_CAPTURED’,
  READY = ‘READY’,
  DELIVERY_REJECTED = ‘DELIVERY_REJECTED’,
  SHIPPED = ‘SHIPPED’,
  TAX_NOT_COMMITED = ‘TAX_NOT_COMMITED’,
2nd Last
  PICKUP_COMPLETE = ‘PICKUP_COMPLETE’,
  DELIVERY_COMPLETED = ‘DELIVERY_COMPLETED’,
Last
  CANCELLED = ‘CANCELLED’,
VERY LAST >>>> new ticket
  Unconsigned, but cancelled (quantity=0)
```

Would need advice on above as I tried other things which I left commented in the PR

**Comment by KateChuen** [comment]
The following is displayed in this order:

ON TOP (RANDOM)
- [x] IN_TRANSIT -> In Transit
- [x] READY_FOR_PICKUP -> Ready for Pickup
- [x] READY_FOR_SHIPPING -> Ready for Shipping
- [x] WAITING -> Waiting
- [x] DELIVERING -> Delivering
- [x] PICKPACK -> Preparing for Shipment
- [x] PAYMENT_NOT_CAPTURED -> Payment Issue
- [x] READY -> In Process
- [x] DELIVERY_REJECTED -> Delivery Rejected
- [x] SHIPPED -> Shipped
- [x] TAX_NOT_COMMITED -> Tax Issue

MIDDLE
- [x] PICKUP_COMPLETE -> Pickup Complete
- [x] DELIVERY_COMPLETED-> Delivery Complete

BOTTOM
- [x] CANCELLED -> Cancelled
- [x] Pending

![Screen Shot 2020-01-16 at 11 00 41 AM](https://user-images.githubusercontent.com/45409515/72543237-708dbe80-3853-11ea-91dc-4dd1e4daafb4.png)

- With Pending status
![Screen Shot 2020-01-16 at 11 24 52 AM](https://user-images.githubusercontent.com/45409515/72543247-74214580-3853-11ea-9e25-674267f0efd9.png)
