### ISSUE TITLE
[GH-6052] Fix Visual Focus differences between Windows and Mac Browsers

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#6052]
**This is a master ticket that fixes around 33 tickets, it can be closed once all referenced tickets below are closed.**

As per screenshot, there are some differences on how the visual focus is displayed, elements to be fixed:

- [x] input fields
- [x] select fields
- [x] ngselect
- [x] radio buttons
- [x] checkboxes
- [x] anchors (links, banners, company logo)
- [x] buttons
- [x] textarea (reviews)

**Windows/Chrome**
<img width="785" alt="Win Chrome" src="https://user-images.githubusercontent.com/15113219/72196719-3f8f3300-33e8-11ea-8f5d-3e3f98cc54ed.png">

**Mac/Chrome**
![Mac Chrome](https://user-images.githubusercontent.com/15113219/72196737-47e76e00-33e8-11ea-9ef5-dabb26f67397.png)

**Windows/Firefox**
<img width="658" alt="Win Firefox" src="https://user-images.githubusercontent.com/15113219/72196749-5afa3e00-33e8-11ea-9298-967b193043c4.png">

**Mac/Firefox**
![Mac Firefox](https://user-images.githubusercontent.com/15113219/72196760-6cdbe100-33e8-11ea-8e7e-b9f34421b21b.png)

**Comment by developpeurweb** [comment]
**For QA:**

- The purpose of this ticket is to standardize cross-browser/cross-platform look & feel of the visible focus outline.
- Visible focus outline overlapping adjacent ui elements may happen and may not be an issue, if in doubt please open a ticket per element.
- For now the visible focus outline only works when theme `calydon` is enabled.
- For Safari testing please refer to the settings detailed in ticket GH-5041.

**Comment by KateChuen** [comment]
Caine and Kacper tested on Windows.
While the Mtl team tested on Mac.
