### ISSUE TITLE
Improve generic pagination component

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#6060]
There are several issues with the current pagination component, related to user experience as well as reusability/extensibility. 

From a user experience point of view, we like the pagination component to act like this: 
- Show maximum 3 pages at a time
- Center the current page if possible
- Add links to navigate to the start («) and end (») with one click
- Use anchor links for navigation
- Provide accessibility for the links
- pages should be disabled if they're active  
  (i.e. disable start link on the first page)

This results in the following experience.

From a extensibility point of view, we like to support the following:
- Allow for other pagination experiences:
  - Always show first and last page
  - Add a previous / next button (on top of first / last)
  - Add gap indicators (dots) for hidden pages at the beginning and end
- Control the pagination options with CSS  
  All pagination functions are offered by default, but *enabled* by CSS display properties
- Extend pagination builder with angular DI

In order allow for a flexible setup, the page building mechanism will take all features into account, while the actual UI will be limited by CSS. This allows for an easy customisation of the pagination. 

The visual below shows the Spartacus preferred version on the left, where as the full available pagination is shown on the right. 

![image](https://user-images.githubusercontent.com/4745807/72349009-f686f980-36db-11ea-87f1-51148e8a87d6.png)

**Comment by tobi-or-not-tobi** [comment]
Issues we have currently with pagination:
- CSS hovering issues
- previous page is not always available (i.e. if you're on the 4th page)
- next page is not always available (i.e if you're on the 3rd page)
- previous / next buttons are not configurable
- are shown when there's only 1 page
- pagination logic is in component (not extensible)
- no indexable (using click events instead of anchor links)
- not accessible (partially fixed by accessibility branch, but given that it's using click event still not working)

**Comment by tobi-or-not-tobi** [comment]
New insides from Anthony:
- forget about first and last as explicit navigable numbers
- use double chevron for first and last

With this, the pagination component becomes much more concise, which is great, specifically on mobile. 

Give that we have most of the feature already in place, we are keen to keep it configurable, allow for some customers or some places in the storefront to keep more advanced pagination. 

![image](https://user-images.githubusercontent.com/4745807/72272538-16111a00-3629-11ea-9d5a-b7e00770b3fb.png)

**Comment by tobi-or-not-tobi** [comment]
Fixed with 2.0

**Comment by Xymmer** [comment]
To summarize what Tobias told me about this ticket, it fixes these issues:
#3045, #5631, #4632, #5487, #3856, #3118

**Comment by tobi-or-not-tobi** [comment]
QA:
- ensure that Spartacus renders a minimum pagination object everywhere with maximum 3 pages (`range`) and a `start` and `end` button. 
- configure the pagination component with various options, ensure it works nicely.

**Comment by KateChuen** [comment]
Tested on dev10. 
The pagination works well now. Only 3 pages are displayed at a time, with a "start" and "end" button. 

<img width="797" alt="Screen Shot 2020-03-02 at 2 21 41 PM" src="https://user-images.githubusercontent.com/45409515/75709709-348eab80-5c91-11ea-883d-9ef7a028c9c7.png">

The active page is centered, except for the first and last page as expected. 
<img width="407" alt="Screen Shot 2020-03-02 at 2 22 37 PM" src="https://user-images.githubusercontent.com/45409515/75709766-4a9c6c00-5c91-11ea-9112-392ec4c90617.png">
<img width="432" alt="Screen Shot 2020-03-02 at 2 22 32 PM" src="https://user-images.githubusercontent.com/45409515/75709775-4e2ff300-5c91-11ea-94bf-075dd44af5ae.png">

The active page button is disabled. So are the start and last page buttons when the first page and last page is active. 
We can always go to the next and previous page now. 
The pages have accessibility.



When there's only one page, the pagination is not displayed. 
<img width="1252" alt="Screen Shot 2020-03-02 at 9 52 01 AM" src="https://user-images.githubusercontent.com/45409515/75687880-7f49fc80-5c6c-11ea-8c46-da37a186b5a5.png">


Pagination is displayed when there's at least 2 pages.
<img width="1232" alt="Screen Shot 2020-03-02 at 9 54 45 AM" src="https://user-images.githubusercontent.com/45409515/75687873-7b1ddf00-5c6c-11ea-950f-094536a048e4.png">

**Comment by KateChuen** [comment]
Tested with the following config:

```
ConfigModule.withConfig({
    pagination: {
        addFirst: true,
        addLast: true,
        addDots: true
    }
}),
```

There's always the first and last page displayed.
Then the active page is in the center. Then we always have the previous and next page.
And the dots in between is disabled. 
Active page is disabled. 
And we have a start and end button.
<img width="1262" alt="Screen Shot 2020-03-02 at 11 55 41 AM" src="https://user-images.githubusercontent.com/45409515/75706442-2a69ae80-5c8b-11ea-9539-fe83ce82f28a.png">

<img width="979" alt="Screen Shot 2020-03-02 at 11 57 39 AM" src="https://user-images.githubusercontent.com/45409515/75706561-61d85b00-5c8b-11ea-8037-aea46b08d298.png">

<img width="1279" alt="Screen Shot 2020-03-02 at 11 55 50 AM" src="https://user-images.githubusercontent.com/45409515/75706471-3c4b5180-5c8b-11ea-96ad-43ceabc4897e.png">

 <img width="1048" alt="Screen Shot 2020-03-02 at 11 58 30 AM" src="https://user-images.githubusercontent.com/45409515/75706598-6ef54a00-5c8b-11ea-8910-ebbb0eeb921c.png">

<img width="918" alt="Screen Shot 2020-03-02 at 11 58 36 AM" src="https://user-images.githubusercontent.com/45409515/75706601-6f8de080-5c8b-11ea-919d-9aee9677c817.png">

```
ConfigModule.withConfig({
    pagination: {
        addFirst: false,
        addLast: true,
        addDots: true
    }
}),
```

There's no first page, only the last page is always displayed.
Then the active page is in the center. Then we always have the previous and next page.
And the dots in between. 
Active page is disabled. 
And we have a start and end button.

<img width="893" alt="Screen Shot 2020-03-02 at 1 43 19 PM" src="https://user-images.githubusercontent.com/45409515/75707066-3dc94980-5c8c-11ea-91ad-0d122effce5b.png">
<img width="901" alt="Screen Shot 2020-03-02 at 1 43 40 PM" src="https://user-images.githubusercontent.com/45409515/75707068-3efa7680-5c8c-11ea-9e58-36088a1ed1b5.png">

```
ConfigModule.withConfig({
    pagination: {
        addFirst: false,
        addLast: false,
        addDots: true
    }
}),
```

There's no first and last page displayed.
Then the active page is in the center. Then we always have the previous and next page.
And the dots in between. 
Active page is disabled. 
And we have a start and end button.
<img width="876" alt="Screen Shot 2020-03-02 at 1 48 12 PM" src="https://user-images.githubusercontent.com/45409515/75707390-cfd15200-5c8c-11ea-840c-eb2998ece8d0.png">
<img width="810" alt="Screen Shot 2020-03-02 at 1 48 22 PM" src="https://user-images.githubusercontent.com/45409515/75707395-d1027f00-5c8c-11ea-8965-6e4b805cfa25.png">

```
ConfigModule.withConfig({
    pagination: {
        addFirst: true,
        addLast: false,
        addDots: true
    }
}),
```

There's only a first and the last page is not displayed.
Then the active page is in the center. Then we always have the previous and next page.
There's dots in between. 
Active page is disabled. 
And we have a start and end button.
<img width="705" alt="Screen Shot 2020-03-02 at 1 58 46 PM" src="https://user-images.githubusercontent.com/45409515/75708053-0bb8e700-5c8e-11ea-994f-9e706526f0a8.png">
<img width="668" alt="Screen Shot 2020-03-02 at 1 58 57 PM" src="https://user-images.githubusercontent.com/45409515/75708054-0c517d80-5c8e-11ea-9740-aff332940ea0.png">
<img width="586" alt="Screen Shot 2020-03-02 at 1 59 10 PM" src="https://user-images.githubusercontent.com/45409515/75708055-0c517d80-5c8e-11ea-8c88-38708825bcfa.png">


```
ConfigModule.withConfig({
    pagination: {
        addFirst: true,
        addLast: true,
        addDots: false
    }
}),
```

There's always a first and last page displayed.
Then the active page is in the center. Then we always have the previous and next page.
There's no dots in between. 
Active page is disabled. 
And we have a start and end button.
<img width="910" alt="Screen Shot 2020-03-02 at 1 54 19 PM" src="https://user-images.githubusercontent.com/45409515/75707808-96e5ad00-5c8d-11ea-9f4e-31f29afdfa9e.png">
<img width="795" alt="Screen Shot 2020-03-02 at 1 54 30 PM" src="https://user-images.githubusercontent.com/45409515/75707811-977e4380-5c8d-11ea-9f62-a6a9ce9f9926.png">

```
ConfigModule.withConfig({
    pagination: {
        addFirst: true,
        addLast: false,
        addDots: false
    }
}),
```

There's always a first page displayed but no last page.
Then the active page is in the center. Then we always have the previous and next page.
There's no dots in between. 
Active page is disabled. 
And we have a start and end button.

<img width="514" alt="Screen Shot 2020-03-02 at 2 10 04 PM" src="https://user-images.githubusercontent.com/45409515/75708883-a665f580-5c8f-11ea-9bd2-54cc9a818f70.png">


```
ConfigModule.withConfig({
    pagination: {
        addFirst: false,
        addLast: true,
        addDots: false
    }
}),
```

There's always a last page displayed but no first last page.
Then the active page is in the center. Then we always have the previous and next page.
There's no dots in between. 
Active page is disabled. 
And we have a start and end button.

<img width="794" alt="Screen Shot 2020-03-02 at 2 14 38 PM" src="https://user-images.githubusercontent.com/45409515/75709225-41f76600-5c90-11ea-90a5-1a044891e06e.png">


```
ConfigModule.withConfig({
    pagination: {
        addFirst: false,
        addLast: false,
        addDots: false
    }
}),
```

There's no first and last page displayed.
Then the active page is in the center. Then we always have the previous and next page.
There's no dots in between. 
Active page is disabled. 
And we have a start and end button.
<img width="547" alt="Screen Shot 2020-03-02 at 2 18 34 PM" src="https://user-images.githubusercontent.com/45409515/75709498-c6e27f80-5c90-11ea-95c2-9eac82fe4bbd.png">

**Comment by tobi-or-not-tobi** [comment]
@KateChuen thanks for the thorough QA! There are actually a few more props to test which you can find in the docs - but this is already great.

**Comment by KateChuen** [comment]
Thanks for pointing it out, I've added a couple extra tests with all the parameters:

```
ConfigModule.withConfig({
    pagination: {
        addFirst: true,
        addLast: true,
        addDots: true,
        addStart: true,
        addEnd: true,
        addPrevious: true,
        addNext: true,
        rangeCount: 4
    }
}),
```

<img width="936" alt="Screen Shot 2020-03-03 at 9 31 57 AM" src="https://user-images.githubusercontent.com/45409515/75785936-7faccb00-5d32-11ea-8276-499e2386c764.png">

```
ConfigModule.withConfig({
    pagination: {
        addFirst: true,
        addLast: true,
        addDots: true,
        addStart: false,
        addEnd: false,
        addPrevious: true,
        addNext: true,
        rangeCount: 1
    }
}),
```

<img width="920" alt="Screen Shot 2020-03-03 at 9 44 43 AM" src="https://user-images.githubusercontent.com/45409515/75786677-a4557280-5d33-11ea-8082-18445636541d.png">


```
ConfigModule.withConfig({
    pagination: {
        addFirst: true,
        addLast: true,
        addDots: true,
        addPrevious: true,
        addNext: true,
        rangeCount: 11
    }
}),
```

<img width="847" alt="Screen Shot 2020-03-03 at 9 51 08 AM" src="https://user-images.githubusercontent.com/45409515/75787328-8b998c80-5d34-11ea-9b2c-aa8c36829259.png">

```
ConfigModule.withConfig({
    pagination: {
        addFirst: true,
        addLast: true,
        addDots: true,
        addPrevious: true,
        addNext: true,
        rangeCount: 1
    }
}),
```
<img width="636" alt="Screen Shot 2020-03-03 at 1 27 06 PM" src="https://user-images.githubusercontent.com/45409515/75807059-c0b4d780-5d52-11ea-861c-0d01175c3fd1.png">

```
ConfigModule.withConfig({
    pagination: {
        addFirst: true,
        addLast: true,
        addDots: true,
        addPrevious: true,
        addNext: true,
        rangeCount: 0
    }
}),
```

If rangeCount=0, no pagination is displayed. 
<img width="1196" alt="Screen Shot 2020-03-03 at 1 22 25 PM" src="https://user-images.githubusercontent.com/45409515/75807087-cc080300-5d52-11ea-86b4-0518e2e409b5.png">


One question, in the doc it says: 

> addStart adds a link to skip to the start of the pages. The default is set to false.
> addEnd adds a link to skip to the end of the pages. The default is set to false.

But I see them displayed, when I don't have them configured in app.module. 
So it looks like the default is true for me? Can you confirm please?

**Comment by KateChuen** [comment]
@gladius-mtl To update the doc https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/pull/511/files#diff-c3ff7dd65cc4f239f430e50b9d46827b

> addStart adds a link to skip to the start of the pages. The default is set to false.
> addEnd adds a link to skip to the end of the pages. The default is set to false.

The doc should say _the default is set to true_.

**Comment by gladius-mtl** [comment]
Fixed! Thank you for catching this, @KateChuen 🙂
