### ISSUE TITLE
Replace rendering subTotal instead of totalPrice

### ISSUE THREAD

**Issue by psmul** [SAP/cloud-commerce-spartacus-storefront#6061]
Currently, to display the total price of items added to the cart, we are using a value from field "totalPrice", which might be confusing, because it includes e.g. delivery costs (if pre-selected in checkout process).

**Comment by psmul** [comment]
QA steps:
- go to any product
- add it your cart
- go through checkout UNTIL delivery mode
- when you select delivery mode (no matter which one) go to cart again (the point is to leave checkout process)
- go to store and add another item

Expected result:
- Total price on "add to cart" modal should be net (not including delivery mode price)

**Comment by Matejk00** [comment]
QA done, working as expected.
