### ISSUE TITLE
[new PR ready] Expose personalization context in Spartacus

### ISSUE THREAD

**Issue by marek-sap** [SAP/cloud-commerce-spartacus-storefront#6072]
With personalization context data available in rest response we should create interceptor for the web request that extracts content of personalization_context and emits an observable with it.

**Comment by marek-sap** [comment]
PullRequest:
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/5985

**Comment by WeizhengSap** [comment]
Where the emit observable (`getPersonalizationContext()`) will be used?

**Comment by Xymmer** [comment]
also what release is this going in? (1.4 is in RC, 1.5 is on its way, so i assume 1.5)

**Comment by Xymmer** [comment]
@marek-sap 2 questions for you above

**Comment by marek-sap** [comment]
Hello,
This feature is going to 1.5 release, it will be used by Argonaut's team.

**Comment by WeizhengSap** [comment]
I really don't think it should be an interceptor. You can create `facade` folder in `Personalization`, which will be exposed in public api. 
We have `getComponentData` in `CmsService`. Given component id, component data can be got directly. `ContentSlotComponentData` has property `properties`. So, you can convert `properties` to `context` directly.

**Comment by marek-sap** [comment]
It's done as interceptor to update personalization context each time 'personalization' changed on page.
Client just needs to subscribe to method 'getPersonalizationContext' and client is notify every time personalization change.
If we will create facade which will be exposed in api, client will be responsible to retrieve personalization context whenever will need it, but won't be notified if personalization change on page.

**Comment by WeizhengSap** [comment]
The facade method can return `Observable`. Client can subscribe it and be notified every time personalization change.

**Comment by dunqan** [comment]
As we should already have that data in our state (for current page) I think we should consider getting it from the state, not via interceptor. 
It will also work in scenarios where we will not be doing any actual requests because of some caching strategy for example. 
Also, if it will an Observable based on current page data, then it will emit new value on each navigation, etc.

**Comment by marek-sap** [comment]
As a result of discussions we will rewrite this PR to follow your suggestions.

**Comment by WeizhengSap** [comment]
maybe something like this:
```
  return this.cmsService.getCurrentPage().pipe(map(page => {
      const slot = page.slots['PlaceholderContentSlot']  // get slot by position, not by slotId
      if (slot && slot.components[0].uid === 'PersonalizationScriptComponent') {
        const properties = slot.components[0].properties
        if (properties && properties.script) {
          // convert script data to context
          return context;
        }
      }
      return undefined;
    }))
```

**Comment by marek-sap** [comment]
I have reimplemented the pull request to follow your suggestions.

**Comment by WeizhengSap** [comment]
I did the test. It works.
