### ISSUE TITLE
Login refactor / login-form component

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#609]
See GH-585 for description.

**Comment by developpeurweb** [comment]
As per screenshot the `.scss` file is empty.
The `.html` file has only BS4 classes.
Nothing to refactor. We can close this ticket.

![screen shot 2018-12-13 at 1 47 46 pm](https://user-images.githubusercontent.com/15113219/49962837-5cef8600-fee4-11e8-82d8-1012b14ecd4e.png)
