### ISSUE TITLE
List view of PLP is not consistent with Grid view on mobile

### ISSUE THREAD

**Issue by Matejk00** [SAP/cloud-commerce-spartacus-storefront#6094]
Product listing page - list view and grid view looks different on mobile resolution.

Grid View:
![GridView-RWD](https://user-images.githubusercontent.com/6958810/72433905-a9b62800-379a-11ea-9e0b-671d6cfe8d07.png)

List View:
![ListView-RWD](https://user-images.githubusercontent.com/6958810/72433908-ade24580-379a-11ea-9455-1a9a2af9960d.png)

- [ ] Both modes should looks the same on mobile resolution (same order of elements, same margins etc.) Please consult a solution with Anthony or @Xymmer if needed.
- [x] Also regarding to #5715 we can reduce number of variants which is displayed in "list view" to prevent elements overlapping on desktop.
![ListView - desktop](https://user-images.githubusercontent.com/6958810/72434133-2c3ee780-379b-11ea-93bc-065d18586576.png)

**Comment by psmul** [comment]
Regarding fixing for above issues:
1. Sadly, mostly styling issues would introduce breaking changes, which we are strongly against. Therefore changes were made, but for calydon theme which will be available with 2.0 release.

2. After some discussions, for now, we do not want to change current mechanics and we will limit to currently implemented changes made in #5715, which also applies for PLP.

**Comment by psmul** [comment]
QA steps:
1. Activate calydon theme
2. Search for some items (i.e. *pant* or *jacket*)
3. Switch between Grid and List view
4. Resize window to mobile width (i.e. 400-450px)

Expected result:
For both modes, list items should look the same in terms of styling

**Comment by mirkosoft** [comment]
QA check passed.
