### ISSUE TITLE
Language E2E test / SPA-944

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#61]
For other E2E tests, we decided to focus on where backend adds value or can influence or cause breakage.

The assumption is that these kinds of tests are in addition to what Stan already is working on, so check with him. E.g. you can register successfully, and the user is logged in.

----

For E2E purposes, some suggestions related to how we get data from the backend:
 * Check that the menu is there and populated (even if there is only 1 language right now it's still there I think)
 * Changing the language refreshes the whole site
 ** ... but stay on same page/view/screen.
 *** In fact if you are in the middle of registering and change the language, your entire form should remain the same.
 ** Check that the text has changed to target language.

Product details page is a good one to make assertions from, as well as registration page for forms.
 * Another test: do a browser refresh after switching the currency/language, to make sure the change sticks beyond the explicit change request from the user. (and doesn't fall immediately back to the default)

The backend sampledata provides English, German, Chinese and Japanese.

Note that language and currency e2e tests are similar in scope - see SPA-945.

**Comment by Matejk00** [comment]
QA done. Language e2e test works good.
