### ISSUE TITLE
Smart edit doesn't work with default routing config

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#6107]
### How to reproduce:
1. remove from app.module the routing config for product (to let only default routing config for PDP stay - which contains only one route alias requiring product code and name (`['product/:productCode/:name']`).
2. Run app in smart edit.
3. Verify that the product preview page is not displaying properly. 
4. You may observe the warning in the console (there are 2 images with different objects expanded, but it's the same warning):
![image](https://user-images.githubusercontent.com/4001059/72522771-bef48a80-385e-11ea-94c2-e7effc86a11c.png)
![image](https://user-images.githubusercontent.com/4001059/72522795-c7e55c00-385e-11ea-8ed4-29c1190a1e4f.png)

### Ideas for solution:
a) pass some dummy (empty?) string as the param `name` to the `routingService.go()` in the implementation of the method `SmartEditService.goToPreviewPage()`. Currently it contains only the `code` param:
```typescript
this.routingService.go({
          cxRoute: 'product',
          params: { code: this.defaultPreviewProductCode },
        });
```
b) the same as above, but firstly fetch the product data with ProductService, and then pass the correct `name` as route param (concerns: Waiting will slow down the SmartEdit experience. Do we really need to wait for product data just to set the real name in the url - it's not used anywhere in components. The purpose of name in URL was only SEO. I'm also not sure if waiting for product data won't cause some race condition with setting cmsTicket - it should be tested then with real instance of SmartEdit)
c) add a secondary product route's alias with only `productCode` required in our `default-routes-config.ts`:
```typescript
paths: ['product/:productCode/:name', 'product/:productCode']
```
(concerns: should we add this alias by default for all customers? Changing the default config can be treated as a breaking change)

**Comment by WeizhengSap** [comment]
I think a) or c) are both fine (but it seems c) is the best solution). To make b) work, we have to get product data first. To make smartedit work, get `cmsTicketId` is the first thing. So, we cannot get product data before it.

**Comment by Platonn** [comment]
@WeizhengSap, thanks for claryfying a race condition with b)
I can see c) is a potential breaking change and unnecessary added default config, lets go with an option a):
Let's add a route param `name` - empty string.

**Comment by WeizhengSap** [comment]
To QA/reviewer: Please make sure you don't have product route aliases in you `app.module`.
You can comment out this in our `app.module`:
```
routing: {
        routes: {
          product: {
            paths: ['product/:productCode/:name', 'product/:productCode'],
          },
        },
      },
```

**Comment by LTiger14** [comment]
QA Passed
