### ISSUE TITLE
Login refactor / reset new password component

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#612]
See GH-585 for description.

**Comment by developpeurweb** [comment]
As per screenshot the `.scss` file is empty.
The `.html` file has only BS4 classes.
Nothing to refactor. We can close this ticket.

![screen shot 2018-12-13 at 1 48 13 pm](https://user-images.githubusercontent.com/15113219/49963211-5281bc00-fee5-11e8-9702-60acf255ecdf.png)
