### ISSUE TITLE
When we display consignments in order details, use the info from the consignment

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#6123]
This issue stems from how we started out with yacceleratorfulfillment and not consignments, and is reallllllly easy to miss in the json output.

When OMS is used and we get consignments (or even "unconsigned" group), we must use the info from the consignment section. This is because multiple orders of the same product could be split into consignments.

This includes the price and subtotal - it's quite possible that even the price could be different for whatever reason - because you are ordering a whole bunch of something from the same place? i've never seen it, unlikely, but just in case a customer has special requirements here, we should do that.

This ONLY COUNTS for display consignments in order details. 
Not for when we display what can be cancelled or returned.

See the following example.

**Items ordered:**
- 4 of 280916 (web camera)
- 3 of 1377492 (micro webcam)
- 2 of 816802 (cybershot w55)
- 1 of 791635 (Macro Ring Lite)

**Consignments**
The product 1377492 (micro webcam), quantity 3, was split into 2 consignments.
- cons00000001_0 has quantity 2, for the consignment
(note that there are 2 different quantities on different levels, one inside the 'entry' and one that's part of the consignment definition)
<img src=https://user-images.githubusercontent.com/4998145/72578096-056bd880-38a3-11ea-9a08-6c3506c55abe.png width=250 />
- cons00000001_3 has quantity 1, for the consignment
<img src=https://user-images.githubusercontent.com/4998145/72578090-fc7b0700-38a2-11ea-81c5-351a66afad82.png width=250 />

**Image of order and postman get of order:**

Image of order split into 5 consignments:
![image](https://user-images.githubusercontent.com/4998145/72577928-6d6def00-38a2-11ea-97ce-7ae26d5792ac.png)

Postman get of order:
[4 items but 5 consignments.txt](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/4074672/4.items.but.5.consignments.txt)

**and**
it leads to this (after canceling 1 of the offending item)
because the consignment strategy cancelled all consignments related to that one product and then created a new consignment that made more sense for the reduced quantity.
![image](https://user-images.githubusercontent.com/4998145/72578650-adce6c80-38a4-11ea-9061-d8133509cebd.png)

[consignments after cancelling 1 thing.txt](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/4074743/consignments.after.cancelling.1.thing.txt)

**Comment by WeizhengSap** [comment]
Compare the order details page in SPA and our legacy storefront, there are some differences:

1. unconsignment displayed above consignment (maybe it's not issue for us)
2. for each unconsignment entry
   check `entry.deliveryPointOfService`; 
      if exist, display `entry.deliveryPointOfService`
      if not exist, display "Ship To" `orderData.deliveryAddress`
3. for each consignment
   display status and date (we have it in SPA)
   check `entry.deliveryPointOfService`; 
      if exist, display `entry.deliveryPointOfService`
          if consignment status is `WAITING, PICKPACK, READY`, display "pick up by" date
      if not exist, 
         display "Ship To" `orderData.deliveryAddress` and `delivery method`
         if consignment is "SHIPPED" and trackingId exist, then display "consignment tracking Id" (We have it in SPA)
         
4. for each entry, if it is consignment entry, then display `consignmentEntry.quantity`, otherwise `orderEntry.quantity`

**Comment by WeizhengSap** [comment]
In this ticket, we will fix 4. Since in SPA, order details page reuses the `cx-cart-item-list`. So, the consignmentEntry has to be passed to `CartItemListComponent`, which will make it look dirty. In future, we can think about create `OrderItemList` (separate order item list and cart item list).

**Comment by plabadie** [comment]
Smoke test good.  I see the proper cancelled qty with the fix:

Before:

![before](https://user-images.githubusercontent.com/7065346/72640840-b96a7380-3936-11ea-9b4a-6b0f405c70b9.png)

Fixed:

![after](https://user-images.githubusercontent.com/7065346/72640857-bff8eb00-3936-11ea-85c3-afcb40424a21.png)

**Comment by Xymmer** [comment]
to test in a different way, pointing spartacus 1.4. branch to dev10, add 50 of one inexpensive product. The consignment algo will give you 2+ consignments. The quantities for each consignment should add up to your total order. You can check the order via postman and see that the entries add up to the total order and the consignments are the parts being shipped.

If your order gets cancelled, it may be because of fraud check and you spent too much $$$ :)

**Comment by KateChuen** [comment]
Tested on dev10. Looks ok now. We display the correct number of consignments.
