### ISSUE TITLE
Infinite loop with errors after creating fresh user and visiting cart details page

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#6133]
## Environment Details
- Spartacus:  latest devleop (Latest commit 3d43cdb)
- Browser: Chrome 79.0.3945.117
- OS: Windows 10
- Device: Dell Latitude5480
- Backend server used: dev 17

## Steps to Reproduce
1. create a brand new user
2. go to /cart page
(optionally you can add a product before visiting /cart page - no difference)

## Observed Results
![image](https://user-images.githubusercontent.com/4001059/72611304-098f0900-392a-11ea-8ecf-e5206805bd70.png)

`Cart not found` error message is displayed. The infinite http calls are made to `https://dev-com-17.accdemo.b2c.ydev.hybris.com:9002/rest/v2/electronics-spa/users/current/carts/selectivecart853aae42-4150-4e20-92a4-711bedd282b0?fields=DEFAULT,potentialProductPromotions,appliedProductPromotions,potentialOrderPromotions,appliedOrderPromotions,entries(totalPrice(formattedValue),product(images(FULL),stock(FULL)),basePrice(formattedValue),updateable),totalPrice(formattedValue),totalItems,totalPriceWithTax(formattedValue),totalDiscounts(value,formattedValue),subTotal(formattedValue),deliveryItemsQuantity,deliveryCost(formattedValue),totalTax(formattedValue,%20value),pickupItemsQuantity,net,appliedVouchers,productDiscounts(formattedValue),user&lang=en&curr=USD`

## Expected Results
No error occurs, nor the infinite loop with failing http calls.

## Additional Information
Is it a problem of sample data recipe or our logic?

**Comment by Platonn** [comment]
It can be just a problem of missing sample data in dev 11. But we should handle backend errors with more grace than just running into an infinite loop.

**Comment by hackergil** [comment]
This is also happening with a registered user and it is preventing us to checkout. Tested on dev17.

**Comment by WeizhengSap** [comment]
This issue is caused by: in `cart.effect.ts`, we have:
```
if (cartNotFoundErrors.length > 0) {
           // Clear cart is responsible for removing cart in `cart` store feature.
           // Remove cart does the same thing, but in `multi-cart` store feature.
           return from([
                 new DeprecatedCartActions.ClearCart(),
                 new CartActions.RemoveCart(loadCartParams.cartId),
               ]);
            }
```
So, if `cart not found`, then the cart will be removed from store. And, in `selective-cart.service.ts`, we have this:
```
    tap(({ cart, loaded }) => {
        if (this.cartId && this.isEmpty(cart) && !loaded) {
          this.load();
        }
    }),
```
So, if cart is empty and not `loaded`, cart will be loaded.

To fix it, I remove that `cartNotFoundErrors` check. I don't know whether it is the best way to fix it.

**Comment by WeizhengSap** [comment]
After discussing with Marcin, we decided to leave `cartNotFoundErrors` check there, but add another condition. 
```
if ( cartNotFoundErrors.length > 0 && payload.extraData && payload.extraData.active)
```

**Comment by KateChuen** [comment]
Tested on dev12, on chrome, safari, firefox.
No more infinite loop when we go to cart page.
Verified we can place an order.
