### ISSUE TITLE
Rename `wishlist` saved cart name to decrease a chance of name collision

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#6134]
Change name from `wishlist` to something more complex.
There is a big change that name `wishlist` would be used as a saved cart name. To lower the risk of this let's change that to something more unique and not so straightforward.

First idea: `spartacus-special-wishlist-saved-cart`

**Comment by Xymmer** [comment]
To test, see wish list test case https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5506#issuecomment-564143176

**Comment by Xymmer** [comment]
turns out we had 2 tickets, this testing also closes #6178 as that is the issue Louis used
