### ISSUE TITLE
Added to cart modal e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6144]
Reopening this issue because added to cart e2e failing again due to a new issue

Files: 
- cypress/integration/mobile/added-to-cart-modal-mobile.e2e-spec.ts
- cypress/integration/regression/added-to-cart-modal.e2e-spec.ts

<img width="1078" alt="Screen Shot 2020-02-10 at 1 38 15 PM" src="https://user-images.githubusercontent.com/30666844/74179005-9025c600-4c0a-11ea-95e5-deb373d44847.png">

**Comment by qjimmy** [comment]
PR #6159

**Comment by psmul** [comment]
QA steps:

- simply run coupon `added-to-cart-modal.e2e-spec.ts` both for mobile and regression against dev-12

Expected result:

- tests should pass

**Comment by mirkosoft** [comment]
QA Passed.

**Comment by hackergil** [comment]
Adding missing PR to 1.5.x branch
