### ISSUE TITLE
ASM e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6145]
ASM e2e tests are failing for multiple reasons, see screenshots below

<img width="1219" alt="Screen Shot 2020-01-19 at 10 48 30 PM" src="https://user-images.githubusercontent.com/30666844/72697387-d73e0100-3b0d-11ea-85ac-bdd6283f2816.png">

<img width="948" alt="Screen Shot 2020-01-19 at 10 48 44 PM" src="https://user-images.githubusercontent.com/30666844/72697394-db6a1e80-3b0d-11ea-8c67-134de52b9166.png">

**Comment by plabadie** [comment]
PR #6219 

- Fixed ASM e2e tests. 
- Reverted the deletion of order history verification code.
- Disabled 5 order history verification tests unit a proper solution is found to the lagging order history.

**Comment by plabadie** [comment]
Still fails in 1.5.x

https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/22/consoleText

**Comment by plabadie** [comment]
PR 1.5: #6881
PR develop: #6882
