### ISSUE TITLE
Cart e2e tests failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6146]
changed method name

**Comment by qjimmy** [comment]
PR #6158

**Comment by qjimmy** [comment]
Failing again due to OMS giving every product a non-zero stock level. Product that is supposed to be out of stock is now in stock and causing the cart e2e test to fail.

<img width="532" alt="Screen Shot 2020-01-31 at 4 16 42 PM" src="https://user-images.githubusercontent.com/30666844/73574948-0412e200-4445-11ea-803e-982d21fcbbef.png">

Product code is 872912. That product used to be out of stock and the test would pass, but not anymore.

**Comment by qjimmy** [comment]
PR #6439

**Comment by bgambocjaviniar** [comment]
PR: GH-6633

**Comment by bgambocjaviniar** [comment]
Will create one from develop, but changes will be different due to the new update from the 2.0 merges

**Comment by bgambocjaviniar** [comment]
clearing milestone 1.5 and 1.5-e2e to remove confusion as it got in for 1.5, but remaining work is to merge to develop
