### ISSUE TITLE
register e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6150]
This test is failing at the Terms and Conditions portion.

It seems like it cannot find the Terms and Conditions link due to a faulty rendering. The register page inputs have empty labels (see pictures below) and the console is throwing hundreds of errors about the consentState

<img width="1089" alt="Screen Shot 2020-01-19 at 11 40 12 PM" src="https://user-images.githubusercontent.com/30666844/72699134-3bb08e80-3b15-11ea-90d3-8a7d8c2f8f76.png">

<img width="1080" alt="Screen Shot 2020-01-19 at 11 40 00 PM" src="https://user-images.githubusercontent.com/30666844/72699137-3d7a5200-3b15-11ea-8af7-295ecfe2e920.png">

**Comment by Matejk00** [comment]
Fix for this one provided in #6137
