### ISSUE TITLE
Anonymous consents e2e tests failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6153]
projects/storefrontapp-e2e-cypress/cypress/integration/regression/anonymous-consents/anonymous-consents-flow.e2e-spec.ts

Similar issue to the register e2e test failing GH-6150, the assertion on the template content is empty. In this case, it expects the span.form-check-label to contain _personalization_, but the element is oddly empty.

<img width="1089" alt="Screen Shot 2020-01-20 at 12 02 18 AM" src="https://user-images.githubusercontent.com/30666844/72699871-1a9d6d00-3b18-11ea-8026-3ad8fa316fc1.png">

**Comment by hackergil** [comment]
This is still failing in our e2e server

**Comment by bgambocjaviniar** [comment]
PR: GH-6415

https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/53/files 
PERSONALIZATION --> Profile (1 month ago)

**Comment by bgambocjaviniar** [comment]
Well one thing I need to say in jenkins build

build from #810 to 815

https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/810/console
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/811/console
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/812/console
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/813/console
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/814/console
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/815/console

**Anonymous config and anonymous flow have not failed**

**Comment by bgambocjaviniar** [comment]
Don't want to put another edit, and is a follow up from `DIGGING DEEPER`, I believe something is not wrong, but I will verify with Nik in the morning!

**Comment by bgambocjaviniar** [comment]
^ above bug that was mentioned will be fixed in #6467

**Comment by hackergil** [comment]
Still failing in the 1.5.x branch

**Comment by hackergil** [comment]
Still failing in 1.5.x branch

**Comment by bgambocjaviniar** [comment]
wasn't merged to the maintenance branch

**Comment by bgambocjaviniar** [comment]
PR: GH-6598

merging to 1.5 maintenance branch
