### ISSUE TITLE
E2E: not enough items in stock for the promotion tests

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6154]
It seems a change of sample data has caused the test to fail. Upon investigation, the product EOS450D + 18-55 IS Kit had only 1 in stock and cannot increment the quantity using the **+** button, which causes the test to fail.

<img width="1089" alt="Screen Shot 2020-01-20 at 12 05 52 AM" src="https://user-images.githubusercontent.com/30666844/72700085-cc3c9e00-3b18-11ea-9862-7fa50025806d.png">

Maybe change test with another product that has more than one quantity and that has promotion?

**Comment by mirkosoft** [comment]
What are the QA Steps?

**Comment by mszczepaniak** [comment]
**QA Steps**
All of the e2e applied promotion tests should pass on dev12.

**Comment by mirkosoft** [comment]
QA passed, all tests fine.
