### ISSUE TITLE
Billing Address e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6155]
It seems this wait for the review page request never occurs in cypress, breaking the rest of the test.

<img width="1089" alt="Screen Shot 2020-01-20 at 12 11 37 AM" src="https://user-images.githubusercontent.com/30666844/72700266-6866a500-3b19-11ea-926d-09f8799cc548.png">

**Comment by LLink-dev** [comment]
billTo.region mapping was wrongly set in the properties. Correct value should be mockup.payment.label.billTo.region=billTo_state

**Comment by LLink-dev** [comment]
Configuration should be handled with this ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6230
