### ISSUE TITLE
Site Context e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6156]
Good evening, this e2e test is failing once again so i am reopening this issue. 

File:
- regression/site-context/language/language-checkout-page.e2e-spec.ts 

<img width="849" alt="Screen Shot 2020-02-10 at 2 16 24 PM" src="https://user-images.githubusercontent.com/30666844/74181764-d6315880-4c0f-11ea-8e37-71413d8f706a.png">

Investigation is needed for each of these failing test and keep in mind that more site-context related tests might fail because of flakiness and inconsistencies.

**Comment by bgambocjaviniar** [comment]
PR: GH-6187

**Comment by bgambocjaviniar** [comment]
PR: GH-6469

**Comment by plabadie** [comment]
Three problems discovered so far:
1- The query to wait for requests after a language change isn't precise enough.  Requests that are not done with the new language are caught.
PR for `develop`: 
PR for `release/1.5.x`: 


2- There is a bug in the checkout itself: GH-6569

3- The bug in the checkout is reproducible 100% of the time when using the storefront manually.  However, the test only catches it 20-30% of the time.  The test should always fail as well.
