### ISSUE TITLE
Wishlist e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6157]
Hello, Wishlist e2e broken again but for a different reason this time.

File: projects/storefrontapp-e2e-cypress/cypress/integration/regression/wish-list.e2e-spec.ts

<img width="1078" alt="Screen Shot 2020-02-10 at 2 06 52 PM" src="https://user-images.githubusercontent.com/30666844/74181599-9d917f00-4c0f-11ea-8f14-30efae83a863.png">

error when the submit button is clicked but the next page is not loaded..

**Comment by qjimmy** [comment]
Fixed by #6169

**Comment by bgambocjaviniar** [comment]
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/164/
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/165/

in the morning (when the job is done in jenkins)

**Comment by bgambocjaviniar** [comment]
release 1.5 PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/6566
