### ISSUE TITLE
Search bar: nothing happens if to click on the empty search bar

### ISSUE THREAD

**Issue by mlogvyna** [SAP/cloud-commerce-spartacus-storefront#6171]
**Steps to Reproduce:**
1. Go to UI -> perform a search (e.g. the query is "product")
2. Pay attention on the list of results shown on PLP
3. Erase the query and click on "Enter"
4. Pay attention on the page behavior and on the list of results shown on PLP

**Actual result:**
When the query is erased and the empty search line is clicked - nothing happens. 
PLP shows the result for the previous query, having an empty search line. 

![image](https://user-images.githubusercontent.com/60095122/72723885-7bfe2400-3b8a-11ea-99b9-ab4235997067.png)

**Expected result:** 
User should receive a feedback after clicking on the empty search line, e.g showing all products (same as search for "*")

**Comment by KateChuen** [comment]
It's by design. We don't query for empty.
