### ISSUE TITLE
Change wish list name

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#6178]
The only way to differentiate a wish list from any other saved cart for the moment is it's name. At the moment, this name is `wishlist`. When the save cart feature is created a user could create a saved cart with that name.

To make such a thing less probable, the new cart name will be `wishlist{customerId}`, with customerId the customer Id (not user id).

**Comment by LTiger14** [comment]
### For Review:

Test the wish list features. In the store in the multi-cart section you should see the wish list cart. In the details the name should be `wishlist${customerId}`. Also check in backoffice.

**Comment by LTiger14** [comment]
### For QA:

These steps: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5506#issuecomment-564143176

**Comment by Xymmer** [comment]
Didn't realize it before but there was a dupe ticket in Asterix: #6134
test results are there
