### ISSUE TITLE
Error in console after visiting PLP - BreadcrumbComponent

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#6192]
Similar to https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6086, but caused only be the BreadcrumbComponent. To be fixed in 1.4.1.

### How to reproduce:
1. Open the chrom dev tools console
2. Using Spartacus top menu, navigate alternately between the home page and some category page.
3. Verify that on entering PLP, there happens an error in the console `ExpressionChangedAfterItHasBeenCheckedError`:
![obraz](https://user-images.githubusercontent.com/4001059/72799979-a1e8fe80-3c46-11ea-8e34-0943ac8f33dc.png)

### Explanation of the error
The `ExpressionChangedAfterItHasBeenCheckedError` occurs when the template of the component A depends on a value modified synchronously later by the component/service B (but very soon - in the same tick, in the same change detection cycle) . This error indicates that the rendered template of the component A may present outdated values. It's a code smell.

### Proposed solution
There are many possible causes and solutions of this problem. In our case it suffices to delay the updates of the view, using `observeOn(asyncScheduler))` which performs under the hood the emission of the observable in the next macrotask.

**Comment by bgambocjaviniar** [comment]
PR -develop : GH-6783
PR -maintenance : GH-6798
