### ISSUE TITLE
Log into 2 base sites with same login, saved cart name error

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#6213]
Using local b2*oms recipe with cancel/return api's and Kungfu extensions:

1. Log into electronics
2. add products to cart, go to cart
3. log into apparel on same server
4. add products to cart, go to cart

special cart name conflict, see screenshot.
can assume same problem for wishlist.
![image](https://user-images.githubusercontent.com/4998145/72852790-a977ca00-3c7d-11ea-9c51-7a49dac7de6d.png)

When I look at the backoffice details, the cart that's the selective cart has 
order nr: selectivecartdfc19c5e-810a-4eb2-adf4-96cd0540492f
name: selectivecart
but wishlist has order nr 0008935 and name wishlist.

Deleting the selective cart using backoffice, problem goes away.

**Comment by marlass** [comment]
Problem only affects selective cart. Wishlist works correctly.

**Comment by Xymmer** [comment]
thanks Marcin
closing as not a bug in Spartacus and will follow up with the team responsible

**Comment by hackergil** [comment]
This issue was reverted in our last release because it was causing issues with a test environment (dev17). Let's try to merge it back

**Comment by KateChuen** [comment]
Tested on dev10, pointing to dev17.
- It works now. I can switch back and forth between the 2 base sites, and the cart is retrieved properly. 

Only see a 'cart not found' error because of coupons.
