### ISSUE TITLE
PDP not work in smartedit for 1.5/develop as of jan22

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#6214]
Go to smartedit, open pages, and search "product". 
Open "product details" page, you will see it does not work.

I tested `release/1.4.x`, it works.
![Screen Shot 2020-01-21 at 6 13 55 PM](https://user-images.githubusercontent.com/44440575/72854017-12147600-3c81-11ea-8bb7-e62fe39ea3de.png)
But, in develop branch, it does not.
![Screen Shot 2020-01-21 at 6 15 16 PM](https://user-images.githubusercontent.com/44440575/72854039-23f61900-3c81-11ea-8da1-91ee1e3c6224.png)

**Comment by WeizhengSap** [comment]
This issue is caused by `ProductVariantGuard`. 
In function `canActivate()`, 
```
 return this.routingService.getRouterState().pipe(
      map(state => state.nextState.params.productCode),
      filter(Boolean),
      ....
```
The `filter(Boolean)` will make this function return nothing when there is no `productCode` in route parameter. In smartedit, PDP can be opened without `productCode`. So, this will make the navigation cannot be complete because of this guard.

**Comment by KateChuen** [comment]
Tested on dev2. Can now display pdp on smartedit for both online and staged catalog. (with some error in the console though).
Can also add/edit/delete a component from pdp on smartedit.

<img width="1431" alt="Screen Shot 2020-02-06 at 1 46 38 PM" src="https://user-images.githubusercontent.com/45409515/73969168-e7fdbd80-48e8-11ea-8ea6-210a44a2b48b.png">
<img width="979" alt="Screen Shot 2020-02-06 at 1 53 05 PM" src="https://user-images.githubusercontent.com/45409515/73969177-ea601780-48e8-11ea-811c-d20066f0a498.png">
