### ISSUE TITLE
Test smartedit with the latest develop

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#6217]
We need test smartedit fully with our latest release.
The tests should include:
1. In Page list (click page tab), 
    a). you can open and edit components in "my account" pages (no need test each my account page, you can just test one, e.g. address book).
    b). You can open and edit components in "product details" page
    c). You can open and edit components in "product list" page
2. In Home page:
    a). You can edit homepage: remove/add/update one component, make sure the page is auto-refreshed.
   b). You can clone page

**Comment by KateChuen** [comment]
Waiting for it to be deployed on a server to test... 
Which is currently blocked by an error...

**Comment by KateChuen** [comment]
Tested on dev12. 
- Myaccount page - address book -> OK
- HomePage -> got errors product not found. But able to add/edit/remove component -> OK
- Page list -> Cannot add/edit/update component -> 6398

**Comment by KateChuen** [comment]
Tested on dev2. 
Works now. Can add/edit/remove a component on these pages

- MyAccount - address book
<img width="986" alt="Screen Shot 2020-02-07 at 3 00 34 PM" src="https://user-images.githubusercontent.com/45409515/74063306-274a0e00-49be-11ea-94bc-d0a88d4aa6c1.png">

- Product Details
<img width="988" alt="Screen Shot 2020-02-07 at 3 10 16 PM" src="https://user-images.githubusercontent.com/45409515/74063448-6b3d1300-49be-11ea-9c73-20a959f2df7f.png">

- Product List
<img width="983" alt="Screen Shot 2020-02-07 at 2 56 19 PM" src="https://user-images.githubusercontent.com/45409515/74063325-316c0c80-49be-11ea-83af-74662a04d5fd.png">

- Homepage 
<img width="988" alt="Screen Shot 2020-02-07 at 3 03 45 PM" src="https://user-images.githubusercontent.com/45409515/74063473-798b2f00-49be-11ea-9728-1aba85ca4986.png">


- Homepage - can clone too. although there were console errors.
<img width="1440" alt="Screen Shot 2020-02-07 at 3 24 42 PM" src="https://user-images.githubusercontent.com/45409515/74063348-3df06500-49be-11ea-860e-8f9ce45cb930.png">
