### ISSUE TITLE
[MASTER] Spartacus sample data: Sync apparel with electronics

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#6231]
New features were added for 1.5 but likely a few CMS components required for new features didn't make it into Apparel Spartacus sample data.

For example, I don't see cancel/returns nor save-for-later.
- Cancel/returns might be there, but disabled by default because the feature isn't really available until May.
- For save-for-later, it might just be that apparel wasn't completely finished at the time so KungFu didn't add it.

The goal here is to check all commits to electronics and make sure features are working in apparel, and then we can retest these features in apparel.

**Comment by mirkosoft** [comment]
see how it was done in the past: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5147

**Comment by mirkosoft** [comment]
After checking the spartacussampledataaddon commit history I've found below changes didn't reflect other content catalogs than electronics:
Maggie Lin:
- [ ] save for later
- [ ] customer coupons

Tobias:
- [ ] Amend order confirmation, see #6019 

Jerify:
- [ ] e2e failing test data fix
- [ ] stock notification

Nikola + Brian:
- [ ] merchandising carousel

For the order cancel&returns I can see Wei did changes for all catalogs - so no need to re-check I believe.

**Comment by bgambocjaviniar** [comment]
> Nikola + Brian:
> 
> * [ ]  merchandising carousel

consents were put in both except the sample data.
Will put it once discussing the best place to put it as we do not use test-data.impex anymore

**Comment by Xymmer** [comment]
Brian to create tickets for all tasks and add to Miro's comment
