### ISSUE TITLE
Cart remains in store after checkout

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#6238]
### Issue

When you do a checkout after following the steps described lower, the previous cart remains with a "cart not found" error and the items are still in the cart. Adding an item is not possible. Upon browser refresh, the error is fixed.

### Steps to reproduce

- dev-17 frontend 
- AND
- local on 1.4.0 pointing to dev-12

happy path e2e (checkout-flow)
using chrome, and clicking mobile view with pixel 2 XL

- click hamburger for sign in / register (MAKE SURE NOT TO GIVE CONSENT -- untick the first checkbox in the register page)
- register new account / you will be redirected to login page
- click sap logo for homepage
- choose one of the products from the top or bottom carousel and add to cart
- click proceed to checkout
- use the newly registered account
- you will either be redirected to homepage or checkout shipping page (bug) -- needs to be checkout shipping page 100% (bug in develop and release branch)
- fill shipping address (I used Andorra for country input, and any title) After for any input, I did an increment from 1 -- click continue
- delivery mode, just click continue
- payment detail checkout page, visa as payment type, 1 for account holder name, 1234123412341234 as card number, continue
- review page, give consent and continue
- BUG: it says cart not found.. on the order confirmation page. The item got processed and exists in the order history page and in the cart, it still says 1 with the product we checkout with

Note the cart is not visible in backoffice anymore after checkout.

### Expected behavior

The cart should be empty

**Comment by marlass** [comment]
Already merged to `release/1.4.x` branch.
