### ISSUE TITLE
Cart Page refactor / added-to-cart component

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#625]
See GH-585 for description.

**Comment by developpeurweb** [comment]
This one got fixed in GH-624 as it is part of the same **add-to-cart** folder, as per screenshot, so we can close this ticket.

![screen shot 2019-01-17 at 10 55 13 am](https://user-images.githubusercontent.com/15113219/51331299-733eb380-1a47-11e9-9b5b-65b90bfd8fb0.png)
