### ISSUE TITLE
Regression: Product search e2e tests failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6267]
Re-opened this since it is now failing once more.

e2e tests for : 
- product-search-pricing-flow.e2e-spec.ts
- product-search-pricing-type.e2e-spec.ts

are failing for both mobile and desktop

Recipe changes have caused assertions to become outdated

**Comment by qjimmy** [comment]
PR #6271

**Comment by LTiger14** [comment]
Fixed in #6572
