### ISSUE TITLE
Variant selection doesn't work

### ISSUE THREAD

**Issue by CarlEricLavoie** [SAP/cloud-commerce-spartacus-storefront#6270]
## Environment Details

- Spartacus:  1.5.0-next.2

## Steps to Reproduce
Go to any PDP that has multiple variants. 
Click on one of the variants

## Observed Results
The user is sent to the home page.

An error is logged `No configured path matches all its params to given object.  Route config:  {paths: Array(1), paramsMapping: {…}} Params object:  {code: "96977_white"}`

## Expected Results
The user should be sent to the PDP of that variant

## Additional Information
This is caused by missconfiguration of the router config.
Router config expects both name & code on the product, yet the variant-selector only passes a code.

The variant selector should pass both the code & the name to avoid sending user to a PDP without the name and therefore indexing both PDP with and without name.

**Comment by Platonn** [comment]
Should be fixed.
The variants selector should pass also the name to generate a route URL.

**Comment by mszczepaniak** [comment]
QA steps:
1. Go to `app.module.ts` and change the line:
paths: ['product/:productCode/:name', 'product/:productCode'],
to
paths: ['product/:productCode/:name'],
2. Start the app
3. Go to http://localhost:4200/apparel-uk-spa/en/GBP/product/300738133/Asterisk%20SS%20youth%20washed%20orange%20L
4. Change the style or size variant.
5. Check that the URL of the reloaded page contains both product code AND product name

**Comment by Matejk00** [comment]
QA done, URL's are working as expected.
