### ISSUE TITLE
Sample test data for Apparel

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#6274]
sample data exist in `test-data.impex` for electronics catalog

The above impex does not exist for apparel, so I will create a new one for it and put the data in from there

**Comment by bgambocjaviniar** [comment]
BACKEND PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/62

> Nikola + Brian:
> 
> * [ ]  merchandising carousel

fixes the above

**Comment by hackergil** [comment]
#6319 created to fix data for coupons (promotions)

**Comment by bgambocjaviniar** [comment]
(Coupons/Promotions) will be done in another ticket
Current fails to import with line 57-67. If you remove that, it will work --> that's a pass ✅

**Comment by bgambocjaviniar** [comment]
QA: 

- apparel user exist
- merchandising carousel coming from cms component in section2c slot homepage
- e2e data

Basically, need to create an e2e helper that works for apparel (which we don't have, so we can't really test it fully)
