### ISSUE TITLE
Sync sample data for 'Save for Later' to apparel

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#6282]
This sample data (spartacussampledataaddon) that is in electronics were put by was Kungfu / Maggie Lin

--- anyone can take this ticket
- Please add missing sample data to apparel

MASTER ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6231

please tick the checkbox once merged and completed

**Comment by Matejk00** [comment]
Backend PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/64

**Comment by Matejk00** [comment]
QA Steps:
- check if `cleaning.impex` file for apparel can be imported without problems
- check if `SaveForLater Component` is created after import

**Comment by mirkosoft** [comment]
checked, no import errors and component created.
