### ISSUE TITLE
Sync sample data for 'Customer Coupons' to apparel

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#6283]
This sample data (spartacussampledataaddon) that is in electronics were put by was Kungfu / Maggie Lin

--- anyone can take this ticket
- Please add missing sample data to apparel

MASTER ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6231

please tick the checkbox once merged and completed

**Comment by LTiger14** [comment]
PR https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/66
