### ISSUE TITLE
Sync sample data for 'Amend order confirmation' to apparel

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#6286]
This sample data (spartacussampledataaddon) that is in electronics were put by was Tobias

--- anyone can take this ticket
- Please add missing sample data to apparel

MASTER ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6231

please tick the checkbox once merged and completed

**Comment by bgambocjaviniar** [comment]
![Screen Shot 2020-01-28 at 7 18 47 PM](https://user-images.githubusercontent.com/29099466/73317201-4220c380-4203-11ea-9c36-fdf563097dc5.png)
![Screen Shot 2020-01-28 at 7 20 08 PM](https://user-images.githubusercontent.com/29099466/73317202-4220c380-4203-11ea-891b-d350a0f7dd41.png)

All new cms components are there for apparel-uk-spa

**Comment by bgambocjaviniar** [comment]
BACKEND PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/65

**Comment by mirkosoft** [comment]
QA steps:
1. Go to `/apparel-uk-spa/en/GBP`
2. If you dont' have any orders in your account create one
3. check the cancel/return orders flow behave the same way as in electronics store in context of changes done in the impex

**Comment by Matejk00** [comment]
QA done, all cancel and return components exists and rendering properly on apparel.
