### ISSUE TITLE
Sec Alert. js-yaml. Update to 3.13.1. DOS / Code Injection

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#6294]
The following security alert has been risen by github.

**Alert:**
https://github.com/SAP/cloud-commerce-spartacus-storefront/network/alert/projects/backend/occ-client/yarn.lock/js-yaml/open

**Severity:**
high-severity

**Request:**
Upgrade set-value to version 3.13.1 or later.

**Motive:**
Versions js-yaml prior to 3.13.0 are vulnerable to Denial of Service.
WS-2019-0032

Js-yaml prior to 3.13.1 are vulnerable to Code Injection
WS-2019-0063 

**Additional comments:**
If decision is to dismiss, please provide concrete justification for further assessment during peer review.

**Comment by tobi-or-not-tobi** [comment]
fixed with #6299
