### ISSUE TITLE
Sec Alert. mem. Upgrade to version 4.0.0. Memory leak -> DOS

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#6296]
The following security alert has been risen by github.

**Alert:**
1. https://github.com/SAP/cloud-commerce-spartacus-storefront/network/alert/projects/backend/mockgenerator/yarn.lock/mem/open

2. https://github.com/SAP/cloud-commerce-spartacus-storefront/network/alert/projects/backend/occ-client/yarn.lock/mem/open

**Severity:**
moderate.

**Request:**
Upgrade handlebars to version 4.0.0 or later

**Motive:**
In nodejs-mem before version 4.0.0 there is a memory leak due to old results not being removed from the cache despite reaching maxAge

WS-2018-0236

**Additional comments:**
If decision is to dismiss, please provide concrete justification for further assessment during peer review.

**Comment by tobi-or-not-tobi** [comment]
fixed with #6299

**Comment by giancorderoortiz** [comment]
agreed
