### ISSUE TITLE
Variant size selector does not create the up-to-date URL

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/cloud-commerce-spartacus-storefront#6317]
**Steps to reproduce:** 

1. Go to the product with variant, example:
http://localhost:4200/apparel-uk-spa/en/GBP/product/300738133/Asterisk%20SS%20youth%20washed%20orange%20L

2. Change the size

Generated URL does not match displayed variant (shows the previous one, see the picture below):

![variantUrl](https://user-images.githubusercontent.com/4272069/73368446-45728880-42b1-11ea-921e-cb76e7f7a440.png)

**Comment by mirkosoft** [comment]
QA Steps:
1. Go to product linked in the description
2. Change the size
3. check if url match with product title - QA pass if it does

**Comment by bgambocjaviniar** [comment]
http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/product/300608386/I%20Love%20Tee%20SS%20Women%20turquoise%20L

used the product above, as well as others. The size changes and the url's product title matches.
✅ 

dev-com-17 got updated with latest develop branch, as well as including apparel-uk-spa
