### ISSUE TITLE
Page Slot component overwrites any classes

### ISSUE THREAD

**Issue by CarlEricLavoie** [SAP/cloud-commerce-spartacus-storefront#6318]
We are in the process of migrating an existing custom to spartacus. As part of that process we want to make it as seemless as possible for end users when they navigate from the accelerator to Spartacus. 

In order to do that, we want to replicate the existing HTML to leverage existing CSS and ultimately end up with identical pages.

For that to happen, we need contentSlots to behave similarly to the way they worked in the page. For PageSlots to work similarly to the old slots, we are extending the existing page-slot.component.ts but changing the selector to be an attribute selector which will avoid the extra <cx-page-slot> wrapping. 

All of this works very well, except that whenever we use our attribute, all existing css classes are removed from our element because of the way [position] is binded to the host [class] attribute.

## Environment Details

- Spartacus:  1.5.0-next.2

## Steps to Reproduce
use the PageSlotComponent using an attribute selector.

## Observed Results
All existing [class] on the HTML element are removed.

## Expected Results
Classes should be added, but existing ones shouldn't be removed.

## Offer to Fix
Yes, will open a PR to discuss possible solutions.

**Comment by CarlEricLavoie** [comment]
@tobi-or-not-tobi  - this is related to the question I asked you in slack. For now we'll overwrite locally, but i'd be curious to know why this behavior was reverted.

**Comment by tobi-or-not-tobi** [comment]
@CarlEricLavoie thanks a lot for pointing this out! It's actually a breaking change, we haven't realised this during the implementation. I already have made a quick fix locally, so happy to formalise a PR later on. But I'm not against getting an input from your side. 

The reason why it was dropped, is that we like to not use lower level APIs if not needed.

**Comment by CarlEricLavoie** [comment]
Gotcha, as I mentioned we already have a work around on our project so it's not a big deal. What might be interested is for spartacus to have an actual PageSlotComponent that uses an attribute selector.

I feel like it's a very useful component for migrations.

The code itself is nothing fancy, here's a screenshot. The only difference is the selector. The HTML itself is exactly the same as your PageSlotComponent.

![2020-01-29_13-27-34](https://user-images.githubusercontent.com/7239120/73385454-308afa80-429b-11ea-95a4-3aab97b4784d.png)

**Comment by psmul** [comment]
QA done. Fix working as intended.
