### ISSUE TITLE
cx-merchandising-carousel styling not available in 1.4

### ISSUE THREAD

**Issue by matt-williams8** [SAP/cloud-commerce-spartacus-storefront#6336]
## Environment Details

- Spartacus:  1.4
- Browser: All
- OS: All
- Device: All
- Other environment details: cds module version 1.0.0-next.0

## Steps to Reproduce
1. Run spartacus with CDS enabled.
1. Navigate to a page with a merchandising carousel configured

## Observed Results
The style of the `cx-merchandising-carousel` does not match the styling of standard product carousels. E.g. the product name and price in `a` are not formatted the same as in a standard carousel.

## Expected Results
`cx-merchandising-caorusel`s should be styled in the same way as a standard product carousel

## Additional Information
As part of the cds-integration the `cx-merchandising-carousel` scss file was added to storefront styles. As cds was added to spartacus from 1.5 onwards, this styling is not yet available in storefront styles. Is there anyway to instead move the styling into the cds module so that it is always available?

**Comment by bgambocjaviniar** [comment]
not a problem since cds work is 1.5 and above
