### ISSUE TITLE
Page content fetched a second time on the client when using Server-side rendering

### ISSUE THREAD

**Issue by arminh** [SAP/cloud-commerce-spartacus-storefront#6337]
## Environment Details

- Spartacus: 1.4.0
- Browser: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- OS: Ubuntu 18.04.3 LTS
- Device: Dell Precision-5530

## Steps to Reproduce
1. Install Spartacus from the libraries using the schematic and the --ssr flag
2. Build and run the application using `yarn build:ssr` and `yarn serve:ssr`
3. Open the landing page in the browser 
4. Open the Developer console, inspect the server-side rendered index.html and observe that the page content is passed from the server in the `serverApp-state`
![image](https://user-images.githubusercontent.com/3740956/73523800-f725cc80-440b-11ea-85cf-79a773e89687.png)
5. In the network tab inspect the executed XHRs

## Observed Results
The page content is fetched on the client a second time
![image](https://user-images.githubusercontent.com/3740956/73522852-c775c500-4409-11ea-899a-2260ae9df8b3.png)

## Expected Results
The client shouldn't load the page content another time since it was already transferred from the server in the serverApp-state

**Comment by KateChuen** [comment]
For now, it's by design. There is an intention to improve it in the future.

**Comment by danilchican** [comment]
@arminh , do you have a solution already?

**Comment by tobi-or-not-tobi** [comment]
@arminh @danilchican It's arguable to say it's by design in my pov, but it's for sure a side effect of the design. We're currently investigating to solve this issue for customer who do not need any (aggressive) personalisation for revisits of pages in the same session. See the lined ticket for more info.
