### ISSUE TITLE
Apparel. Console Errors Upon Login/Logout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#6354]
**Steps to reproduce:** 
1. Navigate to Apparel storefront
1.a. Such as : http://dev-com-6.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/

**2. Sign in as registered user.** 
3. Sign out. 

**Expected results:** 
2 & 3: No console errors seen. 

**Actual results:** 
2 & 3: 
main.c1f62f51f5f28eeb580e.js:1 ERROR TypeError: Cannot read property 'component' of undefined
    at main.c1f62f51f5f28eeb580e.js:1
...

**Sign in console errors:** 
![Screen Shot 2020-01-31 at 3 46 05 PM](https://user-images.githubusercontent.com/46171897/73573247-e8a5d800-4440-11ea-8abf-395fd54abd83.png)

**Sign out console errors:** 
![Screen Shot 2020-01-31 at 3 45 30 PM](https://user-images.githubusercontent.com/46171897/73573256-ee032280-4440-11ea-8a7d-ac65ee5522c2.png)

**Comment by giancorderoortiz** [comment]
Error is reproducible as well in electronics

**Comment by giancorderoortiz** [comment]
Using latest develop branch & backend: dev-com12

**Comment by plabadie** [comment]
The issue seems to have been introduced by this commit:
https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/4768442b946dd56533ceb645d9a3cccee0daa270

**Comment by znikola** [comment]
Fix: #6384

**Comment by bgambocjaviniar** [comment]
QA steps:

- open dev tools
- register a user
- login with that new user
- signout, and look if there's the error above in console for 'component of undefined'

**Comment by giancorderoortiz** [comment]
Test successful. Console errors no longer seen.
