### ISSUE TITLE
404 page not working

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#6372]
Issue present on branch: develop 
Issue not present on branch: release 1.4.x

**Steps to reproduce:**
Navigate to a page that does not exist, such as
http://dev-com-6.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/fsdfgsdfgs

**Expected results:**
The 404 page.

**Actual results:**
A semi blanc page with error in the console.

<img width="1679" alt="Screen Shot 2020-02-03 at 9 40 28 AM" src="https://user-images.githubusercontent.com/7065346/73663300-487fc700-466b-11ea-97f4-5e53df8025a4.png">

**Comment by plabadie** [comment]
Looks like the issue is introduced by this commit:
4768442b946dd56533ceb645d9a3cccee0daa270

**Comment by znikola** [comment]
PR: #6385

**Comment by bgambocjaviniar** [comment]
QA steps: 

- be at homepage
- append anything after the last `/` like /electronics-spa/en/USD/fsdfgsdfgs

**Comment by giancorderoortiz** [comment]
redirection works as expected.

![Screen Shot 2020-02-04 at 3 27 14 PM](https://user-images.githubusercontent.com/46171897/73784180-fc17b280-4762-11ea-9003-bfb4f03e82f2.png)
