### ISSUE TITLE
user profile is loaded for anonymous user

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#6373]
The `UserService.load` is loading the user profile regardless whether the user is logged in or not. When this method is called before the user is known, a call for `/rest/v2/electronics-spa/users/anonymous` will be return a 401 which is causing confusion for developers who open the console. Moreover, the call is blocking the experience to render as fast as possible. Specifically for new users.

So far the (unofficial?) guideline was to keep the responsibility of calling the service by the consumer of the facade. As a result there's at least a single code in the current code base where this issue is popping up. Developers who are not aware of this will likely spent time on this. Moreover, the amount of unnecessary conditional checks can be prevented if we centralise this code.

It is recommended to add a conditional check in the facade to avoid lower level code which is causing side effects (i.e. a user load event).

**Comment by tobi-or-not-tobi** [comment]
This issues is first seen on 1.5, where the `SelectiveCartService` was added to the `CartPageLayoutHandler`.

**Comment by tobi-or-not-tobi** [comment]
QA:
- open spartacus without a logged in user
- ensure that there's no 401 for a call to `/rest/v2/electronics-spa/users/anonymous`

**Comment by psmul** [comment]
QA done. Can confirm that 401 call is not there anymore for anonymous user.
