### ISSUE TITLE
Stale page title when browsing from text search results to category pages (issue with category-page-meta-resolver.ts)

### ISSUE THREAD

**Issue by gkentr** [SAP/cloud-commerce-spartacus-storefront#6376]
## Environment Details

- Spartacus:  1.5
(Browser, OS, etc. don't matter here)

## Steps to Reproduce
1. In the accelerator, do a text search (e.g. "socks" if you are using the Apparel one)
2. After the results load, browse to a Category page (e.g. Women Bags)

## Observed Results

The page title is not updated and the title from the original text search remains there while accessing other pages. Meanwhile, there is an invalid access in one of the `category-page-meta.resolver.ts` callbacks (check your browser's console for the exact error).

## Expected Results

The page title should be updated.

## Offer to Fix
In `CategoryPageMetaResolver`, this access to the breadcrumbs array is done without checking whether there are actually breadcrumbs:

```
query: (<ProductSearchPage>p).breadcrumbs[0].facetValueName
```
The listener there receives a stale ProductSearchPage object (from the text search) which has no breadcrumbs so the call blows up, causing subsequent updates to not happen. The `filter` argument should probably be excluding objects without breadcrumbs from being passed further down the chain:

` filter((page: ProductSearchPage) => !!(page.pagination && page.breadcrumbs && page.breadcrumbs.length))`

**Comment by LTiger14** [comment]
**Align with Tobias** because the breadcrumbs will be refactored in 2.0 #6090 and he worked on it previously.

**Comment by bgambocjaviniar** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6581

This bug is fixed in 6581 in Tobias branch
