### ISSUE TITLE
Smartedit: displaying apparel page while on electronics basesite

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#6398]
**Environment Details**
Spartacus: develop branch
Browser: Chrome
Device: mac
Happens on: https://dev-com-12.accdemo.b2c.ydev.hybris.com:9002/smartedit

**Steps to Reproduce**
- Go to apparel uk storefront: http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP
- Go to smartedit
- Login as cmsmanager/1234
- Go to Spartacus Electronics Content Catalog - Staged version
- Go to Pages -> Product List page

**Actual Result**
It displays the apparel page, while we are on Electronics basesite. Therefore we get an error and we cannot add/edit a component from the page.

<img width="1438" alt="Screen Shot 2020-02-04 at 11 42 38 AM" src="https://user-images.githubusercontent.com/45409515/73774097-6d4e6a00-4751-11ea-9acd-ff022e274331.png">

**Comment by WeizhengSap** [comment]
PR is here: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/73

**Comment by bgambocjaviniar** [comment]
local backend no longer has the issue with the backend PR

<img width="1440" alt="Screen Shot 2020-02-06 at 2 21 12 PM" src="https://user-images.githubusercontent.com/29099466/73971108-4c6e4c00-48ec-11ea-89a0-44c267d69bed.png">
<img width="1440" alt="Screen Shot 2020-02-06 at 2 21 01 PM" src="https://user-images.githubusercontent.com/29099466/73971104-4a0bf200-48ec-11ea-8b86-c3692e91b7fc.png">

**Comment by KateChuen** [comment]
Tested on dev2. 
Works now, I see electronics page when on electronics basesite.

<img width="989" alt="Screen Shot 2020-02-07 at 2 57 04 PM" src="https://user-images.githubusercontent.com/45409515/74061547-3a5adf00-49ba-11ea-92f7-01fc704b1c37.png">
