### ISSUE TITLE
Storefinder css refactor / store-finder-header component

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#640]
See GH-585 for description.

**Comment by developpeurweb** [comment]
@Xymmer nothing to refactor in this file as per screenshot, we can close it.

![screen shot 2019-02-15 at 12 32 27 pm](https://user-images.githubusercontent.com/15113219/52874455-99777200-311f-11e9-8300-127e26970576.png)
