### ISSUE TITLE
Checkbox without label when config registerConfig is changed, requiredConsents and hideConsents exist (Anonymous Consents)

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#6411]
Add this config to app.module:

```
anonymousConsents: {
   registerConsent: 'PERSONALIZATION',
   showLegalDescriptionInDialog: true,
   requiredConsents: ['MARKETING_NEWSLETTER'],
   consentManagementPage: {
    showAnonymousConsents: true,
    hideConsents: ['STORE_USER_INFORMATION'],
  },
},
```

Go to register page.
There is a checkbox missing a label.

![image](https://user-images.githubusercontent.com/11735817/73847588-e370d080-4826-11ea-93d5-7d5c50dcab62.png)

Note: This fails `anonymous-consents-config-flow.e2e.ts`

**Comment by KateChuen** [comment]
Please refer to #6153

**Comment by bgambocjaviniar** [comment]
it's just a config issue, instead of PERSONALIZATION its PROFILE (changes in the sampledata). I linked it under 6153
