### ISSUE TITLE
1.5.0-RC testing

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#6414]
The following e2es are not passing on dev12. Please add your name next to the test that you will be performing. Check the box once you verify the test cases manually. Post a message on the release channel if you find a problem.

Backend: Dev12
Frontend: Dev12 (or local, **using 1.5.0-RC branch**)

Mobile
- [x] added-to-cart-modal-mobile (Kate)
- [x] cart-mobile @qjimmy 
- [ ] consignment-tracking-mobile @Pucek9 
- [x] coupon
- [x] my-account/my-coupons
- [x] mobile/my-coupons
- [x] save-for-later

Regression
- [x] added-to-cart-modal (GC)
- [ ] anonymous-consents-config-flow (Kate) ❌
- [ ] anonymous-consents-flow (Kate) ❌
- [x] applied-promotions
- [ ] billing-address
- [x] cart @qjimmy 
- [ ] consignment-tracking @Pucek9 
- [x] coupon
- [x] my-coupons
- [x] my-account/payment-methods (GC)
- [x] product-details (GC)
- [x] save-for-later (GC)

**Comment by Pucek9** [comment]
Asterix & Obelix already took care

![image](https://user-images.githubusercontent.com/8040837/73857992-00fa6600-4838-11ea-85eb-167ae35c1189.png)

**Comment by bgambocjaviniar** [comment]
anonymous-consents-config-flow (Kate) ❌

works in https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/6415
