### ISSUE TITLE
Billing address e2e test fails

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#6417]
Billing address issue:
`should fill in payment form with different billing address (country with states)`
after setup shipping address:
```
  {
    city: 'Tralfamadore',
    line1: 'Chrono-Synclastic Infundibulum',
    line2: 'Betelgeuse',
    country: 'United States',
    state: 'Connecticut',
    postal: '06247',
  },
```
and billing address:
```
{
  city: 'Montreal',
  line1: '111 Boulevard Robert-Bourassa',
  line2: '',
  country: 'Canada',
  postal: '9000',
  state: 'Quebec',
}
```
Request URL: https://dev-com-12.accdemo.b2c.ydev.hybris.com:9002/rest/v2/electronics-spa/users/current/carts/00004628/payment/sop/response?lang=en&curr=USD
Request Method: POST
Status Code: 400 

```
"errors" : [ {
  "message" : "RegionModel with country, isocode 'CA, CA-CT' not found!",
  "type" : "UnknownIdentifierError"
} ]
```

**Comment by hackergil** [comment]
I've added the right mapping to dev12 (#6230) and it is already in our recipe and now the test is passing.
