### ISSUE TITLE
Applied promotions not displayed in the order history

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/cloud-commerce-spartacus-storefront#6428]
Currently applied promotions are not shown in the consigned entries

**Comment by Matejk00** [comment]
That cause applied promotions e2e failing.

```
  1) Applied promotions Applied promotions as a logged user Should verify promotions in order confirmation details:
     CypressError: Timed out retrying: expected '<div.cx-promotions>' to contain 'EOS450D'
```

**Comment by mszczepaniak** [comment]
**QA Steps**

1. Add product with the applied promotion activated, i.e. EOS 450D
2. Go through the checkout process
3. After the checkout, go to order history
4. You should see the promotions (see the picture below)
![order](https://user-images.githubusercontent.com/4272069/74157680-fc0f2b00-4c18-11ea-9878-8403d2e58baa.png)

**Comment by Matejk00** [comment]
QA done, applied promotions are displaying on order details page.
