### ISSUE TITLE
Products going out of stock

### ISSUE THREAD

**Issue by hackergil** [SAP/cloud-commerce-spartacus-storefront#6440]
Update OMS backend settings to avoid products going out of stock because of orders placed by e2e tests

**Comment by hackergil** [comment]
Backend PR https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/74

**Comment by bgambocjaviniar** [comment]
works (changes in localhost)

old
<img width="1426" alt="old" src="https://user-images.githubusercontent.com/29099466/74006014-781f1f80-4948-11ea-8aba-e90711a2ca21.png">
new
<img width="1416" alt="new" src="https://user-images.githubusercontent.com/29099466/74006021-7a817980-4948-11ea-9c8a-49448b421d0d.png">
