### ISSUE TITLE
Add null checks for baseOptions

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#6447]
Some backends doesn't return `baseOptions` array in the `entries.product` for the cart endpoint response which cause errors. Let's add some checks to avoid that in the below components (search the project for `baseOptions[`):
- cart item
- amend order items
- wish list item

**Comment by bgambocjaviniar** [comment]
PR: GH-6453

**Comment by bgambocjaviniar** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/6462/files
for the release one ^

Can't merge the PR above for develop until I get an approval for the release branch

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by mirkosoft** [comment]
Not sure how but you need to have product occ response WITHOUT `baseOptions` array in it. And than check the console for errors in places listed in the description.

**Comment by bgambocjaviniar** [comment]
QA: steps 
- go to apparel-uk-spa
- add non baseOption product like 45572
- add baseOption product like 300613173

verify no console errors in wishlist, order/return, cart
