### ISSUE TITLE
Save for later e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6463]
The save for later e2e test is failing due to the 300938 product id not existing in dev-12

file: **cypress/integration/regression/save-for-later/save-for-later.e2e-spec.ts**

<img width="1079" alt="Screen Shot 2020-02-10 at 12 41 10 PM" src="https://user-images.githubusercontent.com/30666844/74174761-8a2be700-4c02-11ea-8829-48291af583c4.png">

**Comment by giancorderoortiz** [comment]
still failing

**Comment by plabadie** [comment]
Fails on the 1.5.x branch
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/31/consoleText

**Comment by mszczepaniak** [comment]
depends on #6704

**Comment by plabadie** [comment]
Thank you for the assessment.
The CI will switch over to dev17-1905.11 soon, see GH-6649.
