### ISSUE TITLE
Product details e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6464]
Product details e2e test failing due to wrong selector

File: **cypress/integration/regression/product-details.e2e-spec.ts**

<img width="1072" alt="Screen Shot 2020-02-10 at 12 46 12 PM" src="https://user-images.githubusercontent.com/30666844/74175191-4c7b8e00-4c03-11ea-959d-5c275cc90d5a.png">

**Comment by plabadie** [comment]
After investigation, this is potentially an issue with the feature that the test caught.
See GH-6495
