### ISSUE TITLE
storefront pre-alpha 10: cx-storefront has no exported member

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#648]
reported in Spartacus chat from Nikola Radulovic:

> When I pulled the latest version of storefront (0.1.0-prealpha.10), I got "cx-storefront has no exported member" message once I tried to access the storefront. Not sure if the setup guide (https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/setupandinstallation.md) is up to date or anything should be done different ? Can someone recheck it by setting up Spartacus from "customer perspective" and verify if the bug is valid ?

**Comment by hackergil** [comment]
Pull request #656

**Comment by tobi-or-not-tobi** [comment]
This closed with #656 being merged and a new version is published.
