### ISSUE TITLE
Variant Selector Not Showing on Base Product(s)

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#6495]
This is a potential variants issue discovered while investigating e2e test failure ( GH-6464 )

## Issue 1
http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/product/100191

![variants1](https://user-images.githubusercontent.com/7065346/74282309-e7e92d80-4ced-11ea-8bac-5a6f2ac5cecd.png)

* Observed: The variant selector does not show when the PDP displays a variant base product. 
* Expected: The style selection should be possible. ( a case covered by e2e test ).  

## Issue 2:

http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/product/100191_glacier/Beacon%20Jacket%20glacier

![variants2](https://user-images.githubusercontent.com/7065346/74282742-a1e09980-4cee-11ea-8654-d4acef13851c.png)

* Observed: The variant size selector does not show when the PDP displays a style variant base product.
* Expected:  The size selection should be possible. ( a case covered by e2e test ).  

## Note:
The variant options selector displays properly when the PDP displays a specific variant:
http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/product/300441354/Beacon%20Jacket%20glacier%20L

![variants3](https://user-images.githubusercontent.com/7065346/74283053-3d720a00-4cef-11ea-93bb-44498b40aa0a.png)

**Comment by plabadie** [comment]
@mirkosoft , can you assess if this looks like a legitimate issue to you?

**Comment by mirkosoft** [comment]
QA Steps: Just follows "expected" statemets in the description.

**Comment by mszczepaniak** [comment]
Tested successfuly.
