### ISSUE TITLE
Improve searchbox tabbing and aux keys

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#6510]
**Environment Details**
Spartacus: epic/accessibility branch
Browser: Chrome & Safari & Firefox
Device: mac
Happens on: http://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
~~Tab to the search box, and type in something, for eg, camera.~~
~~Press Enter Key -> Nothing happens? So I can't search a specific word? I have to choose one of the suggested ones.~~

- Tab down the suggested list, and select one of the suggestions, press Enter -> It goes to that pdp page, but the list of suggestions remains open. Unless we manually go back and press on the X button
-> Maybe an improvement?

**Comment by giancorderoortiz** [comment]
I see the same

**Comment by giancorderoortiz** [comment]
There are many console errors at this juncture. 
![Screen Shot 2020-02-17 at 11 17 12 AM](https://user-images.githubusercontent.com/46171897/74670670-a76b3300-5177-11ea-9492-0cde0e1cd79a.png)

**Comment by KateChuen** [comment]
Confirmed that pressing ENTER after typing a search text is now fixed in #3827. Verified on chrome, safari, firefox.

**Comment by kacperknapik** [comment]
The majority of problems mentioned in this ticket are not related to a11y. The only thing that will be fixed in this ticket is correct tabbing and correct usage of aux keys (arrow, ESC, etc)

**Comment by kacperknapik** [comment]
@KateChuen please create another ticket with the rest of the problems, so somebody can grab it (note: it's a must, so it's rather important to create this ticket)

**Comment by KateChuen** [comment]
The only issue left to tackle in this ticket is this:
Tab down the suggested list, and select one of the suggestions, press Enter -> It goes to that pdp page, but the list of suggestions remains open. Unless we manually go back and press on the X button

Maybe that's more a P2 now?

**Comment by psmul** [comment]
@KateChuen Wasn't able to reproduce the problem. Tried both on dev-3 and dev-12. Tabbed till searchbox and tested different values and result was as intended (searchbox suggestions closed on loading new plp / pdp)

Windows 10
Chrome 80.0.3987.116
Firefox 71.0

**Comment by KateChuen** [comment]
You're right. The suggestion list closes now. I must have pulled in the fix when I updated the server.
