### ISSUE TITLE
[ON HOLD] Prepare for moving default routes config from core to feature modules in lib

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#652]
Decision needed: should we provide the default routes config in:
1. import of `ConfigModule.withConfig()` in feature's module; or
2. `data` property of feature's route

The solution must be compatible with configurable lazy loaded routes #334.

Edit: decided to go for option 1.

**Comment by tobi-or-not-tobi** [comment]
Team framed provides one example, from there we can have other teams joining on this to add it to all feature modules.

**Comment by Platonn** [comment]
We are anticipating different strategy for building configurable routing. So the shape of the config may change. So for now we hold with moving current config from core to lib.

**Comment by Platonn** [comment]
I close this issue in favour of GH-2147
