### ISSUE TITLE
Checkout bug when changing language

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#6569]
Found by: GH-6156

## Environment details
Produced using dev12 as a backend
Reproduced on two branches:
* release/1.5.x
* release/1.4.x

## Steps to Reproduce case 1: 
* Sign in, add something to the cart and start checkout. ( my user also uses a previously saved address )
* change the site language to German at the shipping address step.
* select an address and proceed to the delivery mode step

### Observed Result:
 The delivery modes are not present.  The spinner never goes away.  Impossible to proceed with checkout, even if the language is set back to English.

## Steps to Reproduce case 2: 
* Sign in, add something to the cart and start checkout. ( my user also uses a previously saved address )
* select an address and proceed to the delivery mode step
* See that the delivery mode choice is displayed
* Change the site language to German at the delivery mode step.

### Observed Result:
 The delivery modes are disappear.  The spinner never goes away.  It might be possible to proceed with the default delivery mode.

<img width="1060" alt="delivery-modes-issue" src="https://user-images.githubusercontent.com/7065346/74551705-a9d44f80-4f21-11ea-88c9-7fd67b82982e.png">

**Comment by KateChuen** [comment]
Tested on dev12, it works now. Can change the language on shipping address step, shipping method step, payment step, review step during checkout, without problem. Can proceed with checkout and place the order. 

Only get a "Cart not found" error but not related to this ticket.
`GET https://dev-com-12.accdemo.b2c.ydev.hybris.com:9002/rest/v2/electronics-spa/users/current/carts/selectivecartelectronics-spaa834a1ab-1e6d-4d1b-9c1e-3e38ddbdd5e7?fields=DEFAULT,potentialProductPromotions,appliedProductPromotions,potentialOrderPromotions,appliedOrderPromotions,entries(totalPrice(formattedValue),product(images(FULL),stock(FULL)),basePrice(formattedValue,value),updateable),totalPrice(formattedValue),totalItems,totalPriceWithTax(formattedValue),totalDiscounts(value,formattedValue),subTotal(formattedValue),deliveryItemsQuantity,deliveryCost(formattedValue),totalTax(formattedValue,%20value),pickupItemsQuantity,net,appliedVouchers,productDiscounts(formattedValue),user&lang=en&curr=USD 400`
