### ISSUE TITLE
Update search e2e tests so they are not rely on exact number of search results

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#6572]
In order to avoid frequent e2e failures after recipe change hardcoded assumptions needs to be removed from the tests. For example, for `smoke/product-search` instead of checking for exact hardcoded number let's check the number app receives from the backend:
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts#L61
After successfully change of the above let's reuse the same approach wherever possible for this helper.

**Comment by giancorderoortiz** [comment]
Applies to smoke, regression and mobile tests as well. 
Wherever possible, there must not be an assertion checking for an specific number of results.

**Comment by mirkosoft** [comment]
I would say it may be specific but the correct one :) If we compare with response I meant.

**Comment by bgambocjaviniar** [comment]
PR: GH-6682

only contains changes for the search-*flow.e2e.ts (everything in regression) and not the one in smoke test as it was already done in another PR by someone else.

**Comment by bgambocjaviniar** [comment]
PR to develop: GH-6721

**Comment by bgambocjaviniar** [comment]
clearing milestone 1.5 and 1.5-e2e to remove confusion as it got in for 1.5, but remaining work is to merge to develop
