### ISSUE TITLE
Configurable URL matchers - for easier opt out from suffix routes and more advanced customizations

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#6583]

**Comment by Platonn** [comment]
# QA steps
## Regression
### Product Details Page
1. Open standard PDP
   -  [ ] http://localhost:4200/electronics-spa/en/USD/product/816780/DSLR-A100H
2. Open standard PDP alias
   -  [ ] http://localhost:4200/electronics-spa/en/USD/product/816780
3. Open accelerator-backward-compatible PDP
   -  [ ] http://localhost:4200/electronics-spa/en/USD/Open-Catalogue/Cameras/DigitalCameras/Digital-SLR/DSLR-A100H/p/816780
### Product Listing Page
5. Open standard PLP 
   -  [ ] http://localhost:4200/electronics-spa/en/USD/category/578
6. Open accelerator-backward-compatible PLP alias
   -  [ ] http://localhost:4200/electronics-spa/en/USD/OpenCatalogue/Cameras/Digital-Cameras/Digital-SLR/c/578
## New feature: Configurable url matchers
7. Remove accelerator-backward-compatible PLP alias (which is declared in `matchers` field in the default config), by overwriting `matchers` with `null` in app module:
   ```typescrript
      routing: {
        routes: {
          product: {
            matchers: null,
          },
        },
      },
   ```
   And verify you:
   -  [ ] CAN open (1), (2) 
   -  [ ] CANNOT open (3)
8. Implement custom URL matcher and pass it to the `matchers` of the route config:
```typescript
/**
 * Matches pattern `** / :productCode--test`
 * @param segments
 */
export function customMatcher(segments: UrlSegment[]): UrlMatchResult | null {
  const lastSegment = segments[segments.length - 1];
  if (segments.length && lastSegment.path.endsWith('--test')) {
    const productCode = lastSegment.path.slice(0, -6); // remove `--test`
    return {
      consumed: [...segments],
      posParams: { productCode: new UrlSegment(productCode, {}) },
    };
  }
  return null;
}
```
```typescrript
      routing: {
        routes: {
          product: {
            matchers: [customMatcher],
          },
        },
      },
```
   and verify that you
   -  [ ] CANNOT open any of (1), (2) (3)
   -  [ ]  But CAN open custom url http://localhost:4200/electronics-spa/en/USD/bla/blah/816780--test
9. Combine custom URL matcher with the default one for PDP:
```typescrript
import {PRODUCT_DETAILS_URL_MATCHER} from '@spartacus/storefront';
/*...*/
      routing: {
        routes: {
          product: {
            matchers: [customMatcher, PRODUCT_DETAILS_URL_MATCHER],
          },
        },
      },
```
 and verify that you
   -  [ ] CAN open all of (1), (2) (3)
   -  [ ] And CAN open custom url http://localhost:4200/electronics-spa/en/USD/bla/blah/816780--test

10. Combine custom URL matcher with the standard aliases (but not the accelerator-backward-compatible):
```typescript
import {DEFAULT_URL_MATCHER} from '@spartacus/core';
/*...*/
      routing: {
        routes: {
          product: {
            matchers: [customMatcher, DEFAULT_URL_MATCHER],
          },
        },
      },
```
 and verify that you
   -  [ ] CAN open all of (1), (2)
   -  [ ] But CANNOT open (3)
   -  [ ] And CAN open custom url http://localhost:4200/electronics-spa/en/USD/bla

**Comment by KateChuen** [comment]
- Tested on dev10.

- Before:
Can access (1), (2), (3), (4), (5)

- After this config,

```
routing: {
     routes: {
       product: {
         matchers: null,
       },
     },
   },
```

Can access (1), (2), (4), (5)
Get 404 on (3)

- Implement custom URL matcher and pass it to the matchers of the route config.
Get 404 on (1), (2), (3)
Can access (4), (5) and custom url: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/abcdef/12345/816780--test
<img width="1136" alt="Screen Shot 2020-03-04 at 11 06 30 AM" src="https://user-images.githubusercontent.com/45409515/75993333-51142900-5ec7-11ea-8dfb-d7fd5d2ec6cc.png">


- Combine custom URL matcher with the default one for PDP
Can access (1), (2), (3), (4), (5) and custom url: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/abcdef/12345/816780--test

- Combine custom URL matcher with the standard aliases (but not the accelerator-backward-compatible):
Can access (1), (2), (3), (4), (5) and custom url: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/abcdef/12345/816780--test
Get 404 on (3)
