### ISSUE TITLE
update schematics: implement migration support for html and css files

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#6588]
~This ticket focuses on handling css breaking changes:~
- ~if we change a DOM structure of a component, this breaks customers css. In this case we should find the breaking css selector (search in html  / scss files) and add a comment specifying how to deal with the change~
- ~customers are using a deprecated css styling from Spartacus?~

UPDATE: see [this comment](https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6588#issuecomment-587404228)

**Comment by tobi-or-not-tobi** [comment]
I think this is very difficult and not likely beneficial. CSS selectors can be created in various ways, and it's hard to compute. CSS can be created in different technologies as well. 

I think we should stay out of this for now. 

We could make a general note about breaking UI changes that might affect the custom CSS fo the customer. I.e.:

> In case you've implemented custom style rules for the following selectors, you should evaluate whether your custom CSS was affected:
> - `cx-pagination`, see www.link.to/docs/pagination
> - `cx-item-counter`, see www.link.to/docs/item-counter

We could maintain a list of selector/doc links. 

We can also make it even easier, and just make a single reference to a documentation page, listing all the selector changes from one to another version. Much easier to create and maintain and fix after a release as well.

**Comment by znikola** [comment]
After discussing this, we decided to go in another direction. The idea is that after the update schematics are done executing, we can just drop a link to the docs where customers can read about what Tobias suggested in the comment above.

@gladius-mtl can we please have a placeholder for this page? Tobias will provide content.

**Comment by znikola** [comment]
The link to the CSS deprecation guide should look like this:
https://sap.github.io/cloud-commerce-spartacus-storefront-docs/deprecation-guide/css

- `deprecation-guide` page should be a general page for the migration guide
- `css` page is specific for css migration guide
