### ISSUE TITLE
Wrong Message and Behaviour when Adding an Empty Address

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#6594]
**Steps to Reproduce:**
Navigate to dev-server with accessibility features enabled.
1.a. Such as http://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD
2. Login as registered user.
3. From MyAccount, select Address book.
4. Add a new address.
5. Do not fill any text fields. 
6. Submit (i.e. click on "Add Address") button.

**Expected Results:**
6. Error message indicating text fields need to be actually filled. 
6.a. User remains in Add a new shipping address. 

**Actual Results:**
6. API response error message. 
6.a. Control returns back to Address Book. 

![Screen Shot 2020-02-17 at 10 26 19 AM](https://user-images.githubusercontent.com/46171897/74666862-455aff80-5170-11ea-83b8-32291730845d.png)
![Screen Shot 2020-02-17 at 10 26 27 AM](https://user-images.githubusercontent.com/46171897/74666865-468c2c80-5170-11ea-8c66-9f8a3eaf7c56.png)
![Screen Shot 2020-02-17 at 10 26 35 AM](https://user-images.githubusercontent.com/46171897/74666867-4724c300-5170-11ea-87cf-d6bc591a3e5b.png)

**Comment by giancorderoortiz** [comment]
The error message is too detailed here, and exposes internal class structures in backend.

**Comment by kacperknapik** [comment]
Will be fixed in #6742
