### ISSUE TITLE
Remove useless facets from the product result response

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#6599]
The (current) backend returns facets with values that do not contribute to the facet navigation much, as the number in the result list will not get affected when they got applied. A ticket has been created to optimise this behaviour in the backend. 

As long as this is not in place, we manually filter the facet from the list; any facet that does not have a count < the total results will be dropped from the facets.

The following screen dump shows an example fo this behaviour: 
![image](https://user-images.githubusercontent.com/4745807/74675918-04390e80-51b5-11ea-8606-3d5a0512cd25.png)

part of #5692

**Comment by tobi-or-not-tobi** [comment]
QA:
- filter a product list
- ensure that there are no filters available that will not limit the number of products

You can do the following examples, or try some more
1. [example 1](https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/Open-Catalogue/Cameras/Film-Cameras/c/574?query=:relevance:category:574:price:$0-$49.99): Available stores will not narrow down the search results as there's only 1 product in the list already. The other price values is still available as it expands the list (given it's a  though is actually a useful value, as the facet allows multi-select).
2. [Example 2](https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/search/eos?query=eos:relevance:Resolution,%2080:1280%2Bx%2B720): stores and prices are both useless as they will not narrow down the result.

**Comment by KateChuen** [comment]
Tested on dev10. 
Now, it does not show the facets when not necessary.

No Price facet displayed:
Before the fix:
<img width="989" alt="Screen Shot 2020-02-28 at 10 38 06 AM" src="https://user-images.githubusercontent.com/45409515/75565435-f0df3c00-5a1b-11ea-93af-126830b08220.png">

Now:
<img width="987" alt="Screen Shot 2020-02-28 at 10 38 14 AM" src="https://user-images.githubusercontent.com/45409515/75565454-f5a3f000-5a1b-11ea-861a-d9fc5bdd0492.png">

If price facet was selected in the filter before stores, then it is still displayed:
<img width="818" alt="Screen Shot 2020-02-28 at 10 39 26 AM" src="https://user-images.githubusercontent.com/45409515/75565502-10766480-5a1c-11ea-8260-8f45637662d3.png">

No stores facet displayed:
<img width="818" alt="Screen Shot 2020-02-28 at 10 52 09 AM" src="https://user-images.githubusercontent.com/45409515/75565714-72cf6500-5a1c-11ea-8817-e9b39e901a7e.png">


No stores and no prices facets are displayed:
Before the fix:
<img width="898" alt="Screen Shot 2020-02-28 at 10 41 59 AM" src="https://user-images.githubusercontent.com/45409515/75565634-52070f80-5a1c-11ea-959f-8f1e90daac98.png">

Now:
<img width="923" alt="Screen Shot 2020-02-28 at 10 41 38 AM" src="https://user-images.githubusercontent.com/45409515/75565653-592e1d80-5a1c-11ea-8208-673133aeae20.png">
