### ISSUE TITLE
Save for deletes cart item but doesn't display save-for-list cart

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6613]
<h4>Caught by Save For Later e2e test</h3>

Two cases:
- As anonymous user, the save for later button brings you to the login page.
- As a logged in user, the save for later button deletes the corresponding consignment and a global message error pops up.

<img width="1440" alt="Screen Shot 2020-02-18 at 10 00 27 AM" src="https://user-images.githubusercontent.com/30666844/74750812-53755280-523a-11ea-801d-97acd35afe7c.png">

Potential issue:

Upon investigation, different requests have been made. The release branch `release/1.5.x` works properly but `develop` branch is returning a 400 status code. 

<img width="987" alt="Screen Shot 2020-02-19 at 2 59 03 PM" src="https://user-images.githubusercontent.com/30666844/74871056-cd840500-5328-11ea-92c2-299bc0c5bd0e.png">

Should make sure the save-for-later e2e tests also pass after this fix. [Needed for 1.5]

**Comment by Xymmer** [comment]
Let's retest with 1905.11 once dev12 is updated

**Comment by Xymmer** [comment]
i tested with 1905.11, same error

**Comment by Xymmer** [comment]
Bill asked Kungfu to look into it (Kevin/Terry)

**Comment by kacperknapik** [comment]
`Cart not found` error is indeed fixes. New error was introduced: 
![image](https://user-images.githubusercontent.com/22354613/75032521-0f3bb980-54a9-11ea-81ba-89726ccf8da4.png)

It doesn't give enough informations for the user - he won't know what happened

**Comment by kacperknapik** [comment]
Save-for-later e2e are still failing (both dev12 and dev17)
