### ISSUE TITLE
Drop CSS driven order of PLP slots

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#6615]
So far, the various slots on listing pages (category and search) have been _ordered_ with a combination of a layout configuration and order rules in CSS (flexbox). There is no good reason to do so, and it breaks accessibility. Using the keyboard is breaking the experience, since the re-ordered visual layout(CSS) does not align with the real DOM. 

As part of accessibility improvements and a larger refactor of the facet navigation (#6581) we will change it to a simplified setup (simple DOM, simple CSS).

BREAKING CHANGE: 
- the b2cLayoutConfig will change, which will produced a change in the DOM for the category and search pages 
- the CSS layout for the category and search pages will no longer use specific "order" for the layout.

**Comment by tobi-or-not-tobi** [comment]
QA
- open PLP (category and search) in list and grid mode, ensure that all slots are rendered in the expected order 
- ensure that the order is not driven by CSS, you could verify it in the DOM and validate that the DOM order is the order of slots.

**Comment by KateChuen** [comment]
Tested on dev10.
PLP from category and search, looks ok, for both list and grid view, 

Slots in DOM are in this order:
PLP from category:
<img width="340" alt="Screen Shot 2020-02-27 at 10 16 22 AM" src="https://user-images.githubusercontent.com/45409515/75481583-49a5ca80-5971-11ea-9084-7395f2373fee.png">

PLP from search:
<img width="327" alt="Screen Shot 2020-02-27 at 2 54 38 PM" src="https://user-images.githubusercontent.com/45409515/75481591-4ca0bb00-5971-11ea-97be-76e6f3b1db8b.png">
