### ISSUE TITLE
Decision: how to handle failure of fetching routes config

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#662]

**Comment by marlass** [comment]
There might be some cases when this request will be very slow (waiting for response more than 20 sec, before timeout). Seeing blank screen in those cases might not be a best behavior. In those cases maybe fallback to static configuration will be better (and probably dynamic configuration won't be changed on daily basis and it would be recommended to export it from time to time and save in static config). Another solution might be some static fallback page informing about error and recommending refresh.

**Comment by tobi-or-not-tobi** [comment]
I'd say it's a 404 as we don't know what to do.
