### ISSUE TITLE
HTML markup in URL when additional route param (product name) is defined; when entering PDP from search box suggestions

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#664]
# Steps to reproduce
- configure additional route param for product details page:
```typescript
StorefrontModule.withConfig({
    routesConfig: {
        translations: {
            default: {
                product: { paths: ['product/:productCode/:name'] }
            }
        }
    }
})
```
- type someting in the search box and click the suggested product
    ![obraz](https://user-images.githubusercontent.com/4001059/50167118-b5f65a00-02e8-11e9-8855-1dc9b12eb8f6.png)

# Bug
After navigation to Product details page, the URL is polluted with HTML markup from search box suggestions
    ![obraz](https://user-images.githubusercontent.com/4001059/50167719-1a65e900-02ea-11e9-9ce8-7acdc41b0a41.png)

# Expected behaviour
URL contains simply product name, for example: `http://localhost:4200/cx-product/4205436/32GB%20SDHC%20Card`

# Reason
`suggestion` object contains markup under `name` property instead of just name of the product

**Comment by Xymmer** [comment]
Kris to add supporting info

**Comment by hackergil** [comment]
@LTiger14 Can you check your build? Thanks!
