### ISSUE TITLE
Hide global message "Item ## no longer valid (was removed): object no longer valid" as it's an invalide message

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#6679]
We know that this message is an invalid message, as it's because of simultaneous calls. It will get fixed in 2.0 but doesn't affect carts right now.
![image](https://user-images.githubusercontent.com/4998145/75041831-5a46d400-548b-11ea-841e-500256195fa3.png)

Let's just look for and hide this message for now, as it presents an error that doesn't affect the customer really.

**Comment by mirkosoft** [comment]
QA Steps:
Try to checkout (no need to finish it) so the `addresses/delivery` PUT request should fail (it is fired for various cart actions, changing devlivery adddress is good example; see the network tab). If you dont' see message from the ticket's description QA is passed.

**Comment by Matejk00** [comment]
QA done, such error message is not displaying anymore.

**Comment by umuttoker** [comment]
wow what a nice solution. Instead of preventing duplicate PUT request, just hide the exception.
