### ISSUE TITLE
[resolved in #333] Checkout: last step of checkout is highlighted when we're on the first step

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#669]
## Environment Details

- Spartacus: yenv, dev branch
- Browser: chrome
- OS: mac mojave

## Steps to Reproduce
- Login with a registered user, and place an order.
- Logout
- Add a product to cart
- Proceed to checkout
- Login when prompted. 
<img width="1214" alt="checkoutstephighlighted" src="https://user-images.githubusercontent.com/45409515/49895024-69f57200-fe1d-11e8-9575-756d59f000da.png">

## Observed Results
Last step is highlighted even though we're at the first step, which is The shipping Address Details.

## Expected Results
First step should be highlighted

**Comment by Xymmer** [comment]
verified with github.io
