### ISSUE TITLE
Address Management page

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#67]
This ticket is for implementing the customer's Payment Management page.
We need to add cms in the backend but you can use page label for order history in the meantime.

# Tasks
- [x] ux design
- [x] sandbox (SPA-400 and 421)
- [x] implement
- [x] unit tests
- [x] e2e tests
- [x] proper cms label

# General behavior

### Go to the page and there are already addresses
Display cards of existing addresses, like checkout
https://98qkkl.axshare.com/#g=1&p=addresses_added

### Go to the page and there are NO addresses
Display empty form by default
https://98qkkl.axshare.com/#g=1&p=spa-179-addresses_empty

### Deleting Addresses
Clicking Delete displays "are you sure" inside the box
https://98qkkl.axshare.com/#g=1&p=addresses_delete

### Setting Default Address
Clicking "Set as default" sets the address as default, and it moves to first spot.
Confirmation message appears at top.
https://98qkkl.axshare.com/#g=1&p=addresses_setasdefault

# Click Add or Edit

### Add
Clicking Add shows the form with fields blanked with intro text "Add a new shipping address."
Like: https://98qkkl.axshare.com/#g=1&p=spa-179-addresses_empty
Remember the country/state thing in checkout, same thing.
For default country, use same country as the user's default address (if there is one).
Otherwise use same behavior as checkout.

### Edit
Clicking Edit shows the form with fields filled in, with intro text "Edit an existing shipping address."
Like: https://98qkkl.axshare.com/#g=1&p=spa-179-addresses_empty 
but with info.
Ignore the wire https://98qkkl.axshare.com/#g=1&p=addresses_addform, it's a bit weird.

### State/Province/Regions
Don't forget that if there are no state/regions for a country, hide the state/region menu.
The backend will give an error if you supply an invalid state/region code, but is ok if there is none at all.

### Set as Default when adding and editing
- If there are no addresses yet, don't display check box "Set as default address"
- If there exists one other address, display check box "Set as default address"
If checked, make this address the default.

### Forms and Verification
Copy what we have in checkout.

### Address Verification
Trigger address verification when user clicks Save.

### Canceling
Clicking cancel drops the changes and goes back to the list.

# Out of Scope
- The UX has a menu at left, but we left that out so far

**Comment by Xymmer** [comment]
For the salutation problem ("Mr"), hide the field, but always send Mr for now
Server change will make it so that salutation not required.

**Comment by Matejk00** [comment]
PR: #412
