### ISSUE TITLE
[DUPE of 6712] Remove unused code from "item-counter" calydon instance

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#6713]
Since the item counter implementation has been merged (coming from 2.0 branch) and have taken a different journey for a11y. The code below is no longer used:

`projects/storefrontstyles/scss/themes/calydon/components/cart/_item-counter.scss`

![Screen Shot 2020-02-25 at 12 06 22 PM](https://user-images.githubusercontent.com/15113219/75269654-42db5400-57c7-11ea-868f-643bf7aad83b.png)

**Comment by KateChuen** [comment]
tested through https://github.com/SAP/spartacus/issues/6712
