### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by mirkosoft** [SAP/cloud-commerce-spartacus-storefront#6718]
- [x]  validate that every merged ticket was tested (nothing should be left QA column, exceptions - ticket marked as `not-blocking-release`)
- [x]  ~for new minors/RC create maintenance branch e.g. `release/1.5.x`~
- [x]  ~announce new maintenance branch on tribe channel (only when new maintenance branch)~
- [x]  create release branch `release/1.5.0` (from `release/1.5.x`)
- [x]  build app on this branch using this script: [https://github.tools.sap/cx-commerce/spartacus-installation](https://github.tools.sap/cx-commerce/spartacus-installation)
- [x]  run all e2e tests on release branch (tip: run mobile, regression, smoke scripts in parallel to get all the results faster, after that retry failed tests in open mode)
- [x]  make sure that release branch is working correctly, everything is passing and it builds (click few pages manually and look into build errors)

---

For Mac:
- [x]  cleanup repo, build and generate compodocs and publish on github pages, generate spartacussampleaddon archives (`./scripts/pre-release.sh`)

For Windows:
- [x]  cleanup repo, build and generate compodocs and publish on github pages (`./scripts/pre-release.sh` - without sampleaddon zip)
- [x]  download and rename in root directory `https://github.tools.sap/cx-commerce/spartacussampledataaddon/archive/develop.zip` -> `spartacussampleaddon.zip`
- [x]  download and rename in root directory `https://github.tools.sap/cx-commerce/spartacussampledataaddon/archive/develop.tar.gz` -> `spartacussampleaddon.tar.gz`

---

- [x]  release libraries with `release-it` scripts (eg. for core `npm run release:core:with-changelog`)
        - make sure to run it as an npm script (`yarn` has issues with npm login)
        - add GITHUB_TOKEN env variable (`export GITHUB_TOKEN=token`)
        - be logged in to npm
- [x]  check if release notes are populated on github (polish them or ask someone to review and improve them)
- [x]  check tags on npm (`next` should always point to the highest version, `latest` to highest stable version)
- [x]  check if everything builds from npm packages (spartacus installation script)
- [x]  merge release branch into  maintenance branch
- [x]  announce on tribe channel
- [x]  create tickets to nonblocking release problems found during the release process

**Comment by mirkosoft** [comment]
for schematics I got below error:
```
⠹ yarn build
yarn run v1.17.3
$ tsc -p tsconfig.json
src/add-cms-component/index.ts(11,41): error TS2307: Cannot find module '@angular/cdk/schematics'.
src/add-pwa/index.ts(102,7): error TS2345: Argument of type 'import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/rxjs/internal/Observable").Observable<import("/Users/c5279129/S
APDevelop/cloud-commerce-spartacus-storefront/node_modules/@angular-devkit/schematics/src/tree/interface").Tree>' is not assignable to parameter of type 'import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable").Observable<import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/@angular-devkit/schematics/src/tree/interface").Tree>'.
  Types of property 'source' are incompatible.
    Type 'import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/rxjs/internal/Observable").Observable<any>' is not assignable to type 'import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable").Observable<any>'.
      Types of property 'operator' are incompatible.
        Type 'import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/rxjs/internal/Operator").Operator<any, any>' is not assignable to type 'import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Operator").Operator<any, any>'.
          Types of property 'call' are incompatible.
            Type '(subscriber: import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/rxjs/internal/types").TeardownLogic' is not assignable to type '(subscriber: import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/@angular-devkit/core/node_modules/rxjs/int...'.
              Types of parameters 'subscriber' and 'subscriber' are incompatible.
                Property '_parentOrParents' is missing in type 'import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber").Subscriber<any>' but required in type 'import("/Users/c5279129/SAPDevelop/cloud-commerce-spartacus-storefront/node_modules/rxjs/internal/Subscriber").Subscriber<any>'.
src/add-spartacus/index.ts(15,8): error TS2307: Cannot find module '@angular/cdk/schematics'.
src/add-ssr/index.ts(19,41): error TS2307: Cannot find module '@angular/cdk/schematics'.
src/shared/utils/file-utils.ts(3,41): error TS2307: Cannot find module '@angular/cdk/schematics'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
✖ yarn build
ERROR error Command failed with exit code 1.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storefrontapp@1.4.0-next.1 release:schematics:with-changelog: `cd projects/schematics && release-it && cd ../..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storefrontapp@1.4.0-next.1 release:schematics:with-changelog script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/c5279129/.npm/_logs/2020-02-26T19_29_11_464Z-debug.log
```

**Comment by Xymmer** [comment]
checked release notes, they are there

**Comment by mirkosoft** [comment]
tags has been changed, 1.5.0 is labelled by both latest and next
