### ISSUE TITLE
Wrong value in Qty Input

### ISSUE THREAD

**Issue by jdbrocca** [SAP/cloud-commerce-spartacus-storefront#6724]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  1.4
- Browser: Google Chrome
- OS: Mac OS
- Device: 
- Other environment details: Angular 9.0.1

## Steps to Reproduce
Just enter to PDP

## Observed Results
Qty Input show a value [Object Object]
![image](https://user-images.githubusercontent.com/4001059/75438370-1dca1b00-5958-11ea-8628-00496fdc6f8a.png)

## Expected Results
Show the number 1

**Comment by LTiger14** [comment]
Won't fix due to constraints and Spartacus 1.x not supporting Angular 9.
