### ISSUE TITLE
Update add-ssr schematics for 2.0/ng9

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#6729]
We need adjust our templates to use @nguniversalengine v.9 and Ivy

**Comment by psmul** [comment]
QA steps: 
- go to schematics folder 
- remove node_modules and run *yarn* to get latest libs
- build schematics locally (projects/schematics -> *yarn build && npm pack*)
- in any other folder, create clean angular app
- apply your locally built schematics (*ng add <path_to_tgz_file> --ssr*) SSR mode is very important here
- remember to supply occBaseUrl in environments.prod.ts
- build app for SSR and serve an app

Expected results:
- the application should launch smoothly in SSR mode
