### ISSUE TITLE
Create SmartEdit module and move all SmartEdit code into it

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#686]
Create SmartEdit module
Move all SmartEdit-related code into it

**Comment by WeizhengSap** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/697

**Comment by WeizhengSap** [comment]
We only need on smartedit ticket for QA. All other smartedit tickets are moved to "done".
