### ISSUE TITLE
Secure oauth token

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#690]
Currently oauth token is stored in session storage. We must evaluate if we can further secure the token in order to increase security.

**Comment by josecervera** [comment]
Maybe related: it seems that Spartacus is using Oauth's Resource owner flow, but for web clients, the implicit flow would be recommended:

https://help.hybris.com/6.7.0/hcd/3d3ea6a4d5fa486aa324ce278fa2afc3.html

**Comment by tobi-or-not-tobi** [comment]
We should only store tokens, no personal data. This is caused by a full sync of the token data (thank you ngrx-store-localstorage ;) )

**Comment by Xymmer** [comment]
to confirm, we need to remove user id from the storage

**Comment by Xymmer** [comment]
will be fixed in #2584
