### ISSUE TITLE
Storefront latest tagged version isn't the latest

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#695]
While a blocking bug was fixed in #648, the published lib doesn't have the _latest_ tag assigned to it. You need to explicitly pull the correct version or _next_, otherwise the previous lib version is returned.

**Comment by tobi-or-not-tobi** [comment]
Fixed without a new publication on npmjs.com.

**Comment by marlass** [comment]
New `@spartacus/storefront` and `@spartacus/core` releases are tagged as `latest`
