### ISSUE TITLE
[doc input] Add type safety to other layers + create tickets

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#7]
We need to introduce type safety on a lot of layers, but at least on the facade layer (#6). We've already generated types from out OCC backend (using swagger.json and a standard generator), and ideally we use those generated types.

Type safety provides static code validation and helps customers to develop faster.

**Comment by Xymmer** [comment]
Not sure if type safety is being added to facades thru #6 - creating new tickdt for that, and this ticket will be for future to add it other layers.

**Comment by znikola** [comment]
Doesn't need any doc input.

**Comment by gladius-mtl** [comment]
Doc input looks good! Created follow-up doc ticket GH-591 to provide in-depth edit and review.
This ticket can now be moved to done! 😄
