### ISSUE TITLE
[wait for refactoring to be done] Cannot navigate to PDP by redirect from old link when additional route parameters defined

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#713]
# Expected behvaiour
1. **GIVEN** additional route parameter `:productName` configured for product details page
2. **WHEN** user clicks the banner with category and then banner with product
3. **THEN** router navigates to product details page

# Bug
Error is thrown and cannot navigate to product details page.

# Reproduce
1. Routes config
    ![obraz](https://user-images.githubusercontent.com/4001059/50152493-0ad3a980-02c4-11e9-97c2-a78eb8d14fa5.png)

2. Clicking 2 banners
    ![obraz](https://user-images.githubusercontent.com/4001059/50151739-06a68c80-02c2-11e9-840f-4cd075b44684.png)
    ![obraz](https://user-images.githubusercontent.com/4001059/50151757-1d4ce380-02c2-11e9-9339-ae89332d3c68.png)

3. Error in console
    ![obraz](https://user-images.githubusercontent.com/4001059/50152096-fba02c00-02c2-11e9-98e7-60eccffc3647.png)

# Strategy of redirects to configurable routes needs a change
Currently, the redirect is made to the first configured path alias - which is `product/:productCode/:productName` here. But the link from CMS under the banner doesn't contain `:productName` parameter (`Open-Catalogue/:category1/:category2/:category3/:category4/p/:productCode`). So probably some better strategy is needed to choose which path to use for redirect to configurable route. For example to choose the path:
- not first, but the most relevant (having required parameters)
- not configured, but the predefined one (`product/:productCode`)

There is a ticket for rethinking configurable redirects #657

**Comment by Platonn** [comment]
This bug should disappear when task #822 is done.

**Comment by Xymmer** [comment]
This should wait for refactoring - until we have an implemented solution for configurable product&category pages in the new vein of CMS-driven routes. Currently Stan is working on CMS-driven (sub)routes for content pages. Then we will probably redesign current solution for product&category pages.

**Comment by Platonn** [comment]
Fixed thanks to wildcard routes in GH-1978

**Comment by KateChuen** [comment]
Tested on dev2. 
After changing the routes config, then clicking on the banners to land on pdp page, no error was displayed in the console.
