### ISSUE TITLE
Smoke testing the libs

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#730]
Use this server: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/

Keep the browser's console open at any time and monitor for errors.

Perform the following smoke tests:

  Register, logout, login with the previously registered user
  Go through checkout flow with the previously registered user:
  Search for a product and open it
  Check all tabs (product details, specs, reviews and shipping)
  Add it to cart
  Search for any other product and add it to cart directly from the search results page (don't open the product, just click on "add to cart")
  Change quantity
  Create a new shipping address
  Create a new payment method
  Repeat for an existing user (any user that was registered before the smoke testing)
  Check all other functionality/pages and observe is basic functionality broken, are there any UI elements broken, etc.:
  Order history page
  Change language/currency
  Sort
  When searching, use facets and filters
  Check pagination

**Comment by MitchellScottSandre** [comment]
(Getting blocked by errors but I'll post this for now...)
Made a brand new user
- Spelling Mistake: 'This field is not a valid email addresss'. Three s's.
- Error banner does not go away: Tried to register using email address `aaa@aaa.aaa`, which was not a valid email address. So the banner saying it wasn't valid appears. Then I finish logging in (with a correct email address). But the banner is still there.
- Instructions indicate to change the quantity of a product after adding it directly from the search results page (without clicking on the item, just by clicking 'Add To Cart'). However, there is no option in that modal to change the quantity. Perhaps the instruction "Click on 'View Cart'" should be added.
- Duplicate Text: After creating a shipping address, "Buy over $200.00 get $20.00 discount on cart" displays twice on the right and side of the screen in bold green
- Stuff stops displaying: After creating a Shipping Address, (moving on to step 2: Shipping Method), I was not able to continue. When I wen't back to Step 1: Shipping Address, nothing appears and now I am stuck
- Duplicate Text: "Buy over $200.00 get $20.00 discount on cart" appears twice on the View Cart page
- Facet not displaying after filtering by it: After searching for `cat` and filtering by Floor-standing (under Mounting heading), that facet disappears from the left hand side. It is in the top left as a.. filter option with an X beside it, but the red-checkmarked facet is no longer there. However, filtering by Megapixels, or Price, or Stores, etc, leaves the facet on the LHS and adds a checkmark beside it.

**Comment by MitchellScottSandre** [comment]
I get stuck while attempting checkout. (Have tried with 4 different newly-registered users).
Error occurs after entering new address during checkout, and am unable to click "continue" during step 2.
Console error is:
```
ERROR TypeError: Cannot read property 'forEach' of undefined
    at n._tapNext (main.1c1b6af011eb3af0aab4.js:1)
    at n._next (main.1c1b6af011eb3af0aab4.js:1)
    at n.next (main.1c1b6af011eb3af0aab4.js:1)
    at n._next (main.1c1b6af011eb3af0aab4.js:1)
    at n.next (main.1c1b6af011eb3af0aab4.js:1)
    at n._next (main.1c1b6af011eb3af0aab4.js:1)
    at n.next (main.1c1b6af011eb3af0aab4.js:1)
    at n._subscribe (main.1c1b6af011eb3af0aab4.js:1)
    at n.t._trySubscribe (main.1c1b6af011eb3af0aab4.js:1)
    at n._trySubscribe (main.1c1b6af011eb3af0aab4.js:1)
```

**Comment by plabadie** [comment]
The checkout step progress bar is wrong on the shipping address step.  We are on step 2 and step 4 is highlighted:

![screen shot 2018-12-19 at 2 51 42 pm](https://user-images.githubusercontent.com/7065346/50244749-b5b89600-039e-11e9-9e6d-89b9032ecdbb.png)

**Comment by Xymmer** [comment]
The blocker issue was fixed, I will create tickets for the other minor bugs.
