### ISSUE TITLE
App does not start when installed from the libs

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#740]
After following the installation procedure, I get build errors when I attempt to launch the storefront with `ng serve`:

```
ERROR in node_modules/@spartacus/core/src/product/store/effects/product.effect.d.ts(10,19): error TS2307: Cannot find module '../../../../../../../../../../SAPDevelop/spartacus/dev/2-spartacus/node_modules/rxjs/internal/Observable'.
node_modules/@spartacus/core/src/state/utils/loader/loader.helpers.d.ts(2,59): error TS2307: Cannot find module '../../../../../../../../../../SAPDevelop/spartacus/dev/2-spartacus/node_modules/rxjs/internal/types'.
node_modules/@spartacus/core/src/state/utils/loader/loader.helpers.d.ts(3,59): error TS2307: Cannot find module '../../../../../../../../../../SAPDevelop/spartacus/dev/2-spartacus/node_modules/rxjs/internal/types'.
node_modules/@spartacus/core/src/state/utils/loader/loader.helpers.d.ts(4,62): error TS2307: Cannot find module '../../../../../../../../../../SAPDevelop/spartacus/dev/2-spartacus/node_modules/rxjs/internal/types'.

ℹ ｢wdm｣: Failed to compile.
```

To repro, follow the installation instructions:
https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/setupandinstallation.md

...with the exception that you must use locally built libs for "@spartacus".

**Comment by LTiger14** [comment]
This could be a cause of the first one but it seems you have an error in `styles.css`. In our install guide we tell users to create their shell app with scss as styles preprocessor. Therefore, the import of the styles lib should be in `styles.scss`. 

Also, the error says `Can't resolve '@spartacus/styles/index'`. This should be `~@spartacus/styles/index`.

**Comment by plabadie** [comment]
You are right.  `css` is not good.  It should have been `scss`.  The error is due to a human error on my part.  I omitted the `--style=scss` flag in the command which is, for example `ng new mystore --style=scss`

I reinstalled spartacus manually using the `--style=scss` and the error is gone.  I removed the css error from the issue description to avoid confusion.

The other errors remains.  Which is now consistent with the results I get from the installation script

**Comment by hackergil** [comment]
This problem was the same we had last sprint, where we don't type some things (see above) and when typescript is compiled, the compiler adds a relative path from where to import the type. The solution was to add the types explicitly and the imports (see commit above)

This fix is in our release branch so there's no PR for it. It will be merged when we merge the release branch.
