### ISSUE TITLE
Add classes for all slots on landing page layout.

### ISSUE THREAD

**Issue by radulovicn** [SAP/cloud-commerce-spartacus-storefront#748]
With current structure of landing page layout it is not that easy to style the elements that are located inside it. Few slots (slot-2 and slot-4) already have some css classes on it, which makes the styling of nested elements a bit easier.

....

<cx-dynamic-slot [position]="'Section1'"></cx-dynamic-slot>
<div class="cx-landing-page-layout__container">
  <cx-dynamic-slot [position]="'Section2A'" class="cx-landing-page-layout__slot-2">
</cx-dynamic-slot>

....

Proposal would be to add the missing classes on every other slot (slot1, slot3, slot5) that exist on landing page layout.

**Comment by tobi-or-not-tobi** [comment]
This has been addressed in #353
