### ISSUE TITLE
PR from Walkers: endpoint change 

### ISSUE THREAD

**Issue by waseemHybris** [SAP/cloud-commerce-spartacus-storefront#753]
As a result of the pr review we changed the endpoint to get the counts for stores in countries and regions. Original issue is E2EC-1087:  "a bug fix branch made to basecommerce repo to filter out the counts for countries that are not having the same base stores so we avoid the case where a country doesn't have a region but the store counts are returned even though it doesn't belong to the same base store."

----

The PR to review for Spartacus is #753
Is created to adjust the call from the front end after changing the api to fetch the count for stores in countries and regions

The rest of the E2EC ticket is for C3PO, which was merged in December.

**Comment by marlass** [comment]
I don't think it works correctly.

Result of request to changed endpoint:
`{
   "errors" : [ {
      "message" : "No PointOfService with name storescounts, type STORE found in baseStore electronics",
      "type" : "UnknownIdentifierError"
   } ]
}`

Is it caused by our server configuration?

**Comment by hackergil** [comment]
dev20 has been updated and it has commercewebservices-M3. You can test this there
https://dev-com-20.accdemo.b2c.ydev.hybris.com:9002

**Comment by Xymmer** [comment]
tested with dev17 (dev20 doesn't have latest, servers are mixed up)
got response for store count, passing

```
{
    "countriesAndRegionsStoreCount": [
        {
            "count": 49,
            "isoCode": "JP",
            "name": "Japan",
            "type": "COUNTRY"
        }
    ]
}
```
