### ISSUE TITLE
Backend/OCC: Spelling Mistake: 'This field is not a valid email addresss'. Three s's.

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#755]
From #730 - smoke testing Dec 18 lib release
Check registration and login pages.

**Comment by marlass** [comment]
Search all our files and doesn't found provided text. I assume that comes from backend API. Should be fixed there.

**Comment by Xymmer** [comment]
Found in ycommercewebservices/web/webroot/WEB-INF/messages/messages_en.properties
field.invalidEmail=This field is not a valid email addresss.

So it's team Stingrays.
