### ISSUE TITLE
Error banner does not go away when registering

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#756]
From #730 - smoke testing Dec 18 lib release
Tried to register using email address aaa@aaa.aaa, which was not a valid email address. So the banner saying it wasn't valid appears. Then I finish logging in (with a correct email address). But the banner is still there.

**Comment by kacperknapik** [comment]
waiting for @marlass to decide if we should remove all messages or just login/register-related

**Comment by Xymmer** [comment]
tested
