### ISSUE TITLE
Spartacus says to change quantity after adding but there is no way to do so

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#757]
From #730 - smoke testing Dec 18 lib release
Instructions indicate to change the quantity of a product after adding it directly from the search results page (without clicking on the item, just by clicking 'Add To Cart'). However, there is no option in that modal to change the quantity. Perhaps the instruction "Click on 'View Cart'" should be added.

**Comment by Xymmer** [comment]
looks good!
remember that the quantity that appears in the modal should be the total in cart
so if the person clicks add to cart 2 times separately, it should show as 2
Change title to say "Item added to your cart"
Add note underneath Total saying "The quantity represents the total number of this item in your cart."

**Comment by Pucek9** [comment]
Ok, let us first to update +/- directive (#830), it has some troubles

**Comment by Matejk00** [comment]
QA is done. Quantity switcher in modal is working as expected.
