### ISSUE TITLE
Text for applied promotion appears twice in cart and checkout summary

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#759]
From #730 - smoke testing Dec 18 lib release
Duplicate Text: "Buy over $200.00 get $20.00 discount on cart" appears twice on the View Cart page
Duplicate Text: After creating a shipping address, "Buy over $200.00 get $20.00 discount on cart" displays twice on the right and side of the screen in bold green

**Comment by marlass** [comment]
1. Will remove this information above product and only left info under order summary.
2. Seems that this is backend problem:

![image](https://user-images.githubusercontent.com/6259079/50487789-e8e2d100-09ff-11e9-91bf-8f78a8a06db0.png)

We get multiple entries of this message. At least I will make them show in separate lines, not as one string.

**Comment by marlass** [comment]
I didn't saw any potential promotions, but I only noticed in code, that the information above products in cart is prepared to display them if we receive them from backend. That is the only place that is prepared for that situation. If we don't want them I can remove this information from that place.

**Comment by Xymmer** [comment]
this ticket is about fixing up the applied promotions. workl on potential is a separate effort once applied is cleaned up.

**Comment by Xymmer** [comment]
being fixed in another ticket
