### ISSUE TITLE
Store finder - Impossible to view store's description page for stores under a country

### ISSUE THREAD

**Issue by ChrisXJH** [SAP/cloud-commerce-spartacus-storefront#773]
## Environment
- Spartacus:  styles-0.1.0-prealpha.6
- Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- OS: macOs Mojave 10.14.1 (18B75)
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Other environment details:
        Angular CLI: 6.2.6
        Node: 10.14.1
        Angular: 6.1.10

## Expected Results
Should be able to view the store's description after clicking on a store under a country

## Observed Results
Page will route the Spartacus's home page instead of displaying the store's description.

## Steps to Reproduce
Go to store finder -> go to view all stores -> click on a country name (e.g., United States) -> click on one of the stores available in the country

## Offer to Fix
No

**Comment by mszczepaniak** [comment]
We are waiting for the https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/589 to be merged, so that the E2E tests are not failing anymore
