### ISSUE TITLE
[dupe of #3942] Store finder - find stores pages are not logged in the router

### ISSUE THREAD

**Issue by eliztrinh** [SAP/cloud-commerce-spartacus-storefront#779]
For all details, please see https://jira.hybris.com/browse/E2EC-1356
priority: Minor

## Expected Results
All clicking to the next page are logged in the router so when you click back you go to the previous page.

## Observed Results
It takes you back to the very beginning of store finder (before you clicked search button).

## Steps to Reproduce
go to store finder -> find stores -> go to the next page a few times -> click backward button of the browser

it takes you back to the very beginning of store finder (before you clicked search button).

**Comment by Xymmer** [comment]
trying to repro but blocked by #1236

**Comment by Xymmer** [comment]
don't think this is blocked anymore
pagination is working, and #1236 is more of an improvement

**Comment by Xymmer** [comment]
dupe of #3942
