### ISSUE TITLE
Hide contact us link in storefinder description (if there is no link?)

### ISSUE THREAD

**Issue by eliztrinh** [SAP/cloud-commerce-spartacus-storefront#780]
For details, please see https://jira.hybris.com/browse/E2EC-1349
Priority: Minor

## Expected Results
There should be at least a generic contact page and not a 404

## Observed Results
Page displays "404-not found"

## Steps to Reproduce
Go to Store-finder > View all stores
Click on any stores to go to their details description
Click on the "Contact Us" link

**Comment by Xymmer** [comment]
tried to repro but as of feb 2019, don't see any contact info. need to fix that first

**Comment by Xymmer** [comment]
For now, let's hide the 'contact us' link.
I'd expect it to allow me to contact that store directly, but looking at backoffice, i don't see how that information is available.
This feature also wasn't in Accelerator.
