### ISSUE TITLE
Store-Finder: Address line 2 not appearing?

### ISSUE THREAD

**Issue by eliztrinh** [SAP/cloud-commerce-spartacus-storefront#781]
For details, please see https://jira.hybris.com/browse/E2EC-1350
Priority: Minor

## Expected Results
The address should also include "196 Allen St". (line 2)

## Observed Results
only address line 1("New York, New York, 10002") is displayed in the address. 

## Steps to Reproduce
go to store finder -> view all stores -> choose one store(e.g., "new york/new york store")

**Comment by Xymmer** [comment]
i wasn't able to repro with standard sample data; we'll have to add more addresses and do tests first.

**Comment by Xymmer** [comment]
Make sure we are including address line 2 from data sent back to us.
