### ISSUE TITLE
Storefinder: store detail page should reflect that there's no phone data rather than leaving "Call" on the page

### ISSUE THREAD

**Issue by eliztrinh** [SAP/cloud-commerce-spartacus-storefront#782]
For more details, see https://jira.hybris.com/browse/E2EC-1348
Priority: Minor

## Expected Results
For the example of Chicago Store, Call with no number is meaningless to the user. Store Features also has no data. 

This information shall either not be shown or shown as "not available". For more info, we should verify with PO.

## Observed Results

- Nakano

 => Call +81 7093 958, Feature has data such as Wheelchair Access, Buy Online Pick up In Store, Creche

- Chicago

 Store => Call = no data , Store Features = no data

## Steps to Reproduce
1. Go to Store-finder -> view all stores -> click on Japan >> Nakano store
2. Go to Store-finder -> view all stores -> click on United States for Chicago store details

**Comment by Xymmer** [comment]
as of feb 8, can't even see full store details.

**Comment by Xymmer** [comment]
i could see full store by clicking show all locations, but couldn't find one that has no number. need to repro first by manipulating backend.

**Comment by Xymmer** [comment]
I couldn't find any store without a number in mock data. I had to remove the phone number from an existing store (e.g. Kobe Bay Sheraton Hotel and Towers).
For this task:
- Ensure that we don't display "call" if there is no phone number data
- OK if we leave the blank line

![image](https://user-images.githubusercontent.com/4998145/55718546-f11cb600-59c9-11e9-8773-99eeb77afd63.png)
