### ISSUE TITLE
[Blocked, wait for #3941] if geolocation doesn't work: Store-finder: permission to use location not triggered, possibly we display neverending spinner

### ISSUE THREAD

**Issue by eliztrinh** [SAP/cloud-commerce-spartacus-storefront#784]
'Use my location' currently doesn't ask you for permission and displays a list of storefronts with the map.

- check if we trigger permission
- avoid never-ending spinner if user declines (use some default location that is configurable)

Note: it's possible that 'use my permission' doesn't work unless integrated/connected with actual Google Maps... need to check what's going on under the hood.

**Comment by KateChuen** [comment]
**Bug Triage:**
We should look into whether we can detect if the user has allowed the location.

**Comment by Xymmer** [comment]
also as of feb17, use my location seems to have no effect. let's get it working so the browser asks and then we can fix the spinner at same time.

**Comment by Xymmer** [comment]
I checked this  but couldn't verify 100%.
To do for this ticket:
- Make sure we are triggering the browser's location service when the user clicks "use my location".
- If the user says no, make sure we don't display spinner endlessly. Display message "Location information not available. Possible cause: the browser's setting for allowing location tracking is disabled for this site.".

**Comment by Matejk00** [comment]
Will be fixed in #4238
