### ISSUE TITLE
Shipping is shown as "free" on cart

### ISSUE THREAD

**Issue by eliztrinh** [SAP/cloud-commerce-spartacus-storefront#786]
For details & screenshot please see https://jira.hybris.com/browse/SPA-1423
Priority: Medium

## Environment Details
recipe : b2c_acc_oms 
using spartacus storefront 
platform commerce-suite-1811.0.26891

## Expected Results
Estimated shipping should be 9.99$

## Observed Results

Notice how the 9.99$ is included in the subtotal but shown as "Free" in estimated shipping.

## Steps to Reproduce

- Log in as an user
- Place an order while selecting "Standard delivery" for 9.99$
- Submit the order

**Comment by KateChuen** [comment]
**Bug Triage:**
Has to check if it's a backend configuration problem or not (promotions?)

**Comment by Xymmer** [comment]
We don't have any way of estimating shipping yet, so cart should show TBD until we update this.

**Comment by bgambocjaviniar** [comment]
PR #1714

**Comment by plabadie** [comment]
I smoke tested and the third requirement does not behave as expected:

> if user changes shipping destination, the shipping should go back to TBD, the shipping method is cleared, and the user has to choose a shipping method again.

The shipping method isn't cleared when I change the shipping address.  Suggestion to make to make the logic simpler: each time we select an address, we could clear the shipping method.  Does this make sense?

Also, I think this requirement:
> in checkout: the subtotal should show TBD until the user chooses a shipping destination, then the amount should change.

Small thing, but I think the second requirement was about selecting the _shipping method_, and not the _shipping destination_ (I guess this was the intent):
> in checkout: the subtotal should show TBD until the user chooses a shipping destination, then the amount should change.

**Comment by plabadie** [comment]
Requirements above cleared up.  They are updated in Xymmer's comment.  A followup spike is created to investigate the third requirement.

The second requirement is also cleared up.

**Comment by plabadie** [comment]
Just wait for a green e2e build before merge.

**Comment by KateChuen** [comment]
Tested on dev22. 
It's now TBD until the user chooses the shipping method.
<img width="1008" alt="cartAnonymousUser" src="https://user-images.githubusercontent.com/45409515/54844440-545dd700-4cad-11e9-908d-d598e232b9a4.png">

Shipping amount is changed when user changes shipping method.
<img width="993" alt="afterChangeShippingMethod" src="https://user-images.githubusercontent.com/45409515/54844470-63448980-4cad-11e9-962f-5e6f542d3eb2.png">
<img width="1010" alt="beforeChangeShippingMethod" src="https://user-images.githubusercontent.com/45409515/54844471-63448980-4cad-11e9-84f6-12cac60a2eed.png">

Only thing that doesn't work and that's already pointed out with ticket GH-1743 is when we change the shipping address. Looks like it's reflected in the order summary but not in the shipping methods options.
<img width="1012" alt="changeShippingAdd" src="https://user-images.githubusercontent.com/45409515/54844562-99820900-4cad-11e9-912d-ece60c3e0662.png">
