### ISSUE TITLE
Additional work on billing address

### ISSUE THREAD

**Issue by kacperknapik** [SAP/cloud-commerce-spartacus-storefront#791]
While implementing billing address (#93) I came across a potential backend problem. Currently one of the properties of returned object from `cart.service.ts:248:getPaymentProviderSubInfo()` is `mappingLabels.entry`. It looks like this: 

```
{
// other labels
hybris_billTo_city: "billTo_city",
hybris_billTo_country: "billTo_country",
hybris_billTo_firstname: "billTo_firstName",
hybris_billTo_lastname: "billTo_lastName",
hybris_billTo_postalcode: "billTo_postalCode",
hybris_billTo_street1: "billTo_street1",
// other labels
}
```

We need to rename and add new labels, because billing address consists of more than 6 fields of data.

After implementing new labels, `checkout.effect.ts:294` should be modified accordingly.

**Comment by WeizhengSap** [comment]
`mappingLabels.entry` contains all fields required by the payment provider. So, we cannot rename and add new labels. If billing address consists of more than 6 fields of data, then those data are not required.

**Comment by kacperknapik** [comment]
@Xymmer according to what @WeizhengSap said, we should probably change the billing address form. I'll leave it as it is now. but we should really consider removing some fields, if the payment provider doesn't really need all of them
