### ISSUE TITLE
Spike multi-site

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#8]
While our commerce backend is really strong with multi-site capabilities, this has not yet land fully in the Spartacus storefront. We already support multi-site with a configuration property, but the true multi-site features require:
- a lookup on the storefront domain in the backend. This is done in commerce cloud by default for accelerators, but must be added here. It requires a new endpoint that takes the current location (url). 
- an endpoint that provides all (available) stores / sites, so that we can build a site landing page (i.e. "select your country site")
- allows for multiple catalogs for sites that are driven in a multi-country fashion

**Comment by Xymmer** [comment]
also need tickets :)
dependency on Stingrays to make a change to backend

**Comment by Xymmer** [comment]
closing as we have several multi-site tickets now
