### ISSUE TITLE
Configurable url context parameters (eg. currency, site, lang)

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#803]
Context url parameters should be configurable. For example:
```
context parameters: [ 'lang', 'currency' ]
mystore.com/en/USD/
```
```
context parameters:[ 'site', 'lang', 'currency']
mystore.com/electronics/en/USD/
```
```
context parameters: [ 'lang' ]
mystore.com/en/
```

The url context parameters will affect whole configurable routing (configurable router links, configurable routes definitions, recognition of dynamic URLs from CMS)

Depends on: #186

**Comment by Xymmer** [comment]
[x] Check if default site context parameters are added to url (localhost:4200 -> localhost:4200/en/USD/)
[x] Check if default site context parameters are added to partial url (localhost:4200/en -> localhost:4200/en/USD/)
[x] Check if navigation in app works
[x] Check if changing the parameter (language/currency) in the url will affect the app
but created bug #1276
[ ] Check if changing the parameter from the app will affect the url
(couldn't test as the language menu is missing; will test later)

Check the configuration in app.module.ts:
[ ] change order `siteContext: { urlEncodingParameters: ['currency', 'language'] }}`
[ ] remove one parameter `siteContext: { urlEncodingParameters: ['language'] }}`

-----
[ ] Check if it works in SSR (optional) (not done)

**Comment by tobi-or-not-tobi** [comment]
I'm do QA on the last 3 steps:
[ ] Check if changing the parameter from the app will affect the url
(couldn't test as the language menu is missing; will test later)

Check the configuration in app.module.ts:
[x ] change order `siteContext: { urlEncodingParameters: ['currency', 'language'] }}` Works, but a bug was detected #1288 
[ ] remove one parameter `siteContext: { urlEncodingParameters: ['language'] }}`
