### ISSUE TITLE
Leave the standard routes alongside the configured ones as a fallback for external plugins

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#814]
Some external plugins may expect the standard Spartacus' URLs (for example `/product/xxxxx`) to respond. Currently in Spartacus the standard routes are replaced with the configured ones.

So we should leave the standard routes alongside the configured ones. Or as an alternative just redirect from the standard to the configred ones.

**Comment by tobi-or-not-tobi** [comment]
It would be nice to use the existing accelerator routes as the default, or as a 2nd alternative. Those routes aren't necessarily perfect, but they will help with a smooth transition from old implementations as well as integrations from third-party systems.

**Comment by Platonn** [comment]
Wildcard routes were implemented in GH-1978 (**/p/:productCode, **/c/:categoryCode), so existing accelerator routes are working.
