### ISSUE TITLE
Rerender components and content slots after editing

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#816]
We need one more smartedit ticket for "Rerendering Components and Content Slots After Editing". So that after changing components/slots, spa refresh these content.

**Comment by WeizhengSap** [comment]
PR: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/828

**Comment by WeizhengSap** [comment]
Please read this before review and test:https://wiki.hybris.com/pages/viewpage.action?spaceKey=CxM&title=SmartEdit+Contract+for+Storefronts+-+1811#SmartEditContractforStorefronts-1811-RerenderingComponentsandContentSlotsAfterEditing  (only Frontend Rendered Pages is supported)

After editing/removing components or slots, you should be able to see the changes.
