### ISSUE TITLE
[Probably close as probably smartedit]Opening generic editor for hidden component reloads the whole storefront

### ISSUE THREAD

**Issue by stepan-aleksandrov** [SAP/cloud-commerce-spartacus-storefront#818]
## Expected Results
Opening SmartEdit generic editor should not reload the storefront.

## Observed Results
Opening SmartEdit generic editor for a hidden component reloads the whole storefront and “loading…” message does not disappear .

## Steps to Reproduce
1) Find a component that belongs to a page (if there is no such components, clone one)
2) Open smartedit generic editor
3) Add a time restriction (start date: tomorrow, end date tomorrow)
4) Save
5) Refresh the page
6) Open generic editor for hidden component

**Comment by Xymmer** [comment]
Talk to Stepan about how to add hidden component

**Comment by WeizhengSap** [comment]
I made the component "ElectronicsHomepageSplashBannerComponent" invisible. 

I can see that this is added in smartedit.
```
<a href="#" data-ng-if="!ctrl.readOnly" class="slot-visiblity-component-template__text slot-visiblity-component-template__text__name ng-binding ng-scope" 
data-ng-click="ctrl.openEditorModal()">Electronics Homepage Splash Banner Component</a>
```

![Screen Shot 2019-03-12 at 2 20 24 PM](https://user-images.githubusercontent.com/44440575/54225464-1e14a080-44d2-11e9-84d2-be16834821af.png)

**Comment by Xymmer** [comment]
@WeizhengSap what would make this not on hold? :)

**Comment by WeizhengSap** [comment]
@Xymmer : Stepan is investigating this ticket. I don't think it is an issue in SPA side. He will give feedback after investigating.

**Comment by Xymmer** [comment]
Bill to follow up with Stepan March 20

**Comment by WeizhengSap** [comment]
I will close this ticket because it is on smartedit side. The ticket is: https://jira.hybris.com/browse/CMSX-8368
