### ISSUE TITLE
[hold] In backend, change old URLs in sample CMS data and remove redirects from the code

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#822]
Currently, the sample CMS data contain old URLs like `/Open-Catalogue/Cameras/Digital-Cameras/c/575`, when standard Storefront's routes are different (for example `/category/575`).

To help that, we have added some "redirect routes" from old URLs to standard ones. The drawbacks are:
- those routes end up in the code of the library, but most users don't neet it
- those routes cause problems with configurable routes in some cases

So we should:
1. change sample data to contain only the standard Storefront's URLs
2. remove unnecessary "redirect routes" from the code

### URLs
```
// standard
category/:categoryCode

// old
Open-Catalogue/:title/c/:categoryCode
Open-Catalogue/:category1/:title/c/:categoryCode
Open-Catalogue/:category1/:category2/:title/c/:categoryCode
OpenCatalogue/:category1/:category2/:title/c/:categoryCode
```
```
// standard
product/:productCode

// old
Open-Catalogue/:category1/:category2/:category3/:category4/p/:productCode
```

**Comment by Xymmer** [comment]
Kris says postpone this one until a decision is made on the future of support.

**Comment by Platonn** [comment]
No need to change sample data. Redirects were removed thanks to wildcard routes in GH-1978
