### ISSUE TITLE
Implement Google API Key in Storefront Config

### ISSUE THREAD

**Issue by wishfulthinkerme** [SAP/cloud-commerce-spartacus-storefront#824]
For now we are using e2eservices to obtain google API key. It seems that at some point these services stopped working so, e.g. maps in Store Finder doesn't work.

After talk with Bill/Tobias/Stan we decided to move key to storefront config and stop using e2eservices, as on Spartacus we should only use OCC.

In the future we might move key to backend and obtain it from there, but are not ready yet.

**Comment by Matejk00** [comment]
There is no possibility to obtain Google API key using e2e service call anymore. All the time server returns 404 status. For now we can add such key as storefinder config property.

**Comment by Matejk00** [comment]
PR: #1047
