### ISSUE TITLE
Upgrade to Angular 7.2

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#825]
The latest and greatest version of Angular is out v7.2. When updating to Angular 7, the goal was to directly go to 7.2 but because it wasn't released we had to settle on 7.1.4.

The update to 7.2 should be seamless from 7.2.

**Comment by LTiger14** [comment]
Waiting on Angular cli 7.2 to release. Should happen January 9th 2019.

**Comment by LTiger14** [comment]
Waiting for https://github.com/angular/angular-cli/issues/13387 should be resolved tomorrow (Jan 10)

**Comment by plabadie** [comment]
Updated the installation script, see PR: https://stash.hybris.com/projects/C3PO/repos/spartacus-installation/pull-requests/18/overview
