### ISSUE TITLE
[to be confirmed for cancel] Remove `only-number.directive.ts`

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#830]
A custom directive was introduced to validate form values and add additional logic to numeric fields. This is too complex, and there are already standard things to use.

To begin with, there's an html5 input number type. This native input only allows for numbers and does allow for copy, paste, delete, etc. If the UI would not allow for the standard controls (aka input spinners), we can hide them with css, see https://css-tricks.com/snippets/css/turn-off-number-input-spinners/. 

Additionally, angular template and reactive forms provide validation logic. This could also be used. 

For now, I'd like to use html5 number inputs. It's simple, and doesn't require additional changes.

**Comment by Pucek9** [comment]
@tobi-or-not-tobi
After verification your solution we can see that's not enough for our expectation. 
type="number" unfortunately allows for remove value (to be ""). We need additional logic to force keeping value

That directive will be also probably place for fix bug in #512
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/512

**Comment by Pucek9** [comment]
@tobi-or-not-tobi
There are 2 new proposals:

1 -/+ are not disabled when we are out of range (eg. 0, more than available). Clicking on button going to correct direction are icreasing/decreasing value by 1. Similar with left/right arrow keys on keyboard. What about set it immediately to min/max value?
2 Clicking on -/+ are blocking themself for moment of fetching data. Left/Right arrows are not. So there is still posibility to increase/decrease value in input. All of them are triggering action "[Cart-entry] Update Entry" which trigger loading data. What do you think to unify it and use debouncing there (Better UX and optimize API calls)

**Comment by tobi-or-not-tobi** [comment]
The only-number.directive.ts is just not good imho, but I agree that my proposed solution isn't working.  If we use reactive forms we could add a validator to manage this. Let's cancel for now, It might come back with a better solution in mind.
