### ISSUE TITLE
Error while creating Breadcrumbs

### ISSUE THREAD

**Issue by maazahmed12** [SAP/cloud-commerce-spartacus-storefront#834]
## Environment Details

- Spartacus:  
- Browser: 
- OS: 
- Device: 
- Other environment details: 

## Expected Results

I just created breadcrumbs and they were working fine untill I took the latest pull:

![image](https://user-images.githubusercontent.com/42023747/50894802-03687180-1426-11e9-9568-c144dc7d75cc.png)

## Observed Results

Now it gives an error because of this line in Breadcrumb.component.ts:

![image](https://user-images.githubusercontent.com/42023747/50894887-46c2e000-1426-11e9-93f4-e1cad94557b2.png)

which looks like this:

![image](https://user-images.githubusercontent.com/42023747/50894933-68bc6280-1426-11e9-93d6-8744dbc93959.png)

## Offer to Fix

YES

**Comment by Xymmer** [comment]
Hey @maazahmed12, see comments in #823.
Currently we're spiking this issue - see  #136.
