### ISSUE TITLE
SPIKE: Generic CMS content pages

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#846]
Content pages can be setup in the CMS by business users. They will create any content pages, like:

/help
/help/faq
/help/contact

We currently do not support this. 

we should support local prefixes, i.e.

/de/help
/de/help/faq
/de/help/contact

However, we do not translate the URL parts.

**Comment by Platonn** [comment]
Close spike ticket without merging the code.
