### ISSUE TITLE
Refactor async logic in product carousel component

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#853]
Please check if it's possible to refactor it in a way, that subscribe is not necessary.

Some hints:
1. `productCodes$` can be a result of `this.component.data$.pipe(...)`
2. `resize$` can be changed to windowWidth$
3. `productGroup$` can be a result of `combineLatest(productCodes$, windowWidth$).pipe(...)`
4. `products` array could be populated in a `tap` of `productCodes$`

**Comment by tobi-or-not-tobi** [comment]
Refactoring is implemented as part of #884.
