### ISSUE TITLE
Sorting by Top Rated results are strange when also applying facet filtering

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#863]
**Environment**: 
SPA with yenv (develop branch)

 
**Steps**:
Go to electronics storefront
Search for "DSC-N1" -> Should have 21 results
Sort by "Top Rated" -> Results look good, first item listed is: Cyber-shot DSC-W55
 
![sortbytoprated](https://user-images.githubusercontent.com/45409515/51051424-b7dad280-15a1-11e9-99f3-b260c0314cb9.png)

Now, filter by Megapixels "10 - 10.9 mp (10)"
 

**Actual Result:**
The results are off. The first item is now:DSC-S930
Previously first item listed (Cyber-shot DSC-W55), is now displayed as 9th on the list.
Items with less stars, and no stars are displayed before it. 
![filterbymegapixels](https://user-images.githubusercontent.com/45409515/51051451-ccb76600-15a1-11e9-9020-2dacff8649fd.png)

**Solution**:
Jose from Cthultu team investigated and said:

> The issue is that the relevance and topRated sorts have inStockFlag as first sort field, if you remove it it should work fine.
This should be fixed on the sample data for the sample stores which does not belong to us.

**Comment by Xymmer** [comment]
closing as it's a sample data / config issue
