### ISSUE TITLE
Create Spartacus gradle recipe file for 1811

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#865]
Until a standard recipe works properly with Spartacus, we need to create a special recipe for each release. Currently it's only some smartedit extensions that pull in content catalog data that interferes. This should be fixed in 1905. There is one for 1808 based on b2c_acc_plus. We need one for 1811.

1. Duplicate b2c_acc_plus from 1811.
2. Comment out:

//        extName 'cmswebservices'
//        extName 'smarteditwebservices'
//        extName 'cmssmarteditwebservices'

//        extName 'previewpersonalizationweb'

all 'personalization...' extensions
//        extName 'personalizationcmsweb'
// ....

all 'merchandising...' extensions
//extName 'merchandisingaddon'
// ...

3. From pl.project.addons section, remove:
the 2 'personalization' addons 
the 2 'merchanding' addons.

Use this file to test with newest setupandinstallation instructions (#44).

After it passes testing, add this file to docs/assets. Move the existing file to archive to go along with setupandinstallation archive instructions for 1808.

**Comment by gladius-mtl** [comment]
Merged as part of GH-44.
