### ISSUE TITLE
CI build improvements

### ISSUE THREAD

**Issue by bcullman** [SAP/cloud-commerce-spartacus-storefront#868]
According to the (admittedly aged) tweet here:

https://twitter.com/travisci/status/424990533447327744

The TravisCI environment is limited to 5 concurrent builds per org. We think these lines in your travis config allocate 2 of those shared resources at once: 

https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/.travis.yml#L16-L25

Would you be willing to look into changing this configuration so they run serially, so that TravisCI resources can be distributed a bit more?

Additionally, would you be willing to look at other ways to speed up your build time?

**Comment by bd82** [comment]
Hello.

Have a look at enabling **yarn caching**, that should shave off ~30seconds from each of your sub builds.
https://docs.travis-ci.com/user/caching/#yarn-cache

Also The "validation" sub build takes 1.5minutes, of which only **a few seconds** seem to be actually running the validations, so you could run both "Validation" and "Lint" scripts in the same travis container sub build.

**Comment by hackergil** [comment]
Pull request #933 to observe build times
