### ISSUE TITLE
Create e2e tests around language/currency

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#869]
Right now, the E2E test that we have around language/currency, only tests changing it on PDP page. 

We want to have more tests that will cover checking other pages: 

- [x] Language switch during registration

- [x] Language switch on MyAccount 
      - 8 pages of my-account except sign out
 
- [x] Language & Currency switch on product search 

- [x] Language & Currency switch on product details, then add to cart (check add to cart modal also)

- [x] Language & Currency switch on cart page (with promotions)

- [x] Language & Currency switch during checkout

**Comment by bgambocjaviniar** [comment]
PR: GH-2887

**Comment by bgambocjaviniar** [comment]
taking this back for a second, somehow its failing
