### ISSUE TITLE
Changes to forms now that title code no longer mandatory

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#872]
Title code no longer required (dependency on RAY-74), we'll remove it on some pages and make sure it is optional for others

Remove from:
- Registration page
- Shipping and billing address pages during checkout

Display but make sure it is optional from:
- Address management edit/add (add "None" option but send blank to backend; make "None" the default in grey instead of "Select title")

Check if elsewhere.

Check related tickets #440 and #287 and see if they are fixed or we can close them. If not, pull them into the sprint and fix them.

**Comment by Xymmer** [comment]
update: RAY-74 now merged but not sure if it's in a commerce suite, we'll need it in a cs so we can use it. am checking...

**Comment by Pucek9** [comment]
Backend doesn't allow for register user without titleCode ('' or null)
```
message: "This field is required."
reason: "missing"
subject: "titleCode"
subjectType: "parameter"
type: "ValidationError"
```

**Comment by Xymmer** [comment]
check with gil if we have latest milestones / cs's from them

**Comment by Xymmer** [comment]
also, i realized we'll be causing a problem with this change for people who don't have 1905.
is there a way to test if this field is mandatory, and show the field, but otherwise, hide it?
the way people test for features in JS
so that people using 1811 or 1808 aren't prevented from registering a user.

**Comment by Pucek9** [comment]
Branch with changes is already done, but need wait for testing possibility
https://github.com/SAP/cloud-commerce-spartacus-storefront/tree/feature/GH-872

**Comment by Xymmer** [comment]
Hey all, after talking with Patrick I realized that my request and the solution i proposed would result in emails being sent in the form of "None Bill Marcotte". 

At the same time we need to be backwards compatible with 1811 because otherwise people won't be able to register. 

If you submit an OCC request without title code, this is returned in the body:
 ```
       {
            "message": "This field is required.",
            "reason": "missing",
            "subject": "titleCode",
            "subjectType": "parameter",
            "type": "ValidationError"
        },
```

So:

- Keep "salutation" field in registration and shipping address pages
- Change the "Select title" grayed out option to a selectable option titled "No title" (which submits empty string to backend) - this doesn't come from backend, it's in Spartacus.
- Action button activates even if "Title" is set to "No title"
(Action button in registration is "Register", in shipping address it's "Continue")
It's not visible in Billing Address (I guess it's not needed there? we're so inconsistent :) )
- If you submit and the backend is 1811 or earlier, an error message is returned. If titleCode is the error, display note underneath the title form. Display "Please correct the errors below" in the top red global notification bar. If you submit with 1905, you won't get an error.

Let me know if this makes sense!

**Comment by Pucek9** [comment]
Waiting for VPN credentials

**Comment by Xymmer** [comment]
if Mr. Pucek9 doesn't get vpn access soon, let's assign to someone else.

**Comment by Pucek9** [comment]
Tested manually on: https://dev-com-17.accdemo.b2c.ydev.hybris.com:9002 - looks good

I've added workaround to convert empty string to null and reverse in sending/fetching data in address book form. Please tell me what do you think about this change, maybe let decide to update backend?

**Comment by Pucek9** [comment]
17: allow register and add address without selecting title (workaround converts empty string to null and null to empty string)
20: not allow for register without title (workaround changes server's global message from "'This field is required.'" to "Title is required" ).
Not allow to add/update address without title, replaced message: "Invalid Address" / "Title is required"
