### ISSUE TITLE
Smoke tests for release 2019/01/14

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#875]
Use this server: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/

Keep the browser's console open at any time and monitor for errors.

Perform the following smoke tests:

@kacperknapik 
- [x] Register, logout, login with the previously registered user
- [x] Go through checkout flow with the previously registered user:
- [x] Search for a product and open it
- [x] Check all tabs (product details, specs, reviews and shipping)
- [x] Add it to cart
- [x] Search for any other product and add it to cart directly from the search results page (don't open the product, just click on "add to cart")

@mszczepaniak 
- [x] Change quantity
- [x] Create a new shipping address
- [x] Create a new payment method
- [x] Repeat for an existing user (any user that was registered before the smoke testing)
- [x] Check all other functionality/pages and observe is basic functionality broken, are there any UI elements broken, etc.:

@Matejk00 
- [x] Order history page
- [x] Change language/currency
- [x] Sort
- [x] When searching, use facets and filters
- [x] Check pagination

**Comment by mszczepaniak** [comment]
Minor: Quantity counter is missing the bottom border

![screenshot 2019-01-14 at 15 53 31](https://user-images.githubusercontent.com/4272069/51120091-a51c0400-1814-11e9-93d8-4e71336850c8.png)

**Comment by Matejk00** [comment]
When customer has no any shipping address added yet and want go through the checkout in the console following error appears:

Chrome:
![console_err](https://user-images.githubusercontent.com/6958810/51121449-c0d4d980-1817-11e9-88b5-8e762005a033.png)

Firefox:
![console_err_ff](https://user-images.githubusercontent.com/6958810/51121450-c0d4d980-1817-11e9-9299-650b628cc322.png)

**Comment by marlass** [comment]
Created separate issues for bugs found while testing new release.
