### ISSUE TITLE
The facet names "lens type" and "color" aren't localised in DE

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#881]
**Environment:**
SPA with yenv (develop branch)

**Steps:**
Go to electronics storefront
Search for "canon" in English
Change the language to Japanese (the facets names are localised)
Change the language to Deutsch

**Actual Result**
The facets for "lens type" and "color" don't seem to be localised. 

![facetsde](https://user-images.githubusercontent.com/45409515/51131845-cd990380-17fe-11e9-8d8a-c97483cbe020.png)
![facetsja](https://user-images.githubusercontent.com/45409515/51131852-d12c8a80-17fe-11e9-80db-fd7193d792d3.png)

**Comment by KateChuen** [comment]
**Bug Triage**
Just check if it's backend issue.

**Comment by KateChuen** [comment]
Bug Triage: 
On the ACC, it shows up as:
<img width="1422" alt="facetsoldacc" src="https://user-images.githubusercontent.com/45409515/51257377-77020580-1975-11e9-8530-d813fb3c45d9.png">

**Comment by Xymmer** [comment]
Backend localization issue, we display what we get. not a spartacus bug
