### ISSUE TITLE
Specs & Reviews empty when change language to anything other than English

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#882]
**Environment:**
SPA with yenv (develop branch)

**Steps:**
Go to electronics storefront
Go to a product details page, for eg, http://localhost:4200/product/1934793
Go to the Specs tab
Change the language to any language other than English.
Go to the Reviews tab

**Actual Result**
The specs tab is empty for other languages.
The review tab is also empty. It shows up as 0 Reviews, but the rating remains.

English:
![productdetails-en](https://user-images.githubusercontent.com/45409515/51134156-c4ab3080-1804-11e9-9410-e22175e8f1a6.png)
![productdetails1-en](https://user-images.githubusercontent.com/45409515/51134157-c4ab3080-1804-11e9-8cc4-532628573e3c.png)

Japanese:
![productdetails-ja](https://user-images.githubusercontent.com/45409515/51134162-cb39a800-1804-11e9-8be8-7f19abe22c80.png)
![productdetails1-ja](https://user-images.githubusercontent.com/45409515/51134163-cb39a800-1804-11e9-8d25-63ab0354e4b1.png)

**Comment by KateChuen** [comment]
**Bug Triage**
Need to investigate if it's backend.

**Comment by Xymmer** [comment]
just checked it, that content comes from the backend, and it wasn't translated. so not a bug
