### ISSUE TITLE
Missing some localisation for MyAccount (maybe)

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#883]
**Environment:**
SPA with yenv (develop branch)

**Steps:**
Go to electronics storefront
Login with a registered user
Change the language to Japanese
Go to MyAccount
Go to Address Book, and click on the dropdown menu for Title.

**Actual Result**
1) Sign out from "MyAccount" is not localised
2) The Mr, Mrs etc in the Title drop down menu aren't localised for Japanese (normal?)
3) Also "web"cam from the navigation bar.

![myaccount1-ja](https://user-images.githubusercontent.com/45409515/51136192-e529b980-1809-11e9-8196-71e00e36b8fc.png)
![myaccount2-ja](https://user-images.githubusercontent.com/45409515/51136193-e529b980-1809-11e9-9944-536ed57fd9fa.png)

**Comment by Xymmer** [comment]
we're revamping translation so i'm closing this one and we'll do a new review later
