### ISSUE TITLE
[retest]Quantity counter is missing the bottom border

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#887]
Quantity counter is missing the bottom border. Found while doing smoke tests for release 2019/01/14.
https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/875
![image](https://user-images.githubusercontent.com/6259079/51166782-f5db3d80-18a4-11e9-9a3b-3ca5f607cf52.png)

**Comment by mikelMHybris** [comment]
![Screen Shot 2019-03-21 at 1 30 43 PM](https://user-images.githubusercontent.com/30266610/54772369-90296b80-4bdd-11e9-9b80-6be88d4a6c41.png)

looks like it is fixed now.

**Comment by KateChuen** [comment]
Tested on dev 22. Looks ok now. 
<img width="1010" alt="borderCartQty" src="https://user-images.githubusercontent.com/45409515/54841081-e01f3580-4ca4-11e9-9500-89a37027b1b1.png">
