### ISSUE TITLE
[reverted] Use push strategy for all components by default

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#891]
We need to set the change detection strategy in the root component.

**Comment by tobi-or-not-tobi** [comment]
We set it in the root component and must remove it from any component. With this, customers can change it in their app. Also, it's easier to maintain.

**Comment by Platonn** [comment]
It turned out that change detection strategy is not inherited, so I'll revert the PR and docs.
But we will ensure that at least all CMS components have explicit `OnPush` change detection strategy - in ticket GH-1009
