### ISSUE TITLE
customize the OrderDetail page without modifying the source code

### ISSUE THREAD

**Issue by linlinmq** [SAP/cloud-commerce-spartacus-storefront#903]
The orderDetailsComponent(angular component) renders the whole page, if try to customize this page:
1. no mapping with the backend CMSComponent, can't use  cmsComponentMapping to customize according to projects\storefrontlib\src\lib\occ\docs\cms-component-implementation.md
2. no <ng-template cxOutletRef > can be used to override the page.

**Comment by Xymmer** [comment]
@tobi-or-not-tobi can you respond to this feedback? is this kind of customization on our roadmap?

**Comment by Xymmer** [comment]
labelling a bug and we'll review in triage

**Comment by Xymmer** [comment]
this applies to my account. 
this was converted to cms components and is now configurable.
