### ISSUE TITLE
missing hamburger dependency

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#904]
With the change of #679 the style lib generates the hamburger menu on the fly. This requires an external dependency to be installed. This is not added to the docs. 

We could do different things here:
- add the hamburger npm module as a (peer)dependencies
- refactor the style lib, so that we have a default hamburger type being pre-compiled and only optionally use hamburger library to add more types. We would then add hamburger in the _optionalDepenendencies_.

We should add a note temporarily to the [installation guide](https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/setupandinstallation.md), so that hamburger is added as a dependency in any case.

**Comment by marlass** [comment]
Yesterday after information about the issue I added hamburger as dependency to `@spartacus/styles`.
Release still needs to be merged to master and develop: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/874

**Comment by Xymmer** [comment]
closing as fixed in another pr
