### ISSUE TITLE
[resolved in #927] Item price is not displayed after load Cart [test after 927 is done]

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#909]
When I go to cart after login, item price is not displayed and rest of elements like Counter and Total is aligned to left. Also Order Summary is not complete.
After change quantity/add somethinng to Cart, table is refreshed and then it's look normal.

![image](https://user-images.githubusercontent.com/8040837/51252705-cc9dd880-199c-11e9-810b-71d7293ca7da.png)

**Comment by Pucek9** [comment]
Problem occured on my account after some backend operations. After remove all items, page is working correct again.

**Comment by Pucek9** [comment]
I was trying to reproduce this situation and probably it's possible after change quantity and remove object in same time. We need to block "Remove" link when cart is loading / user is changeing Qty value

**Comment by Pucek9** [comment]
Closed by #927

**Comment by Xymmer** [comment]
retest once #927 is done

**Comment by Xymmer** [comment]
verified on github.io
