### ISSUE TITLE
The number of items added to cart is not correct in add-to-cart popup

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#918]
Currently, this number is the quantity get from counter. It is not correct. This number should be: 
if input.quantity <= maxQuantity (stockLevel) - cart.entry.quantity; then number = input.quantity; otherwise, number = maxQuantity (stockLevel) - cart.entry.quantity.
 

![screen shot 2019-01-17 at 2 52 20 pm](https://user-images.githubusercontent.com/44440575/51344993-e0fad780-1a67-11e9-9d74-b94187cd1b6f.png)

So, for one product, if it is already in cart, and the quantity of this product in cart is 3. If the max quantity is 4, then only 1 can be added to cart. If the max quantity is 3, then 0 can be added to cart. It should be something like this:

![screen shot 2019-01-17 at 2 53 14 pm](https://user-images.githubusercontent.com/44440575/51345158-4b137c80-1a68-11e9-8043-fbd1c009172a.png)

**Comment by Xymmer** [comment]
no longer applies as we don't say '1 item...'
