### ISSUE TITLE
Inconsistent naming - shipping method vs. delivery mode

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#923]
In the code we use `shipping method` and `delivery mode` to describe one thing. This a bit inconsistent and confusing. It's related to names of classes, properties, component `@Input`s, ngrx store properties and CSS classes.

Examples:
- `class DeliveryModeComponent`
- `class DeliveryModeModule`
- `class DeliveryModeFormComponent`
- property `shippingMethod` in `MultiStepCheckoutComponent`
- `@Input selectedShippingMethod` in `DeliveryModeComponent`
- `@Input shippingMethod` in `ReviewSubmitComponent`
- `deliveryMode$` property in `ReviewSubmitComponent`
- method `getShippingMethodCard(deliveryMode)` in `ReviewSubmitComponent`
- method `getSelectedDeliveryMode()` in `CheckoutService`
- method `loadSupportedDeliveryModes()` in CheckoutService`
- ngrx selector `getSelectedDeliveryMode` in `checkout.selectors.ts`
- and many more...

I suppose `delivery mode` is the correct naming and `shipping method` should be replaced. But this is only my assumption and should be double-checked.

**Comment by Xymmer** [comment]
let's use deliveryMethod

**Comment by kacperknapik** [comment]
can we replace `shipping` with `delivery` in general? this inconsistent naming isn't just delivery mode/method related

**Comment by mirkosoft** [comment]
> can we replace `shipping` with `delivery` in general? this inconsistent naming isn't just delivery mode/method related

I've checked the code for `shipping` word only as well. Most of occurences was for "shipping address" which is a different thing. I was thinking about changing "shipping method" wording for the labels too but I guess this needs to be discussed with @Xymmer and/or UX guys. There were also 2 occurrences in the styles but finally decided to leave it as it is - probably this also can be checked with UX.

**Comment by marlass** [comment]
I would also change that in styles. Every variable/reference should be normalized to one version (obviously apart from label text used in UI, which btw. will be soon moved to translations)
