### ISSUE TITLE
Improve code quality for global-message (#692)

### ISSUE THREAD

**Issue by Pucek9** [SAP/cloud-commerce-spartacus-storefront#924]
Commented in https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/802/files

**Comment by kacperknapik** [comment]
- [x] imports in `global-message.service.ts` rewritten
- [ ] ~~`global-message.module.ts` imports~~ (won't change)
- [ ] ~~`global-message-store.module.ts` imports~~ (won't change)

**Comment by marlass** [comment]
Global messages still work correctly.
