### ISSUE TITLE
Implement change billing address during checkout

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#93]
Our checkout lacks the option to specify a separate billing address.
Feel free to break this ticket into smaller subtickets and use this as the master.

# General Usage

The "credit card payment" screen starts out like this:
![image](https://user-images.githubusercontent.com/4998145/48025703-2b7be180-e112-11e8-9622-8594ef96e575.png)

The "same as shipping" is checked and showing the shipping address by default.

If you clear "same as shipping", you get the address form, just like for shipping.
![image](https://user-images.githubusercontent.com/4998145/48025855-86add400-e112-11e8-922a-702b9ecf61c9.png)

# Different Call for Billing Country
The GET COUNTRIES api allows you to specify whether you want billing or shipping country.
https://help.hybris.com/1808/api/ycommercewebservices/index.html#_countries_resource

The payment screen should use the billing one. 

# Edge-Case: Shipping Country Not Supported for Billing

Usually the list of shipping countries is smaller than billing countries (if there is a difference at all). The "same as shipping" should only be selected by default if the shopper's shipping country is supported in billing list. If not, hide "same as shipping" and display address form immediately.

# More Wires
Password: ask bill
https://98qkkl.axshare.com/#g=1&p=w_checkout_step3_no_payment
https://98qkkl.axshare.com/#g=1&p=d_checkout_step3_no_payment
https://98qkkl.axshare.com/#g=1&p=t_checkout_step3_no_payment
https://98qkkl.axshare.com/#g=1&p=m_checkout_step3_no_payment

# Acceptance criteria
- behavior is as outlined above
note: you can remove countries from billing list through backoffice > base store > shipping/billing area. Ask Giancarlo if there is one that doesn't exist in billing that's in shipping.
- tested in 4 responsive viewports
- when i tap on a form field using a phone, it scrolls up so the keyboard doesn't hide it
- address verification modal is called after submitting new address, and behaves like shipping does
- unit tests
- update e2e tests if necessary

**Comment by kacperknapik** [comment]
currently waiting for resolving e2e tests conflicts because of the facades

**Comment by kacperknapik** [comment]
awaits #263

**Comment by kacperknapik** [comment]
Waiting for #791

**Comment by kacperknapik** [comment]
Billing address functionality was successfully created. I separated some small things to do regarding billing address in #791. This ticket - after merging, can be closed.

**Comment by Xymmer** [comment]
tested on github.io 
it all seems to work except the special handling of state/province (region in occ) is not shown.
putting back into to do

**Comment by Xymmer** [comment]
we concluded we need a backend change before we put the region back. closing this one.
