### ISSUE TITLE
In storefront, implement top-right links as cms (after 352 is merged)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#935]
Depends on #352.
(Original ticket is #353. To avoid being held up, Tobias created a workaround. Have to undo his work.)

Otherwise the task is to:
- Replace Sale/Contactus/Help with the cms equivalents. (Find a store already works.)
- Remove hardcoded selectors currently there.
- Create a page for each link (sale, contact us, help).

Acceptance criteria:
- Can see the  links in same place in Spartacus.'
- Clicking the links opens the correct page and displays the dummy text we pulled from cms.

**Comment by bgambocjaviniar** [comment]
PR #1257

**Comment by WeizhengSap** [comment]
It's better we can add some dummy text in the page.

**Comment by WeizhengSap** [comment]
Where is your backend PR?

**Comment by bgambocjaviniar** [comment]
PR Backend https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/16/overview
