### ISSUE TITLE
clicking on the FAQ opens a new window (intentional or not?)

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#936]
**Environment**:
SPA with yenv (develop branch)

**Steps**:
Click on the FAQ link at the bottom of the homepage

**Actual Result**
It opens a new window, with the url https://sap.github.io/faq

**Note**
Talked with Bill, and he said "Shouldn’t necessarily open a new window, create a bug for that."
Before, clicking on both the SAP logo and the FAQ, would open a new SPA window.
Now opening on the FAQ opens a new window but with a different url. So maybe it's intended. Please evaluate in the bug triage meeting.

**Comment by Xymmer** [comment]
because faq is opening a document hosted by our site, stay in same window. also, no styling was appearing, i assume it will be fixed.

**Comment by bgambocjaviniar** [comment]
It is fixed with our new routings. No longer opens  a new window in SPA
