### ISSUE TITLE
Missing number of items added to cart in 'Added to cart modal'

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#939]
![obraz](https://user-images.githubusercontent.com/4001059/51467306-8796ef00-1d6c-11e9-8f31-f90ed06775ee.png)

*Note:* Maybe it's somehow related with #918 ?

**Comment by Pucek9** [comment]
That will be no longer needful. Header is going to be updated in https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/757#issuecomment-452694498
