### ISSUE TITLE
Anonymous GDPR consent

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#965]
See RAY-214 and RAY-222 (might be duplicates). We asked how to set consent for anonymous users. Pawel says it's very complex but maybe it can be done in Spartacus. Accelerator used a cookie. We can work with Team Argos as they are developing the CDS portion.

**Comment by tobi-or-not-tobi** [comment]
@Xymmer I'm not sure about why it's complex, but I might something. I've created an umbrella ticket for token-consent-management, see #1323

**Comment by Xymmer** [comment]
dupe of #2124
