### ISSUE TITLE
Generate 'breaking changes' section in changelog

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#981]
While we are pre-1.0 version I don't think we need 'Breaking changes' section in release changelog. But when we upgrade the major version from 1.0 to 2.0 in future, such a script to generate a list of breaking changes from commits may be helpful. 

**Note:** Regarding our [Commit Guidelines](https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/contributing/commit-guidelines.md), when the commit (PR) introduces breaking changes, it should highlight them in commit message's footer using `BREAKING CHANGES: ` section.

**Comment by Xymmer** [comment]
checking if this is a dupe of 1674

**Comment by Platonn** [comment]
Yes, it's duplicate of #1674
