### ISSUE TITLE
Configurable home page layout

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#982]
We like to leverage configurable layouts, introduced with #907. 

- use configurable layouts
- move page template styles to style lib
- reduce homepage module to generic route config

**Comment by tobi-or-not-tobi** [comment]
**QA Steps**
- Create / change content in the homepage
- experiment with changing the homepage to use the ContentPage1Template. The template isn't necessary prepared for it, but the content should show up

**Comment by LTiger14** [comment]
Passed QA
