### ISSUE TITLE
New backend component "FlexCmsComponent" to replace JSP component

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#986]
Add new type of component-for-angular in sample data, replace all JSP includes with this one.
**FlexCmsComponent** to extend form simplecmscomponent
1 attribute: selector (string)

Not dependent on #893 

storefront work is in #1270

**Comment by Xymmer** [comment]
we said we can wait until week of 18th but account profile may depend on this

**Comment by WeizhengSap** [comment]
We will use the name "FlexCmsComponent" now.

**Comment by WeizhengSap** [comment]
PR is here: https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/pull-requests/15/overview

**Comment by WeizhengSap** [comment]
After build and initialize, you should be able to see the FlexCmsComponent in e.g. LoginPage
![screen shot 2019-02-08 at 10 42 37 am](https://user-images.githubusercontent.com/44440575/52489209-aaf4d300-2b8f-11e9-9af6-e26b74069188.png)

**Comment by WeizhengSap** [comment]
We have 2 forms in the old acc: return customer login and new customer login. In SPA, we only use one. So, we will move one component to another page. But, it is not in the scope of this ticket.
![screen shot 2019-02-08 at 10 55 21 am](https://user-images.githubusercontent.com/44440575/52489362-1179f100-2b90-11e9-80e7-c1c470de4639.png)
