### ISSUE TITLE
Add outlets to page layout component

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#989]
In order to override page templates we can leverage outlets, so that customers can override or append content to existing page templates.

**Comment by tobi-or-not-tobi** [comment]
**QA Steps**
- create an `ng-template` with a cxOutletRef, and assign it to a page template uid (i.e. `LandingPage2Template`) (can be done in `storefront.component.html`)
- confirm that the custom content shows up in Spartacus
- use before or after as alternatives

**Comment by LTiger14** [comment]
Works as intended. One qualm I noticed while QAing it that certain outlets have the same name. For example, `Section2A` is present in both the home page and the help/faq page. Therefore, injecting content into this outlet will render it in both pages.

**Comment by tobi-or-not-tobi** [comment]
> Works as intended. One qualm I noticed while QAing it that certain outlets have the same name. For example, `Section2A` is present in both the home page and the help/faq page. Therefore, injecting content into this outlet will render it in both pages. Maybe the slots should change name or there should be a follow up item for this.

Very good point! I'm about to suggest a re-config of our backend page templates (as there are too many of them for no good reason (anymore)), this is good input in that refactor.
