### ISSUE TITLE
Error when clicking "Show all stores" [also 1113]

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/cloud-commerce-spartacus-storefront#992]
In the storefinder, when clicking on "Show all stores" we do not see all of the stores being shown.

**Comment by Matejk00** [comment]
Until the 'model-t' backend version is outdated the main goal of this task is to refactor all storefinder component to work with up-to-date backend version instance. As a result we fix all console errors and endpoint name problems.

**Comment by Xymmer** [comment]
are #1113 and #992 same issue?

**Comment by Xymmer** [comment]
as of feb8, View all Stores does show Japan link, but then clicking Japan link doesn't work. (see #1113)

**Comment by marlass** [comment]
✔️ View all stores link works. Shows all Japanese shops after clicking "Japan"
